### ISSUE TITLE
[NPC] [Wailing Caverns] Deviate Faerie Dragon

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1296] opened 2014-02-28 15:15 UTC
Deviate Faerie Dragon (http://wotlk.openwow.com/npc=5912) is supposed to appear only sometimes in Wailing Caverns. Right now he appears all the time.

According to http://www.wowwiki.com/Wailing_Caverns, "The Deviate Faerie Dragon is a rare mob you may encounter in this area. Not difficult, drops nice caster gear, but appears rarely. Odds are good that you will never see him unless you enter the instance repeatedly to hunt for him."

**Comment by Demlock** [comment] 2015-02-19 17:52
Confirmed, he does...

**Comment by Rushor** [comment] 2016-11-14 14:01
DB/Creature: Despawn Deviate Faerie Dragon for 85 percent

* closes https://github.com/dalaranwow/dalaran-wow/issues/1296
* this means that the Deviate Faerie Dragon will only appear for 15 % in the instance

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 14:01 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 18:40
Works as intended on ptr.
