### ISSUE TITLE
NPC- Shadowstalker Luther Quest- Untold Truths (Vital for Borean Tundra leveling)

### ISSUE THREAD

**Issue by Arrowzinger** [dalaranwow/dalaran-wow#2764] opened 2015-08-06 17:05 UTC
The Quest- Untold Truths (Borean Tundra, outside of Warsong Hold) is to find Shadowstalker Luther, you are supposed to find his body. Located (40,52) however, it is not there. If you look at the images he isn't where he's supposed to be and the next image shows where the map says he is, so I think he is under the ground. This is on the Main Server- Algalon.
![wowscrnshot_080615_125905](https://cloud.githubusercontent.com/assets/13681885/9117977/a0e2f776-3c3b-11e5-9373-b4901fd6a4c5.jpg)
![wowscrnshot_080615_130134](https://cloud.githubusercontent.com/assets/13681885/9117982/a4e1e3d2-3c3b-11e5-8d3f-fad4abd07df0.jpg)

**Comment by Jasminaria** [comment] 2015-08-06 21:18
Confirmed, He does not appear on screen and mini map does not show "?" icon to indicate quest turn in is there.  Noticed a lot of players flying through area and hovering over his spot looking for him as well.

**Comment by Golganeth** [comment] 2015-08-07 12:15
That's quite odd. The NPC is perfectly fine right now. This looks like a rare pathfinding issue which isn't directly related with the quest/NPC itself, so closing up for now. Feedback is welcome though.

![image](https://cloud.githubusercontent.com/assets/5057942/9135523/be9b65f4-3d0e-11e5-9505-74a24b3ebc09.png)

**Closed** 2015-08-07 12:15 UTC

**Comment by Arrowzinger** [comment] 2015-08-07 17:46
Still not there. What do I need to do to get this quest turned in?

**Comment by Brothus** [comment] 2015-08-07 19:36
Tried to do it yesterday and nope, checked today and still, he is not there   
 This is where it says he is, I used /target macro to put an icon on him
![luther 2](https://cloud.githubusercontent.com/assets/13699022/9144201/4406bf18-3d00-11e5-8b67-60fc8a2b50da.png)
This is where he is supposed to be
![luther](https://cloud.githubusercontent.com/assets/13699022/9144114/b20320ca-3cff-11e5-9118-7b1f4fa080e6.png) 

I saw the icon once, and it was under the terrain, in the place the game says he is, so apparently he is stuck in there
