### ISSUE TITLE
Buffs on BGs

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#3698] opened 2016-09-06 14:53 UTC
**Description**: If you are stealthed it is impossible to take a buff on BGs you walk over it and it just disappers

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) Cannot pick up buffs on BGs while stealthed.

**Expected behaviour**: Tell us what should happen instead You can pick up buffs on BGs even though you are stealthed.

**Steps to reproduce the problem**:
1. Enter bg on rogue/druid
2. Use stealth
3. Try to pick up buff

**Comment by Jokey123** [comment] 2016-09-07 11:18
I tested this on PTR and here are my conclusions:
- Speed Buff: When I walked over it with stealth, 80% of the times I received the buff, but it broke my stealth. In the other 20% of the times, the buffs were gone and nothing happened.
- Berserking: I was never able to receive this buff while in stealth. It just disappears, it doesn't break my stealth.
- Healing Buff: Same as Berserking, I never received it. 

But, I'd like to ask if this is how it was in WotLK, are you sure that you'd be able to receive the buff while stealthed? If so, does it break your stealth or no?

**Comment by Jiaku** [comment] 2016-09-07 12:20
I'm pretty confident to say that you should be able to pick up BG buffs and stay stealthed, otherwise it doesn't make sence.

**Comment by Rushor** [comment] 2016-11-12 17:38
Core/Spells: Spellhandling from gameobjects.

Gameobjects no longer require the target to be visible for itself,
this is a general implemention of an already fixed bug with buffs disapperaing randomly in battlegrounds.

NOTE: Gameobject casts are mainly casted with a World Trigger

* closes https://github.com/dalaranwow/dalaran-wow/issues/3698
* commit: 07bf102cf821a997be928d69a106c11c628ca1a3

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-03-31 12:54
Regarding that sometimes you don't get the buff when you walk over it, it seems fixed on ptr.
However taking the buff sometimes takes the rogue out of stealth, depends on the angle of which the player approach the buff (strange i know).
Video from ptr regarding how to reproduce this issue:
https://www.youtube.com/watch?v=sVWAsf1atYQ&feature=youtu.be

P.S. It's the same for all BG buffs like those.

**Comment by Rushor** [comment] 2017-07-04 10:47
Alright i removed my fix and applied the one from tc instead https://github.com/TrinityCore/TrinityCore/commit/b3a4815067d154fb35da87aa8e7365995d6f65f5 which should fix the mentioned issues properly.

Core/Spells: workaround stealth interaction with Death and Decay and GameObject casts

* closes: https://github.com/dalaranwow/dalaran-wow/issues/3698
* commit: 70d6de0d58709239408b9065afb64c8c5ffef0b0

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-04 10:47 UTC
Labels: Class - Druid, Class - Rogue, General - Mechanics, Priority - High

**Comment by robinsch** [comment] 2017-10-19 12:07
@TeridanDW Could you test if this is still valid, maybe my trap fix also fixed this issue.

**Comment by TeridanDW** [comment] 2017-10-23 12:39
Quick update here:

> All buffs are not invisible to players (issue 2):

Fixed.

**Comment by Aridam** [comment] 2018-05-23 18:49
Relateable issue: If you try to pick a Buff up (in my case it was Berserking) while behind thin LoS (like the cart at the Gold Mine), it will disappear, but not be applied to you -- just-had it happen to me as I picked it up from the cart's thin source of LoS, but the Buff wasn't actually applied to me, so it was simply wasted.

**Comment by Jiaku** [comment] 2018-05-23 22:15
Yes it happens there all the time, not just with berserking, all of them.

**Comment by Rushor** [comment] 2018-06-05 09:18
Already on PTR.
