### ISSUE TITLE
[NPC] Netherock

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1931] opened 2014-10-02 15:20 UTC
http://www.wowhead.com/npc=20772

This elite mountain giant that wanders southern Netherstorm currently is missing his script that should be assigned to him.

1) At 75%, 50% and 25% of Netherock's health, a hostile Netherock Crumbler (http://www.wowhead.com/npc=21323) should spawn near him and engage the player(s) that attack Netherock. When either Netherock or all engaged players die, all Crumblers should despawn.

Also Netherock should be immune to all kind of slows and snares, this must be double-checked.

**Comment by Rushor** [comment] 2016-11-12 17:53
DB/Creature: Implement SAI for Netherock

* closes https://github.com/dalaranwow/dalaran-wow/issues/1931
* commit: 64a4a2d877fa19683c2166e6807294bd3cf616a1

![GitHub Logo](http://i.imgur.com/Yzs8nkr.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 07:42
Creature http://www.wowhead.com/npc=20772/netherock#comments does summon his adds correctly now, however they don't despawn on evade and netherock is not immune to all movement impairing effects (roots/frost nova worked on him).
Proof:

> By Ventile (877 – 2·4) on 2007/02/05 (Patch 2.0.6)		
> He's immune to movement impairing effects.

``` sql
-- Netherock Crumbler SAI
SET @ENTRY := 21323;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,7,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Netherock Crumbler - On Evade - Despawn Instant");
```
and maybe add on spawn assist for Netherock Crumbler to Netherock  (not sure how this is done).

**Comment by Rushor** [comment] 2018-03-28 13:06
fixed by https://github.com/dalaranwow/principal/commit/b917697d0c7d07e5574852956da222f0f169b285

**Closed by Rushor** 2018-03-28 13:06 UTC
Labels: Area - Outland
