### ISSUE TITLE
[Quest] Dailys don't give Exp

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#2964] opened 2015-10-20 14:08 UTC
As the title mentioned, certain dailies don't give Exp.
What I mean by "dailies with conditions" are dailies that require something special to be available, other than level/rep, so like the Dalaran Jewelcrafting daily (requires JC425), or the dailies for Hallowed End (requires Hallowed End event). While the quest completion screen does say it grants Exp, they don't.
https://gyazo.com/d79bd53de53f06cb2400ebca60ac555c
(And no, I don't have my Exp locked)

**Comment by swiftdeath** [comment] 2015-10-22 10:45
I have seen the same issue appear while levelling Wuotan, my DK on Algalon. Specifically the KAlu'ak dailies in HF, DB and BT

**Comment by Rushor** [comment] 2016-11-10 11:43
Game/Player: Implement QUEST_FLAGS_ALWAYS_XP which enables XP for daily quests if the player didn't reached maxlevel

* closes https://github.com/dalaranwow/dalaran-wow/issues/2964
* commit: c3f09aedc846f41a4649a7b910eb947b7c8e8831

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment] 2016-11-10 11:43
this affects these quests:

-- Daily Quest Flag
11691, 11924, 11925, 11921, 11926, 11917, 11917, 11948, 11952, 11953, 11954,
12958,
12959,
12960,
12961,
12962,
12963,
11391,
11940,
11945,
11960,
12038,
12170,
12244,
12268,
12270,
12280,
12284,
12288,
12289,
12296,
12314,
12315,
12316,
12317,
12323,
12324,
12372,
12432,
12437,
12444,
12501,
12502,
12509,
12519,
12541,
12563,
12564,
12568,
12582,
12585,
12587,
12588,
12591,
12594,
12601,
12602,
12604,
12689,
12702,
12703,
12704,
12705,
12726,
12732,
12734,
12735,
12736,
12737,
12741,
12758,
12759,
12760,
12761,
12762,
12813,
12815,
12833,
12838,
12869,
12977,
12981,
12994,
12995,
13003,
13006,
13046,
13069,
13071,
13233,
13234,
13261,
13276,
13280,
13281,
13283,
13284,
13289,
13292,
13297,
13300,
13301,
13302,
13309,
13310,
13322,
13323,
13330,
13331,
13333,
13336,
13344,
13350,
13353,
13357,
13365,
13368,
13376,
13382,
13404,
13406,
13414,
13422,
13423,
13424,
13425,
-- argetumquests
13592,
13600,
13603,
13616,
13625,
13627,
13665,
13666,
13669,
13670,
13671,
13673,
13674,
13675,
13676,
13677,
13681,
13682,
13741,
13742,
13743,
13744,
13745,
13746,
13747,
13748,
13749,
13750,
13752,
13753,
13754,
13755,
13756,
13757,
13758,
13759,
13760,
13761,
13762,
13763,
13764,
13765,
13767,
13768,
13769,
13770,
13771,
13772,
13773,
13774,
13775,
13776,
13777,
13778,
13779,
13780,
13781,
13782,
13783,
13784,
13785,
13786,
13787,
13788,
13789,
13790,
13791,
13793,
13809,
13810,
13811,
13812,
13813,
13814,
13847,
13851,
13852,
13854,
13855,
13856,
13857,
13858,
13859,
13860,
13861,
13862,
13863,
13864,
14074,
14076,
14077,
14080,
14090,
14092,
14095,
14096,
14101,
14104,
14107,
14112,
14140,
14142,
14143,
14144,
14145,
14152,
-- bc
10106,
10110,
11080,
11076,
11055,
11018,
11017,
11016,
11015,
11008,
11020,
11023,
11035,
11051,
11066,
11077,
11085,
11086,
11097,
11101,
11502,
11503,
11513,
11514,
11515,
11516,
11520,
11521,
11544,
11875,
11877,
11880,
11496,
11523,
11524,
11525,
11532,
11533,
11535,
11536,
11537,
11538,
11539,
11540,
11541,
11542,
11543,
11546,
11547,
11691,
11917,
11947,
11948,
11952,
11953,
11954,
14488,
11377,
11379,
11380,
11381,
13692,
11364,
11371,
11376,
11383,
11385,
11387,
11389,
11500,
11354,
11362,
11363,
11368,
11369,
11370,
11372,
11373,
11374,
11375,
11378,
11382,
11384,
11386,
11388,
11499);

**Closed by Rushor** 2016-11-10 11:43 UTC
Labels: Continent - Northrend, Quests
