### ISSUE TITLE
[Item] Shadowmourne Soul Fragment Proc Chance

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#4852] opened 2017-08-20 12:12 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Soul Fragments from the Shadowmourne proc are currently not proccing as much as they should. Their proc chance seems to be about less than half then what it should be.

**Expected behaviour**: Soul Fragments should proc more often. I have found a video back from retail WotLK and made a side-by-side comparison of the procs. I linked it below.

**Steps to reproduce the problem**:

1. Get Shadowmourne
2. Observe how slow Soul Fragments can be stacked up on Dalaran

**Include proofs for this behaviour**

Live Server: https://youtu.be/1xHkAIYD9qY?t=3m54s
Dalaran WoW: https://www.youtube.com/watch?v=VwCeDp8Rocg (not even a single Chaos Bane proc)

You can see on this retail log here that Soul Fragments are stacked up insanely fast on a retail unholy DK:
![image](https://user-images.githubusercontent.com/4272703/29499316-864bc220-860e-11e7-93a4-b32bc8c1f7ff.png)

Here is a link to the log (retail 2010): http://www.worldoflogs.com/reports/5ci4g3tsubth9gz2/log/?s=2428&e=2971

This is a log from our raid for comparison:
![image](https://user-images.githubusercontent.com/4272703/29499309-70999330-860e-11e7-9be9-0863ca477c8b.png)

Back on retail, people used cancelaura macros for Chaos Bane, because the Soul Fragments would stack up so insanely fast that it would be a dps gain to just collect new fragments instead of having the Chaos Bane buff. With the current proc chance on Dalaran this would be a big loss instead of a dps gain.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by tripleslash** [comment] 2017-08-20 12:34
Will update once I got a log parse from our raid.

**Comment by Rushor** [comment] 2017-08-21 06:57
yes currently the proccchance is 20% but it should be 100%.

sources: http://forums.elitistjerks.com/topic/88411-shadowmourne/page-8 http://wowwiki.wikia.com/Shadowmourne 

and:

**Comment by Rushor** [comment] 2017-08-21 07:00
DB/Item: Shadowmourne - Enable 100 percent proccchance

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4852
* commit: 868579028c2f1491f59bcc3b030b119a91c63fcb

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-08-21 07:00 UTC
Labels: General - Items

**Comment by TeridanDW** [comment] 2017-10-23 12:58
Works as intended on PTR.
