### ISSUE TITLE
[Quest][Borean Tundra] Report to Steeljaw's Caravan

### ISSUE THREAD

**Issue by sifiuocz** [dalaranwow/dalaran-wow#2601] opened 2015-07-05 19:16 UTC
link: http://wotlk.openwow.com/quest=11591
You are supposed to speak with Grunt Ragefist (link: http://wotlk.openwow.com/npc=25336), but you can't click on her. It doesn't work properly for me atleast.

**Comment by Furminator** [comment] 2015-07-05 20:45
The quest itself works, the problem is that the npcs near the Caravan gets stuck after someone already completed the quest We Strike Back (I think its called). There are a few solutions to this problem at the moment:

* Get a GM to reset the NPCs
* Have a member of the Alliance (If you know any) kill the NPCs and wait for them to respawn
* Try pulling a few mobs near the NPCs and they get in combat, keep chainpulling till they all die and wait for the respawn

**Comment by sifiuocz** [comment] 2015-07-05 20:59
That explains why is this NPC is buggy as much. Alrighty, thanks.

**Comment by VonKaufmann** [comment] 2016-04-06 16:33
Still bugged. Two more in a long line of quest chains in BT unavailable/broken.

**Comment by Rushor** [comment] 2016-11-25 12:43
reason for the bug:
if you start the quest "We Strike Back" Grunt Ragefist will remove his questflag and start following. once the eskortquest is completed and Grunt Ragefist is respawned, she will not add here questflag back.

**Comment by Rushor** [comment] 2016-11-25 12:45
DB/Quest: Report to Steeljaw's Caravan -  Grunt Ragefist - Readd questgiverflag after respawn

* closes https://github.com/dalaranwow/dalaran-wow/issues/2601
* commit: 27f3d9fb1f5c054f970814535e391283de3f28d1

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 12:45 UTC
Labels: Continent - Northrend, On PTR, Quests
