### ISSUE TITLE
[NPC][Ulduar] 2 Algalons exist in a single encounter

### ISSUE THREAD

**Issue by Sartorios** [dalaranwow/dalaran-wow#3637] opened 2016-08-06 11:11 UTC
**Description**:
whenever we initiate the one hour countdown( after unlocking the door ) of Algalon the observer, there will be another algalon that spawns in the middle of the room in which he can be pulled by any slight mistake.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
This bug happens in ulduar encounter ; Algalon the observer. when we pull Algalon, another algalon exists in the same place.
**Expected behaviour**: Tell us what should happen instead
only 1 Algalon should exist at a single encounter
**Steps to reproduce the problem**:
1. unlock the door of Algalon the observer.
2. pull the first algalon.
3. pull the 2nd algalon in the same attempt.

**Comment by plznoz** [comment] 2016-08-06 20:32
Happens when you press the door panel more than once.

**Comment by Sartorios** [comment] 2016-08-07 06:25
even if u press it once , it still happens

**Comment by plznoz** [comment] 2016-08-07 06:50
Then someone but you would have had to pressed once aswell. This bug has been around since forever.

**Comment by Tarpor** [comment] 2016-08-07 10:59
Did they both spawn coming from above, or was 1 already standing there? As far as I am aware the clicking fast does not work. But it occurs sometimes (randomly, I'm not sure what causes it) that one is already standing there, and when you press the switch another one spawns, as it's supposed to. But the one standing there shouldn't be there.

**Comment by plznoz** [comment] 2016-08-07 11:00
But most of the time the door is already open then?

**Comment by Tarpor** [comment] 2016-08-07 11:01
The door is closed, there is already 1 Algalon due to an unknown reason (this is the issue). You open the door, another one spawns because you opened the door, you now have 2 Algalons.

**Comment by Rushor** [comment] 2016-11-14 10:33
Scripts/Ulduar: Prevent multiple summon of Algalon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3637
* if there are more than one algalon in the instance, it will be unsommoned (this **also** fixes the issue with multiple summon which is a result of spamming the door panel)
* commit: d488d45dc79926ffbaa8c760a19c105d35d59f9f

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 10:33 UTC
Labels: Instances, On PTR

**Comment by TeridanDW** [comment] 2017-03-31 17:51
Spamclicking still triggers 2 or more events, however there can't be more than 1 Algalon up now, BUT we still can enjoy the double brann spam :)

![image](https://cloud.githubusercontent.com/assets/6797611/24562261/d5e79dbc-1652-11e7-90cf-5e6c0f1f5631.png)
