### ISSUE TITLE
[Instances/Bosses] Twin Val'kyrs - encounter in progress

### ISSUE THREAD

**Issue by wilczakadam** [dalaranwow/dalaran-wow#3099] opened 2016-01-18 19:26 UTC
If you wipe on Twin Val'kyrs in ToC10 (and maybe 25, didn't try yet) there is a big chance you won't be able to enter the instance again, it will keep telling you that "Enocunter is in progress". Only server crash can fix it. It is a terrible inconvenience for raiders, please look into it.

**Comment by Crispybuilt** [comment] 2016-01-18 23:43
The reason this happens is because players release way too fast and nobody is left inside the instance while the Val'kyrs are reseting. You have to wait for them to walk through the door and disappear. Otherwise, if nobody is inside the instance while they are doing that, the server won't register a proper reset and it will glitch out the instance.

**Comment by wilczakadam** [comment] 2016-01-19 09:54
Still - it is a bug and should not be happening. The bosses should reset no matter how fast we release.

**Comment by Lukas45** [comment] 2016-01-19 12:27
True it shouldn't be happening, but what Crispy said is the best way to avoid it from happening - aslong as just one person stays inside while they reset and it wont bug.
But I have a feeling it can take a long time to fix *cough Hodir*

**Comment by Kchekrik** [comment] 2016-01-25 13:07
When you see the gate opening as the twins are leaving the arena, then its safe to release, and thats also the same time when you can enter again.

**Comment by Rushor** [comment] 2016-11-17 18:58
Scripts/TrialOfTheCrusader: Twin Valkyr - set them active

* with this change, the creatures will also reset, if there is no living player in the instance
* closes https://github.com/dalaranwow/dalaran-wow/issues/3099
* commit: 2f168804be1b6b37ce35c26b68027d8a1a1fab1d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 18:58 UTC
Labels: Instances, On PTR
