### ISSUE TITLE
[Quest][Classic] Lokhtos Darkbargainer quests

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4707] opened 2017-05-12 17:28 UTC
**Current behaviour**: Currently Lokhtos Darkbargainer does not offer you the 5 repeatable quests for the Thorium Brotherhood faction if you are in Neutral standings with them.

**Expected behaviour**: Lokhtos Darkbargainer should offer you the 5 repeatable quests from Neutral.

**Steps to reproduce the problem**:

1. Go to brd
2. Talk to Lokhtos Darkbargainer when you are Neutral with the Thorium Brotherhood.
3. Notice that he doesn't offer you any quests.

http://www.wowhead.com/faction=59/thorium-brotherhood
http://www.wowhead.com/npc=12944/lokhtos-darkbargainer
http://wowwiki.wikia.com/wiki/Thorium_Brotherhood?oldid=2395248

**Comment by TeridanDW** [comment] 2017-05-14 08:23
Hello @Klala , thank you for the report.
After a short investigation I found that these quests are currently ingame and working, however they are offered when the player is _honored_ with Thorium Brotherhood.
These 5 quests:
[Favor Amongst the Brotherhood, Core Leather - ID: 6645](http://www.wowhead.com/quest=6645/favor-amongst-the-brotherhood-core-leather)
[Favor Amongst the Brotherhood, Blood of the Mountain - ID: 6646](http://www.wowhead.com/quest=6646/favor-amongst-the-brotherhood-blood-of-the-mountain)
[Favor Amongst the Brotherhood, Fiery Core - ID: 6643](http://www.wowhead.com/quest=6643/favor-amongst-the-brotherhood-fiery-core)
[Favor Amongst the Brotherhood, Lava Core - ID: 6644](http://www.wowhead.com/quest=6644/favor-amongst-the-brotherhood-lava-core)
[Favor Amongst the Brotherhood, Dark Iron Ore - ID: 6642](http://www.wowhead.com/quest=6642/favor-amongst-the-brotherhood-dark-iron-ore)
should be offered to players when they are **Neutral** with Thorium Brotherhood.
Proof:

> By nomadicdruid (4,788 – 18·59) on 2009/06/08 (Patch 3.1.3)		
> I don't know if this was new at some point, but you can turn in the quests inside BRD any any rep level. So with the going prices, from neutral to friendly is far cheaper if you buy (or farm) fiery core, lava core, and core leather. I paid 10g for 2 cores, and 50 for 2 more. I also paid 5g per core leather. To compare to the cheapest I found, 10 heavy leather for 5g. At that price, I'd have to buy 20 stacks (100g) to get the 500 rep I got by purchasing the cores.

You can find more proofs here: [Thorium Brotherhood](http://www.wowhead.com/faction=59/thorium-brotherhood)
I have also checked the reputation rewards from these 5 quests and they are correct (the wrath values).

Fix for this issue, tested and working:
``` sql
UPDATE `quest_template_addon` SET `RequiredMinRepValue` = 0 WHERE `ID` BETWEEN 6642 AND 6646; 
```

**Comment by TeridanDW** [comment] 2017-05-14 08:42
While I was testing some of these quests I found an issue with quest [Gaining Acceptance - ID: 13662](http://www.wowhead.com/quest=13662/gaining-acceptance):
 - quest is not repeatable
 - quest does not have max reputation cap (when this cap is reached it should not be offered anymore)

Proof - http://wowwiki.wikia.com/wiki/Thorium_Brotherhood?oldid=2395248

Note: For a reference quest [Gaining Even More Acceptance - ID: 7737](http://www.wowhead.com/quest=7737/gaining-even-more-acceptance) works as intended.

Updated the code above with this fix also.

**Comment by Rushor** [comment] 2017-07-01 18:59
DB/Quest: Lokhtos Darkbargainer quests - Update reputationreward, faction and specialflags

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4707
* commit: 32e37522c26dec0f21d89ce53bb6425dabdfe930

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


thank you.

**Closed by Rushor** 2017-07-01 18:59 UTC
Labels: General - Quests

**Comment by TeridanDW** [comment] 2017-10-24 07:39
Works as intended on PTR.
