### ISSUE TITLE
[Quest][Northrend]"Hand of the Oracles" and "Return of the Friendly Dryskin"

### ISSUE THREAD

**Issue by Craftymind** [dalaranwow/dalaran-wow#4660] opened 2017-04-08 13:29 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Hello,

I was told to make a video about the bug that's happening in the last section of the chain quest to unlock the Oracles dailies. So here it is. All what you need to know is in this video. I tried to show everything related to this bug, and explain it as much as possible, to allow the Devs a better understanding of what's exactly happening.

https://www.youtube.com/watch?v=JUB5Pm-Hbuk

Here are the links for the respective NPC and quests:
Jaloot: http://www.wowhead.com/npc=28667/jaloot
Hand of the Oracles: http://www.wowhead.com/quest=12689/hand-of-the-oracles
Return of the Friendly Dryskin: http://www.wowhead.com/quest=12695/return-of-the-friendly-dryskin

And here you can find all of the chain quests leading to unlock the dailies:
http://wowwiki.wikia.com/wiki/Quest:Return_of_the_Friendly_Dryskin
http://www.wowhead.com/quest=12695/return-of-the-friendly-dryskin#comments

I'm hoping for a quick response for my ticket in-game as well.

**Comment by TeridanDW** [comment] 2017-04-08 16:00
Hello, thank you for the report and the video @Craftymind .
Regarding the issues you mentioned - most of them are fixed in #3507 however they are not applied on live realms yet. 
 - For the fight with http://www.wowhead.com/npc=28659/artruis-the-heartless there is indeed an issue with the normal(when you choose faction for the first time) and daily(when you decide to switch faction) quests are not offered by the creature you choose to aid. That is server-side issue and it's already fixed by @Rushor in #3507:

> DB/Quest: Sholazar Basin: Oracles/Frenzyheart switch-quest can now be done multiple times

 - For the respawning issue you are right, they are suppose to spawn at the same time together with Artruis, that can be fixed by increased the respawn timers of the 2 creatures next to him by a lot and adding linked respawn behaviour with Arthuis (so when he spawned the 2 creatures next to him will be "forced" to spawn/respawn. I will add this issue to #3507 
 - For the issue with the quest not been registered as you said:

> Also, the 1st quest mentioned ( http://www.wowhead.com/quest=12689/hand-of-the-oracles ) seems to have not registered as completed

 You are using an addon and if the issue is related to him we can't really do anything as it's not a server-side issue. That's why we often ask when people test something to test without addons so they get "pure" data without any addon related errors that can mislead everyone.

Regarding:

> I'm hoping for a quick response for my ticket in-game as well.

Making an ingame ticket and providing as much as possible information for your issue(there) will be the best course of action. I would suggest to add links to the quests you need in order to proceed with the faction you choose.

So merging this report with #3507 and we can continue the topic there.

**Closed by TeridanDW** 2017-04-08 16:00 UTC

**Comment by Lothloryen** [comment] 2017-05-02 04:20
Hello there,

This issue should be corrected after the next realm restart.

Thank you.
