### ISSUE TITLE
[Quest][Northrend] The Cleansing

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2522] opened 2015-06-15 14:05 UTC
After killing 'your inner turmoil' one should get a buff that works like slow fall. name and description of this was: Soul lightened, cleansed your inner turmoil (or something like that). This buff is missing.
The Cleansing Quest id:
http://wotlk.openwow.com/quest=11317

Possible id for this aura (im not sure about this):
http://wotlk.openwow.com/spell=50238

**Comment by TheFidlar** [comment] 2015-11-04 06:19
Confirmed. Player meditates (with buff [10seconds]) and 'your inner turmoil' spawns. Kill him after a few seconds pause and no completion.

**Comment by Rushor** [comment] 2016-11-26 21:28
DB/Quest: The Cleansing - Add 'Slow Fall' on death of Your Inner Turmoil

* closes https://github.com/dalaranwow/dalaran-wow/issues/2522
* commit: 07a5c66d64dca565bb410b9953390c4a5cb7d428

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 21:28 UTC
Labels: Continent - Northrend, On PTR, Quests
