### ISSUE TITLE
[Quest][Northrend] Hah ... You're Not So Big Now!  11653

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#706] opened 2013-08-28 14:34 UTC
http://www.wowhead.com/quest=11653
When  using the quest item http://www.wowhead.com/item=34812 on one of these NPCs http://www.wowhead.com/npc=25432 and http://www.wowhead.com/npc=25434 - no account credit after killing it.

**Comment by trincore** [comment] 2015-02-20 22:22
Confirm, not working as intended, but still doable.
You need to look for Magmoth Crusher mobs around. Use Crafty's Ultra-Advanced Proto-Typical Shortening Blaster on that mob till he have any of debuffs (need one debuff) and then kill it. After killing, credit is given. My rate - 6 mobs for 5 credits. Completed with paladin.

**Comment by n-ghost** [comment] 2015-03-18 04:56
This thing has a good chance to crash client as of lately.

Use blaster on Magmot Crusher, apply some random effect on it, when it dies, loot. Crash seems to occur as soon as loot window is being closed.

**Comment by Sagrath** [comment] 2016-05-30 20:30
Quest is working,

**Comment by Xandriarn** [comment] 2017-03-28 18:01
The use of Crafty's Ultra-Advanced Proto-Typical Shortening Blaster puts a debuff on both the mob AND the player. If the mob is killed before the player's debuff (18 seconds) wears off, no credit is given no matter what debuffs are on the mob. 

I checked on wowhead (http://www.wowhead.com/quest=11653/hah-youre-not-so-big-now) and none of the information there or anything in the comments mention anything about having to wait for your debuff to drop for credit.

**Comment by TeridanDW** [comment] 2017-03-29 08:22
Hello. Thank you @Xandriarn  for the report.
I can confirm that there is an issue with quest credit not been granted everytime, however this:

> If the mob is killed before the player's debuff (18 seconds) wears off, no credit is given no matter what debuffs are on the mob.

is only part of the problem. Sometimes I got the credit while having the debuff, sometimes i didn't.
Video from PTR:
https://www.youtube.com/watch?v=uIRjpu75wG0&feature=youtu.be

**Comment by Rushor** [comment] 2017-03-29 17:17
issues:

- 25432 has not the coreai for the questreward
- there is a 50% chance to not reward the buff. This is guessed value, not blizzlike and should be removed
- one killcredit aura check for spell 45683 is missing
- triggered flag for the spell should be removed in order to prevent client crash

**Comment by Rushor** [comment] 2017-03-29 17:50
Scripts/Northrend: Borean Tundra: Hah... You're Not So Big Now! - Improvements

* assign corescript to creature: 25432 in order to load questscript
* remove 50 perecent rollchance for questcredit (credit should always be rewarded
* remove triggered flag from spells: 45668 and 51912 (Crafty's Ultra-Advanced Proto-Typical Shortening Blaster)
* add questcreditcheck for one missing aura: 45683 (Polymorph: Crafty Wobblesprocket)
* closes: https://github.com/dalaranwow/dalaran-wow/issues/706
* commit: 03d7580b098ec8a7ab535c6d29c704707e7a7a5c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-29 17:50 UTC
Labels: Area - Northrend, General - Quests
