### ISSUE TITLE
[Mechanic] Zeppelin Masters won't show zeppelin locations.

### ISSUE THREAD

**Issue by Aporis** [dalaranwow/dalaran-wow#3102] opened 2016-01-21 20:30 UTC
For example. The Zeppelin Master from Orgrimmar to Undercity called "Frezza"
If you ask him about the location of the Zeppelin, he won't reply at all, nothing actually happens if you click the dialog choice. "Where is the zeppelin now?"

**Comment by Sagrath** [comment] 2016-05-17 22:16
Confirmed

**Comment by Rushor** [comment] 2016-12-01 14:12
Scripts/World: Zeppelin Master - Implement "Where is the zeppelin now?" options

* closes https://github.com/dalaranwow/dalaran-wow/issues/3102
* depending on the location of the zeppelin, the zeppelin master will now show different options
* commit: 57e863bac9708dc2af5c3f1b15ccd55bc8618c40

![GitHub Logo](http://i.imgur.com/MnfEkxt.jpg)
![GitHub Logo](http://i.imgur.com/ubj2AD4.jpg)
![GitHub Logo](http://i.imgur.com/Y78mOzQ.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-01 14:12 UTC
Labels: Fixed - Waiting for PTR Update, General - Mechanics

**Comment by TeridanDW** [comment] 2017-11-09 18:57
Works as intended on PTR.
