### ISSUE TITLE
Stasis Chambers of the Mana-Tombs

### ISSUE THREAD

**Issue by Fundalicious** [dalaranwow/dalaran-wow#3727] opened 2016-09-26 10:25 UTC
**Description**: The Quest: Stasis Chambers of the Mana-Tombs is not completable, as the stasis chamber is not spawned.

**Current behaviour**: The stasis chamber, that should be in the room of Nexus-Prince Shaffar is not spawned on heroic Mana-Tombs, thus the quest cannot be completed.

**Expected behaviour**: A Stasis Chamber should be spawned. This can be unlocked with Mana-Tombs Stasis Chamber Key, provided by the quest and a boss will spawn "Yor". Killing him should trigger the quest to complete.

**Steps to reproduce the problem**:
1. Gain revered status with Consortium
2. Complete the long quest chain up to Stasis Chambers of the Mana-Tombs
3. Enter Mana-Tombs heroic

**Include proofs for this behaviour**

Proof is seen on the screenshot, as there is an absence of a stasis chamber.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=10977/stasis-chambers-of-the-mana-tombs

**Include Screenshots from the issue if necessary**

![image](https://cloud.githubusercontent.com/assets/19974824/18831033/d70ebf42-83e3-11e6-838f-ddf171ef1473.png)

PS: This is my first report of a problem, sorry if I missed anything

**Comment by robinsch** [comment] 2016-09-26 18:58
On PTR.

**Comment by Rushor** [comment] 2016-11-10 19:11
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 19:11 UTC
Labels: Continent - Outland, On PTR, Priority - Low, Quests
