### ISSUE TITLE
shapeshift bug

### ISSUE THREAD

**Issue by dakramon** [dalaranwow/dalaran-wow#3710] opened 2016-09-09 21:28 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: my rogue was shapeshifted into a pile of bones and it has not undone itself. i cant mount and i cant fly anywhere. this is affecting my game play

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by kalvindeane** [comment] 2016-09-09 22:03
If your character is having issues then you will need to create an in-game ticket for assistance. If this is a reproducible bug then please provide some more information. 

Thank you.

**Comment by Golganeth** [comment] 2016-09-09 23:27
Make an in-game ticket and your issue will be sorted out.

Duplicate of #1971.

Closed

**Closed** 2016-09-09 23:27 UTC
