### ISSUE TITLE
Maraudon NPC - Vile Larva

### ISSUE THREAD

**Issue by belegija** [dalaranwow/dalaran-wow#2826] opened 2015-08-28 00:14 UTC
In the dungeon Maraudon the NPCs [Vile Larva](http://www.wowhead.com/npc=12218/vile-larva) should not be skinnable.

**Comment by Golganeth** [comment] 2015-08-31 10:44
Couldn't find any information saying it's not an intended behavior. Closing up until source/proof is given (WoTLK, not Wowhead)

**Closed by Golganeth** 2015-08-31 10:44 UTC
