### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4783] opened 2017-07-06 17:32 UTC
Downstairs of the boat should be creatures that you kill to obtain the needed quest items

Quest: http://www.wowhead.com/quest=11527/mutiny-on-the-mercy

here is a shown video of the quest how it should be:

https://www.youtube.com/watch?v=qHPzdao_zIk

<a href="http://nl.tinypic.com?ref=2ponk12" target="_blank"><img src="http://i67.tinypic.com/2ponk12.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://nl.tinypic.com?ref=rriofa" target="_blank"><img src="http://i68.tinypic.com/rriofa.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Rushor** [comment] 2017-07-06 18:12
The issue is a duplicate of https://github.com/dalaranwow/dalaran-wow/issues/457. I will close this one, as it is not needed to report 2 times the same thing in two open tickets. Thanks.

**Closed by Rushor** 2017-07-06 18:12 UTC
