### ISSUE TITLE
[Spell] Ritual of Summoning

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#3950] opened 2016-12-09 15:54 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

This is currently bugged for both meeting stone summons and warlock ritual of summoning.

**Current behaviour**:
Summoning the same player a second time before they except the first causes the summon to fail.
https://youtu.be/twKknuJYjq0

**Expected behaviour**:
The second summon should reset the summon time to two minutes and still function when accepted within that time.

**Steps to reproduce the problem**:

1. Summon a player.
2. Summon the same player again before they accept.
3. Have the player accept the summon.
4. Witness failed summon.

**Include proof for this behaviour**
Couldn't find evidence from retail but it's common sense the summon should still work.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/spell=698
http://wotlk.openwow.com/spell=59782

**Comment by Rushor** [comment] 2016-12-09 17:10
aye fix inc.

**Comment by Rushor** [comment] 2016-12-09 17:19
Game/Player: Enable accept of summon after doubleport

* only the last summoned position should be active and acceptable
* closes https://github.com/dalaranwow/dalaran-wow/issues/3950
* commit: cb78351306c4efab18762896bdb230df230556fd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-09 17:19 UTC
Labels: Fixed - Waiting for PTR Update, General - Mechanics

**Comment by shadovvs** [comment] 2016-12-09 17:45
I am not sure if this is intended effect or not:
If you change your target during the summoning process (after somebody assisted), your last target will be summoned, not the one you had targeted when somebody clicked on the portal.

**Comment by Rushor** [comment] 2016-12-09 18:16
that issue is caused by addons like "gearscore" as far as i know.

**Comment by shadovvs** [comment] 2016-12-09 20:06
I have also tested it on s stock TrinityCore with 0 addons loaded. Maybe it is the intended behavior. Target for summon is probably chosen at the moment when the cast finishes not when someone clicks the portal.

**Comment by RandomXD** [comment] 2020-07-11 12:11
still an annoying issue
