### ISSUE TITLE
[ToC] Death Knight pet ability makes Frost Spheres unhittable

### ISSUE THREAD

**Issue by Chenocide** [dalaranwow/dalaran-wow#3659] opened 2016-08-16 09:27 UTC
**Description**:

The Death Knight pet ability "Gnaw" can make Frost Spheres in Trial of the Crusader unhittable. 

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Fighting Anub'arak in Trial of the Grand Crusader 10 and 25-man. Not sure if the issue is present in other difficulties of Trial of the Crusader.

Our current tactic is to Death Grip Frost Spheres into position. If a Death Knight has Gnaw on autocast and if the pet uses Gnaw, then the Frost Sphere will become unhittable and will just float above ground. This means that the sphere will not create an ice patch on destruction and is wasted. Unconfirmed if it keeps this behavior all the way through the encounter, but I believe it does. 

**Expected behaviour**: Tell us what should happen instead

Gnaw shouldn't affect the Frost Sphere at all and the Frost Spheres should be hittable.

**Steps to reproduce the problem**:
1. Death Grip a Frost Sphere in ToGC25
2. Have Death Knight pet use Gnaw on a Frost Sphere.
3. Frost Sphere becomes untargetable and unhittable.

**Include proofs for this behaviour**

I will provide screenshot or video of the Frost Sphere behavior next week if my guild wants to risk a wipe since we simply turn of Gnaw from now on.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

47481 - Gnaw spell ID.
34606 - Frost Sphere npc ID.

**Include Screenshots from the issue if necessary**

As I already mentioned above, I'll try and get a screenshot or video if we decide to use Gnaw again, otherwise it might be possible to reproduce the problem in a lower difficulty.

**Comment by Golganeth** [comment] 2016-08-26 17:07
Similar issue with Scions riding hover disks in Eye of the Eternity. If you grip one of those mobs they will be unhittable and wipe must be forced.

**Comment by Rushor** [comment] 2016-11-29 09:51
Scripts/TrialOfTheCrusader: Frost Spere should be immune against Gnaw

* closes https://github.com/dalaranwow/dalaran-wow/issues/3659
* commit: 8ee104219576f8c6f3d8d85d881d2639f01abe2d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 09:51 UTC
Labels: Instances, On PTR, Priority - High
