### ISSUE TITLE
Terokk's Downfall

### ISSUE THREAD

**Issue by natrixas** [dalaranwow/dalaran-wow#2215] opened 2015-02-02 20:02 UTC
Tarokk's summon is gliched, you may use item near Ancient skull pile or talk with it, but nothing happens. It may be fast fix about it and more ppl could faster grind Sha'tari Skyguard reputation :)
BTW Quest chain for heroic key to tempest keep seems not working also.
Thank you for super working WOTLK :)

**Comment by Golganeth** [comment] 2015-02-02 20:41
Duplicate of #709

**Closed by Golganeth** 2015-02-02 20:41 UTC
