### ISSUE TITLE
[NPC] Insane Ghoul

### ISSUE THREAD

**Issue by Arcanebinder** [dalaranwow/dalaran-wow#3461] opened 2016-06-15 14:41 UTC
**Description**: Incorrect spawn place.

**Current behaviour**:
NPC: Insane Ghoul.
Location: Duskwood, the Tranquill Gardens Cemetery, outside the church

**Expected behaviour**: Have to spawn _inside_ the church.

**Steps to reproduce the problem**:
1. Go there.
2. See him

**Include proofs for this behaviour**
Srsly?

**Comment by Golganeth** [comment] 2016-06-15 15:18
Confirmed. Spawns on the cemetery outside the church and doesn't seem to move at all.
http://www.wowhead.com/npc=511

> He spawns in the church then begins walking within the graveyard's fence. His path then takes him around the outskirts of the graveyard and behind the church.

http://www.wowhead.com/npc=511/insane-ghoul#comments

**Comment by Sagrath** [comment] 2016-06-20 18:35
Im not sure if that comment is correct, all the videos I saw about the quest, he was inside the church

**Comment by Rushor** [comment] 2016-11-12 21:43
> Holding these flowers standing in a church, it seems as he waits for a wedding that has never happened and will never happen :(

same here, i think the change of the spawnpoint towards the church will be enough

**Comment by Rushor** [comment] 2016-11-12 21:47
DB/Creature: Insane Ghoul - Move spawnpoint towards the church

* closes https://github.com/dalaranwow/dalaran-wow/issues/3461
* commit: ebdc79af71360b47acbd85f6424a6e7a94581cab

![GitHub Logo](http://i.imgur.com/P9Ot2Zz.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 21:47 UTC
Labels: Continent - Classic, On PTR

**Comment by Rushor** [comment] 2017-01-23 21:40
on retail he walks in the church like crazy, will add him some wps

**Comment by Rushor** [comment] 2017-01-23 21:51
DB/Creature: Add Run movement for Insane Ghoul

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3461
* commit: cf4bf15cf924922557171aa447d06e2939c15e72

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by robinsch** [comment] 2017-01-23 22:11
@Rushor Does Slack works for you?
