### ISSUE TITLE
[Item] Unfired Plate Gauntlets

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3866] opened 2016-11-20 08:20 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
Found near the lava at the bottom of LBRS shortly after entering the Firebrand area, the Human Remains which start the quest Hot Fiery Death are next to it. The item is needed for the quest following Hot Fiery Death, [Fiery Plate Gauntlets](http://db.vanillagaming.org/?quest=5124).
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The Unfired Plate Gauntlets can't be picked up. 
Even if you have sufficient BS skill (I had 450) and the quest from the Human Remains, the item is not in the container. The arm does despawn after being used once, though. So that works.
**Expected behaviour**: Tell us what should happen instead
[If you have the sufficient BS skill (I guess?)](http://www.wowhead.com/item=12812/unfired-plate-gauntlets#comments:id=135518), you should be able to pick it up. 
[Interesting enough, this issue was also present in Retail during WotLK patch, but was fixed later.  ](http://wowwiki.wikia.com/wiki/Quest:Hot_Fiery_Death)
**Steps to reproduce the problem**:

1. Have BS
2. Go LBRS
3. Try to loot arm 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Unfired Plate Gauntlets object(container?) ID 176089
Unfired Plate Gauntlets item ID 12812

**Include Screenshots from the issue if necessary**
http://i.imgur.com/u7elKbF.jpg

**Comment by Rushor** [comment] 2016-11-21 11:12
the BS skill is not required to loot it.

availability of the item is fixed on ptr

DB/Item: Unfired Plate Gauntlets - should be lootable

* closes https://github.com/dalaranwow/dalaran-wow/issues/3866
* commit: 5f7a99311c2cd6e0563780407088a3d5d1cf7f46

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-21 11:12 UTC
Labels: Items, On PTR

**Comment by Edzero** [comment] 2017-03-28 21:28
Unfired Plate Gauntlets in Blackrock Spire can now be looted.
