### ISSUE TITLE
[NPC] Precious bad positioning

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1270] opened 2014-02-23 22:51 UTC
Precious (http://wotlk.openwow.com/npc=14528) should be above the ground and next to Simone the Inconspicuous (http://wotlk.openwow.com/npc=14527).

**Comment by Rushor** [comment] 2016-11-13 21:18
also the waypoints are missing for simone

**Comment by Rushor** [comment] 2016-11-13 21:21
DB/Creature: Add waypoints and formation for Simone the Inconspicuous

* closes https://github.com/dalaranwow/dalaran-wow/issues/1270
* also added the formation for Precious (it will follow simone) and changed the spawnposition
* commit: 42184ed80b282a346ca3ef1c09eae2a9ea70c7b2

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 18:51
Works as intended on ptr, however i would like to add combat spells for http://wotlk.openwow.com/npc=14527

``` sql
-- Simone the Inconspicuous SAI
SET @ENTRY := 14527;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,4000,6000,8000,10000,11,23206,0,0,0,0,0,2,0,0,0,0,0,0,0,"Simone the Inconspicuous - In Combat - Cast 'Chain Lightning'"),
(@ENTRY,0,1,0,0,0,100,0,0,10000,20000,30000,11,23504,0,0,0,0,0,2,0,0,0,0,0,0,0,"Simone the Inconspicuous - In Combat - Cast 'Fool's Plight'"),
(@ENTRY,0,2,0,0,0,100,0,0,0,30000,30000,11,23205,0,0,0,0,0,2,0,0,0,0,0,0,0,"Simone the Inconspicuous - In Combat - Cast 'Temptress' Kiss'");
```

**Comment by TeridanDW** [comment] 2017-12-23 17:12
Hello, I would like to ask the SAI posted above to be ignored as it is incorrect. The creature's behaviour is far more complicated.

**Comment by TeridanDW** [comment] 2017-12-23 17:19
After a quick test on PTR, the waypoints and the formation is missing.

![image](https://user-images.githubusercontent.com/6797611/34321372-386ee572-e816-11e7-90bb-3a928f6beae2.png)

**Comment by TeridanDW** [comment] 2018-01-05 17:50
Closing this report and merging with #974 as it is relevent to it.

**Closed by TeridanDW** 2018-01-05 17:50 UTC
Labels: Area - Classic
