### ISSUE TITLE
NPC's In Air

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2287] opened 2015-03-11 06:43 UTC
Hello Best developer's and programer's of Dalaran Wow Server in the Starting Zone's Monster's in The Mine's are floating from time to time pls check the pathing's of the monster's in all zone's where there are Mine's only there i can see Mob's Flying good Luck.

On Algalon Realm I am Playing.

P.S=Good Server

**Comment by Golganeth** [comment] 2015-03-11 20:54
Duplicate of #42

**Closed by Golganeth** 2015-03-11 20:54 UTC
