### ISSUE TITLE
[Mechanic][NPC] AI: Fleeing / CCed

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#2166] opened 2015-01-08 19:15 UTC
NPCs are able to cast spells while fleeing or under crowd control effects. While it seems to be a general issue, this behavior may not be present in all of the NPCs.

**Comment by Rushor** [comment] 2016-11-12 18:13
Game/SmartScripts: Prevent SMART_ACTION_CAST if the creature is under CC effect

* closes https://github.com/dalaranwow/dalaran-wow/issues/2166
* this fix only affects creatures with a SmartAI (80% of all creatures use this AI)
* if the creature is fleeing or is confused or is stunned, the creature will not cast it's spells

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 18:13 UTC
Labels: Mechanics, On PTR

**Comment by TeridanDW** [comment] 2017-04-07 18:52
Works as intended on ptr.

**Comment by Aridam** [comment] 2017-11-07 15:05
Confirmed as still-present on live -- just used Intimidating Shout on the Grimtotem in Feralas and some of the Shamen there still had me targetted and cast on me despite them being afflicted with the Fear Debuff.

**Comment by Lothloryen** [comment] 2017-11-07 15:11
Thank you @aridam, forgot to port this commit from Rushor. There are on live several corrections applied regarding the NPCs casting while moving. Anyways, this issue should be corrected with the next maintenance (probably tomorrow morning).

If you do not mind, any kind of feedback about it after the fix goes live will be appreciated.

**Comment by Aridam** [comment] 2017-11-07 16:21
Yes, I've noticed that sometimes they do not do this, so a partial correction is indeed already at play here; will try to remember to update next time then.

**Comment by Aridam** [comment] 2017-11-17 02:00
Double-posting to confirm Mobs no longer do anything while fleeing in Fear now.
