### ISSUE TITLE
Spell: Mirror image

### ISSUE THREAD

**Issue by Coldwarr** [dalaranwow/dalaran-wow#998] opened 2013-12-06 07:37 UTC
<i><strong> Mage spell: </strong></i>
<strong> Mirror image  </strong> - 55342

<strong> Issues present: </strong>
- The moment the images are summoned they cast fireblast at a nearby hostile target, ignoring crowd control effects breaking the crowd control. (eg. Polymorph)
- The images only start attacking when:  an NPC aggro's the player, the mirror images are positioned closely to a hostile unit (about 12-15 yds) and when they are attacked themselves.
- The images do not inherit the mages spell hit rating from items.
- When the /petfollow and /petpassive commands are used, the images continue casting and don't return to the mage.

<strong> How it should work: </strong> 
- The images should never cast any spell including fire blast at targets affected by crowd control debuffs, including at the start of the summon.
- The images should attack the NPC with the <strong> highest threat </strong> towards the player, even when not aggro'd. When the mage attacks another player in PvP combat, the mirror images should start attacking that enemy player. When an enemy player attacks the mage, the mirror images should start attacking that player. The fact that the mirrors start attacking a hostile unit at 12-15 yards without any sorts of combat interaction works as intended though.
- The images should inherit any<strong> item </strong> spell hit rating from the mage, this does not apply to talents like Precision.
- The mirror images should obey the /petfollow and /petpassive command despite of having no separate pet bar. They should however not respond to /petattack.
## 

<strong>Sources:</strong>
http://www.wowhead.com/spell=55342#comments
http://www.wowwiki.com/Mirror_Image
http://wowpedia.org/Mirror_Image

Retail WoTLK player

**Comment by Vaxsysl** [comment] 2015-01-07 22:57
Since this has no comments, not that they are needed, but, confirmed, still up!

**Comment by Vaxsysl** [comment] 2015-01-15 00:28
Another bug, using images doesn't make players de-target us in PvP. Afaik, it should work like that, and it's also a way to avoid missile spells such as Haunt.

**Comment by Golganeth** [comment] 2016-06-29 12:58
#3520 - 

> Sometimes when MI ends, the mage using it gets some insane amounts of threat (omen says something about 40 millions instant threat) and eventually ythe mage overaggroes, even if his threat is fine for all the rest of the fight.

**Comment by Rushor** [comment] 2016-12-07 20:16
most of this was fixed by https://github.com/TrinityCore/TrinityCore/commit/ee9c9e6051e4bcbd02d7710473068d8ddab89cc5

pls test it on ptr. thanks

**Closed by Rushor** 2016-12-07 20:16 UTC
Labels: Class - Mage, Fixed - On PTR

**Comment by Rushor** [comment] 2018-05-25 15:01
On PTR.
