### ISSUE TITLE
Badlands Reagent Run II

### ISSUE THREAD

**Issue by hhansx** [dalaranwow/dalaran-wow#3691] opened 2016-09-02 03:50 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: The quest [Badlands Reagent Run II](http://db.vanillagaming.org/?quest=2203) does not work. You recieve three [Empty Thaumaturgy Vessels](http://db.vanillagaming.org/?item=7866) which you are to fill with blood from the corpse of [Scorched Guardians](http://db.vanillagaming.org/?npc=2726).

**Current behaviour**: When you use the empty vessels on the corpses nothing happens. The vessel does go on cooldown though.

**Expected behaviour**: The empty vessel should turn into [Vessel of Dragon's Blood](http://db.vanillagaming.org/?item=7867).

**Include proofs for this behaviour**

http://i.imgur.com/fVBAmcw.gifv

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

[Badlands Reagent Run II](http://db.vanillagaming.org/?quest=2203) - Quest ID 2203
[Scorched Guardians](http://db.vanillagaming.org/?npc=2726) - NPC ID 2726
[Empty Thaumaturgy Vessels Item](http://db.vanillagaming.org/?item=7866) - ID 7866
[Vessel of Dragon's Blood](http://db.vanillagaming.org/?item=7867) - Item ID 7867

**Comment by Jokey123** [comment] 2016-09-02 14:25
I just tested this on the PTR after reading the quest description. It never said anything about using the quest item on the creature's CORPSE. So I went out, used the item on the Scorched Guardians while they were alive, and it worked as intended.

**Comment by hhansx** [comment] 2016-09-02 15:05
wow, my bad!

**Comment by Golganeth** [comment] 2016-09-05 20:10
The quest works fine. I could not find evidence regarding if the quest item could be wrongly used and go on cooldown, so closing for now.

**Closed by Golganeth** 2016-09-05 20:10 UTC
