### ISSUE TITLE
[Quest] Tirion's Gambit

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#636] opened 2013-08-18 03:08 UTC
=To be edited=

**Issue for now**: The entire event is missing.

**Video of how it should look:** http://www.youtube.com/watch?v=4Efu3fmmvM4

**Comment by n-ghost** [comment] 2015-01-01 01:30
Confirmed, after obtaining Cultist Acolyte's Hood (which works fine, by the way), Tirion is nowhere to be found.

**Comment by Dasher2417** [comment] 2015-04-08 20:30
Still an issue.

**Comment by NotBadGuy** [comment] 2015-10-02 08:44
Quest works as normal, but the event after obtaining Acolyte's Hood (after entering the cathedral) activated once I tried to leave the cathedral (Lich King came walking in). The rest of the event worked as normal and after a slightly longer fight a portal opens to Crusader's Pinnacle where you can turn the quest in.

**Comment by MrAndersonX** [comment] 2016-02-07 16:49
Confirmed - bugged. Needs a fix.

**Comment by zykadelic** [comment] 2016-06-20 22:17
@MalkaviaDW Why was this closed? I'm having the same issue.
@NotBadGuy Did you do anything special to activate the event?

**Comment by Golganeth** [comment] 2016-06-21 15:04
As @NotBadGuy mentioned the Lich King spawns too far away and doesn't interact / move until a player gets close (walk to the entrance of the Cathedral and The Lich King will trigger). The quest itself can be completed but the event needs a few polishments.

@zykadelic The event can be activated correctly, read quest log or internet sources.

**Comment by Rushor** [comment] 2016-06-21 18:52
we could set him active am spawn

**Comment by Golganeth** [comment] 2016-06-21 20:42
It seems to be the general issue with NPCs not having AI /interacting if no GM/players around. Happens with a lot of NPCs and stuff in general

**Comment by Golganeth** [comment] 2016-06-23 17:46
@jonanone 
After the latest fixes:

**Major issue:**
- Quest is doable only once per hour, Highlord Tirion Fordring (ID: 32239) has around 1 hour respawn timer once someone has done the quest.

-------------

**Minor issues:**
- Some Zealots will reset back to their spots on the start of the "fight". They go so far away that sometimes only 1 of the NPCs will charge to them, while the other NPCs will stand still in battle stance. Because of this the "fight" phase may take too long. 
- After doing it a 2nd time, the NPCs near Tirion outside the Cathedral (Disguised Crusader, ID: 32241) didn't follow us.

**Comment by MrAndersonX** [comment] 2016-11-14 22:51
Can't complete it. I took/used the hood but Tirion never showed up, so I guess..Bump ?

**Comment by Rushor** [comment] 2016-11-24 13:40
Scripts/Quest: Tirion's Gambit - Set respawntime to 60 seconds for Tirion and the Disguised Crusaders

* closes https://github.com/dalaranwow/dalaran-wow/issues/636
* i could not reproduce the fightscene/attackbehavioud issues anymore
* commit: 9f54399c1bf994cf298d1cabdf7c979137c2e92b

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 13:40 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-11-01 10:38
Works as intended on PTR.
