### ISSUE TITLE
[Death Knight] [Talent] Magic Suppression (Anti-Magic Shell)

### ISSUE THREAD

**Issue by AraelWindwings** [dalaranwow/dalaran-wow#2198] opened 2015-01-26 21:09 UTC
Talent: http://wotlk.openwow.com/spell=49611

It doesn't work. You will not absorb 100% damage if taken, but only 75%.

Spell: http://wotlk.openwow.com/spell=48707

I didn't make test on damage reduction.

I didn't make test on specific spells but It must protect against spell like Hex and Cyclone.

**Comment by MikeViper** [comment] 2015-01-28 17:02
Confirmed, this bug is presented on most wotlk private servers. The 25% extra absorption is lost upon death or when changing zones, making Anti-Magic Shell being back to its default 75% absorption instead of 100% when the said circumstances happen.  A rather major bug for all unholy builds.

**Comment by Vaxsysl** [comment] 2015-02-02 12:57
Seems to me its like Drudi's Primal Fury bug (adds extra combo point on crit), you need to swap specs or relog to fix the issue.

**Comment by AraelWindwings** [comment] 2015-02-04 09:53
Confirmed, the bug occurs under some circumstances.

**Comment by Rushor** [comment] 2016-12-03 14:07
problem s, that the spell has proccharges and simply disapears upon spellhit.

fix for this is already on ptr.

Core/Spells: Magic Suppression - Set ProcCharges
commit: ce4bd3c2de8c78466f54846c3e24bc35fedfc8d8

**Closed by Rushor** 2016-12-03 14:07 UTC
Labels: Class - Death Knight, Fixed - On PTR

**Comment by TeridanDW** [comment] 2017-04-07 18:39
Works as intended on ptr.
