### ISSUE TITLE
[Quest] Distracting Jarven

### ISSUE THREAD

**Issue by sedenha** [dalaranwow/dalaran-wow#4716] opened 2017-05-25 01:40 UTC
In the quest, the NPC Jarven Thunderbrew (NPC ID #1373), when activated the quest Distracting Jarven (QUEST ID #308), is running in his path.
In this quest, this NPC walk, and no run.
It's simple, but important for the lorekeepers.
Thanks a lot.
![wowscrnshot_052417_223114](https://cloud.githubusercontent.com/assets/28940372/26432401/f01ebf72-40d1-11e7-9cc7-710ce53c737b.jpg)

**Comment by Rushor** [comment] 2017-07-01 11:54
so the creature should actually walk the path, but instead it's running too fast

**Comment by Rushor** [comment] 2017-07-01 12:36
DB/Quest: Distracting Jarven - Enable walking of Jarven Thunderbrew instead running + move actionlist to waypoint script

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4716
* commit: 1a039457bd5e7c86b1b8160b2eb661c7e4e31b8a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-01 12:36 UTC
Labels: Area - Classic, General - Quests

**Comment by TeridanDW** [comment] 2017-10-24 07:28
Works as intended on PTR.
