### ISSUE TITLE
[Mob] Reset Range to short?

### ISSUE THREAD

**Issue by Rumsteak** [dalaranwow/dalaran-wow#2474] opened 2015-06-04 00:25 UTC
Another thing i recognized while playing tonight:

Mobs seem to reset after a very short range, if you try to outrun them.

Tested it with various mobs in the Northern Barrens, only raptors followed me around for as long as usual.

**Comment by Rushor** [comment] 2016-12-02 12:02
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/3090

**Closed by Rushor** 2016-12-02 12:02 UTC
Labels: Duplicate / Invalid Report, General - Mechanics
