### ISSUE TITLE
[Shaman] Fire Nova LoS problem

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#3131] opened 2016-02-07 02:39 UTC
From 3.3.0 PTR Patch Notes :
"Fire Nova Totem: This totem has been replaced with a new spell, Fire Nova, which is available at the same ranks as the old Fire Nova Totem. Existing characters will automatically learn this new spell in place of the totem. With a Fire Totem active, shamans will be able to use Fire Nova (fire magic) to emit the same area-of-effect damage as the old Fire Nova Totem from the active Fire Totem, not consuming the totem in the process. Fire Nova will activate a 1.5-second global cooldown when used and has a 10-second spell cooldown. The caster must be within 30 yards of the totem to use this ability, **but does not need to be within line of sight of the totem**."

Currently Fire Nova will issue an error when cast if your fire totem is out of LoS. This will eat up the cd and the mana, and do no damage. Instead, it should not issue any error even if the fire totem is out of LoS and still do damage

**Comment by adytzyca** [comment] 2016-02-07 12:10
The problem extends to all the shaman totems:for instance,if you use tremor totem behind the pillar,you will still get fully feared even if you're within its range.Same goes for Cleansing Totem-its effect wont be triggered if you're LoSing your totem

**Comment by robinsch** [comment] 2016-11-21 13:42
On PTR.

**Comment by Edzero** [comment] 2017-04-01 00:57
The LoS portion is now working properly but there is no range limit on casting the ability.

I believe this should be fixed at the same time rather than pushing it in a half broken state.

**Comment by robinsch** [comment] 2017-04-01 10:50
Script/Spell: Fixed range check for Fire Nova
1adfabd190e8f5095ca40c3bad24f520dfbf5d18

Seems to be not on PTR. I tested it local and the range is correctly limited to 30.0f.

**Closed by robinsch** 2017-04-01 10:50 UTC
Labels: Class - Shaman, General - Mechanics, Priority - High

**Comment by TeridanDW** [comment] 2017-10-13 17:17
After some tests on ptr, this issue is fixed and working as intended.
![wowscrnshot_101317_201732](https://user-images.githubusercontent.com/6797611/31557942-95e57da6-b053-11e7-99f0-b942e378959b.jpg)
