### ISSUE TITLE
[Mechanic] Combat/Infight Bug

### ISSUE THREAD

**Issue by Mattgoheels** [dalaranwow/dalaran-wow#3656] opened 2016-08-16 01:42 UTC
If you attack a creature which is in evade-modus, you will get in combat and never leave combat again. This creates the famous "Combat/Infight-Bug".

**Comment by Jokey123** [comment] 2016-09-01 11:26
Works fine on PTR.

**Comment by Rushor** [comment] 2016-11-10 21:33
Game/Unit: Don't add threat to an evading Unit

* closes https://github.com/dalaranwow/dalaran-wow/issues/3656
* if you attack a creature if it is in evade-modus (f.ex. if the creatures tries to run back to his homeposition) you will no longer generate aggro on that creature. This will resolve several combat/infight-bugs.
* commit: 93b621a5205eb25d0dbbabef99351852b381e3c8

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 21:33 UTC
Labels: Mechanics, On PTR

**Comment by TeridanDW** [comment] 2017-03-31 13:53
Can't confirm or deny the fix here. There is something wrong with combat reset for players on ptr. Players does not leave combat upon creature evade or death (sometimes).
