### ISSUE TITLE
Icecrown perma freeze

### ISSUE THREAD

**Issue by Dorvald** [dalaranwow/dalaran-wow#3908] opened 2016-11-30 17:55 UTC
Hi guys! I got perma freeze in Icecrown. I tried to write in the forum but first I have to select a character in the website from my account. I could not select any of my characters on the website, it says " No characters have been found" in the account ( I have a lvl 79 shaman). So my character stuck and i cant use your forums to write, please help me.

**Comment by Rushor** [comment] 2016-11-30 18:01
A fix for the freeze in the area will be applied this night. thanks for your report. duplicate of https://github.com/dalaranwow/dalaran-wow/issues/3903

**Closed by Rushor** 2016-11-30 18:01 UTC
Labels: Duplicate / Invalid Report

**Comment by Dorvald** [comment] 2016-11-30 18:20
But could you put my character to Dalaran for example please? I would like to continue leveling.

**Comment by Dorvald** [comment] 2016-11-30 18:34
Well guys somehow its working now. I can log in. Sorry for the disturb.

**Comment by Lothloryen** [comment] 2016-11-30 18:37
Hello Dorvald,

One question if you do not mind, please. If you have successfully logged in with that character, was your character still in Icecrown?

Thank you.

**Comment by Dorvald** [comment] 2016-12-01 14:33
Hi. I deleted a folder, named Cache and then i could log in with the
character. And yes, it was still in Icecrown but not in the same place. It
looked like i got a rollback or something.

2016-11-30 19:37 GMT+01:00 Lothloryen <notifications@github.com>:
