### ISSUE TITLE
[NPC] North Fleet Marine 23893

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#945] opened 2013-10-28 19:30 UTC
These mobs have no loot implemented
http://www.wowhead.com/npc=23983/#drops:50-16+1

**Comment by Rushor** [comment] 2016-11-12 20:42
DB/Creature: North Fleet Marine - Add loot

* closes https://github.com/dalaranwow/dalaran-wow/issues/945
* commit: 4258d2239960199a47388ce69a76ba6c135680d4

```sql
DELETE FROM `creature_loot_template` WHERE `entry`= 23983;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES 
(23983, 26000, 26000, 3, 0, 1, 1, 1, 1, NULL),
(23983, 26001, 26001, 3, 0, 1, 1, 1, 1, NULL),
(23983, 26003, 26003, 1, 0, 1, 1, 1, 1, NULL),
(23983, 26004, 26004, 1, 0, 1, 1, 1, 1, NULL),
(23983, 26017, 26017, 0.5, 0, 1, 1, 1, 1, NULL),
(23983, 26018, 26018, 0.5, 0, 1, 1, 1, 1, NULL),
(23983, 26044, 26042, 2, 0, 1, 0, 1, 1, NULL);
```

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 15:44
This fix is not on the ptr currently.
@Rushor that loot table is completely wrong, really doubt this item should drop from them http://www.wowhead.com/item=26000/gladiators-linked-gauntlets#drops:0-18-16+1 or am I missing something?

**Closed** 2017-11-30 14:24 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR update
