### ISSUE TITLE
[NPC] Corki - Texttargeting

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1166] opened 2014-02-05 17:28 UTC
**Issue:** Once you release Corki for the quest "HELP!", you will encounter a typo:

![asd](https://f.cloud.github.com/assets/5057942/2089686/7b6f1502-8e8a-11e3-93a2-cb6c280ed954.png)

Where "$C" should be the class of the rescuer.

http://wotlk.openwow.com/npc=18445
http://wotlk.openwow.com/quest=9923

**Comment by Rushor** [comment] 2016-11-12 12:56
Scripts/Outland: Corki - Texttargeting

* closes https://github.com/dalaranwow/dalaran-wow/issues/1166
* the name of the character should now always be displayed correctly

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 12:56 UTC
Labels: Continent - Outland, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-03 19:47
Works as intended on ptr.
