### ISSUE TITLE
[NPC][Cosmetic bug] [Tirisfal Glades] Deathguard Terrence

### ISSUE THREAD

**Issue by ashphoenix92** [dalaranwow/dalaran-wow#3828] opened 2016-11-11 09:26 UTC
**Description**: NPC In Tirisfal Glades, Minor\Cosmetic Bug, [Deathguard Terrence]

**Current behaviour**: NPC in question laughs constantly, emote of "laugh" is on constant 
reiteration. Does not affect gameplay or mechanics, but still is very irritating.

**Expected behaviour**: Expected not to irritate and not use scripted emotes.
**Steps to reproduce the problem**:

1. Turn off scripted emote, which, currently, is overlapping.

Link to NPC's database http://www.wowhead.com/npc=1738/deathguard-terrence
http://wowwiki.wikia.com/wiki/Deathguard_Terrence

Thank you for your attention.

**Comment by Rushor** [comment] 2016-11-11 10:08
DB/Creature: Deathguard Terrence - Remove emote in waypointscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/3828
* commit: 51a9b36553ebe2c42122f038afaaeddb7a44dcbc

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 10:08 UTC
Labels: Continent - Classic
