### ISSUE TITLE
[Spell] Wind Stones in Silithus

### ISSUE THREAD

**Issue by krellemeister** [dalaranwow/dalaran-wow#3096] opened 2016-01-14 18:09 UTC
The stones are supposed to work as described here: http://wowwiki.wikia.com/wiki/Wind_stone

Basically, the issue is that the prerequisite gear is not removed upon interaction with all three types of Wind Stones (Lesser Wind Stone, Wind Stone, and Greater Wind Stone). Because of this, you are able to spawn as many elementals and Dukes as you want, all of which gives quite a nice bunch of loot including greens, blues, and elemental Essences.

For the sake of proving my point, I went ahead and spawned 5 Dukes. I received 250 reputation with Cenarian Circle, 4 blue items, and 3 green items from them, all in a couple of seconds.

**Comment by Rushor** [comment] 2016-11-16 17:07
DB/Spell: Silithus Stone spells -Ignore LOS

* closes https://github.com/dalaranwow/dalaran-wow/issues/3096
* commit: bd2a1d79c5e8ceef6ba05fb811bfb6f31d8eb58f
* the items will be removed now after summon of the creatures

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-16 17:07 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 13:55
Works as intended on ptr.
