### ISSUE TITLE
Quest: Preparations for War 13418 -A  13419 -H

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#653] opened 2013-08-18 22:36 UTC
http://www.wowhead.com/quest=13418 (alliance)
http://www.wowhead.com/quest=13419 (horde)
http://www.wowhead.com/quest=31081 (Officer Van Rossem - Alliance)
http://www.wowhead.com/npc=31085 (Sky-Reaver Klum - Horde)
- The gossip of these two NPCs upon taking the quest does not work
- They should take you flying to IceCrown's flying ships.
- As horde, you can speak to Van Rossem, and you see that gossip option but this should NOT happen and Klum has 2 of same gossip menu
  Related spells are
  http://www.wowhead.com/spell=58349 (A)
  http://www.wowhead.com/spell=58352 (H)

**Comment by Lothloryen** [comment] 2016-07-01 19:50
By Jonanone:

- The vehicle summoning and the route has been implemented.
- Once the vehicle is near the gunships, it will despawn and cast a parachute on the player.
- Usually it will fail to aim the gunship since the coordinates can't be obtained correctly.
* At least the quest is doable and it helps the player locating the gunship.

**Comment by MrAndersonX** [comment] 2016-11-02 21:44
Like Loth said, but unfortunately if the player doesn't have a cold weather flying, reaching the ship is impossible.

**Comment by Edzero** [comment] 2016-11-03 13:39
You can "rent" a flying mount which will work if you can't afford to buy one. Temporary workaround for players until it is working properly.

**Comment by MrAndersonX** [comment] 2016-11-03 20:34
Yeah, still needs a fix, but good that u posted a temp solution for it for people to see. Ty.

**Comment by Rushor** [comment] 2016-11-24 14:31
DB/Quest: Preparations for War - Update columns for `gossip_menu_option`

* closes https://github.com/dalaranwow/dalaran-wow/issues/653
* enabled the gossips on ptr
* script works perfectly for me http://i.imgur.com/QMXElPu.png

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 14:31 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by Rushor** [comment] 2018-05-24 12:31
That fix is already on PTR.
