### ISSUE TITLE
Pet talent Wild Hunt

### ISSUE THREAD

**Issue by LordTmpp** [dalaranwow/dalaran-wow#2910] opened 2015-09-23 09:10 UTC
Wild Hunt doesn't seem to be working correctly, it's not giving my pet any stamina whatsoever. It does give my pet the attack power bonus after dismissing and recalling, but no stamina.

Curiously, if I have my pet learn both Great Stamina and Wild Hunt, and then UNLEARN my pet's talents, the health and stamina numbers jump to levels that they should be at with Wild Hunt, but that only lasts for as long as I dismiss the pet.

Without Wild Hunt:
![petnohunt](https://cloud.githubusercontent.com/assets/14801940/10041229/45d8d884-61eb-11e5-849a-d0618dd312cc.png)

With Wild Hunt:
![petwithhunt](https://cloud.githubusercontent.com/assets/14801940/10041250/8c51d130-61eb-11e5-8e11-2f451fbeadc0.png)

With Wild Hunt after dismissing:

![petafterdismiss](https://cloud.githubusercontent.com/assets/14801940/10041261/a5ce1808-61eb-11e5-9a9f-1e9befd6ae80.png)

With Great Stamina and Wild Hunt, after unlearning pet talents:

![staminahuntunlearned](https://cloud.githubusercontent.com/assets/14801940/10041298/fb672836-61eb-11e5-9101-c8c85434b00c.png)

**Comment by robinsch** [comment] 2016-07-01 07:28
On PTR. Note: You need to resummon your pet to update stats.

**Comment by MrAndersonX** [comment] 2016-07-12 21:05
Alot of pet talents are still bugged, waiting for the changelog to be applied to the live realm. Can we get a timed release on it ? We've been waiting for it to be applied for a while now...

**Comment by Winstrol** [comment] 2016-07-13 22:49
ok so i tamed a new pet resummoned it check hp and specced, after i resummoned it again it still had the same hp.
so im assuming its still broken

**Comment by MrAndersonX** [comment] 2016-07-13 22:53
Well yes, Wild Hunt, Cobra Strikes and pet stamina/hp/hit etc are still bugged, or better said the patch fix still hasn't been implemented on the live server...And the changelog/patch came out like 2 and a half weeks ago -_-....

**Comment by MrAndersonX** [comment] 2016-07-13 23:05
Well Lothloryen said : "Hello there,

The remaining fixes were applied yesterday night already.

Thank you very much."

But still, Wild Hunt is still bugged (no increase stamina or ap), same as pet stats, hit ,expertise, etc and Cobra Reflexes. So, what gives ?....

**Comment by Winstrol** [comment] 2016-07-13 23:50
i think you mean Cobra Reflexes and it seems to be working aswell as steady shot, only seem to be a problem with Wild Hunt

**Comment by MrAndersonX** [comment] 2016-07-14 09:00
Well, pet stats are the same as they were after the patch, and yes, Cobra Reflexes now works, but stats + Wild Hunt are bugged the same way they were before.

**Comment by robinsch** [comment] 2016-07-14 10:05
They are not tested yet on PTR, that's why they were not shipped to live. We're looking for new testers to join the development team. I will just leave this here, if you want to get things shipped to live faster - feel free to apply.

**Comment by MrAndersonX** [comment] 2016-07-14 10:18
Well, from what Loth said, I thought they were tested and applied (from the The Beast Within changelog), so I didn't really get it why they didn't work. Well, guess I'll have to wait again till they are tested/applied. But also, I wanna ask that when a changelog gets announced/released, please state ONLY the things that were tested and then CONFIRM when they have been/are being applied. So, like 3 weeks later, people won't have to wonder what part of the changelog was applied and what actually works/doesn't work. 

Thank you.

**Comment by Lothloryen** [comment] 2016-07-14 11:38
Hello there,

I will check what happened with Wild Hunt, pets stats should be scaling properly though.  If anyone can post a proof about stats not scaling as they should, it would be really appreciated. 

I have re-checked it now and It works.

Feedback would be welcome.

Thank you very much.

**Comment by MrAndersonX** [comment] 2016-07-14 11:39
Thanks alot Lothloryen. Keep us up to date with Wild Hunt :P !

**Comment by kalvindeane** [comment] 2016-08-27 01:09
Results from testing the hunter and pet talents (only ones related to pet scaling) on the PTR:

The pet talent "Wild Hunt" still isn't affecting the pet. the bug the OP mentioned about unlearning the pet's talents is not present either. 

The hunter talent "Animal Handler" isn't granting the 10% attack power bonus to the pet either.

Following talents are working fine in regards to pet scaling:

Cobra Reflexes (pet talent),
Great Stamina (pet talent),
Spiked Collar (pet talent),
Natural Armor (pet talent),
Endurance Training (hunter talent),
Thick Hide (hunter talent),
Unleashed Fury (hunter talent),
Ferocious Inspiration (hunter talent), 
Serpent's Swiftness (hunter talent),
Kindred Spirits.

**Comment by robinsch** [comment] 2016-08-27 11:57
Wild Hunt and Animal Handler on PTR.

**Comment by kalvindeane** [comment] 2016-09-15 01:14
Confirmed working on PTR.

**Comment by Serpentsting** [comment] 2016-10-20 14:39
![wowscrnshot_102016_173543](https://cloud.githubusercontent.com/assets/22957732/19564413/271f4d1a-96ec-11e6-8056-ac6c6e911b8a.jpg)
![wowscrnshot_102016_173606](https://cloud.githubusercontent.com/assets/22957732/19564417/2d7926b8-96ec-11e6-960b-bd8ed04e2230.jpg)
![wowscrnshot_102016_173621](https://cloud.githubusercontent.com/assets/22957732/19564420/2e66646e-96ec-11e6-9773-5edb03703df1.jpg)
![wowscrnshot_102016_173635](https://cloud.githubusercontent.com/assets/22957732/19564421/2f3c8314-96ec-11e6-84ba-589c8c640369.jpg)
![wowscrnshot_102016_173646](https://cloud.githubusercontent.com/assets/22957732/19564422/30372efe-96ec-11e6-844a-5303fec5a978.jpg)
wasn't fixed.

**Comment by Edzero** [comment] 2016-10-20 14:57
I've tested this on the PTR and it seems to be working on there (tried with one Cunning pet and two different Ferocity pets).

My understanding is that this talent was working on live after a patch a while ago and it has since stopped working.

**Comment by MrAndersonX** [comment] 2016-10-20 15:20
Tbh, since I started playing here, I've never seen or heard about it working. Just saying...All I know is that it was supposed to be implemented on the live server, that it was working on PTR, but it never happened. The patch that was suppose to implement it, but it had a few bugs, and some stuff in it didn't get implemented.

**Comment by Edzero** [comment] 2016-10-22 18:08
It wasn't put on live when the patch notes came up but was allegedly working some time after I marked it working on the 15th September according to 2 different players. We must now wait for Loth or a dev to investigate.

Thank you for your contributions so far guys. ^^

**Comment by MrAndersonX** [comment] 2016-10-22 18:09
Same, thanks.

**Comment by Rushor** [comment] 2016-11-12 14:16
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 14:16 UTC
Labels: Class - Hunter, Mechanics, On PTR, Priority - High
