### ISSUE TITLE
[Quest][Northrend] Fire Upon the Waters

### ISSUE THREAD

**Issue by Exorcista** [dalaranwow/dalaran-wow#1989] opened 2014-10-18 21:19 UTC
The following quest @ Dragonblight http://www.wowhead.com/quest=12243/fire-upon-the-waters, does not work as intented and is a little bit tricky to do it, and you might die trying to.

<b>How it Works:</b> you go to the named ship and use the item on the biggest sail a couple of times until you get credit (i guess has to be a precise spot), when this is done, deckhands are unafected so you either clear the ship after seting the sail on fire or you are going to die awfully. Rest of the quest works fine.

<b>Video of how Should it Work:</b> https://www.youtube.com/watch?v=4L_J0K5VJAU

**Comment by Vaxsysl** [comment] 2015-05-20 14:38
I got credit by using the quest item at the base of the front sail.

**Comment by MrAndersonX** [comment] 2016-10-31 15:47
Currently trying to set it on fire, but it doesn't seem to work for any position. Needs a fix.

**Comment by Rushor** [comment] 2016-11-26 20:48
DB/Quest: Fire Upon the Waters - The whole sail can be used for the credit now

* closes https://github.com/dalaranwow/dalaran-wow/issues/1989
* commit: 2b81a2828ecd7e4aa401ee431afc082b75912f17

![GitHub Logo](http://i.imgur.com/yRLipYr.jpg)
![GitHub Logo](http://i.imgur.com/IqQVPG6.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 20:48 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:12
Works as intended on PTR.
