### ISSUE TITLE
Tempest Keep Not giving raid ID

### ISSUE THREAD

**Issue by Drawsblood** [dalaranwow/dalaran-wow#4387] opened 2017-02-08 23:16 UTC
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Just cleared TK and did not receive a raid ID, was wondering why I started seeing so many Ashes around. :^)

**Expected behaviour**: Tell us what should happen instead

Obtain ID upon killing boss.

**Steps to reproduce the problem**:

1. Enter dungeon
2. kill boss
3. dont get saved

**Comment by alexuktc** [comment] 2017-02-09 08:04
I am not sure how you accomplished that. but as one of the people with the Ashes I can assure this is not the case for us. Don't assume people have abused just because they have Ashes.

**Comment by Drawsblood** [comment] 2017-02-09 08:08
Just reporting a bug I found while doing TK yesterday.  Please calm down .

**Comment by Rushor** [comment] 2017-02-09 09:03
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/3133

**Closed by Rushor** 2017-02-09 09:03 UTC
