### ISSUE TITLE
Fall Damage

### ISSUE THREAD

**Issue by syrixVG** [dalaranwow/dalaran-wow#279] opened 2013-07-31 18:14 UTC
When you fly with your form (Flight Form) and while you fly you change the form to normal then fall for a bit then change back to flight form, sometimes when you land on the ground ( not from high ) you take alot of damage. Like if you are falling from alot higher then 1 y. (Thats the best way I could've explained it)
![Uploading FallDamage.png . . .]()

**Comment by Sedare** [comment] 2015-02-22 23:58
I have no idea how the platform thing happened, but I dont see that related to the dismount from flying mount issue. 

I have traced this to an elevation marker placed on your character when you mount your flying mount. I can test this and reproduce this at any time. Go to storm peaks, mount where thorim is, and fly down and 20 yards above the ground, dismount. you will die. The characters last known unmounted location is used as the reference for falling elevation when you dismount in mid air. The only exception for this is using slowfall. Thats it.

**Comment by Zeilze** [comment] 2015-02-23 03:18
Confirmed. Agreed with Sedare's comment. In Netherstorm, around co-ordinates (35,58) (Next to Area 52), an area with  a lot of plateaus and schisms I died twice in 30 minutes due to this falling 5-10 yards from the ground.

**Comment by Kenleed** [comment] 2015-02-24 20:58
Confirmed, I can reproduce this bug, if you fly op and log out / Dc, and i dismount to charge a mob, from like 1-2 meters above the mob i die from fall damage...

**Comment by Leodimas** [comment] 2015-05-25 19:12
want to add : the game or server or what it is called, has a delay in detecting when your character stoped moving,maybe even less than .1 seconds. 
I notice that when I cast a spell right after moving, i get an error saying "cant cast while moving".
There seems to be a little lag between client and server talking to each other when they exchange player position , movement etc.

**Comment by M0dinstaller** [comment] 2015-08-21 00:54
Hi there, according to the trinitycore github, this is due to an anti-cheat plug-in.
https://github.com/TrinityCore/TrinityCore/issues/2072
I suggest you get another one, like Warden.

**Comment by vdanielpop** [comment] 2015-10-24 08:46
Any updates on this one? It's a gamebreaking issue that needs to be fixed as soon as possible, it should be prioritary.

**Comment by DrFuler** [comment] 2015-12-18 03:54
18/12/2015: This is still happening.

As pointed out, this is very common/upsetting at Netherstorm.

**Comment by Rushor** [comment] 2016-05-05 17:03
https://github.com/TrinityCore/TrinityCore/pull/16955

**Comment by Rushor** [comment] 2016-06-08 06:26
https://github.com/TrinityCore/TrinityCore/pull/16955

**Comment by Kaporalhart** [comment] 2016-06-08 19:05
wow, it's been 3 years since someone first pointed out that bug. Could you please maybe fix this ? I just died for like the 4th time today because of this and i thought maybe no one reported it because it's been here for so long that nobody ever think about it and in fact nobody has... but no ! it's been 3 years ! fix it already !

**Comment by Rushor** [comment] 2016-06-08 20:34
tc fix merged

**Closed by Rushor** 2016-06-08 20:34 UTC
Labels: Core/System
