### ISSUE TITLE
[Quest][Northrend] Worm Wrangler

### ISSUE THREAD

**Issue by xxauroraxx** [dalaranwow/dalaran-wow#2574] opened 2015-06-28 19:07 UTC
You're supposed to get within melee range of a certain mob, and use an item. Then, you're supposed to click the item as it replaces the mob in the world.

The mob is never replaced and remains in the world. You do not get credit for clicking on the newly placed item.

**Comment by darkwulfv** [comment] 2015-06-29 21:01
Can confirm that the mobs do not get replaced, but the placed item (the crate) does credit, although I did have one instance where I was not credited.

So the quest is mostly working, and is can be completed.

**Comment by Rushor** [comment] 2016-11-26 21:14
http://wotlk.openwow.com/quest=12078

**Comment by Rushor** [comment] 2016-11-26 21:21
DB/Quest: Worm Wrangler - now despawn after placing the sturdy crates

* closes https://github.com/dalaranwow/dalaran-wow/issues/2574
* commit: 72e73aac3db60e0c1f78b678ee969677ccdca001

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 21:21 UTC
Labels: Continent - Northrend, Items, On PTR, Quests
