### ISSUE TITLE
[NPC] Bloodscalp Hunter unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1223] opened 2014-02-18 03:47 UTC
Bloodscalp Witch Doctor (http://wotlk.openwow.com/npc=660) and Bloodscalp Hunter (http://wotlk.openwow.com/npc=595) are not casting any of their abilities. The other bloodscalp npcs might be unscripted as well, I was not able to check them all.

**Comment by Rushor** [comment] 2016-11-14 18:38
Bloodscalp Witch Doctor (http://wotlk.openwow.com/npc=660) is already scripted, Bloodscalp Hunter  needs to be fixed

**Comment by Rushor** [comment] 2016-11-14 18:40
DB/Creature: Add abilities for Bloodscalp Hunter

* closes https://github.com/dalaranwow/dalaran-wow/issues/1223
* commit: bad16feccced0bf4d0be6d53fae7cb90a2c2f4ac

('Bloodscalp Hunter - On Aggro - Cast \'Shoot\'');
('Bloodscalp Hunter - In Combat - Cast \'Net\'');
('Bloodscalp Hunter - Between 0-30% Health - Cast \'Enrage\' (No Repeat)');
('Bloodscalp Hunter - On Reset - Remove Aura \'Enrage\'');
('Bloodscalp Hunter - Between 0-30% Health - Say Line 0 (No Repeat)');
('Bloodscalp Hunter - In Combat - Cast \'Shoot\'');

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 19:18
Hello, some issues that i saw:
 - npc http://wotlk.openwow.com/npc=595 doesn't seems to cast http://wotlk.openwow.com/spell=6533 at all.
 - npc http://wotlk.openwow.com/npc=660 doesn't seems to cast http://wotlk.openwow.com/spell=5605 at all
 - npc summoned by spell http://wotlk.openwow.com/spell=8376 doesn't start to cast it's spell before someone attacks it first (if the player ignores and doesn't attack it, the totem won't do anything)

**Comment by TeridanDW** [comment] 2017-10-28 10:07
Fixed in #4975

**Closed by TeridanDW** 2017-10-28 10:07 UTC
Labels: Area - Classic
