### ISSUE TITLE
[Mage] Faerie Fire and Immunity Spells

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2127] opened 2014-12-22 15:59 UTC
Casting Ice Block will not remove Faerie Fire. It should.

**Comment by Milton3450** [comment] 2015-08-05 12:52
Confirmed. Anonying as hell.

**Comment by Rushor** [comment] 2016-12-03 18:19
DB/Spell: Mage Ice Block cancels Faerie Fire and Living Bomb

* closes https://github.com/dalaranwow/dalaran-wow/issues/2127
* commit: 611755467fd638f28e454d0065323d98c7c38ca1

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-03 18:19 UTC
Labels: Class - Mage, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-23 08:46
Works as intended on PTR.
