### ISSUE TITLE
[NPC] Hydromancer Velratha

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1033] opened 2013-12-13 13:04 UTC
http://www.wowhead.com/npc=7795

Abilities were revamped at cata. Before that, she had 4 abilities:

http://wotlk.openwow.com/spell=12491 - cast on self and allies.

http://wotlk.openwow.com/spell=12739 - main attack.

http://www.wowhead.com/spell=11086 - summons a totem (http://www.wowhead.com/npc=7785), which in turn periodically summons Skeletons of Zum'rah (http://www.wowhead.com/npc=7786), non-elite skeletons with 2186 hp that attack player for 20 sec then despawn.

Currently Hydromancer just melees.

**Comment by Rushor** [comment] 2016-11-12 13:59
DB/Creature: Hydromancer Velratha - Update SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1033

"Hydromancer Velratha - In Combat - Cast 'Shadow Bolt'"),
"Hydromancer Velratha - Friendly At 1000 Health - Cast 'Healing Wave'"),
"Hydromancer Velratha - In Combat - Cast 'Ward of Zum'rah'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 13:59 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 11:42
Works as intended on ptr.
