### ISSUE TITLE
The Quest Bitter Rivals in Kharanos is not completing correctly

### ISSUE THREAD

**Issue by Helvorn** [dalaranwow/dalaran-wow#5568] opened 2018-08-04 22:04 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
I did the beer switching, but it did not vanish from my quest tracker. It is marked as (Complete) but it did not conclude.

**Expected behaviour**:
The quest after I switched the beer, should have been completed and vanished from my quest list. 

**Steps to reproduce the problem**:

1. Get the quest completed by switching the beer on the basement of the inn
2. Should get the follow up quest Return to meredeth as can be seen on WoWhead http://www.wowhead.com/quest=310/bitter-rivals
3. 

**Include proofs for this behaviour**
http://www.wowhead.com/quest=310/bitter-rivals

**Comment by boujii** [comment] 2018-08-09 17:13
Just reviewing this.....
![image](https://user-images.githubusercontent.com/1514895/43913981-8af5451c-9bd4-11e8-877b-dea01615e79c.png)

So you have the item#2548 Barrel of Barleybrew Scalder in your bag when clicking the object#270 Unguarded Thunder Ale Barrel?

Indeed the quest is supposed to be completed by the gameobject.
![image](https://user-images.githubusercontent.com/1514895/43914309-841fcf9a-9bd5-11e8-9e06-3b6999082c4f.png)

**Comment by Golganeth** [comment] 2018-08-09 18:51
Could not reproduce it, so I'm closing for now.

**Closed by Golganeth** 2018-08-09 18:51 UTC
