### ISSUE TITLE
[Quest][Outland] Taken in the Night

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1100] opened 2014-01-09 13:36 UTC
http://www.wowhead.com/quest=10873

You have to slay cocoons in order to free the Sha'tar Warriors. The chance there's a Sha'tar Warrior in the cocoon however is far too low. Every cocoon always contains 3 NPC's (should also be 1 I assume), but I've had to wait for a full respawn of the cocoons like 3 or 4 times in order to get 6 Sha'tar Warriors freed (and there are like 8-9 cocoons every run).

**Comment by Demlock** [comment] 2015-06-04 10:26
I can confirm this. It releases all 3 hostile NPC's but it has jet to release a Sha'tari for me.

**Comment by ashido96** [comment] 2015-06-17 18:19
I'm getting an auchenai warrior about once every 15 or so spiderwebs I break open.

**Comment by Rushor** [comment] 2016-11-28 12:00
DB/Quest: Taken in the Night - Only summon one creature after Netherweb Victim was killed

* closes https://github.com/dalaranwow/dalaran-wow/issues/1100
* commit: 3e467f22c7b643364074401187f2a6b9474570ab

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 12:00 UTC
Labels: Continent - Outland, On PTR, Quests
