### ISSUE TITLE
[Northrend] [Quest] The Sum is Greater than the Parts

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3886] opened 2016-11-27 11:28 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 Nergeld's ability Punch doesn't do dmg. Even if the ability is used, it doesn't do dmg.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 The ability doesn't do dmg.

**Expected behaviour**: Tell us what should happen instead
 The Ability should do dmg.

**Steps to reproduce the problem**:

1.  Mount Nergel in The Underhalls.
2.  Use the ability.
3. 

**Include proofs for this behaviour**
 I was forced to use Roar and Stomp to try and kill the mobs, but I still died due to the failed dmg...
https://postimg.org/gallery/2gtveb9ri/
http://wowwiki.wikia.com/wiki/Nergeld
http://www.wowhead.com/npc=30403/nergeld
 I see a ticket was opened and close about this matter, but the skill still isn't working properly so I decided to make a new ticket.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-27 11:38
Punch does damage but the radius for the ability is WAY to low

**Comment by MrAndersonX** [comment] 2016-11-27 11:39
Yes, you need to move the summoned creature in order to do dmg with the ability.

**Comment by Rushor** [comment] 2016-11-27 12:16
DB/Quest: The Sum is Greater than the Parts - Increase damagerange for Punsh

* also add "ignore-pathfinding" flag for hostile creatures
* also remove movement for nergeld
* also set creatures active on spawn
* closes https://github.com/dalaranwow/dalaran-wow/issues/3886

NOTE: There is currently an issue with the creatures, that they don't start attacking one they were knockbacked. This has nothing todo with this questfix. It's an internal PTR error.

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 12:16 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:53
Works as intended on PTR.
