### ISSUE TITLE
[Rogue] Shadowstep at targets in the air

### ISSUE THREAD

**Issue by DinasJ** [dalaranwow/dalaran-wow#2254] opened 2015-02-20 12:54 UTC
Currently, when you Shadowstep a flying target, you teleport behind it, but on the ground.

It should not do that. How it's supposed to be can be seen in these videos, which are recorded on Retail TBC servers. 
https://www.youtube.com/watch?v=UhZfFo5zq_k
https://www.youtube.com/watch?v=5Jw-PGsJKo0
https://www.youtube.com/watch?v=01L5NNLTwKk

Unless someone can prove it was changed in WotLK, I believe this is how it's supposed to work.

**Comment by Golganeth** [comment] 2015-02-20 15:28
Duplicate of #1287

**Closed by Golganeth** 2015-02-20 15:28 UTC
