### ISSUE TITLE
[NPC] Felguard Legionnaire

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1908] opened 2014-09-27 09:00 UTC
http://www.wowhead.com/npc=17152

This mob should have and use two following abilities:
- Cleave for 110% weapon damage that hits the target and another adjacent creature, this one: http://www.wowhead.com/spell=15496
- Cutdown: a knockback on main target that inflicts weapon damage + 50, here: http://www.wowhead.com/spell=32009

Currently Felguard Legionnaires just melee instead.

**Comment by Rushor** [comment] 2016-11-13 20:42
DB/Creature: Add abilities for Felguard Legionnaire

* closes https://github.com/dalaranwow/dalaran-wow/issues/1908
* the creature will noe cast Cleave and Cutdown frequently in combat
* commit: 4d89b5379350f3408e04afb368b62f97573ccc0f

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 20:42 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 09:11
Works as intended on ptr.
