### ISSUE TITLE
Body and Soul Talent does not Dispel Poisons

### ISSUE THREAD

**Issue by MichaelCrow** [dalaranwow/dalaran-wow#5675] opened 2019-01-21 07:25 UTC
> Current behaviour: When you cast Abolish Disease on self, powered up by Body and Soul talent (from holy tree) it only attempts to remove poison on the first tick
> 
> Expected behaviour: It should remove poison on every tick
> 
> Steps to reproduce the problem:
> 
> Cast it on yourself with the talent speced
> ?????????????
> profit
> Include proofs for this behaviour
> 
> https://www.wowhead.com/spell=64129/body-and-soul#comments:id=959626:reply=445227
> wowhead comment
> 
> http://www.arenajunkies.com/topic/46337-macro-abolish-n-cure-disease/
> 3rd post on the thread
> "Yes but you're going to remove a lot more poison/disease if you leave abolish up and spam remove."
> By context, it clearly implies not reseting the abolish tick timers increases poison removal, implying the ticks remove poison
> 
> https://wotlk.evowow.com/?spell=552
> https://wowgaming.altervista.org/aowow/?spell=552
> https://www.wowhead.com/spell=64129/body-and-soul

Fix: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_priest.cpp

**Comment by Chenocide** [comment] 2019-01-21 17:10
#5642 Duplicate.

**Comment by Golganeth** [comment] 2019-01-26 13:57
Duplicate of #5642. Closing

**Closed by Golganeth** 2019-01-26 13:57 UTC
