### ISSUE TITLE
[Instance] Dire Maul - Main Issue

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2503] opened 2015-06-09 13:06 UTC
Dire Maul: West

Currently the dungeon cannot be completed as Immol'thar is unreachable. The demon hound is imprisoned in a barrier which is supposed to fade when all of the 5 crystal pylons in the dungeon have been cleared, and then elf summoners appear to try and contain the demon. Unfortunately, none of this happens. Without killing Immol'thar players cannot obtain the King of Dire Maul achievement, the Classic Dungeonmaster meta-achievement, and cannot make the final boss killable.

---

Dire Maul: East

The water elemental boss Hydrospawn is not spawned in the hydro (heh), but instead a bit higher, luckily that area is reachable so the boss is still killable but aggros with the other boss standing in its correct place.

> The NPC Phase Lasher may get stuck in the ground not being enable to move, sometimes not visible for players (as reported on #2855) - Edited by Golganeth

**Comment by ashido96** [comment] 2015-06-13 01:05
In my efforts to do quests for Loremaster of Kalimdor, I confirm everything stated above except for the tribute run stuff - as that cannot be currently interacted with because of the bugged door. 

Much apreciated if the barrier around Immol'thar would be removed and allow the dungeon to be run as it used to before the update until the scripting for the pylon events can be implemented.

**Comment by QjMimecha** [comment] 2015-08-28 05:10
Yup The door is still bugged

**Comment by Lothloryen** [comment] 2015-10-03 15:03
Hello there,

The Dire Maul North gate issue has been corrected, it will be applied with the next server restart.

**Comment by Lothloryen** [comment] 2015-10-03 15:35
Hello again,

After the next maintenance (not just a server restart), Immol'thar shall be doable. The players will be able to activate the 5 pylons by killing the demons around them, hence the Force Barrier around the boss will be removed.

Thank you.

**Comment by taralej90** [comment] 2015-10-03 15:40
Thank you! With this, the Dire Maul and Classic Dungeonmaster achievements will become doable.

**Comment by Lothloryen** [comment] 2015-10-03 15:56
No problem at all, thank you for your report.

Hydrospawn will have his spawn point slightly modified so he does not go up to the next floor.

**Comment by PSAlias** [comment] 2016-06-11 01:58
Additional Issues in DM East:

-**Pimgib** (_ID: 13349_) and **Lethtendris** (_ID:14327_) can be aggroed separately, when they are supposed to be part of the same encounter.

-The door to **Alzzin the Wildshaper** (_ID: 11492_) starts open, allowing players to jump down to it and skip the entire dungeon up to the final boss encounter. To open this door, you are intended to have to kill **Zevrim Thornhoof** (_ID: 11490_), which turns **Old Ironbark** (_ID:11491_) into **Ironbark the Redeemed** (_ID: 14241_), who has a script event that breaks open the door.

**Comment by DrFuler** [comment] 2016-11-10 11:43
Since there's this issue opened about Dire Maul, I decided to post it here. I have just recently tried to complete the quest Unfinished Gordok Business, given by Captain Kromcrush if you are friendly with him. However, I simply cannot loot the chest where the gauntlet is supposed to be, and even though I can see the chest and it is glowing as an object that you need for a quest, there's no option to take it when I hover it with my mouse.

I've checked a few websites and still have no clue if I'm doing anything wrong of its simply bugged. Just to be sure, I tried to loot the chest with the following conditions, but none of them helped:

a) Wearing the Gordok suit
b) Having the Gordok King buff
c) Killing the elvish prince from west wing
d) Killing the two-headed demon from west wing

Still can't get the item and complete the quest =/

http://www.wowhead.com/quest=7703/unfinished-gordok-business
http://db.vanillagaming.org/?quest=1318

**Comment by Rushor** [comment] 2016-11-10 11:44
i'm going to rework the whole dungeon soon

**Comment by DrFuler** [comment] 2016-11-10 11:48
Thank you Rushor! :) Let us know when the fixes are available :D

**Comment by Zibathy** [comment] 2016-11-17 02:26
I don't know if I'm cursed or what but the [http://wowwiki.wikia.com/wiki/Gordok_Tribute](url) doesn't spawn for me. I tried resetting the instance. So... yeah. I have no idea. 
![wowscrnshot_111616_202221](https://cloud.githubusercontent.com/assets/7729864/20373918/d457ede4-ac3a-11e6-9e77-ea1f4139c576.jpg)
![wowscrnshot_111616_202335](https://cloud.githubusercontent.com/assets/7729864/20373917/d45723a0-ac3a-11e6-9804-add1e008be7e.jpg)

**Comment by Rushor** [comment] 2016-11-17 08:48
i will fix it today on ptr

**Comment by Rushor** [comment] 2016-11-17 08:50
Dire Maul East partially bugged elite ( holding the key to Dire Maul West) 

Hi,

Well, did Dire Maul East yesterday, and while starting the Pusillin chase, I noticed he just runs through the air, walls, texture. Even tho he gets where he should be, and he can be chased properly at half the way, and he can be killed for the key, it's still a minor issues but a issue nonetheless.

**Comment by Rushor** [comment] 2016-11-17 08:51
The Left Piece of Lord Valthalak's Amulet (Dire Maul)

http://www.wowwiki.com/Quest:The_Left_Piece_of_Lord_Valthalak%27s_Amulet_%28Dire_Maul%29

As wowwiki says: "Use the Brazier of Beckoning to summon forth the spirit of Isalien and slay her." Then you have to loot quest item from her.

When you use Brazier, nothing happen. But Isalien is spawned there permanently (which is wrong, but can temporary help). The problem is that she is marked as friendly (green) so you can't attack her and therefore you can't loot quest item to complete the quest.

http://www.wowwiki.com/Isalien

http://wotlk.openwow.com/quest=8967

**Comment by Rushor** [comment] 2016-11-17 13:03
Scripts/Kalimdor: DireMaul - Rewrote the whole dungeon

* closes https://github.com/dalaranwow/dalaran-wow/issues/2503
* commit: aaeb9b9257445f79664838cd513da54eb5127eaf

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

Changes:
* Quest The Left Piece of Lord Valthalak's Amulet can now be completed by summoning Isalien
* Quest Unfinished Gordok Business can now be completed by looting the chess
* Pimgib  and Lethtendris are going infight together now
* The chess after killing King Gordok will always spawn after you talked to Mizzle the Crafty
* Ironbark the Redeemed will open the door to Alzzin the Wildshaper now (you need to kill Zevrim Thornhoof frist in order to talk to Ironbark the Redeemed)
* Pusillin's waypoints were ajusted, the hit-and-run/escortevent should work better now
* Knot Thimblejack  will give you the Leatherworking and Tailoring skills by gossip if you have a skill of 275
* 

* Added and updated the abilities and spells of following creatures:
* Immol'thar
* Warpwood Stomper
* Petrified Treant
* Petrified Guardian
* Warpwood Treant (also added waypoints for therese creatures)
* Arcane Aberration
*  Warpwood Tangler
* Tendris Warpwood (also: if you attack him, all unfriendly creatures in range will assist him, you need to clear the trash frist now)
* Whip Lasher
* Alzzin's Minion
* Netherwalker
* Hydroling and Massive Geyser will despawn now if they are not in combat
* added emotes for Shen'dralar Ancient

* added several missing door. you will need the keys in order to open the doors now
* spawned some bugs
* added waypoint movement for several ogres and Alzzin der Wildformer  + Hydrobrut + Lethtendris + 
* Gordok Mage-Lord + Gordok Brute + Gordok Mauler + Gordok Bushwacker + Gordok Reaver + Gordok Warlock + Gordok Spirit + Gordok Captain will laugh and talk periodically now
* Stomper Kreeg will sleep and dance now
* after looting the Ogre Tannin Basket, a Gordok Bushwacker will spawn and walk down the stairs
* added the growscript for Thornling (14362)
* added spawnpoints and movement and script for Eye of Immol'thar
* reworked the functions of the Crytsals for Dire Maul (all Crytsals need to be deactivated by killing the mana creatures in range in order to break the shield of Immol'thar)
* Fixed the levers befor the Dire Maul instance (they will open the door from the inner side now)
* Guard Slip\'kik can now be freezed by activating the Broken Trap gameobject
* Added the minievent for Mizzle the Crafty after King Gordok was killed

![GitHub Logo]()http://i.imgur.com/MjZnXY1.jpg)
![GitHub Logo]()http://i.imgur.com/0IoXzY5.jpg)
![GitHub Logo]()http://i.imgur.com/E4HQHeD.jpg)
![GitHub Logo]()http://i.imgur.com/HN7fpkW.jpg)
![GitHub Logo]()http://i.imgur.com/vDH9C4l.jpg)
![GitHub Logo]()http://i.imgur.com/IQvmAHT.jpg)
![GitHub Logo]()http://i.imgur.com/AcN261N.jpg)
![GitHub Logo]()http://i.imgur.com/yvdACM3.jpg)
![GitHub Logo]()http://i.imgur.com/wVEOREL.jpg)
![GitHub Logo]()http://i.imgur.com/XvShcY1.jpg)
![GitHub Logo]()http://i.imgur.com/U3ckWJO.jpg)
![GitHub Logo]()http://i.imgur.com/8Oe7Atj.jpg)
![GitHub Logo]()http://i.imgur.com/b1mTPWg.jpg)
![GitHub Logo]()http://i.imgur.com/qI8cPrQ.jpg)
![GitHub Logo]()http://i.imgur.com/7Vy2d0r.jpg)
![GitHub Logo]()http://i.imgur.com/GVZf4hC.jpg)
![GitHub Logo]()http://i.imgur.com/pEy5BAg.jpg)
![GitHub Logo]()http://i.imgur.com/DwOLzJO.jpg)
![GitHub Logo]()http://i.imgur.com/EUEtzW6.jpg)
![GitHub Logo]()http://i.imgur.com/gMvAv1s.jpg)
![GitHub Logo]()http://i.imgur.com/gBgWjT7.jpg)
![GitHub Logo]()http://i.imgur.com/XYED8WZ.jpg)
![GitHub Logo]()http://i.imgur.com/pUuZqPX.jpg)
![GitHub Logo]()http://i.imgur.com/DWlGam8.jpg)
![GitHub Logo]()http://i.imgur.com/b0OuZ2j.jpg)
![GitHub Logo]()http://i.imgur.com/hiv5nBd.jpg)

**Closed by Rushor** 2016-11-17 13:03 UTC
Labels: Instances, On PTR

**Comment by Rushor** [comment] 2016-11-17 13:09
@taralej90 @PSAlias @DrFuler @Zibathy everything is fixed now, it will be applied on the live realm soon

**Comment by meggynka** [comment] 2018-01-19 20:04
I have just tried to complete the quest Unfinished Gordok Business, given by Captain Kromcrush.
I cannot loot the chest where the gauntlet is supposed to be, and even though I can see the chest and it is glowing as an object that you need for a quest, there's no option to take it when I hover it with my mouse...  :(
![wowscrnshot_011918_210334](https://user-images.githubusercontent.com/35611571/35169294-51c063ce-fd5c-11e7-9436-94d0f3e19ab2.jpg)
