### ISSUE TITLE
Spell: Penance

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#1790] opened 2014-08-06 11:27 UTC
When a priest uses levitate on self, and tries to heal a target with penance (while levitate is active), penance bugs and gets interrupted.

As well, sometimes, when healing with penance a target that in movement, penance doesn't throw the last volley of light (3rd one); this rarely happens.

**Comment by Golganeth** [comment] 2016-06-14 23:23
First issue is a duplicate of #1672. Can't reproduce the second issue so closing up until more proof to support the bug is given.

**Closed** 2016-06-14 23:23 UTC
Labels: Class#Priest, Spells/Auras
