### ISSUE TITLE
[Rogue] Killing Spree

### ISSUE THREAD

**Issue by elorix** [dalaranwow/dalaran-wow#1364] opened 2014-03-17 23:58 UTC
theres two issues for me with this ability:

first, autoattack stops during its channeling, which shouldnt happen

second thing is the player position during the channeling, you get ported behind walls, into textures and to the floor of waters

**Comment by M0dinstaller** [comment] 2015-07-24 02:14
Can confirm this, sometimes my killing spree only hits once or twice.

**Comment by marsalandrei** [comment] 2016-02-26 13:20
Can confirm. Sometimes the hits don't chain properly to another mob, but works good enough on a single target. Bright side seems to be no falling under the map, but i am not 80 and haven't raided yet to check how it is in raids. And yes it stops the autoatatck :(

**Comment by klu69** [comment] 2016-11-29 11:12
This would be great to be fixed. But the KS talent is so hard to be scripted :D I don't know but I 've never played on a private server and the Killing Spree to work just as on retail. Never .... I thinks it's very delicate and very tricky to make it work. But yes, it will be awesome if this gets fixed. I mean it's an important skill . I hope they'll make it right , I ll update this thread with some additional  things. Keep up the goos stuff :D

**Comment by Rushor** [comment] 2016-11-29 11:14
frist issue can be fixed by me, second not

**Comment by Rushor** [comment] 2016-11-29 11:27
Game/Spells: Rogue - Killing Spree - no longer resets autoattacks

* closes https://github.com/dalaranwow/dalaran-wow/issues/1364
* commit: a037538dd9bbc2ecc22e25a2fc507644302d208d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 11:27 UTC
Labels: Class - Rogue, On PTR

**Comment by TeridanDW** [comment] 2017-10-23 09:14
Works as intended on PTR.
