### ISSUE TITLE
[NPC][Illidan Stormrage]

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3292] opened 2016-05-16 08:03 UTC
**Issue present:** Illidan can be disarmed during the fight.

**How it should work:** You shouldn't be able to disarm his Warglaive of Azzinoth (Main Hand). He should have "immunity" mask upon himself.

**Source:** 
_http://www.wowhead.com/npc=22917/illidan-stormrage_
_http://wowwiki.wikia.com/wiki/Illidan_Stormrage_(tactics)_

**Comment by Sagrath** [comment] 2016-05-16 20:55
Comfirmed
mechanic immune mask No. 4 is missing

**Comment by Rushor** [comment] 2016-11-13 11:54
DB/Creature: Illidan Stormrage - Apply immunity to disarm

* closes https://github.com/dalaranwow/dalaran-wow/issues/3292
* commit: 8cf10baa681646a8a51e39b596653020907d4b43

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 11:54 UTC
Labels: Instances
