### ISSUE TITLE
[NPC] Theramore Practicing Guard.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1006] opened 2013-12-07 06:12 UTC
http://www.wowhead.com/npc=4951

They should be attacking Theramore Combat Dummies (http://www.wowhead.com/npc=4952, each guard should attack a dummy which he's positioned against). Currently, they do nothing instead.

**Comment by Rushor** [comment] 2016-11-12 19:06
DB/Creature: Theramore Practicing Guard - Add attackemote

* closes https://github.com/dalaranwow/dalaran-wow/issues/1006
* commit: 18dd948f680aad2907ac9a5a4004dd0b5e33d43b

![GitHub Logo](http://i.imgur.com/hjpeamL.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 19:06 UTC
Labels: Continent - Classic, On PTR
