### ISSUE TITLE
Talking to trainers automatically selects top of list.

### ISSUE THREAD

**Issue by MajorSquiggles** [dalaranwow/dalaran-wow#5502] opened 2018-06-07 16:50 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Talking to a warlock trainer will automatically select whatever spell is highest on the list. Generally it takes a few seconds giving you enough time for purchase. However if you aren't fast enough it will deselect the spell you were viewing and choose whatever is at the top of the list.

**Expected behaviour**: When you talk to a trainer and you select a spell to preview, or look at it should just stay selected.

**Steps to reproduce the problem**:

1. Talk to a trainer.
2. Select a spell you are considering to purchase.
3. Wait a second or two and it will automatically select a new spell for you.

**Include proofs for this behaviour**
Zone: Kharanos
NPC: Gimrizz Shadowcog <Warlock Trainer>
Proof: https://i.imgur.com/MjymV7N.gifv

**Comment by Golganeth** [comment] 2018-08-19 16:53
Can't reproduce. Most likely a client bug.
Closing

**Closed by Golganeth** 2018-08-19 16:53 UTC
