### ISSUE TITLE
Characters disappear instantly with ALT-F4

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#2274] opened 2015-03-02 12:09 UTC
As it stands now, when somebody ALT-F4's in a pve or pvp fight, his character instantly disappears from the game, and he can log back in a few minutes later without dying.

On retail and on nearly all other private servers, when you ALT-F4, your character stays in game for 20 seconds and can therefore get killed, both by players and mobs. I have crashed many times and logged back in ghost form, both against mobs and against players, except here.
You can search on google and you'll find posts testifying this, such as this one :
http://us.battle.net/wow/en/forum/topic/7200064035

Fail pvp'ers and world pvp bullies have abused this to its limit, mostly in low level towns. You'll regularly see someone killing low levels in a town and ALT-F4'ing when near death when a high level comes to help. World pvp has become very stale because of this abuse.

**Comment by Golganeth** [comment] 2015-03-02 15:10
Duplicate of #1749

**Closed by Golganeth** 2015-03-02 15:11 UTC
