### ISSUE TITLE
[Quest] Divination: Gorefiend's Truncheon [10636]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2625] opened 2015-07-09 17:13 UTC
The quest item Gorefiend's Truncheon seems to have an abysmal or non-existent drop rate from the mob Ghostrider of Karabor. Many comments from wowhead (on the quest page) back in the TBC patches indicate that you can kill only one and always get the loot. I've now killed 8 and gotten nothing.

http://www.wowhead.com/quest=10636/divination-gorefiends-truncheon
http://www.wowhead.com/npc=21784/ghostrider-of-karabor#comments
http://www.wowhead.com/item=30800/gorefiends-truncheon

Edit: got one on my 4th set of killing the patrolling pack, 1/16 drop rate from that sample set.

**Comment by Rushor** [comment] 2016-11-29 10:47
http://www.wowhead.com/quest=10636/divination-gorefiends-truncheon#comments:id=194385

i will increase the droppchance to 75 %

**Comment by Rushor** [comment] 2016-11-29 11:00
DB/Quest: Divination: Gorefiend's Truncheon - Increase dropchance to 75 percent

* closes https://github.com/dalaranwow/dalaran-wow/issues/2625
* commit: 5d4ecd79e04bede871abbe468dac1cd28df7a8ae

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 11:00 UTC
Labels: Continent - Outland, General - Quests, On PTR
