### ISSUE TITLE
Translation to Ello / Stitches

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#1870] opened 2014-09-12 07:21 UTC
Translation to Ello is not working fully how it should, the key part in this quest that is missing is Stitches.

Upon completing this quest Abercrombie unleashed Stitches, who approached along the road from Raven Hill Cemetery. On the way to Darkshire Stitches would pause to kill any guards who attacked him. Only one Stitches NPC spawned at a time; if he was already spawned from a previous completion and had not died yet, he would not be spawned upon completion of the quest, but the guards still talked as if he was about to appear.

This excerpt can be found here: http://www.wowwiki.com/Quest:Translation_to_Ello

When I finished my quest no Stitches ever showed up.

Edit: I am on the Algalon relm.

**Comment by Golganeth** [comment] 2016-06-23 19:19
@rushor Everytime you get the quest rewarded, a Stitches will spawn. Since they don't activate until someone is close, it can lead to a big stack of Stitches after a while.

Only one should spawn. Too bad it doesn't activate though, we could maybe make it spawn closer, close to Darkshire's player location.

**Comment by Rushor** [comment] 2016-06-24 06:08
loading the grid with corescript upon questreward/accept will fix it :)

**Comment by Rushor** [comment] 2016-11-23 13:25
DB/Quest: Translation to Ello - Load Grid of Stitches on spawn

* updates https://github.com/dalaranwow/dalaran-wow/issues/1870
* commit: 719761dd09708cdb0c69c6bd1776b32b2e0060de

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 13:25 UTC
Labels: Continent - Classic, On PTR, Quests
