### ISSUE TITLE
[Shaman] Purge spell

### ISSUE THREAD

**Issue by Draculle** [dalaranwow/dalaran-wow#1963] opened 2014-10-12 08:06 UTC
Hello, the Shamans' Purge spell should dispell Gluth and some other NPC's Enrage ability, but here, they can't http://postimg.org/image/sr8bue9pj/ , please check it out, thanks,

**Comment by Rushor** [comment] 2016-11-11 20:07
proof: http://wowwiki.wikia.com/wiki/Gluth

     Ability druid challangingroar  Enrage: 

    Increases melee haste by 100% for 8 seconds. Dispellable by Rogues, Hunters, and Shamans' purge.

**Comment by Rushor** [comment] 2016-11-11 21:25
Game/Spells: Gluth Enrage - should be dispellable by Purge from Shaman

* closes https://github.com/dalaranwow/dalaran-wow/issues/1963
* commit: 205fd11e79ace9200aed990a2b3c184c919a7fa6

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment] 2016-11-23 18:14
still not dispellable. do we actually have a video source that this spell can be dispelled by shamans?

**Comment by shadovvs** [comment] 2016-11-29 23:05
I don't think Purge should be able to dispell Gluth. His Enrage ability (28371) is Dispel type: Frenzy/Enrage. Shamans purge removes Dispel type: Magic.

"Enrage effects are a type of buff that can be dispelled with a Rogue's [Shiv] or a Hunter's [Tranquilizing Shot] or a Druid's  [Soothe]. These are similar to normal boss enrages, but are short duration and can usually be healed through. "

(Soothe was changed in cataclysm to remove enrage, different version exists in wotlk that doesn't do that)

Sources:
http://wotlk.openwow.com/spell=28371
http://www.wowhead.com/spell=28371/enrage

http://wowwiki.wikia.com/wiki/Dispel_type
http://wowwiki.wikia.com/wiki/Enrage_(boss)

http://wowwiki.wikia.com/wiki/Dispel
http://wow.gamepedia.com/Dispel

**Comment by Rushor** [comment] 2016-11-30 08:26
@shadovvs thank you for the  research. /closed

**Closed by Rushor** 2016-11-30 08:26 UTC
Labels: Class - Shaman, Duplicate / Invalid Report
