### ISSUE TITLE
NPC / Quest: Spirit of Ar'tor / Lohn'goron, Bow of the Torn-heart

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#617] opened 2013-08-16 22:48 UTC
**NPC:** Spirit of Ar'tor - _21318_
**Quest:** Lohn'goron, Bow of the Torn-heart - _10537_
- **Issue present:** After completing, and turning in the quest **Demonic Crystal Prisons** _(ID:10528)_, the NPC **Spirit of Ar'tor** should spawn nearby player. Also first, NPC **Ar'tor, Son of Oronok** _(ID:10527)_ has to die, and his spirit has to be spawned then on his spot. (This could be solved with a different phase, just phase in the players in that zone so they can see **Spirit of Ar'tor** instead of  **Ar'tor, Son of Oronok** so it won't interfere with the other's people chain quest line,

That NPC offers the next part of the chain quest which is crucial to continue the chain. Only the player who has done the quest _Demonic Crystal Prisons_  can see him and noone else.
- **How it should work:** The NPC Spirit of Ar'tor should be automatically spawned upon turning in the quest **Demonic Crystal Prisons**. Also, when you complete the quest, **The Cipher of Damnation - Ar'tor's Charge** _(ID:10540)_ _(it has to say objective complete)_, this NPC still has to be there and visible to those players who have done **Demonic Crystal Prisons**.

---

http://www.wowhead.com/npc=21318/spirit-of-artor
http://www.wowwiki.com/Spirit_of_Ar'tor
http://www.wowhead.com/quest=10537

**Comment by Golganeth** [comment] 2015-01-05 12:14
Hotfixed on Algalon.

**Comment by Rushor** [comment] 2016-11-15 11:45
DB/Quest: Lohn'goron, Bow of the Torn-heart - Add phasing

* closes https://github.com/dalaranwow/dalaran-wow/issues/617
* commit: 95ef95cbd14adbe836dbb138b3d8bea311ad2f4c
* once you completed the quest Demonic Crystal Prisons, Spirit of Ar'tor  will always be visible. Else he will not be visible. Removed the hackfix from 05.01.2015.

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 11:45 UTC
Labels: Continent - Outland, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-05 10:42
Works as intended on ptr.
