### ISSUE TITLE
Arcane Mage DPS with Arcane missles not working correctly.

### ISSUE THREAD

**Issue by Sedare** [dalaranwow/dalaran-wow#2259] opened 2015-02-22 18:39 UTC
Arcane missiles mana consumption and damage is based on the buffs active on the character.
So if you cast this, with missile barrage, arcane power active or arcane blast debuff, you get consistant damage for each tick of the missles. However this is the only time it is reliably the same.

Here is the issue. When I am bursting DPS, I usually run chain Arcane Blasts until the last second of the arcane power/trinkets/IV that I have active. However on this server, the damage given is based on the abilities present for each tick of the missles. There seems to be a post-cast "check for modifiers" every time damage is dealt ( this is a guess but you should get a better grasp of the issue? ) that bases it on modifiers present. So for normal spells, this is great. But for all channeled spells, this seems to be broken. I will need to test this on Blizzard spells, and pretty much any other class with channeled spells to see how widespread this error is. 

Example. So If my arcane blast debuff expires after the 2nd tick then I lose the Multiplier on DPS on the last 3 missiles. When I had a 4stack of ABlast up with 1 second left, I would start the channel, and the first 2 ticks hit for 1400, and the last 3 hit for 650. Approx. Here is something I noticed tho. If I start a cast of arcane blast, and I have a spell power trinket active, ( thx to addon mage nuggets ) I can tell that the spell power addition lasts until the spell is completed, and once it lands the spell power modifier goes away, spell power goes back. AFTER ARCANE BLAST IS COMPLETED. But with Arcane missles, these stats change everytime a new tick of missles is issued during the channeling. Since the mana drain is designed to be calucluated at the START of the spell ( due to arcane blast debuff mana useages) and ignoring the fact that it doesnt cost mana, because this is likely more then just mages, I am sacrificing either 1. the last 3 seconds of all my modifier cooldowns to maximize DPS, or I and sacrificing mana building up to the last second use of the missle barrage that I do not get a full benefit from.

Please dont hesitate to contact me in game, or PM me on the boards if you need help reproducing these issues. 

Sedare - Mage - Horde
Guild - Certified Insane

**Comment by Darthblaider** [comment] 2015-02-24 06:07
The spell also weirdly scales the rank to the level of the mob you use it on. So doing low level content at level 80, the spell is useless.
I understand your concern for having a spell not work properly, but you shouldn't use arcane missiles EVER without having that proc. It uses too much mana for how little damage it does, and it really is, bare minimum damage.

**Comment by Sedare** [comment] 2015-02-24 06:21
The main issue is the mana used building up to the max usage of the spell while modifiers are active. Since the dps drops when modifiers expire mid cast of missiles this will lower your mana to dps efficiency. I know the mana cost is free. Everyone knows that.

I want to get the most out of stacking the Arcane Blast debuff with modifiers active, and get the intended return out of the spell when it is cast. If I cant get the return out of the cast, then I basicly have 3 seconds of wasted modifiers because I have to burn missiles earlier then I normally would. About 1 GCD early. Thats Huge during arcane burst phases. Im sure if you are stacked at 4, and have cloak proc, trinket active 2nd trinket proc, and mirror images tier 4 piece bonus, that you will pretty much just lose a 25k arcane blast crit because of this bug. You will have to cast it earlier. I will gladly burn mana during this phase and slow dps during off modifier rotation to maximize DPS.

**Comment by Rushor** [comment] 2017-03-14 13:53
Fixed one part of the issue. The spell no longer gets downranked if you target lower level mobs

Core/Spells: mark Arcane Missiles aura as negative. Was downranking the spell when targetting low level mobs due to effect 1 flagged as possitive.
* commit: da8e151126f7bbe5952a5614c10f628f06e2cf0f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-14 13:53 UTC
Labels: Class - Mage

**Comment by TeridanDW** [comment] 2017-10-26 09:46
This:

> The spell no longer gets downranked if you target lower level mobs

seems to work as intended on ptr.
