### ISSUE TITLE
Victorious Challenger

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2414] opened 2015-05-22 11:27 UTC
http://www.wowhead.com/npc=30012/victorious-challenger

The NPCs are perma-hostile. They should be talked to and then they'd get hostile and engage in combat. ATM they're attacking anyone and everyone on sight.

**Comment by ConradSilverwind** [comment] 2015-05-23 11:40
Confirmed.

**Comment by Rushor** [comment] 2016-11-15 18:39
DB/Creature: Victorious Challenger & Brunnhildar Challenger - should be friendly by default

* commit: bd0f0ec39076325686a69f6db02af93288f06a84
* if you talk to them while being on the quest http://www.wowhead.com/quest=13423/defending-your-title or http://www.wowhead.com/quest=12971/taking-on-all-challengers, they will change to the hostile faction

![GitHub Logo](
http://i.imgur.com/pxTIYsm.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 18:39 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-03-30 09:51
Not everything from this report is on PTR currently:

>  - also add fightemotes for Brunnhildar Challenger if they are out of combat

is on ptr and working.

> if you have the aura http://wotlk.openwow.com/spell=55012., the creature will be friendly to you, after you talked to them with gossip option, they will be hostile

is NOT on ptr, creatures are still friendly by default.
![image](https://cloud.githubusercontent.com/assets/6797611/24498535/756d7f08-1547-11e7-85d9-6bdbd44e8d3e.png)

So changing the label to:

**Comment by Rushor** [comment] 2017-03-30 09:53
k thanks, some fix for it was added in another ticket (i remember we already talked about that, but i cannot find the ticketnumber anymore)

**Comment by TeridanDW** [comment] 2017-03-30 09:56
#4306 ?
