### ISSUE TITLE
[Quest][Outland] Subdue the Subduer

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#884] opened 2013-10-07 14:42 UTC
**Quest Subdue the Subduer** - _(ID:11090)_
- **Issue present:** After using the quest item, **Soul Cannon** _(ID:32825)_ on the NPC, **Reth'hedron the Subduer** _(ID:22357)_, nothing happens. You are only damaging him with it and he is "tank and spanking" you. You are able to kill him that way but the credit isn't given at all.
- **Abilites from Reth'hedron the Subduer**: _Cripple_ _(ID:41281)_ and _Shadow Bolt_ _(ID:41280)_
- **How it should work:** Once you use the item on him, he should start attacking you and when you are at 10% of his HP, the nearby warlocks, **Deathshadow Spellbinder** _(ID:23342)_ should spawn and start casting channeling spell on a Dark Portal and force him to enter the Dark Portal where you get the credit. At 1% he becomes immune to any damage and simply becomes an invalid target, as soon as he enter the portal and dissapears, you get the credit.

_There is also a little of roleplay from him_:

> During Subdue the Subduer:

_I WILL CRUSH YOU LIKE A GNAT!_
_What do you hope to accomplish from this, insect?_
_You are making me angry, mortal!_

> Defeated:

_You will regret this, mortal! Reth'hedron will return... I will have my vengeance!_

He may or may not yell any of these quotes at any given time you fight him.

http://wowpedia.org/Reth'hedron_the_Subduer

---
- **Videos of how it should work:** 

_http://www.youtube.com/watch?v=JnMwGSYwDFE_
_http://www.youtube.com/watch?gl=NL&hl=nl&v=HYxi0ljcS2Y_
_http://www.youtube.com/watch?v=qGCedG8tHnM_

---

http://www.wowhead.com/quest=11090
http://www.wowhead.com/item=32825
http://www.wowhead.com/npc=22357/rethhedron-the-subduer#comments
http://www.wowwiki.com/Reth'hedron_the_Subduer

**Comment by Augur89** [comment] 2015-05-12 17:37
Still an issue, confirmed.

**Comment by jonanone** [comment] 2016-06-07 13:11
The Subduer now casts some spells in combat, gives quest credit on death and says some role-play lines. Still missing some role-play actions. The changes will be applied to the live realm soon.

Letting the issue open for future improvements.

**Comment by Golganeth** [comment] 2016-06-09 14:55
Needs some polishments but now it works so much better. The respawn timer for the Subduer is too long too.

**Comment by Golganeth** [comment] 2016-06-09 14:55
Needs some polishments but now it works so much better. Also the respawn timer for the Subduer is too long.

**Comment by Rushor** [comment] 2016-11-29 10:52
Scripts/Quest: Implement roleplayevent for Subdue the Subduer

* closes https://github.com/dalaranwow/dalaran-wow/issues/884
* the roleplayevent where the creature runs to the portal was added
* respawntimer was reduced to ~5 minutes

![GitHub Logo](http://i.imgur.com/rGXuChP.jpg)
![GitHub Logo](http://i.imgur.com/Vf2Q6tM.jpg)
![GitHub Logo](http://i.imgur.com/pzGcmal.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 10:52 UTC
Labels: Continent - Outland, General - Quests, On PTR
