### ISSUE TITLE
[Quest][Northrend][HowlingFord] Into The World Of Spirits

### ISSUE THREAD

**Issue by linkz619** [dalaranwow/dalaran-wow#1557] opened 2014-04-28 14:10 UTC
The Regent Pouches do not spawn anywhere, checked everywhere to no avail

Edit:
They do not spawn on the mentioned location, instead they spawn at a different one not indicated, search the wreckage at  62,51

**Comment by Golganeth** [comment] 2015-01-05 12:37
Fixed.

**Comment by martijnhaah** [comment] 2015-06-09 13:07
its on the wrong boat.

**Comment by catta000** [comment] 2015-10-02 23:07
confirmed - from where the pouch should be according to the map swim north to another shipwreck.

**Comment by exyz3** [comment] 2015-11-30 21:56
There is no item, i searched both ships for 20min+ wtf....

**Comment by epaulito** [comment] 2016-04-09 17:26
confirmed as of now that pouch respawn point is still incorrect. From the ship marked in your map, swim north till you get to the shipwreck near a waterfall.

**Comment by Lothloryen** [comment] 2016-05-04 11:13
It has been corrected, it will be live after the next realm restart.

**Comment by Golganeth** [comment] 2016-06-10 13:58
The gobject is nowhere to be found in the correct location.

**Comment by jonanone** [comment] 2016-07-26 18:03
It seems like Reagent Pouch has multiple spawn points, so now it will spawn in one of the three spawn points randomly each time. The three points are:

· 62.3, 59.3
· 62.0, 57.6
· 62.1, 51.7

Also its respawn time has been reduced to 3 min (from 5 min)

These updates will be applied to the live realm soon.

**Comment by Edzero** [comment] 2016-10-25 16:16
Not spawning at any of the points on PTR.

**Comment by Rushor** [comment] 2016-11-25 13:51
the quest works indeed http://i.imgur.com/DG846Aa.jpg

DB/Quests/Howling Fjord: Into the World of Spirits

Reagent pouch now has 3 spawn points at it will spawn randomly in one of them each time.

Closes https://github.com/dalaranwow/dalaran-wow/issues/1557
* commit: f06f0e7e4dea96fb80ef949d00975c6a4904aef9

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 13:51 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-03 11:49
Works as intended on ptr.

Note to players, in-game quest helper is showing you only 1 of the 3 possible locations for the bag. Please check these coordinates:

> · 62.3, 59.3
> · 62.0, 57.6
> · 62.1, 51.7

Provided by @jonanone
