### ISSUE TITLE
Azuremyst-Bloodmyst Flight Path broken

### ISSUE THREAD

**Issue by Woider001** [dalaranwow/dalaran-wow#2400] opened 2015-05-20 17:39 UTC
The flight path between The Exodar and Blood Watch doesn't work, when trying to use the flight master in either city, a message pops up explaining that you have no connecting flight paths, even if you have visited both the flight master outside The Exodar, and the one in Blood Watch.

**Comment by martijnhaah** [comment] 2015-05-20 18:38
saw a similar issue at trinitycore a few days ago.... seems to be it is rendering you in another continent.

**Comment by n-ghost** [comment] 2015-05-21 10:47
Confirmed.

**Comment by n-ghost** [comment] 2015-06-09 17:19
Seems to be fixed atm.

**Comment by Kelderen** [comment] 2016-07-07 12:06
Just letting you know it doesn't work at the moment, in Kirin Tor. It shows you as being in Zul'Aman instead of Exodar.

**Comment by Rushor** [comment] 2016-12-02 19:36
this was fixed with https://github.com/TrinityCore/TrinityCore/commit/a8f447b9eff366129296d6fcad97bca1767d2fd5

**Closed by Rushor** 2016-12-02 19:36 UTC
Labels: Fixed - On PTR

**Comment by TeridanDW** [comment] 2017-04-02 13:50
Works as intended on ptr.
