### ISSUE TITLE
[Quest] Help Tavara

### ISSUE THREAD

**Issue by BryceLovesGaming** [dalaranwow/dalaran-wow#3518] opened 2016-06-28 19:54 UTC
**Description**:
The quest Help Tavara is currently uncompleted. 
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The quest does not update when you heal the NPC Tavara
**Expected behaviour**: Tell us what should happen instead
Tavara should be healed and the quest should update
**Steps to reproduce the problem**:
1. Be a priest Draenei 
2. accept the quest from Guvan in Azure Watch
3. Travel to the location and attempt to heal Tavara

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Guvan: http://www.wowhead.com/npc=17482/guvan
Tavara: http://www.wowhead.com/npc=17551/tavara
Quest: http://www.wowhead.com/quest=9586/help-tavara
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment] 2016-06-29 12:42
On Algalon it can be completed by healing the NPC with [Lesser Heal](http://wotlk.openwow.com/spell=29170) (it will stand up) and then casting [Power Word: Fortitude](http://wotlk.openwow.com/spell=1243).
This is not intended and it's caused by the the SmartAI script that is linked to the NPC; *npc_garments_of_quests* - from the "Garments of" quests, which involves healing and fortifying the different NPCs.

This however works differently on PTR/live realm;

**PTR:**
- The NPC is always at full health, but you can complete the quest by just healing it. (no AIName, SmartAI script)
- The NPC is permanently on its knees.
- The NPC doesn't despawn at all and it seems the quest can only be completed once per restart/kill+respawn.

**Live realm:**
- The NPC respawns with 69,6% health, which should be perhaps a bit lower (proof needed)
- The NPC is on its knees and rises as soon as the NPC is healed by [Lesser Heal](http://wotlk.openwow.com/spell=29170), however the quest doesn't complete until [Power Word: Fortitude](http://wotlk.openwow.com/spell=1243) is cast.
- The quest can be completed but you have to heal and then fortify (wrong AI script). After you do so, the NPC despawns properly and the quest can be completed by different players once it respawns.

---------------

**Current issues on live realm:**
- The quest should complete right after healing the NPC with [Lesser Heal](http://wotlk.openwow.com/spell=29170)  (Draenei racial, renew and other spells should also work, currently it's not the case)
- The NPC should respawn with lower health, around 15-20%~ (proof needed)
- There's no quotes at all, the NPC simply despawns (this is probably intended, proof needed)

**Comment by Rushor** [comment] 2016-11-15 12:01
DB/Quest: Help Tavara - Update spellhitscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/3518
* commit: 2b43ca8eb7beddb894d6929af21c870456575888
* you can now heal Tavara
* each time you heal Tavara, you will get the questcredit (this means the quest can be done by several player)
* removed the old corescript, so healing Tavara by spell: wotlk.openwow.com/spell=2050, wotlk.openwow.com/spell=2052, wotlk.openwow.com/spell=59544 or wotlk.openwow.com/spell=139 will always give you the questcredit

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 12:01 UTC
Labels: Continent - Classic, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-01 11:00
Hello, the quest is working on ptr, player gets the credit, however i would like to suggest a better solution for it:
``` sql
UPDATE `creature` SET `curhealth` = 15 WHERE `guid` = 63161; 
-- Tavara SAI
SET @ENTRY := 17551;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,4,0,53,0,100,0,9,200000,10000,10000,80,@ENTRY*100+00,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Received Heal Between 9-200000 - Run Script");
-- Actionlist SAI
SET @ENTRY := 1755100;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,91,8,0,0,0,0,0,1,0,0,0,0,0,0,0,"On Script - Remove Flag Standstate Kneel"),
(@ENTRY,9,1,0,0,0,100,0,2000,2000,0,0,64,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tavara - On Script - Store Targetlist"),
(@ENTRY,9,2,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,12,0,0,0,0,0,0,0,"Tavara - On Script - Set Orientation <unsupported target type>"),
(@ENTRY,9,3,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Say Line 0"),
(@ENTRY,9,4,0,0,0,100,0,3000,3000,0,0,33,17551,0,0,0,0,0,12,0,0,0,0,0,0,0,"On Script - Quest Credit ''"),
(@ENTRY,9,5,0,0,0,100,0,4900,4900,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"On Script - Evade");
-- Add texts
DELETE FROM `creature_text` WHERE `entry` = 17551; 
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(17551,0,0,'%s thank $n.',16,0,100,2,0,0,0,0,'');
```

How it looks now:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6797611/24578156/8d9f40aa-16e3-11e7-931d-a2bd54003309.gif)
