### ISSUE TITLE
[NPC] Killing Earthgrab Totem grants XP

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4949] opened 2017-10-24 09:16 UTC
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When killing the Earthgrab Totem summoned by Skullsplitter Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=670 in Stranglethorn Vale you receive experience.

In addition the Earthgrab Totem also moves.

**Expected behaviour**: Tell us what should happen instead
You should not receive experience for killing the totem.

The totem should be stationary.

**Steps to reproduce the problem**:
1. Go to Ruins of Zul'mamwe in Stranglethorn Vale
2. Aggro Skullsplitter Witch Doctor and let him spawn Earthgrab Totem
3. Kill the Earthgrab Totem and observe as you gain experience

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Skullsplitter Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=670

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment] 2017-10-24 09:34
Thank you for the report @Imbarawr.
Creature https://wowgaming.altervista.org/aowow/?npc=6066 is not marked as totem but as guardian, that's why he grats exp and is also been spammed (should be only 1(Earthgrab Totem) active at the same time).
![image](https://user-images.githubusercontent.com/6797611/31935485-9f055958-b8b7-11e7-8b58-66757dd11a52.png)

**Comment by TeridanDW** [comment] 2017-10-26 08:52
I don't think this is the correct way to fix the issue, however it will prevent these totems to grant exp to players.

**Suggested fix:**
``` sql
UPDATE `creature_template` SET `flags_extra` = 64 WHERE `entry` = 6066; 
```

**Closed** 2017-10-28 18:33 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update, Suggested fix, Works - but it needs improvements.

**Comment by TeridanDW** [comment] 2017-10-29 10:48
Works as intended on PTR.
