### ISSUE TITLE
[Paladin] Avenger's Shield from Protection Spec is removing Divine Shield

### ISSUE THREAD

**Issue by Khronos-** [dalaranwow/dalaran-wow#2748] opened 2015-07-30 11:16 UTC
Title is self explanatory: On several occasions I was killed under the bubble effect from Divine Shield by an Avenger's Shield.

This is not working as intended and is an extreme source of imbalance in the game, making Paladin's survival in PvP extremely low when in the presence of an enemy Prot Paladin.

wowwiki on Divine Shield: "The only abilities in the game that can dispel Divine Shield are the Priest's Mass Dispel and the Warrior's Shattering Throw." Source: http://wowwiki.wikia.com/Divine_Shield

**Comment by Golganeth** [comment] 2015-08-05 13:52
Couldn't reproduce the problem after heavy testing. If it happened on "several" occasions I'm sure you'll be able to provide some kind of screenshot or evidence. If you're able to, we'll make sure to figure out what the problem is.

Until then, closing up.

**Closed by Golganeth** 2015-08-05 13:52 UTC
