### ISSUE TITLE
[Quest] text: An Unholy Alliance (part 2)

### ISSUE THREAD

**Issue by Zindai** [dalaranwow/dalaran-wow#1937] opened 2014-10-04 18:25 UTC
Quest: <b>An Unholy Alliance</b> (part 2) - <a href="http://www.wowhead.com/quest=14353/an-unholy-alliance">Wowhead</a>
Quest giver: <b>Bragor Bloodfist</b> - <a href="http://www.wowhead.com/npc=36273">Wowhead</a>

<b>The issue</b>:
1) The quest Progress text is missing.
2) The quest Completion text is missing.

<b>How Progress should look</b> (based on Wowhead): 
<code>Did you find the Ambassador, < name >? Did you kill him?</code>

<code>I will not have the Scourge gain a foothold in Kalimdor. We've fought too hard to allow them easy access to our cities.</code>

<code>At least their crone still numbers among the living. She might be stupid enough to allow the Scourge in her home, but she must have sense enough to know she'd lose everything if she took the 'power' they offer.</code>

<b>How Completion should look</b> (based on Wowhead): 
<code>Good work, < class >!</code>

<code>You've done the Horde proud by stopping the Scourge from setting down roots on our soil. An act like that deserves a reward, and the Forsaken have enough lying around that I'm sure they can spare a few things.</code>

<code>We may not know everything they've done in the Downs, but we'll find out. They can't slink around in the dark forever.</code>

**Comment by Rushor** [comment] 2016-11-23 12:51
DB/Quest: An Unholy Alliance - update request + offer reward text

* closes https://github.com/dalaranwow/dalaran-wow/issues/1937
* commit: d4099c2eb557e9d9452a735f445ad229a9a7e789
* remember to delete the cache folder before testing

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 12:51 UTC
Labels: Continent - Classic, On PTR, Quests
