### ISSUE TITLE
NPC: Risen Longrunner

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#844] opened 2013-09-29 15:50 UTC
These mobs should be constantly casting their sprint ability that makes them run as fast if not faster than an epic mount.
On retail, it used to be extremely annoying to run past these.

http://www.wowhead.com/npc=25350#comments:id=491128:reply=71603

**Comment by Rushor** [comment] 2016-11-09 11:19
DB/Creature: Risen Longrunner - Add ability 'Sprint' in combat

* closes https://github.com/dalaranwow/dalaran-wow/issues/844
* commit: 7d1348e9207a33987c7e40a7d9e0a20b0488ca3a

http://i.imgur.com/jHvETN3.jpg
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-09 11:19 UTC
Labels: Continent - Northrend
