### ISSUE TITLE
[NPC] Thornvine Creepers not skinnable via herbalism

### ISSUE THREAD

**Issue by balkai** [dalaranwow/dalaran-wow#3891] opened 2016-11-27 23:54 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: The Thornvine Creepers in Howling Fjord are unable to be skinned with herbalism, they were skinnable on retail via herbalism and wowhead confirms it.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Mouse pointer does not indicate they are skinnable via herbalism.
**Expected behaviour**: Tell us what should happen instead
They should be skinnable via herbalism.
**Steps to reproduce the problem**:

1. Kill the mob and loot it
2. Try to skin it
3. Impossible

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Thornvine Creeper ID=23874
Herbalism Skill ID=182

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-28 08:38
http://www.wowhead.com/npc=23874/thornvine-creeper#herbalism

**Comment by Rushor** [comment] 2016-11-28 11:22
DB/Creature: Thornvine Creepers - Add herbalism loot

* closes https://github.com/dalaranwow/dalaran-wow/issues/3891
* commit: 349112d49b45916bf392b9f6c717bff3aabc093c

![GitHub Logo](http://i.imgur.com/41xNdur.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 11:22 UTC
Labels: Continent - Northrend, On PTR
