### ISSUE TITLE
[NPC] Quests for buffs from Mangletooth.

### ISSUE THREAD

**Issue by deseth38** [dalaranwow/dalaran-wow#2003] opened 2014-10-23 20:02 UTC
Mangletooth - http://www.wowwiki.com/Mangletooth_(pre-Cataclysm)
"(...)After completing Blood Shards of Agamaggan, he would accept [Blood Shards] in exchange for buffs in the following quests:
[20] Agamaggan's Agility (repeatable)
[20] Agamaggan's Strength (repeatable)
[20] Razorhide (repeatable)
[20] Rising Spirit (repeatable)
[20] Spirit of the Wind (repeatable)
[20] Wisdom of Agamaggan (repeatable)(...)"
Everything is fine, but there is a one problem, The quests don't exchange the [Blood Shards] for buffs. In fact the NPC gets [Blood Shards] from us, but for free, I mean, He will not buff up us.

**Comment by Portotada** [comment] 2015-01-25 00:42
Confirmed!

**Comment by Demlock** [comment] 2015-04-17 22:39
Confirmed

**Comment by Rushor** [comment] 2015-04-19 10:55
```sql
-- 
-- Mangletooth SAI
SET @ENTRY := 3430;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,20,0,100,0,889,0,0,0,75,16618,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mangletooth - On Quest 'Spirit of the Wind' Finished - Cast 'Spirit of the Wind'"),
(@ENTRY,0,1,0,20,0,100,0,5042,0,0,0,75,16612,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mangletooth - On Quest 'Agamaggan's Strength' Finished - Cast 'Agamaggan's Strength'"),
(@ENTRY,0,2,0,20,0,100,0,5043,0,0,0,75,17013,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mangletooth - On Quest 'Agamaggan's Agility' Finished - Cast 'Agamaggan's Agility'"),
(@ENTRY,0,3,0,20,0,100,0,5044,0,0,0,75,7764,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mangletooth - On Quest 'Wisdom of Agamaggan' Finished - Cast 'Wisdom of Agamaggan'"),
(@ENTRY,0,4,0,20,0,100,0,5045,0,0,0,75,10767,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mangletooth - On Quest 'Rising Spirit' Finished - Cast 'Rising Spirit'"),
(@ENTRY,0,5,0,20,0,100,0,5046,0,0,0,75,16610,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mangletooth - On Quest 'Razorhide' Finished - Cast 'Razorhide'");
```

**Comment by Rushor** [comment] 2016-11-23 10:27
DB/Quest: Mangletooth - Add auras on the player after questcompletion

* closes https://github.com/dalaranwow/dalaran-wow/issues/2003
* commit: bd6d4b7c1cf3cc205aab2adbe6a02bbffabcb644

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 10:27 UTC
Labels: Continent - Classic, On PTR, Quests
