### ISSUE TITLE
[NPC] [Mulgore] - Kyle the Frenzied

### ISSUE THREAD

**Issue by xnemeyethx** [dalaranwow/dalaran-wow#5653] opened 2018-12-30 21:39 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Kyle just stays in one place. 
**Expected behaviour**: Tell us what should happen instead
He should be running around the village.
**Steps to reproduce the problem**:

1.  Go to Bloodhoof village
2. Search for Kyle. 

**Include proofs for this behaviour**
https://www.wowhead.com/npc=23616/kyle-the-frenzied

**Include Screenshots from the issue if necessary**

**Comment by xnemeyethx** [comment] 2019-01-08 17:02
Checked it today and he runs around the village. So, it works I guess ;)

**Comment by Golganeth** [comment] 2019-01-14 19:10
Works as intended, so I'm closing.

**Closed by Golganeth** 2019-01-14 19:10 UTC
