### ISSUE TITLE
Achievement: Mine Sweeper

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#213] opened 2013-07-28 12:50 UTC
Achievement Mine Sweeper - 1428

Issue: Once you land on a bomb or walk over them, they are not exploding or knocking you away. Here,you do get damage as intended (500) and you see a small world npc trigger following you and then dissapearing after some time.

Both visual effect and knocking effect is missing.

How it should work: You are supposed to land on a mine, get knocked, land down and jump quickly back on a mine (you have maybe 1 seconds before achievement criteria fails and is not met) and repeat that 10 times until achievement pops.

Video how it should work:

http://www.youtube.com/watch?v=Jmn8b6--3-c

http://www.wowhead.com/achievement=1428/mine-sweeper
http://wotlk.openwow.com/achievement=1428

WoWhead Quote: 
I just tested this, and it's actually absurdly easy, though it is possible it was changed in one of the most recent builds from what you saw.

You don't need to actually hit the mines continually. Considering the mines themselves won't activate before you hit the ground, there is a very small grace period built in to the timer of the achievement. To get it, simply go to the center of the field, and start running into mines. As soon as you land, sprint to the nearest mine by where you landed, and you'll continue your chain.

Hitting multiple mines at once counts. I got it in four jumps for hitting one, then three, then four, then three again.

**Comment by Prljoman** [comment] 2015-08-31 02:48
After big "patch" was released, this mine field was somewhat fixed. No more little elementals spawning, mines are knockbacking character and doing damage. After that "patch", I tried couple of times and days to do this achievement and with no success. I agree with all Crispybuilt said, I had this achievement on my 3 chars on retail and I got them easily. Here, like I said no luck even after hitting 12 mines in a very short time with almost no pause between each mine. So, minefield was repaired but triggering and getting achievement is still probably bugged.

**Comment by Rushor** [comment] 2016-06-07 20:34
https://github.com/TrinityCore/TrinityCore/commit/4fbffab5f8a43410c4e4487e15f22a5173b9bc9e

merged

**Comment by Golganeth** [comment] 2016-06-08 19:17
The achievement doesn't work on PTR.
The amount of mines seems low too, and the range that triggers the explosions.

**Comment by Rushor** [comment] 2016-06-09 16:45
0a78fa13c04f6156fbf4a1c488a778808ee2d0de
- seems like the db part wasn't applied
- http://i.imgur.com/ygXDIPD.jpg if you are fast enough you will get it know :P

**Closed by Rushor** 2016-06-09 16:45 UTC
Labels: Achievements, Miscelaneous, Northrend

**Comment by Golganeth** [comment] 2016-06-10 19:06
It is obtainable but not as intended. The lands don't have to be consecutive, you just have to be fast currently.
The range at which mines trigger seems to be too small.

**Comment by Rushor** [comment] 2016-06-10 20:08
8f3c9d63f2d0ec20302fabc5d2df52fa6def3439
- kay, increaded the radius to trigger the knockbackspell to 8 diameter

**Comment by Golganeth** [comment] 2016-06-14 12:03
Note: Condition for consecutive lands still missing.

**Comment by ImprezaWoW** [comment] 2016-11-26 15:05
You can not fly over the mines anymore, not sure when was this fixed, [but the bombs fly up to you like in the video.](https://www.youtube.com/watch?v=bkEZAqH-FoI)
