### ISSUE TITLE
Penance interrupt while levitating

### ISSUE THREAD

**Issue by theepikkreep** [dalaranwow/dalaran-wow#3458] opened 2016-06-14 22:44 UTC
I'm really into levitating, and I guess I'm not the only one.
So I happen to be casting it a lot and am often under the effect of it.
One thing that bugs me however is that when you cast any channeled spell, Penance for example, my character starts casting but after the first tick it jus cancels it.
This can sometimes be frustrating when you're healing your raid and your most powerful cast isn't really doing much.

So basically you can't fully cast any channeled (maybe channeled targeted) spell while levitating, which worked on retail.
When the cast cancels, it says "Interrupted" in red letters in the upper middle of the screen.

I don't know the reason for this happening, but maybe you can figure it out, and fix it at best.
One thing I do know however is that it may have something to do with the direction your character is aiming: while casting penance, my character automatically looks directly at the target, now when neither the target nor me moves, penance works for all three ticks. So it may be the automatic positioning that leads to this bug.

Should be quite easy, levitate, target someone (not yourself), cast Penance, see if it goes for the full 3 ticks. Done.
It works when cast on self, but in most cases, I want to heal the tank, and that's where it doesn't.

Penance ID=#47540 
Levitate ID=#1706

Screenshot included right at the pint of the first tick.
![wowscrnshot_061516_002624](https://cloud.githubusercontent.com/assets/2260486/16062249/3b34dc20-3292-11e6-91e7-8bfceb6a2470.jpg)

**Comment by Golganeth** [comment] 2016-06-14 23:25
Duplicate of #1672

**Closed by Golganeth** 2016-06-14 23:25 UTC
