### ISSUE TITLE
[NPC] Plagueroach

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2042] opened 2014-11-05 10:28 UTC
Right now, they give XP when killed, when they shouldn't give any.
Also, according to wowhead comments, they should respawn almost instantly after killed.

http://www.wowhead.com/npc=28599#comments

**Comment by Rushor** [comment] 2016-11-17 20:22
DB/Creature: Plagueroach - Remove xp gain + reduce respawntime

* closes https://github.com/dalaranwow/dalaran-wow/issues/2042
* commit: 98d07f9281101279fdea5619a0820d5a3105146d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 20:22 UTC
Labels: Continent - Northrend, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 18:49
Works as intended on ptr.
