### ISSUE TITLE
[Quest] Thane of Voldrune missing prequests.

### ISSUE THREAD

**Issue by Jindra555** [dalaranwow/dalaran-wow#3731] opened 2016-09-28 20:20 UTC
Thane of Voldrune
http://www.wowhead.com/quest=12255

Has prequests:
Secrets of the Flamebinders
www.wowhead.com/quest=12222
and
Thinning the Ranks
http://www.wowhead.com/quest=12223

Should be fixed according to the changelog from 22.07. (as per this report https://github.com/dalaranwow/dalaran-wow/issues/741) but ingame it's still broken.

**Comment by Rushor** [comment] 2016-11-14 09:47
DB/Quests/Grizzly Hills: Secrets of the Flamebonders + Thinning the ranks.

Both quests have to be completed in order to unlock The Thane of Voldrune quest.

* commit: c7f8ba42fbed93d81b2a7fa3ebce65c87f98308b
* maybe the fix wasn't applied, but on ptr it's working fine. once you completed http://wotlk.openwow.com/quest=12292, you can do http://wotlk.openwow.com/quest=12223 and http://wotlk.openwow.com/quest=12222. After completition you can accept http://wotlk.openwow.com/quest=12255

![GitHub Logo](http://i.imgur.com/1pTBxPm.jpg)
![GitHub Logo](http://i.imgur.com/uw0JOZ3.jpg)
![GitHub Logo](http://i.imgur.com/uksolkz.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 09:47 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-03-31 10:28
Works as intended on ptr.
