### ISSUE TITLE
[Minor] Water Walking/Path of Frost and misses

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3074] opened 2015-12-30 17:18 UTC
Water Walking and Path of Frost gets removed by Hunters mark.
The spells state "Any damage will cancel this effect", Hunters mark does not do damage.

**Comment by Darthblaider** [comment] 2016-08-02 18:57
Hunters mark can dispel path of frost. Confirmed.

**Comment by Rushor** [comment] 2016-12-01 10:48
Game/Spells: Path of Frost - no longer gets removed by Hunters mark or non-damage spells

* closes https://github.com/dalaranwow/dalaran-wow/issues/3074
* commit: 00fe944494e5c886a8973e4c1248c6a9a694b6f4

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-01 10:48 UTC
Labels: Class - Death Knight, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-20 19:15
Works as intended on PTR.

**Comment by Lukas45** [comment] 2017-10-20 19:40
@TeridanDW Is this tested with damage that misses too? Because that's what the OP originally said.
Like a level 10 mob trying to hit a level 80, which misses with a spell/melee.

**Comment by TeridanDW** [comment] 2017-10-21 07:01
Hello, yes @Lukas45, path of frost is been removed only when a damage (autoattack/spell/ability) hits the DK now.
