### ISSUE TITLE
[NPC] Enslaved Minion

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2038] opened 2014-11-05 10:15 UTC
Enslaved Minions don't use their ability.

http://www.wowhead.com/npc=32260

**Comment by Rushor** [comment] 2016-11-11 10:17
DB/Creature: Implement Enslaved Minion SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/2038
* now they will cast the spell 31976 2 seconds after starting combat on the next freindly unit in 25 yards range ( in general the summoner warlock) and repeat it every 30 seconds
* commit: 3be43beb9aa6ccfba04e1326b31762e2ce354ec9

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 10:17 UTC
Labels: Continent - Northrend, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 19:01
Works as intended on ptr.
