### ISSUE TITLE
[Quest][GO] Cleansing Felwood

### ISSUE THREAD

**Issue by Spellity** [dalaranwow/dalaran-wow#1841] opened 2014-08-30 21:05 UTC
Greetings.

I encountered an issue regarding a low lvl quest.

I'll explain. In Felwood there is a quest "Cleasing Felwood": http://wotlk.openwow.com/quest=4102

after that it follows cleansing the plants with "Cenarion Plant Salve": http://wotlk.openwow.com/quest=4107

, when you apply it on corrupted plants, you should loot "Night Dragon's Breath": http://wotlk.openwow.com/item=11952

but the salve doesn't cleanse the plants.

Please assist.

Regards,

Spelly

**Comment by Rushor** [comment] 2016-11-23 13:09
Scripts/Kalimdor: Felwood Corrupted Plants - Add Spawn of 'Cleansed Flowers'

* closes https://github.com/dalaranwow/dalaran-wow/issues/1841
* commit: 091eba3bd36da99cf133556ac516c6b63b1c6225
* once you "healed" the corrupted plant, a new cleansed one will spawn 

goids:
	GO_CLEANSED_NIGHT_DRAGON  = 164881,
	GO_CLEANSED_WINDBLOSSOM   = 164884,
	GO_CLEANSED_WHIPPER_ROOT  = 174687,

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 13:09 UTC
Labels: Continent - Classic, On PTR, Quests
