### ISSUE TITLE
[Quest chain] The Calling -> Armaments of War

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1351] opened 2014-03-15 18:39 UTC
After completing the quest The Calling (http://wotlk.openwow.com/quest=8315), a player should have one version of the quest Armaments of War available (based on his class), instead of all versions.

Warrior: http://wotlk.openwow.com/quest=8316
Druid: http://wotlk.openwow.com/quest=8382
Shaman: http://wotlk.openwow.com/quest=8380
Priest: http://wotlk.openwow.com/quest=8379
Rogue: http://wotlk.openwow.com/quest=8378
Hunter: http://wotlk.openwow.com/quest=8377
Paladin: http://wotlk.openwow.com/quest=8376
Mage/Warlock: http://wotlk.openwow.com/quest=8381

After doing the quest on my hunter, I was able to take four Armaments of War rewards from the NPC Geologist Larksbane (http://wotlk.openwow.com/npc=15183).

**Comment by Rushor** [comment] 2016-11-23 20:49
DB/Quest: Fix AllowableClasses for Armaments of War quests 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1351
* commit: 88844d85a2ae7b05a97b962be9cdbb42125d431a

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 20:49 UTC
Labels: Continent - Classic, On PTR, Quests
