### ISSUE TITLE
Mind-numbing potion on Twin Valkyr

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#3702] opened 2016-09-07 00:50 UTC
Currently it is possible for rogues to use mind-numbing potion before the special ability is cast and therefore increasing the cast time on shields by 50%, making it trivial to kill shields.

**Comment by Jokey123** [comment] 2016-09-07 10:37
If the rogue has his Mind-numbing Poison on the Valkyr, the cast time of the Twin's Pact is longer, therefore giving you MORE time to take down the shield. It makes it easier rather than harder. Some bosses aren't immune to Poison Effects, and this is one of them. This is not a bug.

**Comment by tripleslash** [comment] 2016-09-07 11:46
This did not work on retail

**Comment by robinsch** [comment] 2016-09-26 20:38
On PTR. Priority - Critical.

**Comment by Rushor** [comment] 2016-11-12 14:15
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 14:15 UTC
Labels: Instances, Mechanics, On PTR, Priority - Critical

**Comment by plznoz** [comment] 2016-11-21 01:58
I've observed a guild use Curse of Tongues on twins, making the Twin Pact's take 19.5 seconds instead of 15. Maybe your fix change also fixes this, if not you might want to consider fixing that spell as well.
http://wotlk.openwow.com/spell=11719
