### ISSUE TITLE
[Rogue]Hack and slash

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5150] opened 2017-12-02 15:20 UTC
[//]: # (INFORMATION ABOUT TAGS) 
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Hack and slash does proc from special abilities but once in a blue moon and recorded by recount as white attack. Hack and slash does not deal equil damage after ability it proc'd. Hack and slash can be glancing. Hack and slash can miss even if you are hit capped for special ablities and poisons.
**Expected behaviour**: Tell us what should happen instead
Hack and slash proc from special abilities as tooltip says 5% and it is recorded by recount as Hack and Slash. Hack and slash can't be glancing since it should be considered as special ability like Sinister strike for instance. Same rules of miss chances applies to Hack and slash as for any other special ability. If hack and slash procs after special ablitity it will do the same damage as ability before the proc. Hack and slash should always proc from main hand even in case if you keep a fist weapon in the main hand and a sword/axe in the off hand. In that situation your extra attacks from sword/axe specialization procs will be done by the fist weapon with +5% crit chance if you have talents there. After whole day of testing hack and slash didn't proc of itself not even once.

**Steps to reproduce the problem**:
1st case (fan of knives+blade flurry) i was doing fan of knives on two dummies so the hack and slash % should be doubled))
1. Stay away from dummies so you cannot reach them with white attack
2. Use blade flurry
3. Spam fan of knives
![wowscrnshot_120217_165520](https://user-images.githubusercontent.com/20444046/33516322-f899aab2-d781-11e7-8400-e177327200e0.jpg)
![wowscrnshot_120217_165524](https://user-images.githubusercontent.com/20444046/33516323-fb158540-d781-11e7-9acb-7451114cbe0e.jpg)
As you can see it is doing more damage than special ability
The % chance is too low

2nd case (Sinister strike+blade flurry)
1. Go to the dummy
2. Stay at 90 degree angle so you can not hit with white attacks
3. Spam Sinister strike.
![wowscrnshot_120217_162425](https://user-images.githubusercontent.com/20444046/33516088-bc916c52-d77d-11e7-846c-0e3f40868126.jpg)
![wowscrnshot_120217_162616](https://user-images.githubusercontent.com/20444046/33516089-c582e28c-d77d-11e7-8a09-281d2062fac5.jpg)
As you can see hack and slash not doing same damage as special ability
The % chance is too low

3rd case (Hack and slash glancing)
1. Do normal rotation.
2. Check recount 
![wowscrnshot_120217_144002](https://user-images.githubusercontent.com/20444046/33516365-ae6a33b6-d782-11e7-90e6-284f0e887b0f.jpg)

4th case (Hack and slash white attacks)
1. Attack dummy
![wowscrnshot_120217_180644](https://user-images.githubusercontent.com/20444046/33516946-163ea342-d78c-11e7-9eaf-13ed397cd92c.jpg)
![wowscrnshot_120217_180647](https://user-images.githubusercontent.com/20444046/33516947-180fdeb6-d78c-11e7-94c9-255b8984371c.jpg)
Here you can see that avarage damage is the same of melee and hack and slash. Hack and slash should be only performed by main hand so avarage damage should be higher.

**Include proofs for this behaviour**
relevant issue #3617
http://wowwiki.wikia.com/wiki/Hack_and_Slash

**Comment by Jiaku** [comment] 2017-12-08 11:56
Any news?

**Comment by robinsch** [comment] 2017-12-10 15:33
So, I can't really confirm this without some kind of proof. Because HnS has clearly effect SPELL_EFFECT_ADD_EXTRA_ATTACKS. This is the same effect as Sword Specialization which should not copy the damage of the spell that caused it to proc, this is just a basic additional melee swing.

And since it's a normal melee swing it should also count for the hitoutcome, for example miss or glancing.

The proc chance is fine, law of large numbers. But what can happen is that it gets proced on MH and then by offhand too but since extra attacks are only executed on swing it will count as one proc, but there we need a proof for too.

> Proc flag 0x00000014, chance = 5, charges - 0
=================================================
  02 Successful melee attack
  04 Successful attack by Spell that use melee weapon
=================================================

**Comment by Fluffybully** [comment] 2017-12-10 16:05
Ola,

As some1 who play rogue all the time.

H&S:

5% proc chance on melee abilities ie Sinister, FoK, Eviscerate, Rupture etc.. 
5% on MH and OH white hit
Does always MH weapon damage and has normal white attacks flags ie miss, crit etc..

On recount H&S procs show up and add up under "Melee" when procced via normal melee hits

**Comment by Jiaku** [comment] 2017-12-10 20:04
@robinsch It is not as same as Sword Specialization since it says use melee attack(can use MH and OH) Hack and Slash (use only MH damage "The extra attack is always done by the weapon in the main hand.") 
according to the "roc flag 0x00000014, chance = 5, charges - 0
=================================================
02 Successful melee attack
04 Successful attack by Spell that use melee weapon
================================================="
1.this will trigger MH and OH damage.
2.If it  should be recourded as melee attack why in recount appears "HnS records as 0.2% to 0,4%"?
3.If it would work correctly there would be difference from melee damage(white attacks) and melee (hack and slash) but as shown in screeshot there is no difference since hack and slash should be only performed from mainhand but can proc from both OH and MR.
"04 Successful attack by Spell that use melee weapon"
4. Is that means that if my Sinister strike crits for 10k the HnS proc after will be 10k? if so(it is intended) it never appered.
5.HnS procs after Fan of knives should consider each target you hit with FAN(and have 5% for each target) rather then 5% over all.
@Fluffybully It shoudn't proc after Evis "Hack and Slash can proc off both normal attacks (white damage) and attacks such as Killing Spree, Blade Flurry, Sinister Strike and Fan of Knives."
http://wowwiki.wikia.com/wiki/Hack_and_Slash

**Comment by Fluffybully** [comment] 2017-12-11 11:50
> 4. Is that means that if my Sinister strike crits for 10k the HnS proc after will be 10k? if so(it is intended) it never appered.

No it's not supposed to be a 10k hit. It's gona be a normal bonus melee hit that's all.

`"5.HnS procs after Fan of knives should consider each target you hit with FAN(and have 5% for each target) rather then 5% over all. So if i hit 10 targets with FAN each target shoud have 5%.`
Correct.

> @Fluffybully It shoudn't proc after Evis "Hack and Slash can proc off both normal attacks (white damage) and attacks such as Killing Spree, Blade Flurry, Sinister Strike and Fan of Knives.

Yes it does proc from Eviscerates, Envenoms, Ruptures, Killing Spree, SS, FoK, BF, Hemorrhage and so on.

**Comment by Fluffybully** [comment] 2017-12-11 11:58
http://prntscr.com/hly15c

Bonus pic where bonus attacks can be glancing hits.

**Comment by Jiaku** [comment] 2017-12-11 13:22
@Fluffybully Please carefully read this link http://wowwiki.wikia.com/wiki/Hack_and_Slash It shoudn't proc after evis.
@Fluffybully regarding your screenshot
- Patch 1.3.0 (07-Mar-2005): Added a visual to Sword Specialization "proc" that will now show up in the combat log as well.
your combat log doesn't say that it was hack and slash proc but it should.

**Comment by Fluffybully** [comment] 2017-12-11 13:31
> such as
Please =).

> your combat log doesn't say that it was hack and slash proc but it should.
http://prntscr.com/hlzc2f
Say what?

> @Fluffybully Please carefully read this link http://wowwiki.wikia.com/wiki/Hack_and_Slash It shoudn't proc after evis.
http://prntscr.com/hlzdmg

And for the love of god stop using just wowwiki it's ignorant.

**Comment by Jiaku** [comment] 2017-12-11 13:50
@Fluffybully  Do you have anything to backup your words? A trustworthy resource would be nice.
Your screeshow shows it was regular melee attack. If it was HnS it sould say (HnS melee instead)

**Comment by Fluffybully** [comment] 2017-12-11 14:08
I don't know if you're trolling or not but it clearly says [17:50:50.909] Nosfe gains 1 extra attacks from Nosfe's Hack and Slash and it's from method's worldoflogs

**Comment by Jiaku** [comment] 2017-12-11 17:29
@Fluffybully Yeah i misread it, my bad. So i guess it procs after evis afterall but it the HnS should be from main hand. RIght now it does proc from off hand as well.

**Comment by alexuktc** [comment] 2017-12-11 18:35
To clarify his last sentence - it should proc from the off hand weapon as well, but it should always be a main hand attack.

**Comment by robinsch** [comment] 2017-12-13 11:27
Hey, after reading through the comments this is my input: It's basicly the same as Sword Spec, it will always perform a additional weapon swing from main hand (no matter what hand has caused it to proc.

As @Fluffybully confirmed the combat log thing is working too.

So the only valid issue here is that it should not proc from Eviscerate?

**Comment by Fluffybully** [comment] 2017-12-13 11:29
> So the only valid issue here is that it should not proc from Eviscerate?

It should. I even linked retail logs of Evi proccing H&S

**Comment by robinsch** [comment] 2017-12-13 11:34
So there is nothing here?

**Comment by Fluffybully** [comment] 2017-12-13 11:36
Since am not playin Dalaran-WoW my self, I cannot really say what's the issue with H&S, but I can at least provide info on how it should work with legit proof.

**Comment by robinsch** [comment] 2017-12-13 11:37
Okay, I will close this report until someone provide me with something that is clearly wrong with this Talents. Thanks everyone.

**Closed by robinsch** 2017-12-13 11:37 UTC
Labels: Class - Rogue, On Hold - Need Proof, Priority - High

**Comment by Jiaku** [comment] 2017-12-13 15:49
@robinsch So nothing is gonna be fixed, am i reading this right? On a side note what kind of proof need to be provided to get things fixed?

**Comment by Jiaku** [comment] 2017-12-13 16:31
HnS and white attack, i did provide screenshot(4th case). White attacks were made with main hand and off-hand. HnS should performe proc from main hand only, but average damage is the same of white attacks and HnS. My guess is that HnS can perform from main hand and off-hand right now.

**Comment by Fluffybully** [comment] 2017-12-13 16:33
Upload me a raw log of a ~2-3min dummy fight and I'll tell u right away if does OH hits.

**Comment by robinsch** [comment] 2017-12-13 16:34
@Jiaku I can clearly tell you that HnS proc is mainhand only swing.

**Comment by alexuktc** [comment] 2017-12-13 18:42
Reopening this. 

Here is a recount of 10 minutes on a target. You can clearly see that Hack and Slash has the same values as my melee attacks (with small differences that will be attributed to procs as I was doing a test with my raiding gear). I have to point out that the lowest damage for normal hits, critical strikes and glancing blows are made by the offhand weapon, seeing how it has the lowest damage and speed (I am using a 2.6 MH and 1.5 OH) and Hack and Slash has the same values. And with 80% ArP and 1300 low end on my main hand I cannot be hitting a boss target for 640 damage, seeing how my lowest off hand attacks on the same target are for 505.

During this test I noticed that Hack and Slash no longer misses. I thank you for this quick update. Now all that is left is to make them all Main Hand attacks.

https://imgur.com/eQz3wCR

**Comment by robinsch** [comment] 2017-12-13 19:46
As I said before, every hit done by HnS is a mainhand hit. It also goes through the exact same code as white hits.

> During this test I noticed that Hack and Slash no longer misses. I thank you for this quick update.

There was nothing changed at all.

**Comment by Jiaku** [comment] 2017-12-30 05:35
> As I said before, every hit done by HnS is a mainhand hit. It also goes through the exact same code as white hits.
In this case could you please explain why average damage of mainhand+offhand(melee) is the same as damage of mainhand(HnS)?

**Comment by Jiaku** [comment] 2017-12-30 06:16
So out of curiousity i decided to equip 5-11 damage sword and here is recount screenshots.
![wowscrnshot_123017_090154](https://user-images.githubusercontent.com/20444046/34451747-5adf12c8-ed41-11e7-9608-9f8ac13fda66.jpg)
![wowscrnshot_123017_090158](https://user-images.githubusercontent.com/20444046/34451748-5da2074a-ed41-11e7-8e58-7fcbc5e44bb4.jpg)
![wowscrnshot_123017_090202](https://user-images.githubusercontent.com/20444046/34451771-cc688f6e-ed41-11e7-8d5f-ceefb09e8f35.jpg)
![wowscrnshot_123017_090849](https://user-images.githubusercontent.com/20444046/34451751-61737264-ed41-11e7-902b-f19c370ea4f6.jpg)
As you can see on 2nd screenshot that crit is actially lower than hit. I assume that crit was made with off-hand where hit was made with mainhand.
Do you have enough proof to fix it now?

**Comment by Jiaku** [comment] 2018-01-05 01:11
Hello,

**Comment by Jiaku** [comment] 2018-01-05 08:56
> "5.HnS procs after Fan of knives should consider each target you hit with FAN(and have 5% for each target) rather then 5% over all. So if i hit 10 targets with FAN each target shoud have 5%.

Same applies to Blade flurry. I have never seen during AoE HnS procs on multiple targets.

**Comment by AttendantTock** [comment] 2018-04-21 21:43
Hello,

I published results from a test **on current PTR** in: https://github.com/dalaranwow/dalaran-wow/issues/5242
Indicating that H&S seems to be correctly granting **extra attacks from the Main Hand only**.

I will publish results from different tests covering different aspects of this talent in the coming days.
