### ISSUE TITLE
[NPC] Demon of the Orb

### ISSUE THREAD

**Issue by Salamagundi** [dalaranwow/dalaran-wow#837] opened 2013-09-28 02:26 UTC
In the quest "Fragments of the Orb of Orahil" the last step takes place in Dustwallow Marsh in the cottage of Tabetha, where she spawns the mob "Demon of the Orb" and the questee is supposed to kill it. This mob now spawns automatically by her cottage, this can be painful for the unwary as the mob is a lvl 40 elite that hit 10 times as hard as everything else at this level. It needs to be convinced to crawl back into it's orb and only come out when commanded.

**Comment by Rushor** [comment] 2016-11-15 10:57
DB/Creature: Demon of the Orb - should not respawn

* closes https://github.com/dalaranwow/dalaran-wow/issues/837
* commit: 321b335c51276dbb9a5b206711ab81cadb47b816

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 10:57 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 17:00
Works as intended on ptr.
