### ISSUE TITLE
[NPCs] Nekrum Gutchewer and Shadowpriest Sezz'ziz

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1047] opened 2013-12-17 11:56 UTC
Both are a part of Seargant's Blu gauntlet in Zul'Farrak.

Nekrum (http://www.wowhead.com/npc=7796) should have 1 ability: 

Shadowpriest (http://www.wowhead.com/npc=7275#encounter) should have and use 4 abilities:

http://wotlk.openwow.com/spell=15537 - his main attack, scaled to level.
http://wotlk.openwow.com/spell=8362 - heal which he uses on himself and\or allies.
http://wotlk.openwow.com/spell=12039 - fat heal that he can use as well.
http://wotlk.openwow.com/spell=13704 - aoe fear around him which he uses if player gets close to him.

Currently both mobs are just meleeing.

**Comment by Rushor** [comment] 2016-11-11 10:34
DB/Creature: Implement SAI for Nekrum Gutchewer and Shadowpriest Sezz'ziz

* closes https://github.com/dalaranwow/dalaran-wow/issues/1047
* commit: 6209de0edab671e82fccae2caa1fb3daf7f76085

"Nekrum Gutchewer - On Aggro - Cast 'Berserker Charge'"),
"Nekrum Gutchewer - In Combat - Cast 'Fevered Plague'"),
"Nekrum Gutchewer - In Combat - Cast 'Hamstring'");

"Shadowpriest Sezz'ziz - In Combat - Cast 'Shadow Bolt'"),
,"Shadowpriest Sezz'ziz - Friendly At 700 Health - Cast 'Renew'"),
"Shadowpriest Sezz'ziz - Friendly At 1500 Health - Cast 'Heal'"),
"Shadowpriest Sezz'ziz - In Combat - Cast 'Psychic Scream'");

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 10:34 UTC
Labels: Instances, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 11:23
Works as intended on ptr.
