### ISSUE TITLE
[NPC] Scarlet Disciple.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1017] opened 2013-12-11 07:16 UTC
http://www.wowhead.com/npc=4285

Mob should have 3 abilities: Heal (http://www.wowhead.com/spell=11642), Renew (http://www.wowhead.com/spell=11640) and Holy Smite (http://www.wowhead.com/spell=9734). First two he should use one himself when injured and on injured allies, second is his main attack.

Currently it just melees instead.

**Comment by Rushor** [comment] 2016-11-12 18:33
DB/Creature: Update Scarlet Disciple SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1017

"Scarlet Disciple - In Combat - Cast 'Holy Smite'"),
"Scarlet Disciple - Between 0-50% Health - Cast 'Heal' (No Repeat)"),
"Scarlet Disciple - Between 0-25% Health - Cast 'Renew' (No Repeat)"),
"Scarlet Disciple - Friendly At 400 Health - Cast 'Renew'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 18:33 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 12:10
All spells are casted as intended, however i would like to suggest to:
 - add flag 64 to spell holy smite
 - add flag 1 to spell heal and renew
 - add "Scarlet Disciple - Friendly At 700 Health - Cast 'Heal'"
Note: Both friendly actions with flag 1 again.

These are just suggestion and can be ignored so marking as:
