### ISSUE TITLE
[Quest][Classic] The Emitter

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#2388] opened 2015-05-20 08:44 UTC
http://www.wowwiki.com/Quest%3AThe_Emitter
http://www.wowhead.com/quest=9312/the-emitter

There is a cutscene missing upon completion.

Image of Technician Dyvuun (http://www.wowhead.com/npc=16550/image-of-technician-dyvuun) should appear at the emitter and the following exchange should occur:

_Image of Technician Dyvuun says_: By the seven Ata'mal crystals! Others have survived the crash! Zhanaa, is that you? It is so good to see you again!
_Image of Technician Dyvuun says_: And who do we have here? No doubt th... crzzzk ...ade this communication I give you greetings fro... psshzzzk... Azure Watch.
_Image of Technician Dyvuun says_: Judging by your signal, we put you... ust southeast of the larger part of the island we crashed onto. Cross the Crystalbrook River to ge... kshhhhk zzzt. Sorry, there's a lot of stat...
_Technician Zhanaa says_: This is great news! Your efforts have indeed saved us, <name>!

The image should despawn shortly afterwards.

Currently, nothing happens instead.

**Comment by Rushor** [comment] 2016-11-26 10:22
DB/Quest: Add endevent for quest: The Emitter

* closes https://github.com/dalaranwow/dalaran-wow/issues/2388
* commit: d2506fa878161eeca8f0fad76b5512c523b54b61

![GitHub Logo](http://i.imgur.com/sMdUCYp.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 10:22 UTC
Labels: Continent - Classic, On PTR, Quests
