### ISSUE TITLE
[NPC] Urga'zz

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1910] opened 2014-09-27 09:18 UTC
http://www.wowhead.com/npc=18976

This mob should have and use 3 following abilities:
- Power Burn: http://www.wowhead.com/spell=32003 (similar to those guys here: https://github.com/dalaranwow/dalaran-wow/issues/1909)
- Drill: inflicts weapon damage + X, similar to Heroic Strike, scaled to level: http://www.wowhead.com/spell=32004
- Throw Proximity Bomb: http://www.wowhead.com/spell=34095

This one is similar to what Shadowmoon Technicians use in Blood Furnace (http://www.wowhead.com/npc=17414, http://www.wowhead.com/spell=30846), the only difference is that it should summon object 183449 instead of 181877.

Also, Urga'zz should /say following quotes: 
- Work harder!

Currently Urga'zz says nothing and uses only melee attacks.

**Comment by Rushor** [comment] 2016-11-11 11:00
DB/Creature: Implement Urga'zz SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1910
* commit: 0814b61b8f907c904ebb85caaa811473d6ded4a7

"Urga'zz - In Combat - Cast 'Drill'"),
"Urga'zz - In Combat - Cast 'Power Burn'"),
"Urga'zz - In Combat - Cast 'Throw Proximity Bomb'");

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed** 2018-03-28 12:54 UTC
Labels: Area - Outland, Fixed - Waiting for PTR update
