### ISSUE TITLE
Broken Distract ability

### ISSUE THREAD

**Issue by Real-Scaramouche** [dalaranwow/dalaran-wow#4935] opened 2017-10-22 09:13 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
_Rogue ability Distract is not working properly. Instead of distracting mobs into selected direction it taunts the mobs._
**Expected behaviour**: Tell us what should happen instead
_Distract ability should distract mobs into selected direction._
**Steps to reproduce the problem**:

1.  Go in stealth
2. Thow Distract near any aggresive mob
3. Mob aggros you instead of the point of Distract ability

**Include proofs for this behaviour**

Proof of broken Distract ability video:
https://vimeo.com/239309353

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/spell=1725/distract

**Include Screenshots from the issue if necessary**

**Comment by TeridanDW** [comment] 2017-10-22 10:18
Hello and thank you for the report @Real-Scaramouche.
I've tried to reproduce this issue few times on PTR, but I can't. 
![image](https://user-images.githubusercontent.com/6797611/31860927-646ab37a-b72b-11e7-8fb4-982f735a1eac.png)

Any additional information would be really appreciate here.

**Comment by alexuktc** [comment] 2017-10-22 11:48
The only issue I can state about the skill (and I am not certain if it is fixed or not) is that if you cast it on a mob while in stealth and then take aggro, the mob will not move from its location until the 10 second duration of Distract is over. I used to group with hunters to make it a bit easier for them to kill elites this way.

**Comment by Real-Scaramouche** [comment] 2017-10-22 11:51
I'm not sure what else to say. It just stopped working after yesterdays bug fix update.
Maybe try to reproduce this issue on live server?
I would assume that Distract works as it should. It just doesn't register that I'm in stealth whenever I use it. So mobs then aggroing me. But otherwise stealth works just fine so.. it's something weird about it..

**Comment by TeridanDW** [comment] 2017-10-24 08:20
Can someone confirm if this is still happening on live server?

**Comment by alexuktc** [comment] 2017-10-24 15:52
I can only confirm what I have posted before. Casting Distract while invisible causes the mobs to not move from their position until Distract duration runs out.

**Comment by Real-Scaramouche** [comment] 2017-10-24 16:21
I can confirm that it still draws the aggro even when used in stealth at any given distance.

**Comment by Desecrator** [comment] 2017-10-26 10:10
I can confirm too. Ability still draws aggro.

**Comment by robinsch** [comment] 2017-11-01 09:03
@TeridanDW I can't confirm that on PTR too.

**Comment by TeridanDW** [comment] 2017-11-01 09:12
I have just retested this issue on PTR again and it still works properly. I don't know what to say, seems it's a live only problem that does not exits on PTR.
@Lothloryen

**Comment by Real-Scaramouche** [comment] 2017-11-04 21:06
Well I think I found out how you can reproduce the issue on PTR. It seems that when I respeced my talents distract is now working.. I switched back to my old talents and distract is not working again.. so here's my talent tree with broken distract ability.
![wowscrnshot_110417_225806](https://user-images.githubusercontent.com/32997636/32409449-a63b9cea-c1b4-11e7-830a-b81e7880cf49.jpg)

**Comment by robinsch** [comment] 2017-11-05 14:56
@Real-Scaramouche Thanks a lot! Some how it was caused by Master Poisoner talent.

Fixed on PTR.

**Closed by robinsch** 2017-11-05 14:56 UTC
Labels: Class - Rogue

**Comment by Lothloryen** [comment] 2017-11-06 12:48
Working now, thanks @robinsch . Already on live.

**Comment by szattara** [comment] 2017-11-07 23:34
![wowscrnshot_110817_002650](https://user-images.githubusercontent.com/19749419/32523448-9ae315c6-c41b-11e7-8c25-16c392227cbe.jpg)

happened after distract. 
been distracting npc's non stop for the last 5mins nothing happens.
idk worth reporting. but yeh something made it fly.
