### ISSUE TITLE
[Quest] Blood in the Water QuestID=12810 | What Do You Feed a Yeti, Anyway?

### ISSUE THREAD

**Issue by budthechud** [dalaranwow/dalaran-wow#3431] opened 2016-06-10 20:13 UTC
**Description**: Lord-Commander Arete at Death's Rise wants you to fill the Gore Bladder with the blood of 10 Ravenous Jaws.

**Current behaviour**: Sharks are resting at the bottom of the seabed and can be targeted but spells cannot be used against them.  Behavior resembles issues with The Occular- mob appears in one place to the player but is actually present in another.

**Expected behaviour**: Sharks should be targetable by abilities and able to be killed.

Steps to reproduce the problem**:
1. Go to area surrounding Onslaught Harbor
2. Find shark on seabed
3. Use abilities

Location: http://i.imgur.com/mq5n0f2.jpg
Shark not getting hit: https://gfycat.com/DangerousSelfreliantCommabutterfly

WoWhead Quest Page: http://www.wowhead.com/quest=12810/blood-in-the-water

NPC ID: 29392
NPC WoWhead Page: http://www.wowhead.com/npc=29392/ravenous-jaws

**Comment by Rushor** [comment] 2016-06-10 20:23
Hi!
Today I got this random daily quest, "What Do You Feed a Yeti, Anyway?" (id 14112) from Savinia Loresong (NPC 34912) at the Argent Tournament. It seems I have to take "Fresh Chum" (item 47036) from the "Buckets of Fresh Chum" (object 195352) and use it on the water to attract sharks and loot meat pieces.

Well, the item works but the shark (or occasional vrykul) that spawns goes immediately to the sea bed and I can't attack it as it says it is out of range (with me being at melee range).

I think the sharks should stay on the surface and be killable for the quest to work.

By the way, I had the same problem with some sharks on Onslaught Harbor while doing "Blood In the Water" (id 12810), but in this case some of the sharks are targettable.

**Comment by Rushor** [comment] 2016-11-25 11:40
DB/Quest: Blood in the Water | What Do You Feed a Yeti, Anyway? - Enable swimming for affected water creatures

* closes https://github.com/dalaranwow/dalaran-wow/issues/3431
* the creatures are now attackable at their visual position ids: (35061,35060,35071,35072,29392)
* commit: 96a8952277698d25960592d8e1ef39aa5bf1593e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 11:40 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-11-01 10:50
Works as intended on PTR.
