### ISSUE TITLE
[NPC] Enemies at the Court of Skulls and Angrathar the Wrathgate Are Friendly

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2930] opened 2015-09-29 06:31 UTC
The Colossal Abomination (#27605), Plague Eruptor (#27611), Angrathar Necrolord (#27603), Frail Construct (#27604), Frenzied Gargoyle (#27691), Angrathar Aberration (#27631) and the Reconstructed Wyrm (#27693) are all friendly, unattackable, and do not attack. 

Openwow.com incorrectly has them labeled as having a friendly reaction to Horde and Alliance.

_These scourge are enemies of the living should be hostile and attack on sight._

**Comment by npmusicftw** [comment] 2015-10-01 06:53
http://www.wowhead.com/npc=27605/colossal-abomination
http://www.wowhead.com/npc=27611/plague-eruptor
http://www.wowhead.com/npc=27603/angrathar-necrolord
http://www.wowhead.com/npc=27604/frail-construct

etc. etc. etc.

**Comment by Rushor** [comment] 2016-11-15 14:17
DB/Creature: Factionchange for several creatures at Wrathgate

* closes https://github.com/dalaranwow/dalaran-wow/issues/2930
* commit: 9bc0f23fd604bd221f02d3dea33d5b9b99c73135
* they are hostile now. added flagextra, so they will not be killed by other creatures (endless animation of fight will be profided with that addition)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 14:17 UTC
Labels: Continent - Northrend, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 19:19
Works as intended on ptr.
