### ISSUE TITLE
[NPC] Scarlet Scout.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1014] opened 2013-12-11 07:09 UTC
http://www.wowhead.com/npc=4281

Mob should have 2 abilities: Shoot (http://www.wowhead.com/spell=6660) and Fire Shot (http://www.wowhead.com/spell=6979) and use them accordingly.

Currently mob just melees.

(this time for real)

**Comment by Rushor** [comment] 2016-11-12 18:27
DB/Creature: Add SAI for several creatures in tirisfal

* commit: a9203cd600f52899b79067da96f7c678aab12c4d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 18:27 UTC
Labels: Instances, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 15:08
Works as intended on ptr.
