### ISSUE TITLE
[Quest][Classic] Challenge Overlord Mok'Morokk

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1876] opened 2014-09-15 14:59 UTC
quest id: http://www.wowhead.com/quest=1173/deprecated-challenge-overlord-mokmorokk

Currently this quest is on autocomplete.

How it is supposed to work:
- few seconds after accepting quest, Overlord Mok'Morokk (http://www.wowhead.com/npc=4500) turns hostile and /says "Puny %race% wanna fight Overlord Mok'Morokk? Me beat you! Me boss here!"
- Overlord Mok'Morokk melees for 290 - 391 (as per http://wotlk.openwow.com/npc=4500) and has one ability: Wide Swipe (http://www.wowhead.com/spell=6749), stun for a 5 sec which he uses every 15 sec or so.
- Overlord Mok'Morokk is UNKILLABLE, meaning you can't get him past 1 hp and if you actually manage to bring him to 1 hp, you can kite him infinitely. When he loses aggro for any reason and there are no more targets available for him, he turns friendly, runs away and despawns, without giving a credit.
- when you get Overlord Mok'Morokk to 30% of his hp, he should turn friendly again, /yell "Me scared! Me run now!", run away from the village in southeast direction where he despawns roughly near http://www.wowhead.com/npc=4503. Player should get a quest credit then.
- Overlord should respawn in village again so other players can get\do quests involving him as well after 10 minutes or so.

**Comment by Demlock** [comment] 2015-04-17 22:45
Confirmed, currently the quest involving beating him completes automatically.

**Comment by testagle** [comment] 2016-06-27 20:42
Confirmed, and still bugged.

**Comment by Rushor** [comment] 2016-11-11 12:51
DB/Quest: Implement Challenge Overlord Mok'Morokk

* closes https://github.com/dalaranwow/dalaran-wow/issues/1876

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 12:51 UTC
Labels: Continent - Classic, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-03 09:39
Works as intended on ptr, however i would like to add few improvements:
 - when he reach 30%hp or less and turns friendly to use stop combat and regeneration off actions
 - reduce his respawn timer - currently its 20 mins (he is quest giver so that slows other people's progress), between 5mins and 10 mins should be fine.
