### ISSUE TITLE
NPC Spammer: Elemental Slave [2359]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1580] opened 2014-05-05 11:59 UTC
[Elemental Slave](http://wotlk.openwow.com/npc=2359)

![asd](https://cloud.githubusercontent.com/assets/5057942/2877479/b2c51526-d44c-11e3-83d1-d6cd8e9a379c.png)

**Comment by Rushor** [comment] 2016-11-12 20:30
DB/Creature: Elemental Slave - Remove Chatspamming

* closes https://github.com/dalaranwow/dalaran-wow/issues/1580
* commit: 75dd3dbd0bc387fb10d4986af70db2a33f2331e9

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 20:30 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 12:03
Works as intended on ptr.
