### ISSUE TITLE
[Shaman] Magma totem crit chance / crit multiplier / hit

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#3884] opened 2016-11-27 10:14 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: Magma totem (shaman spell) has a too low crit damage multiplier, and has a too low crit chance.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently Magma totem does not benefit from crit rating at all (see proof below).
Also the crit damage multiplier is 2.0 instead of 2.09.
It also doesn't seem to benefit from hit rating.

**Expected behaviour**: Tell us what should happen instead
Magma totem should benefit from crit rating, and the crit damage multiplier should be 2.09.
Should also not miss with hit cap.

**Steps to reproduce the problem**:

1. Spec elemental. For example: [http://wotlk.openwow.com/talent#hAh0qcdftGfzAohxxco](http://wotlk.openwow.com/talent#hAh0qcdftGfzAohxxco)
2. Use Magma totem
3. Observe damage, crit chance and misses.
4. Repeat with different amounts of crit/hit (full gear / no gear)

**Include proofs for this behaviour**

**LIVE** Log showing 209% crit modifier and 42% crit chance (from 01 Dec 2009):
[http://www.worldoflogs.com/reports/r46piz1iavhxn11b/sum/damageDone/?s=6227&e=6725](http://www.worldoflogs.com/reports/r46piz1iavhxn11b/sum/damageDone/?s=6227&e=6725)
![http://i.imgur.com/BR6rMks.png](http://i.imgur.com/BR6rMks.png)
>[22:30:17.823] Magma Totem VII Magma Totem Nerubian Burrower 1094
>[22:30:17.823] Magma Totem VII Magma Totem Nerubian Burrower *2286*

2286/1094=2.089579524680073
Crit multiplier 2.09.

**Dalaran-wow:**
>Magma Totem VII's Magma Totem hits Grandmaster's Training Dummy for 3 Fire.(1053 Overkill)
>Magma Totem VII's Magma Totem hits Grandmaster's Training Dummy for 3 Fire.(2109 Overkill) (Critical)

2113/1057=1.999053926206244
Crit multiplier only 2.00, should be 2.09.

Crit chance on dalaran (823 crit / 129 hit): ![http://i.imgur.com/wQavmEx.png](http://i.imgur.com/wQavmEx.png):
![http://i.imgur.com/CQJsnIR.png](http://i.imgur.com/CQJsnIR.png)

Crit chance on dalaran (with 0 crit rating, 0 hit rating):
![http://i.imgur.com/xul2Abu.png](http://i.imgur.com/xul2Abu.png)
>Magma Totem VII's Magma Totem hits Grandmaster's Training Dummy for 3 Fire.(423 Overkill)
>Magma Totem VII's Magma Totem hits Grandmaster's Training Dummy for 3 Fire.(849 Overkill) (Critical)

Even without the 3% crit dmg from meta gem, the crit dmg is still the same.
853/427=1.997658079625293

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[http://wotlk.openwow.com/spell=58734](url) Magma totem rank 7

**Comment by robinsch** [comment] 2016-11-27 10:24
I get the crit and hit chance. Both should be fixed on PTR.

Where do you get the crit multiplier from?

**Comment by plznoz** [comment] 2016-11-27 10:25
Live logs and DrDamage addon, both say the same.

**Comment by Rushor** [comment] 2016-11-27 10:29
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by robinsch** [comment] 2016-11-27 10:32
- Totem should scale with Shaman crit increasing talents

**Comment by fixlol** [comment] 2016-11-28 22:17
Why not speak of even distance between a totem and the other? that are too close !!!.
speak only of the bugs that goes against you?

**Comment by plznoz** [comment] 2016-11-28 22:21
Why don't you go ahead and report that, since you seem to know how they are supposed to be. Have a nice evening, drink some hot chocolate, maybe you'll feel better.

**Comment by Rushor** [comment] 2016-11-29 17:51
Core/Totem: Totems now inherits owners hit and crit ratings

Issue: https://github.com/dalaranwow/dalaran-wow/issues/3884
commit: 5b592c189f110f80ea25972c0e2ea0a7a230554f

**Comment by robinsch** [comment] 2016-12-04 16:22
Commit Hash: 778d975c2d2b81247a85e304e8182e32bed396c5
Core/Unit: Totems should scale with owner crit increasing auras

**Comment by TeridanDW** [comment] 2017-10-13 16:05
After some testing of this issue on Vesperon, here are the results:
![wowscrnshot_101317_185102](https://user-images.githubusercontent.com/6797611/31555085-5f0c1e6c-b048-11e7-9c48-31ba5792b274.jpg)

>  Hit rating
>  Crit rating

Doesn't seems to be scaling and for:

> Core/Unit: Totems should scale with owner crit increasing auras

I am not sure what exacly I am suppose to test (crit increasing auras from talents, outside sources?).

Crit multiplier for Magma totem is still 2.0 (1.99 to be exact as pointed above by @plznoz )
![wowscrnshot_101317_184132](https://user-images.githubusercontent.com/6797611/31555283-2269f6ae-b049-11e7-98f6-7be0186a82a1.jpg)
![wowscrnshot_101317_184111](https://user-images.githubusercontent.com/6797611/31555332-52d965e0-b049-11e7-9a8a-3a3c5740b4be.jpg)
![image](https://user-images.githubusercontent.com/6797611/31555362-6bbfd328-b049-11e7-86a0-0b895f9f70c6.png)

**Comment by robinsch** [comment] 2017-10-17 17:31
Am I stupid? I don't find any talents from Shaman that increase crit damage, can you post it?

**Comment by TeridanDW** [comment] 2017-10-17 17:45
https://wowgaming.altervista.org/aowow/?spell=60188

**Comment by robinsch** [comment] 2017-10-17 18:01
Yeah redo the test, I just check it with the debugger and my totems got stats from my shaman.

**Closed** 2017-10-17 19:05 UTC
Labels: Class - Shaman, General - Mechanics, Not working/incomplete fix, Priority - High

**Comment by robinsch** [comment] 2017-10-17 21:48
Fixed the crit thing.

**Comment by TeridanDW** [comment] 2017-10-18 07:27
> Totem should scale with owners
> 
>  Hit rating
> 
>  Crit rating
> 
>  Crit increasing damage talents

Works as intended on PTR.
