### ISSUE TITLE
[ICC] Combat Bug After Fight With Beetles Before Professor Putricide

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#5116] opened 2017-11-24 23:24 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: raid is in combat after finishing fight with beetles before Professor Putricide

**Expected behaviour**: raid is not in combat after finishing fight with beetles before Professor Putricide

**Steps to reproduce the problem**:

1. Enter the first door way leading to Professor Putricide
2. Kill the spawning beetles until the second door opens
3. Notice that you're still in combat

**Include proofs for this behaviour**

There is no reason to put raid in combat before the raid boss where people are supposed to rebuff, respec, eat up etc.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Professor Putricide - 36678
Flesh-eating Insect - 37782
Icecrown Citadel - 4812

**Include Screenshots from the issue if necessary**

N/A

**Comment by Crispybuilt** [comment] 2017-11-27 01:53
Can confirm that this still happens and is a very annoying glitch.

**Comment by Lothloryen** [comment] 2017-11-30 16:47
Hello there, 

I have already found the source of this issue, fixed within the next restart.

Thank you for the report.

**Comment by datbunneh** [comment] 2017-12-01 23:42
@Lothloryen Same as with Gluth. Some people were out of combat and some were in combat.

**Comment by Lothloryen** [comment] 2017-12-01 23:46
Hello there,

Are you right now still with such combat? I have hopped into the server, write a ticket if you are so I can do few checks, please. It will be real quick.

**Comment by Crispybuilt** [comment] 2017-12-02 09:43
The main problem here is that "some" of the people could have pulled something before Gluth, and haven't killed that.
Such as Abominations in the first section of Construction Wing, and since Pathfinding isn't perfect in Naxxramas, they will often get stuck behind the wall, or slime river, which they can not cross, hence keeping that particular player in combat and causing entire raid to stay in combat.

In general, any NPCs that is killed properly in the instance which is aggroed or pulled, will never, ever cause a combat bug for anyone in the raid (talking about Naxxramas, Icecrown Citadel)

As for Ulduar: little gnomes in helicopters that jump down after helicopters are killed are untargetable and can only be killed by Retribution Aura/Thorns.

----------------------------------

What most people do not understand about combat and combat bug is how it works, so let's take a few examples here:

Naxxramas:
1st Move to The Construct Quarter
2nd - Pull something on the way
3rd - Leave that behind unkilled
4rd - Permanent combat bug for that particular player/multiple players (if others players interacted with them (such as buffing, healing and so on)

1st - You have reached Gluth without anyone in combat, meaning every trash mob that was pulled was cleared.
2nd - Killed Gluth
3rd - No Combat bug (after recent fix)

1st - You have reached Gluth with someone in combat, meaning you left some trash behind which was pulled before that and not killed.
2nd - You have killed Gluth, people that were previously in combat with something, will stay in combat.

**Comment by Crispybuilt** [comment] 2017-12-02 09:50
Every instance/dungeon works in that way.
**NOTHING** will keep you in combat as long as you **KILL** that particular **NPC**

**List of combat bugs that were fixed and applied properly:**
- Naxxramas (Combat Bug after Gluth (Decimate causing cloud triggers to stay in combat with him/players))
- Trial of Crusader (Combat bug after Lich King shatters the ground beneath us)
- Icecrown Citadel (Combat bug after Putricide's Room)

**List of combat bugs that are still present:**
- Ulduar 10/25 - Upon death of Roflcopters, little untargetable gnomes will jump down, which can not be interacted with and they can only be killed with Ret Aura/Thorns

**Comment by datbunneh** [comment] 2017-12-02 16:52
@Crispybuilt This is not the case. If we had combat with some NPC we would have it even before pulling Gluth. But we were buffing before Gluth and noone had combat at that point.

@Lothloryen Tricky to do it, specially on PP when people start relogging or stacking in corner to get rid of it.

**Comment by Crispybuilt** [comment] 2017-12-02 19:48
Okay, I found the source issue with combat after putricide, it does get removed from players, however it does not from **PETS**.

Once any player that has a **PET** interacts with it, they will get in combat.

**Comment by datbunneh** [comment] 2017-12-02 21:38
@Crispybuilt Probably the same issue with #5028?

**Comment by Lothloryen** [comment] 2017-12-05 17:35
Hello there,

Let me know if it happens now, a fix is already on live. #5028 and this are different issues, I have deployed a fix for both of them.

**Closed by Lothloryen** 2017-12-05 17:35 UTC
Labels: Area - Instances, Priority - High

**Comment by Crispybuilt** [comment] 2017-12-11 12:08
Fixed and working as intended.
