### ISSUE TITLE
Mobs falling underground

### ISSUE THREAD

**Issue by deadmage** [dalaranwow/dalaran-wow#2367] opened 2015-04-29 20:09 UTC
See, I think you've experienced that before with the mobs falling underground (aswell as pets). It's kinda sad and it makes me mad all the time when some mob pushes my pet underground and pulls the whole dungeon or cave in my situation.

**Comment by Golganeth** [comment] 2015-05-04 16:17
Duplicate of #1955

**Closed by Golganeth** 2015-05-04 16:17 UTC
