### ISSUE TITLE
Quest: Securing the Bait

### ISSUE THREAD

**Issue by acidrinker** [dalaranwow/dalaran-wow#1055] opened 2013-12-23 16:56 UTC
Zone: Sholazar Basin

Description: Bring 6 Primordial Hatchlings to Dorian Drakestalker at Dorian's Outpost. There are 2 ways to make it:
1) Destroy Primordial Drake Egg and collect Primordial Hatchling that dropped from it.
2) Collect Primordial Hatchling that is already on the ground.

Issue: You can collect quest item from 1 Primordial Hatchling as many times as you want (in this case 6 times)

How it should work: You should be able to collect only once from each Primordial Hatchling that is on the ground.

**Comment by Watterx** [comment] 2015-02-15 22:13
It's fixed, even tho none marked it as. Working as intended. The drakes tho, walk on the air.

**Closed** 2016-05-04 14:13 UTC
Labels: Northrend, Quests
