### ISSUE TITLE
[Death Knight] DK pet Gnaw reset

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3652] opened 2016-08-14 15:07 UTC
**Description**:
After ghoul dies (u use Corpse Explosion, or Death Pact or it just dies) and you summon it again(after 30s) the cooldown of pet's stun(Gnaw) should reset. 

**Current behaviour**:
If you use Gnaw and your pet dies by damage/CE/Death pact, after 30 seconds when you summon new pet he will still have CD on gnaw.

**Expected behaviour**: 
Gnaw cd should reset upon summoning new pet

**Steps to reproduce the problem**:
1. Use gnaw ability on training dummy
2. sacrifice your pet or use corpse explosion
3. wait 30 sec and summon new pet and you will notice that gnaw is still on cd

**Include proofs for this behaviour**
Watch from ~3:15 - 3:50 and on
http://www.warcraftmovies.com/movieview.php?id=160057
From 1:50 - 2:05
https://youtu.be/QXR5sMKcn08?t=107

[Gnaw ID](http://wotlk.openwow.com/spell=47481)

**Comment by Rushor** [comment] 2016-12-13 11:14
Game/Pet: Ghoul - save CDs if pet is alive

* closes https://github.com/dalaranwow/dalaran-wow/issues/3652
* commit: e61bc76afcbb615540c5f3c9491927ea29302d58

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-13 11:14 UTC
Labels: Class - Death Knight, Fixed - Waiting for PTR Update, General - Mechanics, Priority - High

**Comment by TeridanDW** [comment] 2017-10-20 18:46
Works as intended on PTR.

**Comment by Johanes022** [comment] 2017-11-27 19:10
Not working on live anymore.Was working tho till recently.
