### ISSUE TITLE
[Quest] The Rider of Frost

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#1952] opened 2014-10-09 19:35 UTC
Will not give credit if 2 or more help kill Sapph.

This is a Group 5 Quest

**Comment by Edzero** [comment] 2016-10-25 16:43
The Rider of Blood and The Rider of Unholy are awarding group credit on the PTR but not this one.

**Comment by Rushor** [comment] 2016-11-23 09:15
DB/Quest: The Rider of Frost - Questcredit for Sapph(30956) should always be rewarded now

* before this fix, the questcredit was not always rewarded after the kill
* also reward the questcredit to the whole group
* commit: d78f26f3df7292ddc50c1fcd3e02d5024113ad9e
* commit: 29570f3b760733c80df63a8726799a4232d67107

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 09:15 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by thanhtotti** [comment] 2018-02-26 18:50
Just encounter this bug today, on live server.
