### ISSUE TITLE
[Rogue][Talentes] Rogue talent: Master Poisoner

### ISSUE THREAD

**Issue by asbraich** [dalaranwow/dalaran-wow#2214] opened 2015-02-01 23:25 UTC
There is another bug report open that mentions master poisoner being bugged by judgement and other abilities.  However, there is another issue with master poisoner: the 3% critical strike chance debuff is not being provided on poisoned targets.

I tested this with over 2500 attacks on a dummy and removed any trinkets that would alter my crit chance on activation these were the results:

http://imgur.com/8FiBBkD

Clearly no 3% bonus crit is being provided.

**Comment by asbraich** [comment] 2015-02-01 23:26
> My crit rate was marginally higher than the character tooltip(37.7% vs 37.2%), but not nearly close enough to be within a margin of error for 3% missing crit from master poisoner. Perhaps the talent is bugged to only provide 0.3% crit?

**Comment by Golganeth** [comment] 2015-02-02 05:41
That other bug report also mentions this. Duplicate of #1782

**Closed by Golganeth** 2015-02-02 05:41 UTC

**Comment by asbraich** [comment] 2015-02-02 06:13
It doesn't mention anything about 3% crit
