### ISSUE TITLE
[NPC] Dustwraith

### ISSUE THREAD

**Issue by kuicani** [dalaranwow/dalaran-wow#3188] opened 2016-03-27 19:46 UTC
After more than the solid 50 attempts, Dustwraith hasn't spawned to me in Zul' Farrak. I've been asking around and nobody can confirm anything, so i suspect that he's most likely bugged and doesn't even spawn. Pls fix or gimme a Desertwalker Cane :(

**Comment by Rushor** [comment] 2016-06-05 16:02
yep no spawn for this creature in db

**Comment by Rushor** [comment] 2016-06-05 16:03
http://www.wowhead.com/npc=10081/dustwraith#comments
This guy's a rare random spawn. He can spawn near any of the bosses after the fountain area. bottom of the temple where Sergeant Bly is locked up, near where Hydromancer Velrath spawns, or near Witch Doctor Zum'rah sits. he can drop a pretty good mana regen Offhand. Hope this helps

-Josa

**Comment by Rushor** [comment] 2016-11-25 19:57
DB/Creature: Dustwraith - Add rarespawn in Zul'Farrak

* closes https://github.com/dalaranwow/dalaran-wow/issues/3188
* commit: ac002a548e3a8b6ff95380b5d1ea94659a799490
* commit: aee9b71e62486f5d59a2ea944f842001cd1b3e3d
* he will spawn for 50 on instance enter on this place: 

![GitHub Logo](http://i.imgur.com/8BfkCDd.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 19:57 UTC
Labels: Instances, On PTR
