### ISSUE TITLE
[Azjol Nerub] Boss Bug Reports

### ISSUE THREAD

**Issue by Mirashu** [dalaranwow/dalaran-wow#3280] opened 2016-05-10 13:39 UTC
Before the first boss fight, there are 3 mob packs, in retail you are supposed to pull one of them and finish them off as quick as possible and given enough time, the next mob pack will charge to attack, and then the same on the last group, and when you are done, you can attack the boss.
But when you pull one mob, all 3 mob packs including the boss comes to attack

**Comment by Lothloryen** [comment] 2016-05-10 16:42
Hello Mirashu,

This event is scripted and on every test it has been working fine. How many times have you been able to reproduce this issue? Any extra information would be welcome, maybe there is a very specific condition where this can happen. 

I have been watching some random groups after you wrote this and all of them were fine, the event started correctly after the first pack was pulled.

Thank you for your report.

**Comment by saltylopez** [comment] 2016-05-11 13:20
Did this last night and the pull scripting seemed ok.  The second pack would come like 30 seconds after the first, and the third pack another 30 seconds later.

The problem we encountered was that the Web Wraps placed on players persist even after the web cocoon has been broken.  The debuff should fall off and the player should regain control immediately after the wrap is broken.

As soon as the tank or healer was wrapped it would inevitably lead to a wipe, since it's about a full 10 seconds where they can do nothing.

**Comment by Lothloryen** [comment] 2016-05-11 14:39
Hello there,

Yes, I have seen more Azjol runs in both modes and everything except the wrap issue seems fine, which has been corrected already.

Closing this report, there will be a maintenance in about 20 minutes and the wrap shall be properly removed.

Thank you.

**Comment by Jonny462** [comment] 2016-05-21 06:27
I've only heard of this happening in normal, but I have experienced it 4-5 times while leveling. After that I avoided AN. Its happened to me, with my multibox team a few times. I also do randoms on a single character and it happened 3-4 times in 1 group. After that we all give up.

I will try tomorrow if I can and let you know.

**Comment by Golganeth** [comment] 2016-05-22 10:58
Heroic mode timers seem fine, Normal mode timers will be looked at.

**Comment by Jonny462** [comment] 2016-05-22 18:04
I just tried it again on normal. Same thing happened. My whole group was standing back at the turn, well out of pull and spell range, but the groups still came like they were on a timer.

I was going to try and record it, but my ssd died and its to laggy without it. You can chat me in game on chewey or chewdru. I can try it again if you want to witness it.

**Comment by kalvindeane** [comment] 2016-05-22 18:21
They are on a timer, they are meant to be.

http://wowwiki.wikia.com/wiki/Krik%27thir_the_Gatewatcher

**Comment by Jonny462** [comment] 2016-05-22 18:40
Sorry wrote that fast. I mean't wrong timers. I did it on a team of level 80's and wasn't able to finish the second group before the boss came over, on normal.

**Comment by TheRealestMcCoy** [comment] 2017-01-13 05:43
I know there is a issue with heroic you can pull the boss and the ads wont pull. Pulling the boss it self should trigger all 3 mini bosses sand 6 adds to pull as well. They are not properly linked.

**Comment by Rushor** [comment] 2017-01-13 08:04
could someone write a short sentence with:

How it is currently on algalon?

How it should be retail like (including video proof)?

Maybe something has changes during the time in the script

**Comment by TheRealestMcCoy** [comment] 2017-02-19 20:48
@Rushor 

Current Algalon Heroic Version:

When you get to the first boss. Players with range can pull just the boss. 
Upon pulling the boss the adds do not get pulled with the boss. When all 9 adds and the boss should be pulled if the boss is pulled. [Link of Pulling the Boss First](https://www.youtube.com/watch?v=SAc-EhI9ahU)

If you do the encounter as intended. (Not for the achv) 

You should pull 1 pack of adds of 3 at a time. 
At this point a even timer should be started for the next pack to engage. However i can not find the actual timers at this time. You can see in this [cata video ](https://www.youtube.com/watch?v=-ZOvkzvqZoc) that the first pack was pulled at 4secs. The 1st was killed and at 51secs(47sec kill)  the 2nd pack engaged at 1:00. The 2nd pack was killed at roughly 2:07-2:08 (1:07-08 to kill) And then at around 2:15 the last pack engaged.
 
Times between packs 
Pull
Pack 2 engaged roughly 57 secs later 
Pack 3 engaged roughly 1:15 secs later (2:11secs after initial pull)

**Comment by Teridan-dal-wow** [comment] 2017-02-25 15:50
Reference from retail about this dungeon on normal mode (as i understood the hc version is working correctly):
https://www.youtube.com/watch?v=37tlYcfTr_w&feature=youtu.be

**Comment by TheRealestMcCoy** [comment] 2017-02-25 15:52
The first boss on heroic is not right

**Comment by Teridan-dal-wow** [comment] 2017-02-25 16:14
Alright here is the first boss on hc:
https://www.youtube.com/watch?v=qRDgoMt93IE&feature=youtu.be
The only diffrence between normal and hc that i saw was the timers on hc were shorter (and creature level and damage will be diffrent ofcourse).
I can't be really sure but i think the encounter started after these 3 died:
![image](https://cloud.githubusercontent.com/assets/6797611/23332667/28158cda-fb86-11e6-89f1-a361a4b53d1e.png)
and not when you engage the first "boss" pack. If you watch the hc video you will notice the first speech from the boss came after i have already started the first pack but that is the indicator for when a pack engages the players.

**Comment by TheRealestMcCoy** [comment] 2017-02-25 17:00
The encounter does not start till you pull 1 of the 3 mini bosses. But it is broke cause you can pull the boss and none of the mini bosses pull

**Comment by TheRealestMcCoy** [comment] 2017-02-25 17:01
you want to test the heroic on algalon go on heroic and only pull the boss none of the mini bosses. You will have to do it with 40yd range class

**Comment by Lothloryen** [comment] 2017-02-25 17:03
Hello there,

I will take a look into this so the boss is not aggroable. One question though, the event starts properly if you do not pull the boss, right? I remember implementing the proper event some time ago.

Thank you.

**Comment by TheRealestMcCoy** [comment] 2017-02-25 17:04
the boss should be able to be aggroed but the other 9 adds should all pull at once. That is the current issue besides timers. 

So pull boss watch none of the 6adds or 3 mini bosses pull.

**Comment by TheRealestMcCoy** [comment] 2017-02-25 17:06
The event starts but its not right with the timers if you pull 1 of the mini bosses

**Comment by Lothloryen** [comment] 2017-02-25 17:07
Right, I misunderstood, got it now - thank you.

**Comment by TheRealestMcCoy** [comment] 2017-02-25 17:16
![an](https://cloud.githubusercontent.com/assets/12252441/23333123/2b8eba6c-fb54-11e6-8313-92dced8a9ac6.png)
If this helps

**Comment by Teridan-dal-wow** [comment] 2017-02-25 17:25
Ignore what i said above, this is the correct be behavior:

> The encounter does not start till you pull 1 of the 3 mini bosses.

**Comment by TheRealestMcCoy** [comment] 2017-02-25 17:28
Would a sniff help with this?

**Comment by Teridan-dal-wow** [comment] 2017-02-25 17:42
Already made them together with the 2 videos above, Rushor has access to them.

**Closed** 2019-05-13 14:19 UTC
Labels: Area - Instances, Area - Northrend

**Comment by taichouVu** [comment] 2021-03-02 06:17
Unfortunately this is unfixed. Normal mode, pulled 1st minibox back all the way into the tunnel. 10 seconds later second miniboss group comes. Also minibox Silthik casts aoe poison and webs. I think these abilities are supposed to be Heroic according to Wowhead.
