### ISSUE TITLE
[Quests][Northrend] Mastery of the Crystals

### ISSUE THREAD

**Issue by darkwulfv** [dalaranwow/dalaran-wow#2583] opened 2015-06-30 22:31 UTC
The Oracles daily quest "Mastery of the Crystals" (http://wotlk.openwow.com/quest=12761) does not work at all. You can get the crystal items from the chest, but when used they do not work right; they instead will chase down enemies and try to attack them at melee range. They don't use any of the abilities they should, which makes the quest much more grindy/annoying because you have to manually kill 50 Frenzyhearts.

Items:
Crystal of the Frozen Grip (http://wotlk.openwow.com/item=39689)
Crystal of Unstable Energy (http://wotlk.openwow.com/item=39693)
Crystal of the Violent Storm (http://wotlk.openwow.com/item=39694)

**Comment by Rushor** [comment] 2016-11-25 12:56
DB/Quest: Mastery of the Crystals - Add spells for the summoned crystals

* closes https://github.com/dalaranwow/dalaran-wow/issues/2583
* once the crystals are summoned, they are rooted and cast their spells now
* commit: 460ea333c866cbc91c9860a808c8611383eaf803

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 12:56 UTC
Labels: Continent - Northrend, On PTR, Quests
