### ISSUE TITLE
[Spell] Animal Blood / NPCs Reaction [46221]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1180] opened 2014-02-10 15:37 UTC
**Issue:** While having this debuff, any of the D.E.H.T.A. aligned NPC's should become hostile to you for the duration, but they don't.

The enemy unit plates seem to show up with all the NPC's once you have the spell, but they are all shown as yellow (neutral) plus they don't attack nor can you attack them.

http://wotlk.openwow.com/spell=46221

**Comment by Rushor** [comment] 2016-11-15 09:23
Game/Spells: Animal Blood - Reputation against Cenarion Expedition must be hateful 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1180
* commit: d9cefac9c24d8505191b39d63b4fd9691ae53252

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 19:40
Hm, this fix doesn't seems to work or it's not on ptr.
Spell http://wotlk.openwow.com/spell=46221 is working on TC and more work on this issue was done here #4593

**Comment by Rushor** [comment] 2018-05-07 09:32
fixed together with https://github.com/dalaranwow/dalaran-wow/issues/5399. I will close this as duplicate.

**Closed by Rushor** 2018-05-07 09:32 UTC
Labels: Area - Northrend, Duplicate / Invalid Report / Cannot reproduce
