### ISSUE TITLE
[NPC] Barrens Rares

### ISSUE THREAD

**Issue by ghost** [dalaranwow/dalaran-wow#1420] opened 2014-03-30 11:44 UTC
Above ratchet, there are two rare's, humar the pridelord, and swiftmane. Humar the pridelord for start, is in the wrong place, he should be layed, in the shadow, asleep under the tree, but instead, he is walking around, like one of the other lions, far away from his spot. Swiftmane just does not run, he just stands there, these are minor bugs, but im pointing out :D

**Comment by Rushor** [comment] 2016-11-13 10:12
DB/Creature: Humar the pridelord + Swiftmane - Add emotestate and waypoints

* closes https://github.com/dalaranwow/dalaran-wow/issues/1420
* commit: 60bbc05b122547b3c729d014a842304fa342b795

![GitHub Logo](http://i.imgur.com/907qF0o.jpg)
![GitHub Logo](http://i.imgur.com/t3armD3.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment] 2017-01-11 20:53
DB/Creature: Swiftmane - Update pathing to blizzlike value

* updates: https://github.com/dalaranwow/dalaran-wow/issues/1420
* commit: d682976fa6685f217b3ee60b517dfede13859f0a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 18:28
Hm, that's strange, there is an issue with npc http://wotlk.openwow.com/npc=5828 and http://wotlk.openwow.com/npc=3416 when engaged they don't lose their emote state
![image](https://cloud.githubusercontent.com/assets/6797611/24623770/4575ec04-18b2-11e7-917e-ed4eeb510212.png)

I would like to add here also that npc http://wotlk.openwow.com/npc=3416 doesn't use their spell http://wotlk.openwow.com/spell=6598 on reset.
``` sql
-- Savannah Matriarch SAI
SET @ENTRY := 3416;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,25,0,60,0,0,0,14000,14000,11,6598,0,0,0,0,0,1,0,0,0,0,0,0,0,"Savannah Matriarch - On Reset - Cast 'Savannah Cub'"),
(@ENTRY,0,1,0,4,0,100,0,0,0,0,0,91,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Savannah Matriarch - On Aggro - Remove Flag Standstate Sleep");

```

**Comment by Rushor** [comment] 2018-03-19 09:49
The emotestate issue was fixed in core some time ago with:

```c++
        // Remove emote state - will be restored on creature reset
        SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
```

**Closed** 2018-03-19 09:55 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update
