### ISSUE TITLE
New Character Weapons

### ISSUE THREAD

**Issue by tnkrocha** [dalaranwow/dalaran-wow#3126] opened 2016-02-05 04:47 UTC
I have started a many new characters with many different races and each time the weapons abilities show up as a red '?'. I have to go and buy a new weapon for it to work and then on hunters I cannot equip arrows as they show up as the same red '?'. Keeps saying no arrows equipped when they clearly are.
Same thing with my new warrior. Say cannot use ability because no melee weapon equipped. There is one and he can fight normally. 
What gives? Any ideas?

**Comment by M0dinstaller** [comment] 2016-02-07 02:52
I don't have this. I think it could be your client. Have you tried clearing cache / running without addons / getting a new fresh 3.3.5 torrent that works for other people ?

**Comment by tnkrocha** [comment] 2016-02-07 03:24
I did clear cache and run without addons.
I have 3.3.5a. Should I try reistall?



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by Golganeth** [comment] 2016-02-10 16:41
Could not reproduce the issue at all. Looks like the issue is on your side, could be caused by a corrupted file. You should try re-installing the game from scratch. 

Closing up

**Closed by Golganeth** 2016-02-10 16:41 UTC

**Comment by tnkrocha** [comment] 2016-02-10 18:50
Ok. Thanks I will try. Had a guildie have the same issue with her hunter.

Thank you,

Todd Rocha
BnK Construction, Inc.
503-808-0729

**Comment by tnkrocha** [comment] 2016-02-10 18:56
Do you have a link to a download client I can try?

Thank you,

Todd Rocha
BnK Construction, Inc.
503-808-0729
