### ISSUE TITLE
[Taunt] - Targets with large hitbox

### ISSUE THREAD

**Issue by shadovvs** [dalaranwow/dalaran-wow#3827] opened 2016-11-10 21:21 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
Taunting npc targets with large hitbox makes them move.

**Current behaviour**: 
Taunting targets with large hitbox makes the target move away to the max melee range from the player that taunted. 

**Expected behaviour**: 
Taunted target should not move away from the player that taunted.

**Steps to reproduce the problem**:

1. Stand very close to a target with a large hitbox (e.g. Gormok the Impaler/Dreadscale)
2. Taunt the target
3. Targets moves away to max melee range

**Include proofs for this behaviour**

OverDoZer - Algalon

Gormok the Impaler
https://youtu.be/x94kVTO61iE?t=5m48s
Dreadscale:
https://youtu.be/x94kVTO61iE?t=7m01s

Video from Jan 29, 2010

Gormok the Impaler
https://youtu.be/feno0x6bTsE?t=1s
Dreadscale
https://youtu.be/feno0x6bTsE?t=2m21s

**Tip for the tank swaps until this gets fixed:**
Before taunting off the tank that has aggro, move to the max melee range of the target and then taunt. 
If done right, target will not move.

**Comment by Ninielle** [comment] 2016-11-15 12:32
Maybe related to this but i have some issues with auto-attacking/skill using. Targets with larger hitbox have sweet spots where you can't hit them with your auto attacks, but you can with skills. It gets quite frustrating because as a warrior without my autos i often run out of rage. Worst part of this is when you have to switch tanks during a passive encounter and you always have to go forward/backpedal for your autos to work.

**Comment by ashido96** [comment] 2016-11-21 01:24
ninielle, just bind every cleave, bloodthirst whatever you do to a macro, sometimes helps, sometimes not
For instance this is what nearly every one of my ret macros looks like, doesn't really directly address your problem (which i've never experienced a year+ raiding here), but should help

/tar heart of the
/tar Nether Portal
/tar Infernal Volcano
/tar Saronite Animus
/cancelaura Divine Intervention
/startattack
/cast Judgement of Light

**Comment by robinsch** [comment] 2016-12-05 15:16
Commit Hash: c40df52c398b239a49dd8ac3d864dedeac4df0ff
Core/Creature: Make units with large hit box not move away from already close targets

**Comment by Edzero** [comment] 2017-03-30 14:58
Still occurs on PTR. If the player taunts a mob they will move to maximum melee range if they are not already at that range. Same issue if the mob's current target moves even slightly.

**Comment by Rushor** [comment] 2017-03-30 18:15
That's not on PTR yet

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-30 18:15 UTC
Labels: Area - Instances, General - Mechanics, Priority - High

**Comment by TeridanDW** [comment] 2017-10-14 07:35
Works as intended on ptr.

**Comment by ashido96** [comment] 2017-10-16 03:15
this fix was not pushed to live server as of testing in raid 20 minutes ago.

**Comment by TeridanDW** [comment] 2017-10-16 07:33
Hello @ashido96, could you tell me on which bosses did you encounter this issue on live?

**Comment by Lothloryen** [comment] 2017-10-16 12:34
Hello there, my apologies I set the Fixed - On Live Server by mistake. This correction is not yet deployed, I shall change the label once it is done.
