### ISSUE TITLE
[Quest][Outland] You're Fired! 

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1733] opened 2014-07-07 03:02 UTC
This quest is currently not working.

How it should work:
After gaining keys by killing the Anger Guards in Forge Camp: Anger, you should click on the obelisks to activate them. When activated, lightning should shoot out from the tips toward the other obelisks. When all 5 are active, Doomcryer should spawn.

Issues Present:
The obelisks will take the key, but do not activate. There is no visual indication of being active, and clicking all five obelisks does not summon Doomcryer.

**Comment by Focused12** [comment] 2015-06-21 04:02
Can confirm, got this quest to work, took me close to 10 tries but eventually she came down in to the middle gate. All the bells and whistles did not happen, simply look at the gate north of the center pillar.

**Comment by Rushor** [comment] 2016-11-28 21:43
DB/Quest: Properly implement quest: You're Fired!

* closes https://github.com/dalaranwow/dalaran-wow/issues/1733
* commit: f8c40125410ffd0ab196c869200e7fa924a21564

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 21:43 UTC
Labels: Continent - Outland, On PTR, Quests
