### ISSUE TITLE
Disarm lowers melee damage after the duration's ended.

### ISSUE THREAD

**Issue by Liefde** [dalaranwow/dalaran-wow#1530] opened 2014-04-20 14:08 UTC
Being disarmed appears to permanently reduces your melee damage, not just on your char screen but your actual damage. Said reduction in damage will only go away if you either relog or unequip and reequip your weapon(s).

Confirmed on:
Kenata Dabyrie (quest mob) - Disarm - Dabyrie Farmstead (Arathi Highlands)
Scarlet Guardsmen - Disarm - Scarlet Monastery Armory
Lashtail Raptors - Dropped Weapon - Around Grom'Gol (Stranglethorn Vale)

The video below this sentence will show you exactly what happens during and after the disarm, please note the almost halved damage I deal at the end of the fight even though I had my weapon back in my hands.

http://www.dailymotion.com/video/x1ptusl_bugged-attack-damage_webcam

**Comment by rinleezwins** [comment] 2016-04-18 13:12
I swear I searched for "disarm" before opening my issue and didn't see this. So it's been 2 years now, any update on this matter?

**Comment by Rushor** [comment] 2017-03-29 20:41
This is still an issue on PTR?

**Comment by TeridanDW** [comment] 2017-03-29 20:49
Can't reproduce it on PTR anymore (tried with the same raptor).

**Comment by Rushor** [comment] 2017-03-29 20:50
kay thanks, the fix for it (if there was any) will be merged with further updates on the live realm then.

**Closed by Rushor** 2017-03-29 20:50 UTC
