### ISSUE TITLE
Daily quests not rewarding exp

### ISSUE THREAD

**Issue by nemmjuuk** [dalaranwow/dalaran-wow#3846] opened 2016-11-15 06:25 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: Players below level 80 don't receive exp for repeating daily quests. 

**Current behaviour**: Players below level 80 don't receive exp for repeating daily quests. 
This is not Blizz like 

**Expected behaviour**: Below lvl 80, players should receive exp for finishing the quest, At lvl 80 the exp is converted to gold.
**Steps to reproduce the problem**:

1. Finish daily quest below lvl 80.

**Include proofs for this behaviour**
Discussion about changes to daily quest exp and gold rewards on the official Blizzard forum. This happened at a time Blizzard made changes in preparation for the CATA release.  Quotes:
-----------------------
OK I went out with a level 80 and a level 79 to see what I could work out. 

Dalaran Cooking daily - still gives 5g80s and 16350 exp to the 79 as before. Only gives 5g80s to the 80. Interestingly, in the quest log it still said the 80 was going to get 9g93s like it used to, but in the dialog where you accept the quest and also when you turn it in it does say you will only get 5g80s. 

Regular quest (at Argent Vanguard because they were close by) - still gives 6g80s and 21600 exp to the 79. Only gives 6g80s to the 80 while it used to give 12g96s. 
-------------------
Anyway there is still 20 days before Cata is out, so you are still level capped and it should reward the money for level capped unless Blizzard reduced the xp reward from those dailies. 
--------------------
http://us.battle.net/forums/en/wow/topic/1020824555

**Comment by Rushor** [comment] 2016-11-15 09:06
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/2964

**Closed by Rushor** 2016-11-15 09:06 UTC
Labels: Duplicate
