### ISSUE TITLE
[Quest] Mark V is Alive!

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#718] opened 2013-08-31 09:39 UTC
_Location:_ Outland/Netherstorm
_Quest Start:_ Maxx A. Million Mk. V (http://wotlk.openwow.com/npc=19589)
_Quest End:_ Bot-Specialist Alley <B.O.O.M.> (http://wotlk.openwow.com/npc=19578)
_Quest Link:_ http://wotlk.openwow.com/quest=10191

**Current Issue:** The Robot (Maxx A. Million MK. V) doesn't get attacked by any hostile NPCs in the area. Therefore you can avoid fighting completely by avoiding to get yourself into aggro range (very easy with flightmount), which makes the quest extremely easy.

**Comment by Demlock** [comment] 2015-07-17 21:19
Confirmed.

**Comment by Rushor** [comment] 2016-11-17 20:07
Scripts/Outland: Maxx A. Million Mk. V - change faction during escortevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/718
* the ecortnpc will now always assist the player. the npc is also no longer attackable by the opponent faction during the escort
* commit: 009210cbc40eb39957700dc8cd7a0946f28c5012

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 18:12
Npc http://wotlk.openwow.com/npc=19589 is still been ignored by some hostile npcs, however at some checkpoints he does engage in combat. After these fight Maxx behaive strange as he runs forward and comes back to his path after few seconds.

**Comment by Rushor** [comment] 2017-07-01 19:54
Scripts/Outland: Maxx A. Million Mk. V - Remove UNIT_FLAG_IMMUNE_TO_PC on quest accept

* updates: https://github.com/dalaranwow/dalaran-wow/issues/718
* commit: 732276ff2beac1000455568ae3ec8b233b714c00

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-01 19:54 UTC
Labels: Area - Outland, General - Quests
