### ISSUE TITLE
[NPC] Treant Ally

### ISSUE THREAD

**Issue by Exicucumber** [dalaranwow/dalaran-wow#2492] opened 2015-06-07 22:14 UTC
Mob: Treant Ally
Zone: Stonetalon Peak, Stonetalon Mountains
Wowhead: http://www.wowhead.com/npc=5806/treant-ally

When you aggro this mob, it will never lose aggro. You can kite this mob for as long as you please, into every zone (as far as I know).
It's not urgent, just a minor annoyance.

![wowscrnshot_060815_000149](https://cloud.githubusercontent.com/assets/749256/8026382/4583a552-0d73-11e5-8ac1-d9bbbb0a7af5.jpg)

**Comment by Rushor** [comment] 2016-11-17 21:01
DB/Creature: Treant Ally - Add basic AI

* this allows him to reset
* closes https://github.com/dalaranwow/dalaran-wow/issues/2492
* commit: dae6120830783e15f59c409fe15edf40386b135a

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-02 12:55
They nolonger chaise forever, which means this fix is on ptr, however when the creature is suppose to enter evade mode and run back to his original position it doesn't. Instead it sets it current position as home and stays there, it can be aggroed again and same will happen on the next spot there it should reset.

**Comment by Rushor** [comment] 2017-07-04 12:49
DB/Creature: Treant Ally - creature should walk back to their spawnposition on evade/reset

* updates: https://github.com/dalaranwow/dalaran-wow/issues/2492
* commit: 0a3680cc7018cf99579fbfb954b2505d922b2fe8

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-04 12:49 UTC
Labels: Area - Classic, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-26 09:41
Works as intended on PTR.
