### ISSUE TITLE
[NPC] Skullsplitter Spiritchaser unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1233] opened 2014-02-18 20:36 UTC
Skullspitter Spiritchaser (http://wotlk.openwow.com/npc=672) is not casting any of its abilities.

**Comment by Rushor** [comment] 2016-11-12 13:06
DB/Creature: Skullsplitter Spiritchaser - Add SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1233

"Skullsplitter Spiritchaser - Between 0-40% Health - Cast 'Healing Wave'"),
"Skullsplitter Spiritchaser - In Combat - Cast 'Lightning Bolt'"),
"Skullsplitter Spiritchaser - In Combat - Cast 'Mana Burn' (No Repeat)");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 13:06 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 19:05
Works as intended on ptr.
