### ISSUE TITLE
Runetog Wildhammer not offering flight services

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3744] opened 2016-10-06 13:24 UTC
**Description**:
The NPC Runetog Wildhammer, located at  78.4 34.9 in Hellfire Peninsula, is a Gryphon Master. 
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Clicking on the dialogue option "Show me where I can fly" gives no response; there is no option to choose a flight path.
**Expected behaviour**: Tell us what should happen instead
Clicking the dialogue option should lead to the Gryphon Master showing discovered flight paths which you can fly to. 
**Steps to reproduce the problem**:
1. Right click (open dialogue window) Runetog Wildhammer;
2. Click on Show me where I can fly;
3. Nothing happens.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

[Runetog Wildhammer, NPC ID 20234](http://wotlk.openwow.com/npc=20234)
[Hellfire Peninsula, zone ID 3483](http://www.wowhead.com/zone=3483/hellfire-peninsula)

**Comment by Rushor** [comment] 2016-11-10 18:55
DB/Creature: Fix Flightmaster Runetog Wildhammer, Shatter Point

* closes https://github.com/dalaranwow/dalaran-wow/issues/3744
* commit: 749a70d3e3d32ed113196dae7714f809f261cc9c

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 18:55 UTC
Labels: Continent - Outland, Priority - Low

**Comment by TeridanDW** [comment] 2017-03-31 08:28
Works as intended on ptr.

**Comment by Crispybuilt** [comment] 2017-11-10 22:44
After a recent check it doesn't work on PTR anymore, fix has to be deployed again properly.

**Comment by Crispybuilt** [comment] 2017-11-10 22:59
Will work after next server restart.
