### ISSUE TITLE
[Quest][Northrend] Gods Like Shiny Things

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1518] opened 2014-04-16 13:52 UTC
http://www.wowhead.com/quest=12572

For some reason players seem unable to see the shiny spots on the ground (nor does Lafoo dig them up). GMs however are able to see them.

This quest worked fine over a week ago, seems bugged now.

**Comment by ashido96** [comment] 2015-06-07 04:43
Can confirm that this will NOT work unless he is resummoned at each spot as described above.

**Comment by Rushor** [comment] 2016-06-07 06:43
"npc_lafoo" // new npc_lafoo(); new npc_shiny_thing_visual();

**Comment by Golganeth** [comment] 2016-06-23 20:56
Lafoo doesn't dig all treasures, for some of them it takes so long until he digs, some others he'll just ignore.

**Comment by catta000** [comment] 2016-06-28 16:03
Quest works well, but works a little different: 
If Lafoo comes close to a treasure (marked by the glintering spot) he starts to dig after a while, you will notice glinting bugs start to spawn. It may take up to a minute or so until the treasure appears, but there is always a treasure. Do not move while Lafoo digs cause this might cause him to stop.
Sometimes Lafoo does not start to dig when he already found a treasure, in this case resummon him by using his bag.

**Comment by ashido96** [comment] 2016-06-30 03:52
I went back and did this quest again to verify all the things.
If there's a shiny flashing dot thing on the ground, THERE IS A TREASTURE THERE.
Lafoo doesn't like to walk ANYWHERE on his own, he will dig thing pretty much immediately if you position and orient yourself and in such a way that he will sit directly over the flashing dot.
Lafoo hates working, slap that bag again every time to get him working again, after which you meticulously position him to be over the next shiny dot on the ground (becomes much quicker after you do it a couple days in a row).

**Comment by Rushor** [comment] 2016-11-25 10:01
damn i love the music in sholazar. 

the npc script must be updated, adding passive mode + readding follow movement after digging will fix all the issues here

**Comment by Rushor** [comment] 2016-11-25 10:25
Scripts/Quest: Gods Like Shiny Things - Lafoo will dig and follow his owner properly now

* closes https://github.com/dalaranwow/dalaran-wow/issues/1518
* commit: 115b2b8393289322248d09cf66ddf742dcae6350

![GitHub Logo](http://i.imgur.com/TUH99Zo.jpg)
![GitHub Logo](http://i.imgur.com/nsYEMzW.jpg)
![GitHub Logo](http://i.imgur.com/lZcxZf2.jpg)
![GitHub Logo](http://i.imgur.com/Yqm4KHB.jpg)
![GitHub Logo](http://i.imgur.com/2PoRSZU.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 10:25 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:02
Works as intended on PTR.
