### ISSUE TITLE
[Quest][Northrend] Gambling Debt

### ISSUE THREAD

**Issue by abonander** [dalaranwow/dalaran-wow#3498] opened 2016-06-25 07:43 UTC
**Description**:
Taruk at Scalawag Point in Howling Fjord asks the player to get debt payment from "Silvermoon" Harry from him inside his tent on the other side of the village. "Silvermoon" Harry gets a new dialogue option which turns him aggressive and causes him to attack the player.

http://www.wowhead.com/quest=11464/gambling-debt

**Expected behaviour**:
Once the player gets him to ~50% health, he is supposed to turn friendly and gain a new dialogue option allowing the player to collect his debt: http://www.wowhead.com/item=34115/silvermoon-harrys-debt

**Current behaviour**: 
However, his dialogue options are unaffected, leaving the player with the static option to access his vendor inventory, or the initial dialogue option to attempt to collect his debt. If the player selects the latter option, he will instantly surrender again once he is at 50% health, but nothing changes.

_ADDENDUM_
I just tried doing it again, and if I instantly hit him with Fire Blast before he surrendered again, I got the new dialogue option to collect his debt. So the events that make him surrender, and that make him surrender (so two redundant triggers?) and give the collect-debt dialogue option are triggered incorrectly.

**Steps to reproduce the problem**:
1. Take the quest from Taruk.
2. Go to "Silvermoon" Harry and select the "Taruk sent me to collect what you owe." option. 
3. Damage "Silvermoon" Harry until he is around 50% health.
4. Harry says "Eek! I'll pay! I'll pay! [..]"
5. Interact with Harry and note that he has the same dialogue option as before.
6. Repeat step 2, but hit Harry before he surrenders again, hard enough to get him to 37% or lower (that's what worked for me, it might be higher than that).
7. Interact with Harry to collect his debt with the new dialogue option.

**N.B.** according to WoWhead, his debt shouldn't be in his loot table as a corpse, but that seems to cause troubles with players that are powerful enough to kill him in one hit. Might be a good idea to add it?

**Comment by jonanone** [comment] 2016-07-29 17:39
This seems to be working on the PTR, so please, if it is still happening on Algalon let me know in order to make further investigations. Thanks!

**Comment by jonanone** [comment] 2016-07-29 17:39
I will let this open just in case.

**Comment by Rushor** [comment] 2016-11-25 13:47
DB/Quest: Gambling Debt - Enable second gossipoption

* closes https://github.com/dalaranwow/dalaran-wow/issues/3498
* the second gossip option will be visible again

![GitHub Logo](http://i.imgur.com/z4jemZu.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 13:47 UTC
Labels: Continent - Northrend, On PTR, Quests
