### ISSUE TITLE
[Quest] Fresh Remounts

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4794] opened 2017-07-08 17:41 UTC
The scarlet knight evades everything when you try to hit im off the horse to get on hi's horse i don't know if you're supposed to take his horse since there are many more in the area but still cannot hop on a single horse

http://www.wowhead.com/quest=12214/fresh-remounts

<a href="http://nl.tinypic.com?ref=2nks85y" target="_blank"><img src="http://i64.tinypic.com/2nks85y.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://nl.tinypic.com?ref=no92iw" target="_blank"><img src="http://i66.tinypic.com/no92iw.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ashido96** [comment] 2017-07-10 12:44
#637 #875 #3008 #3395 lets use the search function shall we? Duplicate.

**Comment by Rushor** [comment] 2017-07-29 09:40
Your issue posted here is a duplicate of issue: https://github.com/dalaranwow/dalaran-wow/issues/637 (< click on this and you will be redirected to the original posted issue).

**Closed by Rushor** 2017-07-29 09:40 UTC
