### ISSUE TITLE
[ICC][Valithria Dreamwalker] Earth Shield scaling with Twisted Nightmares

### ISSUE THREAD

**Issue by strobe-light** [dalaranwow/dalaran-wow#4739] opened 2017-06-06 06:23 UTC
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently Earth Shield benefits from the +% healing boost of Twisted Nightmares too much. 

**Expected behaviour**: Tell us what should happen instead
Earth Shield should scale accordingly with the % boost

**Steps to reproduce the problem**:

1. Play a resto shaman on Dreamwalker
2. Go into the portals and take stacks of the Twisted Nightmares debuff
3. Cast Earth Shield on Dreamwalker

**Include proofs for this behaviour**
Dalaran, at 0 stacks of Twisted Nightmares:
![image](https://cloud.githubusercontent.com/assets/15903359/26815984/bc9216da-4ad2-11e7-8385-84db01bea227.png)
Dalaran, at 38 stacks of Twisted Nightmares (200 dmg tick/stack, 7600 ticks = 38 stacks):
![image](https://cloud.githubusercontent.com/assets/15903359/26816032/fab8fc26-4ad2-11e7-9217-b2b9ac5dab00.png)
Comparing Healing Wave for reference:
healing wave crit 0 stacks:	17 404
healing wave crit 38 stacks:	84 865

expected result: 17 404 * (1+3.8) = 83 539. Seems good

earth shield crit 0 stacks: 	5 719
earth shield crit 38 stacks: 	1 313 193

expected result: 5 719 * (1+3.8) = 27 451. It is benefiting far more than expected

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Twisted Nightmares: 71940](http://www.wowhead.com/spell=71940/twisted-nightmares)
Earth Shield: 379 and 49284

**Comment by Marquito01** [comment] 2017-06-06 21:44
That bug is actually not related to Valithria and scaling there at all. Had 2 resto shams and neither of us got more than 50k-ish tick from ES. Didnt have it on 10m either.

![untitled](https://user-images.githubusercontent.com/12214615/26853088-dffcef6c-4b10-11e7-9dcc-0d7681668803.png)

I can confirm there's a weird bug with ES that happens once in like 5.000 casts, where all 8 stacks are multiplied by a lot.  Had 50k crits in hc last week for all stacks from 1 ES cast. No clue what triggers this, but its really rare. And thats probably the reason u got insane numbers on valithria.

![es bug](https://user-images.githubusercontent.com/12214615/26853179-3a9081dc-4b11-11e7-9f16-4a36c78d9a92.jpg)

**Comment by strobe-light** [comment] 2017-06-06 23:03
Hi, you're right that not every application of ES was doing insane healing, here's a more complete log and you can see that there are two ticks at 20:55:49.068 and 20:55:55:926 that both seem reasonable considering the number of stacks at the time, but basically every other cast since entering the portals was scaling in the ridiculous fashion.
![image](https://user-images.githubusercontent.com/15903359/26854832-3bddfb92-4b5b-11e7-9a0c-940fb7875f90.png)

Secondly, the first screenshot that you posted doesn't prove/disprove anything. Actually, the fact that over the course of the encounter you have average Earth Shield noncrits for 42k compared to average Holy Light noncrits for 38.5k indicates that ES is heavily outscaling HL with Twisted Nightmares stacks considering that noncrit ES ticks with 0 stacks in this gear hit for ~3.8k and HL for ~13k.

**Comment by ashido96** [comment] 2017-06-10 14:26
Fix #3537 first? Then see how this is working on valithria.

**Comment by Rushor** [comment] 2017-07-03 19:32
The real fix for this is https://github.com/TrinityCore/TrinityCore/issues/13808. But i'm going to add an easier fix for this for now.

**Comment by Rushor** [comment] 2017-07-03 19:46
Scripts/Spells: Earth Shield - Reduce healamount if player is affected by Twisted Nightmare or healing reductions

* also remove the spellbonus scaling from Twisted Nightmare
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4739
* commit: 7b7146a340a76608e57f0126b8644d16816a58a1

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-03 19:46 UTC
Labels: Area - Instances, Class - Shaman, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-11-01 10:58
Hello after few tests on PTR:

> Scripts/Spells: Earth Shield - Reduce healamount if player is affected by Twisted Nightmare or healing reductions

and

> also remove the spellbonus scaling from Twisted Nightmare

works as intended.

I didn't test TrinityCore/TrinityCore@816d44d as I don't know if it is on PTR.
