### ISSUE TITLE
Splithoof Hold and Splithoof Crag mobs

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3721] opened 2016-09-21 09:14 UTC
**Description**:
In the Splithoof Hold + Splithoof Crag regions of the game in Thousand Needles, there are alot of mobs ( in the cave especially ) that walk upwards toward the sky/ceiling and pass through it, or just plain walk in the ground/walls/mountains etc. Makes some  mobs impossible to kill as they do not return, and while others return, if they have a dot applied to them and die in a wall/sky/ceiling/air, they are impossible to loot.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Read above.
**Expected behaviour**: Tell us what should happen instead
Mobs should not be able to pass through texture ( walls, ground, ceilings, caves etc) or even fly for that matter.
**Steps to reproduce the problem**:
1.  Attack a few mobs, watch them _flee in fear_ and see how they run upwards or in walls ( in the cave) or pass through them, or attack mobs in Splithoof Crag and watch them walk under/through the ground/mountains.
2. 
3. 

**Include proofs for this behaviour**
Alot of screenshots can be found here ( tried to get some in the Crag but forgot to save them...sorry ) : 
http://postimg.org/gallery/36kre3blm/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**
See above.

**Comment by Rushor** [comment] 2016-11-10 18:30
DB/SAI: Remove FFA from Galak Mauler, Galak Stormer and Galak Marauder

* i removed the ability fleeforassisnatnce for these creatures because it creates some serious problems in that area
* closes https://github.com/dalaranwow/dalaran-wow/issues/3721

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 18:30 UTC
Labels: Continent - Classic, On PTR, Priority - Low

**Comment by TeridanDW** [comment] 2017-03-31 11:37
Creatures no longer FFA anymore, however i would like to delete some of the spawns here, there are spots with double even tripple spawns (in the cave).
``` sql
DELETE FROM `creature` WHERE `guid` IN (20974, 21010, 21029, 13099, 21765, 21760, 13098, 21012, 21766);
DELETE FROM `creature_addon` WHERE `guid` IN (20974, 21010, 21029, 13099, 21765, 21760, 13098, 21012, 21766);


UPDATE `creature` SET `position_x`=-4999.669,`position_y`=-2354.202,`position_z`=-55.643 WHERE `guid` = 21037;
```
