### ISSUE TITLE
The Culling of Stratholme bugs

### ISSUE THREAD

**Issue by hairychestfan** [dalaranwow/dalaran-wow#5333] opened 2018-03-06 21:06 UTC
**Current behaviour**:  Well there are several bugs here. First of all speaking with gnome by entrance you should be able to skip the roleplaying part once you've already done it but this doesnt work. Also you cannot see where the waves are on the map. Another new bug is that Arthas cannot be spoken to at all.. So you cannot even start the roleplaying part so instance cant even be done in the current state.. Its a trap you end up having to kick everyone in the team to leave the place.

**Expected behaviour**: Talking to gnome you should be able to skip the roleplaying part and get teleported right into instance and begin the waves... Alsoyou should see where the waves of mobs have spawned so you know where to go.. Also you should be able to talk to Arthas to progress through the instance.

**Steps to reproduce the problem**:

1. Que up for Culling of Stratholme
2. Talking to npcs to have them do their thing
3. They dont do anything/cant be spoken to.

**Include proofs for this behaviour**

http://storage.koinup.com/090117x112402/112402-5.jpg

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/npc=26499/arthas
http://www.wowhead.com/npc=26527/chromie

**Include Screenshots from the issue if necessary**

**Comment by hairychestfan** [comment] 2018-03-06 21:50
another bug.. MAL'GANIS the final boss of the instance (heroic) only gives EMBLEM OF HEROISM. so people who have done naxx or anything above that content and are getting higher badges from heroics get NOTHING from this boss.

**Comment by Rushor** [comment] 2018-03-08 12:37
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/5257

**Closed by Rushor** 2018-03-08 12:37 UTC
