### ISSUE TITLE
"Can't do that while moving" Mount problem

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#2694] opened 2015-07-19 12:43 UTC
I don't know if someone reported this bug or not but since I can't find it anywhere on the bugtracker I took it upon myself to report it myself.

The thing is, whenever you try to pick an item for a quest, skin\mine something you dismount automatically and starts the channeling to pick the item, but immediately after dismounting and starting the channeling you get intterupted and the "Can't do that while moving" error.

You should be dismounting and be able to pick the object without any issues.

**Comment by Watterx** [comment] 2015-07-19 23:21
yea thats annoying

**Comment by InvincibleEagle** [comment] 2015-07-21 01:18
That only happens with flying mounts (with me at least). I guess it's because you're dropping to the ground as you get off your flying mount, which counts as movement.

**Comment by M0dinstaller** [comment] 2015-07-22 21:00
I can +1 that, not supposed to be like this.

When your flying mount is on the ground and you try to cast something it will count the dismount as some sort of movement and cancel the cast (if it's not instant ofc).
A flying mount dismount shouldn't count as movement if the flying mount is standing on ground. Note that it also happens on druids' flying form.

**Comment by swiftdeath** [comment] 2015-10-13 07:32
Still an issue for me.

**Comment by datbunneh** [comment] 2016-07-03 20:53
Still there.

**Comment by beregas** [comment] 2016-08-02 02:36
just noticed this bug recently when arrived at hellfire. its very anoying on object looting quests

**Comment by beregas** [comment] 2016-09-02 02:39
any fix to be expecting?

**Comment by beregas** [comment] 2016-09-28 02:07
any update on this?

**Comment by robinsch** [comment] 2016-09-28 10:11
Hey, this was already deployed to PTR a few days ago. I just saw this on reddit and didn't check for any open issues.

On PTR.

**Comment by Rushor** [comment] 2016-11-12 14:13
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 14:13 UTC
Labels: Mechanics, On PTR, Priority - High

**Comment by beregas** [comment] 2016-11-26 18:46
How can I access the PTR to test it?

**Comment by Rushor** [comment] 2016-11-26 20:11
you need to write an application to become a tester :)

**Comment by TeridanDW** [comment] 2017-04-01 20:42
Works as intended on ptr.
Hm, i always though this is was result of the lack of delay system on the realm, does this mean we have one working on ptr now?

**Comment by robinsch** [comment] 2017-04-02 08:54
No, it was the result of not resetting some movementflags upon land.
