### ISSUE TITLE
Sale Pending Mail

### ISSUE THREAD

**Issue by arizonalighting** [dalaranwow/dalaran-wow#1390] opened 2014-03-24 15:47 UTC
Does not delete on it's own when you do not open it at all.
Does not delete at all period. Some do most don't.

**Comment by robinsch** [comment] 2016-09-24 10:37
On PTR. Expired mail will now be checked every minute for online players. It can happen that you have both pending sale and mail containing the money from the auction. But within the next minute it should be deleted.

**Comment by Rushor** [comment] 2016-11-12 14:17
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 14:17 UTC
Labels: Mechanics, On PTR, Priority - High

**Comment by Rushor** [comment] 2018-05-27 19:30
Already on PTR.
