### ISSUE TITLE
Trial of the sea lion

### ISSUE THREAD

**Issue by trelystus** [dalaranwow/dalaran-wow#5576] opened 2018-08-07 01:07 UTC
The second half of the pendant is missing off the Silverpine coast. I see that this issue has occurred before, and I'm afraid it's occurring again.

**Comment by trelystus** [comment] 2018-08-07 01:08
The second half of the pendant is missing off the Silverpine coast. I see that this issue has occurred before, and I'm afraid it's occurring again.

**Comment by Chenocide** [comment] 2018-08-08 07:51
It's supposed to be Westfall and Darkshore, not sure where you're getting Silverpine from.

**Comment by Maleficen** [comment] 2018-08-08 11:45
He is probably referring to the Horde side:

[https://youtu.be/Kw8tzeN0I2I](url)

**Comment by Chenocide** [comment] 2018-08-08 22:46
Yea disregard my comment.

**Comment by boujii** [comment] 2018-08-09 18:10
![image](https://user-images.githubusercontent.com/1514895/43916161-cb5e21c2-9bda-11e8-8299-cfcbc7aa7f43.png)

Find the Half Pendant of Aquatic Agility and the Half Pendant of Aquatic Endurance.  Speak with the residents of Moonglade to learn clues as to where these items may be located.$B$BForm the Pendant of the Sea Lion from the two pendant halves.  You need to be in proximity of the Shrine of Remulos to do this.$B$BBring the joined pendant to Dendrite Starblaze in the village of Nighthaven, Moonglade.

For the second trial, you'll need the two halves that make the Pendant of the Sea Lion.  One half draws power from the agility of the sea lion aspect, gliding through water; the other draws power from the incredible endurance of the sea lion aspect.  Druids draw on both these traits equally to embody the aspect of their aquatic form.$B$BSpeak with the locals of Moonglade to learn where the parts may lie, and bring both here to join them together.  Once formed, take the pendant to Dendrite Starblaze.

So it appears you can't find Half Pendant of Aquatic Endurance?
Since items are never "spawned", it must come from a gameobject. And here we find it.
![image](https://user-images.githubusercontent.com/1514895/43916826-a98515c2-9bdc-11e8-93b2-70fc2c654a65.png)

**Comment by boujii** [comment] 2018-08-09 18:40
If you are at Silverpine Forest, look for this boat.

![image](https://user-images.githubusercontent.com/1514895/43918714-d3dd0398-9be1-11e8-9245-83949d16b54d.png)

Then swim out a few miles (lol) to The Great Sea 38,38
Then swim down to the bottom of the ocean and you will see it.
It's very likely that you will barely reach the bottom before you run out of air.

**Comment by boujii** [comment] 2018-08-09 18:42
FYI: The other gameobject 177790 is the westfall one Chenocide was referring to.

**Comment by Golganeth** [comment] 2018-08-09 18:48
Works as intended.

![image](https://user-images.githubusercontent.com/5057942/43919193-848f1d10-9c15-11e8-86ee-eb0186aa0c24.png)

Closing

**Closed by Golganeth** 2018-08-09 18:48 UTC

**Comment by boujii** [comment] 2018-08-09 18:55
I thought the problem was they was unable to locate the second item, not the problem being combining it?
