### ISSUE TITLE
[Quest][Outland] An Improper Burial 10913

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#954] opened 2013-11-01 11:36 UTC
http://www.wowhead.com/quest=10913/
Players are able to finish the quest on 1 of each type of corpse
Slain Sha'tar Vindicator corpse burned (8)
Slain Auchenai Warrior corpse burned (8)
http://www.wowhead.com/npc=21846
http://www.wowhead.com/npc=21859

**Comment by Daveonx** [comment] 2016-06-10 02:53
Currently the quest works with some issues. The can no longer be used on the same corpse multiple times, which is correct. Issue is that [Slain Sha'tar Vindicator](http://www.wowhead.com/npc=21859/slain-shatar-vindicator) only has 7 spawned in-game when is should have 16 according to WoWhead (not sure how accurate it is), same goes for [Slain Auchenai Warrior ](http://www.wowhead.com/npc=21846/slain-auchenai-warrior) which only has 4 spawned.

**Comment by Rushor** [comment] 2016-11-28 21:17
DB/Creature: Add missing Slain Auchenai Warrior + Slain Sha'tar Vindicator spawns

* closes https://github.com/dalaranwow/dalaran-wow/issues/3857
* closes https://github.com/dalaranwow/dalaran-wow/issues/954
* commit: 0c41f1143118deda6953a451010ebd5c6b2b4078

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 21:17 UTC
Labels: Continent - Outland, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-04 16:07
Works as intended on ptr.
