### ISSUE TITLE
[Quest][Outland][Shadowmoon Valley] Thwart the Dark Conclave

### ISSUE THREAD

**Issue by tavna** [dalaranwow/dalaran-wow#1556] opened 2014-04-28 05:46 UTC
I used the quest item on several different spots after killing the ritualists, not working

http://wotlk.openwow.com/quest=10808

**Comment by martijnhaah** [comment] 2015-05-21 15:39
Can confirm... used it under the old god, item went on cast... but no credit.

**Comment by indigoataxia** [comment] 2015-05-21 18:08
Strange someone posted 2 hours ago and I didn't see em but same for me, did not work anywhere but in lava and still did not complete when doing in lava.

**Comment by ashido96** [comment] 2015-07-01 23:53
The item is usable in the center of the c'thun looking thing, but does not give credit upon finishing the spell cast.

**Comment by muffygb** [comment] 2015-08-08 01:43
Confirmed still not working. Only way i got it to cast was on stood in the lava with the creature but no quest completion.

**Comment by catta000** [comment] 2015-09-29 12:07
Confirmed still not working.. item can be used but quest does not complete..

**Comment by Finlaypro** [comment] 2015-10-11 02:20
11/10/2015: Still not working.

Killing Conclave or not, You can use the item in the lava under the big creature that have many eyes but it doesn't complete.

**Comment by DrFuler** [comment] 2016-01-03 18:47
03/01/2016: Still not working.

Can't cast it from where the conclave bird-guys were. Can be cast under the big creature, but doesn't give credit.

**Comment by NovaHiros** [comment] 2016-03-23 13:31
Two years passed, still no credit...

**Comment by NomadicTurtle** [comment] 2016-05-20 09:52
Confirmed, still no credit. Only usable in the lava inside the old god.

**Comment by Golganeth** [comment] 2016-06-04 21:51
Needs some polishing since you are able to use the quest item even if the area isn't unguarded (all NPCs channeling dead) but can be completed perfectly.

> Minor issue.

**Comment by Zibathy** [comment] 2016-11-17 07:46
Still bugged on Algalon.
![wowscrnshot_111716_014332](https://cloud.githubusercontent.com/assets/7729864/20380430/a4d7e39e-ac67-11e6-923d-58a159b8817b.jpg)
![wowscrnshot_111716_014520](https://cloud.githubusercontent.com/assets/7729864/20380432/a4d81c42-ac67-11e6-8543-8c29b87166b8.jpg)
![Uploading WoWScrnShot_111716_014530.jpg…]()
![Uploading WoWScrnShot_111716_014532.jpg…]()

**Comment by Rushor** [comment] 2016-11-17 13:45
DB/Quests: Thwart the Dark Conclave - Add spellscript and increase spellfocusrange

* closes https://github.com/dalaranwow/dalaran-wow/issues/1556
* commit: e5176b38ee0f8909af34b9f094fb79682c089b37

![GitHub Logo](http://i.imgur.com/XvMRocE.jpg)
![GitHub Logo](http://i.imgur.com/4Bv3TFj.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 12:39
Hello, few issues I noticed here:
 - event can be done only once per server restart, after all creatures are respawned (force respawn with command) player will only gets the error pointed by everyone on top.
 - the 2 npcs http://wotlk.openwow.com/npc=22138 at the back a trying to cast spell http://wotlk.openwow.com/spell=38469 but are out of range from the imp. 60 yards aren't enough.
Screenshot from retail:
![image](https://cloud.githubusercontent.com/assets/6797611/24609475/9f431808-1883-11e7-91f3-34189b9b8745.png)

**Comment by Lothloryen** [comment] 2017-12-09 18:09
Hello there,

This quest works is completable multiple times without problem. If anyone finds an issue, feedback would be welcome so we can fix it.

Thank you for the reports.

**Closed by Lothloryen** 2017-12-09 18:09 UTC
Labels: Area - Outland, General - Quests, Works - but it needs improvements.
