### ISSUE TITLE
[NPC] Dr. Whitherlimb

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3567] opened 2016-07-08 05:51 UTC
**Description**:
Unless it is intentional behaviour, the spawn place/timers for the NPC are off.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The respawn timer is 8 hours, and the NPC seems to spawn in one place at a time.
**Expected behaviour**: Tell us what should happen instead
The respawn timer should be 2 hours, and the NPC should spawn in 2 places at a time:
either the 2 north ziggurats or 2 south ziggurats.
There are singular reports of him being present in all 4 ziggurats too.
Based on that it can also be assumed that he might be spawned in all 4 ziggurats, and respawns  2 hours after death in every place, leading to him being spawned in multiple spots. That's a guess though.
**Include proofs for this behaviour**

http://www.wowhead.com/npc=22062/dr-whitherlimb#comments:id=41474
http://www.wowhead.com/npc=22062/dr-whitherlimb#comments:id=72788
http://www.wowhead.com/npc=22062/dr-whitherlimb#comments:id=1520347
http://www.wowhead.com/npc=22062/dr-whitherlimb#comments:id=56071
http://www.wowhead.com/npc=22062/dr-whitherlimb#comments:id=749587
http://et.worldofwarcraft.wikia.com/wiki/Dr._Whitherlimb

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Dr. Whitherlimb NPC ID 22062

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-16 14:19
Adding 4 spawns with 2 hours respawntime would be enough

**Comment by Rushor** [comment] 2016-11-16 14:29
DB/Creature: Dr. Whitherlimb - Add 4 spawnpoints with 2 hours respawntimer

* closes https://github.com/dalaranwow/dalaran-wow/issues/3567
* commit: 18f9310ff13026ab2908aa1b50728f9db0223e25

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-16 14:29 UTC
Labels: Continent - Classic, On PTR

**Comment by Rushor** [comment] 2017-03-10 09:11
merged this fix from TC https://github.com/TrinityCore/TrinityCore/commit/fb58e3f1b55260f79b78d9b27400d85c9d447703 for him. so he will be pooled and only one spawn can be active at the same time.

Please discuss in https://github.com/TrinityCore/TrinityCore/commit/fb58e3f1b55260f79b78d9b27400d85c9d447703 if this behaviour is correct or not.

**Comment by Rushor** [comment] 2017-03-10 09:15
DB/Creature: Dr. Whitherlimb - Add pool template and a few missing spawns

(respawntime of Dr. Whitherlimb is 72000 seconds)

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3567
* commit: 6bb877ceb8692cf64a2d6ae5193c896c5d1baa4f

**Comment by TeridanDW** [comment] 2017-04-01 08:59
> DB/Creature: Dr. Whitherlimb - Add 4 spawnpoints with 2 hours respawntimer

Is working as intended on ptr.

> DB/Creature: Dr. Whitherlimb - Add pool template

Is not on ptr yet.

The creature should speak on aggro.
Proof:
http://et.worldofwarcraft.wikia.com/wiki/Dr._Whitherlimb
https://www.youtube.com/watch?v=4zkXFf9AIPk

Texts:
``` sql
-- Add texts
DELETE FROM `creature_text` WHERE `entry` = 22062; 
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(22062,0,0,' It is very kind of you to donate your organs!',12,0,100,0,0,0,0,0,''),
(22062,0,1,' Be proud, your brain will be put to good use in one of my abominations.',12,0,100,0,0,0,0,0,''),
(22062,0,2,' Excellent! Fresh parts!',12,0,100,0,0,0,0,0,'');
```
