### ISSUE TITLE
[ICC] Abomination transformation issues with transformed druid

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#4725] opened 2017-05-30 03:24 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Context: ICC 25 - Professor Putricide
The druid in our raid today was running into an issue where if he moved or rotated his character in any manner after clicking on the table he stated that abomination would not have any abilities and that also /rl or /reload would not bring the bar back. 

**Expected behaviour**: Tell us what should happen instead
As a paladin tank I was able to move directly after clicking on the table and transformed, we think it MAY have something to do with the druid being transformed causing the issue

This does need some further clarification such as testing if he has any issues when NOT transformed and clicking on the table. As well as any druid that does click on the table while transformed (in this case bear form) that does not have this issue would just mean we need to yell at our bear to uninstall UI addons. 

http://www.wowhead.com/npc=36678/professor-putricide
Sorry I was not able to find the ID for the table game object

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or

**Comment by Craftymind** [comment] 2017-05-30 17:21
Does your druid use the addon Bartender ? If so, he needs to activate all action bars that he previously had disabled. One of our Warriors had similar issue on Blood-Queen Lana'thel where after 1 min passed of being bitten, his action bar wouldn't change and wouldn't offer him the spell with which he should bite other players. Enabling the action bars fixed this for him, so it might help your druid too.

Another solution is to drop Bartender (if he's using it) and just go with ElvUI or the standard action bars.

**Comment by Rushor** [comment] 2017-06-30 12:50
Scripts/IcecrownCitadel: Putricide | Mutation Init - Remove Shapeshift Auras on Affect Remove 

* Problem was that shapeshifted people summon the vehicle, but the player were not mounted on it because of the shapeshift
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4725
* commit: 7114d4032834a5a232a6f62769b1d3b9e61c2863

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-06-30 12:50 UTC
Labels: Area - Instances, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2018-01-30 18:08
Works as intended on PTR.
