### ISSUE TITLE
[Item] Quest Reward: Small Velvet Bag

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#1938] opened 2014-10-04 18:46 UTC
The quest reward Small Velvet Bag from the quest Gem Perfection does not contain any item, it should contain at least 1 perfect gem.

http://www.wowhead.com/item=41888/small-velvet-bag

**Comment by Rushor** [comment] 2016-11-23 10:34
DB/Item: Update lootchances for Small Velvet Bag

* closes https://github.com/dalaranwow/dalaran-wow/issues/1938
* commit: 98712c3f1291ab8261170001cac7feb7a36d191e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 10:34 UTC
Labels: Items, On PTR
