### ISSUE TITLE
Quest: The Drakkensryd

### ISSUE THREAD

**Issue by AizenD-WoW** [dalaranwow/dalaran-wow#388] opened 2013-08-05 17:31 UTC
Once players accept the quest, they are not mounted on the Proto-Drake and sent off to the Temple of Storms. Once they arrive in that area they should use the harpoon provide by the quest giver to "jump" from Proto-Drake to another one and fight while mounted riders, it should be repeated till 10 are defeated.

Quest might require some heavy scripting due to its complicated mechanics, but should be regarded high priority since its required for players to start Sons of  Hodir reputaition.

http://www.youtube.com/watch?v=c9i4SD9IeeY
http://www.wowhead.com/quest=12886/the-drakkensryd

**Comment by Trixsterme** [comment] 2015-04-11 09:28
I'm one of the grateful guys towards your good work you're all doing here.
I have this little problem with the quest chain for getting Sons of Hodir rep... 
I've got to the point where I do quests in Brunhildar Village, and there was the Drakkensryd quest that gave me debrief instantly and I could accepted it, but I chose to press escape to see if there are other quests available. When I tried to retake or click quest, it was only there with a grey "?" and can't be clicked or taken. Can this be solved, please?

**Comment by Jorar** [comment] 2015-05-20 22:40
Just accepted this quest does not seem to be working. I can fly manually on my own mount to the area and jump on the backs of the protodrakes  but cannot attack the riders.

**Comment by Lothloryen** [comment] 2015-05-21 13:03
Hello there,

This quest is working now, it still needs few improvements though. I will close the issue and will update when some details are corrected.

Thank you.

**Closed by Lothloryen** 2015-05-21 13:03 UTC
Labels: Northrend, Quests

**Comment by Vaxsysl** [comment] 2015-05-22 11:37
We have to fly there manually, we can use the harpoon to mount the drakes. I can attack the riders. The only problem atm (other than not being sent off) is that they're not moving. They're just sitting there, spawned.

**Comment by Lebaowski** [comment] 2015-06-07 04:17
Credit is not given for killing the Hyldsmeet Drakerider after manually flying there and harpooning onto the proto-drake at the moment.

Tried relogging and abandoning the quest but neither worked.

**Comment by exiledone** [comment] 2015-11-27 15:59
quest works almost as intended

**Comment by fizzl** [comment] 2016-03-03 12:26
Currently stuck on one of the ornaments.
When I got there, all the dragons were static. I could not move or attack anything. Decided to try and harpoon an ornament. That worked. Kinda...

Now I'm stuck in the ornament and cannot do anything. Not even stone home or use the "auto-unstuck" feature.

**Comment by beregas123** [comment] 2017-03-05 17:58
Quest is doable, were able to complete it with no prob

But the animation are still wrong, drakes are standing still flying.

**Comment by Rushor** [comment] 2017-03-06 09:46
that issue is also fixed with https://github.com/dalaranwow/dalaran-wow/issues/4349

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
