### ISSUE TITLE
[Quest] The Touch of Zanzil - Curse doesn't work properly and Doc Mixilpixil disappeared

### ISSUE THREAD

**Issue by Alavarin** [dalaranwow/dalaran-wow#3015] opened 2015-11-30 21:19 UTC
I layed down, he diagnosed me and then PUFF, he disappeared and I can't complete that quest. I guess only thing I can do is wait for respawn but it's kinda annoying. Empty room here:
![doc](https://cloud.githubusercontent.com/assets/16082894/11484764/346d5eb2-97b0-11e5-8290-5ece5abb0f7a.png)
And completed quest in empty room:
![doc2](https://cloud.githubusercontent.com/assets/16082894/11484772/3ff4e8e0-97b0-11e5-8322-14477259a447.png)
By the way - curse should affect my Stealth but it does the thing only with Agility.
![doc3](https://cloud.githubusercontent.com/assets/16082894/11484793/62de3294-97b0-11e5-9421-327390d00e02.png)

**Comment by 1ncredebil** [comment] 2016-04-14 16:02
Confirmed.
Main issue: NPC [Doc Mixilpixil](http://www.wowhead.com/npc=7207/doc-mixilpixil) disappears after diagnosing you.
Secondary issues(not important):
1. After accepting the quest the player has to target Doc and /lay for the diagnosis to start, instead it just starts automatically.
2. [Touch of Zanzil](http://www.wowhead.com/spell=9991/touch-of-zanzil) not affecting stealth

**Comment by Rushor** [comment] 2016-11-17 21:09
DB/Creature: Doc Mixilpixil - should not despawn 

* closes https://github.com/dalaranwow/dalaran-wow/issues/3015
* Doc Mixilpixil will no longer despawn after queststart
* Touch of Zanzil will disable the use of stealth
* commit: ef2a5ba8ed021849c3a1bd49b5a65b46978efdd2

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-01 19:07
Everything above works as intended on ptr, however i would like to suggest diffrent solution regarding Doc Mixilpixil's SAI:

``` sql
-- Doc Mixilpixil SAI
SET @ENTRY := 7207;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,19,0,100,0,2608,0,0,0,64,0,2,0,0,0,0,7,0,0,0,0,0,0,0,"Doc Mixilpixil - On Quest '' Taken - Store Targetlist"),
(@ENTRY,0,1,0,22,0,100,1,125,0,0,0,80,@ENTRY*100+00,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - Received Emote 125 - Run Script (No Repeat)"),
(@ENTRY,0,2,0,40,0,100,512,3,7207,0,0,80,@ENTRY*100+01,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Waypoint 3 Reached - Run Script"),
(@ENTRY,0,3,0,25,0,100,0,0,0,0,0,82,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Reset - Add Npc Flags Gossip & Questgiver");

-- Actionlist SAI
SET @ENTRY := 720700;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,83,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Remove Npc Flags Gossip & Questgiver"),
(@ENTRY,9,1,0,0,0,100,0,0,0,0,0,72,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Close Gossip"),
(@ENTRY,9,2,0,0,0,100,0,1000,1000,0,0,66,0,0,0,0,0,0,12,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Set Orientation <unsupported target type>"),
(@ENTRY,9,3,0,0,0,100,0,100,100,0,0,5,353,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Play Emote 353"),
(@ENTRY,9,4,0,0,0,100,0,2000,2000,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Say Line 0"),
(@ENTRY,9,5,0,0,0,100,0,3000,3000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Say Line 1"),
(@ENTRY,9,6,0,0,0,100,0,3000,3000,0,0,53,0,7207,0,0,0,2,1,0,0,0,0,0,0,0,"Doc Mixilpixil - On Script - Start Waypoint");

-- Actionlist SAI
SET @ENTRY := 720701;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,100,100,0,0,66,0,0,0,0,0,0,12,0,0,0,0,0,0,0,"On Script - Set Orientation <unsupported target type>"),
(@ENTRY,9,1,0,0,0,100,0,1000,1000,0,0,15,2608,0,0,0,0,0,12,0,0,0,0,0,0,0,"On Script - Quest Credit ''"),
(@ENTRY,9,2,0,0,0,100,0,100,100,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"On Script - Evade");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry`=7207;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(22, 2, 7207, 0, 0, 9, 0, 2608, 0, 0, 0, 0, 0, '', '');

```

With this script we add the part:

> _**/Lay**_ down to be examined by Doc Mixilpixil. How can he find the cure if he can't find the cause?

Which is the emote /lay when the player targets the creature, however i couldn't find the id of emote "/lay" so i used 125 (which is "/raise") this needs to be changed and the quest is good to go.

Note: A player can start the quest's script only if he has the quest http://wotlk.openwow.com/quest=2608 in his log and uncompleted, also the event can't be spammed by spamming /raise on target.

**Comment by Rushor** [comment] 2017-07-01 19:39
TEXT_EMOTE_LAYDOWN              = 61,

**Comment by Rushor** [comment] 2017-07-01 19:41
DB/Quest: Doc Mixilpixil - Update questevent - Event now only starts after player handled the lay-down textemote

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3015
* commit: 4327563d689338c62a5fc28293294264d14ed591

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-01 19:41 UTC
Labels: Area - Classic, General - Quests

**Comment by charliedaboss** [comment] 2018-03-20 20:19
This guy just disappeared again...can't complete the quest.
