### ISSUE TITLE
[NPC][WotlK]Onslaught Knight unattackable

### ISSUE THREAD

**Issue by Muph0** [dalaranwow/dalaran-wow#4622] opened 2017-03-21 21:04 UTC
Hello
I was doing the Fresh remount quest and I had to kill the knights to get riding crops and steal horses. However, the knights seem to be unattackable and invurneable. They don't even attacked me at all so there's no way to kill them.

**Comment by Rushor** [comment] 2017-03-21 21:13
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/637. the fix need to be tested on ptr first. it will be applied with the next changelog.

**Closed by Rushor** 2017-03-21 21:13 UTC
Labels: Duplicate / Invalid Report
