### ISSUE TITLE
Blood elf death knight - master of ghouls #death knight

### ISSUE THREAD

**Issue by stewazy** [dalaranwow/dalaran-wow#1838] opened 2014-08-28 21:00 UTC
Hello I have a problem with my dk in unholy spec when i summon my ghoul with the talent master of ghouls it should have a name but it doesn't it just says Risen ghoul it works fine. But when i use death pact on it, the ghoul just disappears and it doesn't trigger the cooldown on raise dead spell, i have to relogg to make it work :S. Am I the only one with this problem or r there other people with similar problems. The summon ghoul and death pact works normally when i'm in blood spec. Can someone help me, what steps should i take to solve this problem ? Thanks in advance

**Comment by Rushor** [comment] 2016-12-04 11:39
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/1815

**Closed by Rushor** 2016-12-04 11:39 UTC
Labels: Class - Death Knight, Duplicate / Invalid Report
