### ISSUE TITLE
[NPC] Black Cat - Hallow's End

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3823] opened 2016-11-09 19:49 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
Currently all the Black Cats are still spawned across Dalaran even though the event has ended long ago.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Black Cats are still spawned even though event has ended.
**Expected behaviour**: Tell us what should happen instead
The Black Cats shouldn't be spawned anymore or visible to players.
**Steps to reproduce the problem**:

1. Walk around Dalaran
2. See the Black Cats are still spawned
3. Kill them out of joy! Or slaughter, you could technically still slaughter them.

**Include proofs for this behaviour**
![image](https://cloud.githubusercontent.com/assets/5054924/20152287/f492129c-a6bd-11e6-8c31-361f35442e12.png)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/npc=22816
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-09 20:00
DB/Creature: Remove Black cat (Hallow's End)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3823
* commit: 32b8556f0c3fbc93abc19b622eb03d002e8b0374

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-09 20:00 UTC
