### ISSUE TITLE
[Item] Argent Squire Mount

### ISSUE THREAD

**Issue by Danielicius** [dalaranwow/dalaran-wow#2535] opened 2015-06-17 16:28 UTC
The Argent Squire Mount is not working, i bought it, use the item, it gives me the Archivement "Pony up!" but nothing more happens, my argent Squire didnt get his mount or the option to have access to the Bank it only opens the shop.

**Comment by Warthug** [comment] 2015-06-17 18:21
Actually Argent Squire/Gruntling, is not showing any options at all, like the one that allows him to wear a champion's pennant of your faction on him, even if you become an exalted argent champion of the alliance/horde you cannot do it, He's showing a shop instead.  Here is a couple of videos from wotlk, you can see how it should be when you meet these different criterias. 
https://www.youtube.com/watch?v=7Vectgmyto4
https://www.youtube.com/watch?v=acwB_y6tZ9Y

**Comment by Spruitje** [comment] 2015-07-15 17:16
Confirmed this not working
Did get the Pony up! achievement and i have all the other rep and champion achievements at 5 cities
Shame i didn't notice this bugreport before because i've wasted 150 seals on an achievement, while i could have spend it on mounts and heirlooms

The item in question is "Argent Pony Bridle"
http://www.wowhead.com/item=47541/argent-pony-bridle

**Comment by M0dinstaller** [comment] 2015-07-22 03:16
Can this get brought up a bit in the priority list ? It possibly is the only reason some people will level their reps and do the dailies for 1 month, and it's unique in the game, having ah/mailbox/bank from anywhere every 4 hours seems great, it would be awesome if it could get fixed !
Many thanks to the dev for your work on the serv.

**Comment by Augur89** [comment] 2015-09-19 18:43
Seconded, spending 150 seals to find only the vendor function is available is annoying to say the least. There are mammoths that do the same and are easier to get (the number of seals obtainable per day being limited, while gold isn't).

The utility the pony brings is important for those of us who are not Engineers and the effort to obtain it is no joke, so I'd like this to get some attention ;-)

**Comment by LoveDalaranWow** [comment] 2016-06-10 10:31
This is still not working, and it's a huge handicap for non-engineer characters (also considering the tedious grind required for it).

**Comment by Lothloryen** [comment] 2016-06-30 19:37
Hello there,

Thank you for the reports, it shall be scripted and available after the next scheduled maintenance.

**Comment by LoveDalaranWow** [comment] 2016-07-03 11:05
Unfortunately, nothing changed since the maintenance.

**Comment by LoveDalaranWow** [comment] 2016-07-08 14:16
After this maintenance, the pet is completely broken: can't be used as a shop, the only option it gives is only one pennant (which doesn't do absolutely nothing when clicked). Either with the character being on a horse or not, you can't do anything right now.

**Comment by Lothloryen** [comment] 2016-07-08 16:14
Hello there,

I had some unexpected troubles with yesterday's maintenance and I had to revert part of the updates. We are working on it and hopefully I will be able to perform a complete update this night.

**Comment by LoveDalaranWow** [comment] 2016-07-12 18:42
Alas, this little guy is still bugged and can't be used for anything at the moment.

**Comment by LoveDalaranWow** [comment] 2016-07-14 08:29
Works perfectly, thanks to all the staff for scripting perfectly this little guy!

**Comment by kelvala** [comment] 2016-09-30 12:25
Argent Squire is not showing any options.

**Comment by Rushor** [comment] 2016-12-04 08:58
going to rescript this whole guy soon.

**Comment by Rushor** [comment] 2016-12-04 11:22
Scripts/Pet Implemented Argent Squire/Gruntling and Argent Pony Bridle

* closes https://github.com/dalaranwow/dalaran-wow/issues/2535
* @ testers: pls add the related quests and achievements before you summon the pet, else it's script will not work
* commit: de311e83176db7d4f1fe24d307717b80d8b10fc9

![GitHub Logo](http://i.imgur.com/47Bds8Q.jpg)
![GitHub Logo](http://i.imgur.com/krxPCgV.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-04 11:22 UTC
Labels: Fixed - Waiting for PTR Update, General - Items
