### ISSUE TITLE
[Quest][Northrend] Army of the Damned

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3804] opened 2016-11-07 16:01 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
The quest "Army of the Damned" is currently half working and doable, while still encountering some bugs. Some improvements are needed.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Well, first of all, while doing the quest and controlling Arthas you cannot attack the Foot Soldiers/Captain. 
Also, you cannot use : "Soul Cleave", doing damage to up to 4 targets, restoring mana.
The minions under your control do not attack or protect you.
The soldiers do not attack or try to kill you.
So, basically speaking, if you do not kill enough soldiers and raise them with : "Gift of the Lich King", raising ghouls from the dead Lordaeron Footmen in a ground-targeted AoE, you will not be able to regenerate mana from "Consume Minions", restoring 10% health/mana per nearby ghouls consumed, up to 5 ghouls at a time.
This in turn prevents you from killing soldiers in the only way possible, which is by using : "Deathstorm", doing 25,000 damage per target to up to 12 targets.

**Expected behaviour**: Tell us what should happen instead

You should be able to attack/kill soldiers.
Soldiers should be able to attack and kill you (Arthas).
Your ghouls/undead minions should defend you/attack/kill the soldiers.
You should be able to use Soul Cleave, and it should regenerate your mana.

**Steps to reproduce the problem**:

1.  Complete the chain quest up to "Army of the Damned".
2.  Speak to Matthias Lehner.
3.  Try to attack or use Soul Cleave or see if the minions attack/defend you.

**Include proofs for this behaviour**

Currently don't have any ps to prove this, as I did the quest earlier today and did not think about attaching some pictures to a new thread. So currently I cannot take the quest again to inclue some evidence, but I can include the web pages I got my info from : 

https://www.youtube.com/watch?v=ty7dzVLHCOE

http://www.wowhead.com/quest=13236/army-of-the-damned

http://wowwiki.wikia.com/wiki/Quest:Army_of_the_Damned (Also shows the NPC skills/dmg etc)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=13236/army-of-the-damned (quest=13236)

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrAndersonX** [comment] 2016-11-07 16:02
Also some problems have been referred to in ticket nr. #921 .

**Comment by Rushor** [comment] 2016-11-27 11:31
DB/Quest: Army of the Damned - Ghoulish Minion attack victims on summon now

* updates https://github.com/dalaranwow/dalaran-wow/issues/3804
* ref: https://github.com/TrinityCore/TrinityCore/issues/17205
* commit: fd11b486dd865de6373f129750ca01683ed27089

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 11:31 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:49
Works as intended on PTR.

**Comment by MightyFlix** [comment] 2019-03-18 12:16
Quest got back to previous behaviour, can't complete for the same reasons OP described.
