### ISSUE TITLE
Rocket Boots Xtreme Lite

### ISSUE THREAD

**Issue by dxxa** [dalaranwow/dalaran-wow#3364] opened 2016-06-04 17:44 UTC
Hello
I want to report item Rocket Boots Xtreme Lite does not work anymore, this item before Onixya release working correctly but now indicates the CD of 5 min but does not work, I tried to recreate it again, but nothing, it is inoperable
thanks

**Comment by Golganeth** [comment] 2016-06-04 18:19
Duplicate of #3247

**Closed by Golganeth** 2016-06-04 18:19 UTC
