### ISSUE TITLE
Daily Quest: The Not-So-Friendly Skies

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1131] opened 2014-01-24 00:56 UTC
http://www.wowhead.com/quest=11035

There are only about 3 attackable Netherwing Transporters, meaning you have to wait for respawns all the time. On top of that, the droprate for the quest item Netherwing Relic (http://www.wowhead.com/item=32509) is much too low. It seems to have about a 30% drop rate or less, where wowhead says it should be near 100% (98% WH says)

**Comment by ashido96** [comment] 2015-07-02 00:19
Going to confirm both the comments above, though there a couple that float around the northern floating stones, so you have about 5/6 transporters to kill, drop rate is still very crappy however.

**Comment by Rushor** [comment] 2016-11-28 14:14
DB/Quest: The Not-So-Friendly Skies - Update questscript

* creatures (.go c 78496) + (.go c 52330) will now summon Dragonmaw Transporter which will flight their path after summon 
* increase droppchance for Netherwing Relic to 100 %
* closes https://github.com/dalaranwow/dalaran-wow/issues/1131
* commit: 066906a9a21edc517682b9aded2839696c6c38be

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 14:14 UTC
Labels: Continent - Outland, On PTR, Quests
