### ISSUE TITLE
[NPC][Northrend] The Underhalls

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3885] opened 2016-11-27 11:22 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 While descending down The Underhalls sometimes mobs get aggro on you after you climb down the stairs, and they fly/swim up through the floor and attack you. A similar thing happens during the quest "Deep in the bowels of the underhalls" (http://www.wowhead.com/quest=13042/deep-in-the-bowels-of-the-underhalls) when u have to kill Apprentice Osterkilgr. After getting him low hp, he sometimes flies/swims through the roof/floor above also leaving combat and reseting.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 Mobs can pass/swim through floors/texture.

**Expected behaviour**: Tell us what should happen instead
Mobs should not pass/swim through it.

**Steps to reproduce the problem**:

1.  Go to The Underhalls.
2.  Go down the stairs while also killing the mobs u encounter along the way.
3. 

**Include proofs for this behaviour**
 
https://postimg.org/gallery/1z4j4eg9a/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-27 11:32
we need to add "ignore-pathfinding" for these creatures

**Comment by MrAndersonX** [comment] 2016-11-27 11:37
It seems even the minions spawned by Army of the Damned and Raise Dead seem to be able to pass through the textures.

**Comment by Rushor** [comment] 2016-11-27 11:44
https://github.com/TrinityCore/TrinityCore/issues/9753

**Comment by Rushor** [comment] 2016-11-27 12:29
DB/Creature: Add "ignore-pathfinding" for creatures in The Underhalls

* closes https://github.com/dalaranwow/dalaran-wow/issues/3885
* commit: 7021cfe823686b6dd5df678a8abe5854b16e2c00

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 12:29 UTC
Labels: Continent - Northrend, On PTR, Quests
