### ISSUE TITLE
Runeforging does not work on Heirloom Weapon

### ISSUE THREAD

**Issue by vison2** [dalaranwow/dalaran-wow#2359] opened 2015-04-25 18:03 UTC
Trying to Runforge a Heirloom Weapon (Dal'Rends Sacred Charge) always results in the error

"Target is too low level"

I know this was also an issue on "live" that got changed with Cataclysm... So it´s technically not a bug, But maybe a feature that should be reworked.

**Comment by Golganeth** [comment] 2015-04-25 19:07
Works as intended, closing up since this is not a bug.

You should visit the [Suggestions and Opinions](http://www.dalaran-wow.com/forums/news-and-rules/suggestions-and-opinions) section of the forums, although I can tell you beforehand that we'll never add any in-game custom feature.

**Closed by Golganeth** 2015-04-25 19:07 UTC
