### ISSUE TITLE
[Death Knight] Cast Corpse Explosion on pet with macro

### ISSUE THREAD

**Issue by AraelWindwings** [dalaranwow/dalaran-wow#2201] opened 2015-01-27 21:29 UTC
The actual fix on Corpse Explosion doesn't allow the player to make an efficient macro to cast this spell on his/her ghoul.

Example:

/cast [@pet] !Corpse Explosion
/cast [target=pet] corpse explosion

And many more don't work.

It keep saying I can't use it right now (no body found on the ground).

You must target it first and then cast it.

No need to say this will change your current target.

Not so important but troublesome.

**Comment by MikeViper** [comment] 2015-01-28 16:59
Confirmed, not that major but still problematic. Also not to burden the tracker with more bugs about Corpse Explosion, I'd want to report that its glyph of increasing range by 5 does not work when pet is exploded, it only works via normal way of using it on a corpse.

Furthermore, the explosion when used on pet can be accidentely canceled if the DK uses the spell right when the pet uses his Claw ability. As of result the 40 runic power cost is lost, cooldown is applied, and the explosion being canceled does not trigger. The pet once being made to explode has an "arming" time of 1.5 second, basically its own cast before it dies to detonate. And of course its explosion spell should not be canceled by its own claw ability.

**Comment by AraelWindwings** [comment] 2015-01-28 18:46
Corpse Explosion glyph works only on YOUR Corpse Explosion, the pet's one is considered its own skill. 

So it's working as it should be.

**Comment by Rushor** [comment] 2017-03-10 09:30
once part of this was fixed by https://github.com/TrinityCore/TrinityCore/commit/84229f89e4d09162f9a00e127cf37eacb3e82683

and as already said in:  

> Corpse Explosion glyph works only on YOUR Corpse Explosion, the pet's one is considered its own skill.

> So it's working as it should be.

The skill works as intended

**Closed by Rushor** 2017-03-10 09:30 UTC
Labels: Class - Death Knight

**Comment by Rushor** [comment] 2017-03-10 09:38
the remaining issue will be handled in https://github.com/dalaranwow/dalaran-wow/issues/3548
