### ISSUE TITLE
[Quest][Outland] Blast The Gateway

### ISSUE THREAD

**Issue by Anomander1** [dalaranwow/dalaran-wow#2344] opened 2015-04-12 16:31 UTC
the Sizzling Embers doesn't release a Living Flare

**Comment by ashido96** [comment] 2015-05-14 17:36
Confirmed, quest ID" 11516
Blast the Gateway: http://www.wowhead.com/quest=11516/blast-the-gateway
Sizzling Embers: http://www.wowhead.com/item=34253/sizzling-embers
Living Flare: http://www.wowhead.com/npc=24916/living-flare

**Comment by Braniacz** [comment] 2016-06-22 10:15
Still bugged

**Comment by Rushor** [comment] 2016-11-28 11:47
DB/Quest: Implement quest: Blast The Gateway

* closes https://github.com/dalaranwow/dalaran-wow/issues/2344
* commit: 4ebbf7b009bdc469abbb1dace5875772d9e3e2ba

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 11:47 UTC
Labels: Continent - Outland, On PTR, Quests
