### ISSUE TITLE
[Quest][Classic] Mok'thardin's Enchantment

### ISSUE THREAD

**Issue by rifles** [dalaranwow/dalaran-wow#2103] opened 2014-11-30 22:21 UTC
The issue with this quest is the fountain that you must interact with to receive the Holy Spring Water (http://www.wowhead.com/item=737#contained-in-object) has a very long respawn timer. I showed up, did the entire killing portion of the quest, and then spent over 20 minutes sitting trying to figure out how to interact with the fountain before the interactable part of the fountain appeared and I could actually get the item. Appears to have a respawn of greater than half an hour, probably closer to 40-45 minutes, though I don't know how long before I even began the quest it was last used. 

The respawn timer should be reduced dramatically to make this quest more feasible for multiple people (more than one person per hour) to do.

The fountain appears as:
![wowscrnshot_113014_171400](https://cloud.githubusercontent.com/assets/10013678/5239585/cc8d61ea-78b4-11e4-8ca5-c30bbd1c3965.jpg)

Location on the map: 
![wtegat3](https://cloud.githubusercontent.com/assets/10013678/5239590/f2591360-78b4-11e4-9266-8404e10f9703.png)

**Comment by shilofax** [comment] 2015-06-15 23:13
Still bugged.

**Comment by rinleezwins** [comment] 2016-04-16 19:28
Got to the fountain right after someone snatched the item, 15 minutes break I guess...

**Comment by Rushor** [comment] 2016-11-26 10:39
DB/Gameobject: The Holy Spring - Reduce spawntime to 2 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/2103
* commit: 9f12787f71ac748aa9108880c26fcfab86d4cf26

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 10:39 UTC
Labels: Continent - Classic, On PTR, Quests
