### ISSUE TITLE
Death Knight: Dancing Rune Weapon

### ISSUE THREAD

**Issue by Lenc** [dalaranwow/dalaran-wow#1098] opened 2014-01-09 01:00 UTC
Dancing Rune weapon does 2-3 damage on target. It does not apply its own diseases and does not mimic players attacks. It simply auto attacks for 2-3 damage.

How it should work: Dancing rune weapon should apply its own diseases when player applyes his/hers, it should do every attack the player does but for 50% reduced damage.

**Comment by taralej90** [comment] 2015-05-20 13:35
Is this fixed after last night's update? I tested it yesterday before the update and the issues were still present - not applying diseases, auto-attacking for 1 dmg. If it is, then BDKs may finally become viable for DPS, as they should be.

**Comment by taralej90** [comment] 2015-06-14 18:18
It is also worth noting that DRW completely ignores target dummies for some reason.

**Comment by mondvrr** [comment] 2015-09-25 10:39
the dancing rune weapon dont even hit the 2-3 damage, it stay on the ground and dont mimic any of the dk skills

**Comment by lonesomeduck** [comment] 2015-09-26 15:57
I can confirm what mondvrr said. DRW when used just sits in the same position and does nothing. I used it on both dummies and npcs and it never works, no matter what abilities I use. This is really a bummer since I wanted to play blood dps

**Comment by taralej90** [comment] 2015-09-27 23:37
That's because it needs to be used on a target which has aggro and dummies have no aggro. Try it on an NPC which will fight back and you'll see that it starts attacking and mimicking moves... but only for 2-3 dmg.

**Comment by mondvrr** [comment] 2015-09-28 08:30
used it on npc with has aggro. 0 damage no mimic moves.

**Comment by Lothloryen** [comment] 2015-09-28 12:40
Hello there,

I shall take a look into this issue right after ToC's release.

Thank you.

**Comment by Lothloryen** [comment] 2015-10-21 10:58
This spell is almost finished, I need a bit more of time to correct two glitches and it shall be deployed to the live server.

**Comment by Lothloryen** [comment] 2015-10-22 09:46
Hello again,

This spell shall be working as intended after the next scheduled maintenance.

Thank you.

**Comment by Lothloryen** [comment] 2015-10-23 06:57
Hello again,

It is already deployed, any feedback will be appreciated.

**Comment by PolarCookie** [comment] 2015-10-23 07:04
dancing rune weapon is not applying it's diseases, it does direct damage of icy touch but no disease

**Comment by Lothloryen** [comment] 2015-10-23 08:54
Hello,

Yes, PolarCookie, you are right. After the next scheduled maintenance the Dancing Rune weapon will successfully apply the diseases.

Thank you.

**Comment by Lothloryen** [comment] 2015-10-24 09:28
Hello again,

It has been deployed to the live server, it shall also apply the proper diseases now.

Thank you.

**Comment by Lothloryen** [comment] 2015-10-28 09:35
Hello there,

I am temporary reverting this spell to its previous state in order to improve few things. I shall deploy it again during the next few days.

Thank you.

**Comment by Lothloryen** [comment] 2015-11-19 12:46
Hello again,

Sorry about the delay, this spell is going to be re-enabled after the next scheduled maintenance.

Thank you.

**Comment by mondvrr** [comment] 2015-11-30 21:47
is the fix up? i just try it and still don't work not 100% at least in 1 case the drw does an autoattack but not the skill and the next time i tried the drw don't do nothing so idk if is up or not.

**Comment by PolarCookie** [comment] 2015-12-19 23:23
when is the "next scheduled maintenance"? it's been a month now.

**Comment by ciccioriccio** [comment] 2016-05-30 07:55
The fix has never beed applied, and Dancing Rune weapon is still bugged out. Please give it an high priority, becouse it is compromising an entire talent tree.

**Comment by MrAndersonX** [comment] 2016-10-24 18:06
Please, please, pretty please with a cherry on top fix it ASAP. I wanna go blood and I want to use this talent so much. I'll do censored things for it to work :D. And donate when I get my paycheck again :P.

**Comment by epaulito** [comment] 2016-11-29 15:52
(Y)

**Comment by epaulito** [comment] 2016-11-29 15:55
(y)

**Comment by Rushor** [comment] 2016-11-29 21:07
@MrAndersonX added a fix for this. Actually the fix was there since some months, but i think it was not applied due to some crashreasons. The crashes should be fixed with my commit now.

Core/Spell: Dancing Rune Weapon should now mimic most of the attacks it should.

commit:
c6c379f235967c4a3ad90246202ab9918538c13d
5f170f105ed091c0b758d4a38d4687c82efcd363
9f0b99985b62cef511178c33aaac1e0ca3b0ae33

**Closed by Rushor** 2016-11-29 21:07 UTC
Labels: Class - Death Knight, Fixed - Waiting for PTR Update
