### ISSUE TITLE
[NPC] Maggoc

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1925] opened 2014-09-30 21:16 UTC
http://www.wowhead.com/npc=20600

Maggoc is an elite gronn, one of the sons of Gruul, that patrols southwestern Blade's Edge.

He should have and use 4 following abilities:
- Boulder: hurls a rock at his target or at random target in 5-30 yards if more than one threat is present. That rock does damage scaled to level and dazes for 6 sec.
  http://www.wowhead.com/spell=42139
- Mortal Wound: hits main target for 75% of his damage and applies stacking debuff that reduces healing by 5%. This ability is used roughly every 15 sec and stacks up to 4 times (so total 20% healing reduction max).
  http://www.wowhead.com/spell=38770
- Frenzy: used randomly throughout the fight, 15 sec duration, increases attack speed by 30% and damage by value scaled to level.
  http://www.wowhead.com/spell=40743
- Rock Rumble: deals damage and knocks player who has aggro back.
  http://www.wowhead.com/spell=38777

**Comment by Rushor** [comment] 2016-11-11 11:47
DB/Creature: Update Maggoc SAI 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1925
* commit: 242f6e32a1e611cf1fda2a231a1f0ee7d0e7d396

"Maggoc - In Combat - Cast 'Mortal Wound'"),
"Maggoc - In Combat - Cast 'Rock Rumble'"),
"Maggoc - Within 5-30 Range - Cast 'Boulder'"),
"Maggoc - Between 0-30% Health - Say Line 0 (No Repeat)"),
"Maggoc - Between 0-30% Health - Cast 'Frenzy' (No Repeat)"),
"Maggoc - On Just Died - Cast 'Maggoc: Summon Maggoc's Treasure Chest'");

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 11:47 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 08:01
Works as intended on ptr.
