### ISSUE TITLE
Lost Thunderbrew Recipe

### ISSUE THREAD

**Issue by Spruitje** [dalaranwow/dalaran-wow#1613] opened 2014-05-18 03:46 UTC
The quest [Lost Thunderbrew Recipe] (http://www.wowhead.com/quest=4134/lost-thunderbrew-recipe)

After destroying the kegs (there are 3) nothing happens

**Comment by n-ghost** [comment] 2015-02-10 14:18
https://github.com/dalaranwow/dalaran-wow/issues/917

**Comment by Golganeth** [comment] 2015-02-12 13:35
Duplicate of #917 indeed, closing up. Thanks @n-ghost

**Closed by Golganeth** 2015-02-12 13:35 UTC
