### ISSUE TITLE
[Quest][Northrend] Weapons of Destruction (Sholazar Basin)

### ISSUE THREAD

**Issue by randymarsh69** [dalaranwow/dalaran-wow#1430] opened 2014-04-01 23:33 UTC
The bombs don't despawn properly, and respawn very quickly. Players can destroy the same bomb 4 times in a row and get full credit for the quest.

**Comment by Rushor** [comment] 2016-11-26 14:07
also the explosion is missing

**Comment by Rushor** [comment] 2016-11-26 14:17
DB/Quest: Weapons of Destruction - Add explosioncast and despawn for Unstable Explosion

* closes https://github.com/dalaranwow/dalaran-wow/issues/1430
* the explosion is visible now and the Unstable Explosion will despawn for 5 minutes
* commit: 16e827a1e8a3276cec7c85f8659ab8e53fdb28f2

![GitHub Logo](http://i.imgur.com/cBnJAZq.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 14:17 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-11-01 10:27
After few tests on PTR:

> DB/Quest: Weapons of Destruction - Add explosioncast and despawn for Unstable Explosion

Works as intended, however if player spam rightclick on bomb he still can get all 4 credits from 1 bomb.
