### ISSUE TITLE
[Quest][Northrend] Examples to be made

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#398] opened 2013-08-05 19:04 UTC
Quest works, the issue is that the Hyldnir Overseer should only attack Garhal once the players attacks first, this is not happening, they are attacking him when ever he re-spawns, which is annoying players since they need to be fast when he re-spawns to get credit.

http://www.wowhead.com/quest=12907/examples-to-be-made
http://www.youtube.com/watch?v=vBIto09R7dI

**Comment by Watterx** [comment] 2015-02-16 17:04
Still bug.

**Comment by ises** [comment] 2015-06-03 14:42
Confirmed still happening

**Comment by BloodyIron** [comment] 2016-10-15 17:50
Yeah, just happened for me too. Where they attack automatically.

**Comment by Rushor** [comment] 2016-11-24 11:53
DB/Quest: Examples to be made - Hyldnir Overseer will only attack Garhal if Garhal gets in combat by a player/pet first

* closes https://github.com/dalaranwow/dalaran-wow/issues/398
* they will no longer start attacking automatically
* also you need to do at least 1 damage on Garhal to get the full questcredit on death
* commit: 12f0521efda810185cd27947887ebea2c573c7df

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by BloodyIron** [comment] 2016-11-24 20:19
Fabulous!

**Comment by Rushor** [comment] 2016-11-24 21:11
you are welcome :)

**Comment by TeridanDW** [comment] 2017-10-29 08:52
Works as intended on PTR.
@Lothloryen, could you add this:
``` sql
DELETE FROM `creature_addon` WHERE `guid` IN (118803, 118804);
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(118803,0,0,0,1,0,''),
(118804,0,0,0,1,0,'');
```
to this commit as the creatures behind Garhal  are not suppose to do the mining emote.
Proof:
https://www.youtube.com/watch?v=PwWHtyeRjiU
Thank you.

**Comment by Lothloryen** [comment] 2017-10-30 18:22
@TeridanDW Added - it looks good, thank you.

**Comment by antonius123** [comment] 2017-11-12 04:40
Is it supposed to be fixed? The Overseer npcs still attack Garhal right as he spawns. I did the quest today and had to wait right by it to tag Garhal before he dies.

**Comment by Lothloryen** [comment] 2017-11-12 16:06
@antonius123 Yes, this was already deployed. @TeridanDW Could you check if there is still any condition where the original issue can be reproduced, please?

**Comment by TeridanDW** [comment] 2017-11-12 19:25
Works perfectly fine on PTR.

**Comment by Lothloryen** [comment] 2017-11-12 19:41
Thank you, I will re-apply it to Algalon just to be sure.

**Closed by Lothloryen** 2017-11-12 19:41 UTC
Labels: Area - Northrend, Fixed - On Live Server, General - Quests, Listed - Changelog, Not working/incomplete fix
