### ISSUE TITLE
Buffs removed on spell hit instead of spell cast succeeded

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#2186] opened 2015-01-21 12:18 UTC
I've noticed that all of the buffs that should be removed as soon as you cast the spell are actually getting removed when the spell hits the target which, if you're a caster and standing quite far away from your target, means after a couple of seconds.

• Druid 
    - Talent: Omen of Clarity (16864) > Buff: Clearcasting (16870)

• Hunter
- Talent: Lock and Load (56342, 56343, 56344) > Buff: Lock and Load (56453)

• Mage
- Talent: Presence of Mind (12043) > Buff: Presence of Mind ()
- Talent: Arcane Concentration (11213,  12574, 12575, 12576, 12577) > Buff: Clearcasting (12536)
- Talent: Arcane Potency (31571, 31572) > Buff: Arcane Potency (57529, 57531)
- Talent: Hot Streak (44445, 44446, 44448) > Buff: Hot Streak (47108)
- Talent: Fingers of Frost (44543, 44545) > Buff: Fingers of Frost (74396)
- Talent: Brain Freeze (44546, 44548, 44549) > Buff: Fireball! (57761)
- Talent: Missile Barrage (54490, rank 5) > Buff: Missile Barrage (44401)

• Shaman
- Talent: Elemental Focus (16164) > Buff: Clearcasting (16246)
- Talent: Maelstrom Weapon (51528, 51529, 51530, 51531, 51532) > Buff: Maelstrom Weapon (53817)
- Talent: Nature's Swiftness (16188) > Buff: Nature's Swiftness (16188)

• Warlock
- Talent: Nightfall (18094, 18095) > Buff: Shadow Trance (17941)
- Talent: Molten Core (47245, 47246, 47247) > Buff: Molten Core (71165)
- Talent: Backdraft (47258, 47259, 47260) > Buff: Backdraft (54277)
- Talent: Empowered Imp (47220, 47221, 47223) > Buff: Empowered Imp (47283)

**Comment by Esunnaxqt** [comment] 2015-01-21 22:54
Druid Predator and Nature Swiftness also have this bug. Im trying to figure out if its only a visual bug or you actualy keep the buff and can for example get two pyroblasts from Hot Streak.

**Comment by Sedare** [comment] 2015-02-23 13:44
I will say that for Mage clearcast, its broken because you must have enough mana to start casting the spell in order for you to use clearcast. If you dont have enough mana to cast it, Clearcast is unusuable.

**Comment by Vaxsysl** [comment] 2015-07-05 10:30
Add mages' Missile Barrage talent buff as well. Not at home, can't post IDs, sorry.

**Comment by M0dinstaller** [comment] 2016-02-07 02:48
Can confirm, I have this on my elem shaman.

Also, if you get the buff while casting a spell, the spell you're casting will not eat a stack of the buff (for example, your previous bolt just landed and critted while you were casting your next one).

**Comment by Akkalevil** [comment] 2016-04-07 11:30
Notice : finger of frost is a wrong example. It should actually only lose a charge on spell HIT and NOT on spell CAST - that's the whole concept of the "shatter combo", trying to include a last instant-cast of ice lance/brain freezed frostfire bolt, before your frostbolt reach the target.

Hot Streak should definitely consume a charge on cast, though.

**Comment by Rushor** [comment] 2016-12-05 13:16
merge: 

https://github.com/TrinityCore/TrinityCore/commit/dec369c740876deb123f715cf4fc3a838228f9d0
https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686

**Comment by Crytexx** [comment] 2017-04-14 16:46
Can confirm the elemental focus and actually the bug means it is better than improved storm strike for enhancements too atm.
Regarding the MW stacks - indeed the buff gets consumed after the bolt lands but it is rather bad bug for us. Tho the buff does not get consumed, in my expirence you cant get another cast off of the same MW buff (trust me, haste is not the isue), which actually increases the time to get another 5stack buff.
The issue @M0dinstaller expirenced could be just lucky streak - since Storm strike can proc it and and also proc WF, which are another 2 attacks being able to proc MW + AA speed under 1 means you can get 5 chances to proc MW in the same second. It seems like you just bug-refreshed the buff, but this is not the case.

**Comment by Zarjofgt** [comment] 2017-10-19 22:26
Tested omen of clarity by casting moonfire directly after a wrath while I had the clarity buff.
I payed the mana for moonfire but not wrath.
OoC works as intended.

**Comment by TeridanDW** [comment] 2017-10-20 08:09
Hell and thank you for the comment @Zarjofgt.
I've tested around ~50% of these spells/procs on PTR and I wsn't able to reproduce the issue anymore, meaning not only OoC works as intended but all of them. This issue must of been fixed on live in the past.
Closing.

**Comment by shibuyaku** [comment] 2017-10-20 14:43
Still running into this with Mage Talent: Hot Streak (44445, 44446, 44448) > Buff: Hot Streak (47108) in Combination with 2pT10 set bonus (Buff: Pushing the Limit 70753).

To be specific:
- "Hot Streak" Buff is consumed on impact of Pyroblast on Target (~2s delay on max range). Expected behaviour: Consumed on cast of instant pyro.
- If you get another "Hot Streak" Buff between casting the instant Pyroblast and the Spell Impact you do not get the Buff: Pushing the Limit 70753 at all. Looks like this is scripted to check for the absence of a Hot Streak Buff on the players - this condition would be wrong / not Blizzlike and kills, at higher crit rates, about 40-50% of the procs).

**Comment by Synathy** [comment] 2017-10-20 15:00
Proof of shibuyaku by me on the 20th October 2017 at 15:57 server time: https://imgur.com/Pc5rQQJ
You can see Pyroblast being on his way to the dummy and I still have Hot Streak being active.

**Comment by TeridanDW** [comment] 2017-10-20 15:27
Thank you for the comments @shibuyaku and @Synathy.
Regarding:

> "Hot Streak" Buff is consumed on impact of Pyroblast on Target (~2s delay on max range). Expected behaviour: Consumed on cast of instant pyro.

I've noticed this also but I didn't mention it because even though the "Hot Streak" buff is removed from player on target hit the result was correct, meaning even at maximum range the mage is not able to cast 2 pyroblasts (2-nd on has cast time) even though the buff was still present on the player.

Regarding:

> If you get another "Hot Streak" Buff between casting the instant Pyroblast and the Spell Impact you do not get the Buff: Pushing the Limit 70753 at all.

I did not notice this issue, meaning I've to recheck it and if it is true, fixing the first issue should solve this problem automaticly.

**Comment by TeridanDW** [comment] 2017-10-20 15:43
Alright, I was able to reproduce the 2-nd issue on PTR.
So reopening the report with this as main focus:

> "Hot Streak" Buff is consumed on impact of Pyroblast on Target (~2s delay on max range). Expected behaviour: Consumed on cast of instant pyro.

So reopening the report with this as main focus:
"Hot Streak" Buff is consumed on impact of Pyroblast on Target (~2s delay on max range). Expected behaviour: Consumed on cast of instant pyro.

**Comment by shibuyaku** [comment] 2017-10-20 17:14
Thanks for looking into it again. Just adding something I kinda implied without writing it out: Consumation of hot streak on cast/on hit always makes quite the difference for mages with 2pt10, even if the 2nd issue I described would not be happening. Reason: You'd get the haste buff during GCD after casting that instant Pyro and start casting your next spell (fireball most likely) with +12% haste. Whats happening now is that the buff gets applied mid cast, and 1-2 seconds of it are wasted. Quite a lot for a 5 second buff :)

**Closed** 2017-11-01 10:52 UTC
Labels: Fixed - Waiting for PTR update, General - Mechanics, Priority - High

**Comment by datbunneh** [comment] 2017-11-07 10:48
@TeridanDW Did you test Missile Barrage cause it was not in the report originally so it can be easily missed?

**Comment by TeridanDW** [comment] 2017-11-07 11:16
> Talent: Missile Barrage (54490, rank 5) > Buff: Missile Barrage (44401)

Missile Barrage works abit diffrently because acrane missiles is a channeling spell. Missile Barrage is been removed when acrane missiles finishes the channeling duration or when it's been interupted during the channeling.

**Comment by datbunneh** [comment] 2017-11-07 12:10
@TeridanDW That why I made this report #4955 which contains proof.
