### ISSUE TITLE
[NPC] Time-Lost Proto Drake and Vyragosa - Missing Path an script and spawns

### ISSUE THREAD

**Issue by sashouktc** [dalaranwow/dalaran-wow#3142] opened 2016-02-11 15:22 UTC
Alright, my last topic on this matter did not draw any attention from the staff, so I am doing this as formal as possible. I will include all the relevant data to camping TLPD in hopes of getting a developer to look over the scripts and give me a confirmation as to whether his spawn is blizzlike or not. 

When I decided to camp this drake I got educated. I went through guides such as:
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/252061-ultimate-guide-farming-time-lost-proto-drake.html

And spoke to campers to verify those guides. We're talking about people with more than 5 TLPD sightings in retail. And those guides check out. They pretty much contain all there is to know about Vyragosa/TLPD farming. I am mentioning those together because they are closely tied. 

A quick summary of how things should be going versus how things are:
- **How things should be**: Vyragosa and TLPD share a spawn timer and spawn spots. There are 4 spawn points in Storm Peaks and there has not been a pattern found as to where each NPC would spawn. The timer for each spawn varies between 6 hours and 24 hours. Statistics on camping have shown that TLPD is a rare spawn of Vyragosa, averaging 1 out of 6 spawns (things vary accordingly, there may well be 2-3 TLPD spawns in a row).  
  Last thing which is of importance - Rare mobs in Northrend and Outland do get reset on a server reset. But Vyragosa and TLPD do not. They have a specific timer that runs without interference no matter what happens to the server.
- **How things are** (based on observation and sharing data with other campers) : No idea if Vyragosa and TLPD share a spawn timer and spawn points as there has not been a single TLPD spawn yet. The timer for both (I am assuming this works correctly and the timer is shared) is fixed on 8 hours after the corpse of Vyragosa disappears. I had detailed logs on this but they got lost. It's a matter of finding 1 Vyragosa and waiting out 8 hours for each consecutive spawn. Spawn point is always the same - Brunnhildar Village, above the Pit with the bears. 
  From what I have noticed server resets do not affect the timer of Vyragosa, which is correct. 

My experience with other campers include a Night Elf Druid who would log 2-3 minutes before a spawn on top of Brunnhildar Village and hope for TLPD. As I am horde I could not interact with him but you can easily see how he had come to the same conclusions I have, otherwise he would not be logging in such convenient times. And a Tauren druid who would confirm what I have found. The difference between me and him being that he had camped TLPD for 3 months, gotten all Vyragosa kills in that time and not seen TLPD once. I only had around 2 weeks of camping. 

That includes camping on all 4 spawn points by random people and flying the travel routes. The only thing to have spawn in Storm Peaks is Vyragosa in Brunnhildar Village. And lastly, while there are a lot of people (a lot is subjective) with TLPD, all of those have gotten it before/during the mentioned bug where it would constantly spawn on the same spot. I read the issue and the problem was "taken care of". No one has gotten a drake since. Which leads me to believe the drake's spawn is simply disabled. 

Any responses are appreciated

**Comment by Mazz312** [comment] 2016-06-23 05:25
Bump since this is a pretty serious problem for anyone interested in TLPD

**Comment by hacklefellar** [comment] 2016-07-06 14:19
I can confirm this, it is not working. please fix it!

**Comment by Sophilyplum** [comment] 2016-12-06 14:45
Can I please ask for any comments from the developers on this?

**Comment by Rushor** [comment] 2016-12-06 18:03
a fix for this is on PTR. A tester needs to verify how good the fix is working.

DB/NPC/Storm Peaks: Time-Lost Proto Drake.

NPC behaviour changed to CPP in order to be able to alternate between Vyragosa and Time-Lost Proto Drake accordingly.
Every time will be spawned at a random waypoint and with a chance of being the Time-Lost Proto Drake instead of Vyragosa.
Based on Sunwell.

Updates https://github.com/dalaranwow/dalaran-wow/issues/3142

* commit: 1d310196136d0222a6383c1e9b08c1c9b54513c3

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by alexuktc** [comment] 2016-12-17 10:20
Hey guys. 

I wrote this ticket in February. Since TLPD actually does spawn on Kirin Tor I have had 5 successful kills on that server. However he was always on the ground and was moving extremely slow or was not moving. I just want to make sure he is flying with the new update. It is the sole reason people buy Snowfall Lager. 

Thanks.

**Comment by Rushor** [comment] 2016-12-17 12:07
yes flying includes that fix, it just needs to be tested after the icc betas.

**Comment by Lothloryen** [comment] 2017-10-23 18:09
Hello there, this was already deployed long time ago, it seems it is not working properly, could you take a look @Rushor , please? Thanks.

**Comment by lkrocek** [comment] 2017-12-18 16:08
I am tracking TLPD and vyragosa for 3 weeks really frequently and really didn't found them yet, I guess they're not spawning on algalon.

**Closed** 2018-04-12 09:53 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR update

**Comment by Lothloryen** [comment] 2018-04-13 14:37
Hello there,

It's on live server now.

Thank you.
