### ISSUE TITLE
[NPC] Spitelash Siren

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2665] opened 2015-07-15 00:38 UTC
NPCs "Spitelash Siren" (ID: 6195) are bugged - caster mob not casting spells.

**Comment by Rushor** [comment] 2016-11-15 20:07
http://wotlk.openwow.com/spell=11831 and http://wotlk.openwow.com/spell=12551 must be added

**Comment by Rushor** [comment] 2016-11-15 20:23
Scripts/Kalimdor: Add ability for Spitelash Siren

* closes https://github.com/dalaranwow/dalaran-wow/issues/2665
* they will cast http://wotlk.openwow.com/spell=11831 on aggro now

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 20:23 UTC
Labels: Continent - Classic
