### ISSUE TITLE
[Mechanic] Minimap Pings with Rotate Minimap

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1633] opened 2014-05-26 14:05 UTC
If you have enabled the "Rotate Minimap" option under Interface>Display>Rotate Minimap, minimap pings (when a party member clicks on the minimap to indicate a location or direction) will not rotate with the map when you turn.

The ping indicator should rotate along with the minimap if the "Rotate Minimap" option is selected.

**Comment by Rushor** [comment] 2016-12-05 19:23
What steps will reproduce the problem? 1. move with some higher speed 2. ping somewhere on minimap while moving

What is the expected output? What do you see instead? The Minimap Ping should always be on the pinged position on the map, but it is moving It means, the ping itself moves above the map, and not as expected marks the coords you pinged on

What revision of the Core are you using? On what operating system? Ubuntu Linux, Broken since some 3.3.2 revisions, was working before on 3.1.3

Please provide any additional information below. none
Comment #1
Posted on Apr 14, 2010 by Swift Kangaroo

i get this too in the ofi
Comment #2
Posted on Apr 16, 2010 by Quick Wombat

So, it looks to be client issue.


https://code.google.com/archive/p/trinitycore/issues/1682

Clientside issue, so won't fix.

**Closed by Rushor** 2016-12-05 19:23 UTC
