### ISSUE TITLE
[Encounter][NPC] Warchief Rend Blackhand (UBRS)

### ISSUE THREAD

**Issue by wilczakadam** [dalaranwow/dalaran-wow#3307] opened 2016-05-19 17:09 UTC
Once the Gyth spawns in the arena and you kill him, there is a high chance (3 out of 4 attempts in my case) that Rend Blackhand will not spawn, and the whole event gets stuck. The doors are closed and you cannot proceed in the instance.

**Comment by Golganeth** [comment] 2016-05-19 17:43
Duplicate of #90. Workarounds can be found there as well.

Closed.

**Closed by Golganeth** 2016-05-19 17:43 UTC
