### ISSUE TITLE
#Outlands #Quests #NPC

### ISSUE THREAD

**Issue by warcraftgeekygamer** [dalaranwow/dalaran-wow#2578] opened 2015-06-29 23:20 UTC
http://s29.postimg.org/59nb1kohz/Wo_WScrn_Shot_062915_191218.jpg - Flightmaster Krill Bitterhue
http://wotlk.openwow.com/npc=16822#.

http://s29.postimg.org/wiyog2pl3/Wo_WScrn_Shot_062915_191308.jpg - Honor Guard Wesilow
http://wotlk.openwow.com/npc=16827

http://s29.postimg.org/93graq5tz/Wo_WScrn_Shot_062915_191341.jpg - Dumphry
http://wotlk.openwow.com/npc=21209

Dear Dalaran WoW Developers:

Please take a good look at these three screenshots...and you will see not one, but THREE NPC's in Outland (Honor Hold) that are standing in the incorrect position. This effectively prevents Alliance who do not have a flying mount from reaching these NPC's and obtaining their quests. Please correct this.

**Comment by Watterx** [comment] 2015-06-30 07:30
Thats real strange. When I leveled there some time ago they were not there. Easy fix tho.

**Comment by Rushor** [comment] 2016-11-12 12:05
![GitHub Logo](http://i.imgur.com/x10h6TH.jpg)
![GitHub Logo](http://i.imgur.com/OpdmOTB.jpg)
![GitHub Logo](http://i.imgur.com/E4vgFFg.jpg)

Cannot confirm this anymore, but the position of Dumphry is indead wrong. He should stand outside of the tower (http://www.wowwiki.com/Dumphry -> Screenshot)

DB/Creature: Update position of Dumphry

* closes https://github.com/dalaranwow/dalaran-wow/issues/2578
* commit: 484b55ac383048cd395a79c19311a75099a67209

Fix:
![GitHub Logo](http://i.imgur.com/M72yzkA.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 12:05 UTC
Labels: Continent - Outland, OLD - Miscelaneous, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 10:16
Works as intended on ptr.
