### ISSUE TITLE
Game kick me out accepting partys

### ISSUE THREAD

**Issue by Finlaypro** [dalaranwow/dalaran-wow#5876] opened 2020-04-12 14:27 UTC
Sometimes i am trying to going instances or raid group but when someone invite me and i accept game bug to me, kick me out and can't enter again until i am out the party. I wrote to GM but no answer. What I have to do?
Sry for my english. I am spanish.

**Comment by Golganeth** [comment] 2020-04-12 22:19
Sometimes addons or corrupt UI elements can cause this. Are you having the issue with just one character or with all of them?

Disable all of your addons check if it still happens. If that was indeed the problem I'd suggest you to turn them on one by one, so you can easily detect which addon was giving you trouble.

If the issue persists:
- Clear your Cache folder (this might fix small minor issues and it's pretty quick to do). Try also clearing your WTF folder, you will lose your settings but it can potentially fix the problem as a last option.
- At this point if nothing has worked, it's most likely that your client has corrupted files so you should re-install the game from scratch. You can get our game client [here](https://www.dalaran-wow.com/game-client/).

Closing up since the issue is on your side.

**Closed by Golganeth** 2020-04-12 22:19 UTC
