### ISSUE TITLE
Achievement: Gonna Go When the Volcano Blows (10 & 25)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#489] opened 2013-08-09 19:59 UTC
**Achievement:**
_Gonna Go When the Volcano Blows (10 player) - 2047_
_Gonna Go When the Volcano Blows (25 player) - 2048_
- **Issue:** The players are not granted the achievement if the criteria has been met. If you don't get hit by volcano and if you are not affected by a debuff called: **Flame Tsunami** _(ID:57491)_ you still won't get achievement, despite you should.
- **How it should work:** If your raid manages to kill Sartharion without anyone getting hit by  **Lava Strike** you should get the achievement.

**Possible fix for this** - Criteria should be, if non of the players during the encounter had a debuff called **Flame Tsunami** _(ID:57491)_, everyone should be granted achievement upon kill.

![image](https://f.cloud.github.com/assets/5054924/940527/df43ccc0-012d-11e3-9775-2a4357a8b861.png)
![image](https://f.cloud.github.com/assets/5054924/940536/11c18020-012e-11e3-801f-d4b8ef4197ae.png)

**How it should work**: http://www.youtube.com/watch?v=HRwwL8vTwCg

Achievement criteria has to be scripted, since it's unique and hard to develop. This is should be within the core & database.

---

http://wotlk.openwow.com/search=Flame+Tsunami#npcs
http://www.wowhead.com/achievement=2047/gonna-go-when-the-volcano-blows-10-player
http://www.wowhead.com/achievement=2048/gonna-go-when-the-volcano-blows-25-player
http://www.wowwiki.com/Gonna_Go_When_the_Volcano_Blows_(10_player)

**Comment by Tarpor** [comment] 2015-10-10 21:49
Is there any incentive do make this achievement auto-completing the same as #1582?

**Comment by Crispybuilt** [comment] 2016-05-22 12:51
Would be awesome if this achievement could get fixed "soonish"

Glory of the Raider 10/25 would be obtainable then.

**Comment by Crispybuilt** [comment] 2016-06-02 09:56
Can we expect a fix for this "soonish"? Just wondering

**Comment by Rushor** [comment] 2016-06-02 10:04
refernce: https://github.com/Kittnz/Sunwell/search?utf8=%E2%9C%93&q=Gonna+Go+When+the+Volcano+Blows

**Comment by Rushor** [comment] 2017-03-23 21:40
Scripts/ObsidianSanctum: Implement Achievement: Gonna Go When the Volcano Blows (10 & 25) 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/489
* commit: b36ac84150f7b2600c695b1a20fc3819ed3010a8

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-23 21:40 UTC
Labels: Area - Instances, Fixed - Waiting for PTR Update, General - Achievements

**Comment by Lothloryen** [comment] 2017-10-18 19:47
Implemented this achievement, it must be checked by player instead of raid wise.

**Comment by TeridanDW** [comment] 2017-10-19 08:29
Work as intended on PTR.
