### ISSUE TITLE
[Quest][Outland] Prisoner of Bladespire 

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#782] opened 2013-09-17 14:48 UTC
http://www.wowhead.com/quest=10724
Quest is doable, thoo ome small event is missing from the quest,
upon using the q item a Spirit (owl) is spawned witch should release the bat Leokk
from the cage, but upon using the q item the npc spawns and the player gets the q credit

**Comment by Penguindrum** [comment] 2015-09-18 10:45
After 100 ogre kills, ~85% being enofrcers, still couldn't get the key to drop. I know the droprate is low but I  wonder if they even drop it.

**Comment by Rushor** [comment] 2016-11-28 21:07
DB/Quest: Prisoner of the Bladespire - Add endevent and increase droppchance for "Spirit's Whistle" to 20 percent

* closes https://github.com/dalaranwow/dalaran-wow/issues/782
* commit: eac544a93d72b757af17ec11d91c4552d12b8348

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 21:07 UTC
Labels: Continent - Outland, On PTR, Quests
