### ISSUE TITLE
Pathfinding after the recent patch

### ISSUE THREAD

**Issue by Nexnav** [dalaranwow/dalaran-wow#2419] opened 2015-05-23 22:46 UTC
So basically before the last update to the server, pathfinding was working very well, for example, mobs would go around fences to get to you. However, after the update and redoing the pathfinding system, the mobs I mentioned previously actually go up the fence instead of around. Don't think it's supposed to be like that.

**Comment by n-ghost** [comment] 2015-05-23 23:10
Confirmed.

Also, some NPCs caught a habit of flying around a bit.

Like that.

![wowscrnshot_052415_020856](https://cloud.githubusercontent.com/assets/8515510/7786032/ecc4bab0-01b9-11e5-9e56-3b692a7f32bf.jpg)
![wowscrnshot_052415_020902](https://cloud.githubusercontent.com/assets/8515510/7786033/f2738374-01b9-11e5-896b-b5f6a0669a5e.jpg)

Or falling through the surfaces if there is anything below while on escorts.

Like this.

![wowscrnshot_052015_211105](https://cloud.githubusercontent.com/assets/8515510/7786006/f45ad3dc-01b8-11e5-9484-4bb097fa46b4.jpg)

**Comment by Augur89** [comment] 2015-05-27 12:59
That escort had the same issue before the update, I did it with three different characters and the NPC always fell. But the quest is doable as you get credit.

I don't know about the other issues though.

**Comment by Demlock** [comment] 2015-06-09 21:52
Yup, standard pathfinding issue. Still needs a lot of work.

**Comment by Rushor** [comment] 2016-11-17 20:39
already on ptr:

Solve many of the creature falling through floor issues.

This seems entirely wrong to discount the returned map height if we're
already below it. In many cases this is exactly why we want the height!

commit: bebb8db8808beafeab3d3f64cbc4eca5d4ca2ef1

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 20:39 UTC
Labels: Mechanics, On PTR
