### ISSUE TITLE
[NPC] Crimson Courier 

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2892] opened 2015-09-17 21:06 UTC
The Crimson Courier (#12337) who is accompanied by 4 Crimson Bodyguards (#13118) in the Eastern Plaguelands can be pulled off and picked separately from the rest of the force.

Properly executed, anytime any one member of the Crimson Bodyguard or the Courier is pulled, the rest of the members should follow. They should all be strung together as one pull. This was designed this way on purpose.

**Comment by Rushor** [comment] 2016-11-12 20:19
DB/Creature: Crimson Courier - Add formation

* closes https://github.com/dalaranwow/dalaran-wow/issues/2892
* commit: d1690173341833e715ca36f4859f6f986ce8e5a7

![GitHub Logo](http://i.imgur.com/ZAtytLF.jpg)
![GitHub Logo](http://i.imgur.com/Ztx5akD.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 20:19 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 19:40
Works as intended on ptr.
