### ISSUE TITLE
Doubled mobs on ships

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5570] opened 2018-08-06 05:34 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
On a ships for kalimdor or eastern kingdom the NPCs on ships are spawned twice. Eg. ship from Stormwind to Darkshore. I didn't checked all the ships but think it happens on all, except the northrend ships.

**Expected behaviour**: Tell us what should happen instead
each mob should be there one time only as it working on ships into Northrend.

**Include proofs for this behaviour**
they are speaking so you can see all messages twice, also you can click on one mob and can see he is there twice(multiple times click with mouse to select or use tabulator button on keyboard)

Realm: Algalon
Alliance (not sure if horde has same issue)

**Comment by boujii** [comment] 2018-08-09 17:16
I would write this off as a one time event bug, as the guid are unique. Most likely either a client bug or a rare server hiccup.

**Comment by Golganeth** [comment] 2018-08-19 15:51
An NPC could always be duplicated regardless of GUIDs being unique. However I couldn't reproduce the problem so it was most likely an issolated issue or perhaps a character/client problem.
Closing

**Closed by Golganeth** 2018-08-19 15:51 UTC

**Comment by BobBlawblaw** [comment] 2019-01-16 14:17
Still occuring. They Lady Mehlay between Theramore and Menathil has a number of double spawned NPCs.
