### ISSUE TITLE
[NPC] Mosh'Ogg Witch Doctor unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1226] opened 2014-02-18 16:23 UTC
Mosh'Ogg Witch Doctor (http://wotlk.openwow.com/npc=1144) is casting none of his abilities.

**Comment by Rushor** [comment] 2016-11-13 21:06
DB/Creature: Add abilities for Mosh'Ogg Witch Doctor

* closes https://github.com/dalaranwow/dalaran-wow/issues/1226
* commit: b569858a19567fabcadc4a78f7d56de54c4ca9ba

,0,0,0,0,0,"Mosh'Ogg Witch Doctor - In Combat - Cast 'Curse of Weakness'"),
0,"Mosh'Ogg Witch Doctor - In Combat - Cast 'Ward of Laze' (No Repeat)");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 19:09
Works as intended on ptr, however spell http://wotlk.openwow.com/spell=3827 summons a totem who doesn't cast anything and when attack it will autoattack back at invoker (which is not the correct behaviour for totems).
![image](https://cloud.githubusercontent.com/assets/6797611/24626536/3e3ff97c-18ba-11e7-9b10-e1ae8ba59b11.png)

**Closed** 2018-03-23 22:03 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update
