### ISSUE TITLE
Valanyr Fragment Drop Rate

### ISSUE THREAD

**Issue by Drawsblood** [dalaranwow/dalaran-wow#3037] opened 2015-12-10 18:00 UTC
The drop chance of Fragments is still insanely bugged. Lothloryen mentioned a fix in the article #2247 however no fix has ever been deployed, and it seems they don't care to fix it. We run Ulduar 25 twice a week for 2 different members and at this point we are lucky if we even get 1 Fragment. In the article mentioned you say that the drop rate is correct, this is an absurd statement. The first comment of this wowhead article explains the drop rate: "http://www.wowhead.com/item=45038/fragment-of-valanyr#comments". I have run this for months now and have yet to see a fragment of Yogg or Vezax. The article also mentions that up to 2 fragments should be dropping from Hodir hardmode, 1 from each cache. I understand that Lothloryen is busy with all of the current issues, however a legendary item should be one of the top prios, even if it is from Ulduar. Stop closing posts where no fix has been made, kthx.

Draws

**Comment by Golganeth** [comment] 2015-12-10 19:06
Duplicate of #2247

**Closed by Golganeth** 2015-12-10 19:06 UTC
