### ISSUE TITLE
[Object][Sethekk Halls] The Talon King's Coffer

### ISSUE THREAD

**Issue by DalaranLantri** [dalaranwow/dalaran-wow#3449] opened 2016-06-13 15:21 UTC
**Description**:
The Talon King's Coffer contains the key to the Shadow Labyrinth.
**Current behaviour**: 
Once one member of the raid loots the coffer after killing Talon King Ikiss, it despawns.
**Expected behaviour**:
Every member of the group should be able to loot the Shadow Labyrinth Key.
**Steps to reproduce the problem**:
1.  Kill Talon King Ikiss
2. Have one member loot the Shadow Labyrinth Key
3. Chest disappears.

**Include proofs for this behaviour**
http://www.wowhead.com/item=27991/shadow-labyrinth-key#comments:id=27692:reply=1524

**ID's**
27991-Shadow Labyrinth Key
187372-The Talon King's Coffer
18473-Talon King Ikiss
3791-Sethekk Halls

**Comment by Rushor** [comment] 2016-11-12 14:15
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 14:15 UTC
Labels: Instances, On PTR, Priority - Low
