### ISSUE TITLE
[Quest][Outland] Distraction at the Dead Scar (TBC)

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#719] opened 2013-08-31 11:01 UTC
Distraction at the Dead Scar / The Air Strikes Must Continue are two quests which ask of you to take a flight over the dead scar and drop arcane charges on different mobs.
http://www.wowhead.com/quest=11532/distraction-at-the-dead-scar

1) http://www.wowhead.com/npc=25030 ; this NPC is for some reason killed on spawn by the others around it. Thus leaving you with impossible odds to kill 12 of them. I only managed to get 2 in 2 flights.

**Comment by ashido96** [comment] 2015-05-14 16:38
While the mobs are hostile, it's the same thing as npc's fighting each other for quests completion in other areas like grizzly hills. You will only get credit if the Wrath Enforcer is above 50% health when the bomb hits it to get credit.

**Comment by Braniacz** [comment] 2016-07-12 10:33
This is still a problem, I could kill Pit Overlord's and Eredar Sorcerer's on first run but the problem start's WITH Wrath Enforcer's. I just didnt get credit for kill. I also think the speed of flying mount is to fast with this render distance. This doesnt mean quest is not doable it just means that its very frustrating to do and u have to take the flight to death scar at least 5-6 times.

**Comment by Rushor** [comment] 2016-11-29 10:05
DB/Creature: Add faster respawn and CREATURE_FLAG_EXTRA_NO_CREATURE_DAMAGE for several creatures

* closes https://github.com/dalaranwow/dalaran-wow/issues/719
* the affected questcreatures will no longer kill each other (they attack, but they don't deal damage to each other). with that addition, the player always gets the questcredit
* the affected questcrestures will respawn faster (after around 80 sec)
* commit: 3800f19b47bfeeae0dd9934251c394deb9184929

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 10:05 UTC
Labels: Continent - Outland, General - Quests, On PTR
