### ISSUE TITLE
Wild Growth not healing druid while targeting enemy 

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#4829] opened 2017-07-26 19:54 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: While attacking enemy and casting Wild Growth after that, it will not heal the druid.

**Expected behaviour**: Wild Growth should heal the druid too full hp or not.

**Steps to reproduce the problem**:

1. attack enemy target with any damaging ability
2. cast wild growth **while targeting enemy** target 
3. observe buffs and you will notice that there isnt WG buff or healing coming from it

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=NvvdrSYGl60
Please observe buffs and Wild Growth cooldown.After casting starfire and casting WG after that (while targeting enemy WG should be casted on the druid as cast on self spell) notice that there isnt WG buff nor heal, while some other group members get healed by it and not all of them.Also i do have glyph of Wild Growth wich heals one aditional target (5+1).

https://wowgaming.altervista.org/aowow/?spell=53251

**Comment by strobe-light** [comment] 2017-07-27 07:22
From [Elitistjerks' Wotlk Resto Pve Compendium: ](https://web.archive.org/web/20100807214416/http://elitistjerks.com/f73/t88239-resto_pve_compendium_general_discussion/)

> Wild Growth is unusual in that in can be targeted on a hostile unit and will still apply to the lowest-HP raid members near that unit

Looking at your floating combat text when you cast the WG, it is being put onto both the two melee players in your party next to the boss that you are targeting, and you are out of the 15yd splash range from them, so you do not get WG on yourself. 
This seems blizzlike/working as intended if I'm not mistaken.

**Comment by Zarjofgt** [comment] 2017-10-19 18:40
Wild growth can apply to all friendly targets within 15 yards of the target. If you are within 15 yards of the target, it can apply to you.

Abillity works as intended.

**Comment by TeridanDW** [comment] 2017-10-25 18:51
Can someone else also confirms this:

> Wild growth can apply to all friendly targets within 15 yards of the target. If you are within 15 yards of the target, it can apply to you.
> 
> Abillity works as intended.

please?

**Comment by Johanes022** [comment] 2017-10-26 04:40
What i wanted to say is that when u cast some beneficial spell while targeting enemy unit , spell will be applied on yourself.Every hot druid has and every other beneficial spell ingame works that way except for wild growth.It indeed works just as strobe-light said.It is "applied" on enemy unit (except it doesnt heal it)  but it heals friendly units around it, just as if it was casted on friendly target.It was strange to me only because of that  where WG doesnt behave like all other spells.

**Comment by TeridanDW** [comment] 2017-12-14 17:25
If there aren't any objections, I'll close this one as working as intended.

**Closed by TeridanDW** 2017-12-14 17:25 UTC
