### ISSUE TITLE
[NPC] Merideth Carlson

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#1942] opened 2014-10-06 18:03 UTC
Merideth Carlson should hand out her Manna-Enriched Horse Feed to only people/paladins who finish the quest  [60] Manna-Enriched Horse Feed. However she does not have it in her shop.

This was added in patch 1.5.0 http://www.wowwiki.com/Merideth_Carlson

**Comment by Rushor** [comment] 2016-11-13 20:07
http://wotlk.openwow.com/item=18775

**Comment by Rushor** [comment] 2016-11-13 20:09
DB/Creature: Merideth Carlson - add item Manna-Enriched Horse Feed

* closes https://github.com/dalaranwow/dalaran-wow/issues/1942
* the item will only be shown in the shop if you already rewarded the quest Manna-Enriched Horse Feed (http://wotlk.openwow.com/quest=7645)
* commit: cb615c82ffe12a9c7b241ef3da588242982a1f76

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 07:19
Hm, can't even see the npc http://wotlk.openwow.com/npc=2357 at all, in TC DB she is missing also, if there is some event that spawns her, i can't find it.
Reopening the issue until this condition can be tested and she is spawned.

**Comment by Rushor** [comment] 2017-08-13 10:55
Hm she is there in my db:

please rerun this query and she should be there again:

```sql
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (15662, 2357, 0, 0, 0, 1, 1, 3689, 1, -783.566, -603.281, 15.2348, 2.32129, 300, 0, 0, 1163, 0, 0, 0, 0, 0, 0);
```

**Closed by Rushor** 2017-08-13 10:55 UTC
Labels: Area - Classic
