### ISSUE TITLE
Kira Songshine Pathway !

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2288] opened 2015-03-11 12:59 UTC
The npc's is not on the right track she is offroad pls fix the path for the npc's Kira Songshine.
Zone : Elweyyn Forest
Location : Goldshire
http://wotlk.openwow.com/npc=3937

**Comment by TheLichWarrior** [comment] 2015-03-16 14:42
TY

**Comment by TheLichWarrior** [comment] 2015-03-16 14:42
sometimes she fly

**Comment by Rushor** [comment] 2016-11-15 09:45
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/2609

**Closed by Rushor** 2016-11-15 09:45 UTC
Labels: Duplicate
