### ISSUE TITLE
Warrior's Shield Bash

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2296] opened 2015-03-14 00:17 UTC
Beggining effect interupt spell is working but the second effect interrupt school of magick for some 6 seconds isnt working pls fix the problem need thet ability against casters of magick & spell.

Only tried on Mob's havent traied on Players in PVP

**Comment by TheLichWarrior** [comment] 2015-03-14 09:09
hm on all Mob's happens this the correct second effect is to disable the caster school of magick for 6 seconds pls fix faster this. game is hard

**Comment by Golganeth** [comment] 2015-03-14 11:21
Please re-check the current issues before opening new ones. This is a duplicate of #182. Works fine on PvP.

**Closed by Golganeth** 2015-03-14 11:21 UTC
