### ISSUE TITLE
[Paladin] [Spell] Hand of Salvation

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#3966] opened 2016-12-13 05:23 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 

If you receive Hand of Salvation whilst under the effect of Fade or Mirror Image instead of reducing your threat you gain 900k+ 
Then when the Fade or Mirror Image buff expires you gain the threat for real and pull agro.
The tank can taunt from you and retain that huge amount of threat.

**Expected behaviour**:

Standard Hand of Salvation threat reduction.

**Steps to reproduce the problem**:

1. Have Player 1 build agro on an npc
2. Have Player 2 build some agro then Fade or Mirror Image
3. Cast Hand of Salvation on Player 2
4. When Salvation ticks Player 2 is granted 900k+ threat
5. Fade / Mirror Image expires Player 2 instantly pulls agro

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=m4n4wKXpg98&feature=youtu.be

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Hand of Salvation - http://wotlk.openwow.com/spell=1038
Fade - http://wotlk.openwow.com/spell=586
Mirror Image - http://wotlk.openwow.com/spell=55342

**Comment by Rushor** [comment] 2016-12-13 08:26
> Then when the Fade or Mirror Image buff expires you gain the threat for real and pull agro.

This is actually correct, the issue that must be fixed here is, that you should not gain the huge threat if you frist use Mirror Image and then gets the Hand of Salvation

**Comment by Rushor** [comment] 2016-12-13 08:27
Game/ThreatManager: Fix too high/low threat after threat was temporary modified and then modified by a percentage

* closes https://github.com/dalaranwow/dalaran-wow/issues/3966
* commit: 6bd215da0a3e137c4b5313f0bdb272d3dc4a4de3

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-13 08:27 UTC
Labels: Class - Mage, Class - Paladin, Fixed - Waiting for PTR Update

**Comment by Horvic** [comment] 2016-12-13 09:37
> This is actually correct, the issue that must be fixed here is, that you should not gain the huge threat if you frist use Mirror Image and then gets the Hand of Salvation

Yes, this is exactly what I meant.

**Comment by TeridanDW** [comment] 2017-10-23 10:10
Works as intended on PTR.
