### ISSUE TITLE
Quest: The Demoniac Scryer

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#224] opened 2013-07-28 19:12 UTC
Quest The Demoniac Scryer - 10838

Issue: Upon using the item within correct zone / location, it will drop down but it won't summon any kind of mobs at all to protect it. Your goal is to protect the crystal until it fully changes the color from the wave / pack of mobs which are constantly spawning.
You are also able to interact with the object which will tell you some things (you can see the text from the object on the video)

The object has to form 4 blue crystals which are linked to each other directly through the object

When the object is fully charged it will start to cast purple channeling spells into the air and then the gossip option will become available. Once the player clicks on it, the quest will be completed.

How the quest should work, video: 

http://www.youtube.com/watch?v=farj1YWo5ik
http://www.youtube.com/watch?v=6rwZOZJng3U#t=01m25s

http://www.wowhead.com/quest=10838/the-demoniac-scryer
http://wotlk.openwow.com/quest=10838

**Comment by Demlock** [comment] 2015-07-19 20:22
Confirmed. It is auto-complete for now

**Comment by MalkaviaD** [comment] 2016-05-31 17:59
This quest was already working as intended time ago. Closing this.

**Closed by MalkaviaD** 2016-05-31 17:59 UTC
Labels: Outlands, Quests
