### ISSUE TITLE
[NPC] Fel Corrupter

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1928] opened 2014-10-01 11:18 UTC
http://www.wowhead.com/npc=21300

These cultists should have and use 2 abilities with damage scaled to their level:
- Shadow Bolt: their main shadow damage attack.
  http://www.wowhead.com/spell=9613
- Corruption: 15 sec shadow damage dot.
  http://www.wowhead.com/spell=32063

Currently Fel Corrupters will just melee instead.

**Comment by Rushor** [comment] 2016-11-13 20:17
DB/Creature: Add abilities for Fel Corrupter

* closes https://github.com/dalaranwow/dalaran-wow/issues/1928
* commit: 1b6fd6106a18d7de1689fdd09dadf88e2c3561d3

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 20:17 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 07:46
Works as intended on ptr.
