### ISSUE TITLE
[NPC] Herbalism/mining level requirement

### ISSUE THREAD

**Issue by hiibs** [dalaranwow/dalaran-wow#2547] opened 2015-06-20 20:30 UTC
In retail you could get any gathering profession up to 150 on a level 1 character. It seems that on this server you have to be at least level 5 to train apprentice herbalism or mining and level 10 for journeyman skill.

http://us.battle.net/wow/en/game/patch-notes/3-0-3 (scroll down to professions)
- The level requirements required to train gathering skills have been removed.

https://www.youtube.com/watch?v=VvBsIDh1LiM (2009 video from live servers)

**Comment by warcraftgeekygamer** [comment] 2015-06-21 15:14
That's because we aren't playing on a MoP server. The changes you speak of were made in patch 5.3 of MoP.

http://us.battle.net/wow/en/blog/9679398#professions
http://www.wow-professions.com/news/patch-53-herbalism-and-mining-changes
http://wowwiki.wikia.com/Herbalism
http://wowwiki.wikia.com/Mining

* Herbalists of low skill can now pick herbs in Pandaria for a small amount of usable material. The yield an herbalist will be able to harvest from each node is determined by skill level.

* Miners of low skill can now mine mineral deposits in Pandaria for a small amount of usable material. The yield a miner will be able to harvest from each node is determined by skill level.

Prior to patch 5.3, you are required to have a certain skill level in order to gather ores & herbs.

This is working as intended.

**Comment by hiibs** [comment] 2015-06-21 17:06
I'm not talking about the profession skill level required to pick up herbs or mine the deposits. I mean the character level required to learn those professions.

http://us.battle.net/wow/en/game/patch-notes/3-0-3 (scroll down to professions)
* The level requirements required to train gathering skills have been removed.

https://www.youtube.com/watch?v=VvBsIDh1LiM (2009 video from live servers)

**Comment by Watterx** [comment] 2015-06-26 08:43
Its on purpose so people doesn't bot/hack to farm stuff with alter accounts.

**Comment by Rushor** [comment] 2016-12-02 11:44
DB/Creature: Reduce Trainer Skill level requirements

* closes https://github.com/dalaranwow/dalaran-wow/issues/2547
* commit: 62bdaedf6f2cbb3e2867cabdf0dc76217a9464dd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-02 11:44 UTC
Labels: Fixed - Waiting for PTR Update, General - Mechanics
