### ISSUE TITLE
WG quests

### ISSUE THREAD

**Issue by HeadOwns** [dalaranwow/dalaran-wow#876] opened 2013-10-04 12:09 UTC
well, recently, i've noticed something, Slay Them All quest only works out of WG battle, cuz when we r inside the battle, we r in raid group, also those quests about the elementals works out of WG battle, so i came with the conclusion that all the quests in WG r working such as "Toppling the Towers" and "Victory in Wintergrasp" and the other 2, but the only prob is that we cant do it while WG is up cuz we r in raid group, so i hope u can fix it soon.

**Comment by Klala** [comment] 2015-08-28 10:22
Slay them all and No Mercy for the Merciless should give you credit for killing players as well as NPCs regardless of being in a raid or not.

**Comment by frznfngrs** [comment] 2016-05-28 03:00
Getting no credit for this quest regardless of raid or solo, WG active or not.

**Comment by Braathan123** [comment] 2016-06-27 11:34
As of 27/06-16 The quests; Toppling the towers, Slay them all! and Defend the siege are still not functioning. You can do Slay them all! But only when WG isn't active.

**Comment by Hephaetorix** [comment] 2016-08-12 20:30
3 years later this still needs to be enabled within raids.

**Comment by Rushor** [comment] 2016-11-26 21:13
Game/Battlefield: WG - Add killcredits for quest: No Mercy for the Merciless, Slay Them All during WG wartime

* closes https://github.com/dalaranwow/dalaran-wow/issues/876
* commit: 9e3da9da1fb6ef72d20ccd0a24b27b70481756ad

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 21:13 UTC
Labels: Continent - Northrend, On PTR, Quests
