### ISSUE TITLE
Bag of Fishing Treasures

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3640] opened 2016-08-10 09:51 UTC
**Description**:
Bag of Fishing Treasures is a reward from TBC daily fishing quests.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
All 5 fishing dailies reward [Bag of Fishing Treasures](http://www.wowhead.com/item=35348/bag-of-fishing-treasures), the version where the crocolisk pets drop.
**Expected behaviour**: Tell us what should happen instead
4 fishing dailies
[Bait Bandits](http://www.wowhead.com/quest=11666/bait-bandits);
[Felblood Fillet](http://www.wowhead.com/quest=11669/felblood-fillet);
[Shrimpin' Ain't Easy](http://www.wowhead.com/quest=11668/shrimpin-aint-easy);
[The One That Got Away](http://www.wowhead.com/quest=11667/the-one-that-got-away)
should reward [Bag of Fishing Treasures](http://www.wowhead.com/item=34863/bag-of-fishing-treasures) (without the pets)
and [Crocolisks in the City](http://www.wowhead.com/quest=11665/crocolisks-in-the-city) 
should reward [Bag of Fishing Treasures](http://www.wowhead.com/item=35348/bag-of-fishing-treasures) (with the pets)

**Include proofs for this behaviour**

http://www.wowhead.com/item=35348/bag-of-fishing-treasures#comments:id=1475123
http://www.wowhead.com/item=35348/bag-of-fishing-treasures#comments:id=264815
http://www.wowhead.com/item=34863/bag-of-fishing-treasures#comments:id=306525
http://wowwiki.wikia.com/wiki/Bag_of_Fishing_Treasures_(Terokkar_Forest)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Bag of Fishing Treasures (with pets) item ID 35348
Bag of Fishing Treasures (without pets) item ID 34863
Bait Bandits Quest ID 11666
Felblood Fillet Quest ID 11669
Shrimpin' Ain't Easy Quest ID 11668
The One That Got Away Quest ID 11667
Crocolisks in the City Quest ID 11665

Non-combat pets:
[Chuck's Bucket](http://www.wowhead.com/item=35350/chucks-bucket) item ID 35350
[Muckbreath's Bucket](http://www.wowhead.com/item=33818/muckbreaths-bucket)item ID 33818
[Snarly's Bucket](http://www.wowhead.com/item=35349/snarlys-bucket)item ID 35349
[Toothy's Bucket](http://www.wowhead.com/item=33816/toothys-bucket)item ID 33816

**Comment by robinsch** [comment] 2016-09-26 20:20
On PTR.

**Comment by Rushor** [comment] 2016-11-10 19:45
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 19:45 UTC
Labels: Continent - Outland, Items, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-03-31 16:55
Works as intended on ptr.
