### ISSUE TITLE
Can't spend talent points on assassination skills for Rogue

### ISSUE THREAD

**Issue by Blanchovies** [dalaranwow/dalaran-wow#3664] opened 2016-08-17 05:07 UTC
Over the last 3 levels or so, i haven't been able to spend my earned talent points on assassination skills that i meet the requirements for such as "Puncturing Wounds". I have already spent the 10 talent points in the assassination column to be able to buy the next set of Assassintion talents, so i can only assume the issue is a bug (or i'm just so blind and dumb to see there's another prerequisite). Please solve this issue as soon as possible, as my rogue is main, and I use assassination skills more than any other.

**Comment by Golganeth** [comment] 2016-08-26 17:05
Can't reproduce. Try closing your game client completely and clear your Cache folder. If the problem persists, it's probably an issue with your client (corrupted files or similar) so you should consider reinstalling a proper client.

Closed

**Closed by Golganeth** 2016-08-26 17:05 UTC
