### ISSUE TITLE
[General] Static flyers are not updated on client

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4327] opened 2017-01-26 12:58 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npcs that are above the ground level (flyers) and are "STATIC" (not moving at all) are not updated properly for every client that enters the area.
Example 1:
![wowscrnshot_012617_143317](https://cloud.githubusercontent.com/assets/6797611/22331690/7f559260-e3d5-11e6-9948-4544065ff05e.jpg)
The npcs "frozen orb" are above the others, however as soon as i enter the area they fall on the ground( visually only for every player). 

Example 2:
Video from the server:
https://www.youtube.com/watch?v=2mh6YCzsXaM
 The harpy is up, near the top part of the tree, however as soon as i "see" here, she falls down, however serverside she doesn't (she is still on top, thats why i get the error "out of range" and she takes so much time to attack me for first time).
Video from the server:

**Expected behaviour**: Npcs are suppose to stay in the air even when they are not moving for every client(player) that enters the area.
Video from retail legion from 26.01.2017:
https://www.youtube.com/watch?v=0YFTGb5LUgo
Note: If the flyer has some movement (random movement or with wps) it will be displed correctly for everyone.

**Comment by Rushor** [comment] 2017-01-26 13:03
yep that's realted to the inhabittype.  inhabittype defines if the creature can walk/swin/fly

in this case the harpy f.ex. only has inhabittype swim + walk, but here spawnpoint is above the ground. So as soon as the player loads her grid she will fall down cuz she cannot fly.

it must be adjusted for the creature entry in general then. 

i will fix it for your examples here. if you find more creatures taht should be able to fly, let me know and i will add it :)

**Comment by Rushor** [comment] 2017-01-26 13:13
DB/Creature: Frostfeather Witch, Frostfeather Screecher, Frozen Orb, Disturbed Taunka Ancestor - Should be able to fly

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4327
* commit: 07fb8298c64875f47c650d3b40c669a9c350394f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-01-26 13:13 UTC
Labels: Area - Northrend

**Comment by Rushor** [comment] 2017-01-26 13:16
[![https://gyazo.com/803923ca2efed1338ae40a5913552f8e](https://i.gyazo.com/803923ca2efed1338ae40a5913552f8e.gif)](https://gyazo.com/803923ca2efed1338ae40a5913552f8e)

**Comment by Teridan-dal-wow** [comment] 2017-01-26 14:37
I see, what about something like this:
https://www.youtube.com/watch?v=Cnw5fzfTeu8
Its the same npc, the only diffrence is that 1 has path and 1 doesn't?

**Comment by Rushor** [comment] 2017-01-26 17:46
could be related to addon, i will check

**Comment by Rushor** [comment] 2017-01-26 17:53
hm yeah i found the reason:

the reason why creature are flying is a flag that applies "hover mode"

we have 2 options to apply such "hover mode" flag to creatures. in creature_template_addon (that applies the flag to all creature IDs) and creature_addon (that applies the flag to the guid (the individual spawnnumber for the creature.))

in this case the "hover mode" flag was added in creature_template_addon. However the creature that has waypoints ALSO has an entry in creature_addon to assign the waypoint path. Due to the fact that creature_addon in this case does not has the "hover mode" flag and the fact that creature_addon always overrwirtes the entry in creature_template_addon > the creature with wp movement does not have the "hover mode" flag

**Comment by TeridanDW** [comment] 2017-10-29 10:27
Works as intended on PTR.
