### ISSUE TITLE
Rage generation

### ISSUE THREAD

**Issue by sabimbi** [dalaranwow/dalaran-wow#3067] opened 2015-12-26 22:03 UTC
Since i have hit 80 and started gearing up for raids, i have trying to get some reads for dps numbers on the training dummy but for some reason the rage i get from doing melee hits seems too low from retail values. Does that mean the amount of rage you should get from autos is broken?

**Comment by Golganeth** [comment] 2015-12-27 00:34
Duplicate of #1254 so closing up.

> The problem is that Rage generated by attacking target dummies does not scale with damage dealt and so players only receive a flat amount of rage.

**Closed by Golganeth** 2015-12-27 00:34 UTC
