### ISSUE TITLE
[ICC][Quest] Securing the Ramparts + ICC Quest pooling system

### ISSUE THREAD

**Issue by g0g0dancer** [dalaranwow/dalaran-wow#4775] opened 2017-07-05 10:28 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 1 of several ICC quests spawn in ICC, which reward the player with bag containing 5 emblems of frost and a random item. 

If the quest "securing the Ramparts" is the weekly quest then.
1. Rotting frost giant, spawns on the ramparts. (quest target)
2. Kor'kron Lieutenant, Spawns on the ramparts. (quest giver)
Unfortunatly the Kor'kron Lieutenant does not actually provide a quest, so the raid is unable to pick up their ICC quest.

**Expected behaviour**: The Kor'Kron Lieutenant should have a quest "Securing the Ramparts".

**Steps to reproduce the problem**:

1. Go into icc 10/25 where the quest spawning is "securing the ramparts".
2. try changing difficulty from hc/normal, or killing hc marrowgar?
one week hc marrowgar 10, then death wisper normal kill, then found bugged quest on way to hc gunship.
3. 

Including a screenshot of the quest giver + quest target up with no quest.
![noquestbossup1](https://user-images.githubusercontent.com/24669454/27860541-f08e8b42-6131-11e7-9f1d-0dc06727fd8b.png)

**Comment by Rushor** [comment] 2017-07-05 11:55
This already works fine on PTR. Maybe the queststarter and questender is missing for this creature on the live realm. i will add that as a commit.

Another reason for the issue is that the quest will reset on each server startup. blizzlike the quest should be bound to the instanceid.

![](http://i.imgur.com/njr6g6t.jpg)

**Comment by g0g0dancer** [comment] 2017-07-05 20:19
Quest starter/ender looks like it spawns, but does not have any quest able to be picked up.

**Comment by Rushor** [comment] 2017-07-05 20:25
i think the other reason is (as i already said)

> Another reason for the issue is that the quest will reset on each server startup. blizzlike the quest should be bound to the instanceid.

This means the quest changes each time after every server restart.

Maybe the Kor'kron Lieutenant spawned, but the pool from the quest is an other one (Minchar quest f.ex.)
The quest must always be bound to the correct creature + the quest and the creature are not allowed to switch after every server restart once the player was assigned to a icc raid id.

Those 2 issues must be fixed (will do this tomorrow)

**Comment by plznoz** [comment] 2017-07-06 21:30
I have a feeling this might be happening because the raid leader had an old weekly quest already. Has happened twice to me like that.

**Closed** 2017-12-02 17:25 UTC
Labels: Area - Instances, General - Quests

**Comment by StheNoble** [comment] 2017-12-03 03:14
the questgiver for that weekly is spawned in lights hammer. We always go there to check after lady deathwisper kill and picm it up. The npc on remparts never offers us the quest or let it turn in, instead there is a duplicate in lightshammer though.

the npc isnt present at raid startbut after marrogwar and/or deathwisper kill. After that hes left of the teleporter next to the 2 normal npcs at the wall.
