### ISSUE TITLE
[Quest][Outland] Dimensius the All-Devouring 10439

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#679] opened 2013-08-22 22:10 UTC
Captain Saeed doesn't have the begin escort option, gossip and
Dimensious isn't targetable.
http://old.wowhead.com/quest=10439/dimensius-the-all-devouring
http://old.wowhead.com/npc=20985 - Captain Saeed
http://old.wowhead.com/npc=19554 - Dimensious

**Comment by ashido96** [comment] 2015-07-13 01:52
With the recent update this quest is no longer on auto-complete - there is no dialogue whatsoever on Captain Saeed.

**Comment by Demlock** [comment] 2015-07-24 22:11
Confirmed

**Comment by DrFuler** [comment] 2015-12-18 05:12
18/12/2015: Still bugged.

No dialogue available on Captain Saeed.

**Comment by MrAndersonX** [comment] 2015-12-26 19:57
Confirmed - bugged.

**Comment by Cone182** [comment] 2016-02-23 20:30
bugged!

**Comment by Crispybuilt** [comment] 2016-03-11 00:21
Confirmed, currently not doable

**Comment by jonanone** [comment] 2016-06-05 18:49
Captain Saeed now has the gossip needed to start the escort. The defenders, avengers and regenerators will follow Saeed til the entrance of the Dimensius "cave". Once the new gossip is accepted, the encounter against Dimensius will begin. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment] 2016-06-05 20:05
Works pretty great, i only encountered a few very minor issues:
- Once the Captain and the Avengers pull an NPC and kill it, sometimes it will take a bit too long until they continue with their waypoints.
- The Captain and the Avengers will drop slightly below the ground while inside the Building.
- Dimensius has a respawn timer of 10 mins, while the Captain and the Avengers share a respawn timer of 2min30 sec approx. Because of this, it is possible to start the event and get there while Dimensius is dead. If this happens the event gets stuck.

**Comment by Golganeth** [comment] 2016-06-07 07:13
The respawn timer of Dimensius is still a bit too long compared to the captain's and guards. (7min vs 2-3mins)

**Comment by Zibathy** [comment] 2016-10-31 23:23
Captain Saeed does not have the dialogue on Kirin Tor. See attachment:
![wowscrnshot_103116_182205](https://cloud.githubusercontent.com/assets/7729864/19874968/0c39f992-9f97-11e6-8993-fc1da59d1ee8.jpg)

**Comment by Rushor** [comment] 2016-12-22 10:51
so this is still an issue

**Comment by Rushor** [comment] 2016-12-22 11:11
Commits:

DB/Quests/Netherstorm: Dimensius the All-Devouring.

Captain Saeed now has the gossip needed to start the escort. The defenders, avengers and regenerators will follow Saeed til the entrance of the Dimensius "cave". Once the new gossip is accepted, the encounter against Dimensius will begin. Also reduce respawntime of Dimensius to 60 seconds.
Closes https://github.com/dalaranwow/dalaran-wow/issues/679
* commit: 35bdb1f0e4f797e38c9403bcaefc006a70a7b37a
* commit: acb1116d7f1bc870a218adf98066c465fc338929
* commit: 3a3f6b4f9c10f0564ce7017ac6e2ca15227fa775

![GitHub Logo](http://i.imgur.com/yLqtlfU.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-22 11:11 UTC
Labels: Area - Outland, Fixed - Waiting for PTR Update, General - Quests
