### ISSUE TITLE
[NPC] [Quest] Mor'vek incorrect quest order

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1269] opened 2014-02-23 21:16 UTC
Mor'vek (http://wotlk.openwow.com/npc=11701) at first offers two quests; if you pick up one of the quests, the other quest will become unavailable. And after you complete the quest you picked up, Mor'vek won't offer the other quest. Instead, he'll offer They Grow Up so Fast (http://wotlk.openwow.com/quest=13906). 

According to the comment (http://www.wowhead.com/npc=11701/morvek#comments) posted on wowhead by a player from patch 3.1 the quest order should be:
1. Toxic Tolerance (http://wotlk.openwow.com/quest=13850)
2. Venomhide Eggs (http://wotlk.openwow.com/quest=13887)
3. They Grow up So Fast (http://wotlk.openwow.com/quest=13906)

**Comment by Demlock** [comment] 2015-04-19 11:45
The problem here on my side was that NPC offered two of the quests simultaneously. These were under numbers 1 and 2. Lucky I knew about this quest order so I have taken the proper quest order and no quest was locked out for me. Other players (esp the ones who don't know this) should watch out, because, according to what you say, this is purely a problem of Venomhide Eggs not having a restriction of Toxic Tolerance being completed. And if you complete the Venomhide Eggs, the game will lock the Toxi Tolerance out because it has determined that you have already completed it.

**Comment by Rushor** [comment] 2016-11-14 21:20
DB/Quest: Apply prevquest to "Venomhide Eggs"

* closes https://github.com/dalaranwow/dalaran-wow/issues/1269
* commit: 0428022f1b9e55df1f331e004e0e0f57e19a6eca
* order will be now: Toxic Tolerance > Venomhide Eggs > They Grow up So Fast

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 21:20 UTC
Labels: Continent - Classic, Quests

**Comment by TeridanDW** [comment] 2017-04-04 10:49
Works as intended on ptr.
