### ISSUE TITLE
[NPC] Drek'Maz and Tiri

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2044] opened 2014-11-05 10:36 UTC
They are not using their abilities.

http://www.wowhead.com/npc=28918#abilities
http://www.wowhead.com/npc=28916#abilities

**Comment by Rushor** [comment] 2016-11-15 10:52
DB/Creature: Add abilities for Drek'Maz and Tiri

* closes https://github.com/dalaranwow/dalaran-wow/issues/2044
* commit: 1b80191a49358523661306c05496cd7e22175b3d

('Tiri - In Combat - Cast \'Concussion Blow\'');
('Tiri - Between 0-50% Health - Cast \'Renew\' (No Repeat)');
('Drek\'Maz - In Combat - Cast \'Mortal Strike\'');
('Drek\'Maz - In Combat - Cast \'Whirlwind\'');
('Drek\'Maz - Between 0-30% Health - Cast \'Enrage\' (No Repeat)');
('Drek\'Maz - On Reset - Remove Aura \'Enrage\'');

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 10:52 UTC
Labels: Continent - Northrend, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 18:47
Works as intended on ptr.
