### ISSUE TITLE
[Quest][Northrend] The Earthen Oath

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#764] opened 2013-09-08 23:41 UTC
**Quest The Earthen Oath** - _(ID:13005)_
- **Issue present:** Players are not getting credit after killing either **Iron Sentinel** _(ID:29984)_ or **Iron Dwarf Assailant** _(ID:29978)_. Even with the assistance of the dwarves.
- **How it should work:** Players gets the item, **Horn of the Peaks** _(ID:42840)_, and with it he can summon 4 dwarfs which have the following abilites: _Earth Shield_, _Earth Shock_, _Earth's Grasp_, _Lava Burst_.

**Earth Shield** - _56451_
**Earth Shock** - _56506_
**Earth's Grasp** - _56425_
**Lava Burst** - _56491_

They will assist you in fighting those mobs and once you kill them **YOU SHOULD** get the credit.

They are related to the following bunnies in-game: 
**Iron Sentinel Credit** _(ID:30296)_
**Iron Dwarf Assailant Credit** _(ID:30297)_

After I killed those as a GM I got the credit.
So I guess fix could look like this: "Spawn those upon death of actual mobs, auto-kill them and give a credit to player. Spawn them as invisible bunnies. or something because this quest could fail if you let your assistans do the blowing kill on a Sentinel or Assailant.

**Video of how it should work:** _http://www.youtube.com/watch?v=q4V1eq6oreI_

---

http://www.wowhead.com/quest=13005/the-earthen-oath
http://www.wowwiki.com/Quest:The_Earthen_Oath
http://www.wowhead.com/npc=30270/oathbound-warder#abilities
http://www.wowhead.com/item=42840

**Comment by taralej90** [comment] 2015-03-03 09:48
Another issue with this quest is that the NPCs summoned by the Horn Of The Peaks do not count as pets/minions and thus we do not get a pet/minion action bar to use their abilities. This makes the quest considerably harder to solo, especially for some classes.

Link to NPC spells: http://www.wowhead.com/quest=13005/the-earthen-oath#comments:id=539610

**Comment by budthechud** [comment] 2016-06-10 04:53
Can confirm the missing abilities of the minions. Attached is a screenshot showing the missing Pet Bar
http://i.imgur.com/cKKvbJe.jpg

**Comment by Rushor** [comment] 2016-06-10 05:28
we can add an ai with abilities for them instead

**Comment by budthechud** [comment] 2016-06-10 07:04
Awesome!  Quick notes is there a way to make it so not getting the killing blow still delivers credit?

**Comment by Rushor** [comment] 2016-06-10 07:30
yes we implemented a flag which requires the player to do at least 1 damage and the player will still get the credit. 

I will reopen the issue due to the missing ablities. Fix will be pushed soon on ptr

**Comment by Klala** [comment] 2016-07-16 10:31
I am still having a hard time getting credit for the kills. In a group it's even worse.
It seems that currently the only way for me to get credit for the kill is to be the one to land the killing strike. If the dwarfs or someone else in your party is the one landing the killing strike you will not get the credit for the kill.

**Comment by Rushor** [comment] 2016-11-24 20:29
Scripts/Quest: The Earthen Oath - Add abilitysupport for Oathbound Warder pets

* closes https://github.com/dalaranwow/dalaran-wow/issues/764
* also if you do at least 1 dmg on the hostile creatures, you will get the killcredit
* commit: 4d9ffe468019ce5bf8e85b11caf012cbde44ccdd

![GitHub Logo](http://i.imgur.com/PWEokFG.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 20:29 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by growler17** [comment] 2017-06-03 18:47
Has this fix been pushed to live? Still seems to require dealing the final blow to get credit.
