### ISSUE TITLE
Quest Item: Box o' Tricks

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#399] opened 2013-08-05 19:19 UTC
Minor Issue: 
The quest item sometimes transforms you into an imp instead of a crate.
That should not happen, on each attempt you should be transformed into a crate.
Also as a crate you cannot move and the event has to start once you become a crate (in this case, the event starts if you move around a little and trigger something so the even can start)

Other than that, the event and quest works fine.
Asked few players if they had the same issue, they confirmed.

Two quests related to this for horde and alliance: 
http://wotlk.openwow.com/quest=10596
http://wotlk.openwow.com/quest=10563
30638 - [Box o' Tricks]

**Comment by Demlock** [comment] 2015-07-24 22:13
Aside from that minor detail, everything is ok

**Comment by Rushor** [comment] 2016-11-28 21:25
DB/Item: Box o' Tricks should always transform you into a box

* closes https://github.com/dalaranwow/dalaran-wow/issues/399
* commit: b1a7bc93a58d01e2d891d1c77bed716241255b77

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 21:25 UTC
Labels: Continent - Outland, On PTR, Quests
