### ISSUE TITLE
Quest: Stunning Defeat at the Ring [11300]

### ISSUE THREAD

**Issue by Acillius** [dalaranwow/dalaran-wow#3240] opened 2016-04-24 19:53 UTC
The quest Stunning Defeat at the Ring, has an issue where the NPC Oluf will not spawn when you kill all the gladiators in the room, I waited for the mobs to re-spawn 4 times before I gave up because he would not spawn. Also to note the Val'kyr that should be flying around in the room are jsut standing on the floor. The other thing is most of the ally NPCs that are prisoners are just standing around doing nothing when most of them should be in cages while some are fighting the gladiators.

Here are some pictures to show what I am talking about.
[http://imgur.com/a/RLK8n](url)

**Comment by Golganeth** [comment] 2016-04-29 11:30
Please open separated reports for each different issue you may encounter. I've edited your report because the first part was a duplicate of #1722. 

Confirming the quest issues.

**Comment by Acillius** [comment] 2016-04-29 15:52
I will remember that from now on thank you for eventually getting to the issue

**Comment by Lothloryen** [comment] 2016-05-02 10:35
Hello there,

Thank you for the report, both issues will be corrected after the next realm restart.

Thank you.

**Closed by Lothloryen** 2016-05-02 10:35 UTC
Labels: Northrend, Quests

**Comment by sixele** [comment] 2016-05-05 16:15
Tried on an alt today, did not seem to work. Issue is still the same at OPs.
