### ISSUE TITLE
[Shaman] Thunderstorm bugg

### ISSUE THREAD

**Issue by dammtoni** [dalaranwow/dalaran-wow#1096] opened 2014-01-07 22:04 UTC
Thunderstorm doesnt work properly atleast the effect which shoud do push back (2nd mana regen work fine) when target is rooted/stuned/feared/sap etc... cant pusg him at all same time caus of the Loss system caunt is like behind a wall doesnt show damage (or any other miss/resist effect) 

how does works:
(regen is fine/damage done is fine)the pushing effect shoud do it even if target is behind a wall (but only if is range  of 10 yards) have to push itback doesnt matter if target is behind a wall(Loss) but only is is range of thunderstorm spell effect

**Comment by Rushor** [comment] 2016-12-07 21:07
root = no. everything else = yes

> -It should work when stunned :S it definitely works when trapped. But it should definitely not work when rooted.

http://eu.battle.net/wow/en/forum/topic/8819242556

Game/Spells: Enable knockback for stunned units

* source: http://eu.battle.net/wow/en/forum/topic/8819242556
* closes https://github.com/dalaranwow/dalaran-wow/issues/1096
* commit: 894eb55daa6a24fdc099a1b6c94e78ef0abdc2fd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-07 21:07 UTC
Labels: Class - Shaman, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-23 09:11
Hello, after few tests on PTR:

> Game/Spells: Enable knockback for stunned units

works as intended (vs stuns/fears/saps and doesn't push vs roots).

Regarding:
 

> the pushing effect shoud do it even if target is behind a wall (but only if is range of 10 yards)

I couldn't find any proof for that. Will be great is someone can, thank you.
