### ISSUE TITLE
[Vehicle] Wintergrasp Vehicle creation before battle

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3038] opened 2015-12-12 19:06 UTC
Players are somehow able to create siege engines (probably demolisher and catapult too) before Wintergrasp battle start giving the advantage of faction who abuse this
http://i.imgur.com/PZp1mbp.jpg
http://i.imgur.com/7ehuTX9.jpg
As you can see on the screenshots 50seconds after battle has started (in this case) horde already has one siege engine even tho it clearly says 0/16 vehicles for horde and 0/8 for alliance.
I dont know how to reproduce this bug but this isnt the first time i see this.

**Comment by Nimrasil** [comment] 2015-12-27 12:19
Confirmed. I was in that Wintergrasp, too (on horde side) and saw someone in that siege. I asked him how he'd done, and he said it just stood there, outside the workshop. I don't think he was able to drive it.

**Comment by Rushor** [comment] 2016-12-01 13:13
i will add the addition, that the vehicle will despawn if the wg wartime is not active

**Comment by Rushor** [comment] 2016-12-01 14:31
Scripts/Wintergrasp: Despawn vehicle if Wintergrasp is not active

* also reward killcredits from the vehicles to the whole group
* also disable killcreditreward if the the vehicle dies because of selfkill in the water
* closes https://github.com/dalaranwow/dalaran-wow/issues/3038
* commit: 5856269a3ca9188cfe44c10f48c91330c148484c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-01 14:31 UTC
Labels: Continent - Northrend, Fixed - Waiting for PTR Update, General - PvP, Priority - High

**Comment by Rushor** [comment] 2018-06-04 15:27
already on PTR
