### ISSUE TITLE
[Hunter] Spell - Flare

### ISSUE THREAD

**Issue by moliskrc** [dalaranwow/dalaran-wow#1206] opened 2014-02-15 18:10 UTC
http://www.wowwiki.com/Flare

Exposes all hidden and invisible enemies within 10 yards of the targeted area for 20 sec.

It doesn't reveal stealthed units in the targeted area while flying.
There is a closed issue of this spell on trinitycore:
https://github.com/TrinityCore/TrinityCore/issues/1331

How it works here:
http://s4.postimg.org/54dk4b8cd/Wo_WScrn_Shot_021514_153417.jpg
http://s17.postimg.org/gfqsc00an/Wo_WScrn_Shot_021514_153421.jpg
http://s29.postimg.org/dixbas1lz/Wo_WScrn_Shot_021514_153424.jpg
Flare is used, but as you can see, the rogue is still in stealth.

How it should work:
The effect of the spell should start on use, not when it lands. The landing of the flare is only visual. It should reveal stealthed units while flying and when landed and break stealth.

http://www.warcraftmovies.com/movieview.php?id=163895
Stop the movie at 1:20, and watch rogues debufs. Flare is used, but not landed and he has the debuf already.
At 3:22 you can see the same thing, flare has not landed, but the mage has the debuf.
At 13:27 you can see rogue has been revealed by the flare which is in the air.

This one is taken from blizz TournamentRealm: http://www.youtube.com/watch?v=a74AeUDLwQI
Stop the movie at 7:42. You can see that rogue, warlock and shaman gets the debuf before flare lands.

**Comment by Rushor** [comment] 2016-12-11 13:18
What should happen instead if a player casts stealth while he has the debuff http://wotlk.openwow.com/spell=1543 ? should the player not be able to cast stealth?

**Comment by Rushor** [comment] 2016-12-11 13:23
some more info on the spell itself:

warning to all hunters. It is possible to sneak inside the flare radius if a stealthed enemy enters IMMEDIATELY after the flare disappears and moments before the next one hits the ground. The flare debuff is not applied until the object itself hits the ground.
http://de.wowhead.com/spell=1543/leuchtfeuer#comments:id=159529

**Comment by Rushor** [comment] 2016-12-11 13:25
Game/Spells: Prevent using stealth while target has aura Flare (1543)

* closes https://github.com/dalaranwow/dalaran-wow/issues/1206
* commit: f67f60d2adecbec0122a0db0e64acb6aadb78bcf

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-11 13:25 UTC
Labels: Class - Hunter, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-21 08:19
Both issues seems fixed and work as intended on PTR.
