### ISSUE TITLE
[Quest][NPC] Mounting Up/Highland Mustang

### ISSUE THREAD

**Issue by abonander** [dalaranwow/dalaran-wow#3676] opened 2016-08-24 06:52 UTC
http://www.wowhead.com/quest=12414/mounting-up
http://www.wowhead.com/npc=26472/highland-mustang

The Highland Mustangs traveling as a herd are effectively impossible to ride back to camp. Their patrol script takes control even while the player is riding them.

**Comment by Icespear1** [comment] 2016-08-24 11:45
Quest works fine if you tame the ones that do not move with a group, the herd travelling mustangs do not break the patrol script when tamed just like you said.

**Comment by Rushor** [comment] 2016-11-13 17:52
DB/Creature: Highland Mustang - Remove waypoints

* closes https://github.com/dalaranwow/dalaran-wow/issues/3676
* i removed the waypoint until a propper charmbehaviour for creatures with waypoints are implemented
* commit: 5d308e69fa3272b5a94fc901eeaae2b70075618b

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-03-31 13:46
This is not working properly. Even though the horses doesn't have a path now, they are still in a formation and the leader has random movement = 1 , which leads to members following him and providing the exact same result as @abonander pointed out.

**Comment by Rushor** [comment] 2017-07-04 11:45
DB/Creature: Highland Mustang - Remove creature formation

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3676
* commit: ac52aa0cd0e31ae0bf6a9c36ed279110444af659

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-04 11:45 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR Update, General - Quests

**Comment by TeridanDW** [comment] 2017-10-24 11:02
Works as intended on PTR.
