### ISSUE TITLE
[Paladin] - Pursuit of Justice talent

### ISSUE THREAD

**Issue by instinctbluez** [dalaranwow/dalaran-wow#3894] opened 2016-11-28 12:01 UTC
**Description**: Mount movement speed issue

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Mount movement speed does not increase if you die and resurrect. Note, it's only the mount movement speed which gets affected, normal movement speed remains fine.

**Expected behaviour**: Tell us what should happen instead
Mount movement speed should increase even if you die and resurrect.

**Steps to reproduce the problem**:

1. Obtain Pursuit of Justice talent
2. Die
3. Mount

**Relogging usually fixes the problem**

**Include proofs for this behaviour**

Attached screenshots

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Spell - 26022 or 26023

**Include Screenshots from the issue if necessary**
Before relogging
![wowscrnshot_112816_171559](https://cloud.githubusercontent.com/assets/24224188/20667530/b11368d2-b58f-11e6-8dff-621706605ce2.jpg)

After relogging
![wowscrnshot_112816_171935](https://cloud.githubusercontent.com/assets/24224188/20667531/b11820f2-b58f-11e6-8cc2-3490995267ef.jpg)

**Comment by Rushor** [comment] 2016-11-28 12:47
DB/Spell: prevent serverside auras for Paladin talent Pursuit of Justice from vanishing after death

* closes https://github.com/dalaranwow/dalaran-wow/issues/3894
* commit: 429c61f393d36b7a63e17ded185abf4996bafb96

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 12:47 UTC
Labels: Class - Paladin, On PTR

**Comment by TeridanDW** [comment] 2017-10-23 07:24
Works as intended on PTR.
