### ISSUE TITLE
[Shaman] Elemental T8 4 piece dot not stacking

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#2622] opened 2015-07-09 09:52 UTC
4 piece T8 - http://wotlk.openwow.com/spell=64928 "Electrified"

HOW IT WORKS NOW:
A LB crit followed by another LB crit does not "stack" the damage from electrified not yet inflicted, it only refreshes the duration and ticks for the 1x amount.

First look at this screenshot with one crit:
![1x crit](http://i.imgur.com/4qAqQR0.png)

Then look at this one with 2x crits in a row:
![2x crits in a row](http://i.imgur.com/afl04pJ.png)
As you can see the damage is not added to the refreshed dot.

HOW IT SHOULD WORK:
The damage that is not yet inflicted, should be added to the new Electrified dot (Just like ignite for mages)

I base this on a post made by "Rambler" on mmo-champion when wotlk was live: ([forum post here](http://www.mmo-champion.com/threads/647881-Ele-Shaman-Tier-8-4PC?p=6254012&viewfull=1#post6254012))
[Video showing stacking on live](https://www.youtube.com/watch?v=-SXW8UVKtXw)

If anyone has input on this matter, feel free to chip in.

**Comment by Rushor** [comment] 2016-12-02 09:41
Game/Spells: Shaman T8 Elemental 4P Bonus - Add remaining ticks to damage done

* closes https://github.com/dalaranwow/dalaran-wow/issues/2622
* commit: 0c84a5bfd026228aade9f0a5d8ddb0345cb10c5f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-02 09:41 UTC
Labels: Class - Shaman, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-22 15:32
Works as intended on PTR.
