### ISSUE TITLE
I am not given a lance with Mastery of Melee (Kirin Tor)

### ISSUE THREAD

**Issue by UncleCrust** [dalaranwow/dalaran-wow#5864] opened 2020-03-31 17:56 UTC
I accept Mastery of Melee from Magister Edian Sunhollow in which he says, "Take this lance...", but there is no lance in my inventory after accepting. I've restarted the game to no avail.

**Comment by Golganeth** [comment] 2020-03-31 18:43
The NPC isn't supposed to provide the lance upon picking up the quest, you must take it.
Closing since the quest works as intended.

**Closed by Golganeth** 2020-03-31 18:43 UTC

**Comment by UncleCrust** [comment] 2020-03-31 18:53
DOH! Thanx, Gol!

**Comment by UncleCrust** [comment] 2020-03-31 22:30
> 
> 
> The NPC isn't supposed to provide the lance upon picking up the quest, you must take it.
> Closing since the quest works as intended.

Exactly *HOW* does one "take it"? I've abandoned & re-accepted the quest 1/2 a dozen times & I cannot figure out how to take the lance. There is no lootable lance in the entire tent & none of the npcs has one. Please explain/detail. Thanks.
