### ISSUE TITLE
[Quest] "Further Conversions" - Converted Sentry will follow you

### ISSUE THREAD

**Issue by Aurainbows** [dalaranwow/dalaran-wow#1776] opened 2014-08-01 05:45 UTC
For the daily quest "Further Conversions" in the Isle of Quel'Danas, after you convert an Erratic Sentry, it disappears and a Converted Sentry appears as it is supposed to. However, the Converted Sentry is the players guardian, and follows the player around. They do not despawn when the quest is turned in.
[EDIT] They did disappear eventually but it is a very long timer, I'm not exactly sure but I'm guessing around 15 minutes. They're supposed to just spawn, say their thing, and disappear after a few seconds - not becoming <Playername's Guardian> following them around.

This can become a problem as the player navigates the zone because they will aggro mobs which then cause the player to be in combat until the mob is killed.

![screen shot 2014-08-01 at 2 42 14 pm](https://cloud.githubusercontent.com/assets/8326673/3775199/c9a9d844-193e-11e4-897f-4b61e5428f0e.png)

![screen shot 2014-08-01 at 2 42 30 pm](https://cloud.githubusercontent.com/assets/8326673/3775205/01897d64-193f-11e4-822d-656acb90a111.png)

![screen shot 2014-08-01 at 2 50 18 pm](https://cloud.githubusercontent.com/assets/8326673/3775235/edf52856-193f-11e4-8ea7-edaf0563c678.png)

**Comment by Rushor** [comment] 2016-11-14 20:59
DB/Quest: Further Conversions - Converted Sentry should despawn after 7 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/1776
* Converted Sentry will now despawn after summon after 7,5 seconds

![GitHub Logo](http://i.imgur.com/qNXx59m.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 11:17
The despawn part works as intended on ptr, however it is not enough because if the player moves away and aggros something, we get the same situation that @Aurainbows described.
I will suggest to add - on spawn - set reach : passive

**Closed** 2018-03-18 21:10 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update, General - Quests
