### ISSUE TITLE
[Northrend][Quest] No Fly Zone

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3896] opened 2016-11-28 17:07 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 At the moment the bone gryphon has 2 bugs from what I've encountered. 
 First, the bone gryphon's Plague Strike doesn't work. It doesn't do dmg at all, only showing the animation.
 Second, Frost Breath has it's target reticle all messed up. You don't really fire in the reticle that you see, but to it's sides or smth like that.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 Plague strike is bugged, and Frost Breath has some targeting issues.

**Expected behaviour**: Tell us what should happen instead
 Plague strike should work, and Frost Breath should deal dmg in it's target reticle.

**Steps to reproduce the problem**:

1.  Take the quest.
2.  Use the skills.
3. 

**Include proofs for this behaviour**

http://www.wowhead.com/quest=12815/no-fly-zone#comments
http://wowwiki.wikia.com/wiki/Bone_Gryphon
https://postimg.org/gallery/2xalfcho8/
 As you can see in the images, Frost Breath doesn't hit it's target in the reticle, and Plague Strike doesn't work at all.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-28 18:13
i will look into that issue mate

**Comment by MrAndersonX** [comment] 2016-11-28 18:16
@Rushor 
Thanks buddy ! :P

**Comment by Rushor** [comment] 2016-11-28 20:51
Game/Spells: Plague Strike - Enable Range + Add targetingconditions for Frost Breath + Plague Strike

* closes https://github.com/dalaranwow/dalaran-wow/issues/3896
* the both damage spells will now also only target the creatures on the island (and no longer players)
* commit: 0551d9b2af7ca61b642c463e6217f51450ccaccf

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 20:51 UTC
Labels: Continent - Northrend, On PTR, Quests
