### ISSUE TITLE
Quest: Saragosa's End

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2252] opened 2015-02-20 12:09 UTC
In this quest Keristrasza asks you to go up on a platform where Saragosa roams, place an enfeebling lure for her, then defeat her once she eats the lure.

The problem: she is summoned, but the script is missing - she doesn't eat the lure so she doesn't transform into her weaker human form. Players are forced to fight a 73lvl elite, which, although only has 9k HP, hits for 1.5k on plate.

Quest link: http://www.wowhead.com/quest=11957/saragosas-end

**Comment by Golganeth** [comment] 2015-02-20 15:29
Duplicate of #546

**Closed by Golganeth** 2015-02-20 15:29 UTC
