### ISSUE TITLE
[Warrior] Talent: Sweeping Strikes

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1066] opened 2013-12-25 00:21 UTC
Talent's link: http://wotlk.openwow.com/spell=12328

What's wrong: while Bladestorming, Sweeping Strikes is not doing damage to the targets hit by the Bladestorm if the caster is not in melee range of the targets

How it should work: When damaging multiple enemies with Bladestorm, Sweeping Strikes should proc too

How to reproduce: Go near two dummies in Stormwind, pop SS, get out of melee range but near enough to hit with Bladestorm, use Bladestorm

**Comment by Rushor** [comment] 2016-12-10 11:27
Should be fixed on PTR.

Fix Sweeping Strikes damage
* commit: d123780b2b04329839f8915afb3bdb7363f5edb7

**Comment by TeridanDW** [comment] 2017-04-06 13:22
Sweeping Strikes still fails to do damage when the warrior is using bladestorm on 2 targets at max distance (while bladestorm still hits the 2 targets)

**Comment by Rushor** [comment] 2017-11-12 10:57
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/5014. I will close the issue here because https://github.com/dalaranwow/dalaran-wow/issues/5014 is more detailed.

**Closed by Rushor** 2017-11-12 10:57 UTC
Labels: Class - Warrior
