### ISSUE TITLE
[NPC] Theka the Martyr

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1045] opened 2013-12-17 11:43 UTC
http://www.wowwiki.com/Theka_the_Martyr

http://www.wowhead.com/npc=7272#encounter

Theka should have 2 abilities: 

http://wotlk.openwow.com/spell=8600 - disease proc on attack.
http://www.wowhead.com/spell=11089 - should make him immune for Physical and Shadow damage for 15 sec.

Currently Theka just melees.

**Comment by Rushor** [comment] 2016-11-12 19:11
DB/Creature: Theka the Martyr - Add 'Theka Transform' ability

* closes https://github.com/dalaranwow/dalaran-wow/issues/1045
* commit: ffc9fe476cebe8f73047d82f0386bf8188492913

![GitHub Logo](http://www.wowhead.com/spell=11089/theka-transform#screenshots:id=82543)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 11:34
Hello, after few tests on this creature i found few issues:
 - Spell http://www.wowhead.com/spell=11089/theka-transform is not casted between 0-50% hp, this is also wrong it should be casted at 30% hp
 - There is a missing mechanic in this fight, at 25%hp he should call for help nearby npcs http://wotlk.openwow.com/npc=7269

Proof:

> By maximusprime (1,136 – 1·13) on 2007/06/02 (Patch 2.1.0)		
> Theka the Martyr patrols around a room full of Scarabs. The Scarabs do not aggro unless you attack them. 
> 
> This is a pretty normal battle. However, once Theka is near ~20% health he uses the ability Theka Transform, with which he becomes immune to both Shadow and Physical damage. Soon after this he makes the nearest Scarabs aggro, usually on the lowest group member (Usually around 5 Scarabs, so be careful if you're cloth). He stays immune for close to 30 seconds so just kill the scarabs then pound him.

**Closed** 2017-12-14 17:21 UTC
Labels: Area - Instances, Fixed - Waiting for Live update
