### ISSUE TITLE
Glowing Blood debuff bug

### ISSUE THREAD

**Issue by Arrenton** [dalaranwow/dalaran-wow#2238] opened 2015-02-12 02:42 UTC
The Glowing Blood debuff from Umbraglow Stingers in Zangarmarsh is supposed to prevent you from using stealth/invisible. But I was able to use prowl as a druid while I had it. 
I have no idea if the other wasp blood debuffs in Zangarmarsh have the same bug or not.

**Comment by n-ghost** [comment] 2015-02-12 04:13
They do.

https://github.com/dalaranwow/dalaran-wow/issues/414

Also applies to that disease on rogue quest that's presumably should prevent them from stealth.

**Comment by Golganeth** [comment] 2015-02-12 13:23
Duplicate of #414

**Closed by Golganeth** 2015-02-12 13:23 UTC
