### ISSUE TITLE
[Warlock] Fel Intelligence Buff missing

### ISSUE THREAD

**Issue by genokan** [dalaranwow/dalaran-wow#3327] opened 2016-05-26 01:24 UTC
Missing the Fel Intelligence buff on my warlock. If I turn auto cast on, it attempts to spam to spell but still will not cast. If I manually cast it, nothing happens.

**Comment by Golganeth** [comment] 2016-05-26 10:38
Can't reproduce. Closing up until more proof to support the bug is provided. Bear in mind this buff shouldn't stack with certain auras so it will not apply if one of those is active in your character.

Closed

**Closed by Golganeth** 2016-05-26 10:38 UTC

**Comment by genokan** [comment] 2016-05-26 12:45
I'll take video/screenshot tonight. This occurs when I'm solo (no other buffs).

**Comment by Lukas45** [comment] 2016-05-26 21:30
This happens if anyone eligible for the buff has either Arcane Intellect or Divine Spirit, and that includes the Felhunter itself. It will attempt to cast, but because someone has a more powerful version, it can't apply the aura, and as is bugged on the server, it will attempt to spamcast.

How to fix?
Get your felhunter killed/dismiss it(not just mount/log) and resummon, and it will be free of all buffs.

**Comment by genokan** [comment] 2016-05-27 12:45
It persisted for a few days through various Felhunter deaths/resummons, but last night it actually was working normally. That does make sense though, because the first time it happened I had grouped up and had a Divine Spirit buff. Thanks for the info, I'll keep that in mind if I see it again!

**Comment by Rahizm** [comment] 2019-08-19 00:24
Sorry for the necro, but can confirm the bug. My felhunter will cast the spell and apply the buff to himself but it will not be cast on my character. This persists through dismissing and resummoning.
