### ISSUE TITLE
[NPC] Minor bugs: NPCs in the air like they don't care.

### ISSUE THREAD

**Issue by ravinki** [dalaranwow/dalaran-wow#2609] opened 2015-07-07 07:46 UTC
1. Kira Songshine in elwyn forest at about 35, 54 is juping around up in the tree tops. 
2. The Kobold laborers in Echo ridge mine in human starting area are having gravity problems and are running around in the mine ceiling.

**Comment by Rushor** [comment] 2016-11-15 09:42
http://wotlk.openwow.com/npc=80
http://wotlk.openwow.com/npc=3937

**Comment by Rushor** [comment] 2016-11-15 09:45
DB/Creature: Kira Songshine + Kobold Laborer - improve pathing and randommovement

* closes https://github.com/dalaranwow/dalaran-wow/issues/2609
* Kira Songshine will now correctly walk up and down along the route
* Kobold laborer randommovement was reduced, this means he will no longer walk on walls

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 09:45 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 20:47
Works as intended on ptr.
