### ISSUE TITLE
Rogues DPS issues in raids.

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5141] opened 2017-12-01 09:58 UTC
[//]: # (INFORMATION ABOUT TAGS) [rogue]
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Right now Rogue doesn't considered as a dps class due to low dps and raids usually have 1 rogue for debuff that's it. But if we look back rogue were one of the top dps in raids... 
**Expected behaviour**: Tell us what should happen instead
Perform well and not considered as "we have to have one for debuff"
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
https://www.youtube.com/watch?v=4L-M_kWMC7A&t=2s
You can see rogue performing 19k burst dps self buffed. I was never able to do so much burst in raid buffs and +5% buff in ICC.
https://www.youtube.com/watch?v=SHAroRXdnPA
https://www.youtube.com/watch?v=tGKIsvXQ3UA
Here is report http://www.mmo-champion.com/threads/752517-Comparison-of-DPS-classes
the data was taken from http://www.worldoflogs.com/

There were reports regarding prey on the week ability not working as intended, hack and slash, rupture doing damage to yourself. I think all rogues would appreciate if devs could take a look

**Comment by TeridanDW** [comment] 2017-12-01 12:06
Alright @Jiaku, so you are saying there is something wrong with rogue's damage but you didn't mention anything, in this report, that might cause it or did I misunderstood it?

**Comment by Zarjofgt** [comment] 2017-12-01 12:13
This is a terrible report, but a big issue regardless. @Jiaku take a look at some logs and find out which abillities arent doing proper damage and the devs might be able to fix this.

**Comment by Jiaku** [comment] 2017-12-01 12:25
There is defenetly something wrong with rogue's dps. THere are reports on github regarding it. #5085 #3987 #3617, as well as poisons doesn't scale properly. During this week i'll try to gather logs.

**Comment by Aridam** [comment] 2017-12-01 13:16
Should probably consider remaking this as either a neat list of reproducible Rogue bugs to easily-prove your claims and help direct attention towards them for future fixes, or do so separately for every individual bug instead -- just not like this because it's practically an invalid report, due to missing too much data and causing confusion; if it's a correct and information-rich report, then you'd be making everyone's time a lot less difficult and therefore, spend less of it on this as well.

However, I can confirm that Combat Rogues for example are supposed to be among the top three in Wrath of the Lich King DpS, alongside Fury Warriors and Fire Mages, so if a geared (and especially, skilled) CR fails to end up at the top in DpS rankings in a controlled environment, then there must be something wrong as referenced in Jiaku's last reply.

**Comment by Jiaku** [comment] 2017-12-01 13:36
I know it is invalid report, all i want is to drug the attention to this case. I would love to test these things but dummies working incorrectly

**Comment by TeridanDW** [comment] 2017-12-01 15:08
Alright, when you have some additional information please edit the first post and it will be reviews.
Closing for now.

**Closed by TeridanDW** 2017-12-01 15:08 UTC
