### ISSUE TITLE
Quest: Get me out of here + ground issue

### ISSUE THREAD

**Issue by Salamagundi** [dalaranwow/dalaran-wow#830] opened 2013-09-27 08:52 UTC
The quest works for the most part, main issue being that the pet and the mob it fought sank through the ground and possibly ended up in the caves underneith (ie entrance to Maraudon). First time the pet was left to fight on it's own and got killed, I retook the quest and had another go and when I got to the spot (roughly coord 61, 37) the same thing happened again, this time I set the pet to passive and called it back. Problem now was that Melizza Brimbuzzle still had aggro on the mob and refused to continue, she did move backwards though, after moving back enough to get aggro on a repop apparently she forgot about the mob underground and we could continue our journey to it's end.

Attaching a screenshot so you can see her parting comments that need to be cleaned up slightly.
![wowscrnshot_092713_102258](https://f.cloud.github.com/assets/5490882/1224659/0afd7d4e-2752-11e3-95d5-54395a4c3d13.jpg)

Summary: the quest basically works just issues with apparent quicksand makes it a bit iffy at one spot.

**Comment by Rushor** [comment] 2016-11-17 14:01
DB/Quest: Get me out of here - Reinsert escortscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/830
* commit: a090c7f4a288bf070a5659825603888894eca9c5

I reapplied my old escortfix from https://github.com/TrinityCore/TrinityCore/blob/680ad1bab8033548b56ee7bd557c3fcf1669190d/sql/updates/world/2015_05_11_05_world.sql. The quest itself should work better now.

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 17:19
Quest is completeable, however there are few issues that can be corrected:
 - On quest accept the cage of melizza should open and close after she leaves it (currently she just passes though the door)
 - the 3 creatures that spawn here:
![image](https://cloud.githubusercontent.com/assets/6797611/24669393/f9735366-1972-11e7-9009-8701279048f0.png)
should engage melizza on summon (currently they just stay and wait for her to get closer)

 - quest credit is given on player way too soon (after the fight with the 3 summons) instead if should be given when she is escored to the camp here:
![image](https://cloud.githubusercontent.com/assets/6797611/24669464/36ff97a8-1973-11e7-9877-245937dedc5b.png)
 - melizza doesn't fightback with the creatures:
![image](https://cloud.githubusercontent.com/assets/6797611/24669605/acc776a4-1973-11e7-97b7-382d99d0ee26.png)
 after the maraudines

 - Milizza's path here:
![image](https://cloud.githubusercontent.com/assets/6797611/24669633/d0430670-1973-11e7-9f08-359d05084aa8.png)
should be checked as she goes forward > backwards > forward on few spot and falls undermap for few seconds.

**Closed** 2017-11-30 14:22 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update, General - Quests, Works - but it needs improvements.
