### ISSUE TITLE
[Rogue] Overkill lasting forever

### ISSUE THREAD

**Issue by KataRinne** [dalaranwow/dalaran-wow#2299] opened 2015-03-15 16:33 UTC
I found a major bug with Assassination talent "Overkill", which might be abused to gain an enormous advantage. Basically you can make it last forever, as long as you do not unstealth while having that talent.
How to replicate: 
1. Have a spec with "Overkill" talent in the Assassination tree.
2. Enter Stealth
3. Switch your spec to the one which does not have this talent.
4. Enter Stealth, or Vanish before you lose the buff and stay stealthed for 20 seconds.
After that, it does not matter whether you stealth or not, the buff will last forever until you change your spec and unstealth again or die.

**Comment by Golganeth** [comment] 2015-03-15 19:38
Duplicate of #2006

**Closed by Golganeth** 2015-03-15 19:38 UTC
