### ISSUE TITLE
Vehicle Bug Abuse

### ISSUE THREAD

**Issue by moonsado** [dalaranwow/dalaran-wow#2640] opened 2015-07-11 18:07 UTC
Hello I don't know if this bug has been listed yet but here it is:
*After Wintergrasp is over some bug abuser's are able to control vehicles after and nuke people I have no problem with ganking but I do when it relates to a bug.

Proof (Click on zoom if you can't see the screenshot):
http://tinypic.com/view.php?pic=2exwirq&s=8#.VaFZ6PlViko
http://tinypic.com/view.php?pic=13ympoi&s=8#.VaFZQvlViko
Upper middle section you can see Horde controlled meaning the big fight is over canons are gone and normally vehicles.

**Comment by lmmense** [comment] 2015-07-12 04:55
Does it also count as bug abuse when you go into Strand of the Ancients and stand just outside cannon range on your demolisher? or is it only abuse when you're the victim, Moonsado? )

**Comment by Tarpor** [comment] 2015-07-12 10:16
Does it also count as bug abuse when you spam leave/enter the demolisher in Strand of the Ancients to regain hp? or is it only abuse when you're the victim, Immense? )

**Comment by Vidmantasaf** [comment] 2015-07-12 10:19
doez it also count as abuse when you enter/exit FL vehicles to reset hp ? hueuhuehueuheu

**Comment by moonsado** [comment] 2015-07-12 15:09
Ok, funny thing that you mention it. I never drive why would a warlock drive when he could just burn you as a passanger?.....
Tarpor yeah thats a bug lol but I thought it was already reported?

**Comment by lmmense** [comment] 2015-07-14 12:27
^ rofl, you tell me, you're the one doing it )

Everytime I've exit a Demo, I haven't re-entered, so you tell me Tarpor )

**Comment by moonsado** [comment] 2015-07-14 14:08
To bad you are wrong, coming here and pointing at people with no valid prof and yet that's not even the real problem go make an issue about that bug too instead of distracting people from the real problem here.
*After Wintergrasp is over some bug abuser's are able to control vehicles after and nuke people I have no problem with ganking but I do when it relates to a bug.*

Hope gm's will see this as a real problem and of course the exit vehicle get back in regen hp bug.

**Comment by lmmense** [comment] 2015-07-14 16:25
Doesn't matter. You've just realized that I'm going to screencap it and rub it in your face if you do it again, so I guess that the problem is solved )

**Comment by moonsado** [comment] 2015-07-14 16:40
*After Wintergrasp is over some bug abuser's are able to control vehicles after and nuke people I have no problem with ganking but I do when it relates to a bug.*

**Comment by Rushor** [comment] 2016-12-02 09:27
people are able to build up the vehicles even if wg is not active

i fixed this in https://github.com/dalaranwow/dalaran-wow/issues/3038 /closing

**Closed by Rushor** 2016-12-02 09:27 UTC
Labels: Continent - Northrend, Duplicate / Invalid Report
