### ISSUE TITLE
Cleansing vs deadly poison

### ISSUE THREAD

**Issue by shaxik1** [dalaranwow/dalaran-wow#3898] opened 2016-11-29 10:14 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
Paladins are dispelling every stack of deadly pooson with one dispell
**Current behaviour**: Holy paladins are dispelling with spel Cleansig every stack of deadly poison

**Expected behaviour**: Cleansing should remove maximum one stack of deadly poison 

**Steps to reproduce the problem**:

1. Paladins's cleansing is dispelling every stack of deadly poison instead of one dispell shoul dispell maximum one stack.

2. It is happenenig all the time holy paladin is dispelling. I have tested it with retri paladin and there it work properly. So a think there is a problem in talent "Sacred cleansing".

**Comment by Rushor** [comment] 2016-11-29 10:26
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/2100

**Closed by Rushor** 2016-11-29 10:26 UTC
Labels: Duplicate / Invalid Report
