### ISSUE TITLE
[Quest][Classic] The Book of Ur

### ISSUE THREAD

**Issue by daxpedda** [dalaranwow/dalaran-wow#2230] opened 2015-02-08 01:51 UTC
<ul>
<li>
<b>Issue Present:</b> For the quest <a href="http://wowhead.com/quest=1013">The Book of Ur</a>, you need to loot <a href="http://wowhead.com/item=6283">The Book of Ur</a> of the object <a href="http://wowhead.com/object=36738">The Book of Ur</a> (looks stupid, i know). Everything works fine except that it despawns after looting.
</li>
<hr></hr>
<li>
<b>How it should work:</b> Objects which are parts of quests, do often not despawn after looting, they just stay so others can loot it. It's really not a problem if you are alone, but if multiple people are doing this quest it's really bothering that you need to wait for respawn.
</li>
<hr></hr>
<li>
<b>Proof:</b> For example I found this <a href="https://www.youtube.com/watch?v=k5oT-xPC_E8#t=1038">video</a>, where you can clearly see that he loots a book and it stays where it is, it doesn't despawn, it just stops "glowing".
</li>
</ul>

**Comment by Khronos-** [comment] 2015-08-17 22:13
Hi.

The issue you describe was common behavior during Vanilla, TBC and WotLK.

How you describe "how it should work" was implemented during Cataclysm, as your proof shows.

As far as I know, working as intended on WotLK: Book despawns for 5min until it respawns again. Takes 10mins on dalaran-wow but it's a matter of waiting.

**Comment by daxpedda** [comment] 2015-08-17 22:54
well, i really searched very very long, and i couldn't find proof for wotlk
and i am really not sure how it worked during vanilla and tbc

but, i never played cataclysm, so this behaviour i am talking about must be at least from wotlk

i will search again and hopefully find something ...

**Comment by daxpedda** [comment] 2015-08-17 23:18
i actually found this:
https://youtu.be/_JuI-o360bk?t=587

you see that he loots the cauldron, but because it is a unique object, it doesn't disappear after looting, it just becomes unlootable as long as you have the corresponding quest item in your bag

its actually not easy to see that its still there, but a couple of seconds after that, for example when he turns to get the steps up to the inn, you can see the cauldron for a second

**Comment by Khronos-** [comment] 2015-09-23 08:48
I understand what you are saying but this is not how the Book of Ur behaved during Vanilla, TBC and WotLK.

You had one object that spawned, 1st person looting it would make it disappear and you'd have a respawn timer on the object. People used to complain and race to said object for the base game and said expansions. I can't prove to you that I've played retail WoW extensively until 2nd patch of Pandaria to guarantee you for sure that this is how it works, you will just have to take my word for it I'm afraid.

It was not until the revamp of the Azeroth and dungeons during Cataclysm that the system was changed to the one you exemplify, static object with interaction if you have the quest, which is not really static, has a respawn timer of half a second in reality.

**Comment by daxpedda** [comment] 2015-09-23 08:53
Well, it as you have seen in the video I have posted, it seems that there are Gameobjects which behave like I descriped.

For example I remember very cleary after having played over a year on private servers, I wanted to try out TBC on retail. I started a bloodelf and one of the first things I noticed was that me and my friends never raced for any Gameobjects because they simply didn't despawn.

So, it seems that this system I am describing should be indeed applied to specific Objects, I just don't know which ones.

By the way, you don't have to take my word on this, just watch the video :).

**Comment by Rushor** [comment] 2016-11-26 10:28
DB/Gameobject: The Book of Ur - Reducde Spawntime to 2 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/2230
* commit: 9503474743bf8a21762e4cef8b98f89f522f2914

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 10:28 UTC
Labels: Continent - Classic, Instances, On PTR, Quests
