### ISSUE TITLE
NPC: Kurzen Commando

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#42] opened 2013-07-22 09:38 UTC
NPC Kurzen Commando - 938

Issue: The issue is related with #41 
They are floating above the ground when in stealth and when engaged into combat. 
They are not standing on the solid texture.

**Comment by TheLichWarrior** [comment] 2015-03-16 14:44
o yea change of style haha

**Comment by Rushor** [comment] 2015-03-16 14:50
caused by wrong byte types in creature_(template_)addon.

**Comment by Rushor** [comment] 2016-06-06 16:12
http://i.imgur.com/oEg2p5i.jpg
http://i.imgur.com/xd77qKu.jpg
http://i.imgur.com/Ni6v0jk.jpg

already fixed by tc

**Closed by Rushor** 2016-06-06 16:12 UTC
Labels: NPC
