### ISSUE TITLE
Quest: Saving Sharpbeak

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#174] opened 2013-07-26 23:54 UTC
Saving Sharpbeak, in The Hinterlands, is half working. The quest can be completed perfectly normally, however, upon releasing him from the cage, we should auto mount him and Sharpbeak should fly to Aerie Peak and iirc some dialog should happen, and we can normally turn the quest in.
Working quest, but not perfectly :P

**Comment by Rushor** [comment] 2016-06-07 09:45
http://www.wowhead.com/quest=2994/saving-sharpbeak

**Comment by Rushor** [comment] 2016-06-07 09:48
5418ece90b41b56cd936f0088a6ec6c4d3631c7f
- added the whole event

**Comment by Golganeth** [comment] 2016-06-08 19:44
Throughout the event, Sharpbeak's Father and Mother are attackable by players (they shouldn't). Once Sharpbeak respawns and you try to trigger the event again, the parents won't appear and Sharpbeak will get stuck outside the cage. (probably because of parents respawn timer)

Sometimes Sharpbeak seems to spawn outside the cage, down the hill, which was probably caused by a forced .respawn after event

http://www.wowhead.com/npc=8023/sharpbeak
http://www.wowhead.com/npc=8024/sharpbeaks-father
http://www.wowhead.com/npc=8025/sharpbeaks-mother

**Comment by Rushor** [comment] 2016-06-08 20:39
e730df42fb375b2fe4ad8ebb36403236ac0eb60e
- faction changed for father and mother to be unattackable, the respawnproblem will remain probably :(

**Comment by Golganeth** [comment] 2016-06-09 11:15
The parents are friendly and not attackable anymore. However it seems that after trying the quest more than once (once Sharpbeak has respawned), the parents will not come and Sharpbeak will get stuck looking into the horizon :cry:
 
Because of this issue probably no other player would be able to complete the quest. Poor Sharpbeak

**Comment by Rushor** [comment] 2016-06-09 15:50
yeah the only requirement is to open the cage :/

**Comment by Rushor** [comment] 2016-06-09 15:53
hm Sharpbeak doesn't actually respawn for me :o

**Comment by Golganeth** [comment] 2016-06-09 16:02
The very first time it respawned down the hill for me (around the zone where it disappears with the parents, down on solid ground). Then I killed and respawned it and it was in the cage. Then the stuck thingy happened.

**Comment by Rushor** [comment] 2017-02-04 18:10
respawnissue fixed with https://github.com/dalaranwow/dalaran-wow/issues/4253

**Closed by Rushor** 2017-02-04 18:10 UTC
Labels: Area - Classic, General - Quests
