### ISSUE TITLE
[NPC] Helcular's Revenge - missing script after turn-in

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3875] opened 2016-11-22 14:38 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
After you turn in Helcular's Revenge (2), a quest in Hillsbrad Foothills, nothing happens.
**Expected behaviour**: Tell us what should happen instead
When the quest is returned to Helcular's Grave, Helcular's Remains(Horde friendly) spawn, saying either of the quotes:

>Southshore shall pay in blood!
>Revenge shall be mine at last!
> I have risen!

Upon entering combat will yell:

> "The undead shall feast on your soul, <name>."

He also spawns 3 non-elite skeletons after a few seconds of being aggro'd. If one minion dies, soon enough he spawns 3 more, and so on.  The skeletons then despawn about a minute after combat. 
He walks around his spawn point, never actually entering Southshore.
Overall, when I (accidentally) spawned him, his script seemed to be fine, but he is not spawned and does not roam after the quest is turned in.
Can't find information about his despawn timer if he is not killed : (
**Steps to reproduce the problem**:

1. Complete Helcular's Revenge, 2nd part;
2. Nothing happens.

**Include proofs for this behaviour**
took patch 3.x.x comments:
http://www.wowhead.com/quest=553/deprecated-helculars-revenge#comments:id=638075
http://www.wowhead.com/quest=553/deprecated-helculars-revenge#comments:id=706625
http://www.wowhead.com/quest=553/deprecated-helculars-revenge#comments:id=992498
http://www.wowhead.com/quest=553/deprecated-helculars-revenge#comments:id=1028306
http://www.wowhead.com/quest=553/deprecated-helculars-revenge#comments:id=682543
http://wowwiki.wikia.com/wiki/Helcular's_Remains

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Helcular's Revenge (2)](http://db.vanillagaming.org/?quest=553) quest ID 553
[Helcular's Remains](http://db.vanillagaming.org/?npc=2433) NPC ID 2433

**Comment by Rushor** [comment] 2016-11-22 20:45
http://smg.photobucket.com/user/Skylander/media/World%20Of%20Warcraft/Helculer.png.html

**Comment by Rushor** [comment] 2016-11-22 20:55
DB/Quest: Add spawnevent for Helcular's Revenge

* closes https://github.com/dalaranwow/dalaran-wow/issues/3875
* commit: ca86907a37fc85d13c3f645096cf59a5c34d325a

once you turned in the quest, the creature will spawn and move random around the place. i added a despawntimer of 5 minutes after the spawn

![GitHub Logo](http://i.imgur.com/vxw2h9D.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-22 20:55 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-03-30 11:53
This is probably not on the ptr, did the quest with horde character> turned on the stone > nothing happened.
Tried again with alliance character > did the quest> could NOT turn it on the stone as i wasn't able to click on it.
![image](https://cloud.githubusercontent.com/assets/6797611/24502938/a40d393c-1558-11e7-918b-6a23e7daaebb.png)

**Comment by Rushor** [comment] 2017-03-30 12:20
yep it's missing then. sadly i cannot control which fix is on ptr and which isn't - depends all on loth. When i pushed those fixes in trello it was marked as "on ptr" so i don't know what happend to the fix. will change the lable

**Comment by TeridanDW** [comment] 2017-03-30 13:00
That's ok, we will correct the labels, no worries.
