### ISSUE TITLE
[NPC] Gravis Slipknot

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#991] opened 2013-12-05 13:29 UTC
http://www.wowhead.com/npc=14221

Rare guy which hangs out in Strahnbrad, currently has his model missing, can't be looted after death and can be killed by AoE abilities\auras only.

![wowscrnshot_120513_151930](https://f.cloud.github.com/assets/5235996/1682746/044400e6-5db1-11e3-93c0-b71b8cb68e13.jpg)

Also, upon engaging he should say the following line: "Greetings hapless adventurer. I ask only that you wait a moment...and BLEED!", which he currently doesn't.

Best wishes.

**Comment by Rushor** [comment] 2016-11-12 18:25
DB/Creature: Gravis Slipknot

* update model
* Add combattext
* Add waypoints
* closes https://github.com/dalaranwow/dalaran-wow/issues/991
* commit: 8f0bf752cabbeab511a117fd0c3f4de6415d9c9f

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 15:24
Hello, everything reported here works as intended on ptr, however i would like to add:
 - update his position as he spawns inside the house but his first wp is far behind the house, so he walks all the way around to get to him.
``` sql
UPDATE `creature` SET `position_x` = 710.176 , `position_y` = -847.229 , `position_z` = 158.977 WHERE `guid` = 86756; 
```
 - he is missing his only combat spell:
``` sql
-- Gravis Slipknot SAI
SET @ENTRY := 14221;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,7,0,0,0,0,0,0,0,"Gravis Slipknot - Between 0-15% Health - Flee For Assist"),
(@ENTRY,0,1,0,0,0,100,0,3000,5000,7000,9000,11,18501,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gravis Slipknot - In Combat - Cast 'Enrage'");
```
and push for live.

**Closed** 2018-03-23 22:40 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update
