### ISSUE TITLE
Rogue; Envenom

### ISSUE THREAD

**Issue by IlijaOs** [dalaranwow/dalaran-wow#824] opened 2013-09-25 15:36 UTC
Once rogues use Envenom, we get buff incereasing chance to apply Instant Posion and Deadly Posion. That buff gets removed from rogues by friendly paladins cleansing or cleansing totem of shamans. That shouldn't be happening and it affects assassination rogues DPS in raids or RDF dungeons a lot. Please take look into this.

**Comment by saltylopez** [comment] 2016-06-14 12:20
A rogue in our raid was complaining about this still being an issue last night.  Cleansing totem was clearing their buff or something.

**Comment by Rushor** [comment] 2016-11-29 18:31
Game/Spells: Make envenom none dispelable

* closes https://github.com/dalaranwow/dalaran-wow/issues/824
* commit: f13dd218ac52701e5c07d22324d68b98bd93fbb2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 18:31 UTC
Labels: Class - Rogue, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-20 08:42
Works as intended on PTR.
