### ISSUE TITLE
[DK] Spell: Death Grip

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#326] opened 2013-08-04 13:40 UTC
http://www.wowhead.com/spell=49576
When you deathgrip someone that is casting a spell it doesnt interrupt the spell

**Comment by Golganeth** [comment] 2015-01-07 14:07
#2158 - Death Grip doesn't have a minimum range.
> http://www.wowwiki.com/Death_Grip
> Patch 3.3.3 (2010-03-23): Minimum range has been changed to 8 yards in PvP.

**Comment by Golganeth** [comment] 2015-01-07 14:14
#1595 - Sometimes Death Grip animation happens but the target doesn't get pulled. It seems to happen mostly when the caster and the target go out of LoS of each other as soon as the spell is used (has to happen quick). Possibly related to texture pathing issues #1447

**Comment by Crispybuilt** [comment] 2015-07-29 18:22
This might have to be corrected again, it got broken with some recent update. Trajectory and pulling speed must be fixed

**Comment by Golganeth** [comment] 2016-06-16 18:37
Pulling still feels a bit too slow.

**Comment by Golganeth** [comment] 2016-06-23 11:47
After the update still feels slow, check vid for reference, test at max. distance

**Comment by MrAndersonX** [comment] 2016-10-26 13:34
Sometimes Death Grip encounters a problem I've also had with Charge. Instead of pulling the target in front of you, it pulls it behind your or sometimes even sideways. It's really irritating.

**Comment by Rushor** [comment] 2016-12-04 13:19
Game/Spells: DK - Death Grip - Increase speed to 20.0f

* closes https://github.com/dalaranwow/dalaran-wow/issues/326
* commit: da326ed316838f2bc7e15a8a3ea8a1a698d0f319

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-10-21 10:01
Hello, everything mentioned above works as intended on PTR with the exception of:

> -Death grip will not be castable on rooted targets.

![image](https://user-images.githubusercontent.com/6797611/31850722-fb3e7560-b65f-11e7-8794-11e08f3ccb1e.png)

**Comment by robinsch** [comment] 2017-12-20 21:16
Someone have a proof of not being able to grip rooted targets?

**Closed** 2018-01-03 12:38 UTC
Labels: Class - Death Knight, Fixed - On Live Server, Not working/incomplete fix
