### ISSUE TITLE
Warlock quest for voidwalker doesn't exist

### ISSUE THREAD

**Issue by Sariix** [dalaranwow/dalaran-wow#5538] opened 2018-07-06 16:57 UTC
I am level 16, the quest to lead up to getting to the voidwalker, Gakin's Summons, does not appear at the NPC who is supposed to have it, Remon Marcot. Note that I have completed all the other warlock quests possible at this point, and the level requirement is only 10, so I am unsure of why this quest does not exist for me. Possibly just a personal issue? Still unsure how to fix it.

**Comment by Golganeth** [comment] 2018-08-19 16:17
Can't reproduce. Please make sure that you have completed all the pre-quests as well as the quests enabling the chain. Also check the proper NPCs according to your race and activate the option "Low Level Quests" on your minimap.

If the issue persists please make an in-game ticket.
Closing.

**Closed by Golganeth** 2018-08-19 16:17 UTC
