### ISSUE TITLE
Major Combat Bug and Error Placement

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2289] opened 2015-03-11 13:07 UTC
Hello server is so fine and good for now i see only one major problem with the Monster's of World of Warcraft or so called mob's.The Problem is when you atack 2 or more at same time the models got stuck in same place or in half half in front of the Player.Its annoying to see them like thet in such good game.My Idea is to place scripts in the models to try the mob's to search a free reserved place around the Player when they start atacking the player and like 1 2 3 monsters to be placed one on the left one in front one in the right side thets it.The work to be done will be hard and long please fix thet major problem server will be best if you implement thouse scripts Good Luck.

**Comment by Golganeth** [comment] 2015-03-11 20:54
Duplicate of #1204

**Closed by Golganeth** 2015-03-11 20:54 UTC
