### ISSUE TITLE
[Quest][NPC] The Defias Traitor

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2579] opened 2015-06-29 23:20 UTC
The Defias Traitor NPC is currently standing in the middle of Moonbrook instead of Sentinel Hill, and he does not offer his quest to eligible players.

Correction. Later, I did find him in Sentinel Hill, so I began his quest. Now, he's standing in the middle of Moonbrook, refusing to go any further to completion.

**Comment by InvincibleEagle** [comment] 2015-06-30 00:54
Correction. Later, I did find him in Sentinel Hill, so I began his quest. Now, he's standing in the middle of Moonbrook, refusing to go any further to completion.

**Comment by Sagrath** [comment] 2015-07-02 12:45
quest works as intended, just tested.

**Comment by dykenugget** [comment] 2015-09-11 16:31
Quest is bugged.

**Comment by Golganeth** [comment] 2015-09-12 14:25
Confirmed.

#2877 - 
> If someone fails to escort the Traitor, the Traitor gets bugged in moonbrook and becomes completely unkillable and bugs in Moonbrook (...)

**Comment by Rushor** [comment] 2016-06-11 08:52
Description: This is the 6th quest in the Defias Brotherhood quest chain, where the Defias Traitor should be at the bottom of the of the steps underneath Sentinel Tower in Westfall. When someone is currently doing the escort quest, it is unavailable, however, no one is doing the quest. I have run multiple times from Moonbrook to Sentinel Tower, camped out in front of his spawn point for hours, and asked in general chat as well. He seems permanently despawned at the moment, preventing anyone from doing the quest or the final quest in the Defias Brotherhood chain of killing Van Cleef in the Deadmines.

Current behaviour: Westfall, bottom of Sentinel Tower, permanently despawned Defias Traitor.

Expected behaviour: He should spawn and allow people to complete the quest.

Steps to reproduce the problem: Just go and see that he is not there, and that waiting for hours does not spawn him, even when you are at that point in the quest chain.

http://wotlk.openwow.com/npc=467
http://www.wowhead.com/npc=467/the-defias-traitor#screenshots:id=9918

**Comment by Rushor** [comment] 2016-11-17 20:57
DB/Creature: The Defias Traitor - Must be active

* closes https://github.com/dalaranwow/dalaran-wow/issues/2579
* commit: 4c9c63b4cc31aea1b779df7f9c398e1d7366cabd

The creature was set to active. This means that the script should no longer stuck, if the escortplayer leaves the area of the creature.

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-24 09:10
Regadring:

> i couldn't fix the "$n" part of the Traitor's speech on aggro - he seems to say the speech before taking the target (setting him to aggresive will mostlikely fix this issue, but is wrong, he should be on deffensive)

added a hack fix:
Changed `$n` with `Enemy`, so the behaviour of the npc stays correct.
Updated the code above.

**Comment by Rushor** [comment] 2017-07-04 13:19
alright i'm going to fix the $n part

**Comment by Rushor** [comment] 2017-07-04 13:26
Scripts/Quest: The Defias Traitor - several escortupdates

* set respawn timer of the Traitor to 30s
* added timing and correct targets on his speeches
* quest credit is now given on all party members upon completing the quest
* enable correct display of victim name in the aggrotext
* updates: https://github.com/dalaranwow/dalaran-wow/issues/2579
* commit: 1b851e4284eb4988e69c99742b0419a2f6bce367

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-10-24 11:14
After a fast test on PTR this:

> - enable correct display of victim name in the aggrotext

Doesn't seems to work.

 - The Defias Traitor doesn't attack back when attacked, he just stays still.

![wowscrnshot_102417_141247](https://user-images.githubusercontent.com/6797611/31940076-8ad4cfc8-b8c5-11e7-85b3-c38020f8468e.jpg)

Everything else works properly.

**Closed** 2017-11-05 16:20 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update, General - Quests, Works - but it needs improvements.
