### ISSUE TITLE
[Quest][Classic] Tome of Valor

### ISSUE THREAD

**Issue by cranstonen** [dalaranwow/dalaran-wow#3628] opened 2016-08-01 15:55 UTC
I got the quest from Duthorian and went to Westfall to Daphne Stillwell. There was no way to talk to her/turn in quest so as to have the waves start spawning. I logged out nothing changed. Waited for 15 mins, but still the same. In the end GM completed the quest for me.

**Comment by Enimorf** [comment] 2016-08-27 13:31
Its bugged.. i try to do ( im paladin lvl 20 ) and 2 ataks only happen.. W8 and w8.. and no more ataks anda can talk again whit Daphne :/ Please.. I aborted the quest 2 times.. but, not work do again..

Sorry my bad english :(

**Comment by Edzero** [comment] 2016-11-13 21:07
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Edzero** 2016-11-13 21:07 UTC
Labels: Class - Paladin, Continent - Classic, Priority - High, Quests

**Comment by TeridanDW** [comment] 2017-03-31 18:36
Works as intended on ptr.
