### ISSUE TITLE
ToGC 10 Anub Nerubian Borrower Damage calculation with block

### ISSUE THREAD

**Issue by fsironman** [dalaranwow/dalaran-wow#2993] opened 2015-11-10 10:44 UTC
On this server the tank takes way too much dmg despite having a ridiculous high block value from optimized gear.

I think the problem is that the formula for dmg calculation is applied false:

> (3000 - 2200) \* (100% + 25% \* 9)
> = (800) \* (100% + 225%)
> = 800 \* 325%
> = 2,600 per hit.

However it seems to be applied like following:

(3000 \* (100% + 25% \* 9))  - 2200
= 3000 \* (100% + 225%) - 2200
= 3000 \* 325% - 2200
= 9750 - 2200
= 7550 per hit.

this is almost triple the amount of damage the tank would normally take.
### Explanation how it should be

The Following is from: http://www.wowhead.com/npc=34564/anubarak#comments:id=860736

> A block tank with 102.4% unhittable can tank 2 or 4 adds quite comfortably. 
> [...]
> However, Anub'arak's adds don't melee for a ton straight up - it goes through a formula. At the base, they melee for around 3000, but their Expose Weakness increases that damage by quite a bit. Expose Weakness stacks up to 9 times on the tank, and increases damage by 25% per application.
> 
> The trick here is the math. Block Value is applied to the melee hit before it's increased by Expose Weakness. The formula looks like this:
> 
> (Damage - Block Value) \* (100% + 25% \* Expose Weakness stacks)
> - where 100% represents the value of the original hit
> - 25% is the amount that the hit is increased by
> 
> Let's assume the tank has a Block Value of 2200.
> 
> Following the formula, an unblocked hit on a tank with 9 Expose Weakness stacks looks like this:
> (3000) \* (100% + 25% \* 9)
> = (3000) \* (100% + 225%)
> = 3000 \* 325%
> = 10,500 per hit.
> 
> Typical raid tanks will avoid maybe 50%-60% of those hits, but the rest of those hits are going through at full power. With 2 to 4 hasted adds, that tank is going down sooner than later and won't be healable, especially thanks to the haste effect of Spider Frenzy the adds give to each other.
> [...]
> Now if the tank is at 102.4% unhittable assuring them of a complete miss or a block, the math for a block looks like this:
> (3000 - 2200) \* (100% + 25% \* 9)
> = (800) \* (100% + 225%)
> = 800 \* 325%
> = 2,600 per hit.
> [...]
### Examples from Retail

Here are two examples from WoL 11.09.2009 prenerf where you could get even 10 stacks of Expose Weakness.
http://www.worldoflogs.com/reports/nKLYEsrjU0Y7lDp3/log/?s=7286&e=7674 

[20:36:53.763]  Nerubian Burrower hits Boyfriend 2572
[20:36:54.628] Boyfriend afflicted by Expose Weakness from  Nerubian Burrower
[20:36:56.050]  Nerubian Burrower hits Boyfriend Parry
[20:36:57.828] Nerubian Burrower hits Boyfriend Parry
[20:36:58.954] Nerubian Burrower hits Boyfriend 1338 (B: 1460)
[20:36:59.853] Nerubian Burrower hits Boyfriend 3327
[20:36:59.871] Boyfriend afflicted by Expose Weakness (2) from  Nerubian Burrower
[20:37:00.654] Boyfriend afflicted by Expose Weakness (3) from  Nerubian Burrower
[20:37:00.879] Nerubian Burrower hits Boyfriend 4188
[20:37:01.061]  Nerubian Burrower hits Boyfriend 4365
[20:37:01.850] Nerubian Burrower hits Boyfriend Dodge
[20:37:01.858] Boyfriend afflicted by Expose Weakness (4) from  Nerubian Burrower
[20:37:02.300] Boyfriend afflicted by Expose Weakness (5) from  Nerubian Burrower
[20:37:02.300]  Nerubian Burrower hits Boyfriend 5371
[20:37:02.922] Nerubian Burrower hits Boyfriend Parry
[20:37:03.455] Boyfriend afflicted by Expose Weakness (6) from  Nerubian Burrower
[20:37:03.473]  Nerubian Burrower hits Boyfriend Dodge
[20:37:04.120] Nerubian Burrower hits Boyfriend 2157 (B: 1460)
[20:37:04.680]  Nerubian Burrower hits Boyfriend 2864 (B: 1460)
[20:37:05.071] Boyfriend afflicted by Expose Weakness (7) from  Nerubian Burrower
[20:37:05.433] Nerubian Burrower hits Boyfriend 4236 (B: 1460)
[20:37:05.859] Boyfriend afflicted by Expose Weakness (8) from  Nerubian Burrower
[20:37:06.291] Boyfriend afflicted by Expose Weakness (9) from  Nerubian Burrower
[20:37:06.495] Nerubian Burrower hits Boyfriend **2612** (B: **1460**)
[20:37:07.472] Boyfriend afflicted by Expose Weakness (10) from  Nerubian Burrower

And here the 2nd example:

http://www.worldoflogs.com/reports/JsCgbdzjmRtYRsUI/log/?s=6285&e=6554

this time I included only actual hits:

[20:47:46.533] Nerubian Burrower's Expose Weakness fades from Ktorrk
[20:48:09.093] Nerubian Burrower hits Ktorrk 1390 (B: 1778)
[20:48:09.150] Nerubian Burrower hits Ktorrk 2553
[20:48:10.215] Ktorrk afflicted by Expose Weakness from Nerubian Burrower
[20:48:10.241] Ktorrk afflicted by Expose Weakness (2) from Nerubian Burrower
[20:48:10.303] Nerubian Burrower hits Ktorrk 2442 (B: 1778)
[20:48:11.376] Nerubian Burrower hits Ktorrk 3906
[20:48:11.441] Ktorrk afflicted by Expose Weakness (3) from Nerubian Burrower
[20:48:11.441] Nerubian Burrower gains Spider Frenzy from Nerubian Burrower
[20:48:11.534] Nerubian Burrower hits Berengar 3857
[20:48:12.043] Nerubian Burrower hits Ktorrk 5316
[20:48:12.243] Ktorrk afflicted by Expose Weakness (4) from Nerubian Burrower
[20:48:12.654] Nerubian Burrower hits Ktorrk Block (3377)
[20:48:13.013] Ktorrk afflicted by Expose Weakness (5) from Nerubian Burrower
[20:48:13.840] Ktorrk afflicted by Expose Weakness (6) from Nerubian Burrower
[20:48:17.420] Nerubian Burrower hits Ktorrk 2979
[20:48:18.245] Ktorrk afflicted by Expose Weakness (7) from Nerubian Burrower
[20:48:18.577] Nerubian Burrower hits Ktorrk 1340 (B: 1778)
[20:48:18.684] Nerubian Burrower hits Ktorrk 1215 (B: 1778)
[20:48:19.472] Ktorrk afflicted by Expose Weakness (8) from Nerubian Burrower
[20:48:19.847] Ktorrk afflicted by Expose Weakness (9) from Nerubian Burrower
[20:48:19.877] Nerubian Burrower hits Ktorrk Block (2636)
[20:48:20.926] Nerubian Burrower hits Ktorrk 3557
[20:48:21.048] Ktorrk afflicted by Expose Weakness (10) from Nerubian Burrower
[20:48:21.092] Nerubian Burrower hits Ktorrk **4363**
[20:48:21.560] Nerubian Burrower hits Ktorrk **298** (B: **2921**)
[20:48:21.711] Nerubian Burrower hits Ktorrk **166** (B: **2921**)
[20:48:21.848] Ktorrk's Expose Weakness is refreshed by Nerubian Burrower
### Example from dalaran-wow

also excluding non hits

[21:11:57.707] Nerubian Burrower's Expose Weakness fades from Horvi

[21:12:00.175] Nerubian Burrower hits Horvi 298 (B: 3455)
[21:12:00.175] Nerubian Burrower hits Horvi Absorb (604)
[21:12:00.182] Horvi afflicted by Expose Weakness from Nerubian Burrower
[21:12:01.495] Nerubian Burrower hits Horvi 476 (A: 1186, B: 3455)
[21:12:01.495] Nerubian Burrower hits Horvi 1349 (B: 3455)
[21:12:01.514] Horvi afflicted by Expose Weakness (4) from Nerubian Burrower
[21:12:02.916] Nerubian Burrower hits Horvi 2308 (B: 3455)
[21:12:02.916] Nerubian Burrower hits Horvi 2942 (B: 3455)
[21:12:02.916] Horvi afflicted by Expose Weakness (6) from Nerubian Burrower
[21:12:04.176] Nerubian Burrower hits Horvi 5313 (B: 3455)
[21:12:04.191] Horvi afflicted by Expose Weakness (7) from Nerubian Burrower
[21:12:05.471] Nerubian Burrower hits Horvi 7250 (B: 3455)
[21:12:05.491] Horvi afflicted by Expose Weakness (8) from Nerubian Burrower
[21:12:08.097] Nerubian Burrower hits Horvi 6911 (B: 3455)
[21:12:08.125] Horvi afflicted by Expose Weakness (9) from Nerubian Burrower
[21:12:10.715] Nerubian Burrower hits Horvi 6539 (A: 1790, B: 3455)
[21:12:10.715] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:11.995] Nerubian Burrower hits Horvi 7897 (B: 3455)
[21:12:12.011] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:14.803] Nerubian Burrower hits Horvi 7939 (B: 3455)
[21:12:14.803] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:16.079] Nerubian Burrower hits Horvi 4613 (A: 1790, B: 3455)
[21:12:16.111] Nerubian Burrower hits Horvi 5778 (B: 3455)
[21:12:16.111] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:18.817] Nerubian Burrower hits Horvi 8123 (B: 3455)
[21:12:18.846] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:23.434] Nerubian Burrower hits Horvi 8645 (B: 3455)
[21:12:23.450] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:30.919] Nerubian Burrower hits  Horvi 11819 (A: 1790)
[21:12:30.919]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:32.667] Nerubian Burrower hits  Horvi 5861 (B: 3455)
[21:12:32.667]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:36.591] Nerubian Burrower hits  Horvi 6101 (B: 3455)
[21:12:36.593]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:40.419] Nerubian Burrower hits  Horvi 7787 (B: 3455)
[21:12:40.435]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:40.844] Nerubian Burrower hits  Horvi 9104 (B: 3455)
[21:12:40.852]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:41.421] Nerubian Burrower hits  Horvi 7430 (A: 25, B: 3455)
[21:12:41.432]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:41.859] Nerubian Burrower hits  Horvi 6469 (A: 1617, B: 3455)
[21:12:41.876]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:42.678] Nerubian Burrower hits  Horvi 2689 (A: 672, B: 3455)
[21:12:42.678]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:44.472] Nerubian Burrower hits  Horvi 2026 (B: 3455)
[21:12:44.493]  Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:49.988] Nerubian Burrower hits Horvi 3021 (B: 3455)
[21:12:49.994] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:50.825] Nerubian Burrower hits Horvi 1690 (B: 3455)
[21:12:50.836] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:52.100] Nerubian Burrower hits Horvi 2702 (B: 3455)
[21:12:52.100] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:52.517] Nerubian Burrower hits Horvi 1592 (B: 3455)
[21:12:52.521] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:53.723] Nerubian Burrower hits Horvi 2744 (B: 3455)
[21:12:53.740] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:54.739] Nerubian Burrower hits Horvi 6023 (B: 3455)
[21:12:54.752] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:57.187] Nerubian Burrower hits Horvi 6906 (B: 3455)
[21:12:57.202] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:57.403] Nerubian Burrower hits Horvi 5669 (B: 3455)
[21:12:57.431] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:58.489] Nerubian Burrower hits Horvi 5691 (B: 3455)
[21:12:58.512] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:12:58.720] Nerubian Burrower hits Horvi **5552** (B: **3455**)
[21:12:58.729] Horvi's Expose Weakness is refreshed by Nerubian Burrower
[21:13:01.249] Nerubian Burrower hits Horvi **5316** (B:**3455**)
### DMG calculation how it should be:

so even after we consider the increased dmg on this server to make up for 3.3.5 path the tank takes about 300 dmg per hit: Nerubian Burrower hits Horvi 298 (B: 3455)

so lets assume they hit for 3455 + 300 = 3755 and apply the formula:

> (3755 - 3455) \* (100% + 25% \* 9)
> = (300) \* (100% + 225%)
> = 300 \* 325%
> = 975 per hit.

But in the log we see hits up to 6000 dmg

**Comment by Winstrol** [comment] 2015-11-10 12:43
Would also like to add that the burrowers seems to have to small hitbox

**Comment by hAkonf** [comment] 2015-11-10 15:37
[22:40:16.326] Nerubian Burrower hits Autismo 1751 (B: 12516)
Can confirm, hits very hard.

**Comment by Vepar90** [comment] 2015-11-10 15:38
Other than that 1 Comment in Wowhead i cant find any confirmation that it is  supposed to work like that.  ((base dmg - block ) * expose weakness)
I was under the Impression that The reason u Get block is so u Don't ever get a hit from them Avoiding getting stacks all together.

Either way The boss is Killable as is!!!

**Comment by hAkonf** [comment] 2015-11-10 15:40
Check the logs from live linked in first post. They prove it.

**Comment by fsironman** [comment] 2015-11-10 15:50
> They prove it.

To be fair they don't prove __exactly__ the formula i posted but they prove that the damage is way over the top.

> Either way The boss is Killable as is!!!

That the boss is indeed easy killable does not mean we don't have an Issue here and is therefore totally irrelevant.

**Comment by Vepar90** [comment] 2015-11-10 16:11
When was that Log Taken?

**Comment by fsironman** [comment] 2015-11-10 16:13
> When was that Log Taken?
09.11.2015 Around 21:00 CEST

**Comment by ntt1** [comment] 2015-11-18 20:24
It makes it harder but not unkillable. Since we already coped with it on 25 heroic, I suggest not fixing it until at least all realm firsts are taken (insanity/immortality 25), so it doesnt affect the race.

**Comment by hAkonf** [comment] 2015-11-18 22:07
The race you speak of doesn't exist, and even if it did, fixing it at the start of a reset would still make it fair.

**Comment by Mike-Hunt** [comment] 2016-08-01 04:37
Now that all realm firsts have been taken for some time, can this be looked at?

**Comment by fsironman** [comment] 2016-08-01 07:18
Realm First or not does not matter at all this is a severe bug and should have been looked at **half a year ago**!

Just for the record: The same issue persists in To(G)C25 aswell.

This bug is especially frustrating for new players trying to progress as you need difficult to obtain gear from all over the place whereas on Retail some block gear here and there made you tank this easy.

**Comment by Rushor** [comment] 2016-11-17 18:10
Instance/ToC: Anub'arak -  Expose Weakness - apply SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT

* closes https://github.com/dalaranwow/dalaran-wow/issues/2993
* commit: 7c892bb85d96e34615609895472ac16803be87dc
* added a workaround, so if you get one stack of spell 67721 or 67847, you will get SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT with 39 %. The damage will be much lower then.

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 18:10 UTC
Labels: Continent - Northrend, Instances, On PTR

**Comment by tripleslash** [comment] 2017-02-12 14:28
Why aren't you fixing the formula for dmg mitigation instead of hackfixing that shit with a buff to your block value? dafuk

**Comment by Rushor** [comment] 2017-02-12 20:50
it's a workaround because the calculation is very sensitive, i will not break anything else for that one issue

**Comment by TeridanDW** [comment] 2017-04-06 11:21
> added a workaround, so if you get one stack of spell 67721 or 67847, you will get SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT with 39 %. The damage will be much lower then.

Workaround tested and works as intended on ptr.
Note: Player gets 39% blockvalue on **_each_** stack of spell 67721 or 67847 (depending on the difficulty)
Example:
0 stacks of spell 67721 or 67847
player's block value = 566

9 stacks of 67721 or 67847
player's block value = 2557

![image](https://cloud.githubusercontent.com/assets/6797611/24751925/2ae7549e-1ad4-11e7-83a6-6f96be74549f.png)
