### ISSUE TITLE
Quest: Heated Battle

### ISSUE THREAD

**Issue by untitledlives** [dalaranwow/dalaran-wow#669] opened 2013-08-21 06:00 UTC
the quest doesn't function as it supposed to

the mobs should spawn at an almost constant rate and you should just have to tag the mob to get credit

instead you have the wait the full spawn timer and the the npc's steal your kills

Also the abom's won't walk up the hill 

the npcs are suppose to help you kill the abom by tanking him and such.

**Comment by GCatalinStefan** [comment] 2015-01-20 15:52
Bump!

Horde side problem still persists:
Long respawn timers (5 mins) and no tag credit for the killed mobs.

**Comment by Klala** [comment] 2015-06-24 14:55
Yes, there is a 5 min respawn time on Frigid Geist Attacker.
Even though the npcs are stealing the credit for the kill I still managed to do it. All I had to do was to deal enough damage before they do. You need to do at least ~65% hp damage to the target to get credit for the kill. But I am a rogue, my burst is fast and massive. Other classes are not so lucky so...

**Comment by darkwulfv** [comment] 2015-06-24 22:36
Quest is still basically impossible Horde side; Frigid Ghoul Attackers spawn frequently but are immediately tagged by NPCs and torn apart before enough damage can be done to consider them "tagged". Aboms can be solo'd if you're able to self-heal (ie: paladins), and you can go to the Alliance side and pull 2 Frigid Geists every few minutes, but getting the Attackers is almost impossible.

**Comment by Vaxsysl** [comment] 2015-06-24 22:51
While it is bugged, you can actually complete it with many re-visits while you're doing other quest and coming close by, or after you complete a quest hub. Key is that Alliance side. You can help yourself with ensuring they are killed last so they spawn last, and camp the area. It's how I did it. Quite a hustle, but...doable. Very annoying problem.

**Comment by nowonshere** [comment] 2015-07-04 17:33
This quest is still not working, even at the Alliance side as the NPCs will tag the quest mobs & won't give you credit.

**Comment by Khronos-** [comment] 2015-08-03 06:42
Confirmed, NPCs stealing credit from the kill.

Only 2 Geists spawn in locations that can be killed without getting a kill steal from NPC (49,51). Respawn timer is 5 mins.

Everywhere else you need to be lucky and grab a ghould from a couple that are attacking 1 single NPC and is not tagged.

So far, 45 mins have passed and I still have 4 Geists to kill.

**Comment by zr00130** [comment] 2015-10-17 20:13
While it's less than ideal to get quest counts as mentioned by plenty of others, there is a sweet spot on the alliance side at 51,48. 

Here a few Frigid Geist Attackers spawn with no Alliance NPCs. The Frigid Ghoul Attackers spawn on the cliffs and should only have one alliance NPC attacking them allowing for an easier time to do more than 50% damage for the count.

**Comment by poprs** [comment] 2015-12-17 21:24
still not work

**Comment by alphaest** [comment] 2016-03-25 16:36
Shamans can go to the ledge with two guards at 52 51 and use a fire elemental to pull the Ghouls faster than npcs. Anywhere else they will engage the dragons and be killed.

**Comment by rinleezwins** [comment] 2016-04-22 15:44
Ghouls: I went to the side where one guard was standing and just waited for one ghoul to respawn constantly, took like 2 minutes.
Geists: Went to the alliance side and kept picking up the 2 geists that respawn down the ramp, close to the grass. That took quite a while, but hey it's "doable". You 're just gonna get a lot of your time wasted.

**Comment by jonanone** [comment] 2016-05-27 17:11
Ghouls, geists and the abomination now grant kill credit more easily. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment] 2016-06-04 21:44
Works great. Credit is granted for all kind of NPCs as long as you deal some moderate amount of damage (even 5-10% will work)

Needs some polishing on abos behavior when lured too far of respawning spots and guards not attacking them though.

**Comment by Golganeth** [comment] 2016-06-04 21:58
Works great. Credit is granted for all kind of NPCs as long as you deal some moderate amount of damage (even 5-10% will work)

Needs some polishing on abos behavior when lured too far of respawning spots and guards not attacking them though.

> Minor issue

**Comment by Golganeth** [comment] 2016-06-19 19:02
Besides issues described above, it seems Frigid Geist Attackers are lacking/have a long respawn timer (especially on Horde area). Only Ghouls seem to be spawning at the moment, and very rarely a Geist.

**Comment by Freshshaven** [comment] 2016-08-02 15:06
Yeah, Geists take forever to respawn and still yet to see an Abom walk up the pathways.

**Comment by Rushor** [comment] 2016-11-24 17:41
http://wotlk.openwow.com/quest=12416
http://wotlk.openwow.com/quest=12448

**Comment by Rushor** [comment] 2016-11-24 20:01
DB/Quest: Heated Battle - Add periodic spawnevent for Frigid Geist Attacker and Frigid Abomination and add selfheal for Alliance Conscript and Horde Conscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/669

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 20:01 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by ASDFGH457** [comment] 2020-07-04 00:26
The Ghouls dont show up??

**Comment by EL100** [comment] 2021-02-11 01:05
+1 The Ghouls don't spawn at all. I waited for many waves. Even tried to drop and retake the quest. I've watched several cycles of the spawns and no ghouls.
