### ISSUE TITLE
[NPC] Peon Garka

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2413] opened 2015-05-22 01:39 UTC
Peon Garka, an Inkeeper in The Storm Peaks, doesn't allow the option to put HS location there.

http://www.wowhead.com/npc=29944/peon-gakra

**Comment by Rushor** [comment] 2016-11-17 19:34
source http://www.wowhead.com/npc=29944/peon-gakra#comments:id=556147

**Comment by Rushor** [comment] 2016-11-17 19:42
DB/Creature: Peon Garka - Add innkeeperflag

* closes https://github.com/dalaranwow/dalaran-wow/issues/2413
* commit: 333cf9203a4234101c20884e032acab72eb35f2a

![GitHub Logo](http://i.imgur.com/19QiYzA.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 19:42 UTC
Labels: Continent - Northrend, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 13:18
Works as intended on ptr.
