### ISSUE TITLE
[Druid] Typhoon Delay

### ISSUE THREAD

**Issue by obryss** [dalaranwow/dalaran-wow#2617] opened 2015-07-08 08:13 UTC
The Typhoon have a huge delay after u cast it u can't interrupt any cast or anything Is really annoying can u fix it?It should hit almost instantly not after 3+secs. Is a must in pvp for a boomkin

**Comment by Milton3450** [comment] 2015-09-17 20:23
Any news on this?

**Comment by Rushor** [comment] 2016-12-02 11:33
reduced the delay of the spell a bit.

i would like to note, that even on retail there were several typhoon bugs, so that behaviour seems to be blizzlike

http://eu.battle.net/wow/en/forum/topic/1302977401
http://us.battle.net/wow/en/forum/topic/2456477631
http://www.mmo-champion.com/threads/684217-Typhoon-bug-with-3-3

Game/Spells: Druid - Update traveltime for Typhoon

* closes https://github.com/dalaranwow/dalaran-wow/issues/2617
* commit: 31fdefbf5f3f5c399276053f3012fdb3a784b234

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-02 11:33 UTC
Labels: Class - Druid, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-23 08:30
Works as intended on PTR.

However I would like to ask if it is possible something to be done for:

> Since 3.3 if had broblems with Typhoon. Most of the time, thou i can see the effects of the spell, **i cant see the animation**. I have run the repair tool. Still bugging.

as most of the casts simply are missing the animation for me too.
