### ISSUE TITLE
[ToC] Combat Bug

### ISSUE THREAD

**Issue by fsironman** [dalaranwow/dalaran-wow#3627] opened 2016-08-01 08:03 UTC
**Description**:
Defeat the Twin Valkyrs on any mode / difficulty and start the Lich King roleplay.
As soon as the floor breaks the whole raid is put into combat indefinitely.

**Expected behaviour**: Tell us what should happen instead
You should not be in combat.

**Steps to reproduce the problem**:
1. Do the Instance for 9 months

**Include Screenshots from the issue if necessary**
https://www.youtube.com/watch?v=HA0Y2zfK4ho
As a Workaround all but one player leave the instance.
I position myself behind the gate so i wont fall down.
At 00:19 you can see +Combat popping up.
Soon after I leave to get out of Combat and go in again so nobody is in Combat.

**Comment by Rushor** [comment] 2016-11-17 17:53
Scripts/TrialOfTheCrusader: Stop combat at the end of the Lichking Roleplayevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/3627
* commit: 91df9ac1f135bd554324f31aa2dc8f0bc8967945

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 17:53 UTC
Labels: Continent - Northrend, Instances, On PTR

**Comment by TeridanDW** [comment] 2017-03-31 18:42
The commit for this bug is in issue #4518, closing this on as:

**Comment by Rushor** [comment] 2018-06-05 09:08
Already on PTR.

**Comment by Chenocide** [comment] 2018-06-05 11:13
It's fixed on live too.
