### ISSUE TITLE
[Warrior] Glyph of Sunder Armor applies 4 stacks instead of 2

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4235] opened 2017-01-15 10:29 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently if you use the Sunder Armor glyph, you can apply 4 sunders in 1 cast (2 per mob).

**Expected behaviour**: Tell us what should happen instead
You should only be able to get 2 sunders per cast (1 per mob).

**Steps to reproduce the problem**:
1. Use sunder armor glyph
2. Find 2 mobs, get them to stand close to each other.
3. Use sunder armor on one, and see that you get 2 stacks on both from only 1 cast.

**Include proofs for this behaviour**
http://i.imgur.com/VqCBEGD.gifv

I have tested this with both 1 and 2 weapons equipped (fury), and it's the same.

http://wotlk.openwow.com/item=43427 Glyph of Sunder Armor
http://wotlk.openwow.com/spell=47467 Sunder Armor (rank 7)

**Comment by Rushor** [comment] 2017-01-15 10:42
Game/Spells: EffectWeaponDmg - Improve stackapplying for Devastate

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4235
* commit: 61e9133f5c1c809a6381eef588f95ddee581723c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-01-15 10:42 UTC
Labels: Class - Warrior, Fixed - Waiting for PTR Update

**Comment by warcraftgeekygamer** [comment] 2017-03-01 22:05
Just curious as to when the changes/fixes will be applied because this is still an on-going issue.

**Comment by Rushor** [comment] 2017-03-02 08:34
The changes/fixes will be applied with the NEXT changelog on the liverealm.

**Comment by TeridanDW** [comment] 2017-10-23 07:17
Works as intended on PTR.
