### ISSUE TITLE
Soul-Trader Beacon

### ISSUE THREAD

**Issue by Joana123** [dalaranwow/dalaran-wow#1249] opened 2014-02-21 08:50 UTC
I am comparing the in-game situation to the information on http://www.wowhead.com/item=38050#comments

When summoned emotes "I have arrived. Shall we set to work, then?". 
---- (doesn't happened when the pet is summoned)

Pet follows and absorbs souls from slain mobs via killing blow in return for Ethereal Credit. 
---- (the pet doesn't do that)

The pet also acts as a vendor and the following items can be bought with Ethereal Credit: [Diluted Ethereum Essence] [Ethereal Mutagen] [Ethereal Liqueur] [Ethereal Essence Sphere] [Soul-Trader's Bindings] [Soul-Trader's Boots] [Soul-Trader's Gloves] [Soul-Trader's Head Wrap] [Soul-Trader's Pauldrons] [Soul-Trader's Waistband] 
---- (the pet currently does not have the option to become a vendor)

**Comment by Rushor** [comment] 2016-11-23 21:31
DB/Creature: Implement Non Combat Pet: Ethereal Soul-Trader 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1249
* commit: ee1c21e3b2d8605268482634ead1778eaeab71e1
* on summon he will say a text
* if you killed a creature, he will give you the share
* he can be used as vendor for the shares

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 21:31 UTC
Labels: Items, On PTR

**Comment by Linozo** [comment] 2017-02-10 12:31
The item I made a post about Is a consumable that can be purchased from this companion. That's also a thing that doesn't work.

**Comment by Rushor** [comment] 2017-02-10 12:55
yes that was also fixed in the commit above.
