### ISSUE TITLE
[NPC] Rare mob "Grimmaw" in Teldrassil

### ISSUE THREAD

**Issue by sokkye** [dalaranwow/dalaran-wow#2813] opened 2015-08-25 11:52 UTC
The rare mob Grimmaw in Teldrassil never seems to spawn.  He should be in Gnarlpine Hold.

**Comment by Sagrath** [comment] 2015-09-11 12:56
Confirmed

**Comment by Rushor** [comment] 2016-06-09 08:37
shuld be around here http://de.wowhead.com/npc=14429/grimmtatze

**Comment by Rushor** [comment] 2016-11-10 11:32
http://wotlk.openwow.com/npc=14429 also ability and waypointpath missing

**Comment by Rushor** [comment] 2016-11-10 11:33
DB/Creature: Add spawn and ability for creature: Grimmaw

* closes https://github.com/dalaranwow/dalaran-wow/issues/2813
* commit: 470314f2658aebed7fd4cb3100e30b9958a0363e

![GitHub Logo](http://i.imgur.com/sm4kH01.jpg)

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 11:33 UTC
