### ISSUE TITLE
[Quest][Classic] Rise, Obsidion!

### ISSUE THREAD

**Issue by rbpaiett** [dalaranwow/dalaran-wow#3696] opened 2016-09-05 21:48 UTC
**Description**:
I accepted the quest and the NPC starts spouting the correct dialogue, then Lathoric the Black comes running in.  As soon as he summons Obsidion, he immediately disappears with no way to attack him.  I kill Obsidion and retrieve his heart.  That's as far as it goes.  I have tried this with abandoning and re-accepting, even moving near where Lathoric summons, but no go.  I should be able to attack Lathoric and retrieve his head.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Jokey123** [comment] 2016-09-06 09:43
I don't mean to sounds rude but, do you mind adding a little bit more information? First of all, you kept most of the questions blank. And second of all, the question asked you to give us the ID of the NPC, etc... And yet you just mentioned a couple websites where we should look it up? I mean, you're the one who's reporting the bug, so report it properly and we can test it.
I'll take a look at it whenever I can.

**Comment by lizardman67** [comment] 2016-09-22 20:12
http://wowwiki.wikia.com/wiki/Quest:Rise,_Obsidion!
http://www.wowhead.com/npc=8391/lathoric-the-black

Other than that theres not much more to describe. Its how the dude said.This npc spawns say his lines and then just disapear. He suppose to turn hostile after that so you can attack him and loot quest item from him ofc.

**Comment by muffygb** [comment] 2016-11-02 01:44
Quest is called Rise, Obsidian [http://www.wowhead.com/quest=3566/rise-obsidion](url) located in the Searing Gorge, Eastern Kingdoms. Quest is part of a chain (Suntara Stones [http://www.wowhead.com/quest=3367/suntara-stones](url) )

What should happen is Obsidian and Lathoric The Black attack and when killed you get [Heart of Obsidion](http://www.wowhead.com/item=10446/heart-of-obsidion) inv_misc_gem_pearl_01  and [Head of Lathoric the Black] (http://www.wowhead.com/item=10447/head-of-lathoric-the-black) inv_misc_head_dwarf_01

What does happen is Obsidian awakens and can be killed and the Heart of Obsidian is collected. Lathoric shows for a short time before dissapearing, he cannot be attacked thus making it impossible to get his head.

**Comment by Rushor** [comment] 2016-11-10 19:44
DB/Quest: Fixup Rise, Obsidion! - Lathoric the Black will no longer despawn after summon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3696
* commit: e029c9fda95a7857468abf55bad10be81d62b4f6

![GitHub Logo](http://i.imgur.com/9nMtal7.jpg)

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 19:44 UTC
Labels: Continent - Classic, On PTR, Quests
