### ISSUE TITLE
Priest spell Prayer of Mending applies heal before damage is registered.

### ISSUE THREAD

**Issue by pepet005** [dalaranwow/dalaran-wow#3205] opened 2016-04-04 20:40 UTC
Tested by me on server Algalon. The healing of priest spell Prayer of Mending applies its heal before the character the spell is active on has actually received damage, which is not the case on the live servers. This results in the spell being significantly weaker than it should be when applied to a target at, or close to, full health, since most of it will be overhealing. Whereas it is significantly stronger than it should be when applied to a target at low health since it may save them when they're supposed to die.

If possible it could perhaps be changed by introducing a short delay of maybe a few milliseconds between the trigger of the spell to the actual heal being applied.

**Comment by Lukas45** [comment] 2016-04-05 14:27
Same issue with Earth Shield

**Comment by Ether009** [comment] 2016-04-05 16:56
It's the same with all damage triggers, not just healing ones. Like Thorns will give damage back before you actually take the damage that triggers it. It's not normally an issue for anything but healing, but there are certain cases that does such as Reflective Shield, which deals back the damage, prior to being damaged which removes the shield. Basically, even if there's only 1 HP left on PW:S, it can still reflect back the full amount as if the shield had been at full hp because that calculation is done before the hp of the shield is even checked. So rather than a short delay, it should be looked into when stuff that triggers on damage should actually be checked. This is a problem in TrinityCore though, so won't be fixed here at all. TC is aware of the problem, but it has a very low priority it seems (though not marked as such) so don't expect a fix any time soon.

**Comment by Golganeth** [comment] 2016-04-05 18:50
Thanks for the report. Considering this is a general issue and not the spell itself, I'll open a general report about it.

@Ether009 Well, your assumptions are completely wrong. Lothloryen doesn't rely on TC to fix anything. First, our core was built and modified by him, which means any TC fix will not be compatible. Second, our priorities are completely different. The list goes on.

**Closed** 2016-04-05 18:51 UTC

**Comment by Ether009** [comment] 2016-04-05 19:23
I didn't say anyone relies on TC to fix anything... I said that it's an issue with TC. And considering what the issue is... Unless there has been some VERY substantial modifications to the spell casting system, which I highly doubt, their fix, when one comes, will be compatible, even if it might require some tweaks to fit. As for that it won't be fixed here but in TC, is simply based on experience on what gets fixed from reports here and what is not...
