### ISSUE TITLE
 [The Last Line Of Defense]

### ISSUE THREAD

**Issue by shadeyolo** [dalaranwow/dalaran-wow#5405] opened 2018-04-16 14:30 UTC
[The Last Line Of Defense] Icecrown quest ....this quest is bugged...dragons cant be hit..they regen after every hit

**Comment by Golganeth** [comment] 2018-04-17 20:11
Duplicate of #5386. If the issue persists, please give any extra feedback once the fix is applied on the live realm (when the tag gets updated).

Closing up.

**Closed** 2018-04-17 20:11 UTC
Labels: Duplicate / Invalid Report / Cannot reproduce
