### ISSUE TITLE
[Mage] Molten Armor triggers Ignite

### ISSUE THREAD

**Issue by gotnoface** [dalaranwow/dalaran-wow#2327] opened 2015-03-29 14:53 UTC
As of patch 3.2.0 Molten Armor shouldn't trigger mage talent Ignite. http://www.wowwiki.com/Molten_Armor

**Comment by Illiyara** [comment] 2016-03-13 16:02
As of now this is still bugged.

**Comment by Rushor** [comment] 2016-12-21 13:49
Scripts/Spells: Mage Ignite should not proc on Molten Armor

* closes https://github.com/dalaranwow/dalaran-wow/issues/2327
* commit: bd2b34de18eccd0486cbc7e9bc012b4e977edc4a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-21 13:49 UTC
Labels: Class - Mage, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-23 08:39
Works as intended on PTR.
