### ISSUE TITLE
Dalaran Weekly Quests

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#4774] opened 2017-07-05 10:12 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently the newly released "... must die!" weekly quests from Dalaran cannot be returned, thus cannot be completed.

**Expected behaviour**: Tell us what should happen instead
You should be able to complete them by returning them to the quest giver.

I am actually surprised I did not see any mention of this.

**Comment by Rushor** [comment] 2017-07-05 10:22
Your issue posted here is a duplicate of issue: https://github.com/dalaranwow/dalaran-wow/issues/4766 (< click on this and you will be redirected to the original posted issue). 

As you can see the issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-05 10:22 UTC
Labels: Duplicate / Invalid Report
