### ISSUE TITLE
[Warrior] Shield Slam

### ISSUE THREAD

**Issue by rayes93** [dalaranwow/dalaran-wow#2371] opened 2015-05-03 21:05 UTC
Normally Shield Slam benefits damage from Shield block value.
The problem is that it doesn't benefits at all. I change gear which gives block value or strength or AP but damage on the Shield Slam does not change.

Another issue i want to make is about the Sword and Board Talent. It say that you have 30% chance after casting Revenge or Devastate to get CD reset on Shield Slam and next Shield Slam, cast within 6s, will cost no rage. Sometimes it works fine, sometimes the buff appears but when you cast Shield Slam rage is consumed and the buff stays with Shield Slam going on CD.

**Comment by Golganeth** [comment] 2015-05-04 16:15
Duplicate of #1255 #1446

**Closed by Golganeth** 2015-05-04 16:15 UTC
