### ISSUE TITLE
[NPC][Karazhan] Nightbane

### ISSUE THREAD

**Issue by Rod2009** [dalaranwow/dalaran-wow#2767] opened 2015-08-08 05:08 UTC
There is a summon boss in Karazhan called Nightbane. There is an urn that will summon him, but when i use it nothing happen. I need that boss for two quest called "Nightbane" and "The Cudgel of Kar'desh" because he drop an item quest to complete it both quest. Thank you.

**Comment by furbs** [comment] 2016-05-05 10:30
Confirmed. Nightbane is supposed to fly onto the terrace and become attackable after the object "Blackened Urn" is clicked if you have, or have completed the quest "Nightbane". Currently the urn is clickable but produces no effect. Since Nightbane is undead a Paladin's "Sense Undead" skill shows his marker on the minimap a little ways into the forest but he does not move and cannot be targeted even with /tar. Couldn't find any workaround.

**Comment by Rushor** [comment] 2016-12-06 10:58
going to rescript the whole encounter.

**Comment by Rushor** [comment] 2016-12-06 18:40
Scripts/Karazhan: Nightbane - rework the whole encounter

* Nightbane now starts flying after using the blackened_urn and will land on the platform
* updated add abilities of him
* closes https://github.com/dalaranwow/dalaran-wow/issues/2767
* commit: b1188b556ea215034aa6111b3b12fd4efaae01bb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-06 18:40 UTC
Labels: Area - Outland, Fixed - Waiting for PTR Update

**Comment by Braniacz** [comment] 2017-12-04 20:16
bump

**Comment by Chenocide** [comment] 2017-12-07 01:17
> The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.

Not on the live realm yet.

**Comment by Mantigora** [comment] 2018-05-08 00:35
Reopen Issue - same bug!

**Comment by lkrocek** [comment] 2018-08-08 16:31
deploy on live pls!

**Comment by Chenocide** [comment] 2018-08-08 22:48
The developers on here cannot push to live, only @Lothloryen can. You will most likely not see anything officially pushed to live until Ruby Sanctum has been released.

**Comment by Ovidijus1992** [comment] 2019-05-15 08:45
@Lothloryen  when this will be pushed to live?
