### ISSUE TITLE
[NPCs] Gan'arg Servant, Gan'arg Tinkerer, Z'kral.

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1909] opened 2014-09-27 09:07 UTC
Gan'arg Servant: http://www.wowhead.com/npc=16947

Gan'arg Tinkerer: http://www.wowhead.com/npc=17151

Z'kral: http://www.wowhead.com/npc=18974

All of these guys should have and use one ability:
- Power Burn: hits an enemy with an anti power bolt that consumes up to 28 to 32 mana. For each point of mana consumed by the bolt, the target takes 1 damage.

Probably should be scaled to level of creature using it.

Link: http://www.wowhead.com/spell=32003

Currently all of them just melee instead.

**Comment by Rushor** [comment] 2016-11-11 11:14
DB/Creature: Implement Gan'arg Servant, Gan'arg Tinkerer, Z'kral SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1909
* first cast of the spell appears 11 - 17 after comnbat start and the creatures will repeat it then every 16 till 30 seconds
* commit: fcb60df788c5af211eef2da1bc4559d499af8819

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 11:14 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 09:08
Works as intended on ptr.
@Rushor isn't 11-17 a bit too rare? These creatures generally die pretty fast.
