### ISSUE TITLE
Achievement: Dinner Impossible

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#745] opened 2013-09-07 10:37 UTC
Achievement **Dinner Impossible** - _(ID:1785)_
- **Issue present:** Achievement is obtained regardless that conditions weren't met by a player. Player got it while he haven't visited not a single Battleground. Instead, he was in the Icecrown Citadel.
- **How it should work:** You should **only** get the credit for this achievement if you place the Great Feast in 5 Battlegrounds. 

Alterac Valley
Warsong Gulch
Eye of the Storm
Arathi Basin
Strand of the Ancients

---

http://www.wowhead.com/achievement=1785/dinner-impossible
http://wotlk.openwow.com/achievement=1785
http://www.wowwiki.com/Dinner_Impossible

**Comment by Rushor** [comment] 2016-11-15 21:41
DB/Achievement: Dinner Impossible - Add placecondition

* closes https://github.com/dalaranwow/dalaran-wow/issues/745
* commit: 597e633697084fa877faa9681f50a62cc819c22d
* you need to be in the correct place now in order to get the credits:
Alterac Valley
Warsong Gulch
Eye of the Storm
Arathi Basin
Strand of the Ancients

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 21:41 UTC
Labels: Achievements, On PTR

**Comment by Bonham01** [comment] 2017-02-01 23:59
I just submitted a ticket in game about this achievement and they pointed me to the bug tracker even though it isn't a bug. Currently, Strand of the Ancients battleground is disabled in game. This means this achievement is literally impossible to get on the live realm. What are my next steps to getting this completed on my character as it is the last achievement I need for the Chef title.

**Comment by TeridanDW** [comment] 2017-04-05 18:38
Works as intended on ptr.
