### ISSUE TITLE
[Quest] The Great Fras Siabi

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#2755] opened 2015-08-02 14:49 UTC
![wowscrnshot_080215_174255](https://cloud.githubusercontent.com/assets/8515510/9026605/4e4a5b62-393e-11e5-8f26-2718f56a9307.jpg)

Somehow you can't interact with his box in Stratholme anymore (it doesn't even sparkle, no gear icon on mouseover either), so he cannot be summoned and defeated for the quest item.

**Comment by DrFuler** [comment] 2016-08-28 02:23
[27/08/2016] - Still not working =/

**Comment by InshadowsAlgalon** [comment] 2016-10-04 17:56
2016-10-04 not working

**Comment by Crispybuilt** [comment] 2016-11-23 00:35
Can confirm that the quest still doesn't work properly.

**Comment by Rushor** [comment] 2016-11-23 07:51
DB/Gameobject: Premium Siabi Tobacco - Enable interaction

* closes https://github.com/dalaranwow/dalaran-wow/issues/2755
* commit: e8fbeecfe5cb6f00ae2469cb78cb08be0be9fe65

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 07:51 UTC
Labels: Instances, On PTR, Quests

**Comment by countinbiskitsyo** [comment] 2017-02-24 18:56
Same issue. Still does not work.

**Comment by Rushor** [comment] 2017-02-24 19:46
The issue is fixed on the **Public Test Realm (PTR).** The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
