### ISSUE TITLE
[NPC] Gahz'rilla

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1046] opened 2013-12-17 11:46 UTC
http://www.wowwiki.com/Gahz%27rilla
http://www.wowhead.com/npc=7273

Gahz'rilla should have and use 3 abilities:

http://wotlk.openwow.com/spell=11836 - 2,5 sec frost stun.
http://wotlk.openwow.com/spell=11902 - knockback uppercut.
http://wotlk.openwow.com/spell=11131 - frostbolt-like spell.

Here's the video from retail: http://www.youtube.com/watch?v=YGUH6Tr1Cwk#t=7m

Currently Gahz'rilla just melees.

**Comment by Rushor** [comment] 2016-11-12 20:36
DB/Creature: Add abilities for Gahz'rilla

* closes https://github.com/dalaranwow/dalaran-wow/issues/1046
* commit: 6f9eb0161c7f8c34e73c643222cdcfd440243820

1216.6,8.88,0,"Gahz'rilla - On Initialize - Move To Position"),
0,"Gahz'rilla - On Initialize - Set Flags Immune To Players & Immune To NPC's"),
0,"Gahz'rilla - On Reached Point 1 - Remove Flags Immune To Players & Immune To NPC's"),
5,40,0,0,0,0,0,0,"Gahz'rilla - In Combat - Cast 'Icicle'"),
,30,0,0,0,0,0,0,"Gahz'rilla - In Combat - Cast 'Freeze Solid'"),
,0,1,0,0,0,0,0,0,0,"Gahz'rilla - In Combat - Cast 'Gahz'rilla Slam'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 19:57
Works as intended, however i would like to add few improvements:
 - The summon possition of npc http://www.wowhead.com/npc=7273/gahzrilla has wrong Z pos (it spawns way too high and falls in the water, instead it should spawn in the water)
`z=-2.083839` seems good

 - Add 1 more action:
`On Reach Point 1 - Set Home Location - Self`

**Comment by Rushor** [comment] 2018-05-10 12:27
> Npc http://www.wowhead.com/npc=7273/gahzrilla should be summoned after player clicked on http://wotlk.openwow.com/object=141832 (after the cast is over), currently it's on player click on that object (at the begining of the cast)

Currently on local PTR it will be spawned after the cast is over :)

Everything else fixed

**Closed by Rushor** 2018-05-10 12:27 UTC
Labels: Area - Instances
