### ISSUE TITLE
[NPC] Nancy Vishas is Set to Passive

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2923] opened 2015-09-28 21:09 UTC
The NPC in Alterac Mountains, the wife of Interrogator Vishas, Nancy Vishas, does not attack. She will not attack if being attacked. 

She should have the standard aggro table the rest of the mobs have.

**Comment by Rushor** [comment] 2016-11-17 20:15
DB/Creature: Nancy Vishas SAI - Fixup agressive behaviour

* closes https://github.com/dalaranwow/dalaran-wow/issues/2923
* she will no longer act passive during the roleplayevent
* commit: 6370b07f4376d223fa553bf834ddcecf7ed18964

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-17 20:15 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 19:25
Works as intended on ptr.

**Comment by Aridam** [comment] 2017-11-05 15:22
Confirmed as still-present on live by the way.

**Comment by TeridanDW** [comment] 2017-11-07 10:52
> Works as intended on ptr.
