### ISSUE TITLE
[NPC] Some Totems Can Move and Attack

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2924] opened 2015-09-28 21:17 UTC
I couldn't find a post explicating this, so...

NPCs # 8127 (Antu'sul), #660 (Bloodscalp Witch Doctor),  #761 (Lost One Seer), #4440 (Razorfen Totemic), #670 (Skullsplitter Witch Doctor), and #5485 (Thistleshrub Rootshaper) cast [Earthgrab Totem](spell ID: 8376). These totems have the same amount of health as the NPC, have an aggro table, and will chase you and somehow melee you for 3-4 damage. 

NPC # 1144 (Mosh'Ogg Witch Doctor) casts spell ID: 3827 (Ward of Laze). Identically to the above, this Ward has over 1500-2500 health, aggros, melees, and moves. 
There may be others, but I have not found them yet. 

NPC totems like these are supposed to be stationary.

**Comment by Rushor** [comment] 2016-11-13 19:39
DB/Creature: Totems disable movement

* closes https://github.com/dalaranwow/dalaran-wow/issues/2924
* disabled the movement for following totems:  Healing Ward (npc=3560), Earthgrab Totem (npc=6066), Greater Healing Ward (npc=8179) and Ward of Laze (npc=2667)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 19:39 UTC
Labels: Continent - Classic, On PTR
