### ISSUE TITLE
Item: Mithril Spurs [7969]

### ISSUE THREAD

**Issue by Spectralus** [dalaranwow/dalaran-wow#1336] opened 2014-03-12 23:17 UTC
Issue present: The following item has no effect on mounted movement speed. Tested and measured with Carbonite addon. Character was lvl 45. Completly useless and broken item to be sold at Auction House. 

How it should work: Use: Attaches spurs to your boots that increase your mounted movement speed by 4%.  Must be level 70 or lower to gain this benefit.

Item: http://www.wowhead.com/item=7969
Spell: http://www.wowhead.com/spell=9783

**Comment by Rushor** [comment] 2016-11-23 20:58
Scripts/Spells: Implement Mithril Spurs

* closes https://github.com/dalaranwow/dalaran-wow/issues/1336
* commit: d3da752665e68367b06591c58fc01897b07f04f7
* the spell will have no effect on targets <= level 70

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 20:58 UTC
Labels: Items, On PTR
