### ISSUE TITLE
Last boss of Blackfathom Deep don't spawn

### ISSUE THREAD

**Issue by Marsheur** [dalaranwow/dalaran-wow#5586] opened 2018-08-15 18:12 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:  (Where:Blackfathom Deeps, When:2018-08-15, What:Aku'mai (last boss) doesn't spawn so we can't complete the instance and get the achivement, Why: Instance not complete,  Who:Amarasu, Gulduur, Nanigi, Norinaga)

**Expected behaviour**: Usually when you activate the 4 fire before the last room the door open. You can then find Aku'mai in the last room and steal his treasor

**Steps to reproduce the problem**:

1.  Enter blackfathon Deep
2.  Reach the last room
3. 

**Include proofs for this behaviour**

A simple visit to blackfathom deep can prove this.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPCid=75408

**Comment by Golganeth** [comment] 2018-08-19 15:37
Can't reproduce so I'm closing this until proper proof is provided.

![image](https://user-images.githubusercontent.com/5057942/44310430-6fdec780-a3d6-11e8-8b2f-4f07959f69bf.png)

**Closed by Golganeth** 2018-08-19 15:37 UTC
