### ISSUE TITLE
[ToC][Icehowl] Engage position/movement

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#4367] opened 2017-02-01 01:47 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Icehowl engages too close to the door without the proper delay.
Icehowl's hit box is also out of line of sight for a second at engage.
This issue is probably related to how far back he starts RP walking from.

**Expected behaviour**:
Icehowl should walk further out and pause for two seconds before engaging.

**Steps to reproduce the problem**:

1. Pull Northrend Beasts
2. Kill Gormok, Acidmaw and Dreadscale
3. Watch Icehowl

**Include proofs for this behaviour**

Videos from live:
https://youtu.be/wvrCIwnS154?t=286
https://youtu.be/GFM9kvDT5HY?t=337
https://youtu.be/NYcYmcnnTC4?t=315

Video from Dalaran (It's an old video for something unrelated but you can still see the issue clearly):
https://youtu.be/M9aAWfM2gps?t=179

Notice the error message "Target is out of line of sight" when I attempt to taunt after Icehowl becomes attackable.

Semi related, this only started happening three weeks ago:
Icehowl's hit box can bug in the doorway and remain out of line of sight from certain locations.
Example:
https://youtu.be/TtUJIJssdN4?t=5

**Comment by alexuktc** [comment] 2017-02-01 06:13
I can confirm. It is very annoying as melee because you cannot hug the wall (he will not be in line of sight if you do), meaning you will always be thrown a big distance when he swirls. This can be the difference between a wipe and a kill in togc.

**Comment by Domynator** [comment] 2017-02-02 05:06
I can confirm as a Melee many times you cannot hit the boss without moving to the middle of the room, and not using the proper mechanics the fight requires. 

Definitely can mean the difference between a kill or wipe when 6-8 people cannot hit the boss.

**Comment by alexuktc** [comment] 2017-02-03 12:19
Also an issue I noticed as a combat rogue - when Icehowl is stunned at the wall Killing Spree will not hit him. I have wasted the skill several times trying to get the bonus damage on it. Considering that he gets a 100% damage bonus there should be a very noticeable difference in the damage values it does compared to another raid boss. I will post a recount showing this after I do beasts on toc25. I will make sure to waste my Killing Spree on him.

**Comment by alexuktc** [comment] 2017-02-03 13:56
Sorry to hijack this thread, but I have found the problem. It is coupled with the issue at hand that the issue opener posted. 
Stunning mobs on this server is bugged. I remember when I leveled my rogue I had many issues with it. 

I would go behind a mob and cheap shot it. Many mobs with instant cast spells would still cast that on me. Even though I have opened with cheap shot the mob would be facing me (even though it shows that it isn't). it made a difference when you're sub and trying to backstab after cheap shot. 

Linking to the issue at hand here. When Icehowl hits the wall he is supposed to be stunned. However even if he if facing the wall he is actually faced towards the raid. When Killing Spree is ast it puts you behind the boss. Since he is not facing the wall you are put behind him next to the wall. Since hugging the wall gives you line of sight issues attacking him, Killing Spree does nothing.

**Comment by Rushor** [comment] 2017-02-15 13:42
Scripts/TrialOfTheCrusader: Update Attackstartposition of Icehowl and delay the attackstart by 1 seconds

* also remove UNIT_FLAG_NOT_SELECTABLE from the northrend beasts (they should be selectable on spawn but not attackable
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4367
* commit: ea4838d5b0999edab55dfcb76dcd71c87921c5ee

![GitHub Logo](http://i.imgur.com/IuUGxBx.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-02-15 13:42 UTC
