### ISSUE TITLE
[NPC][WotlK] Ice Steppe Bull, Ice Steppe Rhino, Stormpeak Wyrm, missing wps, mini event

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4311] opened 2017-01-24 16:52 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Ice Steppe Bull http://wotlk.openwow.com/npc=30445 , Ice Steppe Rhino http://wotlk.openwow.com/npc=29469 are missing all of there paths. Npc Stormpeak Wyrm http://wotlk.openwow.com/npc=30055 has some missing spawn locations and paths for them.
![wowscrnshot_012417_180147](https://cloud.githubusercontent.com/assets/6797611/22256605/f6618b34-e263-11e6-9007-6dd8edcba6b3.jpg)
![wowscrnshot_012417_180157](https://cloud.githubusercontent.com/assets/6797611/22256611/fac7c65c-e263-11e6-97c0-5d524da861a6.jpg)
![wowscrnshot_012417_180218](https://cloud.githubusercontent.com/assets/6797611/22256616/fee2269c-e263-11e6-857b-f0949a4ca722.jpg)
![wowscrnshot_012417_183627](https://cloud.githubusercontent.com/assets/6797611/22256644/14f366bc-e264-11e6-8b73-527110f6c8d0.jpg)
![wowscrnshot_012417_183642](https://cloud.githubusercontent.com/assets/6797611/22256655/1a8a4bfe-e264-11e6-8cb3-9c4eb783c473.jpg)

 - There is a mini event that Stormpeak Wyrm quickly kills a Rhino, grabs it and takes it in the mountains (check end of the video).

 - There seems to be issue with Stormpeak Wyrm that are landed or are flying, they seems to drop combat extreamly fast when i am in the air. They should chase me for the same distance as the ground npcs (when i am on the ground).
Note: If this is general issue with all flyers, please ignore it as it should not be part of this report!

**Expected behaviour**: Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=Y5bWse9dzDA

Related to #4275 as the rhinos seems to have group leaders.
P.S. I hope the sn**** will help because i can't accurately follow every single of those npcs.

**Comment by Rushor** [comment] 2017-01-24 17:45
> P.S. I hope the sn**** will help because i can't accurately follow every single of those npcs.

well you must follow them, else we don't get alle the points. but you can make several sniffs if you want :)

**Comment by Teridan-dal-wow** [comment] 2017-01-24 18:30
Video uploaded.
@Rushor please review the video and the file and tell me if you can pull anything from them, if not, i will redo everything tomorrow on smaller parts.

**Comment by Rushor** [comment] 2017-01-24 20:26
it's a bit hard, cuz there are too many points caused by the follow movement and zoning in and out - i will not go in detail here haha

but it's doable

atm done:
- pathing for bull 1 without follower
- pathing for bull 2 + follower

**Comment by Rushor** [comment] 2017-01-24 21:26
alright the spawns for http://wotlk.openwow.com/npc=30055 is already fine on ptr, with further merges this will be on the server too.

> There seems to be issue with Stormpeak Wyrm that are landed or are flying, they seems to drop combat extreamly fast when i am in the air.

Is a general issue yeah

i will push all the paths for the rinos/bulls now

**Comment by Rushor** [comment] 2017-01-24 21:30
DB/Creature: Pathing for Ice Steppe Bull, Ice Steppe Rhino (7 Paths in total with different formations)

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4311
* commit: 33b42b400df4b88599e156c515fc2ae38bc0cbca

![GitHub Logo](http://i.imgur.com/44XYyAs.jpg)
![GitHub Logo](http://i.imgur.com/5FRNZjx.jpg)
![GitHub Logo](http://i.imgur.com/PPmTNOu.jpg)
![GitHub Logo](http://i.imgur.com/kKY81dp.jpg)
![GitHub Logo](http://i.imgur.com/a7HJVhy.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-01-24 21:30 UTC
Labels: Area - Northrend

**Comment by Teridan-dal-wow** [comment] 2017-01-25 07:19
@Rushor Thank you for your work, I would like to apologies for the crappy report, it won't happen again.

**Comment by Rushor** [comment] 2017-01-25 10:42
no the report itself was fine, but sniffing paths in large files is simply tricky :D 

when i sniffed paths back in the days, i started the sniffer, followed the path one time, stopped the sniffer and killed the creature after it (this prevents multiple datas :) )

**Comment by Rushor** [comment] 2017-01-25 11:10
@Teridan-dal-wow i found the reason for the "missing Stormpeak Wyrm " 

the visibility range is simply too low for them and one can assume that there are too few spawns.

I set them active, and tada: 

![GitHub Logo](http://i.imgur.com/QnMPugG.jpg)

i will push that change here https://github.com/dalaranwow/dalaran-wow/issues/4312, because these creature need the same fix :)

**Comment by Rushor** [comment] 2017-01-25 17:48
also set the rhinos active, so the whole zone will look much better:

![GitHub Logo](http://i.imgur.com/a4ZXOY3.jpg)

**Comment by Teridan-dal-wow** [comment] 2017-01-28 09:51
What about:

> There is a mini event that Stormpeak Wyrm quickly kills a Rhino, grabs it and takes it in the mountains (check end of the video).

Can this be done?

**Comment by Rushor** [comment] 2017-02-03 20:56
yeah maybe, but i would do it with a static guid (the wyrm always picks the same rhino then) pls open up an extern report for this since that needs a lot of work. thanks :)

**Comment by Teridan-dal-wow** [comment] 2017-02-10 19:50
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Found few npcs with missing paths, however the ones that do have works exacly like on retail. Thank you for your work there! (as i know the sniff was terrible).
Regarding the ones that are missing paths i will report them tomorrow with individual sniffs for each one of the them. Also i would like to add that i missed your comment regarding the event (don't know how o_O) and will report it tomorrow too (noticed few rhinos on the field below the wyrms without paths, maybe you can use them as "victims" however i do think all of the rhinos in this area have paths, will double check tomorrow.
Again thanks for this one, i can't really image what kind of pain it would of be to read the sniffs with so many creatures around.
