### ISSUE TITLE
Yogg-saron kill not counted - need the Descent into madness achievement(10)

### ISSUE THREAD

**Issue by Craftymind** [dalaranwow/dalaran-wow#3555] opened 2016-07-04 23:10 UTC
Hello,

I made this ticket in game several days ago on my sole character Craftybm, but the GMs are late to respond, so I'm putting it here too because I need this to be fixed ASAP so I can continue the progression into ToC 10:

I just did Uld(10) and killed Yogg-Saron but I went insane at the end and died. I didn't get the kill counted, neither the Descent into madness(10) achievement. Because I died and released, my skada reset all data, but I have a screen shot of recount that a mage in my group took that shows that I was part of the fight. ( http://imgur.com/a/qC4Xs ). Also here is screenshot of me near Yogg's corpse after I went back in ( http://imgur.com/92yVh3I ).

I Know the GMs are busy with a lot of stuff, but really, the " kill-not-counted-because-of-death-bug " need to be fixed for several bosses in end game content (especially Ulduar). It's ruining the endgame experience a little bit :(

**Comment by ImprezaWoW** [comment] 2016-07-05 02:47
You released spirit. It's not a bug, you willingly left the instance and were not present in the boss's kill. Closing.

**Comment by ImprezaWoW** [comment] 2016-07-05 02:47
On top of that, Yogg was never bugged, and IC and Freya are already fixed. Cheers.

**Closed by ImprezaWoW** 2016-07-05 02:47 UTC
