### ISSUE TITLE
Retribution paladin art of war bug

### ISSUE THREAD

**Issue by zozefin** [dalaranwow/dalaran-wow#2220] opened 2015-02-04 17:47 UTC
After using an instant cast from the proc of art of war ( flash of light or exorcism ) it resets the swing of auto attacks resulting in fewer auto attack and reduced dps.. iv read that this problem will be fixed until the next scheduled maintenance as lothloryen said at 10 oct 2014 (and has been reported since 16 oct 2013)but because i m new to this server i m not sure if the maintenance has be done yet,but anyways its still there.I v noticed this with an addon and hoping some1 could confirm this with a screenshot or a  video since my wow client crushes each time i m trying to capture a Screenshot for somereason and i cant do  it myself

**Comment by Nikvet** [comment] 2015-02-05 16:21
Not bugged. I tested and it's not resetting the Auto-Attack Swing.

**Comment by Golganeth** [comment] 2015-02-05 16:50
Thanks @Nikvet. I've also tested it and couldn't reproduce any issue. This was fixed some time ago. (#918).
Closing up.

**Closed by Golganeth** 2015-02-05 16:50 UTC
