### ISSUE TITLE
[Mechanic] Group Loot and Questing Bug

### ISSUE THREAD

**Issue by thestranger064** [dalaranwow/dalaran-wow#5428] opened 2018-04-28 15:37 UTC
**Current behaviour:**
**When you form a group and do quests only 1 person can loot said objects or npc.:**
 1. When you kill an enemy only 1 person can loot the quest item, but the enemy still glitters and wont allow other players to click it.

2. When you loot an object on ground only 1 person can take it, and the rest of the group has to wait, sometimes more then 10m.

**Expected behaviour:** 
When forming a group for quest objectives, it should allow things to be easier, not harder and more frustrating.
Entire group should be able to loot the current object, or make it so it spawns much faster, and not 10m or more a time.
Entire group should be able to loot said npc on ground once killed, and not just one player.

**Steps to reproduce the problem:**

**Step1.** Form a group, get a quest in the world somewhere.
**Step 2.** Loot a corpse or take a object from the ground.
**Step 3.** Observe and see that the rest of the group has to wait for new respawns from objects or npcs.

**Include proofs for this behaviour**
Heres a few already on bugtracker

https://github.com/dalaranwow/dalaran-wow/issues/5367 - By HS-Disq
This one explains how looting a corpse in said example questing in a open world area can only be done by 1 player - and everyone else cannot take it. A fix is awaited for this.

https://github.com/dalaranwow/dalaran-wow/issues/5409 - by 	idkm23 
This one explains how looting a corpse in this example a dungeon can only be done by 1 player

https://github.com/dalaranwow/dalaran-wow/issues/2230 -Book of Ur by 	daxpedda
This explains the timer on quest objectives that it takes awhile for it to spawn, and is already awaiting a fix.

As you can see this is a **mechanic bug** and its a mayor problem for parties.

I have done many quests since my return to dalaran and I am in Northrend right now, and every quest is the same, as well as quest objects on the ground.
**This is very frustrating when you play in groups, but solo players will not notice this.**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

My Examples:

https://wotlk.evowow.com/?quest=13285 - Forging the keystone (have to wait more then 30m for a respawn if another player in group has done it, and not every player get credit.)

https://wotlk.evowow.com/?quest=12858 - Pieces of the puzzle (Another mob drop thing only 1 person can click and get.)

https://wotlk.evowow.com/?quest=12860 - Data Mining (Quest objects only 1 person can tag, get credit for even in party or group.)

Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills

**You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/**

Note: All this steps are easily reproducable and you only have to follow the steps provided to check it yourself, while in a group. Whether it is a dungeon quest or a area quest in azeroth is irrelative, everything is behaving the same.

**Comment by Golganeth** [comment] 2018-04-29 13:10
> When you kill an enemy only 1 person can loot the quest item, but the enemy still glitters and wont allow other players to click it.
- Intended behavior, unless it's a unique or boss item. If you find an issue with any of those, please make an specific report about the item since most of them are handled and adjusted invidually.

====================
> When you loot an object on ground only 1 person can take it, and the rest of the group has to wait, sometimes more then 10m.
- Intended behavior. If you'd like to report a specific game object that takes too long to respawn please do so (and please add proper proof of the intended timer), since they are adjusted individually on the DB.

----
-----

> #5409 - by idkm23
This one explains how looting a corpse in this example a dungeon can only be done by 1 player
- Isolated issue that I couldn't reproduce, perhaps some of the party members didn't have the quest on their logs by the time the boss was engaged/killed.

====================

>#2230 -Book of Ur by daxpedda
This explains the timer on quest objectives that it takes awhile for it to spawn, and is already awaiting a fix.
- The timer has been reduced so that different party members can complete the quest faster, however as of now the fix is only on the PTR (see tag)


====================
====================


The "issue" you describe was the intended behavior during Vanilla, TBC and WotLK.
Your description of the "expected behavior" is a feature that was implemented during Cataclysm.

As I said on your last report, this is the intended behavior (you can find several proofs about this on the internet, make sure though the sources are from WotLK or from older expansions)
As I also said, this should be taken to the [Suggestions and Opinions](http://www.dalaran-wow.com/forums/news-and-rules/suggestions-and-opinions) section of the forums.

If you'd like to report a quest that doesn't work as intended, or a game object that takes too long to respawn, **add proper proof and make specific reports, so that developers work gets a little bit easier. Most of the quests or game objects are adjusted individually.**

Hope I cleared this up now.

Closing.

**Closed by Golganeth** 2018-04-29 13:10 UTC
