### ISSUE TITLE
Daphne Stillwell

### ISSUE THREAD

**Issue by joelmatheny** [dalaranwow/dalaran-wow#3366] opened 2016-06-04 20:40 UTC
The quest that Duthorian Rall gives Paladins is bugged. Daphne Stillwell helps you defend the incoming Defias, but one of the waves bugs, and you aren't able to finish the quest.

**Comment by Golganeth** [comment] 2016-06-04 20:44
Duplicate of #2452

**Closed by Golganeth** 2016-06-04 20:44 UTC
