### ISSUE TITLE
[Quest][Northrend] Territorial Trespass

### ISSUE THREAD

**Issue by ReaverB** [dalaranwow/dalaran-wow#1552] opened 2014-04-25 15:40 UTC
http://www.wowhead.com/quest=13051/territorial-trespass

Place the Stolen Proto-Dragon Eggs on top of the Broodmother's Nest and return to Thorim at the Temple of Storms.

-Veranus Lured

Placing the egg on Kirin Tor is not summoning Veranus, quest credit is not given for placing the egg.

**Comment by ImprezaWoW** [comment] 2016-05-21 05:16
Seems like Veranus does not spawn after placing the egg anymore.

**Comment by Bloodhawk92** [comment] 2016-05-31 16:59
Seems like Veranus doesn't spawn after placing the egg for me as well

**Comment by Rushor** [comment] 2016-05-31 19:58
you must wait until Veranus reaches it's final position. maybe the creatures must be set active on spawn

**Comment by Lothloryen** [comment] 2016-06-01 00:37
Thank you everyone, I shall take a look and check if what @Rushor comments works for this.

@Rushor Maybe you did not read me through other reports - I would like to speak with you so, if you do not mind, write me an e-mail to: dalaran.community@gmail.com, please.

**Comment by cybergeek94** [comment] 2016-07-30 05:00
Tried this quest just now, waited several minutes but no credit.

**Comment by Nikvet** [comment] 2016-09-03 19:02
I placed the eggs, waited 2-3 minutes for Veranus to appear, but she does not appear. Bugged.

**Comment by Rushor** [comment] 2016-12-13 14:22
DB/Quest: Territorial Trespass - small adjustments 

* add eggspawns
* delay summon of veranus
* add landing point for veranus
* closes https://github.com/dalaranwow/dalaran-wow/issues/1552
* commit: cfb486a1d2857864ff699374c53a248f02bae96b

![GitHub Logo](http://i.imgur.com/Uz2uhVw.jpg)
![GitHub Logo](http://i.imgur.com/M79qD50.jpg)
![GitHub Logo](http://i.imgur.com/jsQsghY.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-13 14:22 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR Update, General - Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:06
Works as intended on PTR.
