### ISSUE TITLE
Fel Armor Bug

### ISSUE THREAD

**Issue by dxxa** [dalaranwow/dalaran-wow#3221] opened 2016-04-13 17:07 UTC
I have a lvl 80 warlock and I noticed that the # **FEL Armor** has very heavy bug in a positive
while I'm flying with the mount or AFK, enchant lightwave Embroidery (295 sp actived on) is always active at any time, even this trinket Dying Curse (750 sp actived on) is always activ and then all automatic activation with trinket spellpower
This bug gives me always more sp 1045 (Dying Curse + lightwave Embroidery750 + 295 = 1045 SP) and FelArmor heal me over always
I have 2600 bonus damge with this bug I always 3700 damage bonus, this bonus damage does not reach not even with the set full wrathfull, this is a crazy bug please let fix it because people will bug abuser
![warlock bug](https://cloud.githubusercontent.com/assets/18446530/14502171/4452b1f6-01aa-11e6-85df-b259162511ba.png)
![warlock wrathfull](https://cloud.githubusercontent.com/assets/18446530/14502182/534578d8-01aa-11e6-9238-725420604528.png)

**Comment by Lukas45** [comment] 2016-04-13 18:53
You should probably mention that the picture #1 has the Dying Curse proc ACTIVE (as the [Full Picture](http://i.imgur.com/iCufxMm.jpg) displays)
Fel Armor does not make them permanently active, it does however make stuff like Dying Curse and Embroidery proc from its healing (along with other things).
Also the armory picture is obviously  unbuffed (no trinket procs etc)
This is my warlock, pretty much equally geared with both procs on: [Picture](https://i.gyazo.com/519bcd6915db5097a01856ed4964b035.jpg)

So apart from a duplicate of #2389 there is nothing wrong here.

**Comment by Golganeth** [comment] 2016-04-18 12:51
Duplicated of #2389 

Closed.

**Closed by Golganeth** 2016-04-18 12:51 UTC

**Comment by dxxa** [comment] 2016-05-01 08:49
I had already seen that someone had posted, but I realized that the date of the post and the May 20, 2015 that is, we talk about one year behind o_O. you are going to fix within onixya? or talk about it next year?

**Comment by Lukas45** [comment] 2016-05-01 09:04
I would appear that, unless a class is beyond broken (like more broken than Fel Armor), it's on very low prio

**Comment by robinsch** [comment] 2016-12-28 13:28
Commit: 6add64e347af4149f9bde94f9e247ce5c8956304
Core/Spell: Don't proc auras if SPELL_AURA_OBS_MOD_HEALTH overheals

**Comment by TeridanDW** [comment] 2017-10-14 07:58
@Lothloryen I will merge this report and #2389 as the commit used by @robinsch is the same one.

Regarding the issue, works as intended on ptr. 
Overheals from Fel Armor nolonger procs Dying Curse or  Lightwave Embroidery, however if the warlock is under 100% hp the heal from the armor will proc them (randomly).

**Comment by Lothloryen** [comment] 2017-10-15 11:11
@TeridanDW Perfect, thank you. Deployed already to Algalon.
