### ISSUE TITLE
[Quest]  Gerenzo's Orders [1090]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#590] opened 2013-08-14 18:14 UTC
http://old.wowhead.com/quest=1090 upon taking this quest there should be waves of mobs spawning to attack you. That doesn't happen.

**Comment by transroute** [comment] 2015-09-25 13:29
confirmed.

**Comment by Zibathy** [comment] 2015-12-31 12:32
Confirmed still bugged. Waited 10 minutes, no waves, nothin.

**Comment by glitterlance** [comment] 2016-02-05 14:02
February 2016, quest is still bugged.

**Comment by Rushor** [comment] 2016-06-07 10:52
requires a bit coresupport to check the waves :/

**Comment by Stihii** [comment] 2016-06-12 15:00
Can confirm as well that the issue is still present on Algalon.

**Comment by Rushor** [comment] 2016-06-22 17:34
22cc6ff5cbae7408ff0816ee9eac9b847ed8cf8e
- script added on ptr

**Comment by Golganeth** [comment] 2016-06-23 12:11
MalkaviaDW:
> The event works, but when Piznik says: Yay! I have found it! (the event should finish with the quest completion) and it is not happening. The NPC continues digging and no more waves of mobs appears.

**Comment by MrAndersonX** [comment] 2016-08-28 12:13
Confirmed. Nothing happens. Waves of creeps never appear, and he never mines any ore.

**Comment by Godzilla2k** [comment] 2016-10-12 19:01
Quest still doesn't work.

**Comment by Rushor** [comment] 2016-11-17 21:43
Scripts/Kalimdor: Quest Gerenzo's Orders

* closes https://github.com/dalaranwow/dalaran-wow/issues/590
* added a new corescript for this
* commit: 1bdadf54fc21e23dd774ce70a937e37e77113689

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-05 10:30
Hello, quest is not completeable but it should be improved before pushing to live. Issues that i saw:
 - both waves http://wotlk.openwow.com/npc=3999 spawn almost at the same time (there should be some delay so the player/s can kill each wave, 6 mobs at the same it is too much for level 20s)
 - when each wave spawns the creatures should startattack > npc http://wotlk.openwow.com/npc=4276 (currently they don't)
 - npc http://wotlk.openwow.com/npc=4276 should lose flag questgiver while the event is running and he should be set to active so the event doesn't get stucked
 - npc http://wotlk.openwow.com/npc=4276 should be attackable by all npc http://wotlk.openwow.com/npc=3999 while the event is running and he shouldm't fight back, instead he should continue to mine all the time, flag civilian and passive i asume.
 - if npc http://wotlk.openwow.com/npc=4276 dies > quest fail

Proof:

> By Drenfrell (165 – 1) on 2007/09/06 (Patch 2.1.3)		
> This is a ridiculously hard quest for it's level. I tried this as a level 28 rogue with reasonably good gear and failed it three times. Once I just got overwhelmed by mobs, the second and third times I failed to aggro a mob that killed Piznik. Upon first approaching Piznik you'll have to kill 5-6 mobs (watch out, they tend to stack on each other, so what first looked like four mobs to me was actually six) just to get the quest. Also as a previous poster mentioned, Piznik has very low health - he can be killed by a single mob, and rather quickly if you're chasing a fleeing mob up the tunnel; you HAVE to aggro all the mobs that spawn. The first wave is pretty easy, only three, but the next wave had five, and then a couple additional adds respawned in the hallway I originally cleared to get to the quest giver. What finally worked for me was waiting at the slight bend in the tunnel where the waves spawn, quickly sapping one, tagging each of the other spawns to keep them on me, and killing the geomancers first. Made a quick target macro for them as they can get lost in the crowd. Crippling poison recommended to deal with runners when you're frostbolted.

**Closed** 2017-11-22 15:56 UTC
Labels: Area - Classic, Fixed - On Live Server, General - Quests, Works - but it needs improvements.
