### ISSUE TITLE
[Quest][Outland] Gather the Orbs

### ISSUE THREAD

**Issue by Loutmourne** [dalaranwow/dalaran-wow#2449] opened 2015-05-29 04:20 UTC
Quest Gather the Orbs (ID:10859) provides players with Orb Collecting Totem (item ID:31668) which "Places an Orb Collecting Totem on the ground in Razaan's Landing for 30 sec". Apparently, the totem it places is hostile to player, is able to move and attack, parry, dodge and provides XP for being killed, like a normal mob. Quest itself is completable although this can cause some very unpleasant situations and possibly get players killed.
![wowscrnshot_052915_070151](https://cloud.githubusercontent.com/assets/12653828/7876360/fa309166-05d2-11e5-8f4a-ce82baac6f2d.jpg)

**Comment by ashido96** [comment] 2015-07-20 03:33
Will confirm that this is the case, totem is hostile to you as soon as it's summoned, but quest is still completable.

**Comment by MrAndersonX** [comment] 2015-10-03 13:28
Yeah, tried to do the quest right now, the totem still attacks/moves etc, but the quest isn't doable anymore. It won't gather yellow orbs no matter what, so it's 100% bugged.

**Comment by MrAndersonX** [comment] 2015-10-03 13:35
Yeah, doable, but still bugged.

**Comment by Rushor** [comment] 2016-11-28 11:35
DB/Quest: Gather the Orbs - Orb Collecting Totem is no longer attackable

* closes https://github.com/dalaranwow/dalaran-wow/issues/2449
* commit: 90d15b08c503652280c3b090166ffac3b534064b

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 11:35 UTC
Labels: Continent - Outland, On PTR, Quests
