### ISSUE TITLE
[NPC] Warleader Krazzilak

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1031] opened 2013-12-13 11:14 UTC
http://www.wowwiki.com/Warleader_Krazzilak

Should have and use following abilities:

http://wotlk.openwow.com/spell=6253 - 2 sec stun;

http://wotlk.openwow.com/spell=22691 - 6 sec disarm;

http://wotlk.openwow.com/spell=38262 - this version of Hamstring, 60%;

http://wotlk.openwow.com/spell=17230 - disease, +6 physical damage taken.

Currently just melees instead.

**Comment by Rushor** [comment] 2016-11-12 19:15
DB/Creature: Warleader Krazzilak - Add abilities

* closes https://github.com/dalaranwow/dalaran-wow/issues/1031
* commit: cc6369489ee300d096ea1d6d2228cc7952771d98

0,0,"Warleader Krazzilak - On Aggro - Cast 'Infected Wound'"),
2,0,0,0,0,0,0,0,"Warleader Krazzilak - In Combat - Cast 'Disarm'"),
,0,"Warleader Krazzilak - Between 0-50% Health - Cast 'Hamstring' (No Repeat)"),
0,0,"Warleader Krazzilak - Between 0-20% Health - Cast 'Backhand' (No Repeat)");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 19:15 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 12:00
He is casting all 4 spells, however i would like to suggest few improvements to his SAI.
 - as he can be pulled from distance = first spell never been used > change to update_ic
 - I couldn't find any info regarding the 50% and 20% hp triggers, so maybe change these 2 spells on update_ic too

Both of these are suggestion and can be ignored so marking as:
