### ISSUE TITLE
[General] Caster mobs

### ISSUE THREAD

**Issue by Deqths** [dalaranwow/dalaran-wow#2365] opened 2015-04-27 18:00 UTC
I noticed that the caster mobs aren't behaving the way they should, some spam spells they aren't meant to spam which makes them overpowered for their level. And there's something more important, the kick/counterspell/silence, when you counterspell a mob casting something, they aren't meant to cast something of that school for 8 seconds and are supposed to come fight in melee if they don't have other spells to use on a different school. But noticed that most of them just continue casting the same spell even if you interrupted them correctly.
Ex :
- Mob casting Frostbolt.
- Using counterspell/kick etc...
- Instead of coming in melee, they just cast Frostbolt over again. ( which shouldn't be possible for 8 sec )

**Comment by Golganeth** [comment] 2015-05-04 16:13
Duplicate of #182 #1793

**Closed by Golganeth** 2015-05-04 16:13 UTC
