### ISSUE TITLE
backstab ambush ravage and shred

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#1834] opened 2014-08-25 23:32 UTC
"these 4 abilities are dodgeable, parry-able, block-able by players (i think it happens if they turn around too fast)
How it should work: those 4 abilities should not be dodgeable, parriable or blockable by any player (not even hunters with deterrence)."

this issue was opened before and closed without getting fixed, here is proof that its still bugged:
http://i.imgur.com/98cnwV6.jpg

**Comment by robinsch** [comment] 2016-05-30 19:50
You could also experience this on retail. This is caused by server side and client side delay on movement and spell. You can cast Ambush (or whatever spell that requires facing or behind) and the target could move to face you and therefore would be able to dodge (or block etc.) the spell.

I'm closing this since it was also a thing on retail.

**Closed by robinsch** 2016-05-30 19:50 UTC
Labels: Class#Druid, Class#Hunter, Core/System, Spells/Auras
