### ISSUE TITLE
[Quest][Northrend] The Hunt is on

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1376] opened 2014-03-23 01:25 UTC
When you use the "Occulus of the Exorcist" to discover the hidden cultists, they aren't surrounded by the dark aura they should have.

**Comment by ImprezaWoW** [comment] 2017-01-12 11:52
Quoting from a ticket, 
NPC Tom hegger in valiance keep has the dialog : "You don't know who you're messing with, $c! Death Beckons!" without mentioning the class. Also a very minor issue

**Comment by Rushor** [comment] 2017-01-12 11:56
Scripts/Northrend: The Hunt is on - Texttargeting for questcreatures

* updates: https://github.com/dalaranwow/dalaran-wow/issues/1376
* commit: 78bf5a0eb86f5346207542b3ad88bf7f6855ebbf

Fixed the texttargeting issue. Please reopen the issue, once the textfix was applied on Live.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-01-12 11:56 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR Update, General - Quests, Priority - Low

**Comment by TeridanDW** [comment] 2017-11-12 18:58
Works as intended on PTR.
