### ISSUE TITLE
[Druid] Swift Flight Form

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#5598] opened 2018-09-06 16:58 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Once you acquire a 310% mount your Swift Flight Form should change to a 310% speed increase. This does not apply for Ashes of Al'ar since it is a TBC mount created before the change. 

You have to mount the 310% mount in order for it to adjust your Flight Form.

As found in the patch notes this was introduced in Patch 3.2.0

**Expected behaviour**: Tell us what should happen instead
Easy. This simply does not work here.

**Steps to reproduce the problem**:

1. Acquire a 310% mount
2.  Mount it.
3.  Nothing happens.

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Swift_Flight_Form -> Go to Patch Notes 3.2.0

**Comment by Golganeth** [comment] 2018-09-08 13:04
Seems to work as intended. You will need to mount a flying mount and make sure it is moving at 310% before trying the swift flight form.

Ignore the tooltip, it only shows base stats and not modified ones, as intended. In order to track your actual movement speed you will need to get an addon.

Closing.

**Closed by Golganeth** 2018-09-08 13:04 UTC
