### ISSUE TITLE
[Quest][Northrend] Sniffing Out the Perpetrator

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#330] opened 2013-08-04 14:52 UTC
http://www.wowhead.com/quest=12855
In this quest, you have to use a provided item Frosthound's Collar to summon a Frosthound and ride it to find some clues.
There are some problems:
- Frosthound is in fact spawned, but it is done like a pet, instead of riding it.
- Also, you use collar several times, and call several frosthounds, which should not         happen.
  Anyway, since you can not ride it, you can not complete the quest.

**Comment by Augur89** [comment] 2015-04-26 13:18
Is the quest unavailable for some reason? The quest giver, Archaeologist Andorin (NPC 29650), has a blue interrogation mark above his head and if I speak to him the quest has a grey interrogation mark and I can't take it.

Please consider fixing it as it starts a long chain that is needed for the achievement.

**Comment by Augur89** [comment] 2015-05-20 13:29
The whole chain is now fixed, all the roleplay events and the final scene... so touching. I never completed these quests on retail so it was the first time for me. So glad I got to experience it on this server and with such scripting quality. Thank you for these moments!!

By the way, completing the quest I finished the Loremaster of Northrend achievement too and I have dozens of spare quests yet, so it is definitely doable and speaks of the great quality of this server!

**Comment by Vaxsysl** [comment] 2015-05-22 12:47
Horde version needs tweaking. Communicator wasn't in the loot table or was it dropped on the ground, or was anywhere in the cave.

**Comment by ashido96** [comment] 2015-05-25 05:12
Can confirm, Communicator has a bugged drop rate while on this quest.

**Comment by ImprezaWoW** [comment] 2016-06-14 19:10
HORDE SIDE: Khaliisi's pet Frostbite seems to be unmountable again. Works fine in PTR, but not in Algalon.

**Comment by Rushor** [comment] 2016-11-24 10:04
todo:
- move ai to vehicleai
- update spellclick
- update loot

**Comment by Rushor** [comment] 2016-11-24 10:42
Scripts/Quest: Sniffing Out the Perpetrator - Update Vehiclescript

* Frostbite will no longer stop his path and will not try to attack the summoned Stormforged Pursuer
* Stormforged Pursuer will despawn after 5 seconds if they are not in combat
* added spellclick condition, you will no longer able to mount on Frostbite if you don't have the quest active
* Brann's communicator will dropp propperly now from Tracker Thullin
* closes https://github.com/dalaranwow/dalaran-wow/issues/330

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 10:42 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by mahiro123** [comment] 2018-01-20 07:45
Quest seems to have bugged again, can't mount Frostbite, thus unable to complete the track scent part of the quest.
