### ISSUE TITLE
[Item] Slag Covered Metal

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3864] opened 2016-11-19 13:52 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
The item Slag Covered Metal is needed to continue the Sons of Hodir quest line. It is dropped by Stormforged Iron Giants east of Dun Niffelem, Storm Peaks.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The item has no requirements to drop, so as soon as you are phased in where Stormforged Iron Giants exist, you can kill them and take the item, and be in 2 parts of the chain at the same time. (with GM you can be level one, teleport to them with having no quests done and still get the item to drop)

The main problem with that is, that if you are currently doing quests in Brunnhildar Village, and you get the item (and, as it is expected, continue on with the chain from the item before backing to the Brunnhildar quests), once you reach the quest Forging an Alliance, you phase out and can not do Brunnhildar Village quests with Forging an Alliance in your logs/completed.
**Expected behaviour**: Tell us what should happen instead
The item should only drop from the Giants when you have completed the quests from Brunnhildar Village and go on to doing Thorim's quests, so it should drop when you have the quest Sibling Rivalry in your logs, or in other words, when you have completed the quest The Drakkensryd

**Include proofs for this behaviour**

http://www.wowhead.com/faction=1119/the-sons-of-hodir#comments:id=385769
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wowwiki.wikia.com/wiki/The_Sons_of_Hodir_quest_chain
[The Drakkensryd](http://www.wowhead.com/quest=12886) quest ID 12886
[Slag Covered Metal](http://www.wowhead.com/item=41556/slag-covered-metal) item ID 41556
[Stormforged Iron Giant](http://www.wowhead.com/npc=29375/stormforged-iron-giant) NPC ID 29375

**Comment by Rushor** [comment] 2016-11-21 11:18
http://www.wowhead.com/item=41556/slag-covered-metal#comments:id=1695739:reply=908734

You can get it after accepting quest Mending Fences (//www.wowhead.com/quest=12915/mending-fences)

some other wotlk sources say this too.

i will add that the item will drop if you have quest 12915: taken, rewarded or completed

**Comment by Rushor** [comment] 2016-11-21 11:22
DB/Item: Slag Covered Metal - Droppcondition

* closes https://github.com/dalaranwow/dalaran-wow/issues/3864
* commit: 936f06f3f19003829556aa741696efc66053c0e1

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-21 11:22 UTC
Labels: Items, On PTR

**Comment by TeridanDW** [comment] 2017-03-30 13:50
Works as intented on ptr.
