### ISSUE TITLE
[ToC][Jaraxxus] Nether Power spellsteal

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4614] opened 2017-03-20 14:40 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Nether Power refreshes its 30 second duration each time it is spellstolen. This can be abused to achieve a very high uptime (100% from first stack is on boss).

**Expected behaviour**: Tell us what should happen instead
When you spellsteal Nether Power, you should get the duration that the npc had on his Nether Power.

**Steps to reproduce the problem**:
1. Play mage on Jaraxxus
2. Spellsteal all but one Nether Power Stack
3. Use the last Nether Power stack to keep up your Nether Power until the next time Jaraxxus gets new ones for you to steal.

**Include proofs for this behaviour**

**Lord Jaraxxus LIVE (2010-01-28):**
`[{"spellNames": ["Nether Power"]}]`
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/log/?s=2643&e=2836
![http://i.imgur.com/lylIQgZ.png](http://i.imgur.com/lylIQgZ.png)
The mages reacted in 1-2 seconds respectively, but the stacks still expired 30 seconds after the boss gained them.

**Lord Jaraxxus Dalaran:**
`[{"spellNames": ["Nether Power"]}]`
http://www.worldoflogs.com/reports/pgonbm9oz5byleq7/log/?s=1710&e=1925
![http://i.imgur.com/992yDMr.png](http://i.imgur.com/992yDMr.png)
![http://i.imgur.com/ERPeOjH.png](http://i.imgur.com/ERPeOjH.png)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/?search=lord+jaraxxus#npcs
http://wotlk.openwow.com/?search=nether+power

**Comment by Teridan-dal-wow** [comment] 2017-03-20 15:52
Hello, thank you for the report, however i can't reproduce the issue you described.
Tested on TC.

![wowscrnshot_032017_174849](https://cloud.githubusercontent.com/assets/6797611/24108236/bb5de214-0d95-11e7-82c3-2b5a30a0c3ab.jpg)
![wowscrnshot_032017_174857](https://cloud.githubusercontent.com/assets/6797611/24108242/bde9340c-0d95-11e7-8930-7836f4894def.jpg)

**Comment by plznoz** [comment] 2017-03-20 15:53
Might be related with @Lothloryen's fix of "invisible stacks" perhaps?
https://github.com/dalaranwow/dalaran-wow/issues/3694

**Comment by Rushor** [comment] 2017-03-20 18:03
That was fixed on TC, it will be merged from TC on the live realm in the future. Thank you

**Closed by Rushor** 2017-03-20 18:03 UTC
Labels: Area - Instances, Fixed - On PTR

**Comment by TeridanDW** [comment] 2017-03-30 08:53
Works as intented on PTR.
