### ISSUE TITLE
[Shaman] Lava Lash 25% bonus isn't working

### ISSUE THREAD

**Issue by Jiokko** [dalaranwow/dalaran-wow#2054] opened 2014-11-07 22:52 UTC
After extensive tests on dummy i noticed that lava lash is not increased when you have flametongue on off-hand. The 25% bonus damage you should have on offhand attack upon Lava Lash hit does not exist. Take a look at the following screenshots.

1) http://i.imgur.com/1nJWkGX.jpg
in that first screenshot i have on both weapons the windfurry enchant, the damage of lava lash is shown

2)http://i.imgur.com/UAF4uCu.jpg
in the second screenshot as you can see i have windfurry and flametongue on offhand, (you can check on the damage done by flametongue). You can clearly see as you compare the two screenshots that the damage is almost the same and the weird thing is that when i had not flametongue at offhand the average Lava Lash damage is just a bit lower (but im gonna say they re almost the same, as the lava lash talent isnt giving the 25% bonus damage).

Take in notice that i have the glyph of Lava lash and got the 2set bonus of t8 set.

**Comment by fishworld** [comment] 2015-01-10 09:44
I can confirm this as well.

**Comment by Trobie** [comment] 2015-03-12 00:27
Yeah the problem still exists if I have done my counting right. It is just as Muircheartach says: it really makes you doubt if you wanna continue playing enh shaman when this problem still exist.

**Comment by juan9669** [comment] 2015-07-27 15:29
seems like the problem still exists

**Comment by klm670** [comment] 2016-05-18 12:40
Still doesn't work...

**Comment by Rushor** [comment] 2016-11-29 19:56
Scripts/Spells: Fix glyph bonus from lava lash glyph

* closes https://github.com/dalaranwow/dalaran-wow/issues/2054
* commit: b34f78a8f9504e1a17b43910810071ead64831f3

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 19:56 UTC
Labels: Class - Shaman, Fixed - Waiting for PTR Update

**Comment by lsn371** [comment] 2017-02-11 03:51
it's not about the glyph but about the ability itself

http://wotlk.openwow.com/spell=60103

**Comment by Rushor** [comment] 2017-02-11 13:03
my fix should solve that, needs testing on PTR.

**Comment by Lothloryen** [comment] 2017-10-18 20:03
Hello there, need testing on PTR.

**Comment by TeridanDW** [comment] 2017-10-19 08:46
Works as intended on PTR.

![wowscrnshot_101917_114158](https://user-images.githubusercontent.com/6797611/31762192-1ec71b16-b4c3-11e7-978a-6eac8835e17e.jpg)
![wowscrnshot_101917_114311](https://user-images.githubusercontent.com/6797611/31762196-209c4876-b4c3-11e7-804f-551ce2f7c748.jpg)
![wowscrnshot_101917_114540](https://user-images.githubusercontent.com/6797611/31762197-220a97f8-b4c3-11e7-8df3-c8a8b0cb8c34.jpg)
