### ISSUE TITLE
Bane/Emberstorm

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2657] opened 2015-07-14 09:10 UTC
Bane/Emberstorm flat portion are applying not as first casting speed reduce (as it should) but as last one making all of other haste/speed increase buffs totally op on destruction warlock.
See over tooltip and actual cast. 
Emberstorm
![wowscrnshot_071415_114223](https://cloud.githubusercontent.com/assets/13163879/8669941/45c8128a-2a21-11e5-8c33-03e2b21cc5b5.jpg)
Bane
![wowscrnshot_071415_115221](https://cloud.githubusercontent.com/assets/13163879/8669942/46aca3a0-2a21-11e5-8190-6406c6f535f6.jpg)
![wowscrnshot_071415_114124](https://cloud.githubusercontent.com/assets/13163879/8669943/48333e3c-2a21-11e5-8165-ea48b89b999b.jpg)
![wowscrnshot_071415_114240](https://cloud.githubusercontent.com/assets/13163879/8669946/4a6122be-2a21-11e5-91c7-47b79833c138.jpg)

**Comment by Vidmantasaf** [comment] 2015-07-14 09:13
It is possible that Holy Light talent works in same way/ Shaman tidal waves are also bugged (because of same way working -0.5 sec to cast talent)
The sequence of application right now is : Speed increase-> Haste-> Bane
Should be : Bane (flat)-> speed increase(various talents like backdraft/decimate etc) -> haste

**Comment by Marquito01** [comment] 2015-07-14 09:31
Confirm, its actually a global bug with talents that apply flat haste (e.g. Bane, Improved Healing Wave) and talents that apply further % reduction (e.g. Decimation, Backdraft, Tidal Waves). Basically the problem is the % reduction talent applies as first and the flat reduction applies after as second. Should be the other way around.

Most affected spell is Soulfire (with Bane + Decimation), where the cast time is 0.8s less then it should be (hence the uber bugged lock dmg and weird 1/2 destro, 1/2 demo spec ppl run around here with which was subpar on retail). 
Dont know all the bugged combinations, but the bug is present also with Chaos Bolt, Immolate, Soulfire (Bane + Backdraft), Incinerate (Emberstorm  + Backdraft), Healing Wave (Improved Healing Wave + Tidal Waves).

leaving link to my detailed old report: http://wotlk.openwow.com/spell=17792

and screen of Shaman Improved Healing Wave + Tidal Waves bug:
![healing wave](https://cloud.githubusercontent.com/assets/12214615/8670047/b1e995c2-2a19-11e5-9a1a-3de1ac8436d5.png)

Pls have a look at it as its quite serious bug. Someone also pls test rest of the classes (apart from shaman, lock and mage) which I dont have on the server.

**Comment by Tarpor** [comment] 2015-07-14 10:20
COMPLETELY GAMEBREAKING OH MY GOD, I get it that it has to be fixed but jesus edit your title

**Comment by Vidmantasaf** [comment] 2015-07-15 16:11
There is class with similar effects that work correctly : holy paladins/druids (+15% casting speed from judgement/ 0.5 hl reduce from talent Light's Grace, just checked working as intended, as well as druid Nature's Grace & Starlight wrath talent, both working correctly

**Comment by Vidmantasaf** [comment] 2015-07-15 19:20
https://www.youtube.com/watch?v=1U-pdYH3r8U check his 1.6 shadowbolts (very high haste plateau), without emberstorm (has demo form) has 1.5 soulfire with decimate, 1.2 with decimate+molten core, in this server 0haste lock has 1.6

**Comment by Vidmantasaf** [comment] 2015-07-16 13:01
bump, just copy the principle from druids/holy paladins and apply to resto shamans/locks and it will be fixed.

**Comment by Rushor** [comment] 2016-11-29 21:10
should be fixed with the commit from https://github.com/dalaranwow/dalaran-wow/issues/3249#issuecomment-263689801

**Closed by Rushor** 2016-11-29 21:10 UTC
Labels: Class - Shaman, Class - Warlock, Fixed - Waiting for PTR Update
