### ISSUE TITLE
[Quest][Classic] Pyrewood Ambush not working

### ISSUE THREAD

**Issue by Tykune** [dalaranwow/dalaran-wow#3715] opened 2016-09-14 21:17 UTC
**Description**:
Starting the quest, the NPC (Faerleia) just sits there and doesn't assist at all in killing the required targets. When killing the targets beside them, still does not complete it. The quest simply does not work. I have abandoned and taken up the quest several times.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
You accept the quest inside the building and she does nothing. The council NPCs spawn all at one time, which I am certain they are not supposed to.. but in either case, I killed them multiple times with no success in completing the quest.

**Include proofs for this behaviour**
You can go to the NPC yourself and check out the behavior. It is obvious.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/quest=452/pyrewood-ambush

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-13 09:21
Scripts/EasternKingdoms: Update script for quest: Pyrewood Ambush

* closes https://github.com/dalaranwow/dalaran-wow/issues/3715
* Faerleia and the hostile creatures will noe attack each other
* also fixed the $C error in the quest-complete-text
* commit: 031d8c0964ee02c52a86211e0c61cc480b2d9793

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 09:21 UTC
Labels: Continent - Classic, On PTR, Priority - Low, Quests

**Comment by TeridanDW** [comment] 2017-03-31 11:48
Works as intended on ptr.
