### ISSUE TITLE
[Quest] Misplaced quest: Urgent Delivery!

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1944] opened 2014-10-07 20:30 UTC
http://www.wowhead.com/quest=9409

This is the one of starting Draenei quests that should be offered by **Proenitus** (http://www.wowhead.com/npc=16477) after you complete either version of  _Replenishing the Healing Crystals_ (http://www.wowhead.com/quest=9280 for Draenei, http://www.wowhead.com/quest=9369 for other races). 

Chain should look like this:
- _You Survived!_ (http://www.wowhead.com/quest=9279, draenei only)
- _Replenishing the Healing Crystals_ (either http://www.wowhead.com/quest=9280 or http://www.wowhead.com/quest=9369)
- _Urgent Delivery!_ (http://www.wowhead.com/quest=9409)

Currently player is able to pick up _Urgent Delivery!_ anytime regardless of previous requirements, potentially breaking the chain (and story logic).

**Comment by n-ghost** [comment] 2015-06-08 13:29
Was fixed roughly a week ago, Ammen Vale now feels much more blizzlike, thanks!

**Comment by Rushor** [comment] 2016-11-23 10:18
DB/Quest: Urgent Delivery! - Update prequestorder

* closes https://github.com/dalaranwow/dalaran-wow/issues/1944
* commit: 6773dab5d32a0920bbc61743d97c780fd6a2e10e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 10:18 UTC
Labels: Continent - Classic, On PTR, Quests
