### ISSUE TITLE
Dispersion unable to cast

### ISSUE THREAD

**Issue by JebsterWrath** [dalaranwow/dalaran-wow#1571] opened 2014-05-02 09:45 UTC
An issue I've seen before a few times in Wintergrasp, is not being able to cast Dispersion while you are stunned (and occasionally when you are silenced). In the tooltip, is says that Dispersion can be "cast while stunned, feared, or silenced and clears all snare and movement impairing effects when cast, and makes you immune to them while dispersed". I have also been stunned and feared during this time, which is fairly game-breaking for priest PvP.

**Comment by Golganeth** [comment] 2016-06-19 17:57
Can't reproduce, closing up until more proof to support the bug is given.

**Closed by Golganeth** 2016-06-19 17:57 UTC
