### ISSUE TITLE
[Ulduar] Ignis - Hitbox Size

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3523] opened 2016-06-29 12:39 UTC
Currently, the hitbox for Ignis in Ulduar is too small.  It requires melee to get all up in his guts when on retail he had quite a large hitbox.  The small hitbox also means that melee is usually hit by each scorch that Ignis dumps, even if they are dpsing from his rear.

This tankspot video shows that there is probably a 15 yard (give or take) distance that a player can be from Ignis center and still be in melee range.
https://www.youtube.com/watch?v=Hp50gUCAqwc
Skip to about 50 seconds. After the tank turns Ignis while he's dropping a scorch you can see a player with the Ice Block raid icon meleeing the boss from a pretty decent distance away. The frontal AoE of the Scorch also does not hit any melee that are behind Ignis.

**Comment by Golganeth** [comment] 2016-06-29 12:44
Duplicate of #3194

**Closed by Golganeth** 2016-06-29 12:44 UTC
