### ISSUE TITLE
[NPC][Vendor] Usuri Brightcoin <Money Changer>

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4521] opened 2017-03-03 16:37 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
This vendor only converts Badge of Triumph into Badge of Valor.
> Emblem of Triumph => Emblem of Valor

**Expected behaviour**: Tell us what should happen instead
Should be able to convert all badge types to a lower one.
> Emblem of Triumph => Emblem of Conquest => Emblem of Valor => Emblem of Heroism

**Steps to reproduce the problem**:
1. Go to NPC to convert your triumphs to conquest while sleepy
2. Shift-click the badges, enter 58 for your new shiny t8.5 token
3. Get scammed xd

**Include proofs for this behaviour**
![http://i.imgur.com/TA2WGDm.png](http://i.imgur.com/TA2WGDm.png)
http://www.wowhead.com/npc=35790/usuri-brightcoin#comments:id=813065
http://wotlk.openwow.com/npc=35790

**Comment by Rushor** [comment] 2017-03-03 19:39
DB/Creature: Usuri Brightcoin <Money Changer> - Add all Emblem change options

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4521
* commit: 4cee5cfe8dd050cba6e9509ba667d29aee41bd22

![GitHub Logo](http://i.imgur.com/VoZZ7IO.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-03 19:39 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR Update

**Comment by ImprezaWoW** [comment] 2017-03-05 14:14
Hello, your ticket has been reviewed and the emblems will not be refunded. Even if the issue is present and one tier was skipped, as seen from the screenshot you are fully aware of what you are receiving both from the description and the image. Thank you for the report nonetheless.

**Comment by alexuktc** [comment] 2018-11-22 18:15
Hello there.

The issue was described as fixed on 3 March last year. The NPC still only offers Valor to Heroism.
