### ISSUE TITLE
Misc Issues

### ISSUE THREAD

**Issue by daibheid** [dalaranwow/dalaran-wow#2189] opened 2015-01-23 01:55 UTC
- Spiritual Attunement isn't working - get no mana back from being healed
- Silence effects (kick, pummel, avenger shield) do not always work

**Comment by Aegletes** [comment] 2015-01-23 21:00
Do you have logs for Spiritual Attunement not working?

(https://github.com/dalaranwow/dalaran-wow/issues/190)

**Comment by daibheid** [comment] 2015-01-24 01:43
Seems like it is giving about 1% of amount healed sometimes, instead of 10%
all the time

On Fri, Jan 23, 2015 at 4:00 PM, Aegletes <notifications@github.com> wrote:

> Do you have logs for Spiritual Attunement not working?
>
> (#190 <https://github.com/dalaranwow/dalaran-wow/issues/190>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dalaranwow/dalaran-wow/issues/2189#issuecomment-71264957>
> .
>



-- 
   Ian D Berghorn
   MS, NREMT-P
   860-989-9855

**Comment by daibheid** [comment] 2015-01-26 20:22
![spirattun](https://cloud.githubusercontent.com/assets/10663372/5907705/2c3b1bfa-a56f-11e4-9edf-141e6e710b61.png)

**Comment by Golganeth** [comment] 2015-01-30 13:44
- Spiritual Attunement works as intended, the question is how close you were to full mana. There is no such thing as "Overmanaed"
- The only issue with interrupts is #182 which is already reported.

Closing up.

**Closed by Golganeth** 2015-01-30 13:44 UTC
