### ISSUE TITLE
[Quest] Aquementas - No item on kill

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1347] opened 2014-03-15 14:39 UTC
The quest Aquementas (http://wotlk.openwow.com/quest=4005) sometimes gets bugged; after the summoned creature Aquementas (http://wotlk.openwow.com/npc=9453) is defeated, it should give you a Silver Totem of Aquementas (http://wotlk.openwow.com/item=11522) in your inventory. It didn't drop it or give it to me in my inventory the first try. The second try, it did though (i think I stood closer to him), but I didn't have to kill it, I just got the item randomly in my bag

**Comment by Tarpor** [comment] 2015-03-31 13:41
Can confirm, it seems like the mob has to hit you to get the completed message. Quest doesn't work at all how it's supposed to. I first oneshot it (as I'm level 80) and didn't get credit, after 5 minutes of waiting and letting the mob hit me, I got the complete on the first hit.

**Comment by Rushor** [comment] 2016-11-23 20:46
Scripts/Kalimdor: Aquementas - also add item on kill

* closes https://github.com/dalaranwow/dalaran-wow/issues/1347
* commit: 34d66ffde2d489fda1c01625b79ce84ae6f96dc4
* you will get the item if you have enough empty bagspace (like mentioned in http://www.wowhead.com/quest=4005/aquementas#comments:id=107399)
i added, that you will also get the item, if you kill him

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 20:46 UTC
Labels: Continent - Classic, On PTR, Quests
