### ISSUE TITLE
[NPC][Sunwell Plateau] Felmyst - Invisible

### ISSUE THREAD

**Issue by erayberkan** [dalaranwow/dalaran-wow#3574] opened 2016-07-10 21:50 UTC
How it Should be
after killing brutallus Felmyst should be revived as a undead dragon and after killing her kalecgos should come and open the way (firewall)

How it is

Felmyst the third boss in Sunwell Plateau is spawning as invisible hard to spot npc and when she dropped to %50 health she kills most of the raid members with one strike (which we never saw )impossible to kill

**Comment by Crispybuilt** [comment] 2016-07-10 22:12
Can confirm this.

**Comment by dreamingdust** [comment] 2016-07-14 21:45
There has been a Felmyst kill achieved on the Horde side. What was needed was a really high amount of DPS, so I believe the raid wiping strike is set not health percentage, but on time. What other has been occurring in our Raids is a massive crash for the World of Warcraft client of everyone but one person (that person is always the one who gets a spell casted on him that looks like a beam, ending with an Orb surrounding the person).

In order to recreate this you need more than one person to be present at the time of the encounter and just let Felmyst attack you, without killing her.

**Comment by erayberkan** [comment] 2016-07-15 11:54
What do you mean by letting her attack without killing her? How long should we wait before killing her or how are we eve gonma kill her its impossible we were 24 man 17 80s and we failed anyway and we tried 4 times and she is invisible so we cant even plan an attack because we cant ee where she is

**Comment by dreamingdust** [comment] 2016-07-17 18:11
The "In order to recreate this you need more than one person to be present at the time of the encounter and just let Felmyst attack you, without killing her." was meant for the Grand Masters that may try to receive the same results as the above mentioned, in case they want to check the bugs on their own.

About your issue, it doesn`t matter how many 80s you have in your raid, if they do low DPS. As I have said in my previous comment, you need to have people with high DPS (the level doesn't even matter since I have seen lvl 70 people do over 5k DPS). In our kill we had Felmyst down  in less than 30 seconds.

**Comment by erayberkan** [comment] 2016-07-17 22:33
30 seconds ? Oh god how is that even possible can you tell what kind of classes you had in the group ?

**Comment by dreamingdust** [comment] 2016-07-19 13:59
If I have to tell you the exact composition of the raid group, I would lie you. What we had was 2 Tanks, 3 Healers (2 of them Priests, that were mostly spamming Mass Dispell) and everything else was DPS. The group was full, or nearly full (22+ /25). Our average DPS would have been around 8k.

**Comment by dreamingdust** [comment] 2016-07-19 22:12
Update: We were able to kill Felmyst tonight again. We had 22 /25 Raid members. Here is a screenshot of the dead Felmyst. Unfortunately my recount is not showing the right admount of DPS because of a combat bug. We killed it in around 30 seconds again.

http://imgur.com/gallery/34HZBQK/new

**Comment by erayberkan** [comment] 2016-07-20 09:27
Do you have an alliance character which can aid me sometime ? And also the felmyst is invisible to us in algalon realm but you can actually see her it has fixed or something?

**Comment by dreamingdust** [comment] 2016-07-20 12:49
I am having alliance characters but none of them are geared. I know of a person that has done SWP on the alliance side, but I was not informed if they have killed Felmyst. The problem on the alliance side with such Old-School raids is that not many people want to join them, and you surely need a full group for Felmyst. In case to aid you, I can come for the tactics, tho, I don't think this bug tracker is the place for such conversation. If you want to reach me in-game you can write a mail to Holydream.

**Comment by Rushor** [comment] 2016-11-14 10:47
Scripts/SunwellPlateau: Felmyst - Encounterchanges

* Felmyst  is now always visible
* Felmyst  announces his breath by raidemote
* Felmyst selects the correct flightpath during flightphase
* reduced the health of the summoned skeletons
* Demonic Vapor trigger are no longer visible for player
* closes https://github.com/dalaranwow/dalaran-wow/issues/3574

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 10:47 UTC
Labels: Instances, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 08:29
I don't think this is on the ptr yet.

**Comment by alexuktc** [comment] 2018-06-10 08:32
Hello

We tested Felmyst twice in the last two weeks as we were told a change is made. There certainly is one as the encounter starts differently and flight phase is different as well. Here are the issues we encountered:

1. Once Brutallus dies Felmyst automatically engages. In retail she would fly above and will have to be pulled with a ranged attack/spell. She certainly did not engage immediately after. 
2. In flight phase she started casting the Fog of Corruption (Mind Control) in the position she currently was facing when she last used her Corrosion (the beam at the start of Phase 2). Assuming you have the healing this trivializes the fight. The idea is that she has 3 preselected paths she takes at random to perform the Fog of Corruption.

https://www.youtube.com/watch?time_continue=123&v=m83ubgODAn4 Shows those paths

Lastly, a perfectly drawn explanation of what happened on our try. I can try and get groups to down her before the first flight phase, but I would prefer an encounter that can go past that to experience the fight fully.

![felmyst](https://user-images.githubusercontent.com/24550199/41199847-fa2f55a6-6ca1-11e8-88d6-54e6f73cb52d.png)
