### ISSUE TITLE
Warrior Charge over charging every time

### ISSUE THREAD

**Issue by Unbeef** [dalaranwow/dalaran-wow#3655] opened 2016-08-15 22:28 UTC
**Description**:

**Current behaviour**: When i charge as a warrior, I have to step back in order to hit the mob. Every time i charge, every single mob.

**Expected behaviour**:  You should charge infront of the mob and be facing it,  Not on top of npc.

**Steps to reproduce the problem**:
1. Charge a mob
2. Charge a mob
3. Charge a mob

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment] 2016-08-28 18:58
On PTR.

**Comment by Rushor** [comment] 2016-11-12 14:15
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-03-31 14:02
Works as intended on ptr.

**Comment by Crispybuilt** [comment] 2017-10-16 15:44
*Doesn't work anymore as intended on PTR or Live.*

- Charge/Intercept still puts you inside the hitbox of a mob and not infront of him.
- On top of that, charging larger scale mobs will also result in a small bounce on top of it which is very annoying. (most likely a pre-measure to avoid falling through the ground, not so good work-around.

**Bounce included, smaller scale NPCs:**
![giphy1](https://user-images.githubusercontent.com/5054924/31621096-2fedcca4-b299-11e7-93c6-a62011ba4195.gif)

**No bounce, biger scale NPCs:**
![Uploading giphy2.gif…]()

--------

*Addtional info*
Charge/Intercept was working very well almost a year ago for a week or two, but it got messed up again.

**Comment by Lothloryen** [comment] 2017-10-16 18:15
Deployed on PTR, remember also to test possible issues with textures, please.

**Comment by Crispybuilt** [comment] 2017-10-16 18:43
**Test results on PTR**

- Charge/Intercept greatly improved in terms of pathing/final destination in between 
Player - NPC
- Checked Caves, Flat terrain, Water, Hills, Dungeons/Instances different zones -  seems quite natural compared to retail.
- Larger scale/hitbox NPCs are now chargeable/interceptable such as Lord Marrowgar/Sindragosa in Icecrown Citadel and the distance is calculated properly.

No path available still exists with some small terrain, but it is in very minor and rare occasion (which is to be expected)

**Comment by bewiserdude** [comment] 2017-10-22 01:55
Hello, after recent changes to Charge mechanics, I began to fall through textures at battlegrounds way too often. This happened today too.

**Comment by gnaruwar** [comment] 2017-11-24 19:44
HEllo i confirm that this bug is again present in the game , is very annoyng.

**Comment by TeridanDW** [comment] 2017-12-02 10:51
Related issue to charge mechanic #5123

**Comment by robinsch** [comment] 2017-12-03 13:58
On PTR again.

**Comment by Aridam** [comment] 2018-05-12 09:42
Still an issue on moving Targets as my report states.

Also there's still a random upwards juttering movement while Charging a Target.

Progress?

**Comment by Aridam** [comment] 2018-05-19 18:27
This an issue -- my closed report regarding arriving points on moving Targets as well.

**Comment by Aridam** [comment] 2018-05-25 13:37
This is still a major issue and every moving thing makes this issue give a hernia. Anything on this yet?

**Closed** 2019-05-14 14:43 UTC
Labels: Class - Warrior, Fixed - On Live Server, General - Mechanics, Listed - Changelog, Priority - High

**Comment by Aridam** [comment] 2019-07-26 14:08
Bump.

Still an issue -- an example would be using Charge on a Wintergrasp Tower Cannons, getting you dead-center into it and oftentimes unable to even attack unless you move. That's a completely-stationary Target at all times, even.
