### ISSUE TITLE
[Quest][Northrend] A bear of an Appetite

### ISSUE THREAD

**Issue by RoflcopterRego** [dalaranwow/dalaran-wow#3475] opened 2016-06-20 17:38 UTC
For the Grizzly Hills quest A Bear of an Appetite:

"School of Northern Salmon" nodes do note disappear when used with Fishing Net. Schools should disappear after being used and respawn a short time later.

**Comment by Rushor** [comment] 2016-06-21 15:46
85c2e6236b56dc8e20cc6ba76b4e77d06b032a10
Scripts/Northrend: Quest A bear of an Appetite - Add despawn for School of Northern Salmon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3475

**Comment by Golganeth** [comment] 2016-06-21 19:31
Even if it despawns you can still spam the quest item on the same spot and get credit.

**Comment by Rushor** [comment] 2016-11-25 11:45
http://wotlk.openwow.com/quest=12279

**Comment by Rushor** [comment] 2016-11-25 11:59
Scripts/Quest: Improve scripts for quests Breakfast Of Champions and A Bear of an Appetite 

Properly despawn the related GameObjects after use of the quest item, avoiding multiple use and summon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3475
* commit: 85c2e6236b56dc8e20cc6ba76b4e77d06b032a10
* commit: 4330978620f0937c431f8721b81dc8041ae6b64a

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 11:59 UTC
Labels: Continent - Northrend, On PTR, Quests
