### ISSUE TITLE
[Warlock] Glyph of Shadowflame

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#1501] opened 2014-04-14 13:41 UTC
http://wotlk.openwow.com/item=45783
http://wotlk.openwow.com/spell=61290

What's wrong: If Shadowflame's initial damage is absorbed there will be no slow effect on enemy.
How it should work: As long as Shadowflame successfully hits it's target slow effect should be applied too.

**Comment by Rushor** [comment] 2016-12-12 18:39
spell_proc needs to be adjusted

**Comment by Rushor** [comment] 2016-12-12 20:04
DB/Spell: Warlock - Glyph of Shadowflame - Apply movement-sloweffect also if damage was absorbed

* closes https://github.com/dalaranwow/dalaran-wow/issues/1501
* commit: 

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-12 20:04 UTC
Labels: Class - Warlock, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-20 08:50
Works as intended on PTR.
