### ISSUE TITLE
Barkskin reduce damage done as well

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5560] opened 2018-08-01 06:24 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Barkskin reduces damage taken by 20% but reduces damage done by 20% as well.

**Expected behaviour**: Tell us what should happen instead
From description it should have affect damage taken only and **not** damage done.

**Include proofs for this behaviour**
I did lot of tests on damage by hurricane on mobs in scholazar unfortunately have no data available. But was clearly visible by damage(max crit. 800 with barkskin and 1000 without barkskin, NOTE was in resto spec to survive) and in skada meter addon

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

https://wowgaming.altervista.org/aowow/?spell=22812

**Comment by alexuktc** [comment] 2018-08-01 16:27
I will test this

**Comment by Zarjofgt** [comment] 2018-08-02 02:16
LOL no

**Comment by Tziva** [comment] 2018-08-02 13:34
Area damage and healing caps limit Area of Effect abilities to a specified multiplier of damage or healing, based on the number of targets affected.For damaging abilities, from 1 to 10 targets, the total damage will increase linearly with each target affected. After that, the total damage output is capped and the amount of damage each individual target will take decreases proportionally.
  Before patch 3.3, the damage cap was completely static based on the rank of the ability, back when abilities had fixed ranks, and increasing damage would mean that players would hit the cap against fewer and fewer targets.Before Patch 2.2, there was no damage cap and damage output would increase linearly without limit.
  Instead of a hard cap on total damage done, the game now caps the total damage done at a value equal to the damage the spell would do if it hit 10 targets. In other words, if a spell does 1000 damage to each target, it would hit up to 10 targets for 1000 each, but with more than 10 targets, each target would take 10,000 damage divided by the number of targets. 20 targets would be hit for 500 damage each in that example.
 So I think barkskin has nothing to do with your issue.

Oh and Zarjo, this is not youtube comment section, so either contribute in a constructive way or keep such pointless remarks to yourself.

**Comment by Golganeth** [comment] 2018-08-02 14:52
I can't reproduce the issue described with barkskin, so I'm closing up until valid proof is provided.

**Closed by Golganeth** 2018-08-02 14:52 UTC

**Comment by Zarjofgt** [comment] 2018-08-23 12:54
@tzvia why would I be constructive to such a ridiculous big report? And why do you write a wall of unrelated bullshit?
