### ISSUE TITLE
[Quest] A Life Without Regret

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3872] opened 2016-11-21 19:54 UTC
**Prequest** A Life Without Regret - ID: 13266

- **Issue Present:** 
After accepting the quest from Thrall to continue your journey to the Undercity, there won't be any portals opened to the main gate of the Undercity.

- **How it should work:**
A portal should open immediately after you accept a quest from Thrall which will lead you to The Undercity main gate.

**Links:**
http://wotlk.openwow.com/quest=13266

**Comment by Rushor** [comment] 2016-11-23 07:25
![GitHub Logo](http://i.imgur.com/1zivCef.jpg)
 fixed with the recent reapply of all db fixed on ptr (no specific commit needed)

**Closed by Rushor** 2016-11-23 07:25 UTC
Labels: On PTR, Quests

**Comment by TeridanDW** [comment] 2017-03-30 12:33
Works as intended on ptr.
