### ISSUE TITLE
[Warlock] Death's Embrace no 12% damage increase

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3887] opened 2016-11-27 13:24 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

**Current behaviour**: 12% Damage increase effect from tallent Death's Embrace doesnt work at all.

**Expected behaviour**: Damage should increase when your target is at or below 35% health.But its not.
**Steps to reproduce the problem**:

1. Test drain soul on target wich is above 35%.Write down the numbers
2. Get your target at or below 35%, use drain soul again and you will notice the same numbers as when the target is above 35%
3. Test with any other spell and you will get the same results

**Include proofs for this behaviour**
 - Proofs are in the screenshots below

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

 - [Death's Embrace](http://wotlk.openwow.com/spell=47200)
 - [Drain Soul](http://wotlk.openwow.com/spell=47855)

**Include Screenshots from the issue if necessary**
  <img src="http://image.prntscr.com/image/7e81318bd5bb4339ae25495732c16394.jpeg"><img>  <img src="http://image.prntscr.com/image/aabededfd57c4230a3df848ddc71c42a.jpeg"><img>

**Comment by Rushor** [comment] 2016-11-27 14:08
Game/Spells: Death's Embrace shoud increase the damage of Drain Soul

* closes https://github.com/dalaranwow/dalaran-wow/issues/3887
* commit: da0ac2e7861223c3e5366f7fa691edd410b030bd

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 14:08 UTC
Labels: Class - Warlock, On PTR

**Comment by Rushor** [comment] 2016-11-27 14:09
spell 
http://wotlk.openwow.com/spell=47199
http://wotlk.openwow.com/spell=47200
http://wotlk.openwow.com/spell=47198

will now increase the damage of spells like http://wotlk.openwow.com/spell=47855 with a classmaskaddition of: 0x4000

**Comment by TeridanDW** [comment] 2017-10-20 10:22
Works as intended on PTR.

**Comment by TeridanDW** [comment] 2017-10-20 17:44
Regarding this report I would like to ask some more experienced warlock player this:
Should the damage from drain soul, drain life with interaction of Death's Embrace talent be dynamicly calculated (on each tick) or just once at the start of the cast based on the target's % hp?
Thank you.

**Comment by AttendantTock** [comment] 2017-10-21 20:30
Hello,

I found this source:
https://eu.battle.net/forums/en/wow/topic/1417734974

> Following is just how DoTs are working generally:
> 
> - when the DoT is cast or when the DoT duration is reset (the later only since 4.0.1) all caster buffs are written down with the DoT on target.
> - when the DoT ticks, it checks all debufs on target to recalculate tick damage (caster buffs are not checked on ticks)
> 
> The same is for drains.
> 
> That means
> - you cast DoT or start channeling drain, and got some buff proc right after that: the buff will not be checked by the DoT, channeling drain, until you refresh duration of the DoT (recast DoT, or refresh it with drain tick/haunt/felflames)/drain (interrupt and start draining again). 
> - you cast DoT or start channeling drain, and some debuf is placed on target right after that: the debuff will be checked on the next DoT/drain tick (no need to refresh/recast)
> 
> After that you only need to know what are the buffs and what are the debuffs (which sometimes might be not quite obvious - f.e. Death Embrace is Buff; before 4.0.1 SE was also buff, but now it is debuff)... 
> 
> BTW. The only difference between pre/post 4.0.1 is that before 4.0.1, caster buffs were not refreshed when the DoT duration was reset with Everlasting Affliction. The only exception to that rule before 4.0.1 was haste, because it was written as total DoT duration only (DoTs had constant amount of ticks, but duration varying depending on haste when you had glyph of quick decay). Now haste is written down with both DoT duration and amount of ticks, and it functions exactly as the rest of the buffs...
> 
> That's it. Warlocomotiff explained by examples - here is more detailed explanation into mechanics

This guy then says to someone introducing the Death's Embrace question:

> > I have not personally tested what happens with Death's Embrace. Notably your corruption and unstable affliction will be refreshed (and thus resampled) by everlasting affliction and pandemic regardless.
> 
> 
> **Death's Embrace is a buff - i.e. only updated when you refresh the dot/recast drain.** 

If this is correct and I understood it well, this means option #2, **just once at the start of the cast based on the target's % hp**.

**Comment by TeridanDW** [comment] 2017-10-22 07:02
Alright, then it works as it should on PTR, thank you.
Subject closed.
