### ISSUE TITLE
[NPC] Rare: Grocklar

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#1939] opened 2014-10-06 01:17 UTC
The rare Grocklar only grants about 1694 experience, this is way to low for what he should grant. In patch 3.0.9 he granted 19567 experience for a person at level 76,  which is the level I killed him at. Note, I also soled him.

This quote is an exerpt from a comment found on Wowhead about this particular mob.
http://www.wowhead.com/npc=32422/grocklar#comments

"justkevin2u on 2009/04/01 (Patch 3.0.9)
Confirmed, just killed him solo as a level 76 DK. Combat Log "Grocklar dies, you gain 19567 experience." General Log "You receive loot: [Abandoned Adventurer's Satchel]." "You receive loot: [Rock-Giant's Pinky Cover of the Foreseer]." "You loot 22 Gold, 3 Silver, 51 Copper" "You receive loot: [Frostweave Cloth]x20."

**Comment by Rushor** [comment] 2016-11-23 09:48
you now get 19735 at level 76 for the kill (this cannot be adjusted more specific)

DB/Creature: Grocklar - Increase expereincemod

* closes https://github.com/dalaranwow/dalaran-wow/issues/1939
* commit: 3a7f06336515a2f38efc03a22b6663a6ae50926f

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 09:48 UTC
Labels: Continent - Northrend, On PTR
