### ISSUE TITLE
[NPC][Event] Gankly Rottenfist NPC and mini-event

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#827] opened 2013-09-26 13:17 UTC
There is a NPC in Nagrand that spawns
http://www.wowhead.com/npc=18297/gankly-rottenfist#comments
and GANKS this NPC - She has a respawn time of 1.5 hours.
http://www.wowhead.com/npc=18294

Now the thing here is that this is a mini-event. The 2nd NPC tries to turn in a quest at Harold Lane. The ganker npc then appears and this dialogue occurs:
- Kristen DeMeza says: Hi, Harold. I Have your skins!
- Gankly Rottenfist says: I'll be taking those skins, tiny.
- Kristen DeMeza says: Ack! Somebody help me!

Now at this point a player can jump in and save her. If successful she will give the quest: http://www.wowhead.com/quest=9897

Wowiki:
http://www.wowwiki.com/Gankly_Rottenfist
http://www.wowwiki.com/Kristen_Dipswitch

Long nice read explaninig the whole event:
http://ravenholdtmanor.blogspot.com/2010/04/know-your-rogue-lore-gankly-rottenfist.html

**Comment by Rushor** [comment] 2016-11-14 14:30
DB/Creature: Implement event for Gankly Rottenfist

* closes https://github.com/dalaranwow/dalaran-wow/issues/827
* commit: bfe307bce3821ac917b217fbaf38a4f3a58f11db
* Kristen DeMeza will spawn near the border to zangarmarch. she will walk towards the camp. Once she reached the camp, Gankly Rottenfist will attack and try to kill her. if you protect her and kill Gankly Rottenfist, Kristen DeMeza will give you the quest, else she will die. Kristen DeMeza will despawn automatically ~320 seconds after you protected her (so the event can be repeated several times)

**Note: You must walk to this place:**
![GitHub Logo](http://i.imgur.com/3boXZBM.jpg)
**in order to start event!**

![GitHub Logo](http://i.imgur.com/3boXZBM.jpg)
![GitHub Logo](http://i.imgur.com/4xdEe5b.jpg)
![GitHub Logo](http://i.imgur.com/Em1o1dh.jpg)
![GitHub Logo](http://i.imgur.com/l2FGpG8.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 14:30 UTC
Labels: Continent - Outland, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-04-05 11:47
Works as intended on ptr.
Regarding:

> Note: You must walk to this place -- in order to start event!

Can we fix this by setting both creatures active on spawn @Rushor ?

**Comment by Rushor** [comment] 2018-05-16 14:11
added the active on spawn flag :)
