### ISSUE TITLE
NPC: Neltharaku

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3597] opened 2016-07-19 12:29 UTC
**Description**:
Quick Facts
Level: 72 (Dragon of Blue Dragonflight I think)
Classification: Elite
React: A H
Added in patch 2.2.0
Health: 69,120 
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
He moves continously during his flight without stopping. Once I managed to catch him him and took the quest "Infiltrating Dragonmaw Fortress" after talking to him for a while. I completed the quest, turned it in, but when I wanted to take the next one he just started moving and never stopped. I've been chasing him for over half an hour now...
**Expected behaviour**: Tell us what should happen instead
He should stop at certain locations/positions during his flight or when interacting with players so players can take/turn in quest.
**Steps to reproduce the problem**:
1.  Try to catch him.
2.  Try to talk to him for over 1-2 minutes.
3. 

**Include proofs for this behaviour**
https://postimg.org/image/ea7i2wjgx/
https://postimg.org/image/j4uaynv5z/
https://postimg.org/image/4ha3iqpbr/
https://postimg.org/image/9bfeb1ayv/
As you can see from the pictures, after chasing him for a while, when I catch up to him and try to talk/interact with him, I either get out of range, or he just disappears completly(must be due to a visual bug or the range interact thing).
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
http://www.wowhead.com/npc=21657/neltharaku#starts
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
NPC ID is nr.#21657 I think.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/
http://www.wowhead.com/quest=10836/infiltrating-dragonmaw-fortress
The quest which I completed and turned in, at which point he started moving without stopping.
**Include Screenshots from the issue if necessary**
See above.

**Comment by MrAndersonX** [comment] 2016-07-19 14:36
He seems to have stopped moving completely at one point :
https://postimg.org/image/n9j0y1q81/

**Comment by ImprezaWoW** [comment] 2016-07-21 05:33
https://github.com/TrinityCore/TrinityCore/issues/790
https://github.com/TrinityCore/TrinityCore/issues/11031
May or may not be related?

**Comment by MrAndersonX** [comment] 2016-07-21 10:05
Seems related to https://github.com/TrinityCore/TrinityCore/issues/11031. The other one I don't understand.

**Comment by ImprezaWoW** [comment] 2016-07-23 10:17
Well the comment was targeted more to the developers when they get on it. :)

**Comment by Rushor** [comment] 2016-11-12 21:54
DB/Creature: Neltharaku  - Change inhabittype

* closes https://github.com/dalaranwow/dalaran-wow/issues/3597
* you can now talk with him everywhere
* commit: 8527fa410fb620d71d59c04babe50d940a792830

![GitHub Logo](http://i.imgur.com/mRo53uD.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 21:54 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-03-31 18:58
Works as intended on ptr.
