### ISSUE TITLE
[Mechanic] Charge on/in water -- in further need of pathing improvements.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5458] opened 2018-05-09 12:26 UTC
**Current behaviour**: https://postimg.cc/gallery/yzhif0xa/860816f1/ -- "No path available."

**Expected behaviour**: There clearly should be pathing active; seems Charge got only a minor improvement but much like the descriptions provided in https://github.com/dalaranwow/dalaran-wow/issues/4652 Charge still mostly works if there is some sort of tether available, otherwise it sometimes works, sometimes doesn't -- issue present on-water as well (sometimes so/sometimes not yet-again).

**Steps to reproduce the problem**:

1. Go in/on water;
2. Try to use any Charge Ability on a Target;
3. Note it sometimes works, sometimes doesn't -- "No path available."

**Include proofs for this behaviour**

Screenshots at the start of this issue report.

**Comment by Rushor** [comment] 2018-05-09 14:12
Yes that issue was posted here https://github.com/dalaranwow/dalaran-wow/issues/4652 too. The fix for it is on PTR and will be tested there.

Duplicate of https://github.com/dalaranwow/dalaran-wow/issues/4652

**Closed by Rushor** 2018-05-09 14:12 UTC
Labels: Duplicate / Invalid Report / Cannot reproduce
