### ISSUE TITLE
[Quest] Avenging the Fallen

### ISSUE THREAD

**Issue by p3ak** [dalaranwow/dalaran-wow#3865] opened 2016-11-19 16:13 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
Quest "Avenging the Falles" can be repeated infinitely.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
You can accept the quest and once done, you can accept it again.

**Expected behaviour**: Tell us what should happen instead
Quest should be a one-timer.

**Steps to reproduce the problem**:

1. Go to hinterlands
2. Accept Quest
3. Finish it
4. Accept it again.

**Include proofs for this behaviour**
http://www.wowhead.com/quest=7830/avenging-the-fallen

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest: 7830
Item: 19025
Questgiver: 14741
Zone: 47

**Comment by Rushor** [comment] 2016-11-19 17:49
DB/Quest: Avenging the Fallen - no longer repeatable

* closes https://github.com/dalaranwow/dalaran-wow/issues/3865
* source: http://www.wowhead.com/quest=7830/avenging-the-fallen#comments:id=461168:reply=155437
* If this quest was, at any point, repeatable, it is not any longer.
* commit: 1da0090b95c4e15d49fee495c547261f3753001a

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-19 17:49 UTC
Labels: Continent - Classic, On PTR, Quests

**Comment by Edzero** [comment] 2017-03-28 16:40
Quest Avenging the Fallen can no longer be repeated.
