### ISSUE TITLE
voidwalker, eye of kilrogg, soul shard bugs

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3815] opened 2016-11-08 23:02 UTC
**Description**: after summoning the Voidwalker (which costs 1 soul shard) and then casting Eye of Kilrogg, when you are done using the Eye of Kilrogg and you return to your character, the pet command bar is gone and you cant dismiss your Voidwalker. then when you log out and log back in , your Voidwalker is gone and your soul shard has returned in your inventory

**Current behaviour**: please see description

**Expected behaviour**: it's expected that after summoning Voidwalker, then casting Eye of Kilrogg and then returning to your character the pet command bar is still there and the pet can be dismissed. then it is expected that when you log out and back in, the Voidwalker is still there and the soul shard that you used is still gone forever

**Steps to reproduce the problem**:

1. summon voidwalker
2. cast eye of kilrogg
3. return to your character (cancel using eye of kilrogg)
4. log out
5. log back in

**screenshots**
http://imgur.com/a/qUESu  **before**
http://imgur.com/a/Y68vb  **during**
http://imgur.com/a/rVAwn  **after**

**IDS**
http://www.wowhead.com/spell=697/summon-voidwalker
http://www.wowhead.com/spell=126/eye-of-kilrogg
http://www.wowhead.com/item=6265/soul-shard

**Comment by Rushor** [comment] 2016-11-09 10:44
fixed with https://github.com/dalaranwow/dalaran-wow/issues/3242

with the fix from the other ticket, the petbar will always be visible. I will close this issue because the fix from https://github.com/dalaranwow/dalaran-wow/issues/3242 will also fix this issue https://github.com/dalaranwow/dalaran-wow/issues/3815

**Closed by Rushor** 2016-11-09 10:44 UTC

**Comment by Rushor** [comment] 2016-11-09 10:54
I added some other fixes for the eye of kilrogg on ptr.

Scripts/Spells: Improve Eye of Kilrogg behaviour

* closes https://github.com/dalaranwow/dalaran-wow/issues/3815
1.) Your eye of kilrogg can fly in outland and northend if you have the glyph
2.) Other pets will be despawned once you cast the eye of kilrogg AND will be respawned if the cast of eye of kilrogg is canceled. That fix will also remove the issue that you loose one of the soul shards.
* commit: 6595ebd8c1caf452e5a6936c0b856162fc703b43

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-10-17 08:09
Works as intended on PTR.
