### ISSUE TITLE
[Spell] DoT phasing

### ISSUE THREAD

**Issue by Dovilacus** [dalaranwow/dalaran-wow#4651] opened 2017-03-30 15:24 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
DoT ticks are getting unsynchronized with the DoT duration as it is refreshed while there is still some duration left on target (also known as "clipping").

**Expected behaviour**: Tell us what should happen instead
When a player clips a DoT, it should reset it's current state and be applied as if it was on a new target.

> "Also as of patch 4.0.1, DoTs no longer can be 'clipped'. Previously, if a DoT was refreshed before it had expired, the tick timer was reset, causing a delay of up to double the normal time between ticks between the last tick that occurred and the first tick of the refreshed DoT."

from http://wow.gamepedia.com/Damage_over_Time

Visual representation:
![corruption-clipping-dot-2](https://cloud.githubusercontent.com/assets/25619125/24503520/5b615780-154a-11e7-9422-3dce233d0595.jpg)
from https://cynwise.wordpress.com/2010/10/29/how-warlock-dots-work-in-cataclysm/

**Steps to reproduce the problem**:
Clip a DoT with an x (reasonable, observable) interval between a tick and the refresh, and observe as it's last tick happens x time before the duration is over.
or
Spam a DoT with cast time < tick period and observe as the ticks still go off.

**Include proofs for this behaviour**
Vampiric Touch, Devouring Plague, Shadow Word:Pain, Immolate, Corruption and Curse of Agony were tested.

- Vampiric Touch
https://www.youtube.com/watch?v=iIGuYJdD5fM
- Devouring Plague
https://www.youtube.com/watch?v=YI4OcPFY2ZY
- Shadow Word:Pain
https://www.youtube.com/watch?v=GxJJ6IIAZwQ
- Immolate
https://www.youtube.com/watch?v=BH_lcDU5nPk
- Corruption
https://www.youtube.com/watch?v=SGmt6Sx9F6Q
- Curse of Agony
https://www.youtube.com/watch?v=u4_Z8k2_BGU

https://www.youtube.com/playlist?list=PLXUBbAx-fM4wng-wYmlmPueM5q1QgrBNl

All of the dots except Devouring Plague, showed evidence of not being phased with the DoT duration. 
Note that this model makes sense on a DoT like Shadow Word:Pain, (or other random applied/refreshed DoTs), since it's refreshed by a rotation filler and reseting the tick timer would drastically reduce how much damage it deals. This should be similar to how on-hit debuffs like Deep Wounds work.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/spell=48160
http://wotlk.openwow.com/spell=48300
http://wotlk.openwow.com/spell=48125
http://wotlk.openwow.com/spell=47811
http://wotlk.openwow.com/spell=47813
http://wotlk.openwow.com/spell=12868

**Include Screenshots from the issue if necessary**

Thanks to Diurnum for pointing this out as an issue,
and for your attention reviewing it.
Kind regards,
Dovilacus.

**Comment by Dovilacus** [comment] 2017-03-30 15:26
As a Post Scriptum note:
Currently for maximizing DPS players should be aware of what dots have this behaviour, and such DoTs should be refreshed consistently before the duration is over.
Also I'm curious of how haste changes affects DoTs which durations are affected by the stat.

**Comment by Rushor** [comment] 2017-03-30 20:25
This was fixed in https://github.com/TrinityCore/TrinityCore/commit/b5e8e0a5db69f2d8075c7e16e4e70c4373d4424f  https://github.com/TrinityCore/TrinityCore/issues/17961 and will be merged on the live realm with further TC Merges.

(Note: I also implemented another patchidea for this, if the tc fi does not work was intended, which will be applied after the merge then (if needed))

Game/Spells: Implement DoT Clipping for several auratypes

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4651
* commit: 85e76e649855fbd8488175e13c8bfcb12e3e2614

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-30 20:25 UTC
Labels: General - Mechanics
