### ISSUE TITLE
Pls help me 

### ISSUE THREAD

**Issue by Averox402** [dalaranwow/dalaran-wow#5964] opened 2021-06-18 16:58 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. i kill boos for the quest and and it didnt complete the quest
![World of Warcraft 18_06_2021 19_50_08](https://user-images.githubusercontent.com/85841921/122594377-9b46fc80-d06f-11eb-90d9-ffa95a7d6ad6.png)

2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Chenocide** [comment] 2021-06-18 20:10
What server are you playing on?

**Comment by Golganeth** [comment] 2021-06-20 21:19
Hello.
The quest Morbent Fel works as intended, you must use the quest item before you kill the NPC, in order to trigger the quest credit.

Cheers, closing up.

**Closed by Golganeth** 2021-06-20 21:19 UTC
