### ISSUE TITLE
[Northrend] [Quests] From Their Corpses, Rise!

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3900] opened 2016-11-29 12:44 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 At the moment, the player can use the quest item on a single dead Scarlet member to get 10/10 ghouls and quest complete.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 The quest is currently positively bugged, because the player can use the quest item on only 1 mob to complete the quest.

**Expected behaviour**: Tell us what should happen instead
 After spawning a ghoul from the dead mob's corpse upon using the quest item on it, the player shouldn't be allowed to use the quest item on the same corpse a second time.

**Steps to reproduce the problem**:

1.  Take the quest.
2.  Kill a quest mob (Scarlet Onslaught).
3.  Spam the quest item on the mob's corpse.

**Include proofs for this behaviour**

https://postimg.org/gallery/zrfe34zo/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-29 13:09
DB/Quest: From Their Corpses, Rise! - Add despawnevent for corpses

* closes https://github.com/dalaranwow/dalaran-wow/issues/3900
* commit: 102d73611ae6a6dc9c7314de4912bb535ad085bf

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 13:09 UTC
Labels: Fixed - Waiting for PTR Update, General - Quests
