### ISSUE TITLE
[Quest][WotlK] The Last of Her Kind

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4313] opened 2017-01-25 08:36 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Quest The Last of Her Kind http://wotlk.openwow.com/quest=12983.
Issue 1: is that i player can "mount up" the Injured Icemaw Matriarch http://wotlk.openwow.com/npc=29563 without having the quest.
![wowscrnshot_012517_102224](https://cloud.githubusercontent.com/assets/6797611/22283043/94b1bdb6-e2e8-11e6-8bec-030ead770076.jpg)
![wowscrnshot_012517_102243](https://cloud.githubusercontent.com/assets/6797611/22283045/9abbbd10-e2e8-11e6-826a-f77c3046eab1.jpg)

Issue 2: if you click "leave vehicle" while you are riding the bear, she will attack you:
![wowscrnshot_012517_102312](https://cloud.githubusercontent.com/assets/6797611/22283081/db51ebba-e2e8-11e6-8f3c-1f0d8c8bf2ff.jpg)

Issue 3: after she kills the player, she will return to the spot where you clicked "leave vehicle" and continue its path to the village and despawn at the end of the script.
![wowscrnshot_012517_102405](https://cloud.githubusercontent.com/assets/6797611/22283132/22961f82-e2e9-11e6-9510-41293207c941.jpg)
![wowscrnshot_012517_102422](https://cloud.githubusercontent.com/assets/6797611/22283138/2765e9a2-e2e9-11e6-82ab-47de004e144f.jpg)

**Expected behaviour**: 
Issue 1: You are not suppose to be able to "mount up" the bear wthiout having the quest "The Last of Her Kind"
Proof: https://www.youtube.com/watch?v=YQDNGAEsJ2A
Issue 2: The bear should respawn instantly.
Issue 3: Won't exist if issue 2 is fixed.

**Steps to reproduce the problem**:

1. Remove Quest The Last of Her Kind from your log (make sure you are in the correct phase)
2. Go inside the cave and find the bear.
3. Notice you can "mount up" the bear without the quest.

Related to #565

**Comment by Rushor** [comment] 2017-01-25 13:27
alright scripttodo:

- spellclick condition
- despawn on removed passenger

**Comment by Rushor** [comment] 2017-01-25 13:46
DB/Quest: The Last of Her Kind - Misc Updates

* Harnessed Icemaw Matriarch will now despawn after player leaved the vehicle
* Spellclick for Injured Icemaw Matriarch will only be available if quest 'The Last of Her Kind' is active
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4313
* commit: 6a30928e27d010df1688a6001bf550816b18ad95

![GitHub Logo](http://i.imgur.com/Xx2jtR7.jpg)
![GitHub Logo](http://i.imgur.com/ENVfPZF.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-01-25 13:46 UTC
Labels: Area - Northrend, General - Quests

**Comment by TeridanDW** [comment] 2017-10-24 10:45
Works as intended on PTR.
