### ISSUE TITLE
[NPC] Ghostlands Area missing most NPCs

### ISSUE THREAD

**Issue by Varen** [dalaranwow/dalaran-wow#2736] opened 2015-07-27 03:19 UTC
![78](https://cloud.githubusercontent.com/assets/3650235/8898077/0e026028-341f-11e5-8289-56e52cdd7270.jpg)

The marked area is missing most mobs, making quest completion there rather annoyingly difficult.

**Comment by Khronos-** [comment] 2015-08-17 21:59
Which quest and which mobs?

I quested in the Ghostlands at the beginning of my toon and completed most of them without any issue.

**Comment by Golganeth** [comment] 2015-08-18 16:54
#795

**Comment by Rushor** [comment] 2016-11-12 20:26
DB/Creature: Ghostclaw Lynx & Ghostclaw Ravager & Greater Spindleweb Spawns

* closes https://github.com/dalaranwow/dalaran-wow/issues/2736
* added 90 spawns of Ghostclaw Lynx & Ghostclaw Ravager & Greater Spindleweb 
* commit: b7c92a96f3088f61b1ce3ae33b7051b8d7374876

![GitHub Logo](http://i.imgur.com/sRSFN7u.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 20:26 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 20:31
Works as intended on ptr.
