### ISSUE TITLE
[Priest] Rapture 

### ISSUE THREAD

**Issue by Marquito01** [dalaranwow/dalaran-wow#3890] opened 2016-11-27 22:59 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: Rapture - No ICD

**Current behaviour**: 
As described here https://github.com/dalaranwow/dalaran-wow/issues/2784, Disc priest talent [Rapture](http://wotlk.openwow.com/spell=47537) has no ICD, which gives disc priests infinite mana pool. The original report was merged with https://github.com/dalaranwow/dalaran-wow/issues/1691 and closed, but the second part of merged report never actually got fixed: http://www.dalaran-wow.com/changelog/16/the-dancing-flames.

**Expected behaviour**: ICD 12s

Thx for fix!

**Comment by Rushor** [comment] 2016-11-28 08:30
Game/Spells: Fix cooldown check talent Rapture (Priest)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3890

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 08:30 UTC
Labels: Class - Priest, On PTR

**Comment by TeridanDW** [comment] 2017-10-20 10:41
Works as intended on PTR.
