### ISSUE TITLE
[NPC] Silverbrook Hunter

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2526] opened 2015-06-15 21:01 UTC
The Silverbrook hunter http://wotlk.openwow.com/npc=27546 should transform into worgen after losing an amount of hp (http://wotlk.openwow.com/spell=49561). Also Vladek their leader should transform into a worgen and enrage .http://wotlk.openwow.com/npc=27547
Atm they just dont.
https://youtu.be/NqWb9w1Gvbk
this is a video of the quest 'My enemies friend' http://wotlk.openwow.com/quest=12412 which has them as target.  Unfortunately the character in this video is overgeared and overlvl'd so u wont see the transformation of every silverbrook hunter, nor the enrage of vladek

**Comment by Rushor** [comment] 2016-11-12 13:15
DB/Creature: Update Silverbrook Hunter + Vladek SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/2526
* commit: 007ad760c8d15cdba4be63999423401967fba023
* Vladek and Silverbrook hunter will now cast 'Improved Wing Clip' in combat. once they dropp below 50 % hp, they will cast their transform

![GitHub Logo](http://i.imgur.com/mWM1HOz.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-02 10:54
The hunters are working as intended on ptr, however Vladek is missing his enrage spell.

``` sql
-- Vladek SAI
SET @ENTRY := 27547;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,2,0,100,1,0,50,10000,10000,11,47457,0,0,0,0,0,1,0,0,0,0,0,0,0,"Vladek - Between 0-50% Health - Cast 'Worgen Transform - Male' (No Repeat)"),
(@ENTRY,0,1,0,2,0,100,0,0,50,10000,10000,11,32714,0,0,0,0,0,1,0,0,0,0,0,0,0,"Vladek - Between 0-50% Health - Cast 'Enrage'");
```
Note: Using action 61 (link) doesn't seems right to me as he is not suppose to transform more than once per fight.

**Comment by TeridanDW** [comment] 2017-04-02 12:32
There are few issues with the hunters and vladek:
 - vladek doesn't cast enrage at all http://wotlk.openwow.com/spell=32714
 - hunters continue to cast when they are in thier worgen form (they shouldn't)
 - hunters are missing spell http://wotlk.openwow.com/spell=6660 (this spell should be casted only in human form)
 - hunters should change weapons depending on which form they are in
 - hunters have a mini combo event, when they can http://wotlk.openwow.com/spell=47168 they should move away from victim and cast http://wotlk.openwow.com/spell=6660
Note: I did everything bug the mini event, creature doesn't move away from victim.

``` sql
-- Vladek SAI
SET @ENTRY := 27547;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,2,0,100,1,0,50,10000,10000,11,47457,0,0,0,0,0,1,0,0,0,0,0,0,0,"Vladek - Between 0-50% Health - Cast 'Worgen Transform - Male' (No Repeat)"),
(@ENTRY,0,1,0,2,0,100,0,0,50,10000,10000,11,32714,0,0,0,0,0,1,0,0,0,0,0,0,0,"Vladek - Between 0-50% Health - Cast 'Enrage'");

DELETE FROM `creature_equip_template` WHERE `CreatureID`=27546 AND `id` = 2;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`) VALUES
(27546, 2, 0, 0, 0);

DELETE FROM `creature_template_addon` WHERE `entry`= 27546;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(27546, 0, 0, 0, 1, 0, '');

-- Silverbrook Hunter SAI
SET @ENTRY := 27546;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,2,1,100,1,0,50,0,0,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - Between 0-50% Health - Increment Phase (Phase 1) (No Repeat)"),
(@ENTRY,0,1,2,61,2,100,1,0,50,0,0,11,49561,1,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - Between 0-50% Health - Cast 'Worgen Transform' (Phase 1) (No Repeat)"),
(@ENTRY,0,2,3,61,2,100,1,0,50,0,0,71,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - Between 0-50% Health - Change Equipment (Phase 1) (No Repeat)"),
(@ENTRY,0,3,0,61,2,100,1,0,50,0,0,40,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - Between 0-50% Health - Set Sheath Unarmed (Phase 1) (No Repeat)"),
(@ENTRY,0,4,0,0,1,100,0,3000,6000,7000,11000,11,47168,0,0,0,0,0,2,0,0,0,0,0,0,0,"Silverbrook Hunter - In Combat - Cast 'Improved Wing Clip' (Phase 1)"),
(@ENTRY,0,5,6,25,0,100,0,0,0,0,0,22,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - On Reset - Set Event Phase 0"),
(@ENTRY,0,6,7,61,0,100,0,0,0,0,0,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - On Reset - Set Sheath Melee"),
(@ENTRY,0,7,0,61,0,100,0,0,0,0,0,71,1,0,5856,0,2552,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - On Reset - Change Equipment"),
(@ENTRY,0,8,0,9,1,100,0,2,30,3000,7000,11,6660,0,0,0,0,0,2,0,0,0,0,0,0,0,"Silverbrook Hunter - Within 2-30 Range - Cast 'Shoot' (Phase 1)"),
(@ENTRY,0,9,0,4,0,100,1,0,0,0,0,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - On Aggro - Increment Phase (No Repeat)"),
(@ENTRY,0,10,0,31,1,100,0,47168,0,0,0,80,@ENTRY*100+00,1,0,0,0,0,2,0,0,0,0,0,0,0,"Silverbrook Hunter - On Target Spellhit 'Improved Wing Clip' - Run Script (Phase 1)");
-- Actionlist SAI
SET @ENTRY := 2754600;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,27,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - On Script - Stop Combat "),
(@ENTRY,9,1,0,0,0,100,0,3000,3000,0,0,79,10,0,0,0,0,0,1,0,0,0,0,0,0,0,"Silverbrook Hunter - On Script - Set Ranged Movement"),
(@ENTRY,9,2,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,2,0,0,0,0,0,0,0,"On Script - Set Orientation Victim"),
(@ENTRY,9,3,0,0,0,100,0,0,0,0,0,11,6660,0,0,0,0,0,2,0,0,0,0,0,0,0,"On Script - Cast 'Shoot'"),
(@ENTRY,9,4,0,0,0,100,0,0,0,0,0,49,0,0,0,0,0,0,2,0,0,0,0,0,0,0,"Silverbrook Hunter - On Script - Start Attacking");
```

**Comment by Rushor** [comment] 2018-03-29 09:19
Added your changes, no idea yet for the mini event cuasing the creature to move away

**Closed** 2018-03-29 09:18 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update
