### ISSUE TITLE
[NPC] Grimungous and Mith'rethis the Enchanter

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1261] opened 2014-02-22 17:54 UTC
Grimungous (http://wotlk.openwow.com/npc=8215) does not cast any of his abilities.

Mith'rethis the Enchanter (http://wotlk.openwow.com/npc=8217) also unscripted.

**Comment by Rushor** [comment] 2016-11-11 18:47
DB/Creature: Implement SAI for Grimungous and Mith'rethis the Enchanter

* closes https://github.com/dalaranwow/dalaran-wow/issues/1261
* commit: 4fe9e942bb2fc8fe81c06ba23898895e0e1b7236

"Grimungous - In Combat - Cast 'Trample'"),
"Grimungous - In Combat - Cast 'War Stomp'");
"Mith'rethis the Enchanter - On Aggro - Cast 'Shadow Word: Pain'"),
"Mith'rethis the Enchanter - Between 0-50% Health - Cast 'Slow' (No Repeat)"),
"Mith'rethis the Enchanter - Between 0-30% Health - Cast 'Enchanted Quickness' (No Repeat)");

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 18:47 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 19:01
Works as intended on ptr.
Suggestion: change from on aggro - cast X spell to update_ic - cast X spell (if you want to, 1 cast per fight seems low to me)
