### ISSUE TITLE
3 bugged quests in the outland content

### ISSUE THREAD

**Issue by kokkino** [dalaranwow/dalaran-wow#2293] opened 2015-03-12 13:05 UTC
1st the quest "Arcane Disturbances" doesn't want to mark as completed when you take the reading from the underground well and the underground pond.
2nd the quest "Building a Perimeter" again doesn't want to mark as completed when performed under the runes. 
3rd the quest "Torching Sunfury Hold" the balistas and the tents don't want to get marked as burned because they don't get fire, the char's animation doesn't show any torch in his/her hand when performing the action.

**Comment by Rushor** [comment] 2015-03-12 14:47
```sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN (19866,19867,19868);

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (19866,19867,19868) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(19866, 0, 0, 0, 8, 0, 100, 0, 34646, 0, 0, 0, 33, 19866, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Invis East KV Rune - On Spellhit "Activate Kirin''Var Rune" - Give Quest Credit'),
(19867, 0, 0, 0, 8, 0, 100, 0, 34646, 0, 0, 0, 33, 19867, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Invis NE KV Rune - On Spellhit "Activate Kirin''Var Rune" - Give Quest Credit'),
(19868, 0, 0, 0, 8, 0, 100, 0, 34646, 0, 0, 0, 33, 19868, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Invis West KV Rune - On Spellhit "Activate Kirin''Var Rune" - Give Quest Credit');
```

for Building a Perimeter

**Comment by Golganeth** [comment] 2015-03-12 15:26
Re-check the current reports before opening new ones. Duplicate of #1517 / #1634 / #1856

If you're going to report something, make separated reports unless the problems are somewhat related with each other.

@Rushor TrinityCore codes do not fit with our core, since it's modified.

Thanks!

**Closed by Golganeth** 2015-03-12 15:26 UTC

**Comment by Rushor** [comment] 2015-03-12 15:36
so u are using mangos?
