### ISSUE TITLE
[quest bug] The Lost Mistwhisper Treasure 

### ISSUE THREAD

**Issue by hairychestfan** [dalaranwow/dalaran-wow#5320] opened 2018-03-01 17:10 UTC
**Current behaviour**: You click on the object and it only spawns warlord

**Expected behaviour**: You click on the object and spawn warlord and loot the quest item.

**Steps to reproduce the problem**:

1. Accept quest and travel to the place
2. Right click on Mistwhisper Treasure
3. You get into combat and the first cast is interrupted due to warlord spawning you are able to click it for several more times and it just spawns as many warlords as you click but as soon as one of the warlords dies you are unable to click the treasure any longer. Relogging or rezoning doesn't solve it either.

**Include proofs for this behaviour**
it's kinda the same as with this guy https://youtu.be/NgQUgNeuyj8?t=1m54s
SHOULD work like this https://youtu.be/4jro1h4k-F8?t=27s

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/object=190578/mistwhisper-treasure

maybe the eazy solution would be to just add http://www.wowhead.com/item=38601/mistwhisper-treasure 100% drop rate to http://www.wowhead.com/npc=28105/warlord-tartek ?

**Comment by hairychestfan** [comment] 2018-03-02 17:44
for some reason i was able to complete quest today after server was restarted.. seems odd. the quest worked fine and was able to loot item with no problem.. i abandoned and re accepted quest 8 times before but it worked the next day after restart so i am not sure it will work for everyone in the future.. maybe its the same bug as with some mining nodes and chests that display THIS OBJECT IS ALREADY BEING USED because i believe someone tried looting/mining/opening it from too far away/los or the server tought the character was still moving even tho in the client he was standing still i believe this causes the object already in use bug with stuff.. this might be the issue but i'm not sure

**Comment by Rushor** [comment] 2018-03-21 09:10
yep, the reason for the issue is already explained in https://github.com/dalaranwow/dalaran-wow/issues/4998 (Closing due to duplicate)

**Closed by Rushor** 2018-03-21 09:10 UTC
