### ISSUE TITLE
[Quest][Outland] The Smallest Creatures

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#572] opened 2013-08-13 07:24 UTC
**Quest The Smallest Creatures** - _10720_
- **Issue present:** After using **Kodohide Drum** _(ID:31141)_ near the invisible Game Object _Marmot Den_ _300117_ - **TEMP Marmot Den**, you enter Shadow Realm but nothing happens. You gain this buff upon using item: **Coax Marmot** _(ID:38544)_
- **How it should work:** After using **Kodohide Drum** _(ID:31141)_ you will get in control of a NPC called **Marmoth** _(ID:22189)_, you will have 3 abilites:
  _Acorn Toss_, _Poison Keg_, _Stealth_. 
  Your character however gets this buff: **Coax Marmot** _(ID:38544)_ so nobody can interfere you when doing this quest. Also, possibly Marmot gains it too, but it's not necessary.

**Acorn Toss** - _38605_
**Poison Keg** - _38629_ - _Main ability that is needed to complete the quest_
**Stealth** - _42347_
- After you are in control of **Marmoth**, you have find and go to nearby these objects:

_(these objects are currently triggable by players and they should't be)_
_185214_ - **Fermented Seed Beer Keg**
_185206_ - **Green Spot Grog Keg**
_185213_ - **Ripe Moonshine Keg**

Locations of these objects currently:

_26104 (Entry: 185214) - Fermented Seed Beer Keg X:3573.100098 Y:5809.379883 Z:2.969690 MapId:530_
_26092 (Entry: 185206) - Green Spot Grog Keg X:3468.479980 Y:5846.970215 Z:5.180390 MapId:530_
_26103 (Entry: 185213) - Ripe Moonshine Keg X:3388.689941 Y:5843.240234 Z:2.862430 MapId:530_

Then, you have to use  second ability. **Poison Keg**. near/on any of those Kegs and you get the credit for it. Simple. The other abilites are purely cosmetic.

**Temporary solution hack and fast solution:** _You could just make objects triggable/interactable by player and once player clicks on them and the cast is finished, give him credit. But this is too easy then._

---

http://wotlk.openwow.com/quest=10720
http://www.wowhead.com/quest=10720/the-smallest-creatures
http://wotlk.openwow.com/spell=38544
http://www.wowhead.com/npc=22189/marmot#abilities
http://wotlk.openwow.com/npc=22189

**Comment by muffygb** [comment] 2015-06-16 23:59
Still a faulty quest. Supposed to get a pet bar showing to poison kegs but you get nothing.

**Comment by Demlock** [comment] 2015-06-30 18:39
Confirmed. This is not working as intended.

**Comment by ashido96** [comment] 2015-07-11 17:34
Going to say that if the temporary solution was ever implemented at one point, it is not working as such not and is uncompletable.

**Comment by Finlaypro** [comment] 2015-10-11 02:52
11/10/2015: Still not working.

You use the drumps and get in a state of death or something like that, a kind of trance, but you don't transform in creature to do the quest. So it is bug :/

**Comment by DrFuler** [comment] 2015-12-15 15:30
15/12/2015: Still not working.

Very upsetting for anyone trying to get the Loremaster achievement, as it is the second quest of relatively long chain.

**Comment by Cone182** [comment] 2016-02-03 20:42
still bugged

**Comment by jonanone** [comment] 2016-06-13 17:40
Now using the quest item on the Marmot Den will summon a Marmot pet under your control.
The marmot pet has the ability to become stealth, the ability to distract enemies and the ability to poison kegs in order to complete the quest.
The fix will be applied to the live realm soon.

**Comment by DalaranLantri** [comment] 2016-06-14 15:01
Quest works perfectly. 1 tiny issue; there's no exit button to leave the Marmot.

**Comment by axenon** [comment] 2016-08-19 17:21
Quest is working fine up to the moment when you have to poison the kegs. After pressing the button of "Poison Keg" ability nothing happens and it gives no credit, making this quest unable to complete. I have tried after few relogs and quest is still bugged.

**Comment by DalaranLantri** [comment] 2016-08-24 19:03
**185214** - Fermented Seed Beer Keg is able to be poisoned.

**185206** - Green Spot Grog Keg
**185213** - Ripe Moonshine Keg
Are not able to be poisoned, making the quest uncompletable for players.

**Comment by Zibathy** [comment] 2016-11-12 03:44
Bugged on Algalon still. For warrior it doesn't even show the poison keg option or whatever.
![wowscrnshot_111116_214119](https://cloud.githubusercontent.com/assets/7729864/20235461/0ca4c032-a858-11e6-878d-5ba82d823de5.jpg)
![wowscrnshot_111116_214123](https://cloud.githubusercontent.com/assets/7729864/20235465/0ca7ba6c-a858-11e6-82d6-35e804a26689.jpg)
![wowscrnshot_111116_214127](https://cloud.githubusercontent.com/assets/7729864/20235464/0ca6ccb0-a858-11e6-90cc-cf33d2c5f1f8.jpg)
![wowscrnshot_111116_214240](https://cloud.githubusercontent.com/assets/7729864/20235462/0ca617b6-a858-11e6-8b1f-54b20cec01f5.jpg)
![wowscrnshot_111116_214241](https://cloud.githubusercontent.com/assets/7729864/20235463/0ca6d23c-a858-11e6-9dcd-26f52f4a1e69.jpg)

Some screenshots.

**Comment by Rushor** [comment] 2016-12-22 12:57
DB/Quests/Blade Edge Mountains: The Smallest Creatures.

Using the quest item on the Marmot Den will summon a Marmot pet under your control.
The marmot pet has the ability to become stealth, the ability to distract enemies and the ability to poison kegs in order to complete the quest.

Closes https://github.com/dalaranwow/dalaran-wow/issues/572
* commit: 3d7dad2c3f49fdce37975667dd91834b3de8382d
* commit: c6cc1b316b1feecd2bdc683657eea3ca861a3fcb

![GitHub Logo](http://i.imgur.com/8nKq2tq.jpg)
![GitHub Logo](http://i.imgur.com/2nawwwD.jpg)
![GitHub Logo](http://i.imgur.com/xgHoM8c.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-22 12:57 UTC
Labels: Area - Outland, Fixed - Waiting for PTR Update, General - Quests

**Comment by Rushor** [comment] 2016-12-22 13:00
Btw: you can dismiss the pet by: rightclick on pet > dismiss.

**Comment by Rushor** [comment] 2018-05-17 09:10
already on PTR :)
