### ISSUE TITLE
Many herbs at the same location in Alterac Mountains

### ISSUE THREAD

**Issue by Flashover369** [dalaranwow/dalaran-wow#1496] opened 2014-04-13 17:09 UTC
Today (~17:30 servertime) I was looking for a good questing zone, when I came to Alterac Mountains.
It's more a general thing, but in a part of this zone, called "ruins of Alterac" there were lots of herbs everywhere. At first I didn't notice and just thought I would be lucky but later on I realized that as many herbs as before spawned also in another location but still in the ruins of Alterac, so this might be not intended to happen. I read a thread on the forums about an increase of herb drops, so I don't know if this is really a bug or something else. If it's not I'm sorry for wasting your time.

**Comment by Rushor** [comment] 2016-12-13 20:38
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/1208

**Closed by Rushor** 2016-12-13 20:38 UTC
