### ISSUE TITLE
[NPC][Classic] Troubled spirits of Kel'theril

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4535] opened 2017-03-06 14:08 UTC
http://www.wowhead.com/quest=5245/deprecated-troubled-spirits-of-keltheril http://wotlk.openwow.com/quest=5245

https://www.youtube.com/watch?v=5q9DcUO-FKQ starts from 2:35

according to the infos in wowhead there should spawn a Suffering Highborne or Anguished Highborne once the player interacted with the gameobject. Those summoned creatures should attackstart the player.

**Comment by Rushor** [comment] 2017-03-07 10:32
DB/Quest: Troubled spirits of Kel'theril - Add spawn of 'Suffering Highborne' & 'Anguished Highborne' once Highborne Relic Fragment was looted

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4535
* commit: d8395f104db3e0e7ca905735d684c66c23989282

![GitHub Logo](http://i.imgur.com/CoL5YY1.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-10-24 09:43
Hello after few tests on PTR:

>  - Add spawn of 'Suffering Highborne' & 'Anguished Highborne' once Highborne Relic Fragment was looted

Doesn't work as intended as a player can mass summon the 2 creatures if he simply opens the GO's loot window --> don't loot the quest item --> close it.
Also at the first time 2 creatures spawn when player open the GO's window and 2 more when he closes it.
Result:
![wowscrnshot_102417_124001](https://user-images.githubusercontent.com/6797611/31935968-d7c84cf4-b8b8-11e7-9b55-0a4163ad22e9.jpg)

I guess there needs to be some condition for the spawns and they also give exp so the quest can be abused.

**Closed** 2018-03-20 14:04 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update, General - Quests
