### ISSUE TITLE
[Quest][Northrend] Where Dragons Fell Cinematic

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3825] opened 2016-11-09 21:31 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

This quest is a part of a much bigger chain in a series where you can explore some lore surrounding the LK.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Some quests along the chain encounter minor/major bugs.

After you take the quest from Matthias Lehner and hand him the 6 Whelp Bone Dusts, you should see a cinematic with the LK raising Sindragosa, but you do not. And after you turn the quest in, he also dephases and you need to leave and return to the area for him to appear again with the next quest in the chain.

**Expected behaviour**: Tell us what should happen instead

You should be able to observer the rise of Sindragosa and the quest giver should not dephase.

**Steps to reproduce the problem**:

1.  Take the quest.
2.  Observer that there is no cinematic, and then the quest giver disappears.
3. 

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=v3FsLm1oY8k
http://www.wowhead.com/quest=13398/where-dragons-fell

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-09 21:42
the event actually happens. only the problem with the phasing needs to be fixed

**Comment by MrAndersonX** [comment] 2016-11-09 21:48
Well, I did it just now and I didn't see it. I really wanted to see LK in action :(.

**Comment by Rushor** [comment] 2016-11-27 11:12
DB/Quest: Where Dragons Fell - Enable Cinematic

* closes https://github.com/dalaranwow/dalaran-wow/issues/3825
* commit: da381cd5c4338a107bf968767bc4ef71d486c1a6

![GitHub Logo](http://i.imgur.com/mthbAQF.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-11-01 10:23
Hello, after a quick test on PTR:
After completing quest https://wowgaming.altervista.org/aowow/?quest=13398 the LK just spawned and attacked me, no event happend.

**Closed** 2017-12-09 14:14 UTC
Labels: Area - Northrend, Fixed - Waiting for Live update, General - Quests
