### ISSUE TITLE
NPC: Helena Atwood

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#890] opened 2013-10-10 12:24 UTC
This NPC:
http://www.wowhead.com/npc=5669#comments

Should do her normal route (which works here btw) but also shoot her gun at a ranged target that is located right at the corner of the war quarter (it's on her route and she even stops there for a sec but doesnt fire).

She has a shoot ability and judging by the comments - Helena Atwood fires her gun about every seven seconds.

**Comment by Rushor** [comment] 2016-11-13 10:32
DB/Creature: Helena Atwood - Add shootscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/890
* commit: 5684953063cd967720505ceea2a883ac0a203045


![GitHub Logo](http://i.imgur.com/ont1ZIt.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 10:32 UTC
Labels: Continent - Classic
