### ISSUE TITLE
[Quest] [Northrend] Betrayal

### ISSUE THREAD

**Issue by darkwulfv** [dalaranwow/dalaran-wow#2576] opened 2015-06-29 15:43 UTC
For the quest "Betrayal", if you die during the fight and go back to re-try it, the Blightblood Trolls (http://wotlk.openwow.com/npc=28931) do not despawn, making the fight extremely difficult the 2nd time around, as getting too close to one of their platforms will cause both to chase you down and probably kill you. It also makes charming one very difficult, as the 2nd one will beat you down while you're trying to charm the 1st. This also applies if someone else recently attempted the fight; their trolls will not despawn (and I saw someone start the encounter during one of my attempts; I'm not sure if this is normal or not).

Sometimes, Drakuru (http://wotlk.openwow.com/npc=28998) will not despawn either and a new one will spawn on top of him. Occasionally the script also fails and your disguise will not begin to fade at the start of the encounter. The item "Drakuru's Skull" (http://wotlk.openwow.com/object=191458) is always in the arena and can be interacted with, but doesn't do anything when used (until you beat Drakuru).

Also, Drakuru's Blight Crystal spell (http://wotlk.openwow.com/spell=54087) has an enormous AoE that is almost impossible to dodge, and no emote is shown to announce the attack. Even if you're not standing in the cloud it leaves, you take the DOT. I've been at least a full quarter-turn of the arena away from the crystal's impact and took the impact damage as well as the DOT.

**Comment by Furminator** [comment] 2015-06-29 16:39
Confirmed that it is not working properly when it comes to mobs despawning and the skull being present (thou not lootable) before killing Drakuru

Regarding the Blight Crystal, the AoE that it has is fine, easily dodgeable and you can clearly see if he is casting it. Still true that is missing his emote.

The DoT you are talking about is something else, that is present all around the upper part of the Necropolis which is a DoT that deals 1k2 damage every 2 seconds more or less (which shouldn't be present at all), nothing really troublesome if you spam the healing of the troll. (Much easier for healing classes)

**Comment by darkwulfv** [comment] 2015-06-29 16:51
I know about the Blight Fog aura, but I've definitely taken damage from the crystal when I've very clearly dodged it and then proceeded to take DOT from the cloud it leaves behind while also not in it's AoE.

**Comment by warcraftgeekygamer** [comment] 2015-06-29 23:22
https://www.youtube.com/watch?v=opArnZy6Go8 - video on how this quest is supposed to work

**Comment by Akkalevil** [comment] 2016-02-01 23:33
On top of all the previous bugs, there is also a permanent and invisible Blight Fog effect on the ENTIRETY of the platform. It deals 1200 damage each tic, which make the fight near impossible.
I had this bug even right after a crash server where everything was reset.

**Comment by DrFuler** [comment] 2016-03-19 03:40
[19/03/2016] - Seems impossible do complete.

The 1200/tic fog thing kills me before I can even think what I should be doing. (and as mentioned above, when the fight begging, the fog starts to hit you no matter where you stand.

**Comment by jonanone** [comment] 2016-06-22 17:52
- The event cannot be started now while another event is happening on the roof.
- The spawning time for Drakuru and the trolls has been adjusted.
- Once Drakuru spawns, the remaining trolls are despawned in order to avoid troll stacking.
- Drakuru's Skull object now only loots Drakuru's skull item. Once the item is looted, the skull from the floor despawns.
- Removed some mobs that shouldn't be on the roof.

These fixes will be applied to the live realm soon.

**Comment by Golganeth** [comment] 2016-06-24 16:27
Works great, no more troll/Drakuru stacking, everything despawns as intended and event can't be started twice if it's already going on.

The only issue I see is troll doing a bit too low damage with abilities/white dmg, and its abilities can't be set as autocast, making the player click constantly.

**Comment by MiyaZaki0** [comment] 2016-07-15 12:42
Did it twice yesterday (14/07/2016), the skull container don't contain anything after the fight, so we can't complete the quest...

**Comment by MrAndersonX** [comment] 2016-11-01 13:24
Currently bugged as fuck and really annoying as fuck. Your disguise gets dispelled and u can't do it again, so you die easily from the dot.

**Comment by Edzero** [comment] 2016-11-01 13:38
As you can see there have been improvements on the PTR but it's not completely bug free.

You've bumped sixteen times in the last week and every bump means that we get notified about issues which we are already aware of. This cuts down on the amount of time we have to work on these issues. Please refrain from doing this unless you have something new to contribute to the issue, preferably with proof.

Remember that this is a bug tracker and not a forum.

I'll re-open this due to the low damage and lack of autocast that Golganeth mentioned. Everything else is working as intended based on Golganeth's testing.

**Comment by MrAndersonX** [comment] 2016-11-01 18:44
I know this is a bug tracker, and I consider doing my duty as a player on the server reporting any issues I encounter. And the one thing I don't understand at all, is why so many issues that haven't been fixed are closed ? Alot of bugged quests, chains, abilities that haven't been repaired, or the fix/repair hasn't been implemented, or applied to the live server have been closed. It seems to me like you're trying to avoid the problems, or pretend they are fixed, when they're actually not. Like, why make a ticket about a problem you struggle to report, if you're just gonna close them and say "eventually they'll get repaired" or "tested on ptr, needs to be applied on live realm soon" ? Seems to me like that "soon" part especially can be between several months and a year, and still not fully fix the problem ("working but needs improvemnts"). 
Please, just focus, and get your head straight. The bullshit is kinda getting piled up.

**Comment by Rushor** [comment] 2016-11-27 10:00
@MrAndersonX:

if something is "on-ptr" we need a tester to test the fix. atm there are like 200 fixed issues that needs to be checked by some testers. Once the issue was confirmed as an improvement it will be pushed to the liverealm. You see everything needs time :) It would be a great help if you would write an application as tester for Dalaran-WoW. You are a really active player.

**Comment by Rushor** [comment] 2016-11-27 10:05
concerning the trollpet: autocast should not be available for him as you can see here https://youtu.be/opArnZy6Go8?t=128

**Comment by MrAndersonX** [comment] 2016-11-27 10:17
@Rushor 
Unfortunately I just don't have the time or the PC for it :). I'm playing with everything on low and I get alot of problems from my laptop also. And that is when I have the time to play. Sorry :(.

**Comment by Rushor** [comment] 2016-11-27 10:20
DB/Quest: Betrayal - Increase Damage for Blightblood Troll

* closes https://github.com/dalaranwow/dalaran-wow/issues/2576
* alright meleedamage is ~3000 now, quest can be done faster
* commit: f23c4521e6d4d9084a190ef2edd6efd3d7a54b56

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 10:20 UTC
Labels: Continent - Northrend, On PTR, Quests
