### ISSUE TITLE
[Quest][Northrend] Valduran the Stormborn

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#367] opened 2013-08-05 11:34 UTC
Hello,

http://www.wowhead.com/quest=12984

This quest is bugged. Valduran cannot be attacked, and even if i use the Horn Nothing happends.

**Comment by irodeyourmom** [comment] 2015-06-16 02:36
Tested today on algalon. Summon works, Dialog works, Npc's do not attack mob. 

If NPC's get hit by an AOE from Valduran, they will attack, but in this case, I did not get credit for the kill. Have tried this quest 4 times, Cannot solo myself. Do not get credit when using help from the NPC's.

**Comment by Golganeth** [comment] 2016-06-29 16:14
@irodeyourmom confirmed.

**Comment by Rushor** [comment] 2016-11-24 11:19
Scripts/Quest: Valduran the Stormborn - Update questscript

* The Horn can now only be used in 19 yards range to Valduran
* the helpfull creature should attack Valduran propperly now
* if there is no player in 50 yards range, teh event will reset after 5 seconds
* you need to do at least 1 damage on Valduran in order to get the questcredit
* closes https://github.com/dalaranwow/dalaran-wow/issues/367
* commit: a0892e394802cfa7ed5ca3ed079967e593c9106d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 11:19 UTC
Labels: Continent - Northrend, On PTR, Quests
