### ISSUE TITLE
[NPC] Feral Dragonhawk Hatchlings not skinnable

### ISSUE THREAD

**Issue by ghostlynx** [dalaranwow/dalaran-wow#2010] opened 2014-10-25 10:03 UTC
The feral dragonhawk hatchlings around the blood elf starting zone are not skinnable... also there doesn't seem to be as much variety in them as in retail.  There should be some hostile ones and higher levels than 5-6 around the city.

**Comment by Rushor** [comment] 2016-11-23 10:14
DB/Creature: Feral Dragonhawk Hatchlings - Add skinning loot

* closes https://github.com/dalaranwow/dalaran-wow/issues/2010
* commit: fd33e22c65034ecb31fb175416fe809492dee12f

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 10:14 UTC
Labels: Continent - Classic, On PTR
