### ISSUE TITLE
[Quest][Classic] Dead Man's Plea

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1109] opened 2014-01-14 01:02 UTC
http://www.wowwiki.com/Quest:Dead_Man%27s_Plea

In this quest you have to rescue Ysida Harmon from Baron Rivendare during the 45 minute timer.

FIrst wrong thing is that timer starts after you enter The Gauntlet. It should start when you take the quest (or maybe when you enter Stratholme - Im not sure with this).

When you engage Baron Rivendare in time, Ysida show up in the room with grey question mark on her head. After you kill Baron, question mark is still gray and quest is not marked as completed. So you cant turn it to Ysida and she will not offer you next quest in chain.

Abandon and retake quest doesn't help, clearing cache also not.

**Comment by n-ghost** [comment] 2015-02-21 14:42
Still an issue.

**Comment by n-ghost** [comment] 2015-02-21 16:55
Also, if the quest is completed by GM, Ysida won't spawn on subsequent runs anymore, and quest can't be turned even if completed.

This might work as intended, but in conjuction with previous issue makes the whole quest a one big heap of troubles both for players and GMs.

**Comment by Rushor** [comment] 2016-12-08 12:54
meg going to rework the whole dungeon

**Comment by Rushor** [comment] 2017-03-20 13:13
here is how it whould work: https://youtu.be/1vLt60BfCfQ?t=546

she should spawn by default, one the run was completed, she should open the cage, say sth, and move forward as well as complete the quest

**Comment by Rushor** [comment] 2017-03-20 13:22
Scripts/Stratholme: Implement questevent for "Dead Man's Plea" 

* moved Baron Rivendares script to eventmaps
* spawn Ysida Harmon by default and add a cage
* once Baron Rivendare was killed, Ysida Harmon opens the cage, says her text, moves forward and completed the quest: Dead Man's Plea
* closes: https://github.com/dalaranwow/dalaran-wow/issues/1109
* commit: 5f7e0f6929ea70fa97565c4bb38c0d63d40fc43a
* commit: 3c2b5ed4693b7337ead93cc0e10bd4e8e42748cd

![GitHub Logo](http://i.imgur.com/jeyQxdF.png)
![GitHub Logo](http://i.imgur.com/jgt6Qba.png)
![GitHub Logo](http://i.imgur.com/newKYI0.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-20 13:22 UTC
Labels: Area - Instances, Fixed - Waiting for PTR Update, General - Quests
