### ISSUE TITLE
[Hunter] Spell - Explosive Shot

### ISSUE THREAD

**Issue by moliskrc** [dalaranwow/dalaran-wow#2024] opened 2014-10-30 19:11 UTC
http://wotlk.openwow.com/spell=67985

When you apply Explosive Shot debuff on target, it should tick 3 times: at start, after 1 second and after 2 seconds. All in all 3 ticks.
The problem is when the debuff is applied, some ticks miss to hit the target despite Explosive Shot debuff already being active on target. Not the shot misses, but the ticks miss.

**Comment by kazubla** [comment] 2015-05-21 03:21
Can confirm that this should be fixed, I am at 8% and looking through my hc parses nothing is ever missed, save for a few blocks but that should be happening anyway if i'm hitting the boss from the front

**Comment by kazubla** [comment] 2015-05-31 10:45
Although I just realised my pet is missing constantly even though I am at 8%, the pet should be gaining my hit rating as well as that amount as hit i.e. if I had a hit rating of 263 my pet should not only be getting the 263 hit but also 263 expertise.

This is a parse from the instance Halls of Lightning with my level 80 wolf
![wowscrnshot_053115_114319](https://cloud.githubusercontent.com/assets/12538122/7901649/6b0cea7a-078a-11e5-9b8c-ef23d2a22059.jpg)

**Comment by Rushor** [comment] 2016-11-23 11:45
Game/Spells: Explosive Shot (trigger) - should not miss

* closes https://github.com/dalaranwow/dalaran-wow/issues/2024
* commit: 96e6de604540b28fe3d71fb278f068ac51328b99

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 11:45 UTC
Labels: Class - Hunter, On PTR

**Comment by TeridanDW** [comment] 2017-10-21 09:29
Works as intended on PTR.
