### ISSUE TITLE
Frost Mage Summon Elemental

### ISSUE THREAD

**Issue by pedrodevargas** [dalaranwow/dalaran-wow#5233] opened 2018-01-06 00:21 UTC
New to this, so let me know if I need to do something differently.

Here's the bug:

Frost mage summons water elemental and has Glyph of Eternal Water. Summoned Pet has terrible AI, doesn't respond to pet behaviors (terrible response to aggressive, defensive only works if you command attack, passive probably works fine). Summoned pet will not dismiss when player mounts, and will attempt to follow player on ground (even if player is on flying mount). When pet dies, pet commands stay locked on screen, and pet is unable to be summoned after it dies.

What should happen:
Frost mage summons water elemental and has Glyph of Eternal Water. Summoned Pet should have acceptable AI, and should respond to pet behaviors (acceptable response to aggressive, defensive how it should, passive should do what it does). Summoned pet should dismiss when player mounts, and not follow player on ground (even if player is on flying mount), aggroing all mobs along the way. When pet dies, pet commands should not stay locked on screen, and pet should be able to be summoned after it dies.

**Comment by Rushor** [comment] 2018-01-08 19:35
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/3800 and https://github.com/dalaranwow/dalaran-wow/issues/4918

**Closed by Rushor** 2018-01-08 19:35 UTC
Labels: Duplicate / Invalid Report
