### ISSUE TITLE
[NPC] Jin'Zallah the Sandbringer

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1032] opened 2013-12-13 11:55 UTC
http://www.wowhead.com/npc=8200

Should have and use 3 following abilities:

http://www.wowhead.com/spell=79884 - his main attack.

http://www.wowhead.com/spell=7272 - AoE hit chance reduction around him.

http://www.wowhead.com/spell=10132 - summons 1 Sand Storm  (http://www.wowhead.com/npc=7226), which should have 2 abilities as well:

http://www.wowhead.com/spell=10093
http://www.wowhead.com/spell=10092

Currently Jin'Zallah just melees instead.

**Comment by Rushor** [comment] 2016-11-12 21:20
DB/Creature: Add abilities for Jin'Zallah the Sandbringer and Sand Storm

* closes https://github.com/dalaranwow/dalaran-wow/issues/1032
* commit: 6b4f47d86298278a46f1bb19348fb0d0f8095a0d
* Jin'Zallah the Sandbringer will cast 'Lightning Bolt' and 'Dust Cloud'. Moreover at 75, 50 and 25 % HP he will summon one Sandcloud. The sandcloud will attack the player, interrupt him and it will despawn after 5 seconds.

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 11:52
Works as intended on ptr, with the exeption of npc http://www.wowhead.com/npc=7226/sand-storm despawning instantly on summon.
Note: Creature sand storm should NOT be attackable or targetable by players and should follow the player under which it was summoned (better use follow instead of aggro as the creature shouldn't autoattack the player).

**Comment by Rushor** [comment] 2018-03-23 13:55
I think we need to use attack for the sand storm here, because https://wowgaming.altervista.org/aowow/?spell=10092 only proccs on meleeattack as said in the dbcs

**Closed** 2018-03-23 14:29 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update
