### ISSUE TITLE
Swimming while mounted

### ISSUE THREAD

**Issue by gotmilk0112** [dalaranwow/dalaran-wow#3109] opened 2016-01-24 16:14 UTC
For some reason, when you are swimming while mounted, the game thinks you're underwater even when you're at the very top of the water. Even if I keep jumping at the top of the water, as soon as I land in the water, the breath meter starts going down again.

Not sure if it's just the Blood Elf mounts; that's all I've been able to test it with so far.

**Comment by Lukas45** [comment] 2016-01-24 20:54
It's for all mounts (tested troll on raptor, orc on dreadsteed).
Also if you have/gain water walking while swimming, you can't get up on the water unless you dismount - you just dont jump high enough

**Comment by robinsch** [comment] 2016-09-24 09:13
On PTR.

**Comment by Rushor** [comment] 2016-11-12 14:15
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 14:15 UTC
Labels: Mechanics, On PTR, Priority - Low
