### ISSUE TITLE
[Engineering/Jewelcrafting] Crafted items

### ISSUE THREAD

**Issue by dsafer** [dalaranwow/dalaran-wow#1294] opened 2014-02-28 09:32 UTC
I know it's not a big deal, but Explosive Sheep won't explode.
After I summon it, it charges into the nearest enemy. There, it just stants there and does nothing. However, the mob attacking it slowly loses HP from every succesful hit against the sheep, dying eventually.

**Comment by aldenfenris** [comment] 2015-04-05 16:47
I really hope they fix this, it's kind of a letdown

**Comment by Demlock** [comment] 2015-04-19 11:40
Confirmed. This really is a letdown, especially because you can't use some of the fun items in Engineering that way. If it is to be fixed, you'd probably be the first server to actually fix it.

**Comment by Rushor** [comment] 2015-04-19 12:37
Heavy Stone Statue (http://www.wowwiki.com/Heavy_Stone_Statue)
Solid Stone Statue (http://www.wowwiki.com/Solid_Stone_Statue)
Dense Stone Statue (http://www.wowwiki.com/Dense_Stone_Statue)

is working already on several tc servers

**Comment by biggestwownerd** [comment] 2016-04-21 02:08
well I crafted rough stone statue and it did not heal me when im damaged. Instead it chose to attack the mob. I hope this will get fixed.

**Comment by Rushor** [comment] 2016-12-11 14:13
fix inc.

**Comment by Rushor** [comment] 2016-12-11 21:17
just as reverence, i will try to fix them all

list: http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/291193-engineering-all-pets-companions-guide.html

**Comment by Rushor** [comment] 2016-12-12 11:32
Scripts/Pet: Add scripts for several Engineering/Jewelcrafting pets

* Rough Stone Statue, Coarse Stone Statue, Heavy Stone Statue, Solid Stone Statue and Dense Stone Statue will now heal the player if he is out of combat
* The Goblin Land Mine now has a arming time of 15 seconds and casts a detonation on hostile creatures
* Goblin Bomb and  Explosive Sheep now attack hostile victims in 30 yards range, run close to it, explode and Despawn 
* Steam Tonk Controller and Battered Steam Tonk Controller can now be used to attack other Steam Tonks
* Target Dummy, Advanced Target Dummy and Masterwork Target Dummy now generates threat to neearby hostile creatures. After the dummy died it can be looted
* Compact Harvest Reaper now despawns after 10 minutes
* closes https://github.com/dalaranwow/dalaran-wow/issues/1294
* commit: a0fb34188e8dfe95a88bf3b71dae2553abde9663

![GitHub Logo](http://i.imgur.com/cbvr9ck.jpg)
![GitHub Logo](http://i.imgur.com/uUCfqXu.jpg)
![GitHub Logo](http://i.imgur.com/QmfOCCd.jpg)
![GitHub Logo](http://i.imgur.com/eUrBVD5.jpg)
![GitHub Logo](http://i.imgur.com/E9dACfD.jpg)
![GitHub Logo](http://i.imgur.com/NVkyvNb.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-12 11:32 UTC
Labels: General - Items
