### ISSUE TITLE
[Arena][NPC] Relentless Weapons Missing

### ISSUE THREAD

**Issue by Tomazo0** [dalaranwow/dalaran-wow#3357] opened 2016-06-03 20:42 UTC
The NPC - Trapjaw Rix <Exceptional Arena Weaponry> , is missing a big part of the elite pvp  weapons . Please add them . Its pretty unbalanced when , for example a Balance druid can buy its spellpower staff , but there is not a Feral Druid staff in the vendor . 

Thank you !

**Comment by Rushor** [comment] 2016-11-13 20:48
http://wotlk.openwow.com/item=51432

**Comment by Rushor** [comment] 2016-11-13 20:50
DB/Creature: Trapjaw Rix - Add all vendoritems

* closes https://github.com/dalaranwow/dalaran-wow/issues/3357
* commit: 126c22259816602834418aab210424a8742e777d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by sixele** [comment] 2016-11-21 15:24
Not sure what you mean with item 51432, when we're currently in S7 with 258 weapons at best. Anyways, hope the other weapons are in the list, such as Relentless Gladiator's Salvation (ID 48519). This issue is present at all of Exceptional Arena Weaponry vendors, i.e.  
Trapjaw Rix <Exceptional Arena Weaponry> in Dalaran
Grex Brainboiler <Exceptional Arena Weaponry> in Area 52
Blazzek the Biter <Exceptional Arena Weaponry> in Gadgetzan
(to be honest I didn't check Arena 52, but it was missing in other 2 zones)

**Comment by Rushor** [comment] 2016-11-21 17:28
yep they are in that list:

-- Trapjaw Rix
DELETE FROM `npc_vendor` WHERE `entry` = 34095;
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES 
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES 
(34095, 0, 51389, 0, 0, 2939, 0),
(34095, 0, 51391, 0, 0, 2939, 0),
(34095, 0, 51393, 0, 0, 2939, 0),
(34095, 0, 51395, 0, 0, 2939, 0),
(34095, 0, 51398, 0, 0, 2940, 0),
(34095, 0, 51399, 0, 0, 2940, 0),
(34095, 0, 51401, 0, 0, 2939, 0),
(34095, 0, 51403, 0, 0, 2939, 0),
(34095, 0, 51405, 0, 0, 2939, 0),
(34095, 0, 51412, 0, 0, 2939, 0),
(34095, 0, 51432, 0, 0, 2939, 0),
(34095, 0, 51440, 0, 0, 2947, 0),
(34095, 0, 51442, 0, 0, 2947, 0),
(34095, 0, 51444, 0, 0, 2947, 0),
(34095, 0, 51446, 0, 0, 2947, 0),
(34095, 0, 51448, 0, 0, 2947, 0),
(34095, 0, 51450, 0, 0, 2939, 0),
(34095, 0, 51454, 0, 0, 2940, 0),
(34095, 0, 51457, 0, 0, 2939, 0),
(34095, 0, 51481, 0, 0, 2939, 0),
(34095, 0, 51516, 0, 0, 2944, 0),
(34095, 0, 51518, 0, 0, 2944, 0),
(34095, 0, 51520, 0, 0, 2944, 0),
(34095, 0, 51522, 0, 0, 2944, 0),
(34095, 0, 51524, 0, 0, 2944, 0),
(34095, 0, 51526, 0, 0, 2947, 0),
(34095, 0, 51528, 0, 0, 2947, 0),
(34095, 0, 51529, 0, 0, 2947, 0),
(34095, 0, 51534, 0, 0, 2938, 0);

if the affects also other creatures, please open up a new issue. ty :)

**Comment by TeridanDW** [comment] 2017-04-01 12:33
This is not on ptr, however i do agree with @sixele we can't push the wrathful items before S8 starts.

**Comment by Edzero** [comment] 2017-04-01 14:55
The correct list of weapons is:

http://wotlk.openwow.com/item=48402
http://wotlk.openwow.com/item=48404
http://wotlk.openwow.com/item=48406
http://wotlk.openwow.com/item=48408
http://wotlk.openwow.com/item=48410
http://wotlk.openwow.com/item=48412
http://wotlk.openwow.com/item=48414
http://wotlk.openwow.com/item=48420
http://wotlk.openwow.com/item=48422
http://wotlk.openwow.com/item=48426
http://wotlk.openwow.com/item=48428
http://wotlk.openwow.com/item=48424
http://wotlk.openwow.com/item=48432
http://wotlk.openwow.com/item=48435
http://wotlk.openwow.com/item=48438
http://wotlk.openwow.com/item=48440
http://wotlk.openwow.com/item=48442
http://wotlk.openwow.com/item=48444
http://wotlk.openwow.com/item=48507
http://wotlk.openwow.com/item=48509
http://wotlk.openwow.com/item=48511
http://wotlk.openwow.com/item=48513
http://wotlk.openwow.com/item=48515
http://wotlk.openwow.com/item=48517
http://wotlk.openwow.com/item=48519
http://wotlk.openwow.com/item=48521
http://wotlk.openwow.com/item=48523
http://wotlk.openwow.com/item=49191

**Comment by Rushor** [comment] 2017-07-01 19:45
setting this "on hold" as mentinoned in https://github.com/dalaranwow/dalaran-wow/issues/3357#issuecomment-290917444 and closing the issue for now.

"...we can't push the wrathful items before S8 starts."

**Closed by Rushor** 2017-07-01 19:45 UTC
Labels: General - Items
