### ISSUE TITLE
[NPC] Driz Tumblequick/Pol Amberstill dialogue options

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3770] opened 2016-10-08 09:16 UTC
**Description**:
Driz Tumblequick(H)/Pol Amberstill(A) used to sell [the Swift Brewfest Ram](http://www.wowhead.com/item=33977/swift-brewfest-ram) and [Brewfest Ram](http://www.wowhead.com/item=33976/brewfest-ram) back in 2007(Retail). Later the option was removed and the only way to get the Rams was from the Coren's Keg, just like it is now in Dalaran-WoW.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The NPCs Driz Tumblequick/Pol Amberstill are offering the dialogue option ["Say, you wouldn't happen to have an extra set of reins..."](http://i.imgur.com/7xnIh5z.png), which does not lead to anything (as it shouldn't). 
**Expected behaviour**: Tell us what should happen instead
1.  Remove the dialogue option as shown in [this comment](http://www.wowhead.com/npc=24510/driz-tumblequick#comments:id=856231) to avoid confusion.
**Steps to reproduce the problem**:
1. Talk to Driz Tumblequick/Pol Amberstill.
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Pol Amberstill ](http://wotlk.openwow.com/npc=24468)(A) NPC ID 24468
[Driz Tumblequick ](http://wotlk.openwow.com/npc=24510)(H) NPC ID 24510

**Comment by Rushor** [comment] 2016-11-10 19:10
DB/Creature: Driz Tumblequick/Pol Amberstill - Remove unneeded dialogue options

* closes https://github.com/dalaranwow/dalaran-wow/issues/3770
* commit: c1f33cdbaf32d4a3b2196ffb07a00e512909731d

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 19:10 UTC
Labels: On PTR, Priority - Low
