### ISSUE TITLE
[Rogue][Talents] Master Poisoner

### ISSUE THREAD

**Issue by crosik** [dalaranwow/dalaran-wow#1782] opened 2014-08-05 17:31 UTC
Talent is getting bugged by palas judgement. After being hit by it envenom starts eating deadly poison stacks again

also if you poison an enemy, he doesn't get a debuff from the talent (at least not a visible one).

**Comment by Esunnaxqt** [comment] 2015-02-08 21:16
Bump, this single bug is killing an entire spec in PvP.

**Comment by Esunnaxqt** [comment] 2015-02-08 21:30
and forgot to say its still bugged, since it got closed...

**Comment by Golganeth** [comment] 2015-02-09 19:51
Don't know where you see it's closed.

**Comment by Mazz312** [comment] 2016-06-28 19:17
Was this bug ever addressed? Along with the other bug of the talent that is wasn't properly adding 3% crit?

**Comment by Rushor** [comment] 2016-11-23 14:15
DB/Spell: Implement Master Poisoner

* closes https://github.com/dalaranwow/dalaran-wow/issues/1782
* commit: 2c3bf75fb01597e994c5e34587fccc34acef44bf

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 14:15 UTC
Labels: Class - Rogue, On PTR

**Comment by TeridanDW** [comment] 2017-10-20 08:46
Works as intended on PTR.
