### ISSUE TITLE
[DK] Unholy ghoul energy

### ISSUE THREAD

**Issue by Thecableguy** [dalaranwow/dalaran-wow#1959] opened 2014-10-11 21:34 UTC
The ghoul will not use its energy sometimes. Seems to happen almost all the time when i am out of combat and get opened up on by a rogue or druid. It's happened while already in combat too, so maybe its not a entering combat thing. Not using its energy means no gnaw or claw. I have tried turning auto cast on and clicking the gnaw icon but it wont use when the bug happens.

**Comment by kumshot** [comment] 2016-02-09 18:13
Yep, same problem. The ghoul randomly won't use gnaw even at full energy ans no CD on the spell for no reason. Pretty annoying considering it's a core tool for uh DK, almost mandatory in PvP.

**Comment by Rushor** [comment] 2017-03-09 21:40
Game/CoreAI: Impreove mechanic how ghouls from Deathknights use there energy while autocasting spells

* The energy will no longer drop below 40 percent
* closes: https://github.com/dalaranwow/dalaran-wow/issues/1959
* commit: f4a9842eb4bd7bd92a7a6c1de342523c10bd024c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-09 21:40 UTC
Labels: Class - Death Knight, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-21 09:36
Works as intended on PTR.
