### ISSUE TITLE
[Paladin] Redemption - Not effected by haste 

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#4714] opened 2017-05-22 00:48 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

The paladin resurrect is not effected by haste, it always 10 seconds.
http://www.wowhead.com/spell=7328/redemption

**Comment by StheNoble** [comment] 2017-05-22 10:49
Ohai,

as far as i know such spells where never affected by haste and have a fixed casting time. i cant find any hint that it should be different.

do you have any source which could prove it should be affected by haste?

**Comment by ashido96** [comment] 2017-05-22 11:18
Every other Resurrection spell on the server is scaled by haste. Paladin's is the only one which is not.

**Comment by TeridanDW** [comment] 2017-05-22 15:14
Hello, thank you for the report @ashido96 .
I can confirm the issue.
Proof that all "resurrection" spells should benefit from haste:

> All of these abilities resurrect the target with 35% health and mana, and cannot be used during combat. They also all have a base cast time of 10 seconds (**_modified by haste_**), and have no cooldown.

Taken from : http://wow.gamepedia.com/Resurrect

And you can see here:
http://wow.gamepedia.com/Redemption
what changes where made on this spell during the expansions.

**Comment by Rushor** [comment] 2017-07-03 19:56
reason for this could be that all ranks of the spell are SPELLFAMILY_GENERIC and not SPELLFAMILY_PALADIN

**Comment by Rushor** [comment] 2017-07-04 09:27
Game/Spells: Mark Paladin - Redemption spells as SpellFamilyName: Paladin in order to enable haste calculation

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4714
* commit: 5430d639a1f40d9dbef3fe8d70fb360012848f72


without haste http://i.imgur.com/L2BV5rK.jpg > 10 sec cast
with haste potion http://i.imgur.com/pU5VjbA.jpg > 8.9 sec cast

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-04 09:27 UTC
Labels: Class - Paladin, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-23 07:14
Works as intended on PTR.
