### ISSUE TITLE
[Ulduar] (More) Yogg Saron Issues

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3564] opened 2016-07-07 12:49 UTC
1. - Malady of the Mind currently seems to be able to chain to more than one player after it's duration ends (ie. one player gets malady, runs into pack of 5, all 5 new players get malady).  All the resources I could check (Wowwiki, Wowhead and old videos) seemed to indicate that it should only chain to one player at a time (one player gets malady, runs into pack of 5, only one new player should get malady).  At 2:20 of the following video (https://youtu.be/MlFDg7IZM-U) you can see a player with malady run in from the bottom of the screen and watch it chain to only one player at a time several times.  The tooltip for the ability itself also states "This ability will attempt to jump to A nearby friend when removed."
2. - In 25 man, Corruptor tentacles currently have a buffed hp value (about 33%) while the other tentacles use retail-like values.  I just wanted to check if this was still intentional.  The buffed values make it extremely difficult to keep the top level clear.  My raiders were also mentioning that it seemed that they spawned too quickly.  Unfortunately, I am usually assigned to the brain portal team, so I cannot confirm that.
3. - Phase 2 tentacles can spawn inside Yogg Saron's hitbox making them impossible for melee players to reach.  A crusher spawning here can spell doom because the tanks are unable to interrupt their channel.
4. - Malady of the Mind and Dominate Mind still act wonky after fading.  Likely related to problems reported elsewhere regarding effects where players lose control of their players.  It ends up leading to problems with warriors charging among other things.  I know this has been reported before, but it is frustrating.

Thanks for your time and dedication.

**Comment by saltylopez** [comment] 2016-07-07 13:56
Another thing that's occurred more than once in our raids:

-If a player enters a portal while they have Malady it is possible for them to either walk out or be kicked out of the mind's eye.  Twice now this has occurred with us where they'll be kicked out and up above with the rest of the raid, but the portal disappears as if it had been used.  The game also seems to consider the character to still be in the mind's eye.  Thus, when Yogg finishes casting Induce Madness the character will immediately go insane and become mind controlled.

**Comment by delebota** [comment] 2016-07-26 02:33
Please for the love of god fix Malady.

**Comment by Braniacz** [comment] 2016-09-08 21:51
Please for the love of god fix Malady.

**Comment by Rushor** [comment] 2016-12-19 12:02
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Malady of the mind spreads to multiple targets upon expiration

**Expected behaviour**: Malady should spready only to 1 random target in range upon expiration

**Steps to reproduce the problem**:

1. Get affected by Malady of the Mind
2. Have more people within 10yards
3. Watch the madness

**Include proofs for this behaviour**

http://www.wowhead.com/spell=63830/malady-of-the-mind
"Inflicts 5000 Shadow damage and causes the enemy target to run in horror for 4 sec, then attempts to jump to another enemy within 10 yds. Also reduces Sanity by 3%." 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Malady of the Mind - 63830 (Spell)
Sara - 33134 (NPC)

**Include Screenshots from the issue if necessary**

This is a separated bug issue from #3564

**Comment by shadovvs** [comment] 2017-02-28 17:03
After making this little modification to the 'OnRemove' function in TrinityCore, I tested Malady of the Mind and it worked as intended. Hope it helps.

```diff
diff --git a/boss_yogg_saron_trinity_core.cpp b/boss_yogg_saron_malady_jump_fix.cpp
index ddfddfb..84b43be 100644
--- a/boss_yogg_saron_trinity_core.cpp
+++ b/boss_yogg_saron_malady_jump_fix.cpp
@@ -2077,7 +2077,7 @@ class spell_yogg_saron_malady_of_the_mind : public SpellScriptLoader    // 63830
                         return;
                 }
 
-                GetTarget()->CastSpell(GetTarget(), SPELL_MALADY_OF_THE_MIND_JUMP);
+                GetTarget()->CastCustomSpell(SPELL_MALADY_OF_THE_MIND_JUMP, SPELLVALUE_MAX_TARGETS, 1);
             }
 
             void Register() override

```

**Comment by Rushor** [comment] 2017-02-28 17:20
Scripts/Ulduar: Yogg Saron - Limit amount of targets for spell SPELL_MALADY_OF_THE_MIND_JUMP

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3564
* commit: dc35ef5d3840dde797ee910f50bd534cf1617acb

Thanks added it to the repo.

**Comment by shadovvs** [comment] 2017-03-01 16:54
Fix for Tentacles spawning inside Yogg Saron's hitbox.
*Modified 'GetRandomPoint' function to generate a point in a ring defined by two radiuses if min_distance is provided.
*Yogg Saron tentacles won't spawn inside his hitbox.

Before:
[http://i.imgur.com/I32mPvW.jpg](http://i.imgur.com/I32mPvW.jpg)
After:
[http://i.imgur.com/4UFxVJg.jpg](http://i.imgur.com/4UFxVJg.jpg)

Fix:
[https://gist.github.com/shadovvs/1e40e2de5090ba9ebd75cfd26ab69601](https://gist.github.com/shadovvs/1e40e2de5090ba9ebd75cfd26ab69601)

**Comment by Rushor** [comment] 2017-03-01 19:13
alright concerning point 4:

> Malady of the Mind and Dominate Mind still act wonky after fading. Likely related to problems reported elsewhere regarding effects where players lose control of their players. It ends up leading to problems with warriors charging among other things. I know this has been reported before, but it is frustrating.

this must be fixed in https://github.com/dalaranwow/dalaran-wow/issues/1451

concerning point 2:

> In 25 man, Corruptor tentacles currently have a buffed hp value (about 33%) while the other tentacles use retail-like values. I just wanted to check if this was still intentional. The buffed values make it extremely difficult to keep the top level clear. My raiders were also mentioning that it seemed that they spawned too quickly. Unfortunately, I am usually assigned to the brain portal team, so I cannot confirm that.

That already works blizzlike on PTR. I cannot change that buff, only the server owner.

Point 1 and 3 are fixed by @shadovvs and can be tested on PTR once it was updated. Thanks for the help.

Game/Object: Update GetRandomPoint for Tentacles spawning inside Yogg Saron's hitbox

* Modified 'GetRandomPoint' function to generate a point in a ring defined by two radiuses if min_distance is provided.
* Yogg Saron tentacles won't spawn inside his hitbox.
* thanks to shadovvs
* closes: https://github.com/dalaranwow/dalaran-wow/issues/3564
* commit: fe422379899865bbf11896b91b49c49e11e66f7b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-01 19:13 UTC
Labels: Area - Instances, Fixed - Waiting for PTR Update

**Comment by Rushor** [comment] 2017-03-01 19:15
@shadovvs if you wanna apply more fixes you could use https://github.com/dalaranwow/TrinityCore/tree/3.3.5 for corechanges aswell :)

**Comment by shadovvs** [comment] 2017-03-01 19:57
@Rushor Maybe I will in the future. Had some free time so I decided to help out a bit. :P
