### ISSUE TITLE
[Quest][Outland] Stopping the Spread

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#953] opened 2013-11-01 11:33 UTC
http://www.wowhead.com/quest=9874/
players are able to burn 1 corpse 10/10 times making the quest easy to do
Sunspring Villager Corpse should despawn after burning it for the first time
http://www.wowhead.com/npc=18240

**Comment by Rushor** [comment] 2016-11-28 13:00
DB/Quest: Stopping the Spread - 'Liquid Fire' can only be used in 3 yards range and only once on Sunspring Villager

* closes https://github.com/dalaranwow/dalaran-wow/issues/953
* commit: d2ca44edf284485ec969495c37d0a0681588a0b2

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 13:00 UTC
Labels: Continent - Outland, On PTR, Quests
