### ISSUE TITLE
[NPC] Terl Arakor, gossip issue "MISSING TEXT" in Wetlands

### ISSUE THREAD

**Issue by MadmanMario** [dalaranwow/dalaran-wow#4694] opened 2017-05-03 18:08 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: NPC simply states MISSING TEXT.

**Expected behaviour**: NPC says what he should at this moment.

**Steps to reproduce the problem**:

1. Go to Wetlands
2. Find the NPC Terl Arakor
3. Talk to him

Evidence: http://imgur.com/I7WAtJ5
ID of NPC uncertain, wikis do not reveal it.

**Comment by TeridanDW** [comment] 2017-05-03 19:34
Confirmed. Thank you for the report @MadmanMario 
Regarding:

> ID of NPC uncertain, wikis do not reveal it.

you can find the ids in wowhead and openwow.

Having trouble finding what the "missing text" should be changed with. Not much of an information for this creature.

**Comment by Rushor** [comment] 2017-07-01 19:00
could someone with a retail account go close to that creature and see what gossip he has?

http://www.wowhead.com/npc=2153/terl-arakor#comments 

he's still available on retail.

**Comment by Rushor** [comment] 2017-07-02 13:25
that's his text http://i.imgur.com/ePA6ZZw.jpg

**Comment by Rushor** [comment] 2017-07-02 13:31
DB/Creature: Terl Arakor - Add missing gossip text 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4694
* commit: a1b747bbf10dcd7f63091e267fb9d7972c1fe0b5
* don't forget to delete the cache and restart the game before testing.

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-02 13:31 UTC
Labels: Area - Classic, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2018-01-30 18:10
Works as intended on PTR.
