### ISSUE TITLE
[Northrend] [Quests] Blood in the Water

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3889] opened 2016-11-27 13:52 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 The sharks can't be attacked/killed at their current position (at the bottom of the ocean). However, if the player swims up, the sharks will rise and start attacking the player, making this only a minor glitch.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 The sharks are sitting at the bottom of the ocean and can't be attacked.

**Expected behaviour**: Tell us what should happen instead
 They should swim in the ocean and be attackable, not just sit at the bottom and glitch.

**Steps to reproduce the problem**:

1.  Take the quest.
2.  Try to kill the sharks at the bottom.
3. 

**Include proofs for this behaviour**

https://postimg.org/gallery/1u0istcmm/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-27 14:03
they cannot swin yes. duplicate of https://github.com/dalaranwow/dalaran-wow/issues/3431

**Closed by Rushor** 2016-11-27 14:03 UTC
Labels: Duplicate
