### ISSUE TITLE
NPC: Razortalon

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1038] opened 2013-12-14 16:43 UTC
http://www.wowhead.com/npc=8210

Abilites were revamped in cata. In wotlk, he should've had 3 abilities, scaled to level:

http://wotlk.openwow.com/spell=11977
http://wotlk.openwow.com/spell=11976
http://www.wowhead.com/spell=3604

Currently mob just melees.

**Comment by Rushor** [comment] 2016-11-12 11:26
DB/Creature: Add Razortalon SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1038
* commit: 35ffefd659068fcd7bfb92530b4927ddc2a7f072

"Razortalon - In Combat - Cast 'Rend'"),
"Razortalon - In Combat - Cast 'Strike'"),
"Razortalon - Between 0-50% Health - Cast 'Tendon Rip' (No Repeat)");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 11:26 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 11:40
Works as intended on ptr.
