### ISSUE TITLE
Quest: If He Cannot Be Turned

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#1085] opened 2014-01-01 14:56 UTC
_Note: I did the Horde Version of this Quest, i'm not sure if the problem is present in the Alliance Version as well_

**Quest Name:** If He Cannot Be Turned
**Quest Link:** http://www.wowwiki.com/Quest:If_He_Cannot_Be_Turned_(Horde)
**Location**: Icecrown
**Quest Objective:** Defeat General Lightsbane
**Start NPC**: Baron Silver
**Start NPC Link:**: http://www.wowwiki.com/Baron_Sliver

**Issue Present:** Upon engaging General Lightsbane, the three NPCs you "turned" for the Pre-Quest (http://www.wowwiki.com/Quest:Free_Your_Mind) should come to help you, but they don't. This makes the Quest much harder than it should be.

**How it should work:** The following three NPCs should be spawned to aid you while fighting General Lightsbane:
Vile: http://www.wowwiki.com/Vile
Lady Nightswood: http://www.wowwiki.com/Lady_Nightswood
The Leaper: http://www.wowwiki.com/The_Leaper

**Comment by LoopyDemon** [comment] 2015-07-24 19:04
The mobs that are supossed to help you do show up now, but they are too weak and get killed by the Quest Mob almost instantly. This quest cannot be completed as is.

**Comment by Lothloryen** [comment] 2016-05-03 22:44
This quest received some general upgrades and should be fine already. Any feedback before closing it would be welcome.

Thank you.

**Comment by Crispybuilt** [comment] 2017-10-28 00:15
Still not working as intended, as @LoopyDemon mentioned, the friendly NPCs which are suppose to help you die within few seconds and it is extremly hard to overcome this quest.

Needs updates.

**Closed** 2017-12-02 13:15 UTC
Labels: Area - Northrend, General - Quests, Not working/incomplete fix
