### ISSUE TITLE
Mutiny on the Mercy

### ISSUE THREAD

**Issue by hairychestfan** [dalaranwow/dalaran-wow#5321] opened 2018-03-02 17:53 UTC
**Current behaviour**: 
The respawn rate of the skeletors below the ship deck is absurdly too long also they disappear when boat is moving because they fall behind due to boat movement then reappear when boat stops. Their position gets all glitchy when boats moves... IF they even are on the boat which it seems they never are so i am unable to complete a quest.

**Expected behaviour**: Skeletors should just chill on the boat and be killable.

**Steps to reproduce the problem**:

1. Accept quest
2. Go below to kill quest mobs
3. Realize they are not there and are never there because respawn time is bugged, if they are there they are all glitchy when boat moves so its a real RNG youll be able to kill em.. i only completed this quest sucessfully on 1 of my characters and it was a struggle.

**Include proofs for this behaviour**

https://user-images.githubusercontent.com/14928789/33717272-9025f41e-db59-11e7-96db-fcf0e8de2063.jpg

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=11527/mutiny-on-the-mercy
http://www.wowhead.com/npc=25026/mutinous-sea-dog

**Comment by Rushor** [comment] 2018-03-08 11:02
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/457

**Closed by Rushor** 2018-03-08 11:02 UTC
Labels: Duplicate / Invalid Report
