### ISSUE TITLE
[Quest][Northrend] The Plains of Nasam and Magic Carpet Ride

### ISSUE THREAD

**Issue by sean1359** [dalaranwow/dalaran-wow#3224] opened 2016-04-15 02:33 UTC
the undead your suposed to kill and the floating platforms from with chh they decend are all buged making the quest incompletable

**Comment by rinleezwins** [comment] 2016-04-20 06:01
The quest is totally completable and as a matter of fact I did it just a few hours ago. The ghouls are bugged - they don't aggro or take any damage. The tank's mines don't seem to ever detonate and the fireball skill flies in a random direction. That being said, you can still do the quest pretty easily by rounding the mobs up and using number 3+4 abilities.

**Comment by Rushor** [comment] 2016-11-25 10:41
http://wotlk.openwow.com/?quest=11642

**Comment by Rushor** [comment] 2016-11-25 11:06
the undeads which are summoned by the platforms are not attackable, because the dummy summons them in the sky

**Comment by Rushor** [comment] 2016-11-25 11:08
DB/Quest: The Plains of Nasam - Mindless Aberration is attackable now after summon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3224
* the summoned Mindless Aberration http://wotlk.openwow.com/?npc=25469 will fall to the ground now, once they are summoned (you can attack them with the vehicle now)
* commit: 6c0580c7610dbfc6c7ee68bf08c862f1e9845acc

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-25 11:08 UTC
Labels: Continent - Northrend, On PTR, Quests
