### ISSUE TITLE
[NPC] Netherweb Victim 

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#948] opened 2013-10-30 20:56 UTC
http://www.wowhead.com/npc=22355/netherweb-victim
the creatures spawning after destorying the cocoons are correct 
but the issue is that more than 1 creature is getting spawned 2 - 4 mostly

**Comment by Rushor** [comment] 2016-11-12 13:46
DB/Creature: Netherweb Victim - Always summon one unit

* closes https://github.com/dalaranwow/dalaran-wow/issues/948
* only one creature will be summoned now after you killed the netherweb

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 15:36
Works as intended on ptr, however there are few more issues with this creature:
 - it shouldn't yell any experience
``` sql
UPDATE `creature_template` SET `flags_extra` = 66 WHERE `entry` = 22355; 
```
 - it shouldn't attack/aggros the player that attack him
 - it shouldn't regenerate hp out of combat

And  the creature that is spawned from Netherweb Victim should:
 -  attackstart > invoker (player that kills the Netherweb Victim)
 -  despawn on evade

**Closed** 2017-11-30 14:25 UTC
Labels: Area - Outland, Fixed - Waiting for PTR update, Works - but it needs improvements.
