### ISSUE TITLE
[NPC] Doomsayer Jurim

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1821] opened 2014-08-21 23:21 UTC
http://www.wowhead.com/npc=18686

Should have 4 abilities, scaled to his level:
- Corruption (http://www.wowhead.com/spell=39212)
- Curse of weakness (http://www.wowhead.com/spell=12493)
- Fear (http://www.wowhead.com/spell=39210)
- Shadow bolt (http://www.wowhead.com/spell=12471)

Currently just melees instead. Patrol waypoints are fine though.

**Comment by Rushor** [comment] 2016-11-13 21:11
DB/Creature: Add abilities for Doomsayer Jurim

* closes https://github.com/dalaranwow/dalaran-wow/issues/1821
* closes aed56301be6ced6ae6f16a96f5628b2b86f89147

0,"Doomsayer Jurim - In Combat - Cast 'Shadow Bolt'"),
,0,0,0,0,"Doomsayer Jurim - In Combat - Cast 'Fear'"),
,0,0,0,"Doomsayer Jurim - In Combat - Cast 'Corruption'"),
,0,0,0,"Doomsayer Jurim - In Combat - Cast 'Curse of Weakness'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 21:11 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 10:52
Works as intended on ptr.
