### ISSUE TITLE
crushridge warmonger patrol route bug

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3814] opened 2016-11-08 22:45 UTC
**Description**: theres a castle in alterac ruins in alterac mountains where big trolls are, theres supposed to be ONE patrolling an area in the castle but instead there's 3 walking at the same time in the same spot.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) 
Crushridge Warmonger , 3 of them patrolling where there should be only 1. they overlap because theyre walking in the exact same spot. this is in alterac mountains in alterac ruins, in the castle

**Expected behaviour**: only one mob should be patrolling that route instead of 3

**Steps to reproduce the problem**:

1. go there
2. be surprised
3. run

**screenshot**
http://imgur.com/a/9NoiU

**ID** 
http://www.wowhead.com/npc=2287/crushridge-warmonger

**Comment by Rushor** [comment] 2016-11-09 10:30
one Crushridge Warmonger is going an other direction than the orther Crushridge Warmongers.
I will remove one unneeded Crushridge Warmonger

**Comment by Rushor** [comment] 2016-11-09 10:35
DB/Creature: Remove one unneeded Crushridge Warmonger

* closes https://github.com/dalaranwow/dalaran-wow/issues/3814
* commit: 2e1b2831a275ade0b87b26c97265c1eac9aaffb9

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-09 10:35 UTC
Labels: Continent - Classic
