### ISSUE TITLE
[NPC] Horde Scout (#11680) issues

### ISSUE THREAD

**Issue by waefre1** [dalaranwow/dalaran-wow#1429] opened 2014-04-01 06:43 UTC
Mob: Horde Scout (#11680)
Location: Warsong Lumber Camp, Ashenvale Forest
Server: Algalon

There are two distinct issues I've noticed here.
1) Non-reactive AI : Horde Scouts properly aggro onto any PC who moves into their radius or attacks, but they do not take any actions beyond running away (they do not move, attack, use abilites, etc.). I've not been able to keep one alive long enough past that point to see if they return to normal behaviour or if they still stand there looking menacing.

and

2) Dialogue : Horde Scouts use taunts that seem to be drawn from some manner of Dark Iron Dwarven mob (they say things like "Feel the power of the Dark Iron Dwarves!" and "Never cross a Dark Iron, < class >!")

Edit : Re:Non-reactive AI - Horde Scouts that run away and survive long enough to come running back do remain non-reactive.

**Comment by Rushor** [comment] 2016-11-10 21:38
DB/Creature: Fixup behaviour for Horde Scout

* closes https://github.com/dalaranwow/dalaran-wow/issues/1429
* creatures will attack you now, and flee-for-assist once they reach 15 % HP
* creatures will no longer talk the Dark Iron Dwarven sentences
* commit: 7435dad69b61eec55f75c98aa7d2c880642d5e3f

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-03 18:34
Npc http://wotlk.openwow.com/npc=11680 doesn't use spell http://wotlk.openwow.com/spell=18545 now,
everything else works as intended on ptr.

**Comment by Rushor** [comment] 2018-03-18 19:10
The creatures uses the spell every now an then in range:

```sql
(@ENTRY,0,2,0,9,0,100,0,5,30,12000,15000,11,18545,0,0,0,0,0,2,0,0,0,0,0,0,0,"Horde Scout - Within 5-30 Range - Cast 'Scorpid Sting'"),
```

**Closed by Rushor** 2018-03-18 19:10 UTC
Labels: Area - Classic
