### ISSUE TITLE
[NPC] Bael'dun Foreman + Sunblade Mage Guard Incorrect behaviour of NPCs that cast spells

### ISSUE THREAD

**Issue by Schnap** [dalaranwow/dalaran-wow#1793] opened 2014-08-06 19:43 UTC
An example of an NPC acting incorrectly when going out of line of sight. 
The NPC should follow you behind the wall and continue attacking, and not just stand at its location
![image](https://cloud.githubusercontent.com/assets/5253352/3832899/dbc2a418-1da1-11e4-83b6-b7a6407f492c.png)

**Comment by bravade** [comment] 2015-01-15 20:02
Is this issue going to be solved ? Sorry but this is why I don't play on Dalaran (I play PVE tank and I think line of Sight pulling is important).
Thank you !

**Comment by Rushor** [comment] 2016-11-14 14:04
this issue affects only certain creature which have no CMC move. we must add this script individually for the creature. This cannot be fixed in general. I will fix it for the http://wotlk.openwow.com/npc=24683 in this ticket. If there are more creatures with the incorrect cast/chase behaviour, please open up a new ticket. Thank you

**Comment by Rushor** [comment] 2016-11-14 14:08
DB/Creature: Update SAI for Sunblade Mage Guard and Bael'dun Foreman

* closes https://github.com/dalaranwow/dalaran-wow/issues/1793
* commit: 09b383d0998078dd9259492e3c7883e6890cfb24

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 14:08 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 10:57
Works as intended on ptr.
