### ISSUE TITLE
[Zul'Gurub] Hakkar The Soulflayer

### ISSUE THREAD

**Issue by Stealthmate** [dalaranwow/dalaran-wow#2113] opened 2014-12-12 16:22 UTC
Ok, so I tried doing this today solo. I had all priests down except for Jeklik. Her silence during the fight worked fine. But there were one problem:

Will of Hakkar. According to WoWWiki: Will of Hakkar: Takes control of a humanoid enemy up to level 65 for 20 sec.
   Well I'm level 80, I should NOT be affected by this.

In any case, according to what I've read around in battle.net forums, Hakkar IS soloable and should NOT mind control when there is only one person fighting him.

**Comment by Witeness** [comment] 2016-05-06 23:21
The tooltip on Will of Hakkar is incorrect, there is omments claiming that they still get MCd at level 65+ in wowhead.

Anyway, it seems to be broke at least on DKs. Without a pet (neither ghoul, army of ghouls or gargoyle), they still ge MCd without a chance of getting the kill.

Tested several times, with pet, with ghoul, with army of ghouls, without all of them and noone worked

**Comment by Rushor** [comment] 2016-11-17 20:43
Hakkar should not cast his mc, if there is only one person fighing him. If you try to kill him with 2 players or more > cast mc.

**Comment by Rushor** [comment] 2016-11-17 20:45
Scripts/ZulGurub: Hakkar - Do not cast MC if there is only one player target infight

* closes https://github.com/dalaranwow/dalaran-wow/issues/2113
* commit: 1d93ce1b96175fa0ed3cd03d6c502489660919bb

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-02 18:37
Works as intended on ptr, however Hakkar casts spell http://wotlk.openwow.com/spell=24690 on victim (and if we asume it's only 1 player trying to kill him/her/it) resuslts in encounter reset because that spell has:

> Apply Aura: Mod Stealth 
> Value: 1000

**Closed** 2017-04-02 18:40 UTC
Labels: Area - Instances
