### ISSUE TITLE
[Quest] Morrowgrain to Darnassus/Feathermoon Stronghold

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1765] opened 2014-07-25 23:02 UTC
Those quests should be available after morrowgrain research(part 2) and should be repeatable.

Right now the morrowgrain research is a repeatable quest so theres no way to ever do the two quests.Morrowgrain to Darnassus/Feathermoon Stronghold

http://www.wowwiki.com/Quest:Morrowgrain_Research_(Alliance,_2)

**Comment by Rushor** [comment] 2016-11-23 14:33
DB/Quest: improve Alliance's "Morrowgrain Research" quest chain 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1765
* commit: 08d99174a106bdef185d9aef5caf5ef87c58e32d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 14:33 UTC
Labels: Continent - Classic, On PTR, Quests
