### ISSUE TITLE
Crashin' Trashin' Robot

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3776] opened 2016-10-14 15:27 UTC
**Description**:
The Toy, made by engineers, can be placed on the ground and it emits a black smoke, has a 3 minute cooldown.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The toy should despawn after 3 minutes, when you can place a new one. i.e. you can only have one robot at a time.
**Expected behaviour**: Tell us what should happen instead
The toy does not despawn until a GM kills it or a server resets, so a player can make any "art" by placing the toys indefinitely.
**Steps to reproduce the problem**:
1. Place the Crashin' Thrashin Robot;
2. Wait 3 minutes. The Robot does not despawn;
3. Place a new Crashin' Thrashin' Robot.

**Include proofs for this behaviour**

http://www.wowhead.com/item=23767/crashin-thrashin-robot#comments:id=123232

> after 3 minutes the robot breaks apart and you can place a new one

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Crashin' Thrashin' Robot item ID 23767

**Comment by Rushor** [comment] 2016-11-10 19:05
DB/Creature: Crashin' Thrashin' Robot - Despawn 3 minutes after summon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3776
* commit: b0dfe16bd57e425c8f2c580006021cf0b49ed60b

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 19:05 UTC
Labels: Items, On PTR, Priority - Low

**Comment by TeridanDW** [comment] 2017-03-31 08:06
The despawn part works properly, however there should be:

> 3 minutes cooldown on using the item, after 3 minutes the robot **breaks apart** and you can place a new one, item stays.

before the despawn.

**Comment by Aridam** [comment] 2017-11-24 12:44
Confirmed on Live as well -- there's "art" in front of the Auction House in Orgrimmar at the moment that's been there for at least two days by my own memory.
