### ISSUE TITLE
[Winter Veil] Crashin' & Trashin' is not crashing and trashing because it doesn't exist!

### ISSUE THREAD

**Issue by lowbow** [dalaranwow/dalaran-wow#3054] opened 2015-12-20 21:44 UTC
Winter came and it's time to do some funny achievements like this one.

According to wowhead (http://www.wowhead.com/achievement=1295/crashin-thrashin),
Blue Crashin' Thrashin' Racer Controller supposed to give you a vehicle vision and one ability that crashes & trashes an opponent vehicle.

Me and another player have been trying to use it. None of us saw any kind of the vehicle and there were no ability to crash & trash, interface was empty. The only present ability was to cancel the vision.

It would be nice if you fix it till the end of event.

Thx, have fun!

**Comment by Rushor** [comment] 2016-11-09 11:34
ach fix and some other winter veil fixes inc.

**Comment by Rushor** [comment] 2016-11-09 13:16
Scripts/Spells: Implement Crashin' & Trashin' (Winter Veil)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3054
* add ach. credits
* fix visuals and charge effects
* commit: 5bf886acdc8f1240f3c87458fb0df2b61c13299f

![GitHub Logo](http://i.imgur.com/pTfEf6E.jpg)
![GitHub Logo](http://i.imgur.com/ZqoJHkP.jpg)
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-10-17 10:31
@Lothloryen what is the situation with this report (On PTR)?

**Comment by Lothloryen** [comment] 2017-10-17 10:42
Hello, not applied yet, need to push a correction to fix the build.

**Comment by Lothloryen** [comment] 2017-10-17 22:58
Now yes, it is on PTR.

**Comment by TeridanDW** [comment] 2017-10-18 07:43
Hello after few tests on PTR here are the results:
 - None of us saw any kind of the vehicle and there were no ability to crash & trash, interface was empty.

Is now fixed.

 - fix visuals and charge effects
is not working as nothing happens when player uses spell https://wowgaming.altervista.org/aowow/?spell=49297

 - add ach. credits
is not testable because of the issue above.

**Comment by Crispybuilt** [comment] 2017-12-05 18:50
As Winter Veil is coming close, this will hopefully get a somewhat decent fix.

**Comment by Lothloryen** [comment] 2017-12-15 19:44
Hello there,

The remaining issues have been corrected.

Thank you.

**Closed by Lothloryen** 2017-12-15 19:44 UTC
Labels: General - Achievements, Not working/incomplete fix
