### ISSUE TITLE
[NPC] Coilfang Scale-Healer

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1915] opened 2014-09-27 10:41 UTC
http://www.wowhead.com/npc=21126

Overall those nagas work fine, but when they attempt to use their Heal spell (http://www.wowhead.com/spell=34945), it gets stuck right at the beginning. It's hard to explain on text, but simply put, they'll try to recast it every 0,1 sec, so cast won't proceed anywhere and they remain stuck like that for eternity.

Similar issues were reported here for some other NPCs with healing spells a year ago or so, but sadly I can't seem to remember what exactly those creatures were (and they were fixed eventually anyway, if I'm not mistaken).

**Comment by Rushor** [comment] 2016-11-13 20:21
DB/Creature: Add abilities and texts for Coilfang Scale-Healer

* closes https://github.com/dalaranwow/dalaran-wow/issues/1915
* commit: 4f2cd6faf5c7027cb795f111e6fb1ccfca880bb4

"Coilfang Scale-Healer - On Aggro - Say Line 0"),
,0,"Coilfang Scale-Healer - Friendly At 1000 Health - Cast 'Heal' (Normal Dungeon)"),
,0,"Coilfang Scale-Healer - Friendly At 1000 Health - Cast 'Heal' (Heroic Dungeon)"),
,0,0,"Coilfang Scale-Healer - In Combat - Cast 'Holy Nova' (Normal Dungeon)"),
,0,0,"Coilfang Scale-Healer - In Combat - Cast 'Holy Nova' (Heroic Dungeon)"),
0,0,"Coilfang Scale-Healer - On Friendly Unit Missing Buff 'Power Word: Shield' - Cast 'Power Word: Shield' (Normal Dungeon)"),
0,0,"Coilfang Scale-Healer - On Friendly Unit Missing Buff 'Power Word: Shield' - Cast 'Power Word: Shield' (Heroic Dungeon)");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 20:21 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 08:33
Npc casts spells properly now, however i would like to suggest a bit of tunning here:
 - http://wotlk.openwow.com/spell=36052 and http://wotlk.openwow.com/spell=17139 (the value scales) seems to be spammed a lot, maybe increase the cd by few secs
 - http://wotlk.openwow.com/spell=34945 and http://wotlk.openwow.com/spell=39378 (the value scales) are been casted when a friendly creature looses 1000 hp, however these heals a powerful and they can get more value if they are used on creature looses X% hp instead.

Note: This are more of personal opinion, so it can be ignored. Marking as:
