### ISSUE TITLE
distance totems

### ISSUE THREAD

**Issue by fixlol** [dalaranwow/dalaran-wow#3631] opened 2016-08-03 14:26 UTC
hi, I have seen on this server bug on a shaman totems, when the shaman places the 4 totems they are too close together, almost attaccati.non know if it's a bug, but it is very annoying because you can hardly distinguish between them .
this is a picture of the correct placement of the totems:
http://imgur.com/a/aPqy9
http://imgur.com/a/glFDo

I can even wrong, but I'm sure you are very close to each other, if you can control and give me an answer? thank you

I did the screen: this is the totem distance in our server:
http://imgur.com/a/BTCyt
http://imgur.com/a/VKZJi

**Comment by robinsch** [comment] 2016-08-04 13:44
On PTR.

**Comment by fixlol** [comment] 2016-08-04 20:18
what it means on ptr? we are resolving it?

**Comment by robinsch** [comment] 2016-08-04 20:32
On PTR means a fix has been applied on the test realm.

**Closed** 2016-08-11 09:19 UTC
Labels: Class#Shaman, Spells/Auras

**Comment by robinsch** [comment] 2016-08-15 12:40
Tested.

**Comment by TeridanDW** [comment] 2017-03-31 18:24
Works as intended on ptr.
