### ISSUE TITLE
Lord Marrowgar, not working 100% correctly

### ISSUE THREAD

**Issue by g0g0dancer** [dalaranwow/dalaran-wow#4778] opened 2017-07-05 19:59 UTC
**Current behaviour**: Lord Marrowgar currently targets random raid members, regardless of distance to him, or if they have bone spike or not. He will occasionally target the same player consecutively.

Lord Marrowgar also does about 30k ticks of physical damage during bone storm if he is directly over top of you. (If you are bone spiked, he can target you, and you take the full ticks)

**Expected behaviour**: Lord Marrowgar is supposed to "pinball" around the room, targeting raid members that are among the furthest away from his current location. (Generate a set of players that are furthest from Lord Marrowgar [50% of the players to generate the set], then pick a random player from that set).

Should only do 10-11k ticks of physical Damage on 25 player Heroic.

Bone Storm:
Attacks nearby enemies in a whirlwind of bone that lasts until cancelled. 3 sec cast. Every two seconds, triggers...
[Bone Storm] Attacks nearby enemies in a whirlwind of bone, which causes them to bleed for 15 seconds. Instant. 8000+?/3 on Normal. 11000+?/3 on Heroic. (ticks every 2 seconds 
(source http://et.worldofwarcraft.wikia.com/wiki/Lord_Marrowgar)
(http://www.wowhead.com/spell=69075/bone-storm) [shows 10350 dmg per tick for 25 hc]

**Steps to reproduce the problem**:

1. Pull Marrowgar HC 25
2. Spread out
3. Have someone stand in bone storm

**Include proofs for this behaviour**
![marrowgar](https://user-images.githubusercontent.com/24669454/27882487-ada95744-6181-11e7-92e0-fbd8a7e3217b.png)
Screenshot of combat log. (was bone spiked so unable to dodge bone storm, no other player at my location)

Sources of his expected behaviour
http://www.mmo-champion.com/threads/694764-Guide-to-Heroic-ICC
Check Lord Marrowgar section for how to deal with this expected behaviour.
https://www.youtube.com/watch?v=YUlvH8n_Zwg
Tankspot guide, with the video of some of his bone storm behaviour. Can check any other Lord Marrowgar video to confirm his behaviour.

**Comment by Rushor** [comment] 2017-07-05 20:12
we must use cbrtf function instead sqrt function here. 

Scripts/IcecrownCitadel: Marrowgar - Calculate bonestorm damage to distant targets properly

* closes https://github.com/dalaranwow/dalaran-wow/issues/4778
* This fixes that you will lower damage if you have an increased distance to marrowgar
* commit: 33db346d3f9fd7b1249c68de3908ee6b10e0a398

> (If you are bone spiked, he can target you, and you take the full ticks)

Cannot confirm this on PTR.

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-05 20:12 UTC

**Comment by ashido96** [comment] 2017-07-06 04:27
Did you also fix him bone storming to people right next to him? He shouldn't be able to move(target)to like the 10 people closest to him while casting bonestorm. There's no fixed number that I can find anywhere but that's about what I think the number of players is after watching like 30 bonestorms cross 10 different kill videos.

**Comment by g0g0dancer** [comment] 2017-07-06 07:33
yeah, i have been targeted twice in a row in 10 and 25 man, while full raid up. 
makes the fight more RNG based than retail. 
once even targeted 3x in a row

**Comment by Rushor** [comment] 2017-07-06 09:55
Lord Marrowgar should always select the most farest player away from his current position. I will research if i alreay fixed that.

**Comment by StheNoble** [comment] 2017-07-06 16:16
i am a bit confused here. @Lothloryen explicit increased Bonestorm Damage. (because it did hit like a wet noodle on Retail - my opinion). 

We checked the damage fall off with increased distance from his hitbox on the Beta, which worked fine. Just the overall Damage has been increased significant. As i said, as far as i know thats intended and shouldn't be a part of this Bugfix.

> >(If you are bone spiked, he can target you, and you take the full ticks)
> Cannot confirm this on PTR.

i can confirm it happened on the Beta and so does on Live. If it doesnt happen on PTR, what has to be changed on live to solve this, since there will never be a full merge of the PTR code base to Live. Or in other words, whats the difference between both that has to merged?

**Comment by Rushor** [comment] 2017-07-06 18:09
> Or in other words, whats the difference between both that has to be merged?

current dalaran ptr = tc version + dalaran dev fixes

BUT the ptr will change in 2 weeks, so we actually develop on the live version of Dalaran and fixes can get merged easier.

**Comment by StheNoble** [comment] 2017-07-06 22:01
that sounds great @Rushor. And sounds more productive, i guess.  thx for the info.

**Comment by datbunneh** [comment] 2017-11-24 23:25
@Lothloryen @TeridanDW Please have a look at this. It's not live yet.

**Comment by alexuktc** [comment] 2018-04-01 13:45
It is still not live.
