### ISSUE TITLE
[Pet] Scaling Warlock, Shaman, Priest, Mage, Hunter, Death Knight

### ISSUE THREAD

**Issue by Dolmio1** [dalaranwow/dalaran-wow#3088] opened 2016-01-07 01:01 UTC
Hello, did some testing after toc launch since you guys promised a pet scaling patch for felguard (#2909) and i noticed nothing had been done, decided to do some testing again and i noticed felguard crit was sort of working, he still misses though (doesnt gain masters hit) and his damage was slightly higher (doing 650 dps instead of 400).

Unholy pet was still doing bad damage, had low crit and no hit / expertise what so ever.

Could we finally have some promised fixes?

" Lothloryen commented on 25 Sep 2015

Hello there,

Thank you very much. After the release of TOC, I will implement a patch where most of the issues related to the pet scaling will be corrected."
![petsskada](https://cloud.githubusercontent.com/assets/13223625/12159426/cb7a903e-b4ea-11e5-8ce7-31e6f50d337f.png)

Was doing some testing on my dk/lock and a guildies lock aswell, lanai has higher gear and tier 9 2 piece (gives crit to the pet), unholy pet is borderline broken.

Best regards,

**Comment by Johanes022** [comment] 2016-01-07 12:16
I can confirm that DK pet doesnt gain  masters hit rating wich is very frustrating in pvp when you are over the hitcap and your pet misses gnaw most of the time.

**Comment by Lothloryen** [comment] 2016-01-07 13:22
Hello there,

Thank you, I have been working on this, now that the Holidays are finished, I shall continue with it. I will keep you updated.

**Comment by Lothloryen** [comment] 2016-01-09 18:49
Hello again,

A small update, Felguard will now scale properly. Working on Risen Ghoul now.

A patch with these corrections shall be deployed during the next few days, I will post here when it is live.

Thank you.

**Comment by Almondswow** [comment] 2016-01-10 01:02
Can we see what else will be in that patch fix wise?

**Comment by Johanes022** [comment] 2016-01-10 09:24
Good to hear that!
Would be nice to see all patch fixes somewhere on forum tho.

**Comment by Lukas45** [comment] 2016-01-10 18:05
Will you also be fixing the hit issues with pets? Currently they get 0 hit from its master

**Comment by Sigwastaken** [comment] 2016-01-21 22:16
This is also a big deal for hunters. Will you be fixing hit and stat scaling for hunters pets as well?

**Comment by Dolmio1** [comment] 2016-02-13 23:07
Any update after a month? "few days"....

**Comment by Lothloryen** [comment] 2016-02-14 00:18
Yes, Felguard was deployed already. I am currently working on the Risen Ghoul, still need further test from the testers though - I had a break from this issue since I needed to work on a more important troubles reported by some users via e-mail.

**Comment by Sigwastaken** [comment] 2016-02-14 06:49
One of our warlocks tested felgaurd after seeing this post and found that while he is not seeing the misses and dodges he was before, the pet is still not scaling with his other stats either. 

Additionally hunters have these exact same problems as well as many others with our pets. When will we be seeing fixes for this issue?

**Comment by Pavidlaa** [comment] 2016-02-27 00:59
How to fix my warlock imp, then i summon imp he is dying after 10 sec, like burning from immolate, please help

**Comment by Lukas45** [comment] 2016-02-27 13:02
Go to OS, put the Imp in the lava and out again before it dies

**Comment by robinsch** [comment] 2016-07-01 10:26
Scaling for Hunter on PTR.

**Comment by ciccioriccio** [comment] 2016-07-17 15:20
The dk pet's stats dont scale with the master's ones. (some other class may have the same issue, but need a confirm)
this is happening after the update of few days ago

**Comment by robinsch** [comment] 2016-12-03 13:07
Commit Hash: fb6193b8924e4b8686bfb2e3a0257f1483025ef6
Script/Warlock: Implement Pet scaling

**Comment by robinsch** [comment] 2016-12-03 13:55
Commit Hash: 54836fe5e14cd9f25ee45e0108a91ee94769ad9a
Script/Shaman: Implement Pet scaling

**Comment by robinsch** [comment] 2016-12-03 14:33
Pet scaling on PTR.

**Closed by robinsch** 2016-12-03 14:33 UTC
Labels: Class - Death Knight, Class - Hunter, Class - Mage, Class - Priest, Class - Shaman, Class - Warlock, Fixed - Waiting for PTR Update

**Comment by roblockster** [comment] 2017-05-27 07:13
Any estimate on when this fix will come to live?

**Comment by Edzero** [comment] 2017-05-31 18:08
Has to be applied to the PTR by Lothloryen so the testers can verify the fix works properly. After that it gets pushed to live in the next changelog.

**Comment by fsironman** [comment] 2017-06-01 18:27
And why does this have to take 6 Months?
Fixing all the Class Bugs is way more important than bringing out ICC.

**Comment by robinsch** [comment] 2017-06-01 19:05
Because have have 0 testers.

**Comment by tripleslash** [comment] 2017-06-18 12:05
Can you just push this untested if noone wants to test it, everything is better than current non existing pet scaling. Thank you.

**Comment by Edzero** [comment] 2017-06-18 16:24
Feel free to apply for tester position:

http://www.dalaran-wow.com/forums/news-and-rules/news-and-announcements/topic/8531/recruiting-testers

**Comment by Lothloryen** [comment] 2017-10-13 11:19
Hello there,

Warlock pet scaling is now on the new PTR, testing needed. Will update with the rest after this is checked.

**Comment by tripleslash** [comment] 2017-10-17 12:47
Was parts of this applied on live already? Gargoyle scaling seems to work much better but the Ghoul is still broken as fuck.

**Comment by TeridanDW** [comment] 2017-10-17 13:39
Hello @tripleslash, you have check if a report is live if he has a label "Fixed - On Live Server" (top right on the report). 
Regarding your question the answer is no and the only diffrence in gargoyle scaling should be this one #2213 as for the report itself I simple does not have enough knowledge to proved an accurate feedback for the developers alone. That's why it is still staying on PTR.
If someone wants to help by providing information how each pet is suppose to scale I'll do my best to test them all as soon as possible, thank you.

**Comment by Lothloryen** [comment] 2017-10-17 17:39
Hello there,

Mage/Druid/Priest/Warlock pets have now Robinsch's pet scaling implementation. Hunter/Death Knights scaling was already on live, if there is something wrong please, let us know as detailed as possible and Robin will work on it.

Thank you very much.

**Comment by tripleslash** [comment] 2017-10-17 18:11
Ghoul doesn't get masters crit rating on live at the moment

**Comment by robinsch** [comment] 2017-10-18 11:25
@tripleslash Ghouls didn't scale with crit rating on 3.3.5

https://wow.gamepedia.com/Risen_Ghoul
https://us.battle.net/forums/en/wow/topic/2650315399

**Comment by Chenocide** [comment] 2017-10-29 22:32
@Lothloryen What about shaman pets?

**Comment by Lothloryen** [comment] 2017-10-29 22:51
@Chenocide My apologies, forgot to add Shamans. Yes, they also had the pet scaling applied.

**Comment by Lothloryen** [comment] 2017-12-09 14:23
Hello there,

I saw some comments from players who claims that Felguard is still not working as it should, however, no report. So, if anyone could give some feedback it would be more than welcome so we can check it out.

Thank you very much.
