### ISSUE TITLE
[Quest][Outland] A Spirit Ally?

### ISSUE THREAD

**Issue by xxauroraxx** [dalaranwow/dalaran-wow#2538] opened 2015-06-18 03:18 UTC
You are supposed to use an item in a specific area. There is NO area where the item can be used. Confirmed with wowhead comments where to use item, and it still would not function.

**Comment by Rushor** [comment] 2015-06-18 06:00
maybe it was disbaled because you can summon thousand of http://www.wowhead.com/npc=18185/feralfen-serpent-spirit with this item

**Comment by darkwulfv** [comment] 2015-06-18 18:22
Worked for me a couple weeks ago. I used it at the bottom of the stairs, but not at the exact bottom; I was a few feet away. Friend of mine also got it to work.

**Comment by Sagrath** [comment] 2015-06-23 21:58
Doable, Boha'mu Ruins Stairs place marker GO ID 99924 radius need to be bigger and missing condition for multiple spawn of the Serpent spirit 18185
quest id 9847

**Comment by Rushor** [comment] 2016-11-11 13:16
DB/Quest: A Spirit Ally?

* increase radius for questitem to 25 yards
* you can no longer cast Place Feralfen Totem (questitem) if Feralfen Serpent Spirit is in 50 yards range
* closes https://github.com/dalaranwow/dalaran-wow/issues/2538
* commit: c99e195cf220e34f69533831948efe2a25c9df5b

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 13:16 UTC
Labels: Continent - Outland, On PTR, Quests

**Comment by Bonham01** [comment] 2016-12-17 22:45
Just to show others roughly where to stand until this fix gets applied to the live server, here is a screenshot of where I was standing to get the totem to work.

http://imgur.com/a/8eith

**Comment by TeridanDW** [comment] 2017-04-02 10:20
Works as intended on ptr.
