### ISSUE TITLE
NPC- Shadowstalker Luther Quest- Untold Truths AGAIN

### ISSUE THREAD

**Issue by Arrowzinger** [dalaranwow/dalaran-wow#2766] opened 2015-08-08 00:25 UTC
Original thread here: https://github.com/dalaranwow/dalaran-wow/issues/2764
Same issue, was marked completed, just wanted to let you know it is going to keep bugging out so something might want to be done.

**Comment by Golganeth** [comment] 2015-08-08 12:40
Right now he's on a different spot and under textures, which means he gets knocked/moved by something. Could be the explosion triggered by a quest close to that spot.

**Comment by Brothus** [comment] 2015-08-09 19:50
It's bugged from time to time, I went there to check periodically and eventually he was there, just saying.

**Comment by Arrowzinger** [comment] 2015-08-09 22:17
I'll keep looking but considering what Golganeth said makes a lot of sense and is super funny. I did do the bombing of the nests or whatever right before getting to this guy, so there is a high possibility to this.

**Comment by Arrowzinger** [comment] 2015-08-09 22:20
Yeah still not there, is there any way that someone can move him away from the blast zone?  I know this will take some time.

**Comment by sly117** [comment] 2015-08-10 04:53
He appears to be under Warsong Hold now.

**Comment by lyrathecleverpony** [comment] 2015-08-10 10:47
Yes. During my leveling experience in Northrend, it was annoying to search everywhere for this guy, only to find out by asking Global that he's bugged, and stuck under the Warsong Hold.

May it be because of a "rare pathfinding issue" or "the explosion triggered by the quest next to that spot." this really should be fixed. Northrend is an important and vital area in Wrath of The Lich King, and the main endgame questing zone. It should not have things like this occurring.

**Comment by Oelacs** [comment] 2016-02-19 11:48
Okej, then i try this 4 mounth old one, Fix the quest, he is under the groud again!

**Comment by SadhuArch** [comment] 2016-04-04 12:55
I believe that the problem is caused by the knockback from the "Seaforium Depth Charge Explosion" spell (45502) from the NPC "Seaforium Depth Charge" (25401) / item "Seaforium Depth Charge Bundle" (34710) which you use to destroy Nerub'ar sinkholes during the quest "Bury Those Cockroaches!" (11608).

So the issue should be fixed by removing the knockback. Not very "retail" but it should be a  relatively quick fix.

**Comment by VonKaufmann** [comment] 2016-04-06 09:00
Ok, this is now happening again. Luther is stuck beneath Warsong Hold.
Is anything being done to fix this? It would have been one thing if it was an old world quest, but you should at least have the Northrend quests working.

**Comment by Golganeth** [comment] 2016-06-05 18:22
Just tested it, the bomb that (sometimes) follows the player, will knock this NPC away.

Reported on #583

**Closed by Golganeth** 2016-06-05 18:22 UTC
Labels: Northrend, NPC

**Comment by Golganeth** [comment] 2016-06-23 13:05
Issue with NPC fixed, applied to live realm soon.
