### ISSUE TITLE
[Mage] Dalaran Brilliance

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2662] opened 2015-07-14 15:10 UTC
I was in a party making a portal to Dalaran to a random player, when upon re-buffing myself Dalaran Brilliance (DI: 61316) I have buffed the lowbie player as well. I have tested it on few people, and I was confirmed, Dalaran Brilliance can go even to level 1 as well. 900 more mana is awesome.

Arcane Brilliance works as intended, as well as Arcane and Dalaran Intellect both.

**Comment by Rushor** [comment] 2016-11-23 18:38
Scripts/Spells: Mage Dalaran Brilliance will only affect player >= level 75

* this prefents the cast of this spell on low level characters or pets
* closes https://github.com/dalaranwow/dalaran-wow/issues/2662

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-10-23 08:05
After few tests on PTR:

> Scripts/Spells: Mage Dalaran Brilliance will only affect player >= level 75
>  - this prefents the cast of this spell on low level characters or pets

Works as intended on PTR, however I would like to ask why set level 75 or up?
Based on how spell https://wowgaming.altervista.org/aowow/?spell=43002 works in-game now (gets applied on level 70 and up players/pets) so should Dalaran Brilliance as the only diffrence between them is visual/cosmetic.

**Comment by robinsch** [comment] 2017-10-23 10:02
@Rushor

**Closed** 2017-10-23 19:39 UTC
Labels: Class - Mage, Fixed - Waiting for PTR update

**Comment by TeridanDW** [comment] 2017-10-24 11:06
Work as intended on PTR.
