### ISSUE TITLE
[Item] Mage Tier 8 (4) bonus

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#1984] opened 2014-10-18 12:06 UTC
"You have a chance for the effect of your Missile Barrage, Hot Streak, or Brain Freeze talent not to be consumed when you cast the spells which benefit."

Mage Tier 8 set (4) set is not working - not one proc remains active after usage. I have tried it in one Ulduar raid and ~40min casting testing done in Ironforge on the training dummy. Additionally, I tried this only for Hot Streak, I do not have Arcane or Frost spec on my mage.

Set chest link: http://wotlk.openwow.com/item=46130
ID of the spell: http://wotlk.openwow.com/spell=64869

**Comment by Vaxsysl** [comment] 2015-07-06 19:40
Any word? It might be the end of T8 era, but we will still use our Ulduar gear for any future achievement runs.

**Comment by Aizenscar** [comment] 2015-07-16 12:28
BumpBumpBump

**Comment by Rushor** [comment] 2016-11-23 09:26
Game/Spells: Implement Mage T8 4P Bonus and Mage T10 2P Bonus

* closes https://github.com/dalaranwow/dalaran-wow/issues/1984
* commit: c9f503e704bc11eff4752458c67639e43b14fd6b

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 09:26 UTC
Labels: Class - Mage, Items, On PTR
