### ISSUE TITLE
Midsummer event

### ISSUE THREAD

**Issue by lowbow** [dalaranwow/dalaran-wow#2549] opened 2015-06-21 09:25 UTC
It seems that daily quests, 
like Torch Tossing, More Torch Tossing, More Torch Catching, does not work. 
Have been trying in Orgrimmar and Undercity - no effect.
Also, in the Slave Pens Normal mode, Numa Cloudsister does not give the quest for summoning and killing Ahune boss.
Players can't benefit from the event by getting that awesome tabards:
Tabard of Summer Flames or Tabard of Summer Skies.
It could have been nice if you fix it (especially the tabard part) till the end of the event.

**Comment by Alver1** [comment] 2015-06-21 11:15
Confirmed, there are plenty of bugs regarding this event. Ahune, the Frost Lord can't be spawned, daily quests don't work, the ribbons which you spin around for bonus xp don't work. The meta achievement is not obtainable at this point.

**Comment by Tarpor** [comment] 2015-06-21 12:14
All of these (except the torch quests) worked last year, so they will likely be fixed in the upcoming days.

**Comment by kreaper187** [comment] 2015-06-21 12:27
is it just me or does bloodmyst isle not have its bonfire? went all that way as horde lol...

**Comment by Lothloryen** [comment] 2015-06-21 13:53
Hello there,

Thank you for your reports, it seems some things got glitched. They were working quite nice the last year's event.

Working on it, will try to deploy them as soon as I can. All the feedback you can provide will be more than welcome and it surely will help me to find what has been glitched.

Thank you very much.

**Comment by Crispybuilt** [comment] 2015-06-21 23:45
Flame Warden of Kalimdor
- Silithus (Alliance) NPC is not spawned I believe

**Comment by Xayos** [comment] 2015-06-23 16:22
Is it normal that no items drop now that hes spawning?

**Comment by Lothloryen** [comment] 2015-06-23 16:35
Hello there,

Yes, it is normal that Lord Ahune or the bag do not drop any gear, since it would break the progression. 

Is the Silithus NPC still not spawned? I checked it on the PTR and every camp was spawned just fine. However, if there is any missing, please let me know and I shall correct it.

Thank you very much.

**Comment by Prljoman** [comment] 2015-06-23 16:56
Have you maybe at least implemented enchanting recipe drop? 
Formula: Enchant Weapon - Deathfrost
http://wowwiki.wikia.com/Formula:_Enchant_Weapon_-_Deathfrost
http://www.wowhead.com/item=35498/formula-enchant-weapon-deathfrost

**Comment by Lothloryen** [comment] 2015-06-23 17:07
Hello,

It is already on the Chest's loot table, it has a 3% chance to drop.

**Comment by Prljoman** [comment] 2015-06-23 17:19
Thank you, btw I think it's written 3% because lot of people reported on wowhead it didn't drop because they are not enchanters so they can't see it, as in for real it's much bigger chance for enchanters. But, at least, this is also soemthing. Thanks! ^^

**Comment by Crispybuilt** [comment] 2015-06-23 18:43
Yeah, NPC in Silithus is not spawned, I am standing right next to camp and there is no NPC to talk to get the credit for the achievement at the moment.

**Comment by Crispybuilt** [comment] 2015-06-23 18:57
**Fixed for Silithus - Checked.**

**Comment by Lothloryen** [comment] 2015-06-23 19:07
Everything should be working now, however if I am wrong, please let me know and I shall correct it as soon as I can.

Enjoy the event and congratulations in advance for those who are about to get the Reins of the Violet Proto-Drake

**Comment by n-ghost** [comment] 2015-06-23 21:25
http://www.wowhead.com/quest=11886

It seems like Unusual Activity is bugged atm, killing the cultists for a few hours now to no avail. Drop rate of the Twilight Correspondence should be close to 100% from any of the cultists in the area, but I'm yet to see it drop either for me or for anyone else.

**Comment by Tarpor** [comment] 2015-06-23 21:52
Unusual Activity is not working.
The bag from Ahune should be giving 5-15 Blossoms, it is empty right now.
This makes for barely any blossoms per day, and me being here for over a year, I can't get enough blossoms at this state to get all the achievements cause I bought the pet last year.

**Comment by Doordie1** [comment] 2015-06-24 12:09
Brazier of dancing flames is slightly bugged. She still reacts your emotes, but whenever she moves, she falls to the ground instead of standing on the brazier. When you emote something else, like you stop dancing and do a /wave, she returns to the top, but falls again. Pics below:
http://i.imgur.com/h4nhdB7.jpg
http://i.imgur.com/UW5jxdf.jpg

**Comment by DP77** [comment] 2015-06-26 14:14
I went to all the flame wardens last year and now they are all bugged for me, anyone else have this problem?   I still need 270 fire blossoms for the meta

**Comment by Tarpor** [comment] 2015-06-26 15:24
I have the same issue as Anomander1 at this moment.

**Comment by Anomander1** [comment] 2015-06-29 02:13
Still not working

**Comment by Tarpor** [comment] 2015-06-30 20:21
There's 4 days of midsummer left and I'd like to get my achievement, any update? I'm missing blossoms cuz of things not working. Don't want to be whiny but I dont wanna wait another year

**Comment by Lothloryen** [comment] 2015-07-02 15:02
Do not worry, those who had not the reset write an in-game ticket and a Game Master shall help you out. Wait patiently, please.

Thank you.

**Closed by Lothloryen** 2015-07-02 15:02 UTC
