### ISSUE TITLE
[NPC] Sunhawk Reclaimer

### ISSUE THREAD

**Issue by Uthil** [dalaranwow/dalaran-wow#2149] opened 2015-01-04 13:32 UTC
Was doing a quest in the area where [Sunhawk Reclaimer](http://wotlk.openwow.com/npc=17606#abilities) and saw that mob isn't using correct its abilities. Normally upon aggro range start to cast fireball and then turn into melee. 

That mob though isn't casting at all, upon aggro ranger charges you directly to melee and doesn't cast  at all. 

WoWHead link : [Sunhawk Reclaimer](http://www.wowhead.com/npc=17606#comments) - and how they describe hes actions.

**Comment by Rushor** [comment] 2016-11-12 12:49
DB/Creature: Update Sunhawk Reclaimer SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/2149
* commit: 701006f53c9d77a85a083d54a5b8bc9b1952913e

"Sunhawk Reclaimer - Out of Combat - Cast 'Frost Armor'"),
"Sunhawk Reclaimer - On Aggro - Cast 'Frost Armor'"),
"Sunhawk Reclaimer - In Combat - Cast 'Fireball'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 12:49 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 18:20
Works as intended on ptr, however i would like to suggest diffrent solution:
``` sql
-- Sunhawk Reclaimer SAI
SET @ENTRY := 17606;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,60,0,100,0,0,10000,10000,10000,11,12544,32,0,0,0,0,1,0,0,0,0,0,0,0,"Sunhawk Reclaimer - On Update - Cast 'Frost Armor'"),
(@ENTRY,0,2,0,0,0,100,0,0,0,4500,5000,11,19816,64,0,0,0,0,2,0,0,0,0,0,0,0,"Sunhawk Reclaimer - In Combat - Cast 'Fireball'"),
(@ENTRY,0,3,0,11,0,100,0,0,0,0,0,11,12544,0,0,0,0,0,1,0,0,0,0,0,0,0,"Sunhawk Reclaimer - On Respawn - Cast 'Frost Armor'");
```
so they don't spam their shield so often.
