### ISSUE TITLE
[Quest][Classic] James Hyal

### ISSUE THREAD

**Issue by Tenrazz** [dalaranwow/dalaran-wow#2168] opened 2015-01-09 07:20 UTC
hello guys pls check this quest...Vincent Hyal gives in Esternkingdoms/Wetlands/Menethil harbor ..Cord 8.3,617 Quest name: James Hyal

thx :)

**Comment by Golganeth** [comment] 2015-01-09 08:21
Just a minor issue. The quest is obtainable but it has a prequest when it shouldn't have one.

- [James Hyal](http://wotlk.openwow.com/quest=1301) Quest ID: 1301
- [James Hyal](http://wotlk.openwow.com/quest=1302) Quest ID: 1302

**How it is now:**** You have to turn in 1301 to pick 1302
**How it should be:** You should be able to pick 1302 right away. If you complete 1302 before 1301, then 1301 should get closed and disappear for the character.

**Comment by Rushor** [comment] 2016-11-26 10:34
DB/Quest: James Hyal - remove prevquest

* closes https://github.com/dalaranwow/dalaran-wow/issues/2168
* commit: 9503474743bf8a21762e4cef8b98f89f522f2914

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 10:34 UTC
Labels: Continent - Classic, On PTR, Quests
