### ISSUE TITLE
[NPC] Susan Tillinghast / Aelthalyste / James Van Brunt

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#897] opened 2013-10-10 22:10 UTC
James Van  Brunt
Lacks Animation (should be doing Blacksmithing stuff)
http://www.wowhead.com/npc=4596

Aelthalyste <Priest Trainer> (her dialogue is in gutterspeak dunno if that should be the case) http://www.wowhead.com/npc=4606#comments

Susan Tillinghast
http://www.wowhead.com/npc=2802
should be wandering around in the route showed in wowhead but she is stationary.

**Comment by Rushor** [comment] 2016-11-14 21:27
2. and 3. issue was already fixed, going to add the emote for James Van Brunt

**Comment by Rushor** [comment] 2016-11-14 21:27
DB/Creature: James Van Brunt - Add emotestate

* closes https://github.com/dalaranwow/dalaran-wow/issues/897
* commit: 65dc3fff668d62adc9aa82ec2c2d6691172810b0

![GitHub Logo](http://i.imgur.com/LD2xYn8.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 21:27 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-04 16:22
Works as intended on ptr.
