### ISSUE TITLE
[Quest] text: Hunting in Stranglethorn

### ISSUE THREAD

**Issue by Zindai** [dalaranwow/dalaran-wow#1930] opened 2014-10-02 14:50 UTC
Quest: <b>Hunting in Stranglethorn</b> - <a href="http://www.wowhead.com/quest=5763/hunting-in-stranglethorn">Wowhead</a> / <a href="http://www.wowwiki.com/Quest:Hunting_in_Stranglethorn">WoWWiki</a>
Quest giver: <b>Roon Wildmane</b> - <a href="http://www.wowhead.com/npc=11877">Wowhead</a> / <a href="http://www.wowwiki.com/Roon_Wildmane">WoWWiki</a>
Quest completer: <b>Hemet Nesingwary Jr.</b> - <a href="http://www.wowhead.com/npc=715">Wowhead</a> / <a href="http://www.wowwiki.com/Hemet_Nesingwary_Jr.">WoWWiki</a>

The quest was changed when Hemet Nesingwary Jr. took his father's place in Stranglethorn Vale in The Burning Crusade, but the server Algalon does not reflect this change.

<b>The completion text currently says</b>:
<code>Ah, this horn belongs to a Tauren, Roon Wildmane. He and I had a good time hunting the beasts of Desolace. So Roon is inviting me back, is he?</code>

<code>We're neck deep in the jungle right now, but thank you, < name >. Perhaps my next expedition will take me back to Desolace, the land of the centaurs.</code>

<b>It should say</b> (exactly as written on Wowhead):
<code>Ah, this horn belongs to a Tauren, Roon Wildmane. My father spoke often of the good times they had together hunting the beasts of Desolace. So Roon is inviting me to join him, is he?</code>

<code>We're neck deep in the jungle right now, but thank you, < name >. Perhaps my next expedition will take me to Desolace, the land of the centaurs.</code>

**Comment by Rushor** [comment] 2016-11-23 12:45
DB/Quest: Hunting in Stranglethorn - Update offer reward text

* closes https://github.com/dalaranwow/dalaran-wow/issues/1930
* commit: 4f2e2cf4cbb06272fde10bf11a31c416b5352c7c
* remember to delete the cache folder before testing

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-23 12:45 UTC
Labels: Continent - Classic, On PTR, Quests
