### ISSUE TITLE
[Paladin] Multiple Beacon of Light not transfering Healing

### ISSUE THREAD

**Issue by fsironman** [dalaranwow/dalaran-wow#4743] opened 2017-06-09 08:58 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Holy Paladins Signature Talent Beacon of Light breaks when there is more then one Beacon active in the Raid

After checking all the Logs it worked flawlesly on the 3 ICC 25 normal we did on 28.05. 29.05. and 30.05.
The issue occured to us first on 04.06.

**Expected behaviour**: 
Beacon of Light should always transfer healing.

**Steps to reproduce the problem**:

1. Raid in ICC 25 HC 
2. Have two Holy Paladins use Beacon of Light on other raidmembers
3. Healing is not transfering to the beacon target seemingly at random

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Beacon_of_Light

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/spell=53652/beacon-of-light

**Include Screenshots from the issue if necessary**

The next two Screenshots show Bloodqueen Lanathel HC fight and the Healing Done by both Holy Paladins.
As you can see Beacon of Light Uptime was almost 100% and the Holy Paladins are competent enough to not Heal the Beacon Target. You Except the count of Beacon of Light Healing done closely matching the sum of the Holy Paladins other Healing Spells.

![](http://i.imgur.com/5nB0gTr.png)
If you look at Pion its 197 healing spells casts but only 106 times Beacon healing done.

![](http://i.imgur.com/JbIYXTZ.png)
From Ryley is 199 healing spells but only 92 times Beacon is healing.

Needless to say this is a **MAJOR** problem if only half the Beacon of Light Heals are working. Resulting in effektive 25% less healing for both Paladin and beeing a major risk of tank death.

![](http://i.imgur.com/mevqVls.png)
After switching to only one Paladin Beacon of Light healing done look exactly as expected with 191 Healing Spells cast and 191 time healing done by Beacon of Light.

This is the Timeline of the Encounter with each green dot representing Healing done by Beacon of Light:
![](http://i.imgur.com/w0gshuZ.png)
You would expect them to be occuring in regular intervall every 1,3 sec Instead Beacon seems to work sometime and sometime not.

This is an ingame Screenshot showing the the positioning of the raid to rule out range issue:
![](http://i.imgur.com/46O5R4k.jpg)

I marked the important Parts with arrows.

- Both Beacons are up.
- I cast a heal on Thedream and beacon is transfering healing
- The next cast is done on Runeblade but this time no healing transfer with the beacon.

**Comment by Rushor** [comment] 2017-07-03 13:29
i have a fix for that - going to push it on ptr this evening

**Comment by Rushor** [comment] 2017-07-03 19:18
Game/Unit: Multiple Beacon of Lights now transfer Heal + Disable aggrovalue while casting Beacon of Light & Priest - Rapture - energy trigger spell

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4743
* commit: a930b4a1c9944124ba5a4196288cb8159506ffcc

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by JohnADC** [comment] 2017-11-09 13:42
Can we get an update on this? It's making second holy paladin useless in any raid.

**Comment by TeridanDW** [comment] 2017-11-09 20:09
Works as intended on PTR.

**Comment by StheNoble** [comment] 2017-11-10 01:27
Our pala healer told me that as of today this is not limited to valithria but instead issues with beacons are present in any encounter where multiple hpalas are present (as described in inital report) @TeridanDW

**Comment by Lothloryen** [comment] 2017-11-10 01:30
No no, what Teridan means is that the new implementation fixes this issue (but generates a new one on Valithria). Hence, this will not go to live until a different approach to solve the issue is found.

**Comment by ashido96** [comment] 2017-11-14 04:34
Our holy paladin's input is that he doesn't care at all if he can't beacon heal on valithria if two beacons can work in the raid at all  (which is the issue, we can't use 2 holy paladins on LK 25hc for example even if we wanted to). Temporarily fixing a major bug with the introduction of minor bug is fine until a complete fix can be found (if indeed the only issue is with Valithria)

**Comment by JohnADC** [comment] 2017-11-14 11:03
What ashido96 said, we could really use a second holy paladin for our lk25hc progress at the moment

**Comment by JohnADC** [comment] 2017-12-06 10:27
It has been a month from failed try to fix it. At the moment it is the biggest class bug on the server. Please try and push this as soon as possible. Thank you!

**Comment by robinsch** [comment] 2017-12-13 11:39
Can please someone explain how this can be reproduced in a test enviroment? Do I need to login with 5 accounts, be within a raid with everyone, casting two beacons healing the fifth target and no one gets healed by beacon?

**Comment by TeridanDW** [comment] 2017-12-13 13:02
Sure @robinsch,
Get 4 characters (2 holy paladins and 2 random ones) in a raid group. With the fix that is on PTR their beacons work properly with the exeption of Valithria fight, there when they enter the "dream state" and leave it after their beacon stops transfering heals.

**Comment by Lothloryen** [comment] 2017-12-13 22:23
Hello there,

Okay, did a fix that will work for both cases. It will be applied to the live realm within the next realm maintenance.

Thank you for the reports and collaboration.

**Closed by Lothloryen** 2017-12-13 22:23 UTC
Labels: Class - Paladin, Not working/incomplete fix
