### ISSUE TITLE
[Spells/Auras] Scholomance visual bug

### ISSUE THREAD

**Issue by Todoran** [dalaranwow/dalaran-wow#1971] opened 2014-10-15 06:41 UTC
My caracter looks like a pile of bones runing around,my pet is a devilsaur and it looks like some bones and meat on the ground to, even if i mount i still look like some bones,  all players can see as i am, its not only me, please help me.

Pic1: http://postimg.org/image/opnu526kv/
Pic2: http://postimg.org/image/x97i6arfl/

EDIT: for some reason the bug is gone  :dancer:

**Comment by luc666** [comment] 2015-06-20 16:07
still bugged. im pile of bones after scholo. Char name - Slightdemon. Please .unaura, cuz cant play like that...

**Comment by Vathdar** [comment] 2015-06-20 21:36
Same as luc666 on my character Vathdara.

**Comment by belegija** [comment] 2015-08-18 03:08
This bug happened to me today, character name Razbijach, please help, I am unable to play

**Comment by belegija** [comment] 2015-08-19 14:32
May I politely ask/suggest for some kind of hotfix, to disable that ability? I keep seeing more and more people running around in Stormwind with that bug, and it is truly game breaking. Tickets apparently take few days to be answered (mine is 2 days old and waiting).

**Comment by AnaxusRath** [comment] 2015-08-19 14:35
Same here, character name Fazy on Dalaran, it's quite frustrating. 
I can confirm that it is caused by Scholomance Necromaners.

**Comment by Rkololz** [comment] 2015-08-24 20:54
I have the same problem with this bug i even made a ticket sience 8 days more than a week come on man i'm not lvl 50 or 60 i'm 80 i have 4.2 k gs i can't reroll my class do something

**Comment by PapaBeard** [comment] 2015-12-07 22:29
Hi all,
Same problem as well. I opened a ticket about a month ago and I am still bugged.
Is it complicated to solve this bug?
It is very upseting not to be able to play my toon because of that.
If a GM gives a look to this thread, could they drop me a quick in-game mail so that I can know where they are at?
Have fun guys!

**Comment by PapaBeard** [comment] 2015-12-09 23:28
My toon's name is Oktav and I usually play between 21.00 and 23.00 UTC.

**Comment by Rushor** [comment] 2016-11-11 13:08
DB/Creature: Scholomance Necromancer - Remove ability 'Corpse Explosion'

* that spell: 'Corpse Explosion' http://wotlk.openwow.com/spell=17616 caused the player to morph into some strange pile of ****.
* commit: dbb4f0540271a79c163bf28e80f320d0e7116722

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-02 19:36
Found out why this is happening, the target of spell http://wotlk.openwow.com/spell=17616 is choosen like this:
``` sql
(@ENTRY,0,0,0,5,0,100,3,0,0,0,0,11,17616,0,0,0,0,0,7,0,0,0,0,0,0,0,"Scholomance Necromancer - On Killed Unit - Cast 'Corpse Explosion' (No Repeat) (Normal Dungeon)"),
```
`On Killed` means when creature kills something, however in this case the creature can kill a player and if the player doesn't release immediately, he becomes a valid target of that spell.
And the spell itself has:
`Effect #2	Apply Aura: Transform (28590)` http://wotlk.openwow.com/npc=28590

Also spell http://wotlk.openwow.com/spell=14887 should have flag 64

**Comment by TeridanDW** [comment] 2017-05-09 11:55
Hello, after further investigation of this issue I found an additional problem:
 - spell [17616](http://www.wowhead.com/spell=17616/corpse-explosion) has targeting problem - it will always target the caster(self) regardless of what target is set in the SAI of the creature.

**ID - 17616 Corpse Explosion
AttributesEx1: 0x00000088 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_CANT_BE_REFLECTED)
AttributesEx2: 0x00000001 (SPELL_ATTR2_CAN_TARGET_DEAD)**


This issue needs to be resolved in the core, when this is done all other problems can be fixed with SAIs.

For testing purposes I have set the Scholomance Necromancer to cast the explosion on it's victim (player/me) however this is what happens:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6797611/25849353/d14502da-34c6-11e7-95f6-6888d5c49cb3.gif)

Trigger for the cast is the death of the Scholomance Adept and these are the 2 SAIs, so you can test it yourself.

Note: Fixed some mistakes and improved the overall combat behaviour of the 2 creatures.

``` sql
-- Scholomance Necromancer SAI
SET @ENTRY := 10477;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,2,0,0,500,500,11,14887,64,0,0,0,0,2,0,0,0,0,0,0,0,"Scholomance Necromancer - In Combat - Cast 'Shadow Bolt Volley' (Normal Dungeon)"),
(@ENTRY,0,1,0,2,0,100,2,0,30,28000,28000,11,12020,33,0,0,0,0,2,0,0,0,0,0,0,0,"Scholomance Necromancer - Between 0-30% Health - Cast 'Call of the Grave' (Normal Dungeon)"),
(@ENTRY,0,2,0,2,0,100,3,0,15,0,0,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Scholomance Necromancer - Between 0-15% Health - Flee For Assist (No Repeat) (Normal Dungeon)"),
(@ENTRY,0,3,0,38,0,100,2,1,0,0,0,11,17616,1,0,0,0,0,2,0,0,0,0,0,0,0,"Scholomance Necromancer - On Data Set 1 0 - Cast 'Corpse Explosion' (Normal Dungeon)");

-- Scholomance Adept SAI
SET @ENTRY := 10469;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,2,0,0,500,500,11,15043,64,0,0,0,0,2,0,0,0,0,0,0,0,"Scholomance Adept - In Combat - Cast 'Frostbolt' (Normal Dungeon)"),
(@ENTRY,0,1,0,9,0,100,2,0,8,9400,14300,11,15244,1,0,0,0,0,2,0,0,0,0,0,0,0,"Scholomance Adept - Within 0-8 Range - Cast 'Cone of Cold' (Normal Dungeon)"),
(@ENTRY,0,2,0,9,0,100,2,0,18,12200,24700,11,15499,1,0,0,0,0,2,0,0,0,0,0,0,0,"Scholomance Adept - Within 0-18 Range - Cast 'Frost Shock' (Normal Dungeon)"),
(@ENTRY,0,3,0,2,0,100,3,0,15,0,0,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Scholomance Adept - Between 0-15% Health - Flee For Assist (No Repeat) (Normal Dungeon)"),
(@ENTRY,0,4,0,6,0,100,2,0,0,0,0,45,1,0,0,0,0,0,10,91331,10477,0,0,0,0,0,"Scholomance Adept - On Just Died - Set Data 1 0 (Normal Dungeon)");

```

**Closed** 2017-11-30 14:41 UTC
Labels: Area - Instances, Fixed - Waiting for PTR update, Works - but it needs improvements.

**Comment by Golaman2** [comment] 2018-06-28 14:16
I am a pill of bones, too. How can I undo it..? I opened ticket but no one answers. I cannot play!

**Comment by Rkololz** [comment] 2018-06-28 15:07
You have to wait until the gm fixes you so it may be a while

On Jun 28, 2018 4:16 PM, "Golaman2" <notifications@github.com> wrote:

I am a pill of bones, too. How can I undo it..? I opened ticket but no one
answers. I cannot play!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dalaranwow/dalaran-wow/issues/1971#issuecomment-401050417>,
or mute the thread
