### ISSUE TITLE
[Quest][Northrend] Fuel for the Fire

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#532] opened 2013-08-11 10:52 UTC
http://www.wowhead.com/quest=12690/fuel-for-the-fire

Bloated Abominations missing Burst at the Seams
"Causes the abomination to explode, killing any nearby Drakkari Skullcrushers."
http://www.wowhead.com/spell=52811

**Comment by Cone182** [comment] 2015-01-14 18:46
Confirmed, still cant pull the abos to the mountain top.

**Comment by Kumanix** [comment] 2015-02-09 14:58
Confirmed.
When entering combat, the abomination breaks free from your control making it unable to use it to kill the trolls. Killing the Drakkari Skullcrusher by my own hand won't count for the quest either.

**Comment by Vandreth** [comment] 2015-06-21 16:11
Cannot complete the quest chain with these bugs.

**Comment by Kaporalhart** [comment] 2015-08-02 14:02
I found a fix ! Set your abomination's aggro to Passive, he won't leave as soon as you enter combat.

**Comment by Cone182** [comment] 2016-01-16 21:52
can be completed, capture an abomination, put him on passive, make him follow you, and use only him to attack the trolls.

**Comment by budthechud** [comment] 2016-06-07 05:51
Currently I am setting the Abom to passive and walking into groups and setting him to explode.  The issue remains though that if you capture an Abom and walk it to the back-most grouping straight from the entrance there is a mind control break.  It seems to be a leash issue with it's origination and where it is being lead to.
I tried this in several degrees:
1. RP Walking into the Drakkari
2. Backward walking
3. Aggressive/passive/Defensive

What it cam down to was getting a questing partner, going bear form, gathering the mobs on top of the abom and having it explode.  Needless to say it shouldn't work that way I'm sure.

**Comment by kjraider** [comment] 2016-06-18 12:53
Still the same leashing issues here, came here to make sure something was still open regarding this quest.

**Comment by jonanone** [comment] 2016-07-12 11:54
Spawn times for trolls and abominations have been reduced to 2 mins.
Also some text and role play has been added. Once the Chieftain is summoned, it will run towards the player. Then Shalewing will appear and despawn it.

These updates will be applied to the live realm soon.

**Comment by MrAndersonX** [comment] 2016-11-01 12:55
Bugged as hell. Needs a fix badly. Has been broken since acient times...

**Comment by Rushor** [comment] 2016-11-24 12:30
_Required Improvements:_
- The amount of trolls has to be increased (just a little bit), whilst their spawn time should be reduced from 6 minutes to 25-30 seconds.
- Aggro range before trolls evade and reset needs to be increased.
- The spawn time of all the abominations should be reduced from 6 minutes to roughly 1 minute.
- If the player gets in combat before the abomination does, no resets should happen. That has to happen only if the ghoul disguise gets removed by any mean.
- In regards of the event with Drakkari Chieftains, it's mostly missing. Everytime you have killed 20 trolls, a Drakkari Chieftain has to appear and run towards you (quote) and short after he gets carried off by Shalewing (quote).

---

---

_Drakkari Chieftain quotes:_

**On spawning:**
< I come to avenge my bruddas, mon! >
< We gunna drive all da Scourge outta Zul'Drak, mon - startin' with you! >
< Die, nasty scourge! >

**When carried off:**
< Owww! >
< Wha?!... >
< Ooof! >

---
- http://wotlk.openwow.com/quest=12690
- **Floated Abomination** - _ID: 28843_ ~> http://wotlk.openwow.com/npc=28843
- **Drakkari Skullcrusher** - _ID: 28844_ ~> http://wotlk.openwow.com/npc=28844
- **Drakkari Chieftain** - _ID: 28873_ ~> http://wotlk.openwow.com/npc=28873

**Comment by Rushor** [comment] 2016-11-24 13:23
Scripts/Quest: Update Fuel for the Fire

* The troll spawn time was reduced from 6 minutes to 25-30 seconds.
* Aggro range before trolls evade and reset was increased by 90 yards.
* The spawn time of all the abominations was reduced from 6 minutes to roughly 1 minute.
* closes https://github.com/dalaranwow/dalaran-wow/issues/532

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 13:23 UTC
Labels: Continent - Northrend, On PTR, Quests
