### ISSUE TITLE
[Quest] "More Warbeads!" give less reputation than intended.

### ISSUE THREAD

**Issue by isama92** [dalaranwow/dalaran-wow#3837] opened 2016-11-13 20:20 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
The quest "More Warbeads!" that should give you 500 reputation with Mag'har gives only 250.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Loot 10 Obsidian Warbeads
2. Go to the NPC Warden Bullrok
3.  Complete the quest.
4. You get 250 reputation with Mag'Har.

**Include proofs for this behaviour**
Just test it, i dont wanna waste 10 more
This is the quest: http://www.wowhead.com/quest=10478/more-warbeads
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-13 20:28
DB/Quest: The Mag'har - double repeatable quest reputation

* closes https://github.com/dalaranwow/dalaran-wow/issues/3837
* commit: 19f993f159434b95c0a82c6cebaa819c273fb752

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 20:28 UTC
Labels: Continent - Outland, Quests

**Comment by TeridanDW** [comment] 2017-03-30 17:47
Works as intended on ptr.

**Comment by ArchmageVargoth** [comment] 2018-01-03 04:45
Currently on Algalon, the Alliance More Warbeads Quest still only gives 250 reputation. Is this still expected to roll out on Live Realm?
