### ISSUE TITLE
[NPC] Franclorn Forgewright

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#1202] opened 2014-02-15 07:44 UTC
**NPC ID**: 8888
Location: Blackrock Mountain
Link: http://www.wowhead.com/npc=8888/franclorn-forgewright

**Issue Present**: This NPC should only be visible to dead players (--> Player has to be in ghost form), yet at the moment, he is visible and interactable for living players, but not for players in ghost form.

Sidenote: Living players can accept and complete his quests, so this is only a minor issue.

**Comment by Demlock** [comment] 2015-04-04 10:16
Confirmed.

**Comment by M0dinstaller** [comment] 2016-02-07 03:09
Still bugged.

**Comment by Rushor** [comment] 2016-11-12 13:04
DB/Creature: Franclorn Forgewright - should only be visible for dead player

* closes https://github.com/dalaranwow/dalaran-wow/issues/1202

![GitHub Logo](http://i.imgur.com/vUCJHEf.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 13:04 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 19:31
Works as intended on ptr.
