### ISSUE TITLE
Quest: See You on the Other Side 12121

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#643] opened 2013-08-18 17:10 UTC
www.wowhead.com/quest=12121
No credit given after being "killed" by Warlord Jin'arrak

**Comment by Daveonx** [comment] 2016-06-08 17:11
The initial part of the quest is working fine now, it is the later part that isn't. For some reason the aura [On the Other Side](http://www.wowhead.com/spell=61611/on-the-other-side) is removed once players enter the Drakil'Jin Ruins. Since it is removed players are unable to hand in the quest, halting progress in the chain.

**Comment by Rushor** [comment] 2016-11-24 14:21
DB/Creature: Warlord Jin'arrak - no longer attackable

* closes https://github.com/dalaranwow/dalaran-wow/issues/643
* commit: bb43ed92d594afbdf3caf1084d3b00a800563ec0

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 14:21 UTC
Labels: Continent - Northrend, On PTR, Quests
