### ISSUE TITLE
[Northrend] [Quests] Battle at Valhallas

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3888] opened 2016-11-27 13:26 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
 After taking the quest I tried handing it in to Geirrvif to complete it. However, she's flying in the air and Prince Sandoval is spawned in the center of the arena ring. And no question mark appears allowing the player to turn the quest in to Geirrvif.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 The NPC is flying in the air and it doesn't allow for a player to turn the quest in to continue the chain thus making it impossible to complete it.

**Expected behaviour**: Tell us what should happen instead
 She should be on the ground offering the players the chance to turn in the quest and take the next quest in the chain line.

**Steps to reproduce the problem**:

1.  Take the quest Battle at Valhallas.
2.  Try to talk to the NPC to complete the quest.
3. 

**Include proofs for this behaviour**

 https://postimg.org/image/m5f3athmn/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-27 13:45
she flies up in the air, once someone started the arenaquest. i think she must be set to active all the time.

DB/Creature: Geirrvif - must be active

* closes https://github.com/dalaranwow/dalaran-wow/issues/3888
* commit: a393d4ba716fd8f58c91bd70363cdc9574e7041e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 13:45 UTC
Labels: Continent - Northrend, On PTR, Quests
