### ISSUE TITLE
[Quest][Icecrown] Quest: Jagged Shards

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1070] opened 2013-12-26 04:47 UTC
Quest link: http://www.wowhead.com/quest=13136

Quest giver link: http://www.wowhead.com/item=43259

What's wrong: When right clicking on the quest item to accept the quest, the following message appears "You don't meet the requirements for that quest"

How it should work: This quest has no requirement other than being level 77, as long as you get the item you should be able to accept the quest. I'm level 80 and still can't accept it

**Comment by Snusnufs** [comment] 2015-07-13 00:35
This quest is still bugged.

**Comment by Cone182** [comment] 2016-01-26 19:40
The quest item is not dropping for me.

**Comment by Mattgoheels** [comment] 2016-02-05 23:56
I had this problem, couldn't get the quest from the item.  I went to orgrimmar and tried again and was able to get the quest - so try using it in a different area.

**Comment by DrFuler** [comment] 2016-04-08 02:05
[07/04/2016] - Still bugged.

"You don't meet the requirements for that quest."

**Comment by Lothloryen** [comment] 2016-05-03 19:18
Currently, there is a condition on the database - in order to be able to accept this quest, you must first complete http://www.wowhead.com/quest=13134/spill-their-blood

**Comment by Klala** [comment] 2016-07-19 18:27
There is something very wrong here. I had 2 characters that got the quest item while doing Spill Their Blood, but 1 character who couldn't loot it. (When it dropped I could see it with only 2 characters while the third didn't have anything to loot), so I ignored it and thought that it will drop next time, but it didn't, then I completed Spill Their Blood quest and now the quest item doesn't drop at all.
And no, I don't have the quest item in my inventory.
So what are the conditions? You said that you must comeplete Spill Their Blood quest in order to accept Jagged Shards but if the quest item doesn't drop AFTER you completed already completed it, then what?

**Comment by Rushor** [comment] 2016-11-24 21:16
i think the prequestcondition Spill Their Blood is simply wrong. on wowhead i could not found such information

**Comment by Rushor** [comment] 2016-11-24 21:21
DB/Quest: Jagged Shards - Remove wrong prevquest

* closes https://github.com/dalaranwow/dalaran-wow/issues/1070
* you NO longer need quest 13134 completed to accept 13136
* commit: a83b608b795544d50efcf8bc21e69405f7ef1f04

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 21:21 UTC
Labels: Continent - Northrend, On PTR, Quests
