### ISSUE TITLE
[Effect][Interrupt]There is a slight delay on interrupting spells

### ISSUE THREAD

**Issue by chereyo** [dalaranwow/dalaran-wow#1610] opened 2014-05-16 22:21 UTC
There is a miniscule delay between interrupting effects and spellcasts. A lot of times I have already stopped casting, but a kick or counterspell will often lock me in school. It's a hard thing to test, but it's something you can "feel" when you play a lot of arena between servers. Other players say they still see me casting when they get me interrupted, but on my screen I have clearly stopped casting. Perhaps a look at the correlating scripts could reveal something. 

Edit\* my ms is ~30 all the time.

**Comment by Rushor** [comment] 2016-12-14 19:54
Most likely caused by lags or an implementation of the spell delay system. /closing

**Closed by Rushor** 2016-12-14 19:54 UTC
