### ISSUE TITLE
[Warlock][Talent] Decimation

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3249] opened 2016-04-27 14:59 UTC
**Issue present:**
_http://wotlk.openwow.com/spell=63158_

Decimation equation for Dalaran WoW is currently wrong.
It looks something like this: 

```
                cast time = 6 * 0.6 - 2 = 1.6  
```

While it should be like this (retail version)

```
                cast time = (6 - 2) * 0.6 = 2.4
```

---

**Related issues**: #3248 #3100 #2379

---

**Comparison to Sunwell Core**: 
Decimation works exactly as it should there.
You get 2.4 cast while being naked on level 80.

**Comment by Lukas45** [comment] 2016-04-28 09:20
It's a general issue of which order the calculations are made.
Soul Fire is casting faster than it should (which is news to nobody) because of Decimation.
It should be like what you said it is like, while it is like what you described it should be like.
Current:
(CastTime*0.6)-2 = 1.6s
Should be:
(CastTime-2)*0.6 = 2.4s

It's the same issue with Resto Shamans with Healing Wave (Imp. Healing Wave) + Tidal Waves, and probably Disc Priests too with Greater Heal (Divine Fury) + Borrowed Time.

But as you mentioned already with related issues, this is a dublicate

**Comment by Marquito01** [comment] 2016-04-28 22:33
Reported this long time ago during ud season, but it seems class bugs are at the bottom of the priority list here. 40% free haste on one of the highest dmg spells is prob not worth fixing...

**Comment by Rushor** [comment] 2016-11-29 20:31
Game/Mechanic: Spellmods

*Fix spellmod calculations, Flat modifiers should be added before multipliers
*Fixes Decimation & Bane stacking behavior
* closes https://github.com/dalaranwow/dalaran-wow/issues/3249
* commit: 46df6bb6b6abd0b23671d7920465423d34efc011

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 20:31 UTC
Labels: Class - Warlock, Fixed - Waiting for PTR Update

**Comment by tripleslash** [comment] 2017-10-17 12:55
Is this on PTR right now?

**Comment by TeridanDW** [comment] 2017-10-20 09:27
Merging with #2657 as the same commit was used by @Rushor for both reports.

**Comment by TeridanDW** [comment] 2017-10-20 09:43
After a lot of tests on PTR:

This:

> *Fix spellmod calculations, Flat modifiers should be added before multipliers

is works as intended.

Also this commit fixes far more talent/spell combinations than just:

> *Fixes Decimation & Bane stacking behavior
