### ISSUE TITLE
Quest / NPC: Scalps! [12659] ~~ Heb'Drakkar Striker [28465]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1454] opened 2014-04-07 08:32 UTC
**(Minor problem)**

**Issue:** _"Scalps!"_ can NOT be completed using **Heb'Drakkar Strikers** (the ones riding a bat).
However, the quest can be completed using Heb'Drakkar Headhunters.
- http://wotlk.openwow.com/quest=12659
- **Heb'Drakkar Striker** - http://wotlk.openwow.com/npc=28465
- **Provided item - Ahunae's Knife** - http://wotlk.openwow.com/item=38731

**Comment by Golganeth** [comment] 2016-06-23 12:10
MalkaviaDW:

> Works, but you can scalp multiple times the same NPC, so just killing one of them and spam the object will give you credit for the 10 needed.

**Comment by jonanone** [comment] 2016-08-02 19:21
I tried it today and I haven't been able to scalp multiple times the same mob. These should be tested again just in case.

**Comment by Rushor** [comment] 2016-11-14 18:33
DB/Creature: Heb'Drakkar Striker - Despawn after spellhit of'Ahunae's Knife'

* closes https://github.com/dalaranwow/dalaran-wow/issues/1454
* added a save call to always despawn the creature after the knife was used
* commit: e96e46fc6d242b519c65ae822a538c0747337aac

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 18:33 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by Zibathy** [comment] 2017-03-22 20:54
This is not working on Kirin Tor. I cannot scalp the Heb'Drakkar Strikers. I have screenshots if needed.

**Comment by Rushor** [comment] 2017-03-22 21:36
**The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.**

@Zibathy pls don't push this. The fixes will be applied in the future on the realm. They are not pushed on live yet.

**Comment by TeridanDW** [comment] 2017-04-04 09:27
Works as intended on ptr.
