### ISSUE TITLE
[NPC] Scarlet Preserver.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1015] opened 2013-12-11 07:11 UTC
http://www.wowhead.com/npc=4280

Mob should have 2 abilities: Holy Strike (http://www.wowhead.com/spell=13953), which does additional Holy damage on melee attack, and Holy Light (http://www.wowhead.com/spell=13952) which he should use when on low health or on injured comrades.

Currently mob just melees.

**Comment by Rushor** [comment] 2016-11-12 18:28
DB/Creature: Add SAI for several creatures in tirisfal

* commit: a9203cd600f52899b79067da96f7c678aab12c4d

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 12:25
Spells are been casted now, however there is 1 issue:
 - On aggro creature doesn't say anything at all

Note: Action `"Scarlet Preserver - Between 0-55% Health - Cast 'Holy Light' (No Repeat)"),` is marked as no repeat but in-game it is repeatable (i think its better to leave it like that, repeatable).

**Comment by Rushor** [comment] 2018-05-10 14:34
changed the SAI to this:

* Scarlet Preserver - In Combat - Cast 'Holy Strike'
* Scarlet Preserver - Friendly At 500 Health - Cast 'Holy Light'
* Scarlet Preserver - Between 0-15% Health - Flee For Assist (No Repeat)"
* Scarlet Preserver - On Aggro - Say Line 0

**Closed** 2018-05-10 14:36 UTC
Labels: Area - Instances, Fixed - Waiting for PTR update
