### ISSUE TITLE
NPC: Bloodscalp Warrior

### ISSUE THREAD

**Issue by Comgu** [dalaranwow/dalaran-wow#1115] opened 2014-01-18 05:22 UTC
**Link:** http://wotlk.openwow.com/npc=587
**Location:** Stranglethorn Vale

**Issue present:** Bloodscalp Warrior's spell Shield Bash is not working properly.

**How does it currently work:** Shield Bash does not have a cooldown. Therefore the NPC uses Shield Bash on every non-instant cast spell that the player tries to cast if the NPC is in range. Casting non-instant cast spells is impossible.

**How it should be:** Shield Bash should have a cooldown.

**Spell link:** http://wotlk.openwow.com/spell=11972

**Extra Info:** Any other mobs which use this spell *might* have the same issue.

**Comment by Golganeth** [comment] 2015-01-10 12:55
This problem was fixed with #438 since it's the same spell. It works as intended now

**Closed by Golganeth** 2015-01-10 12:55 UTC
Labels: Classic, NPC
