### ISSUE TITLE
[Item] 3 engineering items, that do not work

### ISSUE THREAD

**Issue by urecheandu** [dalaranwow/dalaran-wow#4750] opened 2017-06-12 17:07 UTC
Several engineering items do not work as they should.
The items I have tested and found broken are: Explosive decoy, Goblin land mine, Gnomish Alarm-o-Bot,
Gnomish flame turret, Explosive sheep, target dummy(and probably the others as well, though I did not test them)

**Current behaviour**:

Gnomish alarm-o bot: doesn't do anything. According to my friend with who I have tested it, it can't even be killed, though i have seen a friendly stormwind guard kill it.

Gnomish flame turret: it's a guardian, it moves and attacks enemies.

Explosive decoy: it did not explode when killed by a mob, and according to the friend I tested it with, it could not be attacked.

**Expected behavior**: 

- [ ] Gnomish alarm-o bot: it should be placed on the ground, follow the player around and reveal invisible enemy units, every 5 or so seconds.
- [ ] 
- [x] Gnomish flame turret: it should be constructed at the player's feet, and attack enemy targets by dealing damage in a cone in front of it.
- [ ] 
- [x] Explosive decoy: it should be placed on the ground and explode when killed

**Steps to reproduce the problem**:

1.  Create the items
2.  Find a mob
3.  Use the item

**Include proofs for this behavior**

https://www.facebook.com/permalink.php?story_fbid=101496810462786&id=100018074014042&pnref=story

(6 videos I posted on a newly made facebook account)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/item=18645/gnomish-alarm-o-bot#created-by-spell
http://www.wowhead.com/item=23841/gnomish-flame-turret#created-by-spell
http://www.wowhead.com/item=40536/explosive-decoy

(I am aware that wowhead is updated to legion, however I could not use openwow for whatever reason, so I decided to stick to wowhead, the comments are from around 2009, so they should be of some use)

**Include Screenshots from the issue if necessary**

**Comment by Edzero** [comment] 2017-06-15 23:37
Some but not all of these are handled in #1294

**Comment by urecheandu** [comment] 2017-06-16 18:55
well, according to my tests, the land mine doesn't work. keep in mind the testing was done a day before I posted this.

**Comment by urecheandu** [comment] 2017-06-16 19:00
I realized my proof was not public. All should work fine now.

**Comment by Rushor** [comment] 2017-06-30 10:04
i'm going to modify and delete the items that are already fixed in https://github.com/dalaranwow/dalaran-wow/issues/1294

**Comment by Rushor** [comment] 2017-06-30 10:16
DB/Item: Explosive Decoy/Brown Rabbit - Add Cast 'Decoy Explosive' + Add passive reactstate + Add ignore armor for spell  'Decoy Explosive' 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4750
* commit: d9d2992fe8b39b69fcaf087d9e30f422da68b817

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment] 2017-07-02 09:42
good alternative for id linking now is https://wowgaming.altervista.org/aowow/ (keep that in mind) thank you.

**Comment by Rushor** [comment] 2017-07-02 09:48
Scripts/Item: Implement Gnomish Flame Turret (23841)

* Gnomish flame turret: it should be constructed at the player's feet, and attack enemy targets by dealing damage in a cone in front of it by using spell https://wowgaming.altervista.org/aowow/?spell=30527
* updates: https://github.com/dalaranwow/dalaran-wow/issues/4750
* commit: 076a5bc5fc4a4b1090c79a8ea014f737d7e56d39

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment] 2017-07-02 10:20
the alarm-o-bot should not follow the player but instead simply roam around. Proof:

> By Lockz (186 – 1) on 2009/09/09 (Patch 3.2.0)
> As of 3.2:
> 
>     - Does not follow you around. It roams in a small area at where it was dropped.
>     - Cannot be looted for material, it just disappear at the end.
>     - Only last 2 min.

**Comment by Rushor** [comment] 2017-07-02 10:25
DB/Item: Alarm-o-Bot - Now removes stealth periodically with aura 'Gnomish Alarm-o-Bot'(23003) and moved 10 yards random around after spawn

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4750
* commit: 1928c0574be67c324d2f3eae04e70953fbf94158

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-07-02 10:25 UTC
Labels: Fixed - Waiting for PTR Update, General - Items

**Comment by urecheandu** [comment] 2017-07-03 09:41
Thank you for dealing with this, however, there is an issue (https://github.com/dalaranwow/dalaran-wow/issues/1294), closed, waiting for the ptr update since 2014, containing the items that have been removed. While that is more than understandable, since the issue has been added in 2014, and the ptr update hasn't come for the items that I have tested, may I be so bold as to ask if there is any estimated time at which there will pe a ptr update that will fix the listed items?

**Comment by Rushor** [comment] 2017-07-03 10:02
@urecheandu the ptr updates will follow in the future. loth reorganised the workflow and a new repository was created.
Once i got access to that new repository i will merge the fixes from the "old" ptr. (https://github.com/dalaranwow/dalaran-wow/issues?q=is%3Aissue+label%3A%22Fixed+-+Waiting+for+PTR+Update%22+is%3Aclosed+milestone%3A%22Pending+Update%22) So i think it will take a couple of days, because i have to merge over 1000 fixed issues. the new repository gets merged every week, so the changes will be applied faster now.

**Comment by TeridanDW** [comment] 2018-01-30 17:52
All 3 items work as intended on PTR.
