### ISSUE TITLE
A Special Surprise (Night Elf)

### ISSUE THREAD

**Issue by SadhuArch** [dalaranwow/dalaran-wow#2131] opened 2014-12-23 02:31 UTC
Quest: A Special Surprise (Night Elf race) - http://www.wowhead.com/quest=12743

No big deal really but you are to kill Yazmina Oakenthorn, a female Night Elf of the Argent Dawn. Her speech seem correct but if you wait and don't kill her she dies by her own and the emote says _"Yazmina Oakenthorn dies from **his** wounds."_
Pretty sure it should be _"Yazmina Oakenthorn dies from **her** wounds."_

No big deal for me personally but if a role-player comes along he or she might get out of the role for a second or two.

**Comment by Rushor** [comment] 2016-12-03 18:22
already fixed on PTR:

```sql
%s dies from her injuries.
```

**Closed by Rushor** 2016-12-03 18:22 UTC

**Comment by TeridanDW** [comment] 2017-04-02 18:26
Works as intended on ptr.
