### ISSUE TITLE
Vanish doesn't give immunity to AoE spells.

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5302] opened 2018-02-13 17:51 UTC
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Vanish doesnt give immunity for AoE spells, like affli lock AoE fear, priest fear, warrior fear, shadow fury etc...
**Expected behaviour**: Tell us what should happen instead
Vanish provides immunity for AoE spells.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Johanes022** [comment] 2018-02-13 19:51
I always thought that every rogue on this server is smart one to use Cloak of Sshadows with Vanish , cuz i couldnt get him with my DnD or Blood boil but now i realise it was bug all along.Anyway
Vanish tooltip doesnt say anything about aoe immunity.Only improved stealth.

http://wowwiki.wikia.com/wiki/Vanish

"Casters will be able to AoE you when you Vanish. Use Cloak of Shadows or [Sprint] or strike with [Cheap Shot] or potentially [Sap] (if they are out of combat already) to avoid this. "

**Comment by Edzero** [comment] 2018-02-13 20:31
99% sure it shouldn't give aoe immunity.

Where did you read that?

**Comment by Golganeth** [comment] 2018-02-14 01:12
Please fill the template when creating a bug report. Closing until enough proof to backup the issue is given.

**Closed by Golganeth** 2018-02-14 01:12 UTC

**Comment by Jiaku** [comment] 2018-02-14 16:23
Vanish doesn't say that it gives immunity when you vanish blind or stuns etc it doesn't say that but we all know that it does. But it doesn't apply to AoE Spells on this server.
@Johanes022 Im not that retarted please.
What i did not mentioned that is AoE CC spells that it but i thought saying about all kidna fears and shadow fury would give it away but i guess it didn't.

**Comment by Johanes022** [comment] 2018-02-14 19:05
I see what you mean now.Same thing as it should work with shadowmeld.When u use ability same time as someone else tries to use CC on you such as shadowfury.

**Comment by Edzero** [comment] 2018-02-14 20:20
That's much more clear. Pls re-open it mods
