### ISSUE TITLE
[NPC] Blackwater Deckhands

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3432] opened 2016-06-10 20:29 UTC
**Description**: Blackwater Deckhands have several issues relating to their ability to be farmed for Bloodsail Buccaneers reputation, including rewards, spawn rates, and numbers.

**Current behaviour**: Two Deckhands spawn in the Faldir's Cove subzone of Arathi Highlands. One spawns on the docks, the other on the deck of the ship. These are on seven minute respawn timers and grant 25 reputation with the Bloodsail Buccaneers, as well as reputation penalties of 125 with Booty Bay, 62.5 with Everlook, 62.5 with Ratchet, and 62.5 with Gadgetzan when killed.

**Expected behaviour**: Six Deckhands should be spawned in the area, including two on the docks, one on deck, one in the middle/gun deck, and two in the hold. Killing them should reward 5 reputation with the Bloodsail Buccaneers, as well as reputation penalties of 25 with Booty Bay, 12.5 with Everlook, 12.5 with Ratchet, and 12.5 with Gadgetzan when killed.

**Steps to reproduce the problem**:
1. Observe the currently spawned Deckhands in Faldir's Cove
2. Kill one
3. Wait seven minutes

**Include proofs for this behaviour**
http://www.wowhead.com/npc=2636/blackwater-deckhand#comments
http://wow.gamepedia.com/Blackwater_Deckhand

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPCs:
Blackwater Deckhand: 2636

Zones:
Arathi Highlands: 45

Factions:
Bloodsail Buccaneers: 87
Booty Bay: 21
Gadgetzan: 369
Everlook: 577
Ratchet: 470

**Comment by PSAlias** [comment] 2016-06-10 20:33
These are probably not the only mobs to have issues with the amount of rep they award/reduce with the Steamwheedle and Bloodsail factions, especially in the Faldir's Cove region. I would check in-game amounts against those listed here: http://wow.gamepedia.com/index.php?title=Mobs_which_affect_reputation_with_Steamwheedle_Cartel&oldid=2396650

**Comment by Rushor** [comment] 2016-11-13 11:50
DB/Creature: Blackwater Deckhand

* spawn 6 Blackwater Deckhands
* update reputation reward: you will now get 5 reputation with the Bloodsail Buccaneers, as well as reputation penalties of 25 with Booty Bay, 12.5 with Everlook, 12.5 with Ratchet, and 12.5 with Gadgetzan when killed.
* note 12,5 will be shown as 12 ingame (blizzlike issue)
* closes https://github.com/dalaranwow/dalaran-wow/issues/3432
* commit: 55fe198375fe07479d1025222feeae4d9f8078a2

![GitHub Logo](http://i.imgur.com/p7QW8Il.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 11:50 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 12:21
Works as intended on ptr, with 1 small detail, there should be:

>  one in the middle/gun deck, and two in the hold

however we have 3 in the hold. Still marking as:
