### ISSUE TITLE
Living Bomb severely bugged

### ISSUE THREAD

**Issue by daemonicBookkeeper** [dalaranwow/dalaran-wow#1777] opened 2014-08-02 03:10 UTC
Living Bomb, the 51-point Mage Fire talent, is a damage-over-time effect that detonates at the end of its duration or when the afflicted target dies.

It has two major bugs that I can reproduce:

When a target afflicted by Living Bomb dies, they do not detonate; they simply die and the debuff disappears. This is very easy to reproduce.

Second, when a Living Bomb effect's duration ends on a target, if the target is out of line-of-sight of the casting Mage, the detonation does not happen and a "Target not in line of sight" error is displayed.

**Comment by Vaxsysl** [comment] 2015-01-07 23:09
Additionally, bomb explosions make you enter combat. In a BG, if you LB everyone and run away, one would end up being in combat as those explosions are happening and then additionally wait 5sec PvP combat to wear off.

**Comment by Esunnaxqt** [comment] 2015-01-14 14:15
Confirming the bugs above.

Living Bomb should only give combat to the mage and its target on use.
The explosion should not give combat to anyone and here it gives to the caster and everyone damaged.

**Comment by Vaxsysl** [comment] 2015-01-14 18:10
New update. If Mage gets clearcasting proc (Arcane Concentration talent http://wotlk.openwow.com/spell=18189 ) and Living Bomb goes, off, it consumes Clearcasting, probably because of Burnout talent ( http://wotlk.openwow.com/spell=44450 ).

Also, Living Bomb: http://wotlk.openwow.com/spell=55360 That's the spell ID, but there is also http://wotlk.openwow.com/spell=55362 , I'm not sure what that is.

**Comment by daemonicBookkeeper** [comment] 2015-01-14 18:36
Living Bomb's detonation always put the mage and its victim into combat. This is a feature, not a bug; useful for preventing restealths, drinking, etc. Yes it is annoying occasionally, but it does work properly if it puts the Mage and the target into combat on detonation.

**Comment by Vaxsysl** [comment] 2015-01-14 22:26
My bad then; but other thing(s) remains.

**Comment by Aizenscar** [comment] 2015-07-16 12:31
BumpBumpBump

**Comment by Vaxsysl** [comment] 2015-08-16 20:33
While doing EotS today, my Living Bomb wouldn't even tick if I was not in LoS (I moved behind the MT building). I kept hearing error sounds and no damage was done to any target whatsoever.

**Comment by Vaxsysl** [comment] 2016-03-12 11:48
Bumping serves no purpose, but I'd like to bump nonetheless. I have to express displeasure at not having this bug(s) in your priority queue which resulted in unavailability to play Fire Mage in PvP (with results). Living Bomb is Fire Mage's core PvP ability and we are unable to play fire since realm's launch, which is two years and one month.

*1 When Living Bomb is ticking while not in line of sight on the enemy, we get all kind of errors, mostly Ignite not proccing. 
*2 When Living Bomb is exploding while not in line of sight of the enemy, it doesn't go off at all and does zero damage.
*3 When Living Bomb is dispelled, it doesn't explode as it should.

Unconfirmed: Ignite brings Fire Mage into combat (and the victim as well). I'm not sure if this is a bug or not, but it strikes odd that a DoT debuff's critical strike would make one enter combat. I could maybe understand it if EXPLOSION got us into combat, but applied Ignite from crit? I doubt it. Further research with proof is required.

**Comment by Golganeth** [comment] 2016-06-23 11:33
@rushor @robinsch LoS proc seems fixed, will test later.
98cd07bee101d99b64448133995161f63cfd4bee

Other issues still remain, no explode on dispell, affected target dies

**Comment by Golganeth** [comment] 2016-06-23 15:36
After the latest fixes can't confirm any of the issues above, closing. Dispell and LoS work now. Applied to live realm soon.

**Comment by Vaxsysl** [comment] 2016-06-25 12:50
Was it applied? I am still getting LoS issues.

**Comment by Lothloryen** [comment] 2016-06-25 15:44
Hello there,

It is not yet applied, as stated on the new or changelog overview we might need few days to deploy everything - it will probably be deployed before the Monday/Tuesday.

Thank you.

**Comment by Vaxsysl** [comment] 2016-07-03 15:35
I have just done a BG on my fire mage. All was right with dispelling and LoS, however, the issue when almost nothing happens while we are dead still persists. I got "Invalid Target" errors as well as "Can't do that while dead", while sitting idle as ghost.

**Comment by datbunneh** [comment] 2017-10-19 16:38
@Lothloryen Living Bombs still do not explode on target's death. Is it intended?

**Comment by Lothloryen** [comment] 2017-10-19 16:44
Thank you for the update, Datbunneh. 

@TeridanDW Can you confirm it, please?

**Comment by TeridanDW** [comment] 2017-10-19 17:05
After few tests on PTR:
- This:

> When a target afflicted by Living Bomb dies, they do not detonate; they simply die and the debuff disappears. This is very easy to reproduce.

is happening and confirming it as an issue.

![image](https://user-images.githubusercontent.com/6797611/31783943-a40fd750-b508-11e7-80d7-e1425ba067a0.png)

- This:

> Second, when a Living Bomb effect's duration ends on a target, if the target is out of line-of-sight of the casting Mage, the detonation does not happen and a "Target not in line of sight" error is displayed.

can't reproduce on PTR, must of been fixed in the past.

**Comment by Lothloryen** [comment] 2017-10-20 18:02
Hello again, my bad - living bomb does not have to explode when the target dies, only when the it is dispelled or the debuff expires. Not sure what I was thinking, sorry @TeridanDW . Closing this report. 

Thank you.

**Closed by Lothloryen** 2017-10-20 18:02 UTC
Labels: Class - Mage, Priority - Critical

**Comment by TeridanDW** [comment] 2017-10-20 18:36
This:

> Hello again, my bad - living bomb does not have to explode when the target dies, only when the it is dispelled or the debuff expires.

is correct. Proof for @datbunneh 
https://www.youtube.com/watch?v=aT-GfyeqJNI

**Comment by datbunneh** [comment] 2017-10-24 18:30
@Lothloryen @TeridanDW Alright, was not investigating this. Thought that author of this issue already has done it.

**Comment by daemonicBookkeeper** [comment] 2017-10-25 01:26
I authored this years ago! 

Yes, living bombs did explode on target death in Wrath (your "proof" video is of private server footage...).

**Comment by TeridanDW** [comment] 2017-10-26 10:28
Alright, regarding this:

> Yes, living bombs did explode on target death in Wrath (your "proof" video is of private server footage...).

could you provide a video/information to back up your claim please.

Here is one more video that I _think_ it's from retail:
https://www.youtube.com/watch?v=htyNa1YPMjw
at 1:30 sec

**Comment by daemonicBookkeeper** [comment] 2017-10-26 14:47
I went back and checked! In a video that's 100% from retail... there's no explosion animation. I can't conclude one way or the other on whether it explodes with no animation, but I assume that wouldn't be the case; 

Short version: I think I was wrong. Sorry! Reference video: https://www.youtube.com/watch?v=6hEbteuTPuw

**Comment by datbunneh** [comment] 2017-10-26 16:52
As far I get it, it actually did explode on target death during beta. Then it was changed.
