### ISSUE TITLE
Formula: Runed Adamantite Rod

### ISSUE THREAD

**Issue by Invoker7777** [dalaranwow/dalaran-wow#3429] opened 2016-06-09 22:41 UTC
**Description**:Formula: Runed Adamantite Rod is not spawning every 30 mins as intended

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by ImprezaWoW** [comment] 2016-06-10 00:07
Most likely the respawn timer has been set back to 24 hours [as it used to and should be.](http://www.wowhead.com/item=25848/formula-runed-adamantite-rod#comments:id=310741) 30 minute respawn timer was for convenience of the players. Anyways, duplicate of [1](https://github.com/dalaranwow/dalaran-wow/issues/2721) and [2](https://github.com/dalaranwow/dalaran-wow/issues/2737)

**Comment by Rushor** [comment] 2016-06-10 05:46
yes it's 24 hours respawn time

**Closed by Rushor** 2016-06-10 05:46 UTC
