### ISSUE TITLE
[Wintergrasp] Wintergrasp Marks of Honor bug

### ISSUE THREAD

**Issue by roger6** [dalaranwow/dalaran-wow#2235] opened 2015-02-11 09:13 UTC
1. If Player is ghost when wintergrasp combat is end, ghost status will lead player cannot make Wintergrasp Mark, it means player work hard in all combat but never get anything.
2. According to WoWWiki (http://www.wowwiki.com/Wintergrasp)
Player will get corresponding amount of Wintergrasp Marks of Honor by his rank
(players will be awarded 1 Mark for being a Recruit, 2 Marks for being a Corporal, and 3 Marks for being a First Lieutenant)
But Players always get 3 marks regardless of his rank after winning combat in our server, is it right? please have a look, thanks.

**Comment by Golganeth** [comment] 2015-02-12 13:28
Duplicate of #707

**Closed by Golganeth** 2015-02-12 13:28 UTC
