### ISSUE TITLE
Hunter's Pet

### ISSUE THREAD

**Issue by RazerTek** [dalaranwow/dalaran-wow#5543] opened 2018-07-18 09:20 UTC
Hunter's pet does not switch targets when you attack and well keep attacking the first

**Comment by Real-Scaramouche** [comment] 2018-07-18 09:42
That is not a bug as far as I know.
If you want your pet to attack whatever you choose to attack make a macro.
Something like this: 
> /cast killshot
> /petattack

Or just simply use default keybind Ctrl+1 on your current target.

**Comment by Golganeth** [comment] 2018-07-18 15:57
Not a bug, you have to switch the target.
Closing

**Closed by Golganeth** 2018-07-18 15:57 UTC
