### ISSUE TITLE
[loot][Crafting]  Prospecting does not always yield gems.

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#230] opened 2013-07-28 21:33 UTC
**Issue 1**
Prospecting Skill -  (http://www.wowhead.com/spell=31252) 

Issue:  Prospecting skill does not always yield a gem when using Thorium and Fel Iron Ores.

As per Patch 2.1.0 (http://us.battle.net/wow/en/game/patch-notes/2-1-0 ):
"Prospecting now always yields at least 1 gem."

Roughly 1/3rd of prospects on Thorium and Fel Iron Ores yield no gems, simply destroying 5 ore. Adamantite, Cobalt, and Saronite not yet tested.

**Issue 2**

Description:
10-15% of the time when I prospect ore, the game makes a ding sound and nothing comes out. My inventory doesn't change, the chat log says nothing. This has been consistently happening for over a week now.

Expected behaviour: Tell us what should happen instead
Prospecting should never fail.

Steps to reproduce the problem:

    Prospect enough, say 10-15 stacks of Saronite ore, and pay attention to each prospect

**Comment by haydn132** [comment] 2015-10-23 05:24
Still broken :(

**Comment by Setzer1994** [comment] 2015-10-27 12:08
Still bugged.  About 1/4 of prospects consume 5 ore with no gem returns.

**Comment by Amontis** [comment] 2015-10-28 08:16
Here is further information on it, proving it IS a bug: https://github.com/TrinityCore/TrinityCore/issues/12011


Fix ASAP please! I know it may not seem like a lot but disenchanting feels bugged as well.

**Comment by Rushor** [comment] 2016-11-08 10:04
**Issue 2**
Description:
10-15% of the time when I prospect ore, the game makes a ding sound and nothing comes out. My inventory doesn't change, the chat log says nothing. This has been consistently happening for over a week now.

Expected behaviour: Tell us what should happen instead
Prospecting should never fail.

Steps to reproduce the problem:

Prospect enough, say 10-15 stacks of Saronite ore, and pay attention to each prospect

**Comment by BloodyIron** [comment] 2016-11-08 17:16
FYI Rushor is quoting from the other ticket I opened that they closed, #3811 . I did not know this ticket was already open.

So... why hasn't it been fixed? Jul 2013 was when this ticket was opened...

**Comment by Rushor** [comment] 2016-11-08 17:40
it will be fixed if a developer has time to fix it :)

**Comment by Rushor** [comment] 2016-11-26 09:04
https://github.com/Kittnz/Sunwell/blob/831ac9da07abf607cfb585a4435a0734759da977/sql/world%20fixes/loot/generic.sql#L16

**Comment by Rushor** [comment] 2016-11-26 09:33
DB/Prospecting: Update loot for Fel Iron Ore(23424), Cobalt Ore(36909), Titanium Ore(36910) and Saronite Ore(36912)

* you should always get at least one item after prospecting now
* closes https://github.com/dalaranwow/dalaran-wow/issues/230
* commit: 02901281d8ab0404d28fff5a805b4c6a1c594f70

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 09:33 UTC
Labels: Items, On PTR

**Comment by BloodyIron** [comment] 2016-11-26 22:40
Fabulous! Can't wait till this hits main :D Thanks!

**Comment by BloodyIron** [comment] 2017-01-06 16:18
I'm still getting this on "live". I also don't see any news post since ~Nov covering patches. Is this still on PTR only at this point?

**Comment by Rushor** [comment] 2017-01-06 17:20
no the fix is not even on ptr. once the ptr was updated with the fix, it can be tested. once the fix was confirmed a sowrking it will be pushed to the live.

**Comment by BloodyIron** [comment] 2017-01-06 17:43
> I cannot speed up the process of appling fixes to ptr/or live

Understandable. What is the timeframe though of such things? I don't know :(

**Comment by Rushor** [comment] 2017-01-06 17:47
I don't know when loth has the time to update the ptr :(
