### ISSUE TITLE
[Quest] Fringe Science Benefits / Amped for Revolt!...

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#759] opened 2013-09-08 22:06 UTC
**Quest Fringe Science Benefits** - _(ID:13373)_
**Quest Amped for Revolt!** - _(ID:13374)_
**Quest Riding the Wavelength: The Bombardment** _(ID:13406)_ - Daily
**Quest Total Ohmage: The Valley of Lost Hope!** _(ID:13376)_  - Daily 
- **Issue present:** Players are unable to talk to **Rizzy Ratchwiggle** _(ID:31839)_, to request a vehicle from her gossip option.
- **How it should work:** After clicking on a gossip option, **Ready for action!**, you will automatically be mounted on a vehicle **Horde Infra-green Bomber** or **Alliance Infra-green Bomber** which has several abilites. The vehicle can fly, drop bombs and shoot the undead.

Sadly there is no video anywhere how this quest should work.
Nor I could find the proper vehicle or its abilites.

---

http://www.wowhead.com/quest=13373/fringe-science-benefits
http://www.wowhead.com/quest=13374/amped-for-revolt
http://www.wowhead.com/npc=g/rizzy-ratchwiggle#.
http://www.wowwiki.com/Rizzy_Ratchwiggle
http://www.wowhead.com/quest=13406/riding-the-wavelength-the-bombardment
http://www.wowhead.com/quest=13406
http://www.wowhead.com/quest=13376
http://freewowguide.org/wow-quest-fringe-science-benefits/

**Comment by Braniacz** [comment] 2016-06-21 22:52
Quest Fringe Science Benefits - I managed to do this quest which took little bit of practice but at the end i was able to complete it. On the other hand quest Quest Amped for Revolt! is not doable since Froostbrood Sentry cant be killed by bombers (vehicle) 2nd ability thus i couldnt complete the quest. Big issue i had is when my vehicle got destroyed. Offc i fell down but with my bubble i could survive to fall but than the mobs (Gargoyle Ambusher, Froostbrood Sentry) still had agro on me and totaly rekt me. Even after ressurect i got insta agro and died 2 or 3 times before I could escape my doom. I found quest extremly frustrating.

**Comment by Mazz312** [comment] 2016-06-23 18:10
These quests were indeed scripted by the mobs in question, mainly the Gargoyles and Frostbrood Sentries are incorrectly implemented. The shield on the bomber also seems incorrect. There also seems to be too few mobs on the ground for completion of Fringe Science benefits in one pass.

**Comment by Mazz312** [comment] 2016-06-25 18:35
Alright, I'll transfer the full report here, but I hope there is some response since these are pretty serious problems for zone as a whole.



This quest tree, which was implemented semi-recently, is completely broken and actually causing additional problems in Icecrown that weren't there previously.

I know there is an open issue for this already but this needs to be bumped hard, because some of the mobs involved are causing pretty major problems for the zone as a whole. Particularly the way the flying mobs work right now.

This is a list of issues with this quest tree, in no particular order:

    The player is not receiving the infra-green phase when entering the bomber (nor is the phase buff used at all), which is likely the source of the phasing problems detailed in the comments below.
    [The vision spell = 59651]

    The bomber doesn't have the shield at all, as it does in retail, instead just converting any damage taken into the fires, and periodically just killing the bomber if you get behind on said fires. With no shield, you must be in AA mode to deal with the mass of Gargoyles that spawn or you will burn out and fall to your death, which means you have to resurrect under the ridiculous gargoyles who will likely kill you again.
    [The shield is spell = 59288]

    The Gargoyle Ambushers have a massive aggro radius, which includes an unlimited z-axis. This means if you are near the ground, like after ressing when your fighter is shot down, you will immediately pull aggro and get bolted for 9000 by their spell (in leather). They cast with a 1.5s cast time.

    The phasing of the mobs/gargoyles seems to be broken, which means these gargoyles exist at all times for every character in the area, regardless of if you're on the quest or not. This means a large part of the middle of icecrown is quite nearly unpassable. I think this is tied to the lack of the infra-green phase toggle.

    There are not enough Enraged Fleshstalkers spawning and/or the skeletons are not tagged as bombardment infantry. There is zero possibility you can actually get all 40/50 mobs killed in one pass currently, exasperating the above gargoyle issues.

    The scourge war machines used in Amped for Revolt! are also not phased, which means they attack players in Valley of Lost Hope, where many earlier Icecrown quests are located.

    The Frostbrood Sentries have all the same aggro radius problems as the Gargoyles, but with even more fun attached. While targeted and attacked by ability #2 in the bomber's AA mode, they take zero damage from it. This makes Amped for Revolt! and the follow up daily impossible to finish currently.

    Finishing Fringe Science Benefits unlocks the Amped for Revolt! daily as well as its own, which I think is incorrect.

    When finishing the quest (if you don't get shot down), the plane will dump you near the front of the gate with no parachute, resulting in either your death or very low health and potential aggro from any of the mobs in that area.

IDs:
Quests
Fringe Science Benefits = 13373
-> Riding the Wavelength: The Bombardment = 13406
Amped for Revolt! = 13374
-> Total Ohmage: The Valley of Lost Hope! = 13376

Important Mobs
Gargoyle Ambusher = 32769 or 32188 (could be part of the issue with phasing)
Frostbrood Sentry = 31721
Scourge War Machine = 32154

**Comment by Lothloryen** [comment] 2016-06-25 21:42
Thank you for the report Mazz312, @jonanone already fixed most of those issues during the past two days and they should be deployed to the live realm within the next week.

He shall keep this post updated with further progress.

**Comment by Mazz312** [comment] 2016-06-25 21:47
Alright, good to hear, and thanks. You guys fixed a lot of the other bugs in Icecrown, I just didn't want this one to get overlooked for long because it makes the zone seem far more buggy then it is.

**Comment by Rushor** [comment] 2016-11-15 12:03
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by MrAndersonX** [comment] 2016-11-15 12:31
So, for the Quest " Green Technology #693 , the NPC is not spawned, so completing the quest/taking other quests/finishing the chain is not possible.

https://postimg.org/gallery/2wvkx9nwk/

**Comment by Rushor** [comment] 2016-11-25 19:16
note: npcs were removed due to internal errors. we will improve this later :)

**Comment by TeridanDW** [comment] 2017-04-05 11:22
> note: npcs were removed due to internal errors. we will improve this later :)

This is also the case in ptr, remove the label "fixed on ptr" until they are added again.

**Comment by roblockster** [comment] 2017-05-19 18:34
NPCs still removed, no way to continue chain.

**Closed** 2017-11-30 14:20 UTC
Labels: Area - Northrend, Fixed - On Live Server, General - Quests
