### ISSUE TITLE
[Quest][Northrend] Need to Know

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2392] opened 2015-05-20 14:47 UTC
Horde quest in Dragonblight, http://www.wowhead.com/quest=12234/need-to-know

Quest items: 
Abbey: 37268
Barracks: 37267
Beach: 37269

The quest is...doable, but there's a problem with the quest items: They respawn QUITE late. I was circling around the beach area around all of the tents, and with only one 5min break, I found beach plans 40min later. Yes, I was roaming around so long, and yes, I am aware that someone could've come in those 5min, but hey, this isn't the first time respawn takes longer than it "should". IMO, respawn should be faster, isn't it?

**Comment by Kaporalhart** [comment] 2015-07-30 11:51
I have to confirm this someone took the item before me so i stayed around a bit. But i cleaned the area 2 times now and still waiting...

**Comment by snikt05** [comment] 2015-12-18 11:31
The item of the mission " Scarlet Onslaught Daily Orders: Barracks " is not looteable .

**Comment by Rushor** [comment] 2016-11-26 20:52
DB/Gameobject: Reduce spawntime for Scarlet Onslaught Daily Orders to 60 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/2392
* commit: d1b97a3450d2b728d4ec616ffd43529ce2639e92

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 20:52 UTC
Labels: Continent - Northrend, On PTR, Quests
