### ISSUE TITLE
[NPC] Warmaul Brute

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1907] opened 2014-09-27 08:52 UTC
http://www.wowhead.com/npc=18065

This mob is missing it's one and only ability: 
- Uppercut: inflicts 50% weapon damage and knocks it's victim back. Should be used every couple of second, the whole point of it is knocking people down from Warmaul Hill.

Link: http://www.wowhead.com/spell=10966

Currently Warmaul Brutes just melee instead.

**Comment by Rushor** [comment] 2016-11-11 10:00
DB/Creature: Implement Warmaul Brute SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1907
* now the creatures uses the spell 3-4 seconds the first time after starting combat and repeats it every 8-12 seconds
* commit: 1b0063bea95644575201f0ae595616759e9a4b1a

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-11 10:00 UTC
Labels: Continent - Outland, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 09:12
Works as intended on ptr.
