### ISSUE TITLE
Quest: Gizelton Caravan

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#443] opened 2013-08-07 20:17 UTC
- **Issue:** Same issue and related to #231 

Escort event simply doesn't work .
Nothing happens when you accept the quest from a NPC.

http://www.wowhead.com/quest=5943/gizelton-caravan
http://wotlk.openwow.com/quest=5943

**Comment by Cone182** [comment] 2015-05-31 19:14
stll bugged

**Comment by gotnoface** [comment] 2015-08-19 14:14
Still not doable.

**Comment by Rushor** [comment] 2016-06-08 14:35
065f36c4957efbfe18d246bcaa173e3301031cf3
-  added the escortevent

**Comment by Golganeth** [comment] 2016-06-09 16:05
Can't seem to be able to pick up the quest and start the escort event. The NPCs get stuck on the hut once they finish their path.

**Comment by Rushor** [comment] 2016-06-09 16:35
http://i.imgur.com/xV0H0z4.jpg
http://i.imgur.com/KNxOP7R.jpg

once they reached the hat, they will wait there 15 minutes, after that they will move on some time to this point http://i.imgur.com/KNxOP7R.jpg. there you can accept the quest and the creatures will move on. same goes for the other quest :)

**Comment by Golganeth** [comment] 2016-06-09 17:27
Along their way out of the huts, the NPCs may get stuck when trying to get in combat against NPCs. At that point they'll be charging and insta evading. If that NPC is killed, they will be stuck and not move at all anymore, so quests can't be obtained.

Something must be done about it, reopening for now.

**Comment by Godzilla2k** [comment] 2016-11-05 16:56
Can confirm this is still a problem.

**Comment by Rushor** [comment] 2017-03-20 14:10
DB/Creature: Cork Gizelton + Rigger Gizelton + Gizelton Caravan Kodo - Increase combatdamage

* the creatures should now easier be able to slay the enemies and should no longer evade
* updates: https://github.com/dalaranwow/dalaran-wow/issues/443
* updates: https://github.com/dalaranwow/dalaran-wow/issues/231
* commit: a4cd8398038082d6b8c9240329d61624f02bdadd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-20 14:10 UTC
Labels: Area - Classic, General - Quests

**Comment by Rushor** [comment] 2017-03-21 20:25
Scripts/Desolace: Gizelton - Do not start escortpathevent if the creature is in combat 

* commit: e4fcf15a0758b30b453dde5ec05514dbc514dd5e
* updates: https://github.com/dalaranwow/dalaran-wow/issues/231
* updates: https://github.com/dalaranwow/dalaran-wow/issues/443

With this fix the creatures should always properly start their pathing once the hostile creatures are killed.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Crispybuilt** [comment] 2017-10-16 19:41
Fixed, tested on PTR, working as intended, could use improvements in pathing, but the vendors at least spawn properly.
Needs to be deployed to Live.

**Comment by Godzilla2k** [comment] 2017-11-22 20:07
Gizelton Caravan and related quest to it are still undo able. They Freeze at the top of that hill on their path and stay that way.

**Comment by TeridanDW** [comment] 2017-11-22 20:15
@Godzilla2k is this not working then?

> once they reached the hat, they will wait there 15 minutes, after that they will move on some time to this point http://i.imgur.com/KNxOP7R.jpg. there you can accept the quest and the creatures will move on. same goes for the other quest :)

**Comment by Godzilla2k** [comment] 2017-11-23 00:28
http://i88.photobucket.com/albums/k197/modestlyicons/WoWScrnShot_112217_190658.jpg

Ok. I waited at that point, I also have circled around the path he is supposed to travel on. The only time I see the caravan is on top of that hill. You can not interact with them and they stay bunched up together. I provided a photo to show what I am seeing. If im missing something obvious sorry.

**Comment by TeridanDW** [comment] 2017-11-23 09:09
@Crispybuilt, could you review this again please.

**Comment by gentwistle** [comment] 2019-06-18 00:47
→ Confirmed that the caravan paths are most definitely still broken on Dalaran WoW server. 100% recreated the behavior that @Godzilla2k described in his post above.
 → Since the caravan never moves, the two robot vendors: Vendor-Tron 1000 and Super-Seller 680 never spawn at the campsites at north and south of the route.
 → If someone could take a look at this, that would be very much appreciated!
