### ISSUE TITLE
[Quest] Herald of War

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3871] opened 2016-11-21 19:45 UTC
- **Prequest** Herald of War ID 13257

**Issue Present:** After you get teleported to Durotar infront of Orgimmar, many of the dialogues are missing which can be found walking across Durotar/Orgimmar.

**The refugees will say any of the following:**:
- *We've lost Undercity. Nothing but demons and Putress' apothecaries left there...
Help us! Please!*
- *The Dark Lady fought off as many as she could, but in the end... I hope she survived. Please help!*

**Overlord Runthak has also gathered all the vendors and NPCs at the front of the Orgrimmar bank. The vendors and NPCs will ask the pacing Runthak with questions, who will then ask them for silence**
- *Overlord Runthak yells: SILENCE!*
- *Overlord Runthak says: We are on the brink of all out war with the Alliance!*
- *Overlord Runthak says: Tragic events have unfolded in Northrend. The Warchief is doing all that he can to keep us safe.*
- *Overlord Runthak says: All services and shops are to remain closed until further notice! That is all!*

------------------------------

**Issue 2 present:**

 The entire dialogue again just like in the #3870 is missing here between Jaina, Thrall and Slyvanass.

- *Thrall says: Kor'kron, stand down!*
- *Thrall says: Jaina...*
- *Lady Jaina Proudmoore says: Thrall, what has happened? The King is preparing for war...*
- *Thrall says: Jaina, what happened at the Wrathgate. It was a betrayal from within...*
- *Lady Sylvanas Windrunner says: Lady Proudmoore, the Warchief speaks the truth. This subterfuge was set in motion by Varimathras and Grand Apothecary Putress. It was not the Horde's doing.*
- *Lady Sylvanas Windrunner says: As the combined Horde and Alliance forces began their assault upon the Wrathgate, an uprising broke out in the Undercity. Varimathras and hordes of his demonic brethren attacked. Hundreds of my people were slain in the coup. I barely managed to escape with my life.*
- *Thrall says: The Horde has lost the Undercity.*
- *Thrall says: We now prepare to lay siege to the city and bring in the perpetrators of the unforgivable crime to justice.*
- *Thrall says: Know this, Jaina: War with the Alliance is not in our best interests. If we are forced into a conflict, the Lich King will destroy our divided forces in Northrend.*
- *Thrall says: We will make this right, Jaina. Tell your king all that you have learned here.*
- *Lady Jaina Proudmoore says: I will deliver this information to King Wrynn, Thrall, but...*
- *Lady Jaina Proudmoore says: Bolvar was like a brother to him. In the King's absence, Bolvar kept the Alliance united. He found strength for our people in our darkest hours. He watched over Anduin, raising him as his own.*
- *Lady Jaina Proudmoore says: I fear that the rage will consume him, Thrall. I remain hopeful that reason will prevail, but we must prepare for the worst... for war.*
- *Lady Jaina Proudmoore says: Farewell, Warchief. I pray that the next time we meet it will be as allies.
Jaina takes the portal back to Stormwind City.*
- *Thrall says: Kor'kron, prepare transport to the Undercity.*

**Links:** http://wotlk.openwow.com/quest=13257
http://wowwiki.wikia.com/wiki/Quest:Herald_of_War
**Video Link:**
https://www.youtube.com/watch?v=flPCbRZAaQI

**Comment by Rushor** [comment] 2016-11-21 21:49
the portals and the dialogue are workimg fine for me http://i.imgur.com/bMwY0jZ.jpg. i think the fix in:
quests/zones/special/battle for the undercity/herald of war.sql wasn't applied propperly on ptr. i will inform loth :)

**Comment by Rushor** [comment] 2016-11-22 12:07
yep because of fbc327a08c57bbcda5c04b7e9bd85125c82d5126, the spawn and several other improvements of the quest wasn't applied. i will create a new sql file with all undercity changes with the name: "\sql\fixes\quests\zones\Special\battle for the undercity\battle_for_the_undercity_complete.sql"

@Lothloryen pls rerun this file for the ptr and make shure, that gameobject_addon is enabled. thank you ! :) <3 (commit: b02db6efbde4b13383fa6d0663f8ffe3b5eeecbf)

**Comment by Cone182** [comment] 2017-01-26 18:32
apparently when I pick up the quest, there is no portal to OG showing up.

**Comment by Badjourasmix** [comment] 2017-03-03 14:24
I am having the same problem I accept the quest and the portal doesn't show up

**Comment by Rushor** [comment] 2017-03-03 14:28
The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-03-30 13:16
This part:

> The refugees will say any of the following::
> 
> We've lost Undercity. Nothing but demons and Putress' apothecaries left there...
> Help us! Please!
> The Dark Lady fought off as many as she could, but in the end... I hope she survived. Please help!

doesn't seems to work on ptr.

Everything else in this report works as intended. Quick SAI for them should solve it.

**Comment by Rushor** [comment] 2017-03-30 13:23
more texts here: http://wowwiki.wikia.com/wiki/Forsaken_Refugee

**Comment by TeridanDW** [comment] 2017-03-30 13:24
Yep, wowhead has them too. This should do the trick:
``` sql
-- Add texts
DELETE FROM `creature_text` WHERE `entry` = 31437; 
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(31437,0,0,' The Dark Lady fought as many as she could, but in the end... I hope she survived. Please help!',12,0,100,0,0,0,0,0,''),
(31437,0,1,' Could you spare a gold?',12,0,100,0,0,0,0,0,''),
(31437,0,2,' They killed hundreds! We barely escaped with our lives! Help!',12,0,100,0,0,0,0,0,''),
(31437,0,3,' You must help! We\'re homeless!',12,0,100,0,0,0,0,0,'');

-- Forsaken Refugee SAI
SET @ENTRY := 31437;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,10,0,50,0,0,20,10000,20000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Forsaken Refugee - Within 0-20 Range Out of Combat LoS - Say Line 0");
```

**Comment by Rushor** [comment] 2017-03-30 13:25
more texts:

```sql
DELETE FROM `creature_text` WHERE `entry`=31437;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES 
(31437, 0, 0, 'We''ve lost Undercity. Nothing but demons and Putress'' apothecaries left there...', 12, 1, 100, 0, 0, 0, 32226, 'Forsaken Refugee'),
(31437, 0, 1, 'They killed hundreds! We barely escaped with our lives! Help!', 12, 1, 100, 0, 0, 0, 32229, 'Forsaken Refugee'),
(31437, 0, 2, 'The Dark Lady fought off as many as she could, but in the end... I hope she survived. Please help!', 12, 1, 100, 0, 0, 0, 32230, 'Forsaken Refugee'),
(31437, 0, 3, 'You must help! We''re homeless!', 12, 1, 100, 0, 0, 0, 32227, 'Forsaken Refugee'),
(31437, 0, 4, 'Help us! Please!', 12, 1, 100, 0, 0, 0, 32225, 'Forsaken Refugee');
```

**Comment by Rushor** [comment] 2017-03-30 13:33
DB/Creature: Forsaken Refugee - Add textscript for quest: Herald of War

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3871
* commit: 7273a67fcbbe17673251dd96bcfca4435d4ad143

![GitHub Logo](http://i.imgur.com/WqxjhfR.jpg)

The quest works now as intended

**Comment by roblockster** [comment] 2017-05-21 04:26
Portal didn't spawn, as reported multiple times in this report and in various other reports: #3798 #2560 #2404 #2966 #908 #2506

**Comment by TeridanDW** [comment] 2017-05-21 12:09
Hello @roblockster , everything related to the undercity's event is still on ptr level and all of the tickets pointed by you are ptr relevent only yet. When this event is ready for live there will be an announcement. Thank you.

**Comment by TeridanDW** [comment] 2017-10-16 13:36
Hello after rechecking this quest  I think second part of @Rushor fix:

> DB/Creature: Forsaken Refugee - Add textscript for quest: Herald of War

is missing from PTR (or not working).

Also found 1 very small detail. Players are not suppose to be able to see/click on creature "Portal to Stormwind" https://wowgaming.altervista.org/aowow/?npc=31640 , the portal itself should be visible.
![wowscrnshot_101617_162806](https://user-images.githubusercontent.com/6797611/31614699-f0bbd62e-b28f-11e7-8d4a-32cf017be50c.jpg)

**Closed** 2017-10-23 20:06 UTC
Labels: Fixed - Waiting for PTR update, General - Quests
