### ISSUE TITLE
[Death Knight] DK Spell Army of the Dead

### ISSUE THREAD

**Issue by Kilour** [dalaranwow/dalaran-wow#1393] opened 2014-03-25 00:45 UTC
Currently does not taunt targets and only does damage.

**Comment by Rushor** [comment] 2016-12-13 11:43
DB/Creature: Implement abilities for Army of the Dead Ghoul

* Army of the Dead Ghoul will now cast 'Periodic Taunt' (the ability will only hit non-worldbosses
* Army of the Dead Ghoul will cast 'Leap' and 'Claw' besides it's meleeattacks as combatspells
* closes https://github.com/dalaranwow/dalaran-wow/issues/1393
* commit: 506f18688c5a9e801d3a1d872dc5b0634841cb7f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by tripleslash** [comment] 2017-10-20 17:15
This is bugged on live atm and it taunts raid bosses.

http://wowwiki.wikia.com/wiki/Army_of_the_Dead

It should not taunt raid bosses.

**Comment by Lothloryen** [comment] 2017-10-20 17:22
Hello, it should be fixed but is not on live yet, only on PTR. Once is tested and confirmed as working, it will be deployed to live within the next maintenance.

Thank you.

**Comment by tripleslash** [comment] 2017-10-20 17:24
Oh i mean that the last maintenance that you did today broke army. It did not used to taunt raid bosses.

**Comment by Lothloryen** [comment] 2017-10-20 17:37
Right, thank you very much for the heads up, we will take look.

**Comment by TeridanDW** [comment] 2017-10-20 17:39
After few tests on world boss and world creatures on PTR:

> Army of the Dead Ghoul will now cast 'Periodic Taunt' (the ability will only hit non-worldbosses

I wasn't able to see this ability been used in both cases.


> Army of the Dead Ghoul will cast 'Leap' and 'Claw' besides it's meleeattacks as combatspells

Claw works as intended on PTR.
Leap was never used.

**Closed** 2017-10-30 13:25 UTC
Labels: Class - Death Knight, Fixed - On Live Server, Listed - Changelog

**Comment by TeridanDW** [comment] 2017-10-30 16:26
Hm only 1/3 of the original issue is fixed, but the report is marked as fixed - on live server. Am I missing something here?

**Comment by Crispybuilt** [comment] 2017-10-30 16:44
- Correction still needed for live, Army still taunts Raid Bosses (Saurfang, Marrowgar etc for example)
