### ISSUE TITLE
[NPC] Gahz'ranka

### ISSUE THREAD

**Issue by Braniacz** [dalaranwow/dalaran-wow#3639] opened 2016-08-09 21:19 UTC
**Description**:
 U can summon Boss multiple times in one raid ID.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Zul Gurub (20 man raid vanilla). I summoned Boss named Gahz'ranka and after killing it I could summon it again.
**Expected behaviour**: Tell us what should happen instead
U shouldn't be able to summon boss multiple times
**Steps to reproduce the problem**:
1. Enter Zul Gurub
2. Have 2x Mudskunk Lure and 10x Zulian Mudskunk
3. Summon Boss 2 times

**Include proofs for this behaviour**
Well basic knowledge about Wow tells me that bosses shouldn't be resummoned more than once in same ID. And what I gathered from comments http://www.wowhead.com/npc=15114/gahzranka#comments even with the additional lures boss shouldn't reappear.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Mudskunk Lure (19974), Zulian Mudskunk (19975), Gahz'ranka (15114)- not sure about this one

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment] 2016-11-14 10:27
Scripts/ZulGurub: Prevent multiple summon of Gahz'ranka

* closes https://github.com/dalaranwow/dalaran-wow/issues/3639
* the boss will now only be summoned one time. If you use the Mudskunk Lure another time, it will no longer spawn further Gahz'rankas
* commit: bed7b46973a95819520977b60795693a1e6f1666

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 10:27 UTC
Labels: Instances, On PTR, Priority - Low

**Comment by TeridanDW** [comment] 2017-03-31 17:27
Works as intended on ptr, however i would like to add that:
 - when player uses item http://wotlk.openwow.com/item=19974 , the impact location in the water is wrong.
This is where it is going now:
![image](https://cloud.githubusercontent.com/assets/6797611/24561508/af74df62-164f-11e7-9921-160ee7eaa88d.png)

But it should be where the boss is been summoned (check the videos below).

 - The boss itself should have intro event (just a simple path) which you can see here:
https://www.youtube.com/watch?v=JEmFTdr65UY
https://www.youtube.com/watch?v=zuKQNXdJhts
