### ISSUE TITLE
[NPC] Dragonmaw Scout does not react to the attacker.

### ISSUE THREAD

**Issue by EmeryDuBois** [dalaranwow/dalaran-wow#2032] opened 2014-11-04 12:50 UTC
I took a quest called "The Algaz Gauntlet" and found this bug. Dragonmaw scouts will attack you only if you let them run away which happens only when their health low. I tested Dragonmaw Grunts and they look fine, but I think you should also test them just in case. Sorry for my English.
http://www.wowwiki.com/Quest%3AThe_Algaz_Gauntlet
http://www.wowwiki.com/Dragonmaw_Scout
http://www.wowwiki.com/Dragonmaw_Grunt

**Comment by Rushor** [comment] 2016-11-14 21:32
DB/Creature: Update SAI for Dragonmaw Scout

* closes https://github.com/dalaranwow/dalaran-wow/issues/2032
* the creature will now attack correctly
* commit: e4fef88a00f5399584a26b0e573d6fbb64648851

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 21:32 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-02 19:09
Works as intended on ptr.

**Comment by n-ghost** [comment] 2017-05-09 10:32
Did the Algaz Gauntlet a few days ago, all of the Scouts were nice and violent.

Also, hi.
