### ISSUE TITLE
NPC: Withered Spearhide

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1855] opened 2014-09-07 12:00 UTC
http://wotlk.openwow.com/npc=7332

Currently mob has hard time switching between ranged attacks (that he can use just fine) and melee attacks (that he won't use at all when his target is in melee range).

He should use melee attacks when his target closes to melee range and switch back to ranged when no-one is in melee range, accordingly.

Cheers.

**Comment by Rushor** [comment] 2016-11-13 19:53
DB/Creature: Update SAI for Warsong Scout, Withered Spearhide, Murkblood Spearman and Dragonmaw Scout

* closes https://github.com/dalaranwow/dalaran-wow/issues/1855
* if you run really close to these creatures, they should still hit you with meleeattacks, else they will cast their normal range spells.
* commit: ad238efe57b1844c8ba9e5dea63dad4fa21fd164

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-13 19:53 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-03 10:09
Works as intended on ptr.
