### ISSUE TITLE
Quest / NPC: The Frost Wyrm and its Master / Wyrmcaller Vile

### ISSUE THREAD

**Issue by evilstein** [dalaranwow/dalaran-wow#477] opened 2013-08-09 15:29 UTC
http://www.wowhead.com/quest=11267 (H)
http://www.wowhead.com/quest=11238 (A)
http://www.wowhead.com/npc=24029

The NPC isn't present on its location or the respawn time is too long. For 20 minutes I haven't seen the NPC, neither again after an hour. Without this NPC, the quest is impossible to complete (the NPC is required to be killed and further drops a needed item, which also summons another needed NPC).

**Comment by Golganeth** [comment] 2015-01-05 14:52
Hotfixed. Now players won't need a flying mount to kill Glacion manually.

**Comment by vison2** [comment] 2015-05-29 20:37
Playing on Algalon

there seems to be no Glacion at all

**Comment by robinsch** [comment] 2015-05-30 08:15
Can confirm, tried it yesterday. There is no Glacion.

**Comment by Lebaowski** [comment] 2015-06-05 03:02
Between now and 30 minutes ago I've been able to find Glacion and get credit, but Wyrmcaller Vile is missing and does not seem to spawn.

**Comment by ashido96** [comment] 2015-06-08 22:06
Can confirm that Glacion does spawn and patrols in air relatively close to the ground, was able to taunt and kill as well as correctly awards kill credit.

**Comment by Prazza** [comment] 2015-07-16 21:44
Was able to kill Wyrmcaller Vile.. however no sign of Glacion in the sky, nor would the horn blow.

**Comment by LoopyDemon** [comment] 2015-07-18 23:00
Same as the comment above. Was able to kill Wyrmcaller Vile, but no sign of Glacion in the sky nor the horn would work.

**Comment by Spydoc** [comment] 2015-07-29 12:39
Confirmed. Glacion never spawns and the Wyrmcaller's Horn can't be used on the appropriate location.

**Comment by citizennuber789** [comment] 2015-07-31 12:10
confirmed.
Glacion Patrolling the Air , manual taunt to the ground,
even Wyrmcaller's Horn can't be use properly

**Comment by rodrigonb** [comment] 2015-08-09 09:26
The horn doesn't work, however, there is a way to do the quest, even for people without the flying mount:

You have to stand exactly at 37.5 - 13.7, it's a pretty tall spot and it's directly below his flight path. When he gets close you have to target him and use a ranged ability on him (My Paladin's 30 yard Hand of Reckoning worked).

**Comment by belegija** [comment] 2015-08-30 22:03
Wyrmcaller's Horn still unusable. Also Glacion seems to be on very long respawn timer.

**Comment by exiledone** [comment] 2015-09-09 07:50
stand on the peak to the right of the wyrmcaller, and taunt the dragon as it flys by

**Comment by Thillo** [comment] 2015-09-19 14:02
imho, this quest should be considered bugged and completable by a gm. I spent more than an hour finding a sweet spot to taunt him down and due to his long long flight path, i eventually gave up on it. If a quest doesn't work as intended and is this time consuming to complete, it shouldn't be viewed as completable. But thats my opinion

**Comment by Ticklebur** [comment] 2015-10-08 11:57
can confirm bugged, the horn doesnt work, so you cant call down Glacion, which isnt even there!

**Comment by xjsc16x** [comment] 2016-02-08 05:46
Quest is easily doable as level 80. Make a macro to target and taunt him and then sit at the little peak above the guy that drops the horn (approx. 35.8, 7.7). I got him first try and he died in just a few seconds

**Comment by NovaHiros** [comment] 2016-03-14 06:21
This is still bugged on algalon. Glacion won't spawn. I'm fresh and i can't fly but /target macro won't show me anything for miles.

**Comment by alphaest** [comment] 2016-03-25 09:15
Got this completed today by having two players.
The problem here is that the view-box of Glacion is too small and the horn item doesn't work. 
To be able to pull him on the hilltop you need one player that runs with Glacion from platform to platform to keep the mob moving and the other player be ready to shoot at the before mentioned coords (37.5 - 13.7).
Using "/tar Glacion /stopmacro [noexists] /w myname found %t" macro while running helps to make sure Glacion is in range and moving with you.

**Comment by Lothloryen** [comment] 2016-04-22 15:07
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.

**Comment by Rushor** [comment] 2016-12-03 11:53
seems to be broken again:


12:41 PM

Once you kill Wyrmcaller Vile and loot the Wyrmcaller Horn, you cannot use the horn to spawn Glacion, all it says when you attempt to use the item is: "Requires the Wyrmcaller's Platform".

The Wyrmcaller's Platform is where you kill Wyrmcaller Vile

12:41

So yeah the item doesn't work, you cant use it to spawn Glacion

12:41

Try doing it on a horde character, if it works for you on alliance

**Comment by Rushor** [comment] 2016-12-03 11:57
DB/Quest: Implement quest: The Frost Wyrm and its Master 

* closes https://github.com/dalaranwow/dalaran-wow/issues/477
* commit: 47659ade02ba7dc98941f781cc9f348b73ee485b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-03 11:57 UTC
Labels: Continent - Northrend, Fixed - Waiting for PTR Update, General - Quests
