### ISSUE TITLE
[NPC][WotlK] Enraged Tempest, Raging Boiler and Boiling Spirit

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4592] opened 2017-03-17 10:22 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Npc http://wotlk.openwow.com/npc=25417 is missing all of its spawns and combat spell and paths.
Npc http://wotlk.openwow.com/npc=25419 is missing all of its paths and combat spell.
Npc http://wotlk.openwow.com/npc=25415 is missing 2 paths and combat spells.

What is done here:
 - respawned the fire and water elementals
 - added the missing paths
 - added the missing combat spells
 - increased the normal damage of fire elementals (so they don't always lose to water elementals, they fight each other)

How it looks like:
![image](https://cloud.githubusercontent.com/assets/6797611/24038855/e31575ce-0b0b-11e7-8b8f-be6913a98b45.png)
![image](https://cloud.githubusercontent.com/assets/6797611/24038895/fd178fca-0b0b-11e7-8a53-b9d86f99f4f0.png)

**Comment by Teridan-dal-wow** [comment] 2017-03-17 10:24
Question: Is
``` sql
UPDATE `creature_template` SET `DamageModifier` = 1.2 WHERE `entry` = 25417; 
```
the correct way to increase the normal damage of a creature?

**Comment by Rushor** [comment] 2017-03-20 09:54
yep that's the only way we can increase damage for a single creature type with db currently (2-3 years ago we had min_damage and max_damage, but that was removed)

**Comment by Rushor** [comment] 2017-03-20 10:16
DB/Creature: Enraged Tempest, Raging Boiler and Boiling Spirit 

* respawned the fire and water elementals
* added the missing paths
* added the missing combat spells
* increased the normal damage of fire elementals (so they don't always lose to fire elementals, they fight each other)
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4592
* commit: 87d48d2b18fb8c8e0e90d688198c95b14e71eab3

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

Thanks Teridan :)

**Closed by Rushor** 2017-03-20 10:16 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-29 10:39
Works as intended on PTR.
