### ISSUE TITLE
[Hunter] Pets - Stable pet

### ISSUE THREAD

**Issue by Draculle** [dalaranwow/dalaran-wow#1378] opened 2014-03-23 14:09 UTC
Hello, i want to say that the Hunter's Pets are disappearing from their Stables, i have 2 others friends which they've lost like 3 times a pet from their stable w.o getting any option to regain it back, please check it out, thanks

**Comment by MrAndersonX** [comment] 2016-01-20 20:56
Also, the spirit beast dmg sucks, because one of their skills doesn't scale correctly ( Spirit Strike mostly ).

**Comment by MrAndersonX** [comment] 2016-02-13 13:49
The biggest bugs I found atm is : 
1) When using the ability Mend Pet, the tick heals generate a huge amount of threat. A.k.a bugged as fuck, needs a fix. Tbh when I use mend pet in dungeons and even in some raids my pet pulls higher threat than the tank.
2) Pet stats and buffs reset. Like, pet stat gain is fucking horrible. The hp, dmg etc is absolutely horrific. At 80 my pet is about 6-8k less hp than me unbuffed even tho it's talents/skills/stat gains should make it have way more stamina/hp than me. And always after it gets buffed, if u dismiss it, then resummon it, cause like I have to jump from somewhere or etc, it always loses the HP bonush gained from buffs ( kings, fortitude, gift etc ) and sometimes even the dmg/crit etc bonuses. This is a huge ass problem too atm.

**Comment by MrAndersonX** [comment] 2016-07-13 23:04
Well Lothloryen said : "Hello there,

The remaining fixes were applied yesterday night already.

Thank you very much."

But still, Wild Hunt is still bugged (no increase stamina or ap), same as pet stats, hit ,expertise, etc and Cobra Reflexes. So, what gives ?....

**Comment by Lothloryen** [comment] 2016-07-14 11:30
Not sure why you posted this statement here, there are other issues opened about the pet scaling (which should be working, test it again, please).

This issue is about pets disappearing from the stables.

Thank you.

**Comment by MrAndersonX** [comment] 2016-07-14 11:34
Yeah sorry, my bad. Well if the scaling works properly now, how come the stats of the pet are exactly the same as they were before the changelog ? Now I know I might be wrong, but I just don't understand it. If the scaling got recalculated, shouldn't the pet hp/ap etc increase based on the hunter's stats ? 
Again ,sorry for posting this here. I'll delete the previous thread.

**Comment by Lothloryen** [comment] 2016-07-14 11:35
Do not worry, I understand. Will continue with this here #2910

**Comment by MrAndersonX** [comment] 2016-07-14 11:37
Thank you Lothloryen, you're the best ! ^_^

**Comment by Edzero** [comment] 2016-10-22 18:13
http://imgur.com/zecJhnU

**Comment by Serpentsting** [comment] 2016-11-28 16:06
BUMP

**Comment by Rushor** [comment] 2016-11-28 18:06
Game/Handlers: Fix Stable Master - load dismissed pet to prevent unstabled pet "overwrite" current pet

* closes https://github.com/dalaranwow/dalaran-wow/issues/1378
* the issue from http://imgur.com/zecJhnU should no longer be reproducable with this fix
* commit: c1e53fa26b163f22e6f7be6c31bbd1dfc33496f0

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-28 18:06 UTC
Labels: Class - Hunter, On PTR, Priority - High

**Comment by TeridanDW** [comment] 2017-10-22 07:34
Hello after some tests on PTR ther results are:

 - This:
> Game/Handlers: Fix Stable Master - load dismissed pet to prevent unstabled pet "overwrite" current pet

seems to fix the issue as i wasn't able to reproduce the problem.

 - If player tries to replace the his current pet while the pet is missing with 1 from his stable list, the UI will bug and not allow the player to do the change. If the pet is present there is no issue.
Here is what i mean in short video:
https://www.youtube.com/watch?v=1_5b-SyW4QQ&feature=youtu.be
