### ISSUE TITLE
Fragment of Val'anyr (Super bugged drop rate)

### ISSUE THREAD

**Issue by ubobill** [dalaranwow/dalaran-wow#2247] opened 2015-02-16 13:58 UTC
We have officially hit 20 weeks now of full clears in Ulduar. Shaann is at 19 fragments. We are missing 3 Fragments for yogg 1 hardmode kills where they should be guarenteed. We also now havent seen a single fragment in 5 weeks. Can the loot tables be checked for this? This is a little absurd. At this rate we won't see a legendary mace until after TOGC. I have sent countless emails about this and have not heard any feedback.

**Comment by Winstrol** [comment] 2015-02-17 10:21
agreed, we been doing close to full clears since week 1 and still not even close to a mace (obsidius)

**Comment by Lildreamz** [comment] 2015-08-22 05:14
Slight correction to the original post, Fragments are 100% guaranteed to drop even on normal 4-Light Yogg-Saron. Proof : http://wowwiki.wikia.com/wiki/Yogg-Saron_(tactics)#toc  

Also note that in the patch notes, no changes have ever been made to the drop rates of Fragments for Yogg-Saron Normal or Hard-mode.

**Comment by Lothloryen** [comment] 2015-10-23 08:02
Hello there,

It is not super bugged, the drop rates are correct. However, Yogg-Saron doesn't drop them always - this is not like it should be. Deploying a correction.

Thank you.

**Comment by Drawsblood** [comment] 2015-12-08 21:49
Still not fixed, drop rate is horrid. Please "deploy a correction" faster. Almost finished now with this terribad drop rate...

**Comment by Drawsblood** [comment] 2015-12-11 00:06
The drop chance of Fragments is still insanely bugged. Lothloryen mentioned a fix in the article #2247 however no fix has ever been deployed, and it seems they don't care to fix it. We run Ulduar 25 twice a week for 2 different members and at this point we are lucky if we even get 1 Fragment. In the article mentioned you say that the drop rate is correct, this is an absurd statement. The first comment of this wowhead article explains the drop rate: "http://www.wowhead.com/item=45038/fragment-of-valanyr#comments". I have run this for months now and have yet to see a fragment of Yogg or Vezax. The article also mentions that up to 2 fragments should be dropping from Hodir hardmode, 1 from each cache. I understand that Lothloryen is busy with all of the current issues, however a legendary item should be one of the top prios, even if it is from Ulduar.

Draws

**Comment by Drawsblood** [comment] 2015-12-27 21:33
4 Fragments in the last 2 months. 2 weeks in a row with not a single fragment, thanks #dalaranwow you're the best!

**Comment by Lildreamz** [comment] 2015-12-28 07:07
Indeed, could we get an update about hot fixing this issue so far I'm sitting at 5 Fragments I'm owed from Yogg with proper screen shots or VODs provided in all instances and I can't get a reply to any emails or tickets which go as far back as 5 months ago.

**Comment by AgeAgainst** [comment] 2016-01-04 05:24
Would love to see an update on this as well.   Our last two fragments dropped from FL and Kologarn.  Been downing Yogg every week since Lothloryen said he was deploying a correction and not one single fragment from Yogg.  We've been sending in screenshots of no fragments on Yogg and no hard mode loot on General Vezax since May and we recently got an answer - "We'll get to it soon"

**Comment by kikomir** [comment] 2016-01-12 21:38
Just out of curiosity, are you guys on horde or alliance side? In my experience (raiding on both factions) I've seen alliance runs dropping 2-3 fragments in a single run but not the same on horde. I've also seen people wielding the mace so they were really lucky I guess. Bear in mind this is just my personal observation, not necessarily a fact.

**Comment by Drawsblood** [comment] 2016-01-12 22:03
Horde side. Of course people have the mace.. we are saying the drop rate is bugged (too low). Yogg is supposed to have 100% drop rate, never seen him drop a fragment once, even though Loth mentioned in this article that a "fix is being deployed". Hodir is supposed to be able to drop 2 fragments (One from each cache if killed hardmode), however on this server if you kill Hodir HM all of the loot is contained in the HM Cache, not being seperated making it impossible to ever get 2.

**Comment by Drawsblood** [comment] 2016-01-19 17:43
@Lothloryen Are you sure you even added Fragment of Val'anyr to Yogg's loot table? I'm trying to find the code to link to you so you can fix it already after 3 months with no fix implemented. Or can you message in-game like you said you would? Thx, Draws.

**Comment by Sigwastaken** [comment] 2016-01-21 22:19
We were told two months ago by the GMs that we would be given frags for at least each of our Yogg kills. The drop rates are still very low, we have still never seen one from Yogg, and we have not received a single Fragment from the GMs. Our emails are being completely ignored.

**Comment by Drawsblood** [comment] 2016-01-21 23:42
@Sigwastaken Yeah good luck bud, I was told the same 5 months ago and here I am, thank fuck im finishing this reset (hopefully), then just gotta play the waiting game for a response from GM cause the quest to complete it is bugged.

**Comment by Drawsblood** [comment] 2016-01-23 17:35
@Lothloryen Check out the code linked in this post: https://github.com/TrinityCore/TrinityCore/issues/10631 and see if it will fix the quest item working properly.

**Comment by ashido96** [comment] 2016-06-30 03:38
Yogg'Saron no longer has a 100% chance to drop a fragment, we haven't seen one in a couple months during our weekly runs.

**Comment by Rushor** [comment] 2016-11-14 09:02
DB/Creature: Yogg Saron - Add Fragment of Val'anyr to 25-man lootmode

* closes https://github.com/dalaranwow/dalaran-wow/issues/2247
* item was added with a 100 % chance now
* commit: 4e8eb5091e3084119e24e4ac2273d737fa5dc0c8

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-14 09:02 UTC
Labels: Items, On PTR

**Comment by TeridanDW** [comment] 2017-04-06 13:36
> item was added with a 100 % chance now

Works as intended on ptr.
