### ISSUE TITLE
[Combat Bug] Character

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4799] opened 2017-07-10 14:48 UTC
When you're out of an certain fight at the top of your screen it still shows that you're in combat which is not supposed to be like that..

<a href="http://nl.tinypic.com?ref=2h7kp6r" target="_blank"><img src="http://i66.tinypic.com/2h7kp6r.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ashido96** [comment] 2017-07-12 01:43
Yes combat bugs are known issues across every single private server. What situation were you in, which mob caused it, was it a certain spell that did when interacting with a certain NPC (yes this was the case once), is the mob you were fighting with currently evading, is the mobs corpse mysterisouly targeting you and thus still need to be killed by aoe (this one was a long ass time ago)? Your bug report literally gives the developer NOTHING to fix.

**Comment by koray053** [comment] 2017-07-15 14:18
@ashido96 Well.. it happens everywere almost its just a small chance after a mob goes back to hi's spot that you're still in combat

**Comment by Rushor** [comment] 2017-07-29 09:12
-- Duplicate Issue --
Your issue posted here is a duplicate of issue: https://github.com/dalaranwow/dalaran-wow/issues/1312 (< click on this and you will be redirected to the original posted issue). 

Your issue posted here is a duplicate of issue: https://github.com/dalaranwow/dalaran-wow/issues/1896 (< click on this and you will be redirected to the original posted issue).

**Closed by Rushor** 2017-07-29 09:12 UTC
Labels: Duplicate / Invalid Report
