### ISSUE TITLE
[NPC] Saltscale Oracle, Saltscale Tide Lord, and Saltscale Forager unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1217] opened 2014-02-17 00:06 UTC
Saltscale Oracle (http://wotlk.openwow.com/npc=873), Saltscale Tide Lord (http://wotlk.openwow.com/npc=875), and Saltscale Forager (http://wotlk.openwow.com/npc=877) are not casting any of their abilities.

**Comment by Rushor** [comment] 2016-11-14 18:37
DB/Creature: Add abilities for Saltscale Tide Lord, Saltscale Oracle and Saltscale Forager

* closes https://github.com/dalaranwow/dalaran-wow/issues/1217
* commit: dd4461d7705b46b0d27e292a6f0336b8fbb2f562

1,0,0,0,0,0,0,0,"Saltscale Tide Lord - Out of Combat - Cast 'Frost Armor'"),
,"Saltscale Tide Lord - Between 0-20% Health - Cast 'Frost Nova' (No Repeat)"),
0,0,0,0,0,0,"Saltscale Tide Lord - In Combat - Cast 'Frostbolt'");

,0,0,0,0,0,0,"Saltscale Oracle - In Combat - Cast 'Lightning Bolt'"),
0,"Saltscale Oracle - Between 0-30% Health - Cast 'Healing Wave' (No Repeat)");

,"Saltscale Forager - In Combat - Cast 'Poison'"),
,"Saltscale Forager - In Combat - Cast 'Rend'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-04 10:55
This is not on ptr.

**Comment by Rushor** [comment] 2018-03-23 14:02
reapplied with https://github.com/dalaranwow/principal/commit/a0e32df68dfea8196089cb9631f94e4404f11eb7

**Closed by Rushor** 2018-03-23 14:02 UTC
Labels: Area - Classic
