### ISSUE TITLE
[Quest][Classic] List of Isle of Quel'Danas Issues

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1657] opened 2014-06-03 03:02 UTC
It seems that there are so many issues with the Isle of Quel'Danas that they need their own category because when I tried looking them up here, all I found were scattered fragments and pieces.

Quest: Distraction at the Dead Scar, Bombs Don't Work
https://github.com/dalaranwow/dalaran-wow/issues/719

Quest: Intercept the Reinforcements
https://github.com/dalaranwow/dalaran-wow/issues/1474

NPC: Dawnblade Hawkriders have infinite range and attack players instead of NPCs
https://github.com/dalaranwow/dalaran-wow/issues/730
(This issue also affects Dawnblade Marskmen [http://www.wowwiki.com/Dawnblade_Marksman])

Item: Bloodberry Elixir and Righteous/Blessed Weapon Coating don't work outside the dungeon. They can be applied anywhere from classic to Northrend. Should only work on the specified places in the tooltip (the dungeon and the whole isle)
https://github.com/dalaranwow/dalaran-wow/issues/769

The Abyssal Flamewalker (http://www.wowwiki.com/Abyssal_Flamewalker) currently has no model and no physical presence, but still attacks players with Rain of Fire.

**Comment by Demlock** [comment] 2015-02-16 19:40
Actually, part per part build was only made for initial phases of Isle invasion. Once this phase is over, all players have an entire area avilable to them. So this part is actually working as intended

**Comment by Rushor** [comment] 2017-02-26 11:50
> Also the whole part per part build up is not working, you instantly got acess to the landing area, aswell as to the armory, Inn or gold dailies.

The whole stuff was removed with WotlK. so all player are able to see everything from the beginning.

**Comment by Rushor** [comment] 2017-02-26 13:30
I will fix #769 and #730 in the separatedt linked issues.

DB/Creature: Update model of Abyssal Flamewalker

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1657
* commit: 1d2c34dea8b7586599ee2b7d65dc26a63bb75aac

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-02-26 13:30 UTC
Labels: Area - Classic, General - Quests
