### ISSUE TITLE
[Death Knight] Master of Ghouls 

### ISSUE THREAD

**Issue by Warthug** [dalaranwow/dalaran-wow#1815] opened 2014-08-16 23:40 UTC
Spell ID: http://www.wowhead.com/spell=52143/master-of-ghouls

What's the issue: I'm still having 100% control over my ghoul while im on a different spec such as frost.

How does it happen: Most likely when i have my pet summoned and switch spec's from unholy to frost to join a battleground or arena. 

How should it work: It shouldn't allow me to control the ghoul without Master of Ghouls.

Picture related: ![wowscrnshot_081614_183819](https://cloud.githubusercontent.com/assets/6452694/3943381/5a9f964e-259d-11e4-82f8-6c06dabbdfaf.jpg)

**Comment by Rushor** [comment] 2017-03-09 21:46
Game/Player: DK - Remove permanent ghul from petlist after teleport and don't allow to use it without Master of Ghouls talent 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1815
* commit: 1bd5592225e035312e45b8738b51c9cb1073ca04

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2017-03-09 21:46 UTC
Labels: Class - Death Knight, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-21 09:33
Works as intended on PTR.
