### ISSUE TITLE
[NPC]Caster Mobs

### ISSUE THREAD

**Issue by mrrosh** [dalaranwow/dalaran-wow#3456] opened 2016-06-14 20:47 UTC
**Description**: Caster mobs incorrect behaviour.

**Current behaviour**: The caster creatures cast their spell and right after runs towards the attacker.

**Expected behaviour**: The caster mobs should stand still and cast the spells, and in case the attacker gets in melee range, the mob should run back and start casting again.

**Steps to reproduce the problem**:
1. Find a caster mob.
2. Aggro it from a distance.
3. Watch how it fights totally wrong.

**Include proofs for this behaviour**

https://youtu.be/YwU_JVGUpr8?t=37s

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

In my case: http://wotlk.openwow.com/npc=16522

**Comment by Coltari** [comment] 2016-08-20 10:13
I've also encountered this issue, most recently with Boulderfist Magus in Arathi Highlands:

http://www.wowhead.com/npc=2567/boulderfist-magus

They continue their patrol routes whilst in combat and cast whilst moving as normal.

**Comment by Rushor** [comment] 2016-11-12 10:55
DB/SAI: Add CMC for Surveyor Candress and Boulderfist Magus

* closes https://github.com/dalaranwow/dalaran-wow/issues/3456
* this should prevent the strange combatmovement. The creatures should always cast their spell and stay on place if they have enough mana.
* commit: 8f8aac7ba60acd64613be9ac1f7aa25b158c3fee

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-12 10:55 UTC
Labels: Mechanics, On PTR

**Comment by warcraftgeekygamer** [comment] 2017-02-28 23:28
On February 28, 2017 I experienced this very same issue with [Hillsbrad Councilman](http://wotlk.evowow.com/?npc=2387). This particular Humanoid will cast [Frostbolt](http://wotlk.evowow.com/?spell=20806) at the player when aggro'd and continue to walk. This Humanoid is a requirement for quest [Battle of Hillsbrad](http://wotlk.evowow.com/?quest=532) in Hillsbrad Foothills.

**Comment by Rushor** [comment] 2017-03-01 09:10
that creature already has CMC movement on PTR.

```sql
Hillsbrad Councilman - In Combat CMC - Cast 'Frostbolt'
```

**Comment by TeridanDW** [comment] 2017-04-01 11:38
Works as intended on ptr.

**Comment by warcraftgeekygamer** [comment] 2017-07-24 20:30
This is still an on-going issue on Algalon. This time, the mob is [Vile Familiar](http://db.vanillagaming.org/?npc=3101) found both outside and inside the Burning Blade Coven (cave). This cave is found in the starting area of Durotar for Orcs and Trolls (Valley of Trials).
