### ISSUE TITLE
[Quest][Ouland] Fires Over Skettis

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1145] opened 2014-01-29 12:45 UTC
http://www.wowhead.com/quest=11008

Once you have used the dynamite to blow up eggs, the eggs disappear like they should. However if you then use the dynamite on the same spot (where the eggs were, but aren't there anymore because you already destroyed them) you still get credit as if the eggs were still there and you destroyed them (again).

**Comment by Rushor** [comment] 2016-11-29 11:17
DB/Quest: Fires Over Skettis - Despawn trigger on spellhit

* closes https://github.com/dalaranwow/dalaran-wow/issues/1145
* commit: 1b02c33cf2970c261715cd9349aae02ad9823af4

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-29 11:17 UTC
Labels: Continent - Outland, General - Quests, On PTR
