### ISSUE TITLE
[Rise Dead/Risen Ghoul] (Unholy) Ghouls base strength

### ISSUE THREAD

**Issue by darkczes** [dalaranwow/dalaran-wow#1586] opened 2014-05-06 18:47 UTC
Ghouls now have a base strenght of 22 when they should have a base AP of 1167 and a base Str of 331. Link and pic below for confirmation.

"ghoul facts:

-base ap of 1170 base strength 330
-100% of personal haste goes to the ghoul too (at some cases double dips)
-temporary buffs at dk (fc etc.) benefit ghoul
-1 str equals 1 ap (what a pity)
-no benefit from dk ap
-ghoul benefits from temporary ap buff (abo might f.e.)
-14 ap equals 1 dps

Ghoul str = DK str \* (0.7 + RD + 0.4) (third summand is the glyph; RD ravenous dead = 0.6)
Ghoul ap = Ghoul str - base str + base ap"

ss(working):
http://s17.postimg.org/hxt53gqgf/Bez_n_zvu.png

Link:
http://www.mmo-champion.com/threads/642804-Ghoul-math-help-a-brutha-out?p=6180794&viewfull=1#post6180794

**Comment by AraelWindwings** [comment] 2015-02-08 14:21
http://www.wowwiki.com/Risen_Ghoul

Ghouls receive 2 attack power per point of strength over 10.

**Comment by AraelWindwings** [comment] 2015-02-08 21:37
At level 80, ghouls have 13380 base hp.

    Like all class pets, ghouls' base stats scale with their level.
    At level 80, ghouls have 13380 base hp.
    Ghouls receive 45% of their master's stamina.

Level 80 DK with 1.468 Stamina, the ghoul have just 12.382 HP.

The base HP is Very low. It has very low HP now.

**Comment by Rushor** [comment] 2016-12-01 09:46
DB/Pet: Risen Ghoul - Add basestats

* closes https://github.com/dalaranwow/dalaran-wow/issues/1586
* 331 basestrength  was added now
* commit: c3215dbb6317b49890b4f7783975fbf23d18aece

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-01 09:46 UTC
Labels: Class - Death Knight, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-21 09:41
Works as intended on PTR.
