### ISSUE TITLE
[Quest][Northrend] It's All Fun and Games

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#549] opened 2013-08-11 22:43 UTC
**Quest It's All Fun and Games** - H _(ID:12892)_ / A _(ID:12887)_
- **Issue present:** You are unable to attack the NPC **The Ocular** _(ID:29747)_ with **Eyesore Blaster** _(ID:41265)_ because it keep saying this: **OUT OF RANGE** .
  This is probably because of the Pathfinding System issue.
  Also, I noticed that The Eye is actually not stable on his own spot where it should but simply drops down after you reach it. Also, _29790_ - **The Ocular - Eye of Acherus Exterior Shell** which is purely cosmetic part also falls down with the eye. It is non-triaggable by anything.

![image](https://f.cloud.github.com/assets/5054924/944761/d3e2a9f0-02d6-11e3-912b-a7a3f2ced67d.png)
![image](https://f.cloud.github.com/assets/5054924/944763/eed62e44-02d6-11e3-8da4-e84da920fbcc.png)
![image](https://f.cloud.github.com/assets/5054924/944765/0cdb2412-02d7-11e3-8dbc-d7483e25a45b.png)
- **The Ocular** has to stay up at any given point.

. **How it should work:** You are supposed to destroy **The Ocular** using **Eyesore Blaster** while mounted and the  **The Ocular** should resist and attack you with the following spells:  _Deathly Stare_. NPC also cannot move since it's perma stuck there on top of the building.

**Deathly Stare** - _55269_

---

**Video of how it should work:** http://www.youtube.com/watch?v=hXQL6QRHHNg

---

http://wotlk.openwow.com/npc=29747
http://wotlk.openwow.com/npc=29747
http://wotlk.openwow.com/quest=12892
http://wotlk.openwow.com/quest=12887

**Comment by AgeAgainst** [comment] 2015-01-03 12:39
Tsuwamono's tip worked flawlessly.

**Comment by Fuzilumpkinz** [comment] 2015-04-04 17:36
He is stuck inside the Shadow Vault and when you try to aggro him he will not attack you so I cannot do as others have and just pull him up basically and then kill him in the right location.  May just be a slight server issue that would fix itself on restart though.  Not sure

**Comment by Rushor** [comment] 2015-04-04 17:41
change inhabittype to 4 + add a fly aura should solve the problem

**Comment by irodeyourmom** [comment] 2015-07-30 21:59
He is stuck in the shadow vault currently, and I can not kill him, he resets his health every 10 seconds. Now I can't unlock Ebon Hold rep. And with the currently GM wait times, This is never going to get taken care of. I still have a billing issue open for 5 months ago.

**Comment by oberinjo** [comment] 2015-08-08 12:36
he is still inside chamber, can you reset it?

**Comment by KantorG** [comment] 2015-08-30 11:40
can you fix it please :)

**Comment by Zeffx** [comment] 2015-09-13 12:52
The quest is still not working, The eye is nowhere to be seen. /target dose not work either.

**Comment by Jrizzle23** [comment] 2015-10-22 02:29
The Ocular is still resetting his hp after one shot and you can not kill him

**Comment by swiftdeath** [comment] 2015-10-22 10:51
Yeap, still bugged

**Comment by AgeAgainst** [comment] 2015-11-10 21:15
As of 10 Nov, unable to even target Ocular.

**Comment by PolarCookie** [comment] 2016-01-10 04:01
As of 10. January, he's inside on the ground floor of the vault, he has the savage combat debuff on him.

**Comment by Lothloryen** [comment] 2016-05-03 17:41
This quest should be working properly now, several improvements done.

Thank you.

**Comment by Golganeth** [comment] 2016-05-20 13:50
The NPC falls down then goes back up once you engage him. It keeps regenerating HP so you can't complete the quest

**Comment by DalaranLudste** [comment] 2016-06-03 11:00
One can complete this quest alone at the moment. I kept flying around the eye, pretty close, stopping when gun is off cooldown to fire. The Eye hits for about 700 HP roughly once per cooldown.

**Comment by Rushor** [comment] 2016-06-03 11:08
todo: increase aggro range, add flying aura

note: the dmg is counted from you max-healthpoint, so there will be no static damagevalue

**Comment by Rushor** [comment] 2016-06-04 17:10
* The Ocular should no longer drop below the map
* The Ocular should attack faster

**Comment by Golganeth** [comment] 2016-06-04 19:05
Still drops below the ground all the way to Shadow Vault or to the closest solid ground (sometimes)

https://i.gyazo.com/b1fd4077b432cf6b238b1e577df50c1f.png

When that happens you can damage The Ocular but it will regenerate HP instantly.

**Comment by MrAndersonX** [comment] 2016-11-09 20:37
Yeah, it has some sort of insta hp regen if u don't pull it to the top where u can use the quest item. It still can kill you very easily due to the long cd of the quest item, and it's big dmg from it's ability.

**Comment by Rushor** [comment] 2016-11-09 20:55
we already added all kind of flying abilities :(

**Comment by MrAndersonX** [comment] 2016-11-09 21:07
Well, it is doable. Just gotta pull the eye to the top and spam the quest item before he kills you.

**Comment by Rushor** [comment] 2016-11-24 14:12
alright! i added the possibility, that the creature (eye) should always return to it's spawnpoint out of combat. With this addition it will no longer stay on the ground after respawn.

**Comment by Rushor** [comment] 2016-11-24 14:13
DB/Quest: It's All Fun and Games - Return to spawnpoint out of combat + change inhabittype

* closes https://github.com/dalaranwow/dalaran-wow/issues/549
* comit: 538986b20f2c2aca755c4dec2d19149c6138ad51

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 14:13 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:00
Works as intended on PTR.

Note: Player must be close to the eye in order to get in combat with him.
