### ISSUE TITLE
[Warlock] pet (Felguard) takes permanent fire damage no matter what

### ISSUE THREAD

**Issue by onijack** [dalaranwow/dalaran-wow#2603] opened 2015-07-06 05:39 UTC
It started when I was doing Obsidian Sanctum (10m). I was standing near the lava, and summoned my Felguard. The Felguard was summoned on top of the lava and since then, he keeps taking ticks of fire damage (there's no debuff on him). I've tried relogging, dismissing and resummoning, letting it die, respeccing, but nothing works, the Felguard keeps taking damage as if he were on lava no matter what, anywhere I go making it basically impossible to use him.

**Comment by adytzyca** [comment] 2015-07-07 09:36
You can get that "fixed" by walking into the lava in OS with ur pet

**Comment by warcraftgeekygamer** [comment] 2015-07-08 02:31
@adytzyca 

That is not the point. Players should not have to walk back into OS with a pet, allow them to walk into the lava for a "fix". That's like telling someone with a flat tire to drive over sharp objects for them to have their tire inflated.

**Comment by Vaxsysl** [comment] 2015-07-08 17:05
Well IMO, if fixing the bug is making the pet go into the same lava again, just form 2 man raid group with anyone, enter, dip in, fix the bug. Why pester the staff with simple solutions?

**Comment by warcraftgeekygamer** [comment] 2015-07-11 02:23
@Vaxsysl 

My point still stands. You should not be forced to run your pet back into lava for a "fix". It's absurd. This is not a simple solution - it is a bug and should be resolved when the dev's can get around to it. Besides....as a retort to your question -- why pester players with having to form a raid just so you can "fix" your pet?

Seems pretty silly to me.

**Comment by Vaxsysl** [comment] 2015-07-11 02:50
/shrug, I have no problems with that. I often ask someone random / global / guild if anyone has time for short raid group if I want to setup an addon or enter a raid instance to retrieve my corpse or whatnot. There's a lot of players, not so many developers or game masters to help with the issue. And yes, it should be resolved. Just like other thousands of issues :) hence my previous reply. This is something that players can fix on their own in a very simple manner. There's enough issues open to hire a team of developers. It's a manner of etiquette in my book, and it has both sides to it. Anyways, these are not forums for discussion, and we both said our sides. See you ingame, stranger.

**Comment by warcraftgeekygamer** [comment] 2015-07-12 18:30
@Vaxsysl 

I never said that this issue should not be resolved. What I disagree with, is that you're asking others to run back into OS in order to "fix" the problem. Hopefully the dev's will resolve this issue when they have the time.

Anyways....hoping the dev's can resolve this when the time becomes available to them.

**Comment by Rushor** [comment] 2016-06-07 07:29
liquid auras should not be saved :/

**Comment by Rushor** [comment] 2016-12-02 13:02
Game/Auras: Some liquid auras cannot be saved 

* closes https://github.com/dalaranwow/dalaran-wow/issues/2603
* commit: 2365e539cc3adf4a3ebb1b4c6f9de025657904d0

these auras:
57634: // Magma, CoA Black / Chamber
42201: // Water, Hyjal Past
37025: // Water, Coilfang Raid
36444: // Water, Lake Wintergrasp
28801: // Slime, Naxxramas

can no longer be saved on pets

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-12-02 13:02 UTC
Labels: Class - Warlock, Fixed - Waiting for PTR Update

**Comment by TeridanDW** [comment] 2017-10-20 19:20
Works as intended on PTR.
