### ISSUE TITLE
Quest: Matis the Cruel

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#18] opened 2013-07-21 03:50 UTC
The Flare Gun which you have to use on him doesn't work.
Quote from WoWhead: 

What you're looking for is a blood elf on a horse. Once you find him, inch up to him slowly then use the flare gun. A hunter will appear, let him get aggro then help him fight.

Matis paths on the road from 42,44 to 21,54.

There is also an event missing after you turn in the quest

http://www.youtube.com/watch?v=sDxrJsum5O4

**Comment by DalaranLantri** [comment] 2016-06-25 11:57
Matis the Cruel currently has a gattling gun and will use his ability Shoot 6-7 times a second, making it extremely hard for players to get close for the flare gun, and also just players meeting him wandering around get oneshot.

[13:53:00]Matis the Cruel's Shoot his Lantri for 31 Physical.
[13:53:00]Matis the Cruel's Shoot his Lantri for 31 Physical.
[13:53:00]Matis the Cruel's Shoot his Lantri for 38 Physical.
[13:53:00]Matis the Cruel's Shoot his Lantri for 36 Physical.
[13:53:00]Matis the Cruel's Shoot his Lantri for 39 Physical.
[13:53:00]Matis the Cruel's Shoot his Lantri for 38 Physical.

**Comment by Rushor** [comment] 2016-11-11 12:58
DB/Quest: Reinsert script for quest: Matis the Cruel

* closes https://github.com/dalaranwow/dalaran-wow/issues/18
* commit: 108b253d5296926d488af24fda4591c3b8daf356
* commit: 79be78643d611bec6e39585091685e2f7937d418
* the shoot spell will be repeated now only between 6-8 seconds

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-05 07:54
Hello, quest is completeable now with the help of the creature summoned by item http://wotlk.openwow.com/item=24278, however there few issue that should be fixed before pushing to live:
 - there is a missing condition of using item http://wotlk.openwow.com/item=24278 , should be useable only when you have npc http://wotlk.openwow.com/npc=17664 as target
 - the npc http://www.wowhead.com/npc=17853/tracker-of-the-hand should be summoned around the player and not on top of him
 - the npc http://www.wowhead.com/npc=17853/tracker-of-the-hand should engage npc http://wotlk.openwow.com/npc=17664 on summon (currently it doesn't)
 - at ~30%hp npc http://wotlk.openwow.com/npc=17664 should "die" and after few secs appear on mount and again after few second he and all http://www.wowhead.com/npc=17853/tracker-of-the-hand should despawn (currently he doesn't die and these 2 creatures continue to fight until 0% hp)
 - quest credit should be given to all players in the threatlist of creature http://wotlk.openwow.com/npc=17664 when he reach 30% hp

**Comment by DemaciaMaggotPie** [comment] 2017-06-01 13:16
Hello, just tried doing that quest today on Algalon. Matis still has the "gatling gun" mentioned by @DalaranLantri. He even could keep "Shooting" while feared by my Psychic Scream. The Tracker of the Hand didn't help either, but would most likely haven't changed much.

**Closed** 2017-12-09 17:06 UTC
Labels: Area - Classic, General - Quests, Works - but it needs improvements.

**Comment by Simplyevey** [comment] 2018-01-09 17:48
I just tried this quest and he never surrenders.  When using the flare gun, the tracker just kills him.  Tried the quest several times with the same result.

**Comment by Richitzer** [comment] 2019-01-04 03:36
Matis still has a gatling gun, about 20 damage every 1/10th of a second or so. Was able to complete quest otherwise (tracker "captured" him).
![matis gatling gun](https://user-images.githubusercontent.com/46364205/50672715-d04a5c00-0fa7-11e9-925b-151d27492f67.PNG)
