### ISSUE TITLE
[Quest][Northend] No Place to Run

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#871] opened 2013-10-02 20:12 UTC
Quest is completable, but the NPC Destructive Ward (the object you're supposed to defend in the quest) should be a stationary object, unable to move.
Currently it follows the player as if it were a pet.

**Comment by Rushor** [comment] 2016-11-09 18:38
DB/Quest: Fixup quest No Place To Run

* closes https://github.com/dalaranwow/dalaran-wow/issues/871
* NPC Destructive Ward wil no longer follow/assist the player
* commit: 6ffa62268267cb655d4725cb884c1f41fdd16eca
* commit: 16b109cb9748d0e9be43bb7a0a3c066b90d3f1ff

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ImprezaWoW** [comment] 2016-11-23 17:34
After you spawn Destructive Ward, nothing seems to be happening.

**Comment by Rushor** [comment] 2016-11-23 17:47
http://wotlk.openwow.com/quest=12261

**Comment by ImprezaWoW** [comment] 2016-11-23 17:49
There is no-one to protect the ward from - no mobs spawn around it trying to attack, and the ward does not charge.

**Comment by Rushor** [comment] 2016-11-23 17:54
let me recheck it, i think the db update wasn't applied or the root setting was changed

**Comment by Rushor** [comment] 2016-11-23 18:07
DB/Quest: Fixup quest No Place To Run

* closes https://github.com/dalaranwow/dalaran-wow/issues/871
* commit: 908d21dc8f3dad74f022103d9115a95afa84c714

It should work better now. @Lothloryen i hope 6ffa62268267cb655d4725cb884c1f41fdd16eca and 16b109cb9748d0e9be43bb7a0a3c066b90d3f1ff are both on ptr (note the update from: sql/updates/world/3.3.5/2016_09_09_01_world.sql does not need to be applied :) )

**Closed by Rushor** 2016-11-23 18:07 UTC
Labels: Continent - Northrend, OLD - Miscelaneous, Quests

**Comment by JaneJinx** [comment] 2016-11-27 02:22
I can drop the ward and it stays in place. But nothing happens. I can keep dropping wards every minute, but there is nothing to defend it from. Quest seems unable to be completed.

**Comment by Rushor** [comment] 2016-11-27 08:40
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by JaneJinx** [comment] 2016-11-29 04:17
Thank you very much for your response.

**Comment by Aridam** [comment] 2017-11-28 02:40
It's been a year for this report, so I'm posting to update in case: Quest works fully -- just completed it -- albeit the Destructive Ward _still_ follows the Player who summoned it.
