### ISSUE TITLE
[Quest][Outland] Torching Sunfury Hold

### ISSUE THREAD

**Issue by Stealthmate** [dalaranwow/dalaran-wow#1856] opened 2014-09-08 23:28 UTC
Quest objectives:
Sunfury Ballista destroyed - 4
Sunfury Tents destroyed - 4

How it should work:
You kill Sunfury Flamekeepers and loot a Flaming Torch from them (works). Then you use the torch near a ballista/tent.

How it works now:
Looting the torch is fine, but you can use it anywhere (even when NOT near a tent/ballista) and using it near a ballista/tent doesn't count for the quest objective.

Links:
http://www.wowhead.com/item=28550
http://www.wowhead.com/quest=10233

**Comment by Demlock** [comment] 2015-07-18 21:19
Did it moments ago. As far as I am concerned, this quest works as intended.

**Comment by Rushor** [comment] 2016-11-29 10:09
this was fixed with https://github.com/TrinityCore/TrinityCore/issues/11780

**Comment by TeridanDW** [comment] 2017-04-03 09:58
Quest is completeable now, the quest dummies are set on 5 mins respawn timer, however the quest has very poor visuals and needs to be reworked.
 - Players don't the 1 of the visuals when they use the torch
 - The fire animation is removed after few second while the quest dummie stay dead and if other player comes and uses the torch on same dummie he won't get credit which feels like broken quest.

Visual elements needs to be checked on retail, will come back to this quest soon.

**Closed** 2017-11-30 14:39 UTC
Labels: Area - Outland, Fixed - Waiting for PTR update, General - Quests, Works - but it needs improvements.
