### ISSUE TITLE
Primed Key Mold

### ISSUE THREAD

**Issue by Kirishiki** [dalaranwow/dalaran-wow#3712] opened 2016-09-13 20:49 UTC
Primed key mold was dropped today from Coilfang emissary (rare mob) in zangamarsh and gm told its a bug. Its a quest item for quest i didnt even have.

**Comment by Golganeth** [comment] 2016-09-20 23:02
Confirmed.

**Comment by Rushor** [comment] 2016-11-10 19:18
DB/Item: Primed Key Mold - should not drop by Coilfang emissary

* closes https://github.com/dalaranwow/dalaran-wow/issues/3712
* commit: b09819b5aaa0c7bc9a2854231c52719d673376b6

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-10 19:18 UTC
Labels: Continent - Outland, Items, On PTR, Priority - Low

**Comment by TeridanDW** [comment] 2017-03-31 12:09
Works as intended on ptr.
