### ISSUE TITLE
[Quest] "Threat From Above"

### ISSUE THREAD

**Issue by 7193224** [dalaranwow/dalaran-wow#2512] opened 2015-06-11 17:00 UTC
the quest requires that we kill one drake and three mobs, the mobs are supposed to show up while we fighting the big drake, but sometimes no mobs respawn and sometimes there r only two, lol

**Comment by Spruitje** [comment] 2015-06-21 20:33
Actually, the mobs seem to be riding the drake (don't know if that's right or no) and occasionally 1 (or more) jump off just before or during the fight and runs off. Once i had it happen that 1 mob ran off early/too far and despawned, so i had to wait for the whole group of drake+mobs to respawn just to get that 1 extra mob

Must add though that ToC dailies seem to be changing on a daily basis so the issues you encounter one day might be gone the next, or issues surface where none were encountered before

All of the dailies seem ok (or at least doable) after any server restart/reset and bugs may appear later as time passes
I always rushed to do those bugged dailies i couldn't finish before when a restart/reset occurred 

My guess id they are still ironing out the small issues on the ToC dailies and all will get a perma-fix soon

**Comment by M0dinstaller** [comment] 2015-08-02 07:43
Depending on where Chillmaw is when it dies, the adds can jump down at the bottom of the world instead of on the ground next to you. At the end of the day after a good bunch of people have failed the quest because of that, if you have detect humanoid you can see approximately where it bugs and where it doesn't.

**Comment by Rushor** [comment] 2016-11-24 21:33
DB/Quest: Threat From Above - Chillmaw will spawn the Cultists propperly now + fix time bomb

* closes https://github.com/dalaranwow/dalaran-wow/issues/2512
* the cultists will be summoned at 80, 50 and 30 % Hp
* also fixed the bomb ability from the cultists
* commit: ce1defbc0fd58d486c059fdd59ca51e0be330fed

![GitHub Logo](http://i.imgur.com/u6h6jR4.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-24 21:33 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by TeridanDW** [comment] 2017-10-29 09:40
Works as intended on PTR.
