### ISSUE TITLE
Oculus - Mage-Lord Urom - Teleport issues

### ISSUE THREAD

**Issue by swiftdeath** [dalaranwow/dalaran-wow#5205] opened 2017-12-25 11:56 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When Mage-Lord Urom teleports, he should start casting an empowered arcane explosion and emote 'A taste... Just a small taste.. of the Spell-Weavers power!' or 'So much unstable energy.. But worth the risk to destroy you!'. What happens now is that he teleports, emotes and then resets and returns to his original position, with the health % he teleported with. The group can afterwards simply engage him and nuke down the last few remaining % of health.

I have seen this happen with various group setups. All of them which had DoTs on him ticking.

**Expected behaviour**: Tell us what should happen instead
He should teleport, emote and cast the empowered arcane explosion hitting everyone not hiding behind a pillar. Afterwards he teleports to the highest aggro target and the fight continues.

**Steps to reproduce the problem**:

1. Engage Mage-Lord Urom and wait for him to teleport;
2. Let him teleport and wait for him to reset;
3. Engage him instantly when he returns to his original position.

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=S2_gJMhy0ik this video shows it being bugged on retail as well. as in the Mage-Lord resetting to FULL HP after teleport. It works after the 2nd teleport.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Mage-Lord Urom https://wotlk.evowow.com/?npc=27655

**Include Screenshots from the issue if necessary**

**Comment by thanhtotti** [comment] 2018-02-26 05:24
Confirmed, pretty frustrated to deal with. It should be marked as High priority since this is an end game dungeon imo.

**Comment by Lothloryen** [comment] 2018-02-26 16:55
Hello there,

Thank you for the report, the boss has been re-scripted, it will be on the live realm after the next scheduled maintenance.

**Closed by Lothloryen** 2018-02-26 16:55 UTC
Labels: Area - Instances
