### ISSUE TITLE
[NPC] Dredge Crusher and Sand Dredger gives wrong skinning loot

### ISSUE THREAD

**Issue by cardk** [dalaranwow/dalaran-wow#2770] opened 2015-08-09 19:03 UTC
The two mobs mentioned in the title gives light leather when skinned. They are 54-59 mobs, and should thus give:

Thick Leather
Thick Hide
Rugged Leather,
Rugged Hide.

Regards

**Comment by npmusicftw** [comment] 2015-09-28 21:34
[Silithus]
Dredge Strikers (#11740), Dredge Crushers (#11741)
[Un'goro]
Gruff (#6583)

 http://www.wowhead.com/npc=11741/dredge-crusher#skinning

**Comment by Rushor** [comment] 2016-11-15 18:45
the issue also affects all these creatures:

```sql
(659, 'El Pollo Grande');
(2707, 'Shadra');
(4242, 'Frostsaber Companion');
(4243, 'Nightshade');
(5347, 'Antilus the Soarer');
(5440, 'Tamed Crocolisk');
(6582, 'Clutchmother Zavas');
(6583, 'Gruff');
(6648, 'Antilos');
(7376, 'Sky Shadow');
(8024, 'Sharpbeak\'s Father');
(8025, 'Sharpbeak\'s Mother');
(8204, 'Soriid the Devourer');
(8302, 'Deatheye');
(8303, 'Grunter');
(8925, 'Dredge Worm');
(8932, 'Borer Beetle');
(9032, 'Hedrum the Creeper');
(10177, 'Spire Scarab');
(10204, 'Misha');
(10376, 'Crystal Fang');
(10596, 'Mother Smolderweb');
(10619, 'Glacier');
(10717, 'Temporal Parasite');
(10979, 'Scarlet Hound');
(10988, 'Kodo Spirit');
(11181, 'Shi\'alune');
(11374, 'Hooktooth Frenzy');
(11671, 'Core Hound');
(11672, 'Core Rager');
(11710, 'Mirador');
(11740, 'Dredge Striker');
(11741, 'Dredge Crusher');
(11885, 'Blighthound');
(11896, 'Borelgore');
(11897, 'Duskwing');
(12124, 'Great Shark');
(12125, 'Mammoth Shark');
(12803, 'Lord Lakmaeran');
(13160, 'Carrion Swarmer');
(13178, 'War Rider');
(13221, 'Ryson\'s Eye in the Sky');
(13618, 'Stabled Frostwolf');
(13676, 'Stabled Alterac Ram');
(13916, 'Dire Maul Crystal Totem');
(14283, 'Stormpike Owl');
(14344, 'Mongress');
(14476, 'Krellack');
(14477, 'Grubthor');
(14566, 'Ancient Equine Spirit');
(14568, 'Darkreaver\'s Fallen Charger');
(14732, 'PvP CTF Credit Marker');
(14943, 'Guse\'s War Rider');
(14944, 'Jeztor\'s War Rider');
(14945, 'Mulverick\'s War Rider');
(14946, 'Slidore\'s Gryphon');
(14947, 'Ichman\'s Gryphon');
(14948, 'Vipore\'s Gryphon');
(14965, 'Frenzied Bloodseeker Bat');
(14986, 'Shade of Jin\'do');
(14988, 'Ohgan');
(15041, 'Spawn of Mar\'li');
(15114, 'Gahz\'ranka');
(15172, 'Glibb');
(15204, 'High Marshal Whirlaxis');
(15220, 'The Duke of Zephyrs');
(15316, 'Qiraji Scarab');
(15338, 'Obsidian Destroyer');
(15718, 'Ouro Scarab');
(22556, 'Guse\'s War Rider (1)');
(22563, 'Ichman\'s Gryphon (1)');
(22564, 'Jeztor\'s War Rider (1)');
(22566, 'Mulverick\'s War Rider (1)');
(22570, 'Slidore\'s Gryphon (1)');
(22593, 'Vipore\'s Gryphon (1)');
(22594, 'War Rider (1)');
(22686, 'Ryson\'s Eye in the Sky (1)');
(22764, 'Stabled Alterac Ram (1)');
(22765, 'Stabled Frostwolf (1)');
(22767, 'Stormpike Owl (1)');
(32098, 'Stormpike Owl (2)');
```

**Comment by Rushor** [comment] 2016-11-15 20:24
DB/Skinning: Thick Leather, Thick Hide, Rugged Leather, Rugged Hide - Update template for all creatures `>= level 48 with wrong skinninglootentries

* closes https://github.com/dalaranwow/dalaran-wow/issues/2770
* commit: 642231238607a6c1d5187434e24046804e9b911a

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-15 20:24 UTC
Labels: Continent - Classic, On PTR

**Comment by TeridanDW** [comment] 2017-04-01 20:03
Works as intended on ptr.
