### ISSUE TITLE
"Invalid Target" bug

### ISSUE THREAD

**Issue by ionut028** [dalaranwow/dalaran-wow#5752] opened 2019-06-30 19:46 UTC
No matter what I do I get a "Invalid Target" after killing a NPC on any paladin I create, it happens I changed realmlist to Wow-mania, not the same experience, but the client I've downloaded is the one on Dalaran Wow website.

I've tried some settings that gets that error away but noise is really annoying you can't get rid of that. You kill something, you get that freaking noise again.

**Comment by Chenocide** [comment] 2019-06-30 21:02
Backup your WTF folder and cache and delete both of them. This seems more like a client-side issue than a server-side problem. If deleting those folder didn't help, then I'm out of suggestions.

**Comment by Golganeth** [comment] 2019-07-04 20:10
Hey @ionut028,
This is definitely not a server-side issue. This is what I usually answer to players with client-side issues, follow the steps and your issue should be solved.

- Disable all of your addons check if it still happens. If that was indeed the problem I'd suggest you to enable them one by one, so you can easily detect which addon was giving you trouble.

-----------

 If the issue persists:
- You can clear your Cache folder (this might fix small minor issues and it's pretty quick to do). Try also clearing your WTF folder as @Chenocide suggested, you will lose your settings but it can potentially fix the problem as a last option.
- At this point if nothing has worked, it's most likely that your client has corrupted files so you should re-install the game from scratch. You can get our game client again [here](https://www.sendspace.com/file/oa29kz)

Closing up since the issue is on your side.

**Closed by Golganeth** 2019-07-04 20:10 UTC

**Comment by Chenocide** [comment] 2019-07-04 20:35
If you end up clearing your cache and WTF folder, then do a backup first. If it doesn't fix your problem, then you'll still have your settings.
