### ISSUE TITLE
[Quest][Northrend] Know no fear - Teleport issue

### ISSUE THREAD

**Issue by styled81** [dalaranwow/dalaran-wow#5065] opened 2017-11-12 15:07 UTC
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
After acceptping the quest i should use the teleporter to transfer to the other transporter, this does not happen. Also the suicide goblins should attack the cave but they are idleing and doing nothing.

Minor bug, the quest before this one. i picked up the powercell from a death goblin, the goblin was dead but his corpse was still walking arouund.
**Expected behaviour**: Tell us what should happen instead

Know no fear,
https://www.youtube.com/watch?v=5Yq-DMrsG5o

the first 20seconds illustrate what should happen. you go threw the teleporter and the goblins should attack the cave.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=5Yq-DMrsG5o

http://www.wowhead.com/quest=12822/know-no-fear

**Comment by Rushor** [comment] 2017-11-12 15:38
Please ignore the missing event with the goblins for now - the missing teleport action is fixed now

**Closed** 2017-11-12 15:37 UTC
Labels: Area - Northrend, Fixed - Waiting for PTR update, General - Quests

**Comment by TeridanDW** [comment] 2017-11-12 17:20
Teleportation works as intended on PTR.
