### ISSUE TITLE
[Achievement] City Defender

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#904] opened 2013-10-13 18:33 UTC
**Achievement City Defender** - _(ID:1006 / 388)_
- **Issue present:** Achievement conditions are wrong and the achievement will be obtained (will pop for people) if you simply just kill any unfriendly target in the entire City.
- **How it should work:** Achievement should only be obtainable if you kill Players in PvP combat, and not critters, unfriendly npcs.

The ticket I got today was: 
_Hey dear team, After killing 50 deer's in darnassus i got the achievement[City Defender]: "Kill 50 enemy players in any of your home cities"_
---

http://www.wowhead.com/achievement=1006/
http://www.wowhead.com/achievement=388

**Comment by Rushor** [comment] 2016-11-09 20:12
Scripts/World: Achievements - City Defender

* do not reward credits to non-playing-characters
* closes https://github.com/dalaranwow/dalaran-wow/issues/904
* commit: 15e6fcbac717721c69398c1e847b7b16c1871658

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-09 20:12 UTC
Labels: Achievements

**Comment by Chenocide** [comment] 2019-06-27 21:34
Seems like it's currently impossible for horde characters to receive credit in Undercity for killing lvl 80 alliance characters. Will give the other horde cities a try too.

**Comment by Chenocide** [comment] 2019-06-28 12:29
I'm not getting credit for killing level 80 alliance characters in Orgrimmar, Undercity and Thunder Bluff and can only assume that the achievement is more broken than what was initially stated in this report. It's possible that the fix that Rushor did, is not enough to solve the issue.
