### ISSUE TITLE
[NPC] Highvale Marksman, Highvale Outrunner, Vicious Owlbeast unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1260] opened 2014-02-22 17:25 UTC
Highvale Marksman (http://wotlk.openwow.com/npc=2693),
Vicious Owlbeast (http://wotlk.openwow.com/npc=2927), and
Highvale Outrunner (http://wotlk.openwow.com/npc=2691) cast none of their abilities.

**Comment by Rushor** [comment] 2016-11-14 21:09
DB/Creature: Add abilities for Highvale Marksman, Vicious Owlbeast and Highvale Outrunner

* closes https://github.com/dalaranwow/dalaran-wow/issues/1260

"Highvale Marksman - In Combat - Cast 'Multi-Shot'"),
"Highvale Marksman - In Combat - Cast 'Shoot'");
"Vicious Owlbeast - In Combat - Cast 'Fatal Bite'");
"Highvale Outrunner - In Combat - Cast 'Shoot'");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment] 2017-04-06 12:49
Works as intended on ptr, however there is an issue with:
 - spell http://wotlk.openwow.com/spell=7938 has now effect and some "hidden" cooldown, i think.

**Comment by Rushor** [comment] 2018-03-19 09:29
ah yes it can only be casted at: TargetAuraState = 2 (AURA_STATE_HEALTHLESS_20_PERCENT)

**Comment by Rushor** [comment] 2018-03-19 09:37
> Vicious Owlbeast's melee swing hits Bushcraft for 89 Physical.
> Vicious Owlbeast's attack misses Bushcraft.
> Vicious Owlbeast's Fatal Bite hits Bushcraft for 243 Physical.(97 Overkill)
> Bushcraft died.

```sql
(@ENTRY,0,0,0,12,0,100,0,0,20,3000,18000,11,7938,2,0,0,0,0,2,0,0,0,0,0,0,0,"Vicious Owlbeast - Target Between 0-20% Health - Cast 'Fatal Bite'");
```

**Closed** 2018-03-19 09:37 UTC
Labels: Area - Classic, Fixed - Waiting for PTR update
