### ISSUE TITLE
[Quest][Northend] Dun-da-Dun-tah!

### ISSUE THREAD

**Issue by Exorcista** [dalaranwow/dalaran-wow#1996] opened 2014-10-20 18:11 UTC
The following quest http://www.wowhead.com/quest=12082/dun-da-dun-tah, is working, but not as intented and may bug in the scort process and cannot be completed.

<b>::How is working:</b> you start the escort on the cage, then when u get to the chamber when he frees the prissioner and sumons the Snake, the entrance is on fire, but he still is targetable, then when he sumons the snake you can go in, but after defeating the snake, you either go out really fast or get stuck inside the chamber because the fire will get you there unable to continue the scort and failing the quest.

<b>:: Video of How Should it Work: </b> https://www.youtube.com/watch?v=p-Hdtt0Nu9M

i guess has something to be with the timer of the fire. Cheers.

**Comment by Rushor** [comment] 2016-11-26 21:29
getting stuck depends on the case if someone already died the evnt before you or not. the door shoud always be opened, even if someone did the event before you.

**Comment by Rushor** [comment] 2016-11-26 21:39
DB/Quest: Dun-da-Dun-tah! - Harrison Jones now always opens the firedoor on eventstart

* also fixed the questgiverflag (it should always be available after respawn now)
* also fixed the texttargeting (name and race of the player should be displayed correctly now)
* closes https://github.com/dalaranwow/dalaran-wow/issues/1996
* commit: 4d1aedef8d77737ace82e2618536aa99100d732f

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-26 21:39 UTC
Labels: Continent - Northrend, On PTR, Quests

**Comment by roblockster** [comment] 2017-05-13 08:52
The quest worked fine for me until the end but the objective does not complete and the quest cannot be turned in to Harkor.

**Comment by TeridanDW** [comment] 2017-10-29 09:19
Works as intended on PTR.
![image](https://user-images.githubusercontent.com/6797611/32142219-f46a8012-bc9a-11e7-80e7-d1c6ac6b78a5.png)
