### ISSUE TITLE
[Quest][Outland] Fel Spirits 10909

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#786] opened 2013-09-17 15:24 UTC
http://www.wowhead.com/quest=10909/fel-spirits#.

The problem:
After killing orcs near the stone which appears after using the given device, spirits do not appear, so you can't kill them, and the quest can not be completed.

How it should work:
Probably like in this video: http://www.youtube.com/watch?v=rHBirulrogI - "sparks" or "electric lines" from the stone should hit the orcs, and after you kill an orc, a spirit should appear, which you should be able to kill in order to get credit.

**Comment by Rushor** [comment] 2016-11-27 14:27
DB/Quest: Fel Spirits - Summoned Fel Spirits should attack the player + every killed orc should release one spirit now

* closes https://github.com/dalaranwow/dalaran-wow/issues/786
* commit: 4c1f5a6fe38e7de16c479f495c8b57e293539e41

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Closed by Rushor** 2016-11-27 14:27 UTC
Labels: Continent - Outland, On PTR, Quests
